### ISSUE TITLE
Pure SSH-based protocol

### ISSUE THREAD

**Issue by gully** [git-lfs/git-lfs#1044]
I would like to push git lfs changes via SSH, but this doesn't seem to work "out of the box".  Specifically, I have two remotes: one with https (_origin_, i.e. GitHub) and one with ssh (_alternate_, i.e. a local computer not generally accessible to the web, only ssh).  When I set up git-lfs, the https remote is fine, but I can no longer push to the ssh branch:

``` bash
$ git push alternate master
Git LFS: (0 of 2 files) 0 B / 450.17 KB
exit status 127
error: failed to push some refs to "foo@000.000.000.000:home/blah.git"
```

``` bash
$ git lfs push alternate master
Git LFS: (0 of 2 files) 0 B / 450.17 KB
exit status 127
```

I suspect this Issue is related to Issues #295, and its Pull Request #350, and maybe #798 

Will it be possible to have git-lfs work with existing ssh remotes "out of the box", like https?  Is the currently supported solution to run `git-lfs-ssh-serve` on the remote?  I have not been able to experiment with the `git-lfs-ssh-serve` yet.  Forgive me if this is a naive or duplicate question, or unique to my setup.  Thanks!

**Comment by technoweenie** [comment]
Git LFS doesn't support SSH as a transport protocol. So, as a <del>hack</del> workaround, it executes a `git-lfs-authenticate` command through SSH, which should return JSON. Unfortunately, this isn't really documented that well. Here's [the JSON struct that it needs to return](https://github.com/github/git-lfs/blob/81563f2c085c9ad7b3a98f270f57f6ec19844feb/lfs/ssh.go#L15-L17). Here's a live example:

```bash
$ ssh git@github.com git-lfs-authenticate github/git-lfs download
{
  "href": "https://api.github.com/lfs/github/git-lfs",
  "header": {
    "Authorization": "RemoteAuth monkey"
  },
  "expires_at": "2016-02-25T17:42:24Z"
}
```

This gives the URL and necessary header value to access the LFS API. Not only would you have to implement this `git-lfs-authenticate` script, but you'd have to setup some kind of LFS server somewhere to communicate with the client.

**Comment by gebi** [comment]
@technoweenie we also needed that feature, thus we removed all user handling from git-lfs-testserver and added the necessary infrastructure to support authentication through JWT tokens from gitolite (in our case).

https://github.com/mgit-at/lfs-test-server/tree/master/git-lfs-authenticate

**Comment by MrShadowGames** [comment]
Any update on this yet?

**Comment by ttaylorr** [comment]
> Any update on this yet?

Not yet.

**Comment by laoshaw** [comment]
please support git lfs push via ssh, git push over ssh is widely used.

**Comment by ioquatix** [comment]
We can't deploy via CI using ssh remote because LFS fails. It would be great if it would work.

**Comment by instantname** [comment]
The git-lfs-authenticate workaround is not practical in many cases. Often, it makes sense to keep the LFS repository on the same server as the Git repository. After all, both paths correspond to pieces of the same project... For servers that only allow SSH access for security reasons, you are screwed.
To me, SSH support is a necessity in order to be consistent with Git's capabilities.

**Comment by jeffguorg** [comment]
+1, please support push via ssh

**Comment by seitzbg** [comment]
+1, this feature is very basic and necessary!

**Comment by gebi** [comment]
yes, please add git-lfs push/pull support through ssh.

The biggest problem currently with git-lfs is that it is not symetric in the port usage to git itself. Which makes it a pain in the ass in eg. enterprise deployments because for many uses git works (ssh) but git-lfs does not work because of firewall rules.

**Comment by PaulStegler** [comment]
We need this feature. It's silly not to support it.

**Comment by Arkezis** [comment]
Please, we need this :)

**Comment by frankbenoit** [comment]
Not having this is bad for whole git. Because it a non optional feature in many setups, but it adds inconsistency.

**Comment by frankbenoit** [comment]
I mean git-lfs as tool is non optional in many cases.

**Comment by ttaylorr** [comment]
Thank you, everybody. I have noted everyone's request of this feature, and will try and find time to work on this in the future. I will update this thread when there are updates to be shared.

**Comment by sudomateo** [comment]
+1 for git-lfs using SSH remotes

**Comment by Yuhe-Wang** [comment]
Please, we need this feature badly! Git-lfs-authenticate is not working on customized gerrit server.

**Comment by KiritsuguKun** [comment]
+1 highly needed feature. Maybe any updates on this?

**Comment by joel23888** [comment]
+1 for git-lfs using SSH remotes

**Comment by gerroon** [comment]
pretty please, otherwise this whole git lfs thing is alocal gimmick :(

**Comment by ioquatix** [comment]
I gave up on `git-lfs` because without this feature it is too limited.

**Comment by instantname** [comment]
@gerroon Agreed. Although the whole idea of git-lfs is appealing, I could not implement it for any practical use because of this issue.

**Comment by gerroon** [comment]
yeah I hopethat  the Gitea devs find time to implement this.

**Comment by ttaylorr** [comment]
Thanks for the continued interest. Someone from @git-lfs/core will be
sure to update this thread when we have made progress (if this is the
case).

**Comment by bk2204** [comment]
For those that are interested, there's a proposal for a pure SSH-based protocol in #3290.  I'd like to keep that discussion focused on the technical aspects of the proposal.

We're definitely aware that this is a highly desired feature.  I'm going to retitle this issue to make it a little easier for people to find, since I had a bit of trouble finding it myself.

**Comment by MisterJD** [comment]
+1 push via ssh

**Comment by yucolabjames** [comment]
After two hours of looking around for my missing files and encountering loads of misleading error messages, I only found out now that SSH is not supported for LFS....

Am being diplomatic when i say am very upset that this feature is missing.

**Comment by jvanderzouwen** [comment]
With 2FA enabled, LFS over ssh is dead at this point... prove me wrong

**Comment by jmcarter17** [comment]
+1, please support this.

**Comment by saracen** [comment]
Was any progress made on this? The proposed SSH protocol seems quite involved. I'd like to explore a alternative, and hopefully simpler solution if no work has commenced on this yet.

@bk2204 @ttaylorr

**Comment by bk2204** [comment]
We haven't implemented this yet, no. What were you thinking for a different solution?

**Comment by saracen** [comment]
I think an alternative would be to use the current HTTP API as is, but communicate the protocol over stdin/stdout with a remote running SSH command that then proxies to the regular HTTP backend.

Ordinarily, this would be hard to achieve whilst satisfying the requirements in your proposal, but if we look to HTTP/2 instead, which is designed to use a single connection and multiplexes requests, it should work very well.

Go makes it pretty easy to do this. We could provide a `git-lfs-api` binary for other implementers to use, as there's likely to be very little custom logic as all normal authentication flows would also be supported without modification.

I was planning on providing a demonstration of this, as in theory it's as simple as using a custom http.Transport specifically when you decide to route traffic via an SSH command... but I've found the LFS client to be not very accommodating to this change. I could put together a simplified example though, if there's any interest in this?

**Comment by bk2204** [comment]
I considered using plain HTTP, but unfortunately there are some limitations to doing that:

- We can't assume that server implementations speak HTTP/2, and if there are server implementations that don't, we essentially make them unusable with Git LFS over SSH. Implementing HTTP/2 is very significantly more complicated than HTTP/1.1; the former will almost always require some sort of compiled code, while the latter is usually implementable using the standard library in most scripting languages.
- The authentication in SSH happens at the beginning of the connection, not at each individual request. The only analogue for doing that in HTTP is NTLM, which authenticates the entire connection, not each request; this surprising behavior is actually the basis for a variety of security bugs.
- We end up sending a lot of data over the connection that is redundant by using HTTP. We neither need nor want a Host header, for example. We also don't want to receive or accept a Location header, as that could be a source of security problems.
- Go's HTTP library is not really designed to work over this kind of transport. We can't use HTTP/2 without TLS, for example. Moreover, most languages are not designed to handle HTTP data over non-TCP connections.

The protocol I've proposed is designed to easily map to HTTP and reuses a lot of the same techniques (e.g. status codes and headers) without sending a lot of the redundant data we don't want. It does look complicated because of the grammar, but the mapping is relatively simple. It also uses the same syntax primitives (pkt-line) that are already in use in Git servers, so adding support for it should be relatively easy for server-side implementations.

**Comment by saracen** [comment]
> We can't assume that server implementations speak HTTP/2

I agree. Whilst HTTP/2 has seen decent adoption, it might still be a hurdle. However, as I mentioned, I think this is fine as long as the solution provided is usable by everybody. The solution being a `git-lfs-api` binary that handles HTTP/2, without the upstream server needing to understand it yet.

> The authentication in SSH happens at the beginning of the connection

The SSH authentication in this scenario is effectively only allowing the end-user to proxy LFS data to a specific upstream. All other authentication is handled per request, transparently tunneled. I still envision that the client would perform a request for `git-lfs-authenticate`, to then use those credentials with the proxied connection.

> We end up sending a lot of data over the connection that is redundant by using HTTP.

This and the other issues are present in the current API that I cannot imagine will be disappearing any time soon. HTTP/2 also supports header compression, though. I don't think the overhead of headers would be an issue.

> Go's HTTP library is not really designed to work over this kind of transport. We can't use HTTP/2 without TLS, for example. Moreover, most languages are not designed to handle HTTP data over non-TCP connections.

It can work without TLS, documented as `h2c` (HTTP/2 over TCP, rather than over TLS). It may well be true that it's difficult to emulate a TCP connection over stdin/stdout and support `h2c` in other languages though.

I added support for this to the LFS client earlier today and borrowed functionality from my https://github.com/saracen/lfscache project (with caching disabled) to implement the proxying over stdin/stdout. To proxy the actual batch downloads, the URLs to them need to be rewritten (which lfscache already does, so that the client hits the cache, rather than the remote S3 server etc.). There's a few complications with this approach; confusing log output (about what a HTTP GET request is really doing) and the entry-point into this functionality isn't super clear, but it was mostly my first stab at hooking up the end-to-end communication and get some files being transferred. I'll try to push a branch this week in case others are interested.

**Comment by benchada** [comment]
+1 for implementing lfs through ssh .. please share with us if any updates. Thanks!

**Comment by saracen** [comment]
@bk2204 I take it my response to your concerns wasn't enough to sway your thoughts on the direction of HTTP2 over SSH?

**Comment by gebi** [comment]
awesome :)!
Many THX for starting the implementation of LFS over pure ssh!

**Comment by bk2204** [comment]
No, my opinions on this haven't changed since we discussed it last.  I still think HTTP/2 over SSH isn't the right way forward.

**Comment by saracen** [comment]
@bk2204 Just to make sure, did you read my reply to your previous concerns and get a chance to look at the associated PR? Your first reply seemed to suggest you were confused over what I was proposing, so I was hoping my comments and PR would help there and that there would be around round of discussion.

**Comment by bk2204** [comment]
Yes, I've looked at the PR.  This PR works decently for the client side of things, but it makes non-Go implementations very difficult, because HTTP/2 libraries are usually over a TLS connection, not an SSH connection.  We have alternate client implementations that do not use Go, and we have server implementations that don't use Go.  I can imagine this being difficult to implement server-side in Java, for example.  It will also likely be difficult to implement with existing HTTP/2 implementations in Rust as well.

I still think it's too early to assume that everyone has implemented HTTP/2, since multiple major hosting providers don't have public HTTP/2 support over HTTP.  In addition, if we're going to design a protocol, I'd like to avoid having to make multiple SSH requests, one each for authentication and data, since doing so can prompt the user for each request (e.g. with SSH keys on a smart card).

In addition, while using HTTP/2 support is an easy way to get support, I don't think it's elegant from a protocol design perspective.  For example, how do we handle a redirect?  How do we handle it if the server tells us we should downgrade to HTTP/1.1?  There's a lot of additional functionality in HTTP/2 (and just HTTP) that we neither need nor want and the error handling necessary to deal with all of these edge cases and make sure we don't introduce a security hole is going to be complex.  It introduces a whole new security model for SSH, which I don't really want.

**Comment by saracen** [comment]
I think there's many libraries that support H2C. It's part of the HTTP2 specification, and whilst I'm not 100% sure, I doubt libraries would purposely *not* implement the cleartext version. I suspect the HTTP/2 protocol is identical in either case, and the only difference is the initial negotiation and the transport used.

I don't think the H2C part would be an issue. It might perhaps be harder to pipe it over anything, as we're doing in this case with an SSH connection. But that's a guess and I don't think not knowing right now immediately kills this idea.

> I still think it's too early to assume that everyone has implemented HTTP/2

My PR and the server side implementation doesn't expect the host to support HTTP/2. The server side component is a binary that handles that HTTP/2 protocol, but doesn't expect the upstream server to support it.

The requirement of users here is SSH support for accessing LFS. We're not really designing a new protocol. My PR purposely doesn't touch much at all. Resolving the flaws of the current design, that may use multiple SSH requests is beyond its scope. It might be that there's an alternative solution there, but the last time I looked at this was in April, so I'm can't recall entirely how that works.

The SSH authentication and connection is effectively allowing communication to be proxied. This HTTP client is no more vulnerable to attacks than your existing HTTP client, because they're exactly the same implementation. The LFS server is also exactly the same server you'd already be communicating with. The difference is the binary acting as a transparent HTTP proxy, and in the example I've provided, all this does is rewrite the data URLs to enforce they go through the proxy - any other endpoint is dropped. I don't believe it adds any new security concerns, and if it does, I'd love to know, as it means my LFS caching server is also vulnerable. 

Given how little this should change client-side, is it not worth exploring further? It doesn't mean there cannot be an alternative in the future. Users that require the SSH support can opt-in to use "h2ssh", rather than it being something that is rolled out to everybody automatically. Github doesn't even need to support it server side. For users running their own Git LFS server, this modification would simply allow them to drop a binary onto a system that proxies connections. If Github do wish to support it, that'd be great and it'd be awesome to pull other developers into this discussion that would be responsible for writing the `git-lfs-tunnel` binary.

**Comment by alexchandel** [comment]
Many self-hosted Git servers only support SSH, not HTTP ([like this](https://www.stevestreeting.com/2018/11/29/self-hosting-vanilla-git-on-a-synology-nas/)).
Wrapping HTTP/2 in SSH isn't the answer when SSH already provides authentication and transfer.  Just write the files in series.

Is there any progress on this, beyond punting to [lfs-folderstore](https://github.com/sinbad/lfs-folderstore)?

**Comment by bk2204** [comment]
There isn't any change in the status.  We'll update the issue if there's any change.

**Comment by saracen** [comment]
> Many self-hosted Git servers only support SSH, not HTTP ([like this](https://www.stevestreeting.com/2018/11/29/self-hosting-vanilla-git-on-a-synology-nas/)).
> Wrapping HTTP/2 in SSH isn't the answer when SSH already provides authentication and transfer. Just write the files in series.

The current proposal for SSH support is here: https://github.com/git-lfs/git-lfs/blob/master/docs/proposals/ssh_adapter.md

That proposal, and my own, both use SSH's authentication. For transfer, a different protocol is used in both instances. One protocol is the pkt-line-HTTP-over-SSH and the other is HTTP2-over-SSH. In terms of protocol alone, @bk2204 has some reasons as why HTTP2 isn't suitable (1) a belief that it will be harder to implement in other languages, and 2) a misunderstanding that the hosted server will need to support HTTP2), but ignoring those potential issues, I don't think HTTP/2 over SSH is any more of an issue than the alternative.

**Comment by jmnielsen7** [comment]
@bk2204 
> There isn't any change in the status. We'll update the issue if there's any change.

I'm just now jumping into this conversation. Where can we track the progress. Is #3290 still being used, or was that only for the initial proposal?

P.S. We have a situation where authentication needs to rely on SSH keys for git lfs.

**Comment by bk2204** [comment]
As mentioned, nothing has changed.  The proposal has been written, but it hasn't yet been implemented.  The amount of work to do so is non-trivial and will touch a lot of code.

It's already possible to use SSH keys for authentication.  The current technique performs authentication over SSH and gets a token that can be used to talk to the HTTP API.  The only thing that's outstanding is a protocol that doesn't use HTTP at all and operates completely over an SSH connection.

**Comment by Manni79** [comment]
Hello, after getting error on push after needing hours to get git working on a Synology Diskstation with ssh access I bump into this issue.
Perhaps someone here is knowing Synology Diskstation. As I understand, it uses its git server over ssh. Ans that's the problem with lfs when I understand it correclty.
DSM Git ssh info: https://www.synology.com/de-de/knowledgebase/DSM/help/Git/git

Because of that git-lfs-authenticate error some at push. Has someone a solution and can me explain in detail (with an example :-)), what I can change to make git on the diskstation work over ssh with lfs support? Or what I can do on client side?

Would be nice to find a solution. Need lfs because of a lot of binary files. 
thanks a lot!

**Comment by bk2204** [comment]
The Synology NAS likely won't support Git LFS, even when we have a full SSH-based protocol.  The NAS would need to support the future SSH-based protocol natively and just because it has a Git server doesn't mean it will support the Git LFS protocol.

**Comment by Manni79** [comment]
Thank you for these clear advice. So I can stop to try nearly everything. I read tons of web sites and tutorials. Also official page: https://git-lfs.github.com
No one (or mostly no one) speaks about what requirements git servers must have for using lfs and how they can easily be checked. I found most new information after getting next errors.
So I know I have to stick to svn or to another solutions.
Thanks a lot! Would nice if Synology or "git server" or whoever ... can change something that git-lfs can also run on Synlogoy. I think it's beside qnap the biggest NAS provider. So should be needed.

**Comment by csingh27** [comment]
So the conclusion is that LFS does not work over SSH, or have I missed some conversation ?

**Comment by bk2204** [comment]
Currently it's possible to use Git LFS with SSH remotes because authentication happens over SSH and then the actual data transfer happens over HTTP or HTTPS using credentials acquired over the SSH connection.  However, Git LFS doesn't offer a native SSH-based protocol that doesn't require HTTP operations at the moment, which is what this issue is tracking.

**Comment by forresthopkinsa** [comment]
The proposal immediately dismisses SFTP, but that seems like a mistake to me. From a layperson's perspective, it looks like SFTP would drastically reduce the amount of work required for this feature.

Can someone explain why SFTP is an insecure option?

> each access (upload or download) must have an access control check instead of one at the beginning of the operation

Why isn't this a problem for e.g. the interactive sftp console packaged with SSH?

**Comment by bk2204** [comment]
> The proposal immediately dismisses SFTP, but that seems like a mistake to me. From a layperson's perspective, it looks like SFTP would drastically reduce the amount of work required for this feature.
> 
> Can someone explain why SFTP is an insecure option?

Most hosting providers use a single account (e.g., `git`) for all uploads and downloads.  If a user invokes a shell command, access control is checked at the beginning of that shell command invocation; if the process is not allowed, then the command channel is rejected.  Access control is checked based on the repository name passed to the command.

With SFTP, you basically have a file system that you can access.  You spawn a single SFTP server process and manipulate any files you want on the remote system.  The root is not restricted by a single repository name, so you're going to have to check access control on each file, which is expensive unless the kernel is doing it for you (which it is not in this case).

It is, of course, possible for your own server to mount the remote via sshfs (which uses SFTP) and push to it like a local server.  That has been supported since local pushes came in with 2.10.

> > each access (upload or download) must have an access control check instead of one at the beginning of the operation
> 
> Why isn't this a problem for e.g. the interactive sftp console packaged with SSH?

Because multiple untrusted users don't share access via a single username.

**Comment by forresthopkinsa** [comment]
> It is, of course, possible for your own server to mount the remote via sshfs (which uses SFTP) and push to it like a local server. That has been supported since local pushes came in with 2.10.

This is the key, then. Thanks!

**Comment by bk2204** [comment]
There is a draft PR in #4446 where work on this is ongoing.  I have no hard timeline for completion, and I want to point out that just because the client adds support for this does not guarantee that any implementer, including GitHub, will add support for it at any given point or ever.  Questions about what a given implementer's plans are should be addressed directly to that implementer, not here.

If you have questions or comments about the work as it's being done in the client, let us know.

**Comment by NightMachinary** [comment]
[**@forresthopkinsa**](https://github.com/forresthopkinsa) commented on [Aug 20, 2020, 9:42 AM GMT+4:30](https://github.com/git-lfs/git-lfs/issues/1044#issuecomment-677096092 "2020-08-20T05:12:56Z - Replied by Github Reply Comments"):
> > It is, of course, possible for your own server to mount the remote via sshfs (which uses SFTP) and push to it like a local server. That has been supported since local pushes came in with 2.10.
> 
> This is the key, then. Thanks!

Beware that `sshfs` can be buggy.

**Comment by hilbix** [comment]
TL;DR

Telling us, that `sftp` does not support proper access control is just plain wrong.

So I do not understand the arguments against `stfp`.  You can even translate HTTP PUT/GET into SFTP commands using some simple BASH proxy scripts.  So where is the problem?

-------

I don't understand the problem with `sftp`.  You can restrict access control based on `~/.ssh/authorized_keys`' `command=` feature without any trouble at all.

That nobody has done it yet (written no such `sftp-server` command) does not say it is impossible.  I even think it is very very easy to do so.

In contrast, your approach needs complex changes to add ssh-based-authentication PLUS even opening a hole to some additional transport.  This IS a much bigger problem than suppying just something like a simple `sftp-server`.

And even yourself note, that **this not needed for people**, who run their own local ssh-based `git` service, if they just trust themselves.  But with your approach, **those need to add all your bloat** even if they do not need any additional access control!

For example, if you want to run GitLab securely, you must close down the HTTP(S) port.  As running GitLab with HTTPS exposed to something like a hostile Internet is was just too dangerous, is just too dangerous, and there are absolutely no signs that in future those GitLab people manage to not implement additional highly critical bugs into their HTTPS frontend (and it may even stem from Rails).

Exposing `ssh` is not only much more secure than exposing GitLab or Ruby or PHP or whatever, there are also various known ways how to keep the `ssh` port closed, like Port Knocking.  The good part here is, that `git` or other commands which use `ssh` as transport, do not even need to know how to handle this added security, as this already is handled by the `ssh` library transparently (as long as you do not use Eclipse, I think.  IntelliJ does it better).

You do not even need to use something like `sftp-server` (you can write your own script or binary), but I recommend `sftp`, as `sftp` is already built into `ssh`, and many many many people out there can use it for their purpose, for example on their NAS boxes out of the box.

And for instances like GitLab it would be easy to implement some sftp-like subsystem which restricts access to the allowed repositories in question.

For example in Linux there are filesystem namespaces.  You can setup those easily on-the-fly based on the database access permission, and cage those sers into that using a chroot-able `sftp-server`.  Nothing of this needs to be left to others like GitLab, as this all already is readily available in Linux distributions.  All implementors like GitLab need to do is to setup the namespaces properly.  The rest can be handled by the Kernel and your standard distribution.  It takes only a fraction of a second to setup and for bigger setups you can even cache the namespaces.

I do not know for BSD like OS, but I think BSD-jail is even more capable.

Now only Windows and MacOS are left.  But are there really productive setups out there running under MacOS or native Windows (in contrast to WSL these days)?  Do we really need to support them with some standard setup?  I would vote for:  We can go with a standard implementation for Linux and BSD and all others should fall back to plain `sftp` without restricting repository access.

FWIW:

I often do not run any `git` server at all.  All I use is some user account with a properly setup `authorize_keys` file.  This always was enough for `git` and should be enough even with git `lfs`.

Hence:

I'd recomment to think again and switch to `sftp`.

(I'd like to help, but I am not sure I find the time myself.  Sorry.)

**Comment by bk2204** [comment]
Hey,

A couple things to note.  First, SFTP is fine if you control a remote file system.  However, if you're looking at an infrastructure provider like GitHub or GitLab, authentication is done when the command is run, and at that point the repository must be known.  Since most hosting providers use an object store and not a real file system for implementing the server, if we used SFTP as the protocol, that would complicate things because access control for a particular repository would have to be checked as each access to each virtual file was being made, which would be substantially less efficient.  I can assure you that the performance would be much worse in that situation.

Also, implementing a file system protocol is very complex.  There are a lot of complex POSIX requirements that apply to file systems that are hard to emulate, so this leads to extensive complexity in the protocol.  I'm also not even sure if the SFTP protocol supports remote locking, which we absolutely need to have as part of the protocol.

So the answer is that we need an approach that works both for Git hosting providers, whether that's large ones like GitHub or individual ones like Gitea, as well as individual users with a remote server.  Fortunately, using a helper binary with a pkt-line based protocol is also what Git does, and we try to emulate Git whenever possible.

However, if you want to use SFTP for a server, there's an easy way to do that: you can use the SSHFS program to mount the remote SFTP file system locally and then just do a local push or fetch.  Git LFS already knows how to work with remotes on local file systems, so that situation works trivially, and this functionality works on any system supporting FUSE, which includes at least Linux, FreeBSD, NetBSD, and OpenBSD.  This is what I do in this situation and I can confirm it works well.

I also want to point out that it's essential that we support Windows and macOS natively here.  Whatever my or your personal opinions on those OSes, they are in fact a substantial portion of software developers, especially for games, where Git LFS is very valuable.  We try very hard in this project to make our code as portable as possible to support as many environments as we can.  Basically, if the OS has security support and we can find a way to legally install it (taking cost and hardware into consideration), we will try our best to support it if Git and Go do.

Hopefully that explains a little about why we've implemented this with the current design and how you can use SFTP if you want to.
