### ISSUE TITLE
RFC: move to LFS command

### ISSUE THREAD

**Issue by larsxschneider** [git-lfs/git-lfs#1077]
I wonder if would make sense to add a "move-to-LFS" command to LFS. As a MVP the command could just run git filter-branch under the hood (as discussed in https://github.com/github/git-lfs/issues/326). The main purpose for this command would not be repo migration (https://github.com/bozaro/git-lfs-migrate would be more suitable). The main purpose would be to fix a repo quick and easy if you accidentally added a file to Git instead of LFS.

Thoughts?

**Comment by javabrett** [comment]
Personally, I'd be concerned if there was a git-lfs command that quietly ran filter-branch and rewrote my history.  Assuming that the bad-commit containing the large file has already been pushed to an important repo, history will have to be rewritten, a forced push performed, and anyone who may have seen that commit will need to know how to deal with the rewound/rewritten head.

You'd want to repair this fairly quickly before the damage spreads - if the bad commit is not deep in the history, instead of using filter-branch, couldn't you just cherry-pick the bad-commit, export the large file to LFS, then cherry-pick any following-commits and force-push the fix, warning everyone ...

**Comment by larsxschneider** [comment]
I understand your concern. This command would need to come with a big warning about possible implications, of course.

However, I don't see the difference between a "filter-branch" rewrite and the "cherry-pick" rewrite that you suggested. AFAIK the result should be the same, no?

**Comment by technoweenie** [comment]
I think this would be awesome. It could work in conjunction with the pre-push hook to reject any git blob content on LFS file patterns in `.gitattributes`. Maybe it could detect potential problem files too, before they get pushed.

```bash
$ git push

Push failed:
* foo/bar/baz.mp3 matches "*.mp3" from .gitattributes, but is not stored in Git.
* foo/bar/baz.wav is over 10MB. Would you like to store it in LFS?
```

It could be a pretty safe command if it created branches to roll back.

**Comment by andyneff** [comment]
Additional ideas:

1. It could check that the commits that get rewritten were not committed (no remote tracking branches). This should help alleviate @javabrett's concern. If it HAS been pushed well... big warning message. It has to be done, in the end :-\
2. I'm thinking it should be the same functionality/syntax as git-lfs-migrate (at least as a starting point), only I'm guessing rewritten in go at some point? These tools seem to be working so far

**Comment by ttaylorr** [comment]
Hi everybody -- reading this old thread gave me a smile :-). I think that we are safe to close it, because we now have the following choices:

- `git lfs migrate info`
- `git lfs migrate import --include="*.mp3" --everything`
- `git lfs migrate import --no-rewrite`
- `git lfs migrate import --fixup --everything`
- `git lfs migrate export`.

I think that should do it 😉.
