### ISSUE TITLE
git lfs push --all fails with "open /FileRemovedInEarlierCommit.png: no such file or directory"

### ISSUE THREAD

**Issue by andyvn22** [git-lfs/git-lfs#1113]
When the server is missing files (due to a bug or migrating to new server or probably other reasons), it's my understanding that `git lfs push --all` will fix it. Problem is my attempts to run that result in `open /Users/andyvn22/Desktop/lfs-testing/LFS Testing/IrisApplication.png: no such file or directory`, where `IrisApplication.png` is an old file I deleted several commits ago, and the missing files are not uploaded to the server. Shouldn't the rest of the command complete, and why is it searching for that no-longer-existent file anyway?

**Comment by technoweenie** [comment]
It's searching for that file because it's in your Git history. The `git lfs push --all` command will only fix things if that deleted file's contents live in `.git/lfs/objects`. If you're migrating from one remote to another, you can run:

```bash
# this downloads ALL lfs objects from the old lfs server
$ git lfs fetch --all old-origin

# pushes ALL lfs objects to the new lfs server
$ git lfs push --all new-origin
```

The only way to truly remove a file in git is by rewriting history. Here's a guide that should help: https://help.github.com/articles/remove-sensitive-data/

**Comment by samskiter** [comment]
I've got the same issue, but I only have one remote. When I `git lfs push --all` some old, deleted files seem to stop the script from pushing all files....

**Comment by sprohaska** [comment]
To push all current LFS files, you can use the following workaround:

```
git lfs ls-files -l | awk '{ print $1 }' | xargs git lfs push --object-id origin
```

**Comment by mathstuf** [comment]
Just seen here as well without a migration case. Here's the setup:

```sh
#!/bin/sh

# Initialize the repository
git init
git lfs install --local

readonly remoteurl=…
readonly forkurl=…

# Add remotes.
git remote add origin "$remoteurl"
git remote add fork "$forkurl"

# Track *.lfs files.
git lfs track "*.lfs"
git add .gitattributes
git commit -m "commit lfs attributes"

# Fork the project. Send EOF to continue.
cat

# Fetch from the fork.
git fetch fork

# Emulate development on master.
git clone "$remoteurl" test-lfs
pushd test-lfs
git lfs install --local
git add other.lfs
git commit -m "add other.lfs"
git push origin HEAD
popd

# Try and sync origin/master with fork/master.
git fetch origin
echo "fork" > fork.lfs
git add fork.lfs
git commit -m "add fork.lfs"
# Trying to push ends up with `open …/other.lfs: no such file or directory`.
git push fork origin/master:master HEAD
```

Without doing the following, how can one get the push to work?

  - fetching all data (seems excessive)
  - checking out `master` and updating to `origin/master` (assumes that local `master` doesn't have existing development)

**Comment by ttaylorr** [comment]
> * checking out `master` and updating to `origin/master` (assumes that local `master` doesn't have existing development)

This seems good to me 👍 .

**Comment by mathstuf** [comment]
That was in the list of "we can't do this" :) . Part of our "push my branch to my fork" script we provide to help those with less Git-fu is to provide this script. Part of it also keeps their fork's `master` up-to-date with `origin/master`. However, we can't guarantee that the local `master` branch isn't modified and that a `git pull` on it is valid (nor that `git checkout master` would work due to local modifications).

**Comment by ttaylorr** [comment]
I think I misunderstood "updating"; are you able to merge in the changes from master?

**Comment by mathstuf** [comment]
I was referring to doing a `git checkout master && git pull origin master` kind of thing. Currently we just `git fetch origin`, but AFAICT, there's no way to fetch LFS data as part of that update as well without also changing the current branch.

**Comment by mathstuf** [comment]
I think the core issue is that LFS is trying to read from the disk (working tree) when looking at a given hash. There's no guarantee that the observed hash is currently checked out. Git-lfs should query the index or relevant tree object for the content of the file.

**Comment by ttaylorr** [comment]
@mathstuf, I see -- thanks for clarifying. I agree; and have milestoned this issue into the next release to reflect.

**Comment by bk2204** [comment]
I have a branch which improves this error message to make it more obvious what's going on.  The underlying issue is that we lack all of the LFS objects needed to push, and I'm not seeing a good way to work around that issue.

It may be the case that the origin server contains those objects, or it may not, and the user has experienced data loss; we don't know when doing a push.

The new error message will look something like the following:

```
Unable to find source for object 9c6e289cd9a56db4275851d92582979e80b7bb9568b7b08c31c108398ee8bbac (try running git lfs fetch --all): open /path/to/repo/file.txt: no such file or directory
```
