### ISSUE TITLE
git commit -v shows pointer but binary is committed

### ISSUE THREAD

**Issue by sgoo** [git-lfs/git-lfs#1167]
I'm not sure if this is a git bug, or a LFS bug but when I do `git commit -v` it shows me its adding the pointer data, but when I look at the commit its created its showing a binary file diff.

``` bash
$ mkdir lfs_test
$ cd lfs_test
$ git init
Initialized empty Git repository in /Users/sgoodhew/tmp/lfs_test/.git/
$ echo "*.bin filter=lfs diff=lfs merge=lfs -text" > .gitattributes
$ git add .gitattributes
$ git commit -m "add attrs"
[master (root-commit) 048e4ee] add attrs
 1 file changed, 1 insertion(+)
 create mode 100644 .gitattributes
$ dd if=/dev/urandom of=test.bin bs=1m count=1
1+0 records in
1+0 records out
1048576 bytes transferred in 0.076730 secs (13665787 bytes/sec)
$ git add test.bin
$ git lfs install --local
Updated pre-push hook.
Git LFS initialized.
# At this point when you look at the commit it shows pointer data
$ git commit -v
[master c8e3e23] Added LFS
 1 file changed, 3 insertions(+)
 create mode 100644 test.bin
$ git show | cat
commit c8e3e23c5cdc1088cfc0ff0cd109314173bb577e
Author: Scott Goodhew <sgoodhew@atlassian.com>
Date:   Fri Apr 22 16:40:13 2016 +1000

    Added LFS

diff --git a/test.bin b/test.bin
new file mode 100644
index 0000000..5375cac
Binary files /dev/null and b/test.bin differ
```

Given that it seem to be git showing me the correct thing, then committing the wrong thing I wasn't sure if this is a git bug, or maybe something to do with that `git lfs install` is doing things to the index?

Reproduced using
git 2.8.1
git-lfs built with go 1.5.3 using a pull from master today (db69cbdc)

**Comment by sinbad** [comment]
Tested this and confirmed it happens when you don't run `git lfs install` (without the `--local`) at least once after you install git lfs. 

You did run `git lfs install --local` but a) the `--local` only installs the pre-push hook in the local repo and b) it was after you ran `git add` anyway so it was too late. FWIW you only had to install the pre-push hook manually because you manually echoed the `*.bin` entry into `.gitattributes` instead of using `git lfs track "*.bin"`, which would have done it for you. 

Unfortunately at this point doing the global lfs filter install isn't automatic and there are no warnings - however you never actually ran any `git lfs` commands other than `install --local` so there wasn't really a place that would have happened. `git lfs track` would be a natural place in future for either doing it automatically or warning that it hasn't been done. 

The one thing I can't reproduce is the part "At this point when you look at the commit it shows pointer data". That doesn't happen for me unless at that point I run `git lfs install` *without* the `--local`. That installs the lfs filter, but at that point it's already too late because `git add` has already been run and the index already contains the binary data. However it might look like it's showing you pointer data because `git diff` will think that the file is modified again (provided the `stat()` picks it up, which it won't always in this scenario without `touch`ing the file because on disk it hasn't changed - `git lfs track` sorts this out if you do it though), because with the filter installed the clean filter would insert pointer data.

You might be wondering why git doesn't complain when you `git add` without the filter defined in `~/.gitconfig`. I think it's because all filters default to `required=false` so when the filter is missing it just gets ignored in git 2.8.

Anyhow, if I make sure I've run `git lfs install` before I run your test script everything is fine. We'll try to surface this missing info better in `git lfs track` in future, but that wouldn't have helped you because you didn't run any lfs commands before `git add`.

**Comment by sgoo** [comment]
To your first point about running `git lfs track` to solve this, I know my example seems kinda contrived, but the real world case where I hit this first was:

1. Didn't have LFS globally installed.
2. Cloned an LFS enabled repo.
3. Added a binary file with a pattern that was already tracked by .gitattributes.
4. run `git commit -v`, see that its committing as binary and abort.
5. Run `git lfs install --local`.
6. Run `git commit -v` Complete the commit because everything looks OK.
8. Realise that everything wasn't OK when git started pushing really large blobs.

I'm not sure why your not seeing the pointer data, Its not that `git diff` is detecting the change and show a diff with pointer data (I don't think it would show that anyway, it would just show "binary file changed") its that the commit "preview" you get with `-v` shows pointer data.

I'm leaning more towards this being a bug in git, that fact that it can show me one thing in `git commit -v` but create a commit of something else seems like a bug in git, but I wanted to get your thoughts first as I'm not sure how LFS interacts here.

**Comment by sinbad** [comment]
> the real world case where I hit this first was

Gotcha - yeah this is very hard to catch if you've never run `git lfs install`. SourceTree has a deliberate config check whenever you open (from clone or otherwise) an LFS repo precisely for this reason; unfortunately when you're just running Git commands on the command line we have no way to intercede early enough. 

> I'm not sure why your not seeing the pointer data, 

Sorry, when I checked out the diff I'd run `git lfs track` instead in this scenario instead of your `git lfs install --local`, my bad - in that scenario the LFS filter still wasn't there so it showed the binary. When you run `git lfs install --local` it installs the LFS filter config as well as the pre-push hook, but it puts the config in `.git/config` instead of `~/.gitconfig` (I was just looking at my gitconfig). So at that point, git's confused because it now has the filter config which it didn't before, but the index has already been updated. It seems that when it's performing `git diff --cached` or `git commit -v` it must re-run the clean filter which now succeeds, so it shows you pointer data, but when it commits I assume it just moves the index data as-is which is still binary. I guess that can be considered a git bug with filter usage since they're inconsistent.

**Comment by ttaylorr** [comment]
> We'll try to surface this missing info better in `git lfs track` in future, but that wouldn't have helped you because you didn't run any lfs commands before `git add`.

Unfortunately, I think that this is the best that we can do given the tools that we have, and modern version of Git LFS do do this.
