### ISSUE TITLE
Can't do `git clone` using HTTPS URL

### ISSUE THREAD

**Issue by SeanHayes** [git-lfs/git-lfs#1190]
A coworker was getting this error:
"Docs: https://github.com/contact Not Found"

after hanging for 10-20 minutes. It happened during `git lfs pull`, and persisted even during fresh clones of the project. Eventually we figured out it was because he used the HTTPS URL for our repo instead of the SSH URL.

**Comment by chasescot** [comment]
I actually believe someone got into my personal home network through Git but I can not be sure.    However I am positive that you have logs that would point to whoever did this. I am sure by mistake.   Could someone keep me posted....Probably not right?



Sent from my Samsung Galaxy smartphone.-------- Original message --------From: Seán Hayes <notifications@github.com> Date: 2016-04-28  9:41 PM  (GMT-07:00) To: github/git-lfs <git-lfs@noreply.github.com> Subject: [github/git-lfs] Can't do `git clone` using HTTPS URL (#1190) 
A coworker was getting this error:

"Docs: https://github.com/contact Not Found"

after hanging for 10-20 minutes. It happened during git lfs pull, and persisted even during fresh clones of the project. Eventually we figured out it was because he used the HTTPS URL for our repo instead of the SSH URL.

**Comment by technoweenie** [comment]
@SeanHayes If you're using an HTTPS remote, you'll want to set up [credential caching](https://help.github.com/articles/caching-your-github-password-in-git/).

**Comment by SeanHayes** [comment]
@chasescot I think you might be having a different issue.

**Comment by ttaylorr** [comment]
Hi, everybody. I am going to close this issue for now since it's not clear exactly what's going on here, and the issue is stale anyway (having last been updated a little over two years ago at the time of writing this comment.)

Please let me know if you are having any issues, and I'd be more than glad to help out and address them in a new issue. Thanks!
