### ISSUE TITLE
LFS trying to push change already on server

### ISSUE THREAD

**Issue by rjbell4** [git-lfs/git-lfs#1244]
In my testing and use of Git LFS, I've run into a situation where the LFS client is trying to push a change to the server that's already on the server.  My server implementation is Artifactory, but I don't think that's the factor at fault here (though it could contribute).  The situation more specifically is that I cloned from one Git repo, and I'm pushing to another (a fork), which doesn't have all of the commits from the first, including missing commits _not_ related to changes I've made locally (and therefore, for which I don't have the LFS objects pulled down).  However, both repos share the same LFS backend, so I shouldn't have to push content to the server, except for the new commits I've added locally (and in this case, there is no new LFS content in those commits).

I've verified that the object ID I'm looking at is on the server, but it's nevertheless being pushed.  I've even verified with `curl` that it can be retrieved in the "normal LFS way".  Finally, I've put `tracerx.Printf()` statements into the code, and I've seen it's completed successfully.

However, I've found that in `transferWorker()`, when the object access is successfully verified, and the loop `for _, c := range q.watchers { c <- oid }` runs, that `q.watchers` is empty.  I believe that this prevents the object ID from being added to the channel, and this is the reason that the object ID is not added to `skipObjects`.  (I've at least verified that the object ID is not in `skipObjects` for _some_ reason, and I think this is the reason)

**Comment by technoweenie** [comment]
Thanks for reporting this. I'll carve out some time to look at it this week. Definitely won't be hurt if someone else beats me to it though :)

**Comment by rjbell4** [comment]
So I tried pulling the call to `checkQueue.Watch()` before the call(s) to `checkQueue.Add()`.  I really don't grasp the full system, but I thought that having the watcher in place before adding the content would prevent the issue where the content is processed before the watcher gets in place.

However, the result is that the process hangs on me.  I think it actually winds up with deadlock because one thread is blocked waiting for room to add an object to the API channel (`apic`), while another thread is blocking waiting for room to add a (completed) object to the transfer channel (`transferc`).  So I guess the solution isn't quite that simple.

**Comment by kkutsner** [comment]
I'm hitting into similar issue.

I have artifactory server (JFrog) and a repository there. I can only push objects to that repository. As a regular user (without admin access rights and special delete permissions) I can't delete anything from that artifactory server. As a result, if I create two git repos with same files  that share the same artifactory backend, then I'll fail to push objects for the second repo, because LFS tries to delete the existing objects to overwrite it with "new" files which does not make any sense because files are identical for both repos.

**Comment by jasonwhite** [comment]
My team is hitting this issue on a fairly regular basis.

We've got an Artifactory server with quite a few LFS repositories corresponding to their respective Git repositories on GitHub Enterprise (LFS is disabled on it). No one has Delete/Overwrite permissions. If they did, they could delete all of the LFS files in an Artifactory repo. My workaround is to simply give the person hitting the error temporary Delete/Overwrite permission in Artifactory so that they can do their `git push` and trust they won't destroy everything.

If this issue gets fixed, we'd also be able to have a single LFS repo servicing many different Git repos. That could cut down on duplicate LFS objects across repositories and save a lot of administrative toil.

Since this mostly pops up with Artifactory Pro running LFS repositories, I imagine it's not easy for you guys to test a fix if you don't have an Artifactory Pro license. I'd be happy to help test if needed.

**Comment by jasonwhite** [comment]
This issue appears to be fixed on Artifactory's end:

> Fixed an issue in which deployment of an artifact which already existed in Artifactory would result in its SHA-256 value being null. This would cause the indexing of repository types like Debian and Git LFS to be incorrect since they rely on artifacts' SHA-256 value.

https://www.jfrog.com/confluence/display/RTF/Release+Notes#ReleaseNotes-Artifactory5.6.3

I haven't run into this issue in quite a while now after updating Artifactory.

**Comment by bk2204** [comment]
Okay, sounds good.  I'm going to close this then, since this sounds like it was an Artifactory issue.
