### ISSUE TITLE
Connection not renegotiated upon loss 

### ISSUE THREAD

**Issue by PinoEire** [git-lfs/git-lfs#1289]
Over LTE sometimes the connection resets. In such case why git doesn't try to re-establish the connection? It simply fails instead of reconnecting :( It's pretty simple to refresh current IP and re-establish a connection, why don't we do that?

**Comment by technoweenie** [comment]
Hi, are you asking about Git or Git LFS? Git LFS makes HTTP requests, so it should be creating new connections if the keep-alive connection is reset. Do you have a stack trace with the error?

**Comment by PinoEire** [comment]
I'm afraid there is no meaningful trace, maybe it's while it's pushing Git? I'm unfamiliar with the codebase ;(

**Comment by ttaylorr** [comment]
👋  sorry that this was sitting for a few days. If it's while pushing LFS objects to an LFS-compatible server, then the current version of LFS (v1.2.1 at the time of writing) does not support re-establishing lost connections, since the current API does not support uploading sections of a file in multiple instances. 

On a brighter note, @sinbad is working on resumable transfers using the [Tus.io](http://tus.io/) protocol, which should handle this (if the issue is related to pushing LFS objects). See #1303 for more info. 😄

**Comment by ttaylorr** [comment]
Tus.io support has shipped.
