### ISSUE TITLE
Packaging install/uninstall issues

### ISSUE THREAD

**Issue by petermarko** [git-lfs/git-lfs#1519]
## Issue 1

I'm using debian:jessie package and tried to upgrade to 1.4.1.
It failed when configuring package with

```
Setting up git-lfs (1.4.1) ...
The filter.lfs.clean attribute should be "git-lfs clean -- %f" but is "git-lfs clean %f"
Run `git lfs install --force` to reset git config.
dpkg: error processing package git-lfs (--configure):
 subprocess installed post-installation script returned error exit status 2
Errors were encountered while processing:
 git-lfs
E: Sub-process /usr/bin/dpkg returned an error code (1)
```

My configuration was valid (and default) in old version.
The old format is no longer valid and I need to correct it manually.
The package should include migration script to fix this automatically.
With current git-lfs code, `debian/postinst` should include `--force` flag:

```
#!/bin/sh
git lfs install --system --force
```
## Issue 2

When investigating I have noticed that the debian package contains postinst and prerm
scripts installing and uninstalling git-lfs configuration _unconditionally_.
This seems to be wrong, because `git lfs uninstall` command removes all configuration entries.
I have (in addition to 3 mandatory default entries) also setting of url of my server.
This is valid place to configure it per man page of `git-lfs-config`

```
git-lfs  uses the same configuration files as git-config(1) with the same precedence.
```

So now any upgrade of git-lfs will remove my configuration, which is obviously an error.
To fix this, I propose following `debian/prerm`:

```
#!/bin/sh
if [ "$1" = "remove" ] ; then
  git lfs uninstall
fi
```

This will skip the removal when the package is being upgraded,
while handling uninstall of package properly.
## Note 1

Previous suggestions were made to have a quick solution without any code change.
In my opinion, the proper solution would be to add additional functions in addition to
`git lfs install` and `git lfs uninstall`, which would do migration and
disabling/enabling of git-lfs while keeping othe configuration untouched.

This would be to properly support all relevant debian package management options
- install - install package and configure it
- upgrade - upgrade package and update configuration if needed
- remove - remove the package (keeping config files, just disabling the feature)
- purge - remove configuration files

Note that upgrade should not enable git-lfs is user manually disabled it,
it should just migrate configuration.
## Note 2

This was written for debian packaging.
But the same issue is for sure present also for rpm (or any other package type).
I have no experience there, so I do not have any code/configuration proposals.

This is also reason I'm not providing pull request, since it would be incpomlete.
Instead the needed changes are provided in text above.

**Comment by ttaylorr** [comment]
Hi @petermarko, thanks for opening this.

In terms of the first issue, that is fixed in https://github.com/github/git-lfs/pull/1497, and will be included in the next release of Git LFS (either v1.4.2, or v1.5.0).

In terms of the second issue, I think there are a few ways that we could go about approaching it. I definitely agree that while patching the `debian/prerm` script would work in the short-term, I think it's better to pursue the more correct solution first. I want to fix this quickly, but at the same time don't want to leave other platforms in the dust.

I think we could solve this in a really elegant way by changing the behavior of how we "uninstall" `.gitconifig` sections in Git LFS, per [`lfs/attribute.go`](https://github.com/github/git-lfs/blob/5edb8a7676214817e078558fa436954e61672e61/lfs/attribute.go#L102-L107). If instead of removing the entire "section", we just removed `section.property` concatenations, we'd only be touching _our_ configuration properties, not user's that happen to live under the same section. We could even take this a step further by only removing properties that either a) match the given value, or b) are "upgradable", which would leave pattern-matched (modified) .gitconfig values alone.

I think supporting more stages of the debian installation process (such as purge, remove, etc) woul be a good candidate for a follow-up PR, since I want to keep these changes pretty small. Thoughts?

**Comment by petermarko** [comment]
I did not notice the existing pull request, I guess I have searched only recent issues and there was nothing similar reported.

Regarding the second issue, I like your approach.
Maybe an improvement (if not working like this already) would be that --force option would overwrite the values even if they were changed by the user.

**Comment by ttaylorr** [comment]
Closing this per the discussion in https://github.com/git-lfs/git-lfs/pull/1521.
