### ISSUE TITLE
git lfs pull --recursive is slower than git lfs pull

### ISSUE THREAD

**Issue by filcuc** [git-lfs/git-lfs#1664]
I'm cloning a repo that contains some submodules with ```git lfs pull --recursive``` but it seems to download single file at a time for each submodule.
Instead if i do a ```git lfs pull ``` for a given submodule repo it goes fast.
The output from git for the fist case is
```
Downloading .....................dll (27.50 KB)
```
for the second case
```
Git LFS: (285 of 978 files) 135.88 MB / 275.85 MB
```

What i see is that by using ```git lfs clone --recursive``` each submodule is checked out with ```git clone``` instead of ```git lfs clone```

**Comment by technoweenie** [comment]
I think `git lfs clone` is just passing the `--recursive` flag to `git clone`, which essentially just runs `git submodule update --init --recursive` after the clone operation. Fixing this would require handling `--recursive` in our `git lfs clone` command, instead of just passing the flag through.

However, it may be a moot point with the new filter processes coming in the upcoming LFS 1.5.0 and Git 2.11 releases.

**Comment by filcuc** [comment]
@technoweenie thanks for the answer. Do you have an alternative? with submodules?
Because this doesn't work
```
git clone myRepoWithSubModules
git submodule init
git submodule update --no-fetch
```
Maybe it's my lack of knowledge of git submodules but i didn't find a way to init the repository and automatitcally pull them through ```git lfs clone```

**Comment by technoweenie** [comment]
The reason it's taking so long is that it's running the git smudge filter for each file in those submodules. There are two ways to solve this:

First, you can run `git lfs install --skip-smudge` in your repo. This disables the smudge filter, _requiring_ you to run `git lfs pull` any time you change branches or pull new git changes down. The downside is the extra command, but the upside is parallel downloads.

If you just want to apply this to a single command, you can [do what `git lfs clone` does](https://github.com/git-lfs/git-lfs/blob/5e48c70305d010b0c9c0092e0f59371f5911cb40/git/git.go#L796-L814), and use the `-c` arg:

    $ git -c "filter.lfs.smudge=" -c "filter.lfs.required=false" submodule update --no-fetch

FWIW https://github.com/git-lfs/git-lfs/pull/1617 has more info on the new filter process stuff.

**Comment by ttaylorr** [comment]
Hi, this should no longer be the case, because we have made significant performance improvements in the `process` filter used by Git to convert files in and out of Git LFS. Please make sure that you are running on the latest version of Git LFS, run `git lfs install --system`, and then try again.

If you are still experiencing slow operation times, please definitely let me know. I'd be very curious to see what's going on.

In the meantime, I am going to close this, since I think the above should be good enough to get you going again. Thanks!
