### ISSUE TITLE
external filter 'git-lfs filter-process' failed

### ISSUE THREAD

**Issue by eminence** [git-lfs/git-lfs#1697]
Currently using git 2.11.0.rc2 (I want to test the new process filter stuff), and git-lfs 1.5.1

I'm seeing this error which I can't explain:

```
lxd@sulfursim:/scratch/lxd/08> git init test-lfs
Initialized empty Git repository in /a/tmp/lxd/08/test-lfs/.git/

lxd@sulfursim:/scratch/lxd/08> cd test-lfs/

lxd@sulfursim:/scratch/lxd/08/test-lfs> unzip $HOME/repro.zip
Archive:  /u/users/lxd/repro.zip
   creating: prereqs/
   creating: prereqs/A/
   creating: prereqs/A/foo.m/
 extracting: prereqs/A/foo.m/A.txt
   creating: prereqs/A/bar.m/
  inflating: prereqs/A/bar.m/B.txt

lxd@sulfursim:/scratch/lxd/08/test-lfs> git lfs track "prereqs/**"
Tracking prereqs/**

lxd@sulfursim:/scratch/lxd/08/test-lfs> cat .gitattributes
prereqs/** filter=lfs diff=lfs merge=lfs -text

lxd@sulfursim:/scratch/lxd/08/test-lfs> git add prereqs/
error: external filter 'git-lfs filter-process' failed
fatal: prereqs/A/foo.m/A.txt: clean filter 'lfs' failed

lxd@sulfursim:/scratch/lxd/08/test-lfs> find prereqs/
prereqs/
prereqs/A
prereqs/A/foo.m
prereqs/A/foo.m/A.txt
prereqs/A/bar.m
prereqs/A/bar.m/B.txt

lxd@sulfursim:/scratch/lxd/08/test-lfs> git lfs logs

lxd@sulfursim:/scratch/lxd/08/test-lfs> git lfs env
git-lfs/1.5.1 (GitHub; linux amd64; go 1.7.3; git 4e5ba41)
git version 2.11.0.rc2

LocalWorkingDir=/a/tmp/lxd/08/test-lfs
LocalGitDir=/a/tmp/lxd/08/test-lfs/.git
LocalGitStorageDir=/a/tmp/lxd/08/test-lfs/.git
LocalMediaDir=/a/tmp/lxd/08/test-lfs/.git/lfs/objects
LocalReferenceDir=
TempDir=/a/tmp/lxd/08/test-lfs/.git/lfs/tmp
ConcurrentTransfers=3
TusTransfers=false
BasicTransfersOnly=false
BatchTransfer=true
SkipDownloadErrors=false
FetchRecentAlways=false
FetchRecentRefsDays=7
FetchRecentCommitsDays=0
FetchRecentRefsIncludeRemotes=true
PruneOffsetDays=3
PruneVerifyRemoteAlways=false
PruneRemoteName=origin
AccessDownload=none
AccessUpload=none
DownloadTransfers=basic
UploadTransfers=basic
git config filter.lfs.process = "git-lfs filter-process"
git config filter.lfs.smudge = "git-lfs smudge -- %f"
git config filter.lfs.clean = "git-lfs clean -- %f"

lxd@sulfursim:/scratch/lxd/08/test-lfs> git lfs status

Git LFS objects to be committed:


Git LFS objects not staged for commit:

```

Using the attached [`repro.zip`](https://github.com/git-lfs/git-lfs/files/605059/repro.zip) and the above transcript, I'm hoping you'll be able to reproduce this.  If you can, please let me know how I can debug this further locally. 

Thanks!

**Attachments**: 
[repro.zip](https://github.com/git-lfs/git-lfs/files/605059/repro.zip)

**Comment by ttaylorr** [comment]
I think you might have clobbered the attachment 😭 . Happy to take a look if you re-upload 😄

**Comment by eminence** [comment]
Opps!  I think it's de-clobbered now!

**Comment by eminence** [comment]
One of the strange things about this issue is that while the error references `A.txt`, the problem seems to go away if I modify `B.txt` in anyway (for example by adding a newline at the end, or shortening the file by 1 byte)

**Comment by ttaylorr** [comment]
Interesting. I can reproduce the bug locally, but I'm not sure why it's happening yet. From running this with `GIT_TRACE_PACKET=1` locally, I can tell that LFS is getting the second file (`prereqs/A/foo.m/A.txt`), but the filter process invocation is dead before it can respond. I'm thinking this may have to do with something in the clean code, but I'll have to investigate further to figure out for sure.

**Comment by larsxschneider** [comment]
@eminence Thanks a lot for this report! 👍 

@ttaylorr I think the `pkt_line_reader` gets confused if Git requests to filter a file with the exact size of 1024 bytes. If Git requests to filter a file right after that request then the [request header is empty](https://github.com/git-lfs/git-lfs/blob/cf908f61ae8cc1c345308f0a731bf41592379e6e/commands/command_filter_process.go#L85). That means GitLFS does not see a `command` which [causes a silent error](https://github.com/git-lfs/git-lfs/blob/cf908f61ae8cc1c345308f0a731bf41592379e6e/commands/command_filter_process.go#L93-L94) in GitLFS. I made this error loud with #1698.

I am pretty sure Git sends the request header properly. I added a test simulating the 1024 bytes situation to the Git core test suite and it works. I also [added the same test to the GitLFS test suite](https://github.com/git-lfs/git-lfs/pull/1699/commits/b4c6d79ffdcc25ed7f259f8b8dcb65ce621d3f34) and it failed (see #1699). That's why I believe the problem is located in GitLFS. However, I wasn't able to pinpoint it, yet.

**Comment by larsxschneider** [comment]
OK, I think I [found the issue](https://github.com/git-lfs/git-lfs/pull/1699/commits/53fcd96c951189146c74d40c6b0582891afcdc2a). #1699 should fix it!
