### ISSUE TITLE
Working on integrating git-lfs with Git through external object database support in Git

### ISSUE THREAD

**Issue by chriscool** [git-lfs/git-lfs#1702]
I sent the following RFC patch series to the Git mailing list last June:

https://public-inbox.org/git/20160613085546.11784-1-chriscool@tuxfamily.org/
https://public-inbox.org/git/20160628181933.24620-1-chriscool@tuxfamily.org/

The goal is to make it possible for Git to use external object databases.

These external object databases would be another way for Git to store its objects (blobs, trees, commits, tags). Currently there are 2 ways for Git to store its objects: loose object files and pack-files. But the current ways are not the best for big files. 

I will keep this issue updated if people are interested.

**Comment by chriscool** [comment]
By the way maybe you might want to add my work to the roadmap:

https://github.com/git-lfs/git-lfs/blob/master/ROADMAP.md

**Comment by ttaylorr** [comment]
Thanks, I'll follow along 👍

**Comment by larsxschneider** [comment]
I'll follow along, too! 

@chriscool believe it or not but I am still sitting on my answer to [your email regarding ODB](http://public-inbox.org/git/CAP8UFD0M8MDs-0UAFgx288XVdWg_XP=bOwAWoXdY=5Sg7pMFsw@mail.gmail.com/). I think teaching Git the concept of "external objects" natively would be awesome as it could solve many problems that GitLFS runs into (e.g. large files can only be defined by file path right now). 

However, I would be worried if we introduce yet another Git large file storage solution. GitLFS got already some nice adoption and I think it would be great if we all improve it together (you and me from the Git side; @ttaylorr, @technoweenie and the rest of the GitLFS folks from the LFS side). 

*Disclaimer: This is my personal opinion!*

**Comment by technoweenie** [comment]
Git LFS does not track blob OIDs from Git, so I'm not sure how this would work. Are you suggesting that Git LFS _start_ tracking this through a subcommand?

* `git lfs odb have`: the command should output the sha1, size and
type of all the objects the external ODB contains, one object per
line.

* `git lfs odb get <sha1>`: the command should then read from the
external ODB the content of the object corresponding to <sha1> and
output it on stdout.

* `git lfs odb put <sha1> <size> <type>`: the command should then read
from stdin an object and store it in the external ODB.

Where should Git LFS store this Git Blob OID -> LFS OID mapping? I imagine it'd have to be in the repository somewhere, so that every repo commit has a consistent mapping.

It looks like supporting this feature as it's currently designed, will be a step backwards for LFS. So, here are some suggestions:

1. Running a command per file has an incredible overhead, especially on Windows. Please look at Lars' git filter process stuff (https://github.com/git-lfs/git-lfs/pull/1382) shipping in Git 2.11, where turning `smudge` into a process sped up checkouts (with no LFS downloading) 80x. 
2. Can the commands include the filename? LFS allows users to configure what paths that LFS downloads are triggered through `--include` or `--exclude` flags. This allows an audio engineer to `--exclude media/textures`, or an engine dev to `--exclude media`. 
3. If LFS chooses not to download and provide the file to Git, what should it return? Currently, if someone runs `git lfs clone --exclude=media/textures`, Git writes the unchanged LFS pointer files. Users can download them later if they want with `git lfs pull --include=media/textures`.
4. Speaking of LFS not downloading objects, people have asked for the ability to delete LFS objects without modifying the Git history. https://github.com/git-lfs/git-lfs/issues/1101#issuecomment-260769632

While the filter process stuff is rad, here are a couple things that @larsxschneider has brought up as future improvements. It'd be great for an external odb process to do the same:

1. Allow clients (git lfs) to return some promise for a future response. If Git gives LFS 5 1GB blobs, let LFS respond with "promise" so it can download them in parallel, and _then_ return the object data to Git.  See https://github.com/git-lfs/git-lfs/pull/1646 for an attempt to do this without changing Git.
2. Allow clients to return a path of the filename, instead of streaming the data through STDOUT. Piping has extra overhead on Windows, so this could keep performance for Windows and Unix Git clients comparable. I know it's not very unixlike, but a lot of LFS users are on Windows. Note: this needs some verification with benchmarks, it's just a hunch right now.

I think this is a bit early to put on our roadmap, but I appreciate the heads-up!

**Comment by chriscool** [comment]
First I sent yesterday another RFC version of my patch series:

https://public-inbox.org/git/20161130210420.15982-1-chriscool@tuxfamily.org/

This adds support for external object databases that store files without converting them to the Git object format, and this adds tests that show how to use an apache server as an external object database.

**Comment by chriscool** [comment]
@larsxschneider what I am trying to do is to have a mechanism in Git itself to store objects in external databases. I think it will be great not just for large files but possibly also for files that are already compressed or that have different characteristics than text files for which Git is great.

I am trying to do it so that users only have to configure things using git itself and maybe add drivers for the specific external object databases that they want to use. So it would replace the command line interface of git LFS, but not the driver part of the client side and not the server side.

I think it would be much easier for users as they would not need to learn about another CLI and could just "apt-get install" the drivers they want on the client side.

I may work at one point on converting existing git LFS client code into a driver for an external object database, though I don't think I am the best person to do that as for now I don't know at all about the git LFS code.

**Comment by chriscool** [comment]
@technoweenie maybe just the driver side of git LFS would need to track OIDs from Git. I don't think it's a lot of work. You would just need to have a table to match Git OIDs on one side, with the IDs (whatever they are) on the LFS server on the other side.

Yeah, the driver side could be a "git lfs odb" subcommand for now. When other mechanisms, like for example a single process mechanism for the driver, similar as the single process smudge/clean filter that Lars developed, would be available, it could use that to perform better, so it wouldn't be like a subcommand.

Generally about all your suggestions, yeah, I agree that there is still work needed, but I think some of your suggestions are better addressed in Git itself than in git LFS, for example about point 4, Junio Hamano already told that external ODBs could help addressing it:

https://public-inbox.org/git/xmqqsht2qtnz.fsf@gitster.mtv.corp.google.com/

**Comment by ttaylorr** [comment]
Following along here: https://public-inbox.org/git/20180623121846.19750-1-chriscool@tuxfamily.org/.
