### ISSUE TITLE
Reinitialize a git-lfs repo

### ISSUE THREAD

**Issue by jpschwinghamer** [git-lfs/git-lfs#1740]
Howdy...

Let's say for the sake of argument that I'm convinced our team screwed up our `git-lfs` configuration. What would be the steps to take to reset and start from scratch and reinitialize `git-lfs` in our repository?

Caveat - We're currently only tracking `*.mp4`

**Comment by ttaylorr** [comment]
Hi @jpschwinghamer, thanks for opening this. If you didn't re-write any of your history, all that you'd need to do in order to stop using LFS and start over would be to remove the `lfs`-related filters from your `.gitattributes`.

In the case that you did use a tool to rewrite history, you'd have to again rewrite those commits and replace the LFS pointer files with the actual contents of the `*.mp4` files you overwrote. That should be possible with [`git filter-branch`][1] and yanking objects out of your local `.git/lfs/objects` cache. As long as you have a complete copy of all of the objects on your computer, you can parse out the OID from the pointer and look up the contents from the directory above.

[1]: https://git-scm.com/docs/git-filter-branch

**Comment by jpschwinghamer** [comment]
@ttaylorr much appreciated. Thx!
