### ISSUE TITLE
Guidelines for mirroring repos with LFS data?

### ISSUE THREAD

**Issue by woopla** [git-lfs/git-lfs#1762]
Hello,

We're going to have a Gitswarm server at work. This is a Gitlab instance which auto-mirrors back to a Perforce server. This is all fine and dandy, except that mirroring LFS objects isn't supported :sob: 

According to some Gitlab folks, this is because LFS-enabled repos cannot be mirrored by doing `git pull origin/master && git push remote master` (I'm simplifying here, bear with me :smile: ), since the `pull` will only download actual LFS data for the files in the current working directory.

If one wants to completely mirror a repo with LFS data (including the history), what's the best way to go about it?

Thanks,

Clément

**Comment by technoweenie** [comment]
Actually, that should work, unless your source remote is named something other than `origin`. Assuming it's not, you'll have to turn off Git LFS smudging so that Git LFS is able to download from the correct remote.

```sh
# run this once
$ git lfs install --skip-smudge

$ git pull origin/master
$ git lfs pull origin
$ git push remote master
```

If your remote has been pushed to with Git objects, but not Git LFS objects, you will need to run `git lfs push --all remote` to push ALL the LFS objects. Future `git push remote master` commands should work just fine.

Note: The reason you have to turn off smudging is that internal git smudge filters do not relay the remote from your `git pull origin/master` command. So Git LFS guesses `origin`.

**Comment by woopla** [comment]
Thanks @technoweenie ! I'll close the issue for now, will reopen if something terribly wrong happens :smile:

**Comment by jacobvosmaer** [comment]
I think I am the source (indirectly) of 'According to some Gitlab folks'.

The gotchas with mirroring I was thinking of are:

- what happens when you pull into / push from a bare repo
- assuming a non-bare repo, meaning we're in a working tree, what happens if you do `git lfs pull` while on a branch that has no LFS objects (and no LFS objects mentioned in .gitattributes) even though other branches in the repo do have LFS objects

My understanding is that in both cases above, the LFS client (quite understandably) does nothing. But that would mean you cannot mirror via a bare repo, and when mirroring via a non-bare repo (which is not what GitLab does to my knowledge) you would have to take care to have checked out the 'correct' branch when doing `git lfs pull`.

**Comment by technoweenie** [comment]
> what happens when you pull into / push from a bare repo

Push should work fine. Pull may have issues since there's no working directory. Try `git lfs fetch --all`, it downloads objects to `.git/lfs/objects` for the entire history. Should work fine on a bare repo.

> what happens if you do git lfs pull while on a branch that has no LFS objects (and no LFS objects mentioned in .gitattributes) even though other branches in the repo do have LFS objects

It'll only download the most recent versions of the files for the HEAD commit. `git lfs pull` is basically `git lfs fetch + git lfs checkout`.

**Comment by C0DEF52** [comment]
Solution with `git lfs fetch --all` works great. But I noticed that when I restore from mirror `git push origin` reuploads all LFS objects to remote. It seems it does not check if some objects are already on the remote server and replaces all of them. So, maybe we can make git to upload only missing objects somehow?

**Comment by mloskot** [comment]
Anyone who came over here while searching for mirroring solution, have also a look at later solutions here

https://github.com/git-lfs/git-lfs/issues/2342#issuecomment-310323647
https://github.com/git-lfs/git-lfs/issues/2342#issuecomment-487013443

**Comment by mhoffrog** [comment]
> Anyone who came over here while searching for mirroring solution, have also a look at later solutions here

### Improved LFS mirroring solution

There is a better solution than described by https://github.com/git-lfs/git-lfs/issues/2342#issuecomment-310323647.
This improvement will consistently push LFS files with the LFS reference commit **NOT** requiring a separate `git lfs push --all <TARGET-URL>`.
Instead `git lfs update --force` will install git lfs repo hooks to the mirrored bare repo before pushing so that it ensures implicit and consistent git lfs pushing to the remote target. Note that it is recommended to force overwriting of probable existing hooks, in case another git lfs version would have updated the hook content on a previously mirrored local bare repo:

```
git clone --mirror <SOURCE-URL>
git lfs fetch origin --all
git lfs update --force
git push --mirror <TARGET-URL>
```

### Advantage of this solution

1. LFS files are uploaded implicitly and consistent by the git lfs `pre-push` hook.
2. Probable remote target repo storage quota limit is checked appropriately within the singular push transaction.
   👉 Otherwise there is risk of an inconsistent and incomplete repo content on the target repo missing actual LFS files.
3. No separate `git lfs push --all` is required.
4. If there are many LFS files (e.g. a couple of 100) in a repo, then significant runtime is saved when mirroring the same repo periodically for multiple times.
