### ISSUE TITLE
Coloning file error

### ISSUE THREAD

**Issue by 39Thracian** [git-lfs/git-lfs#1785]
Hey guys! i am taking annoying error when i try cloning a file. You guys can examine error's screenshots at below. I have tried 'git reset' and 'git checkout .' command and took errors at the  2nd screenshot .

![git hub error](https://cloud.githubusercontent.com/assets/23143059/21344185/83d3905e-c6ab-11e6-801e-fdf58b18ed56.jpg)

![git reset checkout](https://cloud.githubusercontent.com/assets/23143059/21344187/85f6385a-c6ab-11e6-8e7a-e79b6a678742.png)

**Comment by ttaylorr** [comment]
Hi, @39Thracian, thanks for opening this issue and sorry that you're having trouble! Would you mind opening a terminal in your repository and running the `git lfs logs last` and pasting the output in this issue? That command will hopefully give us some more information on what's going on 👍

**Comment by 39Thracian** [comment]
Thanks your reply. Here the screenshots.
![1](https://cloud.githubusercontent.com/assets/23143059/21368621/66c6f474-c714-11e6-96f2-bafb77ac6607.png)
![2](https://cloud.githubusercontent.com/assets/23143059/21368623/6818d61c-c714-11e6-94d1-42a6bec5caaa.png)

**Comment by ttaylorr** [comment]
@39Thracian thanks for sending that info along 👍 . It looks like there are a few things going on here:

1. A network connection issue between you and wherever you're trying to download objects from.
2. An outdated version of LFS (you're running v1.3.1, the latest is v1.5.3).

Fortunately, we can fix both issues at once! By upgrading to the latest version of LFS, you'll be able to use the [`lfs.transfer.maxretries`][1] option to increase the number of attempts that LFS will make in order to download that object. Assuming that this is a transient network issue, setting the value to a sufficiently high number should resolve the problem.

[1]: https://github.com/git-lfs/git-lfs/blob/v1.5.3/docs/man/git-lfs-config.5.ronn#L104-L109
