### ISSUE TITLE
"Pointer file error: Unable to parse pointer" and "error: addinfo_cache failed for path"

### ISSUE THREAD

**Issue by provegard** [git-lfs/git-lfs#1828]
I have a repo where a number of large binaries are committed. I just upgraded the binaries to newer versions but GitHub rejected my push, saying that the files were now too large.

So I tried to use LFS. Here's what I did:

1. Created a new feature branch based on my current feature branch prior to the upgrade of binaries.
2. Followed the instructions here: https://git-lfs.github.com/
3. Committed the `.gitattributes` file along with the binary files that were marked as modified.
4. Cherry-picked the "upgrade commit": `git cherry-pick -n <sha1>`

At this point, I got the errors in the title about a lot of the binary files.

Next, I tried: `git checkout --theirs <path>` for one of the binaries, but again got "Pointer file error".

One problem is that `git cherry-pick` is trying to do a merge which I'm not really interested in, so a solution is of course to just copy the files manually. But I'm worried about the error messages. What do they mean?

**Comment by ttaylorr** [comment]
Hi @provegard, thanks for opening this. If you are upgrading a repository to start using LFS with large files already in the history, the large files will still exist at those prior points in the history, even if you add them to LFS via your `.gitattributes` file later in history.

To fix this, you can use a migration tool, or a filter branch command, like:

```bash
$ git filter-branch -f --prune-empty \
  --tree-filter '
    git rm --cached -r -q .
    git lfs track "*.ext"
    git add .
  ' --tag-name-filter cat -- --all
```

Where `"*.ext"` is the file extension you want to track.

**Comment by provegard** [comment]
Thanks for the reply! I don't want to rewrite git history though. It's fine that the files exist as blobs prior to the gitattributes commit.

**Comment by provegard** [comment]
If I were to copy the files instead of cherry-picking, would it be safe to then ignore the errors?

**Comment by provegard** [comment]
Hm, I need to read about filter-branch... If I rewrite history in my feature branch only, will there be a problem when I merge to master later?

**Comment by ttaylorr** [comment]
> If I were to copy the files instead of cherry-picking, would it be safe to then ignore the errors?

It would be safe to ignore the errors either way, they're just always going to be there as long as there are points in your history where the files existed not as LFS pointers. LFS has no current way to detect when a file should _start_ becoming a pointer, and ignore all the errors prior to that point.

If you rewrite history on your branch _after_ the point at which your branch and master diverged, the merge will apply cleanly. Anything before that, and you'll need to resolve the merge yourself.

**Comment by provegard** [comment]
Ok, thanks!

**Comment by evitolins** [comment]
So to be clear @ttaylorr, this also is the case when adding new tracking rules, when previously matching files exist in the commit history? 

__For example:__
Somewhere along the way, a contributor decided to track `*.tga` files, but some `.tga` files had already been committed into Git directly.

During a `git pull`, I should expect to see errors like:
`Pointer file error: Unable to parse pointer at: "Assets/Origin/Textures/stone_2_normal.tga"` which will never go away unless I rewrite the repo's history?

`git status` immediately shows modified files after checkout, and `git reset --hard` does nothing, and continues to return errors like one above.  Without some special maneuvers (which are difficult to locate) I can't seem to get back to a clean repo state :(.

**Comment by ttaylorr** [comment]
@evitolins that is correct. I'm adding some additional information to the `status` command that should help clarify why this is happening.

**Comment by ubershmekel** [comment]
I apologize if this is obvious, but what can be done besides rewriting history in this case?

**Comment by technoweenie** [comment]
We could degrade the message from stderr to the git trace. It'd hide it from normal use, requiring you to run something like `GIT_TRACE=1 git checkout` to see why things aren't working (as in: a malformed LFS pointer wasn't replaced with the file contents as expected). Seems like that case is much more rare than historical files added before the `.gitattributes` change.

**Comment by agole** [comment]
@ttaylorr
I have a situation where we are upgrading a repo to support LFS. We have large files in the history. 
When I tried using your filter branch command I get a bunch of messages and errors. A sampling of them are:
> Rewrite c46bbb8ff8d1d8fb10bf440b6c081c4350b92bc5 (1/743)Tracking "*.bit"
> Rewrite 7e015fbde108f6358a65a920567695e141d4a0d9 (2/743)Tracking "*.bit"
> Rewrite 34af2c6c9ddbad0497e97146803a728332303b4f (3/743)Tracking "*.bit"
> Rewrite 3d964a9a69002fb99993f31372b772ee9287d0e2 (4/743)Pointer file error: Unable to parse pointer at: "project/lpb/syn/lpb_system_top.runs/impl_1/lpb_system_top.bit"
> Tracking "*.bit"
> Rewrite e8856d7fc9a391ede51e945fd1a03f5c4b867569 (5/743)Pointer file error: Unable to parse pointer at: "project/lpb/syn/lpb_system_top.runs/impl_1/lpb_system_top.bit"
> Tracking "*.bit"
> ....
> Rewrite baf5a5bf9b7b3d291c567ebaa798018cf1a65872 (194/743)Pointer file error: Unable to parse pointer at: "project/lpb/syn/lpb_system_top.runs/impl_1/lpb_system_top.bit"
> error: 'project/lpb/syn/lpb_system_top.runs/impl_1/lpb_system_top.bit' has staged content different from both the file and the HEAD
> (use -f to force removal)
> Tracking "*.bit"
> ...
> Rewrite 42214efd60022c56f18ce7fc9d5740eca215ae6c (225/743)Tracking "*.bit"
> Rewrite 3c01b1177044b0a349bc89614da036e263a568b8 (226/743)Tracking "*.bit"
> ...
> Rewrite 7a53cac4e198f803b0682d4b28ac70ac5716ed01 (251/743)Downloading project/lpb/syn/lpb_system_top.runs/impl_1/lpb_system_top.bit (13 MB)
> Tracking "*.bit"
> ...
> Ref 'refs/heads/lfs_work' was rewritten
> Ref 'refs/heads/master' was rewritten
> Ref 'refs/remotes/origin/master' was rewritten
> WARNING: Ref 'refs/remotes/origin/master' is unchanged
> Ref 'refs/tags/3.0' was rewritten
> Ref 'refs/tags/R1.0' was rewritten
> Ref 'refs/tags/R2.0' was rewritten
> Ref 'refs/tags/R2.1' was rewritten
> Ref 'refs/tags/R2.2' was rewritten
> Ref 'refs/tags/R4.0' was rewritten
> R2.1 -> R2.1 (d2e41474589cd36d3b1cbd1af21845315335469e -> 877b26001be6b1fa3ce64e481791812f78dab745)

What do these errors mean and how do I overcome them?
Why do I get a message for some entries that the *.bit file is being downloaded?

**Comment by ttaylorr** [comment]
Hi @agole -- thanks for dropping a comment here! This issue is slightly outdated, as Git LFS now ships with a tool for managing this migration itself. The invocation is:

```
git lfs migrate import --everything --include="*.bit"
```

(in your case). Can you give that a try, and open a new issue if you come across any problemS?

**Comment by agole** [comment]
Oh cool! I'm made a branch to test this out first on which I ran the previous command. Should I run it there or create a new branch?

**Comment by ttaylorr** [comment]
> Should I run it there or create a new branch?

I think that's up to you! 😄

**Comment by agole** [comment]
ok making progress. 
I was able to run 
$ git lfs migrate import --everything --include="*.bit"
while in my master branch and then pushed to origin. I see that the history has been re-written and I have updated refs.

However when I checkout my dev branch now I get 
```
$ git checkout amol-dev
Pointer file error: Unable to parse pointer at: "project/lpb/sdk/lpb_system_top.hdf"
Pointer file error: Unable to parse pointer at: "project/lpb/sdk/lpb_system_top_hw_platform_0/lpb_system_top.bit"
Pointer file error: Unable to parse pointer at: "project/lpb/sdk/lpb_system_top_hw_platform_0/system.hdf"
Pointer file error: Unable to parse pointer at: "project/lpb/syn/lpb_system_top.runs/impl_1/lpb_system_top.bit"
Pointer file error: Unable to parse pointer at: "project/p2zcu102/sdk/p2zcu102_top.hdf"
Pointer file error: Unable to parse pointer at: "project/p2zcu102/syn/p2zcu102_top.bit"
Branch amol-dev set up to track remote branch amol-dev from origin.
Switched to a new branch 'amol-dev'
$ git status -uno
# On branch amol-dev
# Changes not staged for commit:
#   (use "git add <file>..." to update what will be committed)
#   (use "git checkout -- <file>..." to discard changes in working directory)
#
#	modified:   project/lpb/syn/lpb_system_top.runs/impl_1/lpb_system_top.bit
#	modified:   project/p2zcu102/sdk/p2zcu102_top.hdf
#	modified:   project/p2zcu102/syn/p2zcu102_top.bit
#
no changes added to commit (use "git add" and/or "git commit -a")

```
I can't seem to "undo" the modified files listed using checkout or stash. 
```
$ git checkout project/p2zcu102/syn/p2zcu102_top.bit
Pointer file error: Unable to parse pointer at: "project/p2zcu102/syn/p2zcu102_top.bit"
```
How do I make this better? Am I supposed to run lfs migrate on all branches as well?

**Comment by ttaylorr** [comment]
@agole 👋 I think I misunderstood your question. To migrate all branches in a repository, you should run the command with the `--everything` flag, i.e., 

```
git lfs migrate import --everything --include="*.bit"
```

**Comment by AndrewJDR** [comment]
From @technoweenie:
> We could degrade the message from stderr to the git trace. It'd hide it from normal use, requiring you to run something like GIT_TRACE=1 git checkout to see why things aren't working (as in: a malformed LFS pointer wasn't replaced with the file contents as expected). Seems like that case is much more rare than historical files added before the .gitattributes change.

This would be rather nice, in my opinion. It's pretty common (for me, at least), to add lfs to an old repo and not want to migrate old commits to use lfs -- I just want it to apply to new files.

Are there any plans to do this? Thanks!

**Comment by ttaylorr** [comment]
> This would be rather nice, in my opinion. It's pretty common (for me, at least), to add lfs to an old repo and not want to migrate old commits to use lfs -- I just want it to apply to new files.

I am curious if you have any further thoughts on this. To a degree, it makes sense to me to silence those errors. That said, Git will still treat your working copy as having been modified, since the index will differ from what Git expects to be there with `filter=lfs` matching items in your tree.

So, I think that ultimately, we should defer to what Git expects of us, and retain the error. That said, I am pondering adding a `--no-rewrite` option to `git lfs migrate`, which would allow you to add new commits on _top_ of existing history to perform a "soft migration".

Does that seem like a good idea?

**Comment by AndrewJDR** [comment]
> So, I think that ultimately, we should defer to what Git expects of us, and retain the error. That said, I am pondering adding a --no-rewrite option to git lfs migrate, which would allow you to add new commits on top of existing history to perform a "soft migration".
> Does that seem like a good idea?

Not terribly, at least for my particular use case. But I have a similar suggestion that might be more useful...

Just to clarify my usecase, I'll often clone some existing project and maintain my own set of commits on top of it. I'll then occasionally bring in changes from the official project by way of a rebase -- rebase rather than merge because I want to retain all the original project's commit hashes for easy reference.

Usually, in the very first of my own set of commits, I'll copy in my boilerplate .gitattributes at the root level of the project:
```
*.png filter=lfs diff=lfs merge=lfs -text
*.obj filter=lfs diff=lfs merge=lfs -text
*.dds filter=lfs diff=lfs merge=lfs -text
*.ico filter=lfs diff=lfs merge=lfs -text
*.xcf filter=lfs diff=lfs merge=lfs -text
*.ttf filter=lfs diff=lfs merge=lfs -text
*.exe filter=lfs diff=lfs merge=lfs -text
src/res/*.h filter=lfs diff=lfs merge=lfs -text
```

Now, if the project already has some files with one of these extensions somewhere, I'll eventually start seeing the problem described in this issue for those files -- `Unable to parse pointer at...`.

The problem with `--no-rewrite` as your propose is that it would add new commits with git-lfs-ified versions of all files that match my .gitattributes, which would then complicate any later rebasing against the project if they happen to make changes to those same files. (Side note: When I clone an existing project this way I typically have no reason to update the existing binary files in the project -- I only introduce new ones).

Here's what I would prefer:
```git lfs migrate --exclude-existing```
( I know the flag naming is meh but let's just roll with it for now... :) )

This could traverse the commit history looking for files in past commits that match any of the lfs patterns already defined in .gitattributes, then add some new .gitattributes entries that specifically exclude those past files from being checked by git-lfs in the future. Is this possible? my .gitattributes-fu is not sharp enough to say off the top of my head. If it is possible, this would allow to get rid of these error messages and prevent git-lfs from unnecessarily checking certain files.

Hypothetically it might look something like this...

Before `git lfs migrate --exclude-existing`:
```
*.lib filter=lfs diff=lfs merge=lfs -text
```
After `git lfs migrate --exclude-existing`:
```
*.lib filter=lfs diff=lfs merge=lfs -text
some/specific/file.lib filter=none diff=none merge=none
```
But the `none` thing I do here is totally theoretical... does it exist in practice?

**Comment by ttaylorr** [comment]
> Here's what I would prefer:
> `git lfs migrate --exclude-existing`

I am worried that this is too narrow of a use-case to be generally applicable and included in Git LFS. I think that you could get by running something like `git filter-branch` + `git check-attr -a` and rewriting the `.gitattributes` file.

> But the none thing I do here is totally theoretical... does it exist in practice?

I believe that the way to spell this is:

```
*.lib filter=lfs diff=lfs merge=lfs -text
some/specific/file.lib !filter !diff !merge
```

**Comment by AndrewJDR** [comment]
Thanks for the .gitattributes syntax! I'm going to try it next time to see if it addresses this problem for me.

Yep, I'm just one person, so I can't really speak to the narrow-ness or whatnot of different usecases. From my perspective I would never use the `--no-rewrite` option you mentioned, so I actually consider that more narrow in usefulness. If others read this thread and feel one or the other is more/less useful, they can chime in. I suppose it boils down to:

**a.** You're dealing with an existing repo and you're okay rewriting all your history. This implies you have full control over the repo and some level of control over everybody else that forks/clones the repo, because they're going to need a `git reset --hard` or similar in their local copy of the repo.
**Solution**:  Use `git lfs migrate import --everything`

**b.** You're dealing with an existing repo and you're not okay rewriting your history, but you're okay creating some new commits for the existing binary files and converting them to git-lfs. Again this implies a certain level of control over everybody else that is working with the repo.
**Solution**: use the proposed `git lfs migrate --no-rewrite`

**c.** You're dealing with an existing repo and you're not okay with rewriting history, nor are you okay with creating some new history for the existing binary files in the repo because it would create problems later when others that aren't using git-lfs update those files. This can happen if you don't have very much control over others using the original repo. e.g. You're part of a team (TeamA) that has forked another team's (TeamB) project, and you occasionally merge in from TeamA. In this example, TeamA wants/needs git-lfs, TeamB doesn't need/want git-lfs.
**Solution**: A list of exceptions in the .gitattributes file can probably get around this. A `git lfs migrate --exclude-existing` command could automate it.

Personally, I can clearly see the use-case for a, but between b and c it's very hard for me to say which one is the more common use-case.

**Comment by ttaylorr** [comment]
> **b.** You're dealing with an existing repo and you're not okay rewriting your history, but you're okay creating some new commits for the existing binary files and converting them to git-lfs. Again this implies a certain level of control over everybody else that is working with the repo.
> **Solution**: use the proposed `git lfs migrate --no-rewrite`

With regards to this, I think another use case is having large binary files in your repository's history that should be in LFS and are thus causing unclean checkouts, but _aren't_ too big to push to GitHub, so you'd rather create new commits than write over extant history.

As I understand (c) this is essentially analogous to `git lfs migrate export`, which would be useful for moving files out of Git LFS.
