### ISSUE TITLE
Lfs detection inconsistent when manually modify .gitattributes file

### ISSUE THREAD

**Issue by Sanster** [git-lfs/git-lfs#1848]
I meet a similar problem with #1057(which had been solved by #1104), the different between #1057 is I didn't use `git lfs track` to add files type tracked by lfs, I modify .gitattributes file manually. Following series of commands demonstrate the issue:
```
git init git-lfs-bug
cd git-lfs-bug
echo 0 > lfs.bin
git add lfs.bin
git commit -m "add binary file"
echo *.bin filter=lfs diff=lfs merge=lfs -text > .gitattributes
git add .gitattributes
git commit -m "track with lfs"
git status
```

After this series of commands, `git status`  says the woking directory is clean. I can delete .gitattributes file and run `git lfs track *.bin` to make lfs.bin file identified as modified, but if useA just push the code to Github and userB  clone the project, `git status` will tell userB lfs.bin file is modified even userB doesn't do anything after clone (Which I think is a little confused).

I clone the project descriped above with two git-lfs version.
For `git-lfs/1.2.0 (GitHub; windows amd64; go 1.6.1; git 9bd3b8e)`, there aren't any error infos in clone progress.
For `git-lfs/1.5.4 (GitHub; windows amd64; go 1.7.4; git 71b637f1)`，when clone finish, I see this:
> Pointer file error: Unable to parse pointer at: "lfs.bin"

Git version:
* git version 2.5.0.windows.1

**Comment by technoweenie** [comment]
The only thing we can do is offer an extra command that does #1104, without modifying `.gitattributes`. Maybe `git lfs track scan` or something? But, that would require you to remember that command after modifying `.gitattributes`.

**Comment by ttaylorr** [comment]
Thanks for opening this. Since you added the binary file _before_ changing
your `.gittatributes`, Git didn't know to run the LFS filter, which means the
file didn't get converted to a pointer.

Since the file exists in your history as a large binary object, but is marked in
your `.gitattributes` as having been tracked by LFS, LFS gets confused when it
tries to parse a pointer that it thinks it's tracking, but really is not.

I'm on board with @technoweenie's ideas here, but this command can help you fix
your repository's history in the meantime:

```sh
$ git filter-branch -f --prune-empty \
  --tree-filter '
  git rm --cached -r -q .
  git lfs track "*.bin"
  git add .
  ' --tag-name-filter cat -- --all
```

**Comment by Sanster** [comment]
Thanks for the responses. Maybe this is not a problem, I have add this case to our team's `Q&A` page, and suggest always use `git lfs track` to add file type.

**Comment by technoweenie** [comment]
Closing this in favor of #2065. Thanks for the suggestion :)
