### ISSUE TITLE
Proposal: Basic Locking for v2.0.0

### ISSUE THREAD

**Issue by technoweenie** [git-lfs/git-lfs#1883]
I'd like to ship File Locking in Git LFS v2.0. Both @ttaylorr and @sinbad have made great progress, and I think it's nearly ready for an early release. I think it'll be really useful to get something out there in the hands of users, so we can start getting feedback. What would we ship?

1. The `lock`, `unlock`, and `locks` commands.
2. The `track --lockable` flag.
3. The pre-push hook that verifies nothing is locked by another user.
4. Documentation for finalized API.

I want to get the basics out, so we can focus on more advanced locking implementation details (like #1844) for LFS v2.1 and beyond.

**Comment by sinbad** [comment]
👍 

I think 1-3 are ok because they're opt-in. It's important to note that the implementation that's there will allow you to manually implement basic locking workflows, but any parallel development either on different branches or because of delays between unlock & push, forgetting to pull before locking something, can trip you up because we're not checking for that stuff yet. I'd call it still in early adopter stage rather than ready for average users since it needs some additional workflow awareness to use it successfully.

I don't think we can say that the API is "finalised" yet because #1844 will need changes for sure, but it could be considered a v1 until we nail that stuff down.

**Comment by technoweenie** [comment]
> I don't think we can say that the API is "finalised" yet because #1844 will need changes for sure, but it could be considered a v1 until we nail that stuff down.

I'd like to ship the bare minimum to bootstrap basic file locking. IMO this means we can drop or rename properties we aren't sure of yet. Once File Locking v1 ships, dropping or renaming properties is much more difficult.

For example, if we look at the [current API](https://github.com/git-lfs/git-lfs/blob/e029224251e2d8b134ee92f3cc00e001fdcbfb40/docs/proposals/locking_api.md#post-locks) (which I think is a bit outdated from what's implemented in go):

```
> {
>   path: "/path/to/file",
>   remote: "origin",
>   latest_remote_commit: "d3adbeef",
>   committer: {
>     name: "Jane Doe",
>     email: "jane@example.com"
>   }
> }
```

Of those, I think we only require `path`.

1. `remote` isn't even [implemented](https://github.com/git-lfs/git-lfs/blob/e029224251e2d8b134ee92f3cc00e001fdcbfb40/locking/api.go#L15-L26). A Git host shouldn't care what the remote name the end user is using anyway.
2. `latest_remote_commit` had some disagreement about whether it was useful or not IIRC. Let's drop it until we know we need it.
3. `committer` isn't necessary either. Presumably, the LFS service knows who you are. Though, it can stay as a fallback, in case an LFS service isn't tied to a Git host in anyway. The proposal in #1891 introduces a new API endpoint for client side lock verification that doesn't let end users hack their `user.[name | email]` git config to get around.

My suggested initial lock schema is:

```
> {
>   path: "/path/to/file",
>   // IF latest_remote_commit is required
>   // IMO we can drop this
>   remote_ref: {
>     name: "master",
>     sha: "d3adbeef"
>   },
>   // IF committer is useful
>   author: {
>     name: "Jane Doe",
>     email: "jane@example.com"
>   }
> }
```

I want to ship an MVP so we can bootstrap basic file locking. However, you seem to be on the next level of file locking thought :) . Introducing something based on #1844 will require collaboration between git-lfs, a native tool like SourceTree, and an LFS server. I'd be okay with experimental lock schemas that are opt-in, so you or anyone else can play around with more interesting locking workflows, before Git LFS commits to specific API payloads.

I realize this is a bit wishy washy, considering the Locking API proposal has been in `master` for months. But, the lock commands themselves are locked behind env flags, and no one has a production locking service that I know of.

**Comment by ttaylorr** [comment]
> 1. `remote` isn't even [implemented](https://github.com/git-lfs/git-lfs/blob/e029224251e2d8b134ee92f3cc00e001fdcbfb40/locking/api.go#L15-L26). A Git host shouldn't care what the remote name the end user is using anyway.

Totally agree. I can't entirely remember why we needed this in the request payload (as opposed to a parameter used to generate that request), but including the _client's_ name for that remote doesn't make clear any immediate benefits, since client's can name anything however they want. This should be 🔥 'd from the API 👍 .

> 2. `latest_remote_commit` had some disagreement about whether it was useful or not IIRC. Let's drop it until we know we need it.

I think that this has the potential to be useful, but we should remove it until we know that we need it.

> 3. `committer` isn't necessary either. Presumably, the LFS service knows who you are. Though, it can stay as a fallback, in case an LFS service isn't tied to a Git host in anyway. The proposal in #1891 introduces a new API endpoint for client side lock verification that doesn't let end users hack their `user.[name | email]` git config to get around.

👍 

---

> I want to ship an MVP so we can bootstrap basic file locking. However, you seem to be on the next level of file locking thought :) . Introducing something based on #1844 will require collaboration between git-lfs, a native tool like SourceTree, and an LFS server. I'd be okay with experimental lock schemas that are opt-in, so you or anyone else can play around with more interesting locking workflows, before Git LFS commits to specific API payloads.

I think having some sort of test-bed for alternative APIs for the locking commands would be a great idea. We could try out different workflows, figure out what's needed/not and then bring that back upstream.

**Comment by sinbad** [comment]
Yeah I agree with dropping everything in the API except the `path` until we know for sure that it's useful and precisely how it's used. 👍

**Comment by technoweenie** [comment]
Thanks for chiming in. We're moving forward with this: #1908
