### ISSUE TITLE
`smudge filter lfs failed` on `bundle install`

### ISSUE THREAD

**Issue by findchris** [git-lfs/git-lfs#1889]
Hi there.

I have a (Ruby) project that I'm developing for internal company use.  It is common gem used by many other projects.  For some of my tests, I have large (100MB+) files, and so turned to `git-lfs`.  All good so far.

However, when I try to use this gem in other projects, I start getting errors.  In one of the projects using this gem, I update the `Gemfile` with this entry (pointing to my feature branch):
```ruby
gem 'common', git: 'git@github.com:company/common.git', branch: 'feature/add_cool_stuff'
```
When I run `bundle`, I get this explosion 💥 : 
```
Fetching git@github.com:company/common.git
Downloading data/na_04_01.db (128.27 MB)
Error downloading object: data/na_04_01.db (6860f0ae56723ec96e00788106665d1bc2144dc7039ff8985e2b6dd2ecce01e8)

Errors logged to /Users/chris/.rvm/gems/ruby-2.1.2@project1/bundler/gems/common-25fd0c107daf/.git/lfs/objects/logs/20170124T172217.125528551.log
Use `git lfs logs last` to view the log.
error: external filter git-lfs smudge -- %f failed 2
error: external filter git-lfs smudge -- %f failed
fatal: data/na_04_01.db: smudge filter lfs failed
Git error: command `git reset --hard 25fd0c107daf7c9586b175cab3cd29dcd4a6f285` in directory
/Users/chris/.rvm/gems/ruby-2.1.2@project1/bundler/gems/common-25fd0c107daf has failed.
If this error persists you could try removing the cache directory
'/Users/chris/.rvm/gems/ruby-2.1.2@project1/cache/bundler/git/common-650d7e8e490064278ba9d9ed434853f518126933'
```

Running `git lfs logs last` is useless:  `No logs to show`.

I checked the log file mention in the error, and have pasted it into [this gist](https://gist.github.com/findchris/f8299dc6236e9809a55885bb1ba3bd2d) for reference.

Of course, I tried removing the cache directory, as recommended, with the same result.

I tried running `GIT_TRACE=1 bundle`, and the relevant snippet follows:
```
17:37:16.788106 git.c:348               trace: built-in: git 'reset' '--hard' '25fd0c107daf7c9586b175cab3cd29dcd4a6f285'
17:37:16.816352 run-command.c:347       trace: run_command: 'git-lfs smudge -- '\''data/na_04_01.db'\'''
17:37:16.819354 run-command.c:195       trace: exec: '/bin/sh' '-c' 'git-lfs smudge -- '\''data/na_04_01.db'\''' 'git-lfs smudge -- '\''data/na_04_01.db'\'''
trace git-lfs: run_command: 'git' config -l
Downloading data/na_04_01.db (128.27 MB)
trace git-lfs: api: batch 1 files
trace git-lfs: HTTP: POST /Users/chris/.rvm/gems/ruby-2.1.2@project1/cache/bundler/git/common-650d7e8e490064278ba9d9ed434853f518126933.git/info/lfs/objects/batch
Error downloading object: data/na_04_01.db (6860f0ae56723ec96e00788106665d1bc2144dc7039ff8985e2b6dd2ecce01e8)
trace git-lfs: run_command: 'git' version
```

Finally, I tried `GIT_LFS_SKIP_SMUDGE=1 bundle`, and that succeeded.

With background out of the way:  
* What's going on here?
* Is this a bug?
* Did I resolve it correctly?
* Will I have to do this for each app using this gem (and have to inform other team members how to deal with this headache)?

One final question:  I only need the files tracked by `git-lfs` in my development environment.  Is there anyway to only fetch `git-lfs` objects in certain environments?

Thanks!

Ps.  Since I know it'll be asked, this is the output of `git-lfs env`:
```
git-lfs/1.2.1 (GitHub; darwin amd64; go 1.6.2)
git version 2.4.0

Endpoint=https://github.com/company/project1.git/info/lfs (auth=none)
  SSH=git@github.com:company/project1.git
LocalWorkingDir=/Users/chris/code/project1
LocalGitDir=/Users/chris/code/project1/.git
LocalGitStorageDir=/Users/chris/code/project1/.git
LocalMediaDir=/Users/chris/code/project1/.git/lfs/objects
LocalReferenceDir=
TempDir=/Users/chris/code/project1/.git/lfs/tmp
ConcurrentTransfers=3
BatchTransfer=true
SkipDownloadErrors=false
FetchRecentAlways=false
FetchRecentRefsDays=7
FetchRecentCommitsDays=0
FetchRecentRefsIncludeRemotes=true
PruneOffsetDays=3
PruneVerifyRemoteAlways=false
PruneRemoteName=origin
AccessDownload=none
AccessUpload=none
GIT_MERGE_AUTOEDIT=no
git config filter.lfs.smudge = "git-lfs smudge -- %f"
git config filter.lfs.clean = "git-lfs clean -- %f"
```

**Comment by technoweenie** [comment]
Hey @findchris: it looks like bundler's git support clashes with Git LFS. 

```
Fetching git@github.com:company/common.git
Downloading data/na_04_01.db (128.27 MB)
Error downloading object: data/na_04_01.db (6860f0ae56723ec96e00788106665d1bc2144dc7039ff8985e2b6dd2ecce01e8)

Errors logged to /Users/chris/.rvm/gems/ruby-2.1.2@project1/bundler/gems/common-25fd0c107daf/.git/lfs/objects/logs/20170124T172217.125528551.log
Use `git lfs logs last` to view the log.
error: external filter git-lfs smudge -- %f failed 2
error: external filter git-lfs smudge -- %f failed
fatal: data/na_04_01.db: smudge filter lfs failed
```

The `git lfs logs last` command looks for any errors in `.git/lfs/objects/logs` for the current repository. However, Bundler seems to be cloning your `company/common.git` repository to `/Users/chris/.rvm/gems/ruby-2.1.2@project1/bundler/gems/common-25fd0c107daf`.

```
HTTP: POST /Users/chris/.rvm/gems/ruby-2.1.2@project1/cache/bundler/git/common-650d7e8e490064278ba9d9ed434853f518126933.git/info/lfs/objects/batch
```

Git LFS is an unofficial Git extension that requires an LFS server. By default, Git LFS converts your remote URL to an LFS server URL. However, that is attempting to post to your local file path. I'm assuming it's because Bundler clones repositories to a cache directory (like `/Users/chris/.rvm/gems/ruby-2.1.2@project1/cache`), and then makes a clone from that to make the specific version that your project relies on. 

What happens if you go to `/Users/chris/.rvm/gems/ruby-2.1.2@project1/bundler/gems/common-25fd0c107daf` and run `git lfs env`? My hunch is the origin remote will point to `/Users/chris/.rvm/gems/ruby-2.1.2@project1/cache/bundler/git/common-650d7e8e490064278ba9d9ed434853f518126933.git`, when we really want it to point to the remote url `git@github.com:company/common.git`.

I think Git LFS should support these chained local repository clones, this isn't something slated for Git LFS v2.0. 

Here are some ideas for workarounds:

1. Do your projects using "company/common" need _any_ of the LFS objects? If not, `GIT_LFS_SKIP_SMUDGE=1 bundle` is fine :+1: (except you'll have to instruct every user of your app to run that same command).
2. Do your projects that use "company/common" need files like `data/na_04_01.db`, or is it there just for testing? If you do not need files in "data/*", but you do need other things, you can tell Git LFS to exclude it:

    ```sh
    # Run this in the root of your company/common repository.
    # Then commit `.lfsconfig` and push.
    $ git config --file=.lfsconfig lfs.fetchexclude "data"
    ```

3. You can add a `.lfsconfig` file to the root of the repository, setting the `lfs.url` config key. This forces Git LFS to use this as the LFS server, and not some local path like `/Users/chris/.rvm/gems/ruby-2.1.2@project1/cache/bundler/git/common-650d7e8e490064278ba9d9ed434853f518126933.git`. Downside is this locks you in to this github repository (though you can override in local clones with `git config lfs.url`).

    ```sh
    # Run this in the root of your company/common repository.
    # Then commit `.lfsconfig` and push.
    $ git config --file=.lfsconfig lfs.url "git@github.com:company/common.git"
    ```

Also, your versions of Git and Git LFS are outdated. I'd recommend running on Git LFS v1.5.5 and Git v2.11.0+ :)

**Comment by findchris** [comment]
Thanks for the thorough and prompt reply @technoweenie 👍 

> What happens if you go to /Users/chris/.rvm/gems/ruby-2.1.2@project1/bundler/gems/common-25fd0c107daf and run git lfs env?

Your suspicion was correct:
```
Endpoint=/Users/chris/.rvm/gems/ruby-2.1.2@project1/cache/bundler/git/common-650d7e8e490064278ba9d9ed434853f518126933.git/info/lfs (auth=none)
```

As for your workarounds, option 2 seems perfect, since none of my projects using `common` need any of the files under `/data`.  I have tried this out and it appears to work well 👏 

Thanks for pointing out that my Git and Git LFS are outdated.  FWIW, I installed Git LFS less than a week ago per the website's instructions:
```
brew install git-lfs
git lfs install
```
Perhaps the homebrew recipe needs to be updated(?)

Thanks again for your help.

As an aside, it's cool to see you still putting out solid OSS:  I used some of your Ruby stuff starting 9+ years ago (e.g. `attachment_fu`, `restful-authentication`, `acts_as_versioned`).  🏆

**Comment by technoweenie** [comment]
> As for your workarounds, option 2 seems perfect, since none of my projects using common need any of the files under /data. I have tried this out and it appears to work well

One caveat for option 2 that I forgot to mention. No one cloning that repository will get the files because of the default `lfs.fetchexclude` setting in `.lfsconfig`. You can override this in one of two ways:

```sh
# this will not download any lfs objects in data/*
$ git clone git@github.com:company/common.git
$ cd common

# 1: empty string exclude overrides the setting .lfsconfig
$ git lfs pull --exclude=""

# 2: set lfs.fetchexclude in your computer's git config, also overriding .lfsconfig
$ git config lfs.fetchexclude ""
$ git lfs pull
```

> Perhaps the homebrew recipe needs to be updated

We [update homebrew with each release](https://github.com/Homebrew/homebrew-core/blob/master/Formula/git-lfs.rb). You may have to run `brew update` to ensure you have the latest recipes.

> As an aside, it's cool to see you still putting out solid OSS

Ha, thanks :)

**Comment by findchris** [comment]
I'll add `git lfs pull --exclude=""` to the `common` project's `README`, since it seems there's no automated way to pull the Git LFS files cloning `common`, while not pulling the files for repos using that gem.

Thanks @technoweenie 👍

**Comment by karakarasuuuu** [comment]
FWIW, this unexpected behaviour seems to be fixed in https://github.com/ruby/rubygems/pull/9632 🎉
