### ISSUE TITLE
Quotes in GIT_SSH_COMMAND are not properly handled

### ISSUE THREAD

**Issue by mapio** [git-lfs/git-lfs#1895]
If you set `GIT_SSH_COMMAND="ssh -i '/a path/with spaces'"` lfs commands will complain about being unable to read `'/a path/with spaces'` (including quotes) where file `/a path/with spaces` actually exists.

**Comment by ttaylorr** [comment]
@mapio thanks for opening this. I believe the bug is [here][1], where we use [`strings.Fields`][2] to split the given `GIT_SSH_COMMAND`, which doesn't know to group arguments separated by quotes together.

```go
	cmdArgs := strings.Fields(sshCmd)
	if len(cmdArgs) > 0 {
		ssh = cmdArgs[0]
		cmdArgs = cmdArgs[1:]
	}
```

That being said, if you could post the complete error, that would be helpful in debugging and going forward with a fix.

[1]: https://github.com/git-lfs/git-lfs/blob/7e495f5cf7f1962bea40f570db874b9c49a92b1f/lfsapi/ssh.go#L69
[2]: https://golang.org/pkg/strings/#Fields

**Comment by mapio** [comment]
If I define `GIT_SSH_COMMAND="ssh -i '/Users/santini/keys/extra.rsa'"` the error is

```
$ git lfs fetch
Fetching master
Git LFS: (0 of 151 files) 0 B / 6.23 GB                                                                                                                                                    
batch request: exit status 255: Warning: Identity file '/Users/santini/keys/extra.rsa' not accessible: No such file or directory.
Permission denied (publickey).
batch request: exit status 255: Warning: Identity file '/Users/santini/keys/extra.rsa' not accessible: No such file or directory.
Permission denied (publickey).
Warning: errors occurred
```

while if `GIT_SSH_COMMAND="ssh -i /Users/santini/keys/extra.rsa"` no error is returned and all works as expected.

Hope this helps.
