### ISSUE TITLE
Object does not exist on the server

### ISSUE THREAD

**Issue by maklaus** [git-lfs/git-lfs#1935]
Hi there,

I use:
git version 2.10.1 (Apple Git-78)
git-lfs/1.2.0 (GitHub; darwin amd64; go 1.6.2)
macOS 10.12.2

I have account on gitHub (member in Organization)

Its my first time I use LFS because one of my file is over 100Mb

here is my file:
```
git lfs ls-files
2c83a17cad * RedBall4/ios/Ads/FBAudience/FBAudienceNetwork.framework/FBAudienceNetwork
```

I pushed it to gitHub:
```
git push origin master
Git LFS: (0 of 1 files, 1 skipped) 0 B / 100.08 MB, 100.08 MB skipped                                                                                                        
Counting objects: 72, done.
Delta compression using up to 8 threads.
Compressing objects: 100% (72/72), done.
Writing objects: 100% (72/72), 9.95 MiB | 206.00 KiB/s, done.
Total 72 (delta 55), reused 0 (delta 0)
remote: Resolving deltas: 100% (55/55), completed with 53 local objects.
To https://github.com/FDGEntertainment/RedBall4.git
   4eb6232..71e0bef  master -> master
```

I can see this file on remote - its a link file: 100 MB   Stored with Git LFS

As I understand from line `Git LFS: (0 of 1 files, 1 skipped) 0 B / 100.08 MB, 100.08 MB skipped  ` it doesnt uploaded to LFS. As expected when I press green button "Clone or download" I get small link file instead of my big one.

I tried to push thois file with --object-id without success as well:

```
GIT_TRACE=1 git lfs push origin --object-id 2c83a17cad
21:00:46.806996 git.c:563               trace: exec: 'git-lfs' 'push' 'origin' '--object-id' '2c83a17cad'
21:00:46.810535 run-command.c:336       trace: run_command: 'git-lfs' 'push' 'origin' '--object-id' '2c83a17cad'
trace git-lfs: run_command: 'git' config -l
trace git-lfs: tq: starting 3 transfer workers
trace git-lfs: tq: running as batched queue, batch size of 100
trace git-lfs: tq: sending batch of size 1
trace git-lfs: api: batch 1 files
trace git-lfs: Filled credentials for https://maklaus@github.com/FDGEntertainment/RedBall4.git
trace git-lfs: HTTP: POST https://maklaus@github.com/FDGEntertainment/RedBall4.git/info/lfs/objects/batch
trace git-lfs: HTTP: 200
trace git-lfs: HTTP: {"objects":[{"oid":"2c83a17cad","size":0,"error":{"code":404,"message":"Object does not exist on the server"}}]}
trace git-lfs: HTTP: 
trace git-lfs: tq: starting 3 transfer workers
trace git-lfs: tq: running as batched queue, batch size of 100
stat /Users/fedoseev/Documents/iPhone/Projects/RedBall4/.git/lfs/objects/2c/83/2c83a17cad: no such file or directory
Error uploading file  (2c83a17cad)
```

Could you please tell what I'm doing wrong? And what does it mean "Object does not exist on the server"? 

Thanks,
Ev

**Comment by ttaylorr** [comment]
Hi @maklaus, thanks for opening this. Few things going on here:

> ```
> git push origin master
> Git LFS: (0 of 1 files, 1 skipped) 0 B / 100.08 MB, 100.08 MB skipped                                                                                                        
> ```

This means that the file is already present on the server, which is why the LFS client "skips" it. We should probably think about what improving this message should look like, but I'll leave that for a later date.

> ```
> trace git-lfs: HTTP: POST https://maklaus@github.com/FDGEntertainment/RedBall4.git/info/lfs/objects/batch
> trace git-lfs: HTTP: 200
> trace git-lfs: HTTP: {"objects":[{"oid":"2c83a17cad","size":0,"error":{"code":404,"message":"Object does not exist on the server"}}]}
> ```

This is an internal request that LFS makes to the remote to see if it already has the set of objects that it's trying to upload, to determine what files it _actually_ should send to the remote.

Beyond that, it appears as if everything is working normally.

**Comment by maklaus** [comment]
Thanks @ttaylorr !

Seems "Clone or download" doesn't load LFS files.

When I use `git clone` LFS file has been loaded successfully:

`Downloading RedBall4/ios/Ads/FBAudience/FBAudienceNetwork.framework/FBAudienceNetwork (100.08 MB)`

**Comment by tishion** [comment]
> trace git-lfs: HTTP: POST https://maklaus@github.com/FDGEntertainment/RedBall4.git/info/lfs/objects/batch
trace git-lfs: HTTP: 200
trace git-lfs: HTTP: {"objects":[{"oid":"2c83a17cad","size":0,"error":{"code":404,"message":"Object does not exist on the server"}}]}


we got this error message, and then git lfs fetch --all command line exit with error code 2. This makes our task failed. 

Since this is not a real error, why does git lfs return 2?

**Comment by ttaylorr** [comment]
> we got this error message, and then git lfs fetch --all command line exit with error code 2. This makes our task failed.
>
> Since this is not a real error, why does git lfs return 2?

Missing an object on the server indicates a failure to fetch all objects
correctly.

For pushes, you can use the 'lfs.allowincompletepush' option, but there is
currently no equivalent for fetches. One thing you could do is `fetch --oid`,
which will allow you to specify certain OIDs to fetch, instead of assuming that
you want all of them.

**Comment by tishion** [comment]
Hey @ttaylorr .  I am confusing about your comments now.

Did you mean if we encounter the 404 error when we are running 'git lfs push', it doesn't mean there are real errors. While it means there are real errors when we are running 'git lfs fetch --all' and get 404 error?

we got the object Not found [404] error when we were running the command 'git lfs fetch --all'.
if we run 'git lfs fetch' then there will be no errors. And actually the real files represented by the missing objects  are existing. 

So do you have any solutions for resolve our prbolems?  we just want to eliminate the errors.

Thank you!

**Comment by ttaylorr** [comment]
Sorry for the confusion 😄. Here are my best answers to your questions:

> Did you mean if we encounter the 404 error when we are running '**git lfs push**', it doesn't mean there are real errors. While it means there are real errors when we are running '**git lfs fetch --all**' and get 404 error?

A 404 while running `git lfs push` can indicate a few things ([source](https://github.com/git-lfs/git-lfs/blob/master/docs/api/batch.md)). For instance, the HTTP response code during a `git lfs push` or `git lfs fetch` can indicate: 

> - 404 - The Repository does not exist for the user.

or, in the case of a 200 HTTP response, the batch API defines its own set of response codes:

> LFS object error codes should match HTTP status codes where possible:
>
> - 404 - The object does not exist on the server.

which would be an invalid error when `git lfs push`-ing, but would indicate a missing object when you are running `git lfs fetch`.

> we got the object Not found [404] error when we were running the command 'git lfs fetch --all'.
> if we run 'git lfs fetch' then there will be no errors.

This would indicate that your understanding:

> As my understanding, is the missing object representing a specific historical revision of that file?

is correct. `git lfs fetch` scans the working tree for LFS pointer files to download, whereas `git lfs fetch --all` scans the entire history. If the later yields an error and the former does not, it is likely to indicate that a previous version of the file is missing on the server.

> So do you have any solutions for resolve our prbolems? we just want to eliminate the errors.

Beyond a misconfigured implementation of the LFS API (as I discussed earlier), pushing the missing versions of the file that is causing the 404 would be a way to silence these errors.

**Comment by tishion** [comment]
Hi @ttaylorr ,Thank you for so detailed reply. I am clear now.

**Comment by ubershmekel** [comment]
For anyon in a situation where git lfs thinks everything is dandy but repos are spouting `Object does not exist on the server` if you have the file locally in your repo you can find the sha256 hash of the file (it's mentioned in the github placeholder file or just sha256 it yourself) then:

`git lfs push --object-id origin 75...<your sha256 here>...ac`

**Comment by Startouf** [comment]
Thanks @ubershmekel I'm actually getting this error quite often on circleCI (especially following rebases, etc.) and I use the ID reported when the circleCI build fails so I can manually repush the object with your command and restart the build.

**Comment by ilienert** [comment]
Hey @ubershmekel. We are getting this 404 error from a file that was accidentally added to LFS which we later reverted. We determined that it's oid is e70f2f6f92ac50774e87160ee70c163607f69f49518fde060731b28a38a88ca8. The hash of the file itself is 1c29e88d79b5ccd8ae5728ea320a68cbad671905.

Trying out your suggestion, I got the error:

> git lfs push --object-id origin 1c29e88d79b5ccd8ae5728ea320a68cbad671905
> Unable to stat local media path: GetFileAttributesEx C:
path\to\repo\.git\lfs\objects\1c\29\1c29e88d79b5ccd8ae5728ea320a68cbad671905: The system cannot find the file specified.

Is there a way to "trick" the repo into thinking this object still exists?

**Comment by ttaylorr** [comment]
> Is there a way to "trick" the repo into thinking this object still exists?

No, other than putting the correct object in the location specified. Since Git LFS objects are a SHA-256 hash of their content, you will need an original copy of the file's contents.

You can tell Git LFS to ignore the missing object, however, with `git config lfs.allowIncompletePush true` (or read more about it in `man 5 git-lfs-config`).

**Comment by ilienert** [comment]
Thanks @ttaylorr . However, the error still persists:

`
$  git config lfs.allowincompletepush true
$ git lfs fetch --all
Ignoring global include / exclude paths to fulfil --all
Scanning for all objects ever referenced...
* 1447 objects found
Fetching objects...
Git LFS: (0 of 0 files, 1 skipped) 0 B / 0 B, 15.78 KB skipped                 [e70f2f6f92ac50774e87160ee70c163607f69f49518fde060731b28a38a88ca8] Object does not exist on the server: [404] Object does not exist on the server
error: failed to fetch some objects from 'https://bitbucket.org/biognosys/biognosys.git/info/lfs'
`

**Comment by ttaylorr** [comment]
Sorry, I misunderstood that you were trying to fetch, instead of going
the other way around.

Missing data from the server is a situation that Git LFS does not make
an effort to recover from. In other words, Git LFS treats the server
missing data as a fatal error.

To recover from this, I would recommend that you remove the affected
parts of your Git history (with 'git lfs migrate export' or 'git filter-
branch') such that the Git LFS client does not try and fetch pointers
from this region of history that are missing.

If you have any additional questions, I recommend that you open a new
issue, since this one is quite old, and I don't want to send
notifications to the original author who may no longer be interested.

**Comment by norru** [comment]
Hi @ttaylorr, I've just got exactly the same error.

The error comes from a repository which I have just rewritten to import a large file into LFS. After rewriting.

```
$ git lfs push <origin> --all
Uploading LFS objects: 100% (4518/4518), 9.8 GB | 0 B/s, done
```
If, immediately, after this, I do a
```
$ git lfs fetch <origin> --all
fetch: 4571 object(s) found, done
fetch: Fetching all references...
[a9753bb9894124fd99364d9136763f16659cf900b83e00539902b7a9989d55b1] Object does not exist on the server: [404] Object does not exist on the server
[b6dc0fa24bb4551d74b3b6b4c20a11b25313338f2642f0b706b81e42deddbff9] Object does not exist on the server: [404] Object does not exist on the server
error: failed to fetch some objects from 'https://...'
```

Some file is missing. Can you help me explain this discrepancy? Shouldn't the previous `git lfs push` have solved this?

*note that the file that is missing is NOT the file I've imported*

**Comment by norru** [comment]
Never mind, I've tried a second time and it now works.

**Comment by JustinPihony** [comment]
Could somebody share what the export command would look like to ignore/delete/exclude certain files which are missing from the lfs server. I am trying to migrate from a custom LFS to Github's provided LFS and keep getting stuck due to files which were removed for some reason. I've tried `git filter-branch` but it still found the file - maybe because it is referenced in other branches - either way I need a way to complete this migration...

**Comment by bk2204** [comment]
@JustinPihony I don't believe there's a way to skip missing files here.  You'd need to rewrite _all_ the branches and tags in question (say, with `git filter-branch`) to remove any references to the missing objects.  You could specify that with the `--all` option to `git filter-branch`.

**Comment by JustinPihony** [comment]
I have tried this to no avail. I followed https://blog.tinned-software.net/remove-files-from-git-history/ and the file is removed from git log, but not git rev-list, which is what lfs is going off of...I'll keep playing, but if there is an easier way please let me know. I can't use bfg as it is not a unique filename and bfg doesn't allow paths afaict, either.
