### ISSUE TITLE
git lfs pull with .lfsconfig: fetchexclude=*

### ISSUE THREAD

**Issue by grantstephens** [git-lfs/git-lfs#1949]
So I finally figured out some weird behaviour.
I have a .lfsconfig file which simply has fetchexclude=* and that works fine- if you clone the repo with or without lfs you don't get all the data files (I want this- the data files are only for testing).
Now when it comes to automated building and testing the container (Bitbucket pipelines) clones with repo without lfs (automatic, can't be changed). I then want to download the datafiles and run the tests. git lfs fetch --all works and downloads all the files, but doesn't actually replace the pointers. I then tried to run git lfs pull and this didn't do anything- guessing it is blocked by the .lfsconfig file because as soon as I delete that file and then run fetch and pull it all works well.
I think, and I may very well be wrong, that pull also needs to be able to take the --all flag so as to ignore the .lfsconfig.
Please let me know if you need any more info.

**Comment by technoweenie** [comment]
The [`git lfs fetch` command](https://github.com/git-lfs/git-lfs/blob/master/docs/man/git-lfs-fetch.1.ronn) only downloads objects to your `.git/lfs/objects` directory, so it completely ignores the `fetchexclude` setting.

Try running `git lfs pull --exclude=""` to override the `fetchexclude` setting in your git config.

**Comment by grantstephens** [comment]
Why does the fetch command then have the --all flag or is that to do with which version of the files to get?
I'll try that- thank you.

**Comment by technoweenie** [comment]
> Why does the fetch command then have the `--all` flag

The [`git lfs fetch` docs](https://github.com/git-lfs/git-lfs/blob/f3a3a1cda2fe41f7da0b6dd1264275bf1b00d5be/docs/man/git-lfs-fetch.1.ronn) state:

> Download all objects referenced by any commit that is reachable; this is primarily for backup / migration purposes. Cannot be combined with `--recent` or `--include`/`--exclude`. Ignores any globally configured include and exclude paths to ensure that all objects are downloaded.

Also, apparently I was wrong about `fetch` ignoring the include/exclude params. It only does that if `--all` is given. 

Since, `git lfs pull` replaces files in the working tree, `--all` is meaningless here because there's no point downloading objects that aren't used in the working tree. This could include older versions of LFS files in the current branch, or any other branch on the local repository.

**Comment by grantstephens** [comment]
Ah, cool, thank you. Making more sense now.
