### ISSUE TITLE
Panic in retryCollector

### ISSUE THREAD

**Issue by larsxschneider** [git-lfs/git-lfs#1963]
I have seen the following panic on Linux and Windows with Git 2.11 and Git LFS 1.5.5:

Log from Windows:
```
Panic: send on closed channel

goroutine 11 [running]:
panic(0x7a7b60, 0xc042d57090)
       C:/Go/src/runtime/panic.go:500 +0x1af
github.com/git-lfs/git-lfs/lfs.(*TransferQueue).retryCollector(0xc0427b0780)
       C:/Go/src/github.com/git-lfs/git-lfs/lfs/transfer_queue.go:510 +0x532
created by github.com/git-lfs/git-lfs/lfs.(*TransferQueue).run
       C:/Go/src/github.com/git-lfs/git-lfs/lfs/transfer_queue.go:540 +0x6c
```

It happens really sporadically and I was not able to reproduce it consistently.
Here is the code in questions: [lfs/transfer_queue.go:510 in v1.5.5](https://github.com/git-lfs/git-lfs/blob/c2dcd6f569eb30fbb07dd38148a70bf4153c6e8b/lfs/transfer_queue.go#L510)

@ttaylorr any idea?

**Comment by ttaylorr** [comment]
@larsxschneider thanks for opening this. I think what's going on here is that when the transfer queue closes, it `Exit()`s the batcher, dumping out whatever it has accumulated so far<sup>[[1](https://github.com/git-lfs/git-lfs/blob/v1.5.6/lfs/transfer_queue.go#L306-L308)]</sup>:

```go
func (q *TransferQueue) Wait() {
	if q.batcher != nil {
		q.batcher.Exit()
	}
// ...
}
```

which closes the `flush` channel in the batcher<sup>[[2](https://github.com/git-lfs/git-lfs/blob/v1.5.5/lfs/batcher.go#L65)]</sup>:

```go
func (b *Batcher) Exit() {
	atomic.StoreUint32(&b.exited, 1)
	close(b.input)
	close(b.flush)
}
```

and then (occasionally) the Go scheduler will take us to the next line in `*lfs.TransferQueue`<sup>[[3](https://github.com/git-lfs/git-lfs/blob/v1.5.6/lfs/transfer_queue.go#L510)]</sup>:

```go
if q.batcher != nil {
	tracerx.Printf("tq: flushing batch in response to retry #%d for %q (size: %d)", count, t.Oid(), t.Size())

	q.batcher.Add(t)
	q.batcher.Flush() // <-
} else {
	q.apic <- t
}
```

which will try and send on that closed channel.

Fortunately, v2.0.0 is unaffected by this bug, since the `*tq.TransferQueue` is fundamentally different in its operation. I can push out a patch for this in the 1.5.x series, but I think holding out for v2.0.0 (which will be released within a couple of weeks) would be best.

**Comment by larsxschneider** [comment]
We have a build farm of 100+ machines that pull different LFS content all the time. This error happens sporadically but it happens every other day - would you mind releasing a 1.5.x fix?
