### ISSUE TITLE
Disabling local storage

### ISSUE THREAD

**Issue by masics** [git-lfs/git-lfs#1969]
Is there in options combination that will allow me NOT to keep any LFS files under .git folder but to download them and instantiate if needed? In my case it's really waste of storage to keep copies those files.

**Comment by technoweenie** [comment]
Nope. You could set some default include or exclude args to prevent LFS from automatically downloading files: [git-lfs-fetch.1](https://github.com/git-lfs/git-lfs/blob/3cd3a417cbc5c527446e1a85cad5d5f1715dc288/docs/man/git-lfs-fetch.1.ronn#L37-L68).

You can also run [`git lfs prune`](https://github.com/git-lfs/git-lfs/blob/3cd3a417cbc5c527446e1a85cad5d5f1715dc288/docs/man/git-lfs-prune.1.ronn) to remove objects that aren't referenced by the current HEAD commit too. The docs explain some git config values that you can tweak too.

**Comment by masics** [comment]
Keeping data TWICE is not a good especially if LFS storage is over 30GB and files are used in read only mode.
I think it should not be a big problem implementing it. Should it?

**Comment by technoweenie** [comment]
I think the limiting factor is Git's clean/smudge filter requiring us to pass the file contents around. We can't just tell Git to create a hard link pointing to the file in `.git/lfs/objects/...`. @larsxschneider Do you think if you taught Git's filter process to pass file paths around like we've discussed, this could work?

@masics: Do you have any specific ideas?

**Comment by larsxschneider** [comment]
@technoweenie your hard link idea might work ... but I would need to take a close look to be sure ... it wouldn't work on Windows, though.

@masics I understand your trouble - I see it in my large Git repos, too! 

_Here is a crazy though:_ 
If you would use your large files *only* in read-only mode and if *all* your branches have the same version of these large files then you could just delete your `.git/lfs/object` folder I think. Git shouldn't smudge these files if you switch branches as they don't change and GitLFS should fetch these files if you happen to change them. I haven't tested this at all - so be careful and only try it on a backup! If this actually works (and @technoweenie agrees) then we could think about a `git lfs` command to do this.

**Comment by masics** [comment]
@technoweenie This could work if git-lfs flow is changed. The explanation: if user changes file (for some reason), since the file itself is a hardlink, it will be changed in lfs/objects as well. And next checkoutof the file or reset --hard will bring a wrong file.
Instead, I'd prefer to delete file right after filter is applied and re-download if needed. And in this case git will not need any modification. Am I wrong?
@larsxschneider There are too many "ifs" in your assumption. I think more general solution should be used.
With some additional parameter like "lfs.uselocalstorage = false" it will download only what is required and deletes files after use.

**Comment by vt-idiot** [comment]
> @larsxschneider: technoweenie your hard link idea might work ... but I would need to take a close look to be sure ... it wouldn't work on Windows, though.

Que? It works fine. Imagine my surprise when I had to use git lfs for something, Windows warned me about low storage, and I realized it thought it was a **good** idea to take something I'd normally store once, something huge, and store it twice. Identically.

![image](https://user-images.githubusercontent.com/81622808/214171769-6b327662-ac0a-4ee0-924b-4a2a922b8034.png)

The only reason it wouldn't work on Windows is if:

1. `.git` was somehow on another volume.
2. ReFS. Who uses ReFS?

![image](https://user-images.githubusercontent.com/81622808/214172026-ca4bf87c-f7a5-4129-a6d1-0d7e4629f1d1.png)

I used a shell extension because I am lazy, but `mklink` does this and is built into Windows. NTFS Hard Links are simple enough that applications that are too dumb to see symbolic links will just think it's a regular file.

![image](https://user-images.githubusercontent.com/81622808/214171583-89146b41-a586-4cbe-b8a6-8aa3484a7e41.png)

These are files I'm never going to touch - if they're being touched, they're being **deleted**. I'm not really sure what a typical git lfs workflow looks like, but `let us store huge files twice! all the time!` is absurd. Use symlinks in the .git folder or something.

**Comment by sehoffmann** [comment]
Any update on this?

**Comment by bk2204** [comment]
We're tracking this in #2147, so I'm going to close this in favour of that one.  The short answer is that `git lfs dedup` exists and can be used, and if you use `git lfs install --skip-smudge` and `git lfs pull`, then we'll use copy-on-write to avoid creating a second copy in the working tree, but there's no way to simply disable the usage of the local storage altogether.
