### ISSUE TITLE
git-lfs 2.0.0 skips upload when locking API is not supported

### ISSUE THREAD

**Issue by derrickstolee** [git-lfs/git-lfs#2003]
Not all services that support Git LFS support the new locking protocol (such as VSTS or older versions of the on-prem GitHub offering). The LFS client should ignore the locking protocol when not supported, but currently skips file uploads.

**Repro Steps:**
1. Create an LFS repo using 2.0.0 and add one tracked LFS file (I added a jpg)
2. Create a new VSTS repo and set the clone URL as the origin.
3. `git push origin --all`.

**Expected Behavior:**
The push should succeed and the LFS object should be pushed along with the Git objects.

**Actual Behavior:**
The LFS client "skips" the object, but the rest of the push appears to succeed. The skipped file message does not look like an error, so the user assumes the push succeeded.

See the following log of the commands that I ran first with 2.0.0 and then with 1.5.6:
[LFS-2.0.0-IssueLog.txt](https://github.com/git-lfs/git-lfs/files/821525/LFS-2.0.0-IssueLog.txt)

**Comment by technoweenie** [comment]
Git LFS does detect that locking is not supported, and skips it correctly. The problem is VSTS doesn't support the batch api correctly. Responses put the actions in a `_links` property, but since LFS looks for `actions`, it assumes nothing needs to be done on the server and counts it as skipped.

Here's the current API spec:

* [Batch doc](https://github.com/git-lfs/git-lfs/blob/master/docs/api/batch.md)
* [Batch response schema](https://github.com/git-lfs/git-lfs/blob/master/tq/schemas/http-batch-response-schema.json)

Here's the versions from LFS v0.6.0, when the batch api was originally released:

* [Batch doc](https://github.com/git-lfs/git-lfs/blob/v0.6.0/docs/api/http-v1-batch.md)
* [Batch response schema](https://github.com/git-lfs/git-lfs/blob/v0.6.0/docs/api/http-v1-batch-response-schema.json)

The `_links` property is held over from the original API that we deprecated in v0.6.0, and finally removed all support for in v2.0.0. I think something in the code inadvertently supported your hybrid API response, so no one noticed it was wrong. We can provide a fix for this in v2.0.1.

**Comment by derrickstolee** [comment]
Thanks for the details about the LFS API deprecation. We will work to update our API usage on the live site, but this will also affect our on-prem customers, so we appreciate the work to do a client-side fix for 2.0.1.

**Comment by derrickstolee** [comment]
We fixed our API in VSTS and that fix will deploy tomorrow. This issue can be closed. Thanks!

**Comment by technoweenie** [comment]
Cool. If you encounter any issues, ask them to upgrade to 2.0.1 too :)
