### ISSUE TITLE
Include annex style "get" and "drop" options.

### ISSUE THREAD

**Issue by internetimagery** [git-lfs/git-lfs#2012]
One feature git-annex has that is quite valuable for larger projects, is the ability to manually switch files between the full version and the pointer file (removing local copy of the full file) thus saving space.

If the project is quite large (such as moving a project from perforce to git-lfs) it would be nice to "drop" binaries that are unneeded for the users current work to save local space, yet still have visible the files you don't have.

The other piece to this puzzle would be to add an opt-in config to only manually download "get" lfs full files on checkout or get them via .gitattributes setting. Saving bandwith.

**Comment by ttaylorr** [comment]
This seems like something that LFS could potentially support. I don't have an item like this on my roadmap currently, but I'd be happy to help a contributor work on a pull-request to add this functionality.

What you can do, today, however is run:

```bash
git lfs pointer --file=/file/you/want.dat > file/you/want.dat
```

Which will replace the contents of the file with the pointer. For larger files, and depending on how your OS works, you may have to do this "atomically" by storing the temporary pointer in another file and _then_ copying it over. LFS will recognize that a file it has tracked is already a pointer and move on as normal.

**Comment by ttaylorr** [comment]
I should also note:

> The other piece to this puzzle would be to add an opt-in config to only manually download "get" lfs full files on checkout or get them via .gitattributes setting. Saving bandwith.

This is possible to do with a `git lfs {clone,fetch} -{I,X}`.

**Comment by internetimagery** [comment]
Cool thats good to know, thanks. I might alias some of those commands. 😄

**Comment by technoweenie** [comment]
I don't think you should be running something like `git lfs pointer --file=/file/you/want.dat > file/you/want.dat`. Git's filters only run on patterns in `.gitattributes`, so if you add some other file manually, they may not get replaced automatically. The `git lfs [push | pull | clone]` commands should work fine, but not automatic `git [clone | pull | checkout]` commands.

I think the best way to add a single file to LFS is to run `git lfs track "path/to/foo.jpg"` or something. This is only if you aren't already tracking `*.jpg` in `.gitattributes` (which you can check with `git lfs track`). I'm using `*.jpg` as an example since it's a file type that is typically stored IN git (such as web projects or whatever).

Keep in mind that both @ttaylorr's and my suggestion only affects the current version of the file. You'll have to run something like [git-lfs-migrate](https://github.com/bozaro/git-lfs-migrate) or `git filter-branch` to remove all historical versions, rewriting history.

Also, the `--include/--exclude` flags are also available on `git lfs pull`, in addition to `git lfs [clone | fetch]`. The [man pages](https://github.com/git-lfs/git-lfs/blob/2ff28591073fc8f04cb235c5d3a57228a7be6a79/docs/man/git-lfs-fetch.1.ronn#L37) describe the options, and show how to set them in your git config too.
