### ISSUE TITLE
LFS 2.0 doesn't include basic auth when doing a verify.

### ISSUE THREAD

**Issue by sgoo** [git-lfs/git-lfs#2016]
In 1.5.6 and earlier when doing the `verify` action the LFS client would include a `Authorization: Basic` header with basic auth from the git credential manager.

However since 2.0.0 it no longer includes this information.

A bisect shows the change was introduced in e1b4563 which looks unrelated to such a change.
Was this an intentional change or is this a bug? The [spec](https://github.com/git-lfs/git-lfs/blob/master/docs/api/authentication.md) isn't very clear, but does say that the client uses basic auth.

**Comment by ttaylorr** [comment]
@sgoo thanks for opening this, and nice find. I can't remember where we landed on this when working on the `lfsapi` package, so I'm going to defer to @technoweenie. 

@technoweenie I vaguely recall you suggesting that we not include header `Authorization` header in the verify requests. Is this correct?

**Comment by sgoo** [comment]
I was reading the spec some more and what we are doing doesn't really fit with the spec here I guess.

For upload requests we are returning a both a `upload` and `verify` action.

The `upload` request goes to a seperate service that has its own authentication and we include that as a `Authorization` header in our response.
The `verify` requests comes back to the same service that processed the batch request. So we expect LFS to attach the same auth it used for the batch request.

Reading `batch.md` a bit more and looking into the `authenticated` option. Given that it applies to all actions equally it doesn't really fit with what we are doing here?

I'm still not really sure what the correct behaviour should be here.

**Comment by sinbad** [comment]
Looking at the code this got lost in the API refactor because the previous behaviour was:

```go
func VerifyUpload(cfg *config.Configuration, obj *ObjectResource) error {
        // .....
	res, err := DoRequest(req, true)
```

Where the second argument to `DoRequest` was `useCreds`. It was explicitly set to true before which meant that if the first response was an auth error, the creds were added. 

I think you could make the argument that creds shouldn't be filled if the `authenticated` response of the original batch call was `true`, but in this case it's not supplied which according to the spec means it's `false`, meaning that git credentials will be looked up for the URLs. This is a bit of a funny case because the upload URL actually *does* include an `Authorization` header, but the verify doesn't. But, given that the API allowing separately provided URLs means they can be on different systems I don't think this is necessarily incorrect.

**Comment by technoweenie** [comment]
If the verify url has no `authenticated` property and no `Authorization` header, it probably should be checking git credentials.

**Comment by basmevissen** [comment]
Ok, this seems fine in Git-LFS 2.0.2 now. Thanks!

**Comment by dylanh724** [comment]
Still seem to be having this issue in 2.1.8.0.windows.1

**Comment by basmevissen** [comment]
On 17-10-19 04:07, Dylan Hunt wrote:
> Still seem to be having this issue in 2.1.8.0.windows.1
> 

Strange, I don't see your remark on github...

Regarding the issue: I didn't even recall having the issue or even 
writing the comment!

Can you provide a simple test case against some (semi) public resources?

-- Bas.

**Comment by Ciberusps** [comment]
If anybody encountered simple error my solution might work for u.
Check that u use right header in my case there was a problem with lowercased `req.header.Authorization` it was `authorization`
