### ISSUE TITLE
Git checkout still seems to be slow

### ISSUE THREAD

**Issue by samskiter** [git-lfs/git-lfs#2025]
Continuing on from https://github.com/git-lfs/git-lfs/issues/931#issuecomment-285759325

```
$ git config --list --show-origin | grep lfs
file:/usr/local/etc/gitconfig	filter.lfs.required=true
file:/usr/local/etc/gitconfig	filter.lfs.clean=git-lfs clean -- %f
file:/usr/local/etc/gitconfig	filter.lfs.smudge=git-lfs smudge -- %f
file:/usr/local/etc/gitconfig	filter.lfs.process=git-lfs filter-process
file:/Users/samskiter/.gitconfig	filter.lfs.smudge=git-lfs smudge -- %f
file:/Users/samskiter/.gitconfig	filter.lfs.process=git-lfs filter-process
file:/Users/samskiter/.gitconfig	filter.lfs.required=true
file:/Users/samskiter/.gitconfig	filter.lfs.clean=git-lfs clean -- %f
file:.git/config	lfs.<GIT URL>/info/lfs.locksverify=false
```

```
$ git lfs env
git-lfs/2.0.0 (GitHub; darwin amd64; go 1.8)
git version 2.12.0

Endpoint=<REPO URL>/info/lfs (auth=none)
  SSH=<SSH REPO URL>
LocalWorkingDir=/Users/samskiter/<REPO NAME>
LocalGitDir=/Users/samskiter/<REPO NAME>/.git
LocalGitStorageDir=/Users/samskiter/<REPO NAME>/.git
LocalMediaDir=/Users/samskiter/<REPO NAME>/.git/lfs/objects
LocalReferenceDir=
TempDir=/Users/samskiter/<REPO NAME>/.git/lfs/tmp
ConcurrentTransfers=3
TusTransfers=false
BasicTransfersOnly=false
SkipDownloadErrors=false
FetchRecentAlways=false
FetchRecentRefsDays=7
FetchRecentCommitsDays=0
FetchRecentRefsIncludeRemotes=true
PruneOffsetDays=3
PruneVerifyRemoteAlways=false
PruneRemoteName=origin
AccessDownload=none
AccessUpload=none
DownloadTransfers=basic
UploadTransfers=basic
git config filter.lfs.process = "git-lfs filter-process"
git config filter.lfs.smudge = "git-lfs smudge -- %f"
git config filter.lfs.clean = "git-lfs clean -- %f"
```

**Comment by ttaylorr** [comment]
Huh. Thanks for opening this up and providing me with the output: I'm still unclear on why Git is choosing to fallback to the legacy clean/smudge filters.

One thing that we should clarify before diving in deeper: are you talking about `git checkout` operations where _new_ objects (i.e., absent from the cache in `.git/lfs/objects`) are being downloaded? If so, this is a known area for improvement and being tracked in #1646. The problem here is that Git requires external filters to reply with the entire contents of the object as it should be represented in the working tree before asking about the next object in the checkout. This presents an issue to LFS where non-cached objects have to be downloaded completely before the checkout can progress.

**Comment by samskiter** [comment]
Hi @ttaylorr yes, I'm talking about the download of new objects, I thought that was what !931 was about? I guess you can close this ticket then

**Comment by ttaylorr** [comment]
Glad we sorted this one out. https://github.com/git-lfs/git-lfs/issues/931 refers to checkouts with _cached_ LFS objects. https://github.com/git-lfs/git-lfs/pull/1646 refers to checkouts with cached _and_ un-cached items.

Let's move discussion there. 👍

**Comment by samskiter** [comment]
Ah! that's the one I saw and the one I thought had been completed in the latest lfs version!

Sorry for the confusion. and can't wait to have the download promises :)
