### ISSUE TITLE
git push always aborts on the same file at various stages of progress, upload does not actually resume mid-file (which is what it should do!)

### ISSUE THREAD

**Issue by JonasT** [git-lfs/git-lfs#2026]
I am just having big trouble finishing a git push on a slower connection, since it always aborts on the same big file with various stages of progress of uploading this specific file due to random connection hiccups.

Each subsequent upload attempt which I am starting does not actually *resume* at some smart point mid-file, but instead starts over with *the entire file each time*. This is obviously a rather limited approach of dealing with uploading very large files which is bound to break once something really big comes along (or a developer has to work with a shaky connection). Since git-lfs was created specifically for working with exceptionally large files, this seems like something that should really be addressed.

**Comment by ttaylorr** [comment]
Hi @JonasT: here are a few things you can do in the short-term:

> I am just having big trouble finishing a git push on a slower connection, since it always aborts on the same big file with various stages of progress of uploading this specific file due to random connection hiccups.

To address, you can bump the following settings:

- `lfs.transfer.maxretries`<sup>[[1](https://github.com/git-lfs/git-lfs/blob/v2.0.1/docs/man/git-lfs-config.5.ronn#L98-L103)]</sup>: the maximum number of object upload/download retries
- `lfs.transfer.maxverifies` <sup>[[2](https://github.com/git-lfs/git-lfs/blob/v2.0.1/docs/man/git-lfs-config.5.ronn#L105-L111)]</sup>: the maximum number of object verify requests

This will help in dealing with failed object transfers over latent or poor network connections.

> Each subsequent upload attempt which I am starting does not actually _resume_ at some smart point mid-file, but instead starts over with _the entire file each time_. This is obviously a rather limited approach of dealing with uploading very large files which is bound to break once something really big comes along (or a developer has to work with a shaky connection).

Fair point. We do have support for the Tus.io protocol on the client side since https://github.com/git-lfs/git-lfs/pull/1303, and I'd like to implement more generally available server-side support for it soon.
