### ISSUE TITLE
track command should be able to scan all filters to convert objects to LFS

### ISSUE THREAD

**Issue by technoweenie** [git-lfs/git-lfs#2065]
When you run `git lfs track <pattern>`, LFS will touch any matching files, and convert them to LFS objects in the next commit. However, there is no way to trigger this operation manually.

This is something that could also be run after a successful `git lfs clone` command.

**Comment by ttaylorr** [comment]
I like this idea. I think calling this command `git lfs touch` would be good from my end.

**Comment by shana** [comment]
Would `git lfs import` be more obvious of what it's doing, perhaps?

**Comment by ttaylorr** [comment]
Hm, my initial thought with `import` would be that it modifies history to import all revisions of the given file, not just starting at the next commit.

**Comment by shana** [comment]
Oh, good point. That's a highly destructive operation though, and I probably wouldn't recommend doing it on a file by file basis (unless the user really wants to?). The thing with `git lfs touch` is that `touch` is an implementation detail, not a description of what the operation is actually doing, which is "converting" a file to lfs.

**Comment by ttaylorr** [comment]
@shana I think that's a great point re: `touch` being an implementation detail. There has been some discussion about a `migrate` command that would rewrite history and move files into LFS from Git.

Do you think it makes sense to punt on this in favor of that?

**Comment by technoweenie** [comment]
> Do you think it makes sense to punt on this in favor of that?

Some users may want to just transition to LFS with `git lfs track`, while others may opt for a full repository rewrite. I think having both options is important. Also, `git lfs track <pattern>` already does this, just for a single pattern.

**Comment by shana** [comment]
What @technoweenie said. Both are important, but require different "commitments" from the user and reflect slightly different needs:

- rewriting all history is a heavy operation that affects everyone. It would likely be done by a designated repo owner or admin in a coordinated action, since it will require a force push and perhaps disabling branch protection to do so. It can't be incorporated into a day-to-day routine, it would likely be done either as part of a specific migration from another source control or provider, or as part of a repo cleanup. `migrate` sounds like a good verb for this.

- setting up files for lfs on the next commit is light. It can be done by anyone, and can be part of a day-to-day routine. Given that `track` already does this, then it's practically done already, just need a good name for it 😄

**Comment by ttaylorr** [comment]
@technoweenie @shana thanks for providing some insight. I agree 👍
