### ISSUE TITLE
git lfs not working with folder patterns

### ISSUE THREAD

**Issue by jvanbruegge** [git-lfs/git-lfs#2068]
Hello, 
with git lfs 2.0.0 i cant use `git lfs track 'docs/'` to track the docs folder, the folder is added to the normal git history.
When I use `git lfs track 'docs/**'` everything works as expected.

**Comment by technoweenie** [comment]
The `git lfs track` command simply adds entries to `.gitattributes`, instead of introducing our own pattern format. You can read about `.gitattributes` patterns in the [git documentation](https://git-scm.com/docs/gitignore#_pattern_format) (which is identical to `.gitignore` patterns).

**Comment by jvanbruegge** [comment]
yes, I know, but this should work (from the site you linked):
- If the pattern ends with a slash, it is removed for the purpose of the following description, but it would only find a match with a directory. In other words, foo/ will match a directory foo and paths underneath it, but will not match a regular file or a symbolic link foo (this is consistent with the way how pathspec works in general in Git).

thats why im reporting a bug

**Comment by technoweenie** [comment]
That sounds more like an issue with Git, than LFS. Here's the entire flow:

1. `git lfs track` adds patterns to `.gitattributes` with `filter=lfs`, using the exact pattern the user enters. There are a few exceptions, such as replacing spaces with `[[:space:]]`.
2. When git is adding a new file, or checking a file out, it parses `.gitattributes`, and calls LFS for any matches that include `filter=lfs`
3. LFS either replaces added files with LFS pointers to be committed to Git, or it replaces the LFS pointer from git with the actual contents of the file.

**Comment by hmtuapp** [comment]
I'm having this same issue, I'm working on a react-native project and I'm trying to track Pod files using the following command `git lfs track "ios/Pods/"` and I tried with `git lfs track "ios/Pods/**"` but is not working. Can folders be tracked with git-lfs?

**Comment by ttaylorr** [comment]
> I'm trying to track Pod files using the following command git lfs
> track "ios/Pods/" and I tried with git lfs track "ios/Pods/**" but is
> not working. Can folders be tracked with git-lfs?

Folders can't be tracked per-se (that is, you cannot write 'git lfs
track my-folder'), but you can write:

  $ git lfs track 'path/to/folder/**'

or:

  $ git lfs track 'path/to/folder/**/*'

Make sure that you are single-quoting the filepath patterns, since most
shells will expand '**' and '**/*' when enclosed in double quotes.

Likewise, please make sure that you have run 'git lfs install', so that
Git LFS can act on the files that you have tracked (it's possible, for
example, that you _are_ tracking the files correctly, but that there is
no correct installation of Git LFS to pick them up).
