### ISSUE TITLE
git-lfs downloads all objects, then fails to convert any of the actual files in the working tree from the file pointer files to the actual binary files

### ISSUE THREAD

**Issue by JonasT** [git-lfs/git-lfs#2091]
I am just having the following problem: git-lfs downloads all objects, but then it fails to convert any of the actual files in the working tree from the file pointer files to the actual binary files. Instead, all files I open up are still the useless file pointer contents. `git lfs fetch --all` completes without error, and the files are all present on the server (gitlab).

**Comment by ttaylorr** [comment]
:wave: @JonasT, thanks for opening up this issue. There are a few layers to the LFS operation, which can make this whole transaction confusing. Since LFS downloads objects into the local cache, that means the files were cleaned (converted from the working tree into the index) correctly by someone who does have LFS installed on their machine. There are a few things that could go wrong between then and now:

1. Has your .gitattributes changed to no longer invoke LFS on that particular group of files?
2. Is LFS installed correctly on the machine that you're checking out this repository on? See: https://git-lfs.github.com for more details on how to do that.
3. Did you do a `git lfs clone -X '**/*'` or `git lfs install --skip-smudge`? Either of these would skip the smudging operation (converting back from the index into a large object in your working tree).

Also to note, `git lfs fetch` doesn't actually preform a checkout, it only downloads LFS objects into your local `.git/lfs/objects` directory. `git lfs checkout` would check these files out, or you could use `git lfs pull` which is a combination of `git lfs fetch` + `git lfs checkout`.

**Comment by JonasT** [comment]
`git lfs checkout` indeed brings back the files!

What do I need to do so that happens automatically again in this repository? I cannot remember ever being required to do that manually before

**Comment by ttaylorr** [comment]
@JonasT glad everything is all good with your repository, and that we didn't have to get into any weird history-rewriting scenarios.

LFS will automatically checkout the files so long as it has either a `filter.lfs.clean` & `filter.lfs.smudge` combination in your gitconfig somewhere, OR has `filter.lfs.process`. This can be installed via `git lfs install --system` or just `git lfs install`, depending.
