### ISSUE TITLE
NTLM in theory should not work as transport is recreated between Challenge and Auth requests

### ISSUE THREAD

**Issue by twinj** [git-lfs/git-lfs#2115]
In the Client Do function, which is called from ntlm challenge, negotiate and authenticate - c.httpClient is called which resets the transport layer in the Client.

An NTLM session requires the connection to stay alive between the challenge and authenticate requests.

func (c *Client) Do(req *http.Request) (*http.Response, error) {
	req.Header.Set("User-Agent", UserAgent)

	res, err := c.doWithRedirects(c.httpClient(req.Host), req, nil)
	if err != nil {
		return res, err
	}

	return res, c.handleResponse(res)
}

**Comment by ttaylorr** [comment]
Thanks for the report. I'll file this to be addressed in the next release.

**Comment by technoweenie** [comment]
We don't use or have access to any LFS servers with NTLM support. If someone that does could introduce some failing test cases to catch this, that'd be a huge help.

**Comment by ttaylorr** [comment]
Removed this from the milestone. I don't have an NTLM server set up, but I'd be happy to help someone through a PR that addresses this.

**Comment by stffabi** [comment]
The `http.Client` gets cached and reused for every request to a specific host in [client.go#L235](https://github.com/git-lfs/git-lfs/blob/master/lfsapi/client.go#L235) and as part of that the transport.

So that shouldn't be a problem or am I missing something?

NTLM is working in our windows environment with a TFS on-prem server, apart from SSO as mentioned in #2234

**Comment by ttaylorr** [comment]
As @stffabi indicates, it seems as everything is working OK here.
