### ISSUE TITLE
"API rate limit exceeded" not considered an error 

### ISSUE THREAD

**Issue by IoriBranford** [git-lfs/git-lfs#2133]
I deploy builds of my [project](https://github.com/ioribranford/demonizer) with Travis CI. On this and any other issue where not all files are downloaded, git-lfs should exit with a non-zero error code so the build will stop. But on this issue, the build continues on.

From https://travis-ci.org/IoriBranford/demonizer/builds/219084582
Line 1610
```
$ git lfs pull
Git LFS: (9 of 109 files) 1.32 MB / 11.35 MB                                   
batch response: API rate limit exceeded for <IP>. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)
```

**Comment by technoweenie** [comment]
We'll have to investigate any rate limit changes on the server. It might be worse since you're making a public repository request from a shared server (travis). One workaround is to set the `lfs.<url>.basic` git config value inside the local repository:

```sh
$ git config lfs.https://github.com/OWNER/REPO.git/info/lfs.access basic
```

**Comment by technoweenie** [comment]
Bah, I left out one important detail. If you set `lfs.<url>.access = basic`, you'll need a login too. You can create a [github personal access token](https://github.com/settings/tokens) with **no scopes**. This will get you a higher rate limit, without providing access to any private resources.

**Comment by IoriBranford** [comment]
Yes, I now have Travis add my user name and token to the remote URL, so I no longer exceed the rate limit.

**Comment by bk2204** [comment]
@siyangy Generally, you're going to want to avoid putting the token into the URL, instead using a credential helper, in which case what @technoweenie wrote is correct even for a token. If you wish to put the token into the URL nevertheless, then that syntax is correct.

**Comment by bk2204** [comment]
You may need to specify `git config lfs.https://github.com/<owner>/<repo>.git/info/lfs.access basic` (without the token, but with the `/info/lfs`) instead. That should be sufficient to trigger `git lfs env` to show it properly.

It isn't absolutely required that you use a credential helper, but we highly recommend it over storing the token in the URL, since it tends to be more secure. If you have a token, it's equivalent to a password for our (and Git's) purposes, since in this case you're using Basic auth either way.
