### ISSUE TITLE
after merging a git lfs pull is required?

### ISSUE THREAD

**Issue by lukka** [git-lfs/git-lfs#2189]
Scenario brief description:
merging a LFS tracked file.

Detailed sequence of steps:
.... git repo created and lfs enabled
>git lfs track "*.docx"
>.... add and commit file.docx
>....git branch dev
>.... edit file.docx on master branch
>git commit -a
>git checkout dev
>.... edit file.docx on dev branch
>git commit -a
>git checkout master
>git merge dev
At this point the file.docx is a pointer file (actually contains two pointers, one to the file on dev branch, one to the file on master ) containing a conflict marker.
>....edit the pointer file to use the one from dev branch
>git add file.docx
>git commit
>git lfs pull

questions:
1- why the merge resolution operates on the pointers text file? I expected git to not attempt any merge conflict resolution at all on docx files.
2- is the last git lfs pull required to replace the pointer file with the actual binary content?

git version 2.11.0 (Apple Git-81)
git-lfs/2.0.2 (GitHub; darwin amd64; go 1.8)

**Comment by ttaylorr** [comment]
@lukka :wave:, thanks for opening this issue. I believe that what's occurring is that when your introduce a merge conflict, Git does not attempt to filter the content, since it knows that it's broken. In other words, Git does _not_ run the pointer file through LFS, so it never gets "replaced" as a docx file in your working tree.

The `git lfs pull` that you're running can be replaced (I think) with a simple `git checkout .` following a resolution of the merge conflicts. `git lfs pull` (similar to `git pull`) is a fetch+checkout operation, and since you're not downloading any new large objects from your remote, a checkout alone should suffice.

Let me know if you have any other issues.
