### ISSUE TITLE
When cloning a repository, pulling files from LFS seems to be very slow

### ISSUE THREAD

**Issue by devedse** [git-lfs/git-lfs#2256]
Whenever I'm pulling my repository it seems that pulling the files from LFS seems to be causing a delay. After every file there seems to be a delay of a few seconds, thus causing a number of small files to download really slowly.

![image](https://cloud.githubusercontent.com/assets/2350015/26357251/00b1fec0-3fcf-11e7-9a0e-bb27867d0056.png)

(Basically between every line of 'Downloading' there is a few seconds of delay in between).

**Comment by ttaylorr** [comment]
👋 @devedse, thanks for opening this issue! Due to the way that Git does a checkout after cloning, downloading these files happens sequentially in serial. To work around this, LFS has a `git lfs clone` wrapper command that parallelizes the downloads. Could you try that instead?

If you're talking about actual network transfer speed, there are many options you can look into in the `git-lfs-config(5)` man page.

Please don't hesitate to reopen this if you run into any issues in the future.

**Comment by devedse** [comment]
@ttaylorr, but what is the underlying cause that a checkout for a file takes almost 3 seconds?

**Comment by ttaylorr** [comment]
> but what is the underlying cause that a checkout for a file takes almost 3 seconds?

For an LFS object that is not cached locally, you must first download it, which is a function of your network speed/connection etc.

For a file that is cached locally, there may be other factors at play, but I have not been able to reproduce checkouts that slow on my Windows VM.

**Comment by devedse** [comment]
My network speed is 500mbit fiber so there should be no issue there. Is there a way to manually execute a checkout on a file to see how long that takes?

**Comment by ttaylorr** [comment]
> Is there a way to manually execute a checkout on a file to see how long that takes?

You can do this using `time git checkout <branch> <pathspec>`.

**Comment by devedse** [comment]
That seems to work instantly for me.

**Comment by ttaylorr** [comment]
> That seems to work instantly for me.

I think this may be fast now because the objects that you are trying to checkout are present in your local `.git/lfs/objects` cache.

The reason that this may have been slow when you did a `git clone` (not a `git lfs clone`) is that Git forces these to be downloaded in series, one after another, which makes this a linear function of a) how fast your network is, b) how many objects you have, and c) their average size. Once they are downloaded, it's a disk operation, not a network operation.

Additionally, if you have all your objects locally and you're doing a checkout with many files, this can be slow if you're using the legacy `smudge` filter. (You can guarantee you're using this if either a), you're on a Git version lower than 2.11, or b) you have the `git config filter.lfs.process` unset). This is the case because Git invokes the smudge program once per file, instead of once per checkout. This is particularly pernicious on Windows, because the overhead for starting a new process is large, and is multiplied over the amount of items in your checkout.

**Comment by devedse** [comment]
I indeed seem to be using git version 2.10, I will upgrade and inform you about the results :)

**Comment by ttaylorr** [comment]
> I indeed seem to be using git version 2.10, I will upgrade and inform you about the results :)

Great, thanks!
