### ISSUE TITLE
Git push with LFS results in LFS file push that keeps looping with a tcp read error at the end

### ISSUE THREAD

**Issue by devedse** [git-lfs/git-lfs#2259]
Whenever I do a Git push to a brand new repository with some files that should be pushed to LFS I am running into a problem:

First I run the git push command:
![ezgif com-video-to-gif](https://cloud.githubusercontent.com/assets/2350015/26404421/28af1a2a-4092-11e7-95fb-e01bb7592bda.gif)

After a while when it almost reaches the end it hangs at 1011.91mb and then goes back to 0mb.
![ezgif com-video-to-gif 1](https://cloud.githubusercontent.com/assets/2350015/26404482/7693184a-4092-11e7-9534-a26b292a042a.gif)

After letting the command try to push for about 20-30 minutes it ultimately results in the following message:
![image](https://cloud.githubusercontent.com/assets/2350015/26404517/9577712a-4092-11e7-95d9-ada5e5d4a6ac.png)

I tried this on 3 machines. On 2 of the machines I run into this issue. (One is on a corporate network, one is on an Azure VM).
On my third machine at home I was able to do this push though. (By just zipping the repository and executing the git push command on that machine)

Edit:
As seen in the images above, there are only 2 of the 19 files remaining to be pushed to LFS. The other 19 pushed to there without any issues.

**Comment by technoweenie** [comment]
It looks like you're hitting network io timeouts trying to upload the file. You can tweak LFS' timeouts with various settings described in [docs/man/git-lfs-config.5.ronn](https://github.com/git-lfs/git-lfs/blob/master/docs/man/git-lfs-config.5.ronn):

* lfs.dialtimeout
* lfs.tlstimeout
* lfs.activitytimeout
* lfs.keepalive

The reason why the upload restarts is because it's hitting an error, and retrying. If you run the command with `GIT_TRACE=1` at the front, you'll be able to see more internal details of what's happening.

**Comment by devedse** [comment]
I think a network timeout is really really unlikely since the virtual machine I was running it on is being hosted in Microsoft Azure with a gigabit or more backend.

**Comment by craigminihan** [comment]
@technoweenie I know this is old now but it helped me figure out a similar problem:

Uploading large files to LFS on VSTS timeout on upload completion because the remote takes > `lfs.activitytimeout` (10s as default) to store the file and respond to the client. This causes the client to retry for inifinity or until the credential cache has expired.

In my case VSTS took approx 15s *after* completion to store a 410MB file and return a response to the client. It is likely I'll hit this issue on a regular basis so increasing the default `lfs.activitytimeout` at least in the case of a completed upload would make a lot of sense.

I can raise this as a separate issue if you'd prefer.

**Comment by technoweenie** [comment]
@craigminihan LFS does not set a complete request timeout for LFS uploads or downloads, since the duration is related to the size of the image. So the activity timeout is for the duration between individual tcp reads/writes. This is implemented as a net connection object that wraps read/write calls:

https://github.com/git-lfs/git-lfs/blob/28925b7178704ce97a06a80ac782a289db268ac8/lfsapi/client.go#L351-L369

> In my case VSTS took approx 15s after completion to store a 410MB file and return a response to the client.

It sounds like VSTS is doing some sort of post processing of the file. Unfortunately, due to the way the activity timeout is implemented, there's no easy way to ignore the tcp write deadline after the HTTP request has finished sending the request body. I just wish the Go HTTP client implemented this natively :)

So, I think increasing the default timeout is the way to go here. What do you think about a new default of 60s?

**Comment by craigminihan** [comment]
@technoweenie A fairly standard default for socket read/write operations is 30s. It would be a relatively low risk quick-win I reckon.

60s may cause other more unacceptable issues but at some point if the server backing store commit exceeds `lfs.activitytimeout` you fall back into the same hole again.

I'm not a Go dev so I'm not sure about the HTTP APIs they expose, however if you know the request body size and you know how far thru the write sequence you are you may be able to modify the read timeout after the last write accordingly. For example by adding a new setting `lfs.committimeout` where you assume the last write is a success and you therefore tolerate a longer tcp read timeout just for the last block.

If I get time today I'll put together a simple repo case and try it out on Gitlab and VSTS.

**Comment by technoweenie** [comment]
> I'm not a Go dev so I'm not sure about the HTTP APIs they expose, however if you know the request body size and you know how far thru the write sequence you are you may be able to modify the read timeout after the last write accordingly.

The HTTP client is a global instance, so there's not an easy way to tune the read/write timeouts per http request. I think it'll take a totally different approach to improve this. Maybe something at a higher level, at the specific spots in the app that we're sending or receiving data?

At any rate, I'll bump it to 30s for v2.3.2. Not sure when that'll get released though.

**Comment by mbbvn** [comment]
I see same behavior when I try to push a really large file to LFS (2.8 GB). Tried it with GIT LFS plugin v2.5.2. Increased _lfs.activitytimeout_ to 600 (and also 6000) with no luck.

Enabling GIT_TRACE and GIT_CURL_VERBOSE shows HTTP 401 error along with HTTP 200. Can someone shed some light on this please?
[git-lfs.txt](https://github.com/git-lfs/git-lfs/files/2510281/git-lfs.txt)
