### ISSUE TITLE
Git status slow with git lfs

### ISSUE THREAD

**Issue by lasryaric** [git-lfs/git-lfs#2274]
Hi,

We have a git repo with a few large files (around 5 files of 4GB each). All these big files are managed by git lfs.
Everytime I do a git status on my repo, git status takes around 30 seconds to complete and when I look at the process tree, I see that the git status command trigger a `git-lfs filter-process` process which lives for 30 seconds, every time I trigger that command.

Here is the output of `git --version`, `git-lfs --version`, `git lfs fsck`, `git lfs status`:
```bash
➜  param_clean_3 git:(master) git lfs fsck
Object tpl/model.ckpt-82500 (52640bc56590758fe9ef3948096e919b5507446223f32f866bbb0ad955021ba1) could not be checked: no such file or directory
Object tpl/model.ckpt-82500.meta (a9ce35d312ddee2c85b4d1c9ba3aa0c8bcbe5c8dfb1635647badc0bdde4c1c75) could not be checked: no such file or directory
Object tpl/model.ckpt-72500 (6169fa2389e1ed4c372e129a12ecc7ef2ca12f89f9eb84db6eaa8a31d0de6bed) could not be checked: no such file or directory
Object tpl/model.ckpt-72500.meta (0b326d1a69945fbee74b3a2dff5b8a092b4fe84e3e829da4c7d4447437dab28b) could not be checked: no such file or directory
Moving corrupt objects to /Users/aric/param_clean_3/.git/lfs/bad
rename /Users/aric/param_clean_3/.git/lfs/objects/52/64/52640bc56590758fe9ef3948096e919b5507446223f32f866bbb0ad955021ba1 /Users/aric/param_clean_3/.git/lfs/bad/52640bc56590758fe9ef3948096e919b5507446223f32f866bbb0ad955021ba1: no such file or directory
➜  param_clean_3 git:(master) git-lfs status
On branch master
Git LFS objects to be pushed to origin/master:


Git LFS objects to be committed:


Git LFS objects not staged for commit:

	area/nyc/gpd/data.0000000000000000.e2b5-a54a-ee8f-c46c (LFS: 681e2af -> File: 681e2af)
	area/nyc/tt/data.0000000000000000.5c98-aeb4-1a9b-2376 (LFS: 1e9366c -> File: 1e9366c)

  ➜  param_clean_3 git:(master) git --version
  git version 2.13.0

➜  ~ port info git-lfs
git-lfs @2.1.1 (devel)

Description:          Git Large File Storage is an extension for versioning large files
Homepage:             https://git-lfs.github.com/

Build Dependencies:   go, rb19-ronn
Runtime Dependencies: git
Platforms:            darwin
License:              MIT
Maintainers:          Email: raimue@macports.org
                      Policy: openmaintainer
➜  ~
```

Any idea where that can be coming from?

Thanks.

**Comment by ttaylorr** [comment]
@lasryaric thanks for opening this issue. I think the issue is this:

- Git detects that some files in your repository are stat-dirty from the index or history, and therefore need to be re-scanned.
- Git checks `.gitattributes` and finds that some of these files are stored in LFS, so it spins up the `git-lfs filter-process` command to convert them.
- Slow disk operations between Git and LFS yield the slowdown.

In other words, I think this is a hardware issue having to do with disk speed. I can't think of anything in the the `filter-process` that would cause a _repeated_ slowdown of `git status` performance. The `filter-process` does have the potential to download LFS objects from an LFS server, but would only do that once (unless you were repeatedly running `git lfs fsck` before `git status`).

If this seems off, please don't hesitate to re-open this issue.

**Comment by 1KFHE7w8BhaENAswwryaoccDb6qcT6DbYY** [comment]
кто вы

**Comment by swapnilbhave** [comment]
@ttaylorr We saw the same issue with our repo recently. Take example of "git lfs track"
time_taken = time_taken_to_generate_list_of_files_to_ignore + time_taken_to_do_fstat_on_files_included.

At our repo's scale, time_taken_to_generate_list_of_files_to_ignore >> time_taken_to_do_fstat_on_files_included
So generating exclude list using  fastWalkCallback(fastWalkWithExcludeFiles(rootDir, ".gitignore"), cb) is taking too much time compared to the time saved by doing fstat on less number of files.
Probably Excludefile generation could be further optimized to be much faster to be effective. 
I just reverted this and everything becomes faster again, but this is a temp change https://github.com/swapnilbhave/git-lfs/commit/e4778607608ee0906368081079feb21758e3cc81

You may want reopen this Issue and try out the speed for this function for various ratios of number of exclude files and include files.

**Comment by swapnilbhave** [comment]
@ttaylorr Went back and looked at the code again, not familiar with golang much but I think we are not doing two passes as I thought before. We just walk and check of the current file is part of exclude pattern or not. I think that check is taking a longer time for us. O(patterns in .gitignore) A data point is that we have around 900 patterns in .gitignore. Do you think that could be the issue? Thanks.

**Comment by bk2204** [comment]
There are two parts that can be causing slowness, and you'd need to measure appropriately to see what's what.  First, your files are likely stat dirty because their stat data has changed by mounting the diskimage or changing the working tree (since the index will have device and inode numbers in it).  If the files are stat dirty, they will all have to be filtered, which can be very costly.  You can try adjusting `core.checkStat` to `minimal` and `core.trustctime` to `false` (try them in that order and then both together).

The other issue is #3428, for which there is a branch in the issue that provides an optimized walk routine.  You're welcome to look at it and report back in that issue if it helps for you.  It will likely help if you have a large number of ignored files, but not if you have a large number of untracked files.
