### ISSUE TITLE
Git LFS files skipped even though the where tracked

### ISSUE THREAD

**Issue by Caspert** [git-lfs/git-lfs#2279]
I having some trouble with the use of GIT LFS. I had some issues to add a commit to git when I added CocoaPods to my Xcode project. The error that `GitHub's file size limit of 100.00 MB
`. After some research I came to the LFS library. After installing I cloned the project without CocoaPods. Added the Pod file and installed the GVRSDK Pod.

After that I did the following commands:
`git lfs track [files that where been added by CocoaPods]`
`git lfs track` - The tracked files where tracked
`git add .`
`git commit -m "Added Pods to project"`
`git push`

But after pushing the commit I receive the same error. Also it says: `Git LFS: (0 of 0 files, 8 skipped) 0 B / 0 B, 112.96 MB skipped`.

I have updated my git to the latest version of 2.13.0

What do I wrong or am I missing? I followed this tutorial: https://github.com/git-lfs/git-lfs/wiki/Tutorial

The complete error is:

`Git LFS: (0 of 0 files, 7 skipped) 0 B / 0 B, 1.02 KB skipped                  Counting objects: 760, done.
Delta compression using up to 8 threads.
Compressing objects: 100% (600/600), done.
Writing objects: 100% (760/760), 57.14 MiB | 73.00 KiB/s, done.
Total 760 (delta 212), reused 0 (delta 0)
remote: Resolving deltas: 100% (212/212), done.
remote: error: GH001: Large files detected. You may want to try Git Large File Storage - https://git-lfs.github.com.
remote: error: Trace: 4e56dff020008a4a06c019a10618d5ab
remote: error: See http://git.io/iEPt8g for more information.
remote: error: File Pods/GVRSDK/Libraries/libGVRSDK.a is 112.96 MB; this exceeds GitHub's file size limit of 100.00 MB
To https://github.com/Caspert/RSRVR
 ! [remote rejected] dev -> dev (pre-receive hook declined)
error: failed to push some refs to 'https://github.com/Caspert/RSRVR'`

**Comment by ttaylorr** [comment]
@Caspert thanks for opening this, and sorry that you're having trouble. I think there are two issues at play here:

1. LFS "skips" objects in the upload queue if they are already present on the remote. You or a colleague of yours may have already pushed the 112.96MB of objects that your are seeing as skipped.
2. GitHub is rejecting your push because it still has large objects somewhere in your history. If you can locate the range of commits that contain these large objects and rewrite them (or remove them from your push, see: `git-rebase(1)`, `git-filter-branch(1)`) the push should succeed.

Let me know if this resolves your issue. If you have any other questions, please don't hesitate to re-open this issue!

**Comment by Caspert** [comment]
Hi @ttaylorr. Thanks for your replay. I working individual on this project, so I am the only one that commit changes. Your second point, when I don't add Pods to my project and just edit something in my Storyboard I can commit and push that one without any problems. I tried to use LFS just for like to track my Storyboard and that is working correctly. After I do `pod init` and add the `GVRSDK` to the list, and commit that change I get above error. Hope there is a solution for this, because I never had an issue with committing a project that make use of Pods. I am looking forward for your replay. Thanks in advance.

**Comment by ttaylorr** [comment]
Before you commit, can you run `git lfs status` on the broken branch(es) and paste the output here?

**Comment by arvindnrbt** [comment]
I have the same problem, same error. This is what git lfs status shows.
On branch master
Git LFS objects to be committed:
	.gitattributes (Git: 8e4d8c6 -> Git: 63954a4)
Git LFS objects not staged for commit:

**Comment by technoweenie** [comment]
Since this issue was closed, LFS has a new `migrate` command. If you're having pushes rejected because of a remote's blob size restriction, running this should fix it:

```sh
# check to see what file types are using so much space.
$ git lfs migrate info
migrate: Fetching remote refs: ..., done
migrate: Sorting commits: ..., done
migrate: Examining commits: 100% (1/1), done
*.zip          	264 MB	1/1 files(s)	100% # there's my big file!
*.gif          	391 B 	3/3 files(s)	100%
*.bin          	378 B 	3/3 files(s)	100%
*.gitattributes	168 B 	1/1 files(s)	100%
*.JPG          	130 B 	1/1 files(s)	100%

# by default, only operate on *unpushed* commits
$ git lfs migrate import --include="*.zip"
migrate: Fetching remote refs: ..., done
migrate: Sorting commits: ..., done
migrate: Rewriting commits: 100% (1/1), done
  master	5025a0b34495b7d6c9ccd6e2521c994b6294feed -> 828f85586eadcbb21537715e9df60312b39c2f4a
migrate: Updating refs: ..., done
migrate: checkout: ..., done
```

That `import` command shows the `master` branch changing the head commit that I attempted to push, `5025a0b`, into a new commit (`828f855`) with the git blob replaced with an LFS pointer.

You can confirm it worked with `git show`:

```sh
$ git show
commit 2d9f007d0381ec5c15b088bfc1f4d1712a33736a (HEAD -> master)
Author: rick olson <technoweenie@gmail.com>
Date:   Thu Oct 5 08:15:17 2017 -0600

    add big file without lfs

diff --git a/.gitattributes b/.gitattributes
index 3ba8f4b..a8e5b9d 100644
--- a/.gitattributes
+++ b/.gitattributes
@@ -2,3 +2,4 @@
 *.png filter=lfs diff=lfs merge=lfs -crlf
 *.jpg filter=lfs diff=lfs merge=lfs -text
 *.bin filter=lfs diff=lfs merge=lfs -text
+*.zip filter=lfs diff=lfs merge=lfs -text
diff --git a/zip/Dieselboy - THE DESTROYER 2 - Extinction Event.mp3.zip b/zip/Dieselboy - THE DESTROYER 2 - Extinction Event.mp3.zip
new file mode 100644
index 0000000..33e7dba
--- /dev/null
+++ b/zip/Dieselboy - THE DESTROYER 2 - Extinction Event.mp3.zip
@@ -0,0 +1,3 @@
+version https://git-lfs.github.com/spec/v1
+oid sha256:66bdacf0b8e81414a864a5842085adf4d43587d8032647d6d5f08127f4fd6393
+size 263485279
```

@arvindnrbt If you're having a different problem, please open a new issue with full details about it, and I'll do my best to help :)
