### ISSUE TITLE
After git lfs install it still shows the old version when git lfs version on Windows 10

### ISSUE THREAD

**Issue by jasjuang** [git-lfs/git-lfs#2281]
I am on Windows 10.

I uninstalled git lfs 2.0.1 and downloaded the latest 2.1.1. I installed it and I run 

``````
git lfs install
git lfs version --> shows git-lfs/2.0.1 (GitHub; windows amd64; go 1.8; git 678cdbd4)
git-lfs version --> shows git-lfs/2.1.1 (GitHub; windows amd64; go 1.8.1; git 3314e287)
``````

Note that `C:\Program Files\Git LFS` is in my PATH variable and there is a git-lfs.exe inside it.

I attempted

``````
git-lfs install
git lfs version --> shows git-lfs/2.0.1 (GitHub; windows amd64; go 1.8; git 678cdbd4)
git-lfs version --> shows git-lfs/2.1.1 (GitHub; windows amd64; go 1.8.1; git 3314e287)
``````

same result. How can I make `git lfs version` show `git-lfs/2.1.1 (GitHub; windows amd64; go 1.8.1; git 3314e287)`?

**Comment by ttaylorr** [comment]
Hi @jasjuang, thanks for opening this issue!

It seems that you have multiple `git-lfs.exe`'s present on your path. One of them seems to be running version `2.0.1` of the client, so you should remove that one.

This can be confusing, since given `git xxx`, Git will look for an executable named `git-xxx.exe` somewhere on your path.

In particular, I'm thinking that this may be related to your version of Git for Windows including an older version of LFS. Could you, after removing the extra `git-lfs.exe` on your path` try and download the latest version of Git for Windows?

Please don't hesitate to re-open this issue if you have any further questions/issues.

**Comment by jasjuang** [comment]
Thanks, reinstalling git without the built in git lfs works.
