### ISSUE TITLE
runtime: failed to create new OS thread

### ISSUE THREAD

**Issue by jmoser11** [git-lfs/git-lfs#2351]
Hello,

I have a few users reporting the following error when attempting operations involving GitLFS 2.1.1. This particular error snippet was generated performing a commit:

```
runtime: failed to create new OS thread (have 911 already; errno=11)
runtime: may need to increase max user processes (ulimit -u)
fatal error: newosproc

runtime stack:
runtime.throw(0x899d58, 0x9)
      /usr/local/Cellar/go/1.8.1/libexec/src/runtime/panic.go:596 +0x95
runtime.newosproc(0xc422d5d800, 0xc42540e000)
```

Has this been seen during any build tests? Could it be related to https://github.com/golang/go/issues/19163? If so, are there plans to create a new version of GitLFS based on Go 1.9 when it releases?

Thanks!

**Comment by ttaylorr** [comment]
@jmoser11 thanks for opening this issue, and sorry that you're having trouble! I haven't seen this error appear before in either my own usage of LFS, or during any of the integration tests that we run on PRs.

That being said, I'm very curious about what's going on here. I'd first like to rule out the possibility that this could be another process consuming resources and starving LFS. I'd be curious about `sudo htop`.

Once we can rule that out, I'd be curious about LFS's own behavior. How many file descriptors does it have open? (i.e., `lsof -p $LFS_PID | wc -l`). I can't think of any operation that LFS would need to do while committing that would starve resources, so I'm not immediately sure of any follow-up questions to ask here.

> If so, are there plans to create a new version of GitLFS based on Go 1.9 when it releases?

I think we'll be well into the 2.2.x releases by then, so perhaps 2.3.0, or a 2.2.x release will be built with Go1.9. I typically like to only upgrade Go across `MAJOR` or `MINOR` version bumps, but if this problem is the fault of Go 1.8 then I think upgrading across a `PATCH` (and backporting that to other 2.x.x releases) would be pertinent.

**Comment by jmoser11** [comment]
Hi @ttaylorr,

The users haven't been able to run the tests you mentioned, so I'll go ahead and close the ticket. I'll reopen it if it turns out this is still an issue.

Thanks!
