### ISSUE TITLE
Add git-lfs into ubuntu universe repo

### ISSUE THREAD

**Issue by KOLANICH** [git-lfs/git-lfs#2354]

**Comment by technoweenie** [comment]
This would be really cool! How do we make this happen? No core contributors have much Ubuntu package experience. Any guidance, @ssgelm?

**Comment by ssgelm** [comment]
After looking into this I believe that ubuntu will fall into the same boat as debian, where they require a separate source package for each go dependency.  I believe the best way to do this would be to get the package and its deps into debian, then request it be imported into ubuntu.  That's what ubuntu recommends too: https://wiki.ubuntu.com/UbuntuDevelopment/NewPackages.  It is still a goal of mine to package all the deps as requested by debian I just have not had a chance to do so.

**Comment by ssgelm** [comment]
Yeah for sure.  I'm working on getting it into debian.  Once that's done I think the process of getting it into ubuntu should be pretty easy.

**Comment by technoweenie** [comment]
> After looking into this I believe that ubuntu will fall into the same boat as debian, where they require a separate source package for each go dependency.

This just isn't compatible with Go conventions, unfortunately. Go imports are in the format `github.com/user/repo`, which leaves no room for specifying a version. LFS specifies package versions as commit shas [through Glide](https://github.com/git-lfs/git-lfs/blob/35f66354929e3ce971192c9d2d47dbc3d4558e22/glide.lock).

So, if we want to support Debian, we'd either have to ask maintainers to throw some Git tags in there, or fork the repos into `git-lfs` and maintain them there. I don't know how comfortable I'd feel releasing debian packages for something like `github.com/bgentry/go-netrc` without the author's consent, even if it becomes `https://github.com/git-lfs/go-netrc`. But, that misses the point in having system packages that can be updated with bug/security fixes.

Another issue is this introduces a discrepancy between our Git LFS releases, which use the local `vendor` packages, and Debian releases. We use `vendor` and Glide for reproducible builds. It'll make debugging more difficult if we don't know exactly what pages are used to build Git LFS for a given bug report.

**Comment by ttaylorr** [comment]
> Go imports are in the format `github.com/user/repo`, which leaves no room for specifying a version.

I think https://gopkg.in would help with this issue. We can specify `gopkg.in/user/repo.v<tag>` which would allow us to pin to a particular version without Glide, but would introduce a dependency on the gopkg.in service being available.

> So, if we want to support Debian, we'd either have to ask maintainers to throw some Git tags in there, or fork the repos into `git-lfs` and maintain them there

I think having tags in the repositories upstream is [a good idea][1], but if that's not possible (inactive project, etc), I wouldn't mind forking them to the `git-lfs` org with permission.

[1]: https://dave.cheney.net/2016/06/24/gophers-please-tag-your-releases

> It'll make debugging more difficult if we don't know exactly what pages are used to build Git LFS for a given bug report.

I agree, but only to an extent. We can identify if the OS is Debian in the issue, and then ask for the version of the dependency packages.

**Comment by technoweenie** [comment]
> I wouldn't mind forking them to the git-lfs org with permission.

This would give us the sole responsibility for releasing and maintaining more debian packages like `git-lfs-go-netrc` or something. Now, that package isn't exactly a monster of functionality, and the author may be open to just creating some tagged releases or even sharing collaborator access with us.

Also, are you suggesting we stop using Glide and `vendor`, and rely on gopkg imports solely? It treats repositories without tags (like `go-netrc`) as unstable. Also, it'd require us to update the entire code bass any time a dependency is updated. Though on the other hand, it does give us the option to support multiple versions of the same package. Not something I'd recommend, but could be useful in a pinch.

Also, rather than having to ask everyone with problems if they're using debian, I'd much rather move towards a more uniform package situation. It may be possible to use versioned gopkg packages so that all Git LFS builds can be linked to the same exact Go code.

I think we should create some big checklist to get this done.  How do we update the packages? Who do we contact to help with versioned releases on their respective packages? How do we change the LFS build process? Can we support RPM packages too? Is it even worth the effort right now? 

@ssgelm: I really appreciate your help on LFS. I just want to get all this out there so that we don't put you in an awkward position. I think this is worth doing, but only if we can do it correctly and sustainably.

**Comment by ssgelm** [comment]
@technoweenie I totally understand your points.  A couple of things:

- Debian's (and therefore Ubuntu's) general model is that the author of an application does not need to be responsible for packaging it for inclusion in Debian.  While there are definitely authors that do that the vast majority of packages are handled by a non-affiliated maintainer.
- Debian's go library versioning uses the commit sha along with the date of the commit (for ordering).  For example, https://packages.debian.org/sid/golang-github-spf13-pflag-dev.  Given that, the only change that might be necessary is that debian has included a newer version of the dependency with breaking changes.  So far that has only seemed to happen in one case (#2390) although of course it's always a possibility.
- The majority of git-lfs' dependencies are already in debian and I'm going to upload the remaining ones in the next few days.

To be clear, debian's policy of using non-vendored dependencies makes a lot of sense in most languages because it allows for libraries to be updated without having to rebuild every package that depends on it.  The policy makes significantly less sense with golang because of the fact that it produces static binaries.  Even so, I think it's unlikely that debian will change their policy here any time soon.  There is a fair amount of demand from debian users for having the package included (https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=792075) so I still think it's worth trying to get it included.  I don't think there's a need to change the way git-lfs currently handles dependencies as regardless of what is done it's unlikely debian packaging will be able to take advantage of it anyway.

**Comment by technoweenie** [comment]
Ah, thanks for clarifying. I do feel better about the effort involved, knowing that non-affiliated package maintainers are common, and that most of the LFS deps are already packages. It sounds like we can support non vendored dependencies for debs (and RPMs too, if it makes sense) without changing how we package things _too_ much. Ideally the baseline vendored deps and package deps are kept in sync. Could even be some kind of CI test that ensures our deps are up to date.

**Comment by ssgelm** [comment]
Yeah, honestly, as scary as it sounds the actual process isn't too bad.  The only real issue so far is #2390 and it sounds like that will be fixable.

**Comment by ssgelm** [comment]
To close the loop here, git-lfs is now in ubuntu universe for artful aardvark, the current testing release:

https://launchpad.net/ubuntu/+source/git-lfs

It will be in stable universe when the next release happens in october.  New versions should automatically be pulled from debian.

**Comment by ttaylorr** [comment]
> To close the loop here, git-lfs is now in ubuntu universe for artful aardvark, the current testing release:

Fantastic work, @ssgelm -- and thank you so much for taking the lead on this. Do you think that you would have time to add some documentation to the `docs/` folder pertaining to anything special we have to do around releasing new versions of LFS? For instance, do we need to push updates to packages when we update things in `glide.yaml`? How do we publish new versions of LFS, and etc?

Forgive my ignorance, but I think that this would also be a good subject to have documented for any new maintainers.

**Comment by ssgelm** [comment]
In this case there shouldn't be anything you need to do.  Debian has tooling around watching for new releases (https://qa.debian.org/cgi-bin/watch?pkg=git-lfs) and when released I or another go packaging team maintainer will package the new version and upload it to debian (which will then be automatically imported by ubuntu after a few days).  As part of that we would check for updated dependencies and update any corresponding packages.

**Comment by ttaylorr** [comment]
@ssgelm perfect -- thank you. I just sent you an invite to join the `@git-lfs/releases` team, which I ping anytime LFS gets released. Feel free to defer updating the packages to any other Go packaging team maintainer, but I figured this will be a good way to keep you in the loop.

**Comment by KOLANICH** [comment]
Thank you, @ssgelm. Could you also bring this to zesty and xenial?

**Comment by ssgelm** [comment]
@KOLANICH as far as I know ubuntu does not pull new packages into existing releases.
