### ISSUE TITLE
test race conditions

### ISSUE THREAD

**Issue by technoweenie** [git-lfs/git-lfs#2360]
Saw some intermittent test failures trying to get https://github.com/git-lfs/git-lfs/pull/2353 out:

First, a simple go test failure. Kind of troubling that the logging outputs `second` twice:

```
--- FAIL: TestLoggerThrottlesLastWrite (0.02s)
	Error Trace:	log_test.go:149
	Error:		Not equal: "first\rsecond, done\n" (expected)
			        != "first\rsecond\rsecond, done\n" (actual)
```

Second has to do with the `migrate info (given unit)` integration test. I didn't capture the output unfortunately, but did trace it back to [this randomized repo name](https://github.com/git-lfs/git-lfs/blob/9f6ca0f22b431f020322c2bbbe4add2a12ecb2eb/test/test-migrate-fixtures.sh#L167). It returned a `/` at the front of the string, and something was trying to create that root directory.

**Comment by technoweenie** [comment]
Seeing similar issues trying to build with the `debian_7` docker img:

```
--- FAIL: TestLoggerThrottlesWrites (0.03s)
        Error Trace:    log_test.go:125
	Error:		Not equal: "first\rthird\rthird, done\n" (expected)
			        != "first\rsecond\rthird, done\n" (actual)

--- PASS: TestWaitingTaskIsThrottled (0.00s)
FAIL
FAIL	github.com/git-lfs/git-lfs/git/githistory/log	0.050s
```

**Comment by ttaylorr** [comment]
@technoweenie thanks so much for opening this up. I have seen this a few times in CI, but never experienced it locally. I ran it through with `stress` and was able to observe the failure:

```
~/g/git-lfs (master) $ go test -c -race ./git/githistory/log -run TestLoggerThrottlesLastWrite

~/g/git-lfs (master) $ stress ./log.test -test.run=TestLoggerThrottlesLastWrite -test.cpu=10
16 runs so far, 0 failures
# ...
267 runs so far, 0 failures

/var/folders/23/1bpchtnj5y71fdyttct74cs00000gn/T/go-stress146920127
--- FAIL: TestLoggerThrottlesLastWrite (0.02s)
        Error Trace:    log_test.go:149
        Error:          Not equal: "first\rsecond, done\n" (expected)
                                != "first\rsecond\rsecond, done\n" (actual)

FAIL


ERROR: exit status 1


/var/folders/23/1bpchtnj5y71fdyttct74cs00000gn/T/go-stress843499794
--- FAIL: TestLoggerThrottlesLastWrite (0.02s)
        Error Trace:    log_test.go:149
        Error:          Not equal: "first\rsecond, done\n" (expected)
                                != "first\rsecond\rsecond, done\n" (actual)

FAIL


ERROR: exit status 1

289 runs so far, 2 failures
309 runs so far, 2 failures
^C
```

**Comment by ttaylorr** [comment]
I took another look at this today, and have a better idea of what's going on. I have as well a few thoughts on things that we could do about this failure, which I would love your thoughts on 😄 .

This test is testing a scenario where a logger `Task` emits an update which gets throttled (not printed to the terminal) and is also the last update the Task emits before being `close()`'d. The logger is supposed to remember the last update, and print that to the terminal as: `"<msg>..., done\n"`.

The way that we do this is with a 15msec throttle, sleeping 10msec in a separate goroutine in order to simulate the throttle. Since there is no synchronization between the `time.Sleep()` in the goroutine and the `time.Now()` in the Logger, there's no way to guarantee that a slow or inaccurate CPU clock wouldn't cause the throttled channel write to _not_ be throttled. This is what's happening when we print `first\rsecond\r\second, done\n`. (The first `second\r` is the unthrottled write).

I think there are a few things that we could do about this:

1. Increase the distance between the throttle time and channel write delay, in the hopes of mitigating the slow/inaccurate CPU clock issue.
2. Synchronize _all_ updates emitted from a Task implementation, something like:

```go
func (l *Logger) acquire(msg string) bool {
	now := time.Now()

	// Remember the last message so we can print that when the channel is close()'d.
	l.msg = msg

	l.mu.Lock()
	defer l.mu.Unlock()

	if now.After(l.last.Add(l.throttle) {
		l.last = now
		return true
	}
	return false
}
```

3. Mock the `time` package so that we can change its behavior from within the test and guarantee that the test moves at a predictable rate.

I think that I'm in favor of 1 or 3, though perhaps 2 is more idiomatic. @technoweenie do you have any thoughts?
