### ISSUE TITLE
`git lfs migrate info` hangs at `Sorting commits: ...`

### ISSUE THREAD

**Issue by sentience** [git-lfs/git-lfs#2380]
```
$ git version
git version 2.12.2

$ git lfs version
git-lfs/2.2.0 (GitHub; darwin amd64; go 1.8.3)

$ GIT_TRACE=1 GIT_CURL_VERBOSE=1 git lfs migrate info
19:49:05.786928 git.c:595               trace: exec: 'git-lfs' 'migrate' 'info'
19:49:05.787711 run-command.c:369       trace: run_command: 'git-lfs' 'migrate' 'info'
trace git-lfs: run_command: 'git' config -l
trace git-lfs: run_command: git cat-file --batch
trace git-lfs: run_command: 'git' rev-parse HEAD --symbolic-full-name HEAD
trace git-lfs: run_command: 'git' rev-parse master --symbolic-full-name master
trace git-lfs: run_command: git rev-list --reverse --topo-order --do-walk master ^refs/remotes/origin/change-font ^refs/remotes/origin/master --
migrate: Sorting commits: ...
```

That last command hangs forever at that point. Any tips for troubleshooting?

**Comment by ltrzesniewski** [comment]
FWIW, I had this issue when my remote URL was a local directory.
Switching to a LFS-enabled https URL or removing the remote altogether fixed the issue for me.

**Comment by sentience** [comment]
@ltrzesniewski My remote was an ordinary `git@github.com:organisation/repository-name.git`, but removing it did successfully work around the hang. 👍

**Comment by ashumkin** [comment]
the same issue
removing remote resolves THIS issue
but the issue #2381 occurs

**Comment by ttaylorr** [comment]
Hi everybody, thanks for opening and commenting on this issue. I think what's going on here is a hang that occurs when there are no commits to migrate.

I took a shot at fixing this in https://github.com/git-lfs/git-lfs/pull/2383, and I'd love if you tried it out. If it works for everybody, I think it would be rad to ship this in v2.2.1 ⚡️.

Here's a list of builds for LFS's default distributions (OS, arch combos) that includes #2383. Can you give it a shot using the same remotes and command that caused it to hang earlier and let me know if it works? I'd expect the output to be blank, since there shouldn't be any commits to migrate (therefore, no files, etc).

[git-lfs-darwin-386-2.2.0.tar.gz](https://github.com/git-lfs/git-lfs/files/1124683/git-lfs-darwin-386-2.2.0.tar.gz)
[git-lfs-darwin-amd64-2.2.0.tar.gz](https://github.com/git-lfs/git-lfs/files/1124678/git-lfs-darwin-amd64-2.2.0.tar.gz)
[git-lfs-freebsd-386-2.2.0.tar.gz](https://github.com/git-lfs/git-lfs/files/1124679/git-lfs-freebsd-386-2.2.0.tar.gz)
[git-lfs-freebsd-amd64-2.2.0.tar.gz](https://github.com/git-lfs/git-lfs/files/1124682/git-lfs-freebsd-amd64-2.2.0.tar.gz)
[git-lfs-linux-386-2.2.0.tar.gz](https://github.com/git-lfs/git-lfs/files/1124680/git-lfs-linux-386-2.2.0.tar.gz)
[git-lfs-linux-amd64-2.2.0.tar.gz](https://github.com/git-lfs/git-lfs/files/1124681/git-lfs-linux-amd64-2.2.0.tar.gz)
[git-lfs-windows-386-2.2.0.zip](https://github.com/git-lfs/git-lfs/files/1124684/git-lfs-windows-386-2.2.0.zip)
[git-lfs-windows-amd64-2.2.0.zip](https://github.com/git-lfs/git-lfs/files/1124685/git-lfs-windows-amd64-2.2.0.zip)

**Comment by ashumkin** [comment]
links above contain
```
$ git lfs version
git-lfs/2.2.0 (GitHub; linux amd64; go 1.8.3; git 58f424f8)
```
I guess these are builds against 58f424f8, not f6f0648
Am I right?

**Comment by ltrzesniewski** [comment]
@ttaylorr thanks for the fix, but I'm pretty sure I had a lot of commits to migrate. Anyway, now I'm getting the following error:

```
$ git --version
git version 2.13.2.windows.1

$ git lfs version
git-lfs/2.2.0 (GitHub; windows amd64; go 1.8.3; git 58f424f8)

$ git lfs migrate import -I '*.dll'
fork/exec C:\Program Files\Git\mingw64\libexec\git-core\git.exe: The filename or extension is too long.
```

But when I did `git remote remove origin` and then retried the command it proceeded with the migration.

Unfortunately I have another issue (which was already there in v2.2.0 a99f4b21): my `.git/lfs/objects` directory ends up empty after the migration (there's just an empty `logs` directory in there but that's all). All I get is rewritten commits which include the `.gitattributes` file.

When the migration is in progress, I get a lot of files in `.git/lfs/tmp` which contain the following (deflated) content:

```
blob 42*.dll filter=lfs diff=lfs merge=lfs -text
```

Which seems weird. 

I tried to submit an issue yesterday but failed to reproduce this with a public repo, but maybe this description will hint you at something.

**Comment by ttaylorr** [comment]
> ```
> $ git lfs migrate import -I '*.dll'
> fork/exec C:\Program Files\Git\mingw64\libexec\git-core\git.exe: The filename or extension is too long.
> ```
>
> But when I did git remote remove origin and then retried the command it proceeded with the migration.

I think what's going on here is the list of refs passed to `git-rev-list(1)` exceeded the character count limit on Windows. You should be able to keep the `origin` remote in your list, and instead use the `--include-ref=` and `--exclude-ref=` instead.

> Unfortunately I have another issue (which was already there in v2.2.0 [a99f4b2](https://github.com/git-lfs/git-lfs/commit/a99f4b21e2e20fb6f470e0bb656c3c05021e4a8d)): my `.git/lfs/objects` directory ends up empty after the migration

😱 oh no! I tried to reproduce this on my own, but was unable to:

After a migration:

```diff
~/D/foo (master) $ g show HEAD
commit a65ddcf4418a78b9e414ead8a5c86c4aebfbb0e1 (HEAD -> master)
Author: Taylor Blau <me@ttaylorr.com>
Date:   Wed Jul 5 09:32:45 2017 -0600

    asdf

diff --git a/.gitattributes b/.gitattributes
new file mode 100644
index 0000000..6a6ccf5
--- /dev/null
+++ b/.gitattributes
@@ -0,0 +1 @@
+*.txt filter=lfs diff=lfs merge=lfs -text
diff --git a/hello.txt b/hello.txt
new file mode 100644
index 0000000..90353d7
--- /dev/null
+++ b/hello.txt
@@ -0,0 +1,3 @@
+version https://git-lfs.github.com/spec/v1
+oid sha256:98ea6e4f216f2fb4b69fff9b3a44842c38686ca685f3f55dc48c5d3fb1107be4
+size 3
```

my `.git/lfs/objects` directory has the object that I expect:

```
~/D/foo (master) $ tree .git/lfs/objects
.git/lfs/objects
├── 98
│   └── ea
│       └── 98ea6e4f216f2fb4b69fff9b3a44842c38686ca685f3f55dc48c5d3fb1107be4
└── logs

3 directories, 1 file
```

> I get a lot of files in `.git/lfs/tmp` which contain the following (deflated) content:

This is expected, the migrator needs to write some files to disk in order to perform the migration. I made sure that these files get removed after the migration in https://github.com/git-lfs/git-lfs/pull/2388.

**Comment by ltrzesniewski** [comment]
Actually it's the `42*.dll` part in the temporary files which seems wrong, along with the fact that I get a lot of identical files with the content I posted above.

I end up with 127k of **identical** files containing the following **uncompressed** content:

```
*.dll filter=lfs diff=lfs merge=lfs -text
```

And another 127k of **identical** files containing the following **compressed** content:

```
blob 42*.dll filter=lfs diff=lfs merge=lfs -text
```

That `42*.dll` part can't be right...

By the way I have over 500k files in the `.git/lfs/tmp` directory, maybe there should be some partitioning scheme like in `objects`. 😉 

One last thing (sorry ^^): after the import process is done, LFS tries to checkout the new head, even if you're on a bare repo, which results in an error.

**Comment by ttaylorr** [comment]
> I end up with 127k of identical files containing the following uncompressed content:
> 
> *.dll filter=lfs diff=lfs merge=lfs -text

I believe each one of these should correspond to the `.gitattributes` for each commit's root tree. These are generated each time a commit is processed, so I'd estimate that 127k is the number of commits in your migration.

> That `42*.dll` part can't be right...

This is (almost, save a `\0` NUL) the header for loose Git objects. The format is [[source]](http://public-inbox.org/git/44D42F0D.3040707@gmail.com/):

```
<OBJECT_HEADER>
	:	<OBJ_TYPE> <SP> <DECIMAL_LENGTH> <NUL>
	;

<BLOB>
	:	_deflate_( <OBJECT_HEADER> <BLOB_CONTENTS> )
	|	<COMPACT_OBJECT_HEADER> _deflate_( <BLOB_CONTENTS> )
	;

<BLOB_CONTENTS>
	:	<DATA>
	;
```

`'blob'` is the object type, then there is a space, `42` is the length of the object, then there's a NUL, then follows the object contents. 

> One last thing (sorry ^^): after the import process is done, LFS tries to checkout the new head, even if you're on a bare repo, which results in an error.

I opened up #2389 to fix.

---

Thanks for all of your feedback. This is very helpful for me 👍 .

**Comment by ltrzesniewski** [comment]
Aww I must have missed the NUL character  because I just dumped the file contents to the terminal. Thanks for the explanation, this makes sense :+1:
