### ISSUE TITLE
`git lfs migrate info` fails with "invalid cross-device link" error

### ISSUE THREAD

**Issue by ashumkin** [git-lfs/git-lfs#2381]
```
$ GIT_TRACE=2 git lfs migrate info
14:00:04.174380 git.c:557               trace: exec: 'git-lfs' 'migrate' 'info'
14:00:04.174469 run-command.c:347       trace: run_command: 'git-lfs' 'migrate' 'info'
trace git-lfs: run_command: 'git' config -l
trace git-lfs: run_command: git cat-file --batch
trace git-lfs: run_command: 'git' rev-parse HEAD --symbolic-full-name HEAD
trace git-lfs: run_command: 'git' rev-parse master --symbolic-full-name master
trace git-lfs: run_command: git rev-list --reverse --topo-order --do-walk master --
migrate: Sorting commits: ..., done                                                                                                                                                                                
rename /tmp/040452966 /data/projects/MobileApplicationsControlServer-v1/.git/objects/c8/d49f5b5760e17701079038132a32986449b51d: invalid cross-device link 
```
```
$ git lfs version
git-lfs/2.2.0 (GitHub; linux amd64; go 1.8.3; git 2fc3f7f)

$ git --version
git version 2.4.5.21.g9c7f10a

$ df -h
Filesystem                    Size  Used Avail Use% Mounted on
...
tmpfs                         7.6G  148K  7.6G   1% /tmp
...
/dev/mapper/vg_data      266G  239G   27G  90% /data
```
any suggestions?

**Comment by ttaylorr** [comment]
Hi @ashumkin, thanks for opening this issue and sorry that you're having trouble!

I think this issue occurs because of a step taken in the object saving process, wherein the object is first written to `/tmp` and then linked (via `os.Rename()`) into `.git/objects` inside of your repository.

I opened up #2382 to try and fix this, and if it works, I'd love to ship it in the v2.2.1 release.

I built #2382 into a binary for Linux on amd64 and x86-64 architectures. Would you mind giving it a shot and seeing if it works?

[git-lfs-linux-386-2.2.0.tar.gz](https://github.com/git-lfs/git-lfs/files/1124631/git-lfs-linux-386-2.2.0.tar.gz)
[git-lfs-linux-amd64-2.2.0.tar.gz](https://github.com/git-lfs/git-lfs/files/1124632/git-lfs-linux-amd64-2.2.0.tar.gz)

**Comment by ashumkin** [comment]
I confirm fix

**Comment by ioquatix** [comment]
I'm using 2.1.1 and I had to do the following:

```
sudo -u http TMPDIR=`pwd`/.git/lfs/tmp git lfs pull
```

Otherwise I got the same errors trying to copy files from /tmp to /srv/http/...

Is this supposed to be fixed or is this another issue?

**Comment by ttaylorr** [comment]
> Is this supposed to be fixed or is this another issue?

Are `/tmp` and `/srv/http` on the same volume? If so, I think that this is another issue.

**Comment by ioquatix** [comment]
`/tmp` is tmpfs.
