### ISSUE TITLE
v2.2.1: incorrect SHA-256 for 32-bit Windows .zip

### ISSUE THREAD

**Issue by dscho** [git-lfs/git-lfs#2408]
The SHA-256 of the downloaded .zip appears to be 0d6347bbdf25946f14949b50f18b9929183aefe55f6b626f8a618ae53c2220bb (instead of the claimed 1142055d51a7d70b3c2fbf184db41100457f170a532b638253991821890927b5).

**Comment by dscho** [comment]
While at it, I also wonder whether it may be possible to use a consistent directory structure inside the .zip files: v2.2.0 had `git-lfs.exe` in the top-level directory while v2.2.1 has it in the `git-lfs-windows-<cpuid>-2.2.1/` subdirectory. Whether or not the executables live in the top-level directory seems to be a bit random.

**Comment by ttaylorr** [comment]
@dscho I can confirm that the `0d6347b` SHA256 is correct for `git-lfs-windows-386.zip`. I calculated the digests on macOS, so I think the discrepancy is having to do with that. I do apologize that this happened again, the release process today is quite manual and is something that I'd like to automate in the future in order to avoid mistakes like these. 

> While at it, I also wonder whether it may be possible to use a consistent directory structure inside the .zip files: v2.2.0 had `git-lfs.exe` in the top-level directory while v2.2.1 has it in the `git-lfs-windows-<cpuid>-2.2.1/` subdirectory.

Historically I believe that we've included `git-lfs.exe` in the top level directory. I did notice while inspecting the ZIPs today that the ZIP contains instead a top-level directory, inside of which contains `git-lfs.exe`, etc.

I am happy to rebuild and ZIP the release on Windows for 2.2.1, if that would make it easier to package within Git for Windows.

---

For now, I've gone ahead and updated the release notes ([source][1]) to include the correct SHA256 for `git-lfs-windows-386.zip`.

[1]: https://github.com/git-lfs/git-lfs/releases/tag/v2.2.1

**Comment by dscho** [comment]
> I am happy to rebuild and ZIP the release on Windows for 2.2.1, if that would make it easier to package within Git for Windows.

That is not necessary, I can easily adjust the script (and [I did](https://github.com/git-for-windows/build-extra/blob/386ee850399baf9d2db7e81584c42c72356cd64b/please.sh#L2358-L2369)). 

> For now, I've gone ahead and updated the release notes (source) to include the correct SHA256 for git-lfs-windows-386.zip.

Thanks.

> I calculated the digests on macOS, so I think the discrepancy is having to do with that.

Hmm. Are the `.zip` files somehow modified after leaving your macOS box? SHA-256 is pretty much standardized and well-vetted, so it would really surprise me if macOS' `sha256sum` would so blatantly differ from the correct result.
