### ISSUE TITLE
Fail to use JFrog Artifactory 4.14.0 as LFS Server

### ISSUE THREAD

**Issue by termit9888** [git-lfs/git-lfs#2409]
Fail to use JFrog Artifactory 4.14.0 as LFS Server.
Push itself works without errors. However, I can't see any files added to Atrifactory.
![image](https://user-images.githubusercontent.com/2271333/28071022-7b4090b2-6657-11e7-869c-8ecb3ffa8cbc.png)
When try to clone repo got error 'System can not find the file specified'
![image](https://user-images.githubusercontent.com/2271333/28071682-4d929046-6659-11e7-956c-be0c43b1ab33.png)
![image](https://user-images.githubusercontent.com/2271333/28071704-618a49c2-6659-11e7-8d2e-fb59245733bb.png)
I would appreciate any help.

**Comment by ttaylorr** [comment]
Hi @termit9888, thanks for opening this issue, and sorry that you're having trouble!

From the information you provided, it sounds like Artifactory isn't processing `push`es correctly. This results in the `pull` response containing an object with `{"size":-1}` (which is invalid, [source][1]). I believe that Artifactory is trying to indicate that the file is missing/damaged. If this is the case, Artifactory should omit the object from the batch response, instead of including it with an invalid size.

That all being said, I'd recommend filing a bug in Artifactory for the invalid `size` issue, and following up there to see why your file isn't being uploaded. 

The other errors you posted seem like residual effects of the missing file.

[1]: https://github.com/git-lfs/git-lfs/blob/v2.2.1/tq/schemas/http-batch-response-schema.json#L43-L46

**Comment by termit9888** [comment]
Hello, @ttaylorr. Thank you for your response. I'll try to reach Artifactory admins to check logs etc.
