### ISSUE TITLE
LFS upload failed: missing 

### ISSUE THREAD

**Issue by fursu69** [git-lfs/git-lfs#2446]
Hello,

I have encountered a problem while doing a push. 

We have our repo setup for gitlfs. For most users it works, but one of our users can't push. He get an error like. 

```
Git LFS: (7/12) 123 MB / 321 MB
LFS upload failed:
(missing) foo1/bar(<sha>)
(missing) foo2/bar(<sha>)
(missing) foo3/bar(<sha>)
```
We tried with a fresh clone, same error and we both have admin rights on the jFrog artifactory. I tried to copy his repo and I can push. We have same versions of git and are working from the same hub. 

I tried with a fresh clone and I can still push. 

An other strange thing is that it says 7/12 when there is only 7 files if I do git lfs ls-files.
The files are not missing localy. 

We tried both git lfs pull /push to reload the references if they are not read. 

I tried to copy his .git/config and /home/$USER/.gitconfig and use the same and i can still push. 

git-lfs/2.1.1 (GitHub; linux amd64; go 1.8.1; git 3314e287)
git version 2.9.3

Any ideas what can be wrong?

**Comment by technoweenie** [comment]
That sounds like it's missing older changes to some of those files. LFS downloads objects on demand. A successful `git clone` or `git lfs clone` only downloads what it needs (which is just the latest version of every file, by default).

It sounds like there are one of two scenarios:

## 1: Using different LFS remotes?

If you're pushing to a whole new LFS server, it's very easy to end up in that situation where you're missing objects.  Easy fix is running `git lfs fetch --all` to download _everything_, so you can push it to the new remote.

```sh
$ git lfs clone my-repo # downloads 7/12 files from the latest commit
$ cd my-repo
$ git lfs fetch --all # downloads the remaining 5 files
$ git push new-remote master
```

## 2: Missing local files?

Nothing in your issue suggests multiple remotes. It's the easiest fix, so I thought I'd lead with that.

It sounds like this user added some files to their history, but then removed the file contents from `.git/lfs/objects`. Unfortunately, if the contents of that directory are lost before changes have been pushed, there's nothing we can do. Here's an example:

```sh
# my latest commit, adding 2 lfs objects
$ git show
commit 4793bc7a1f644c9dda23bed87297294f96e36f05
Author: risk danger olson <technoweenie@gmail.com>
Date:   Thu Jul 27 07:38:22 2017 -0600

    add foo files

diff --git a/bin/foo1.bin b/bin/foo1.bin
new file mode 100644
index 0000000..79cfad7
--- /dev/null
+++ b/bin/foo1.bin
@@ -0,0 +1,3 @@
+version https://git-lfs.github.com/spec/v1
+oid sha256:04dd4d85f5cbf4b7d34bff444a296f89efc2d30c33d396fb6c25757e4b87d9bb
+size 5
diff --git a/bin/foo2.bin b/bin/foo2.bin
new file mode 100644
index 0000000..b488f63
--- /dev/null
+++ b/bin/foo2.bin
@@ -0,0 +1,3 @@
+version https://git-lfs.github.com/spec/v1
+oid sha256:c739918a22764c87ac849e5c5ab4a681ca6d19c2748e434e1817df436b671f81
+size 5

# those files are in .git/lfs/objects
$ tree .git/lfs/objects
.git/lfs/objects
├── 04
│   └── dd
│       └── 04dd4d85f5cbf4b7d34bff444a296f89efc2d30c33d396fb6c25757e4b87d9bb
├── c7
│   └── 39
│       └── c739918a22764c87ac849e5c5ab4a681ca6d19c2748e434e1817df436b671f81

# remove one...
$ rm -rf .git/lfs/objects/04

$ git push origin foo
Git LFS: (1 of 2 files) 5 B / 10 B
LFS upload failed:
  (missing) bin/foo1.bin (04dd4d85f5cbf4b7d34bff444a296f89efc2d30c33d396fb6c25757e4b87d9bb)
error: failed to push some refs to 'https://github.com/github/git-lfs-test'
```

Fixes:

1. Retrieve those files from somewhere, if possible. If you put them in `.git/lfs/objects` in the right paths, the push will work.
2. Rewrite those files out of the unpushed commits.
3. Push any way, by turning on `lfs.allowincompletepush`:

```sh
$ git config lfs.allowincompletepush 1
$ git push ...
```

LFS will complain about the missing files, and you'll only get LFS pointers instead of those missing files, but you will be able to push at least.

Does this help?

**Comment by leewujung** [comment]
Just a note in case it comes in handy for someone running into the same problem. 

For whatever reason the above fixes didn't work for me, but I used [BFG-repo-cleaner](https://rtyley.github.io/bfg-repo-cleaner/) to remove all references to that specific file git lfs complains about, and was able to push successfully.

**Comment by abelbraaksma** [comment]
> Retrieve those files from somewhere, if possible. If you put them in .git/lfs/objects in the right paths, the push will work.

For anybody finding this and wondering what actually "the right path" is: if you have the OID from `git lfs lsck` or from the error mentioned above, take the first two hex digits for the top dir, then the second two hex digits for the 2nd level dir. As in the example above, the dir is `04/dd`, for the OID file starting with `04dd`:

```text
$ tree .git/lfs/objects
.git/lfs/objects
├── 04
│   └── dd
│       └── 04dd4d85f5cbf4b7d34bff444a296f89efc2d30c33d396fb6c25757e4b87d9bb
```

To restore, it is enough to just get the bare file from some backup location, recreate that dir structure, and place the file in that directory with the OID as its name. Now run `git lfs lsck` again or try to `git push` and you should be fine.
