### ISSUE TITLE
Batch download improvements on the way?

### ISSUE THREAD

**Issue by strich** [git-lfs/git-lfs#2473]
Was just wondering what the status is of a batch downloading feature in pull actions? We're finding that it is a real bottleneck in practice - A recent commit of ~1,300 small png files (<5kb) took almost 2 hours to pull down.

**Comment by ttaylorr** [comment]
@strich thanks for opening this. We're working on two features that will help this out: multipart downloads (#802) and the 'delay' capability in `git clone` and `git pull` operations (#2466).

That all being said, since it seems like you have lots of small files, I'd recommend increasing `lfs.concurrenttransfers` since the main bottleneck is probably underutilized network bandwidth.

**Comment by strich** [comment]
I would say with pretty high confidence that the majority of lfs repos (That is, video game dev repos) will contain >1,000 small files after a short amount of time. 

How come `concurrenttransfers` is so low? Is this an arbitrary number, or has someone done some analysis on it?

**Comment by ttaylorr** [comment]
> How come `concurrenttransfers` is so low? Is this an arbitrary number, or has someone done some analysis on it?

It's arbitrary; but we were discussing making it a function of `runtime.NumCPU()`. The difficulty is picking a good value that works across all types of file size distributions.

**Comment by strich** [comment]
Hrm. Unless I'm mistaken about the problem, it should not be relevant to the CPU - The only technical bottlenecks in transfer concurrency should be the number of open connections the client (And I suppose the server) can support.
