### ISSUE TITLE
Cannot push LFS files

### ISSUE THREAD

**Issue by levenlol** [git-lfs/git-lfs#2481]
Hi I've a problem with pushing lfs files. I have 0/1gb bandwith used and 0/1gb sstorage used but i still cannot push. I've tracked my lfs files but all i get when i push is this error: 

batch response: Git LFS is disabled for this repository.

How can i solve that ? I didnt manage to find a solution on google.

**Comment by ttaylorr** [comment]
Hi @levenlol, it looks like LFS was disabled on your account. I have re-enabled it, and you should be able to push again.

If you have any issues in the future, please send an email to `support@github.com`.

**Comment by VectorL1990** [comment]
Sorry I got the same issue, how can I open lFS, my account is VectorL1990

**Comment by bk2204** [comment]
Hi @VectorL1990, if you're seeing an issue with github.com, please reach out to `support@github.com` for assistance.

Thanks.

**Comment by t-jay-777** [comment]
Hei!
I have the same problem 
![Без імені](https://user-images.githubusercontent.com/48657526/71561586-c2270280-2a78-11ea-8811-bba775bf77fa.jpg)
Is there any solution?

**Comment by bk2204** [comment]
Hey,

This is a server-side issue.  You should contact your Git hosting provider and talk to them about the issue.

**Comment by wacimehadrich** [comment]
Hello :)

I have the same problem on my account, please help.

**Comment by wacimehadrich** [comment]
> Hello :)
> 
> I have the same problem on my account, please help.

i have contacted support via mailed and they got it fixed for me :)
it appears that this happens when you exceed the limit and then delete your LFS files/repository but it doesn't re-enable itself.

**Comment by kouzhudong** [comment]
我也遇到了同样的问题。

**Comment by hyeinlee-dev** [comment]
I have a error message for more than 100M files.
----------------------------------------------------------------------------------------------
$ git push origin master
batch response: Git LFS is disabled for this repository.
error: failed to push some refs to 'https://github.com/hyeinlee-dev/KAOS-backup.git'
----------------------------------------------------------------------------------------------
Please help me.
I tried to use "Repo-Cleaner". 
But I didn't work.
Thanks!

**Comment by chrisd8088** [comment]
@hyeinlee-dev, it sounds like this is an issue with GitHub due to your account being over quota.  You probably want to talk to GitHub Support about fixing your quota problem; we can't do anything here as this is just the open-source Git LFS project for the client software.  You likely need to talk to your LFS hosting provider, which in your case is GitHub, so please reach out to their Support team instead to resolve your quota issue.

**Comment by ArnabGupta2004** [comment]
Hi I've a problem with pushing lfs files. I have stable and high speed internet connection but i still cannot push. I've tracked my lfs files but all i get when i push is this error:

batch response: Git LFS is disabled for this repository.

How can i solve that ? I didnt manage to find a solution on google.

**Comment by chrisd8088** [comment]
> batch response: Git LFS is disabled for this repository.

@ArnabGupta2004 — I'm sorry you're having trouble.  Since that message indicates that your remote Git hosting service has disabled Git LFS support for your repository, you'll need to reach out to the Support team of the particular service you're trying to use and ask them for help.

You don't mention which Git storage hosting service you're using, so I can't be certain, but that particular message sounds like one which might come from GitHub.  If that's the case, they have a few [options](https://docs.github.com/en/support/contacting-github-support) for contacting their Support team.

This project is just for the open-source Git LFS client, so we can't help with problems specific to a particular Git hosting service, such as your issue appears to be.
