### ISSUE TITLE
Weird Git LFS issue when pushing

### ISSUE THREAD

**Issue by JCaraballo113** [git-lfs/git-lfs#2513]
What the heck is this? 

![lfs error](https://user-images.githubusercontent.com/6374766/29437348-6cbe0d70-8386-11e7-9be6-67d16e4a21b8.PNG)

**Comment by ttaylorr** [comment]
Hi @JCaraballo113, thanks for opening this issue, and sorry that you're having trouble. This error appears to originate from the netrc library we use:

https://github.com/git-lfs/git-lfs/blob/2ae1594579cb9a5abd97d872e83d4cebe50a400c/vendor/github.com/bgentry/go-netrc/netrc/netrc.go#L353

This, to me, indicates that your `$HOME/.netrc` may have a syntax error. Can you remove the syntax error and let me know if the error persists? This is a difficult error to report, since exposing details out of the netrc is dangerous and should be avoided, as they are sensitive.
