### ISSUE TITLE
unable to pull from repo with lfs and saml authentication using deploy key

### ISSUE THREAD

**Issue by dPeS** [git-lfs/git-lfs#2517]
Hi Guys,

Recently we anabled saml authentication in our organization and "git checkout" stopped working when using deploy key, is it normal or a bug?

Cheers,
Daniel

**Comment by technoweenie** [comment]
Can you narrow this down? Does it only break if SAML is setup, and deploy keys are used? What about SAML + SSH (with personal SSH key), or SAML + https remote?

**Comment by dPeS** [comment]
> Does it only break if SAML is setup
yes

> What about SAML + SSH (with personal SSH key), or SAML + https remote?

we want to use "url = git@github.com[...]" + deploy key registered on repo (not a user)

SAML + https remote + user password works fine
SAML + SSH (with personal SSH key) don't work by saml definition

**Comment by technoweenie** [comment]
It's my understanding that SSH keys don't work with SAML, so LFS won't either. I've raised this with the team that works on SAML, and we'll support SSH as soon as we can.

**Comment by dPeS** [comment]
> It's my understanding that SSH keys don't work with SAML,

This is not true, saml repo works normal way with deploy key. The only difference is: ssh client has only one shot to propose proper key to repo (lessons learned from life, not docs).

**Comment by technoweenie** [comment]
You are totally correct! I just got some clarification from the team that maintains SAML. We also have a fix for LFS API auth on SAML-enabled orgs that will go out once it passes review. That's why `git push` commands successfully upload objects, but then fail on some `.../verify` requests.

I'll reply and close this issue once I've verified the LFS `verify` API works on SAML orgs. If you have any further questions about SAML support on GitHub though, please go to https://github.com/contact :)

**Comment by dPeS** [comment]
so... when I could retest? Thanks!

**Comment by ttaylorr** [comment]
@dPeS thanks for checking back! @technoweenie deployed a fix for this a few days ago, so you can give this a shot whenever 👍 .

**Comment by technoweenie** [comment]
I just pushed a fix out, so you should be good to go. If not, please let me know!
