### ISSUE TITLE
Auto-pull is not run when cloning from a file path (when a directory to clone into is not explicitly specified)

### ISSUE THREAD

**Issue by jgrosso** [git-lfs/git-lfs#2523]
I can reproduce this consistently, but I can't tell why it's happening (the relevant section of [commands/command_clone.go](https://github.com/git-lfs/git-lfs/blame/master/commands/command_clone.go) doesn't look out of the ordinary to me).

1. Clone an LFS repository with `git lfs clone <url>`. Observe that there will be output of the form `Git LFS: ...` (i.e. `git lfs pull` has, in fact, run).
2. Move to another directory.
3. Run `git clone lfs <relative path to the repo cloned in step 1>`.

Observe that there will be no output of the form `Git LFS: ...` (i.e. `git lfs pull` has not, in fact, run), and that you can change directory into the repo cloned in step 3 and `git lfs pull` successfully.

**Comment by ttaylorr** [comment]
Hi @jgrosso, thanks for opening this and sorry that you're having trouble. I think this is the same issue as described in https://github.com/git-lfs/git-lfs/issues/1207#issuecomment-217455331, so I'd like to move any further discussion from here to there.

**Comment by jgrosso** [comment]
@ttaylorr Thanks for the reply! I don't think this is the same, since it works fine if a directory to clone into is specified (i.e. `git lfs clone <some repo> <directory>`). There is a `.lfsconfig` file inside the repository being cloned which is configured to use my GitHub remote, so I don't think the lack of a server is an issue.

**Comment by jgrosso** [comment]
(Or, does the `.lfsconfig` not matter at all when cloning with `git lfs clone`? If that is the case, is it a bug that `git lfs clone` works at all when a directory is explicitly specified?)

**Comment by ttaylorr** [comment]
Sort of, the behavior is a bit confusing here. Here's how `git-lfs-clone` works:

1. Take all of the arguments passed to `git-lfs-clone`, and execute `git-clone` with the same arguments. Disable smudging (downloading files from the LFS server) during the post-clone checkout.
2. Once cloned, do a parallelized smudge by trying to contact the LFS server (given by .lfsconfig, your git config, or the URL passed to `git-lfs-clone`.)

Since `git-clone` works when given a local directory, that's why you're seeing the repository appear when you run `git-lfs-clone` with a directory. However, since there is no LFS server, once the underlying `git-clone` has completed, Git LFS does not know how to download objects.

That all said, it is _probably_ a bug that `git lfs clone` works with directories.

**Comment by jgrosso** [comment]
I do have an `.lfsconfig` pointing to the correct GitHub URL, though, so wouldn't `git-lfs-clone` use that? (Sorry if I'm misunderstanding, and thanks for the help!)

**Comment by ttaylorr** [comment]
@jgrosso ah, thank you for clarifying. I don't think that this is something that we're going to fix in `git-lfs-clone`, since we are deprecating the `git-lfs-clone(1)` command.

That said, I think that this is worth taking a look at for normal `git-clone`'s. A complete fix for this would involve two parts:

1. Teaching `git clone` how to re-read the .lfsconfig in a repository if one exists, and respect those settings.
2. Teaching `git clone` how to work without an LFS server when cloning from a local/remote directory.
