### ISSUE TITLE
Support old Linux platforms?

### ISSUE THREAD

**Issue by gitfoxi** [git-lfs/git-lfs#2549]
I was wondering if there's a client I can use on RHEL3?  Old Linux will never build Go 1.8. I notice there's a bunch of server implementations in Java, Python and that would work if I wanted a server, but I'm just looking for a client. Thank you for your attention.

**Comment by ttaylorr** [comment]
Hi @gitfoxi, thanks for opening this. I'm sorry to be the bearer of bad news, but we don't currently offer builds for RHEL3, nor do we plan to. Since we can't build Go 1.8+ on older kernels, one would have to maintain their own set of patches to Git LFS that allows it to be built on earlier versions of Go.

I would personally be happy to offer pointers on how to do that, but the project itself stays on a fairly recent version of Go.

**Comment by technoweenie** [comment]
You may be able to use a pre-built linux binary from the [latest release](https://github.com/git-lfs/git-lfs/releases/latest).
