### ISSUE TITLE
got `Authentication error`. after rm some hooks, push ok, but large files can not be downloaded.

### ISSUE THREAD

**Issue by echoma** [git-lfs/git-lfs#2564]
I got `Authentication error` when pushing new large file after using git-lfs on the wiki repo of my project.

I've read #2291 and other issues it refered, and after `rm .git/hooks/pre-push` i could push again, but when i try to download [this large file](https://raw.githubusercontent.com/wiki/echoma/text_sequence_diagram/down/text_sequence_diagram_linux64_20170907.tar.gz), it shows:

```
version https://git-lfs.github.com/spec/v1
oid sha256:e16818d6bb7725865045703214f6230455ffa363bc7100fafb9e203e4fd06a92
size 66215761
```
Here are my questions:
1. What causes this `Authentication error`? Is there any FAQ or trouble shoot on this problem, I am still confused after reading these issues.
2. Whether the wiki repo of my github repo support LFS?
3. I think that my large file haven't been uploaded to github yet, my `git push` completed so quickly, so how can i push this large file to github?

Here is my operations (sorry for some Chinese charater):
```bash
{10:19}/data/github/text_sequence_diagram.wiki:master ✗ ➭ git lfs install
Updated git hooks.
Git LFS initialized.
{10:20}/data/github/text_sequence_diagram.wiki:master ✗ ➭ git lfs track "*.gz"
Tracking "*.gz"
{10:20}/data/github/text_sequence_diagram.wiki:master ✗ ➭ git add .gitattributes 
{10:20}/data/github/text_sequence_diagram.wiki:master ✗ ➭ git add down/text_sequence_diagram_linux64_20170907.tar.gz 
{10:20}/data/github/text_sequence_diagram.wiki:master ✗ ➭ git commit -m "add tgz"
[master d89172a] add tgz
 2 files changed, 4 insertions(+)
 create mode 100644 down/text_sequence_diagram_linux64_20170907.tar.gz
{10:20}/data/github/text_sequence_diagram.wiki:master ✓ ➭ git lfs ls-files
e16818d6bb * down/text_sequence_diagram_linux64_20170907.tar.gz
{10:21}/data/github/text_sequence_diagram.wiki:master ✓ ➭ git push origin master
Username for 'https://github.com': fatmck@163.com
Password for 'https://fatmck@163.com@github.com': 
Username for 'https://github.com': fatmck@163.com
Password for 'https://fatmck@163.com@github.com': 
ERROR: Authentication error: Authentication required: You must have push access to verify locks
error: 无法推送一些引用到 'https://github.com/echoma/text_sequence_diagram.wiki.git'
{10:21}/data/github/text_sequence_diagram.wiki:master ✓ ➭ 
{10:32}/data/github/text_sequence_diagram.wiki:master ✓ ➭ rm .git/hooks/pre-push
{10:32}/data/github/text_sequence_diagram.wiki:master ✓ ➭ git push
Username for 'https://github.com': fatmck@163.com
Password for 'https://fatmck@163.com@github.com': 
对象计数中: 5, 完成.
Delta compression using up to 4 threads.
压缩对象中: 100% (5/5), 完成.
写入对象中: 100% (5/5), 591 bytes | 0 bytes/s, 完成.
Total 5 (delta 1), reused 0 (delta 0)
remote: Resolving deltas: 100% (1/1), completed with 1 local object.
To https://github.com/echoma/text_sequence_diagram.wiki.git
   bd62e67..d89172a  master -> master
{10:32}/data/github/text_sequence_diagram.wiki:master ✓ ➭ 
```

`git lfs env` shows:
```
git-lfs/2.2.1 (GitHub; linux amd64; go 1.8.3; git 621d1f82)
git version 2.11.0

Endpoint=https://github.com/echoma/text_sequence_diagram.wiki.git/info/lfs (auth=basic)
LocalWorkingDir=/data/github/text_sequence_diagram.wiki
LocalGitDir=/data/github/text_sequence_diagram.wiki/.git
LocalGitStorageDir=/data/github/text_sequence_diagram.wiki/.git
LocalMediaDir=/data/github/text_sequence_diagram.wiki/.git/lfs/objects
LocalReferenceDir=
TempDir=/data/github/text_sequence_diagram.wiki/.git/lfs/tmp
ConcurrentTransfers=3
TusTransfers=false
BasicTransfersOnly=false
SkipDownloadErrors=false
FetchRecentAlways=false
FetchRecentRefsDays=7
FetchRecentCommitsDays=0
FetchRecentRefsIncludeRemotes=true
PruneOffsetDays=3
PruneVerifyRemoteAlways=false
PruneRemoteName=origin
AccessDownload=basic
AccessUpload=basic
DownloadTransfers=basic
UploadTransfers=basic
git config filter.lfs.process = "git-lfs filter-process"
git config filter.lfs.smudge = "git-lfs smudge -- %f"
git config filter.lfs.clean = "git-lfs clean -- %f"
```

**Comment by ttaylorr** [comment]
Hi @echoma, thanks for opening this issue. Here are my best answers to your questions:

> What causes this `Authentication error`? Is there any FAQ or trouble shoot on this problem, I am still confused after reading these issues.

I'm curious to get @rubyist's perspective here, but I don't believe that we support the lock verification step done in the pre-push hook on Wiki repositories. If true, this would point to why removing the `.git/hooks/pre-push` solves the problem.

> Whether the wiki repo of my github repo support LFS?

Yes and no. By circumventing the lock verification done in the pre-push step, you can push LFS objects to your repository, since Wikis are a Git repository just like any other. That said, referencing a large object in the body of your Wiki will not display it correctly (to my best knowledge), so I don't know if it would be worthwhile to push LFS objects to your wiki in the first place.

> I think that my large file haven't been uploaded to github yet, my `git push` completed so quickly, so how can i push this large file to github?

There are a couple of things that could be going on here:

1. Your large objects _were_ pushed to GitHub, and all that was left to push were the tiny pointer files accompanying them. If this is the case, it is expected that the `git push` operation would not take very long.
2. Your large objects were _not_ pushed to GitHub, but the push that you are executing does not cover any references that have commits containing LFS objects reachable within them. In other words, if you have LFS objects on branch `my-feature`, but are pushing `master`, there are no LFS objects to scan in the first place, thus, none will be uploaded.

**Comment by echoma** [comment]
Thanks a lot, ttaylorr.
I uploaded my large files to a normal repo instead, lfs works fines.
