### ISSUE TITLE
Annoying error about missed object

### ISSUE THREAD

**Issue by gurugray** [git-lfs/git-lfs#2581]
We have a missed object in our old git history
Periodically we need to fetch all objects

```
git lfs fetch --all
Scanning for all objects ever referenced...

✔ 130641 objects found                                                                                                                                
Fetching objects...
Git LFS: (21 of 22 files) 941.59 KB / 962.45 KB                                                                                                      
LFS: Repository or object not found: https://github.server/storage/lfs/13581/objects/7b13a13f329cb4679c1e99dd145efb9aee4b4786cdf9af201f5464a6e2f3a2ee?token=0
Check that it exists and that you have proper access to it
Warning: errors occurred
```

How can we get rid of this message?
How can we mark this object as missed?

**Comment by technoweenie** [comment]
There isn't any way right now. Though, being able to delete objects from the server, and have LFS just tolerate missing objects, is a common request. Tackling this is in our backlog, but not scheduled yet. It's pretty high on the list though.

There are currently a few config options you can try, but it won't affect `git lfs fetch`:

* `lfs.allowincompletepush` - Spews warnings of missing local files on push, but still completes the git push. Default: enabled.
* `lfs.skipdownloaderrors` - Ignores download errors in the Git smudge feature. Leaves LFS pointers if the file is missing, instead of breaking the current Git checkout.

**Comment by gurugray** [comment]
Thanks for your response!
We already use this options, but as you told  it's affect `fetch`.

Is there an issue about it to watch it further?

**Comment by technoweenie** [comment]
The backlog pointed to an old issue. I created one specifically to discuss an object expire proposal instead: https://github.com/git-lfs/git-lfs/issues/2623

Closing this, we can chat there :)
