### ISSUE TITLE
jar file gets corrupted when cloning

### ISSUE THREAD

**Issue by lucananni93** [git-lfs/git-lfs#2724]
Hi everybody, I'm having a problem using Git LFS for tracking the JAR files in my repository.
Currently my repository contains one JAR file (having a dimension of around 100 Mb).
I tracked JAR files using the command `git lfs track "*.jar"`, but since JAR files are binary I changed the relative line in `.gitattributes` to `*.jar filter=lfs binary` (instead of the default generated `*.jar filter=lfs diff=lfs merge=lfs -text`).

The problem is that when I try to clone my repository in a brand new place and try to execute the JAR file inside (`java -jar jarFile.jar`) java tells me that the JAR is corrupted. 
Of course I've cheked and the original file (the one on my local machine) is intact and fully functioning.

Thanks for your support.

Luca

**Comment by technoweenie** [comment]
> The problem is that when I try to clone my repository in a brand new place and try to execute the JAR file inside

Did you install LFS in the new place? Without it, Git will only download an LFS pointer for it. 

1. Install Git LFS to your new machine.
2. Run `git lfs pull` in local repository clone.

**Comment by ttaylorr** [comment]
> but since JAR files are binary I changed the relative line in `.gitattributes` to `*.jar filter=lfs binary` (instead of the default generated `*.jar filter=lfs diff=lfs merge=lfs -text`).

I think that this is perhaps unnecessary, and may even be causing the issue. The `-text` directive (note the `-` prefix) instructs Git to _not_ treat tree entries matching that pathspec as text, thus I think that adding `binary` is _at least_ redundant.

That said, the most common/likely issue here is that LFS is not installed in the correct place, and @technoweenie's comment above explains how to do that. As he said, without LFS installed correctly, you'll only retain the LFS pointer for the JAR file, not the JAR itself, which would in all cases "corrupt" the JAR.

Can you try removing the "binary" flag, making sure that Git LFS is installed correctly, and then try again?

I'm going to close this issue in the meantime since it hasn't had any activity on it for a while, but please don't hesitate to comment here if the above doesn't work for you, and I'd be happy to dig in further.
