### ISSUE TITLE
git lfs ls-files output format not parsable when there are spaces in path

### ISSUE THREAD

**Issue by kforner** [git-lfs/git-lfs#2771]
Hi ,
In the event of additional columns, the ouput of `git lfs ls-files` would be ambiguous when there are spaces in the file path:

```
a39a1b806f * dir1/dir2/foo bar xtra_value1
d0b29ae1f4 * dir1/dir2/bar_foo xtra_value2
```
My suggestion:
- either quote the path 
- or use \t as field separators

The problem is that it breaks the existing output.

**Comment by ttaylorr** [comment]
Hi @kforner, thanks for your suggestion. Since `git-lfs-ls-files(1)` doesn't have multiple columns (save the `--size` flag), I'm going to close this since it isn't an immediate issue. That said, if/when we introduce information, I think that adding a `-0` option (a-la Git) to separate the output with a `NUL` byte would be sensible.

**Comment by kforner** [comment]
>I'm going to close this since it isn't an immediate issue.

ok

> I think that adding a -0 option (a-la Git) to separate the output with a NUL byte would be sensible.

Why not, but using \t is much more common, and even recommended (TSV files) for tabulated text files. And it is human readable.

**Comment by peflo** [comment]
I'd like to second this - I'm working on a script right now to automatically extract compressed files stored in lfs and that would certainly simplify things.  (A 'short' option to print only the names themselves could also be handy)
