### ISSUE TITLE
Git-LFS can't work with complex path on Windows 10

### ISSUE THREAD

**Issue by OMICRON3069** [git-lfs/git-lfs#2782]
I put my git directory into a Windows onedrive folder like this:
```
D:\Download\OneDrive\OneDrive - <my-email>\<path-to-directory>\
```
So, if i run `git lfs track`, it will not respond.

And while I push to my serve, it will tell me:
```
Unable to create lock system: init lock cache: readlink D:\Download\OneDrive\OneDrive - <my-email>\<path-to-directory>\.git\lfs: The system cannot find the file specified.
error: failed to push some refs to 'git@xxxx.com:OMICRON3069/xxxxxx.git'
```
Also, if I put my git directory into another directory such as `E:\`, it works fine~ 

Git Version: Git-2.15.1.2-64-bit
Git-LFS Version: git-lfs-windows-2.3.4
Windows Version: Windows 10 1709; OS Build: 16299.125

**Comment by HowcanoeWang** [comment]
Same problem

**Comment by ttaylorr** [comment]
Hi @OMICRON3069 and @HowcanoeWang, thanks for opening this and I'm sorry that you're having trouble. Git LFS used to have a wrapper package around `os` (responsible for things like this) that ported a not-yet-landed change in Go that would read long paths in Windows 8 and better, but has since gotten rid of this.

We make use only of the standard library's `os` package, so I think that this is a bug there. Can you please open an issue on the Go repository and link it back here?

**Comment by asishm** [comment]
Has there been an issue opened on the Go repository? Having the same issues, when my repo sits on my One Drive folder on windows 10. I'm not familiar about the exact Go issue so I'm not sure about how to illustrate the issue or I'd have done this.

**Comment by ttaylorr** [comment]
> Has there been an issue opened on the Go repository?

There are quite issues on golang/go that mention both "path" and
"Windows" in the open state [1], but one that seemed particularly
relevant is [2].

[1]: https://github.com/golang/go/search?q=is%3Aissue+is%3Aopen+windows+path&type=Issues
[2]: https://github.com/golang/go/issues/27029
