### ISSUE TITLE
Implement auto-locking option for files that have been modified in the working area

### ISSUE THREAD

**Issue by SamiSamoiel** [git-lfs/git-lfs#2801]
I am not an experienced user of git/git-lfs and therefore my suggestion might be unreasonable but it would be very useful to be able to configure a repository to automatically lock some difficult to merge files if they are modified in the working area:
git lfs autolock '*.bin'

The locking could be triggered by the command that SourceTree uses when a project is refreshed (I think it's a diff command).

This feature would build on the currently developed locking mechanism.

**Comment by technoweenie** [comment]
That's an interesting idea. You can actually mark files as lockable today:

```sh
$ git lfs track "*.bin" --lockable
Tracking "*.bin"

$ cat .gitattributes
*.bin filter=lfs diff=lfs merge=lfs -text lockable
```

This tells LFS to make the files read-only, forcing you to lock them before making changes.

```sh
$ ls -al
total 24
drwxr-xr-x  5 rick  staff  160 Dec  4 09:37 .
drwxr-xr-x  9 rick  staff  288 Dec  7 11:23 ..
-r--r--r--  1 rick  staff  126 Dec  4 09:36 again.bin
-r--r--r--  1 rick  staff  126 Dec  4 09:37 b.bin
-r--r--r--  1 rick  staff    3 Nov 17 13:08 hi.bin

$ cat hi.bin
hi

$ echo "hello" >> hi.bin
zsh: permission denied: bin/hi.bin
```

The file is then made writeable once you lock it.

```sh
$ git lfs lock hi.bin
$ echo "hello" >> hi.bin

$ cat bin/hi.bin
hi
hello

$ git lfs locks
bin/hi.bin	technoweenie	ID:4271
```

**Comment by SamiSamoiel** [comment]
Thanks technoweenie, I wasn't aware of this feature and will try it out once bitbucket supports locking and is deployed at my work organisation; 

however, I believe the auto locking feature would provide a more seamless user experience that would prevent most conflicts without adding overhead. This is especially true if the work process/work segmentation should already prevent conflicts and the locking mechanism is used as a safeguard against human error.

**Comment by ttaylorr** [comment]
Hi @SamiSamoiel, thanks for opening this issue. That looks like a great suggestion to me. Just to clarify, the behavior that you're looking for is that Git LFS would detect when files that are "auto-lockable" are modified, and then automatically acquire the lock, or warn the user if the lock is already held?

I agree, and think that something like this would be useful to users of the locking feature.

My immediate question is concerning what time would be most appropriate to try and acquire the lock. Without significant effort in writing an always-running Git LFS "daemon" (which is something that I'd like to avoid, anyway) I think we're limited to Git hooks. Of the hooks available, I think that the `pre-commit` (https://github.com/git/git/blob/master/templates/hooks--pre-commit.sample) hook is the earliest that we could reasonably catch these.

Of course, one way to "harden" this check is to also cause certain LFS commands to inspect the state. This, however, becomes burdensome since the locking API necessitates a round-trip network request. I do not want to block `git lfs status` (for example) on a network request.

What do you think?

**Comment by technoweenie** [comment]
The problem is that if you're _not_ using the `lockable` attribute, then the files will be checked out with read/write privileges. Meaning anyone on any local clone can update these files without grabbing a lock first. You may find that you lost the "lock race" by waiting until a `pre-commit` hook. Redoing work is no fun. I'd prefer to be notified _before_ I start work.

I understand you want LFS locking capabilities in a general purpose Git tool like SourceTree. However, I don't think using `pre-commit` hook, or somehow integrating with SourceTree through a `diff` command is the best way. I'd prefer tools choose to implement locking support _with_ LFS. The [GitHub Unity](https://unity.github.com) tool lets you lock and unlock from the GUI, annotating the icons with a little lock icon. This seems closer to how version control systems with locking tend to work.

**Comment by ttaylorr** [comment]
> Redoing work is no fun. I'd prefer to be notified _before_ I start work.

Agreed; I think that that sufficiently covers the case that @SamiSamoiel is looking for here.
