### ISSUE TITLE
Push fails with MISSING file error

### ISSUE THREAD

**Issue by xkrys** [git-lfs/git-lfs#2813]
I commited some png files but lfs can't push.

```
$ git lfs status

On branch master
Git LFS objects to be pushed to origin/master:

        phone/qml/images/icon_appli-assets/icon_fleche.png (%!s(MISSING))
        phone/qml/images/icon_appli-assets/icon_fleche@2x.png (%!s(MISSING))
        phone/qml/images/icon_appli-assets/icon_fleche@3x.png (%!s(MISSING))
        phone/qml/images/icon_appli-assets/icon_fleche@4x.png (%!s(MISSING))
        phone/qml/images/icon_appli-assets/icon_quit@3x.png (%!s(MISSING))

Git LFS objects to be committed:

Git LFS objects not staged for commit:
```

See attached [push.log](https://github.com/git-lfs/git-lfs/files/1611827/push.log)

Environment:

- OS: Windows 7
- LFS: 2.3.4
- Git : 2.15.1.windows.2

**Comment by ttaylorr** [comment]
Hi @xkrys, thanks for opening this and I'm sorry that you're having trouble! I think there are two issues going on here:

1. The `(%!s(MISSING))` issue that you're seeing show up in the output of `git lfs status` is a known bug which was fixed in https://github.com/git-lfs/git-lfs/pull/2746. This is scheduled for the next release, which has is not out yet.

2. The failure to push looks like a networking issue with either your host or server, from the part of the push.log that you have attached. It, at the bottom, notes that there is an I/O timeout, which has something to do with the way that your server, or the connection between your client and server is configured. This is a configuration issue, and does not pertain to LFS, so a better place to follow up with this would be support@github.com

**Comment by xkrys** [comment]
Thanks @ttaylorr , you were right it was a proxy configuration issue. It works fine now!
