### ISSUE TITLE
Installer fails on Windows under MINGW64 Git Bash

### ISSUE THREAD

**Issue by macfisher** [git-lfs/git-lfs#2844]
I ran into the same issue as https://github.com/git-lfs/git-lfs/issues/919 and I will just provide the same image that was posted there: https://imgur.com/SjfCDXk

That issue was closed but the issue was never resolved. The installer creates a 'Git LFS' directory based on the user's choice of directory, but the user must then manually move the git-lfs.exe file from that directory and place it into the /mingw64/bin directory in GitBash. The Windows path for me was: C:\Program Files\Git\mingw64\bin

Once git-lfs.exe is manually placed inside the mingw64/bin dir then the user can run 'git lfs install' and should get the 'Git LFS initialized.' message. In my opinion, I think either the installer needs to be fixed to work as documented or the documentation needs to be fixed to guide Windows users on how to manually install.

Thank you, I look forward to using Git LFS on my new project!

**Comment by ttaylorr** [comment]
Hi @macfisher thanks for opening this issue and sorry that you're having trouble! I'm not sure why the original issue was closed (perhaps it was fixed at one point and then broken again?) but I am happy to dive in here.

I am not too familiar with the Git LFS installer code for Windows, but @sschuberth may have some ideas. Ping!

**Comment by sschuberth** [comment]
> That issue was closed but the issue was never resolved.

That's not true. Issue #919 was resolved by the reporter himself even with an [explanation what had fixed the issue](https://github.com/git-lfs/git-lfs/issues/919#issuecomment-168780039). Basically, it was a user error trying to run 64-bit `git-lfs` on 32-bit Windows.

>The installer creates a 'Git LFS' directory based on the user's choice of directory, but the user must then manually move the git-lfs.exe file from that directory and place it into the /mingw64/bin directory in GitBash.

Now *that's* another issue than #919. It's basically a duplicate of #2587. Ever since Git for Windows started to ship with its own version of `git-lfs`, it's somewhat unclear what the user expects if he / she also installs upstream Git LFS. Which installation should take precedence? The one that was installed last? The most recent version? Actually, my vote on this would be to talk to the Git for Windows maintainer and ask him to stop including Git LFS again.

**Comment by macfisher** [comment]
Well that's interesting, because the #2587 issue claims that the system detected the git-lfs.exe in C:\Program Files\Git LFS? That would be a separate issue since my system did not come with Git LFS installed by default and when I ran the upstream Git LFS installer it installed to C:\Program Files\Git LFS and the system was unable to detect that installation when I ran a 'git lfs install'.

I appreciate the responses here and I understand the dilemma with the installer. It seems like Git for Windows should come with LFS installed and not cause any issues since, in my case, it wasn't able to run outside of mingw\bin anyways, so I do not see how the system would detect two versions. And if the user wants to install it manually then they just need to figure out that git-lfs.exe needs to be moved manually to mingw\bin.
