### ISSUE TITLE
Ubuntu Artful 404s

### ISSUE THREAD

**Issue by joerenzullo** [git-lfs/git-lfs#2859]
Err:13 https://packagecloud.io/github/git-lfs/ubuntu artful Release                              
  404  Not Found [IP: 52.219.20.97 443]
E: The repository 'https://packagecloud.io/github/git-lfs/ubuntu artful Release' does not have a Release file.

**Comment by ttaylorr** [comment]
Hi @joerenzullo, thanks for opening this issue. Support for Artful is new since 2.3.0 (https://github.com/git-lfs/git-lfs/pull/2704) and thus has not been included in the 2.3.x series.

Git LFS v2.4.0 will be released to Artful, and in the meantime you can build Git LFS yourself by following the instructions in the README.
