### ISSUE TITLE
Clarify the format of `expires_at` in the `git-lfs-authenticate` response

### ISSUE THREAD

**Issue by dpursehouse** [git-lfs/git-lfs#2861]
The [documentation for the `git-lfs-authenticate` command](https://github.com/git-lfs/git-lfs/blob/master/docs/api/authentication.md#ssh) shows an example of the response including an `expires_at` value:

`"expires_at": "2016-11-10T15:29:07Z"`

There are a couple of things about this.

1. Why does it only have second resolution?  Wouldn't millisecond resolution be better, i.e. something like `2016-11-10T15:29:07.123Z`?  Or is it expected that `expires_in` should be used if millisecond resolution is needed?

2. Is the timezone expected to be in UTC, or can it include a different timezone indicator if the server's timezone is not UTC?  I.e. something like `2016-11-10T15:29:07+01:00`

**Comment by ttaylorr** [comment]
Hi @dpursehouse, thanks for opening this issue as always 😄. I agree that these could use further clarification. Since we're depending on Go's implementation of `time.Time.{Unm,M}arhshalJSON`, the implementation would technically accept any valid [RFC3339][1] value.

With regards to your questions:

> Why does it only have second resolution? Wouldn't millisecond resolution be better, i.e. something like `2016-11-10T15:29:07.123Z`? Or is it expected that `expires_in` should be used if millisecond resolution is needed?

As above, `expires_at` will accept any [RFC3339][1] value. Either `expires_at` or `expires_in` would be fine for this purpose, and the spec should be changed to reflect that.

I believe that this answers your second question as well 😄.

##

I would be happy to codify this in the specification. Is this a topic that you'd be interested in submitting a patch for? If not, I would be happy to change it myself. Let me know!

[1]: https://tools.ietf.org/html/rfc3339

**Comment by dpursehouse** [comment]
Actually while I was looking at the documentation locally to see where to add this information, I noticed that in the [batch API documentation](https://github.com/git-lfs/git-lfs/blob/master/docs/api/batch.md#successful-responses) it describes `expires_at` as an ISO 8601 formatted timestamp.
