### ISSUE TITLE
Git LFS still disabled after clearing up storage

### ISSUE THREAD

**Issue by Kevinvdbij** [git-lfs/git-lfs#2862]
I got my Git LFS disabled by going over the storage limit accidentally. I have deleted the repository that filled up my allowed storage usage but I still receive the "Git LFS is disabled for this repository" message when trying to push.

**Comment by ttaylorr** [comment]
Hi @Kevinvdbij, thanks for opening this issue and I'm sorry that you're having trouble! By the looks of it, this issue seems to pertain to Git LFS usage on GitHub.com, not with Git LFS the tool itself. This repository doesn't respond to inquires about the former, but support@github.com can definitely help you out!

Would you mind sending them an email instead? Thanks!

**Comment by faysalhossain2007** [comment]
Did it help after contacting to support? They are not replying me back. And it has already been 8 days since I reported my problem to support.
