### ISSUE TITLE
Team Of 4 Smudge Error Cannot Push or Clone!

### ISSUE THREAD

**Issue by MattSowards** [git-lfs/git-lfs#2869]
Hi! I work with a team of 4 others and it seems 2 out of 4 people can clone the project and upload files, out of the other 2, 1 of them cant even clone it, and the other 1 cant push files. I currently only have the logfile of the 1 that can't even clone it, since it seems his is more serious. They've attempted to re-clone it which has costed me to raise my Git LFS Storage bandwidth up to $30 a month.

Here is the logfile
git-lfs/2.3.4 (GitHub; windows amd64; go 1.8.3; git d2f6752f)
git version 2.16.1.windows.1

$ git-lfs.exe filter-process
Error downloading object: Content/AmmoSet/MasterMaterial/M_MasterMaterial_Label.uasset (3036600): Smudge error: Error downloading Content/AmmoSet/MasterMaterial/M_MasterMaterial_Label.uasset (3036600bd0df731c002b02cce1064580f3a0bf9866b07733ba1c9f85f2f44c38): batch response: Git credentials for https://github.com/MattSowards/BattleForItAll.git/info/lfs not found:
exit status 1

Git credentials for https://github.com/MattSowards/BattleForItAll.git/info/lfs not found:
exit status 1

Current time in UTC: 
2018-02-15 13:08:37

ENV:
LocalWorkingDir=C:\Users\Philip\Documents\Unreal Projects\BattleForItAll
LocalGitDir=C:\Users\Philip\Documents\Unreal Projects\BattleForItAll\.git
LocalGitStorageDir=C:\Users\Philip\Documents\Unreal Projects\BattleForItAll\.git
LocalMediaDir=C:\Users\Philipr\Documents\Unreal Projects\BattleForItAll\.git\lfs\objects
LocalReferenceDir=
TempDir=C:\Users\Philip\Documents\Unreal Projects\BattleForItAll\.git\lfs\tmp
ConcurrentTransfers=3
TusTransfers=false
BasicTransfersOnly=false
SkipDownloadErrors=false
FetchRecentAlways=false
FetchRecentRefsDays=7
FetchRecentCommitsDays=0
FetchRecentRefsIncludeRemotes=true
PruneOffsetDays=3
PruneVerifyRemoteAlways=false
PruneRemoteName=origin
LfsStorageDir=C:\Users\Philip\Documents\Unreal Projects\BattleForItAll\.git\lfs
AccessDownload=none
AccessUpload=none
DownloadTransfers=basic
UploadTransfers=basic
GIT_ASKPASS=C:\Users\Philip\AppData\Local\GitHubDesktop\app-1.0.13\resources\app\static\ask-pass-trampoline.bat
GIT_CONFIG_PARAMETERS='credential.helper='
GIT_DIR=.git
GIT_EXEC_PATH=C:\Users\Philip Ritmeester\AppData\Local\GitHubDesktop\app-1.0.13\resources\app\git\mingw64\libexec\git-core
GIT_LFS_PATH=C:\Program Files\Git LFS
GIT_LFS_PROGRESS=C:\Users\PHILIP~2\AppData\Local\Temp\GitHubDesktop-lfs-progress-rCkDZK\GitHubDesktop-lfs-progress
GIT_TERMINAL_PROMPT=0
GIT_TRACE=0
LOCAL_GIT_DIRECTORY=C:\Users\Philip\AppData\Local\GitHubDesktop\app-1.0.13\resources\app\git

**Comment by ttaylorr** [comment]
> Git credentials for https://github.com/MattSowards/BattleForItAll.git/info/lfs not found:
> exit status 1

Hi @MattSowards, sorry that you and your team are having trouble! I think that the above line looks like the culprit to me. It seems that your credential helper doesn't know the correct credentials for using LFS. Can you make sure that your credential helper is configured correctly?

I'm going to ping @shiftkey here, since it looks like this is using GitHub Desktop.

**Comment by MattSowards** [comment]
I see, What do you recommend I tell my team member to do in this regards?

**Comment by shiftkey** [comment]
@MattSowards can you open a new issue over in https://github.com/desktop/desktop as there's an additional log file that will help troubleshooting?

I'm tracking this issue https://github.com/desktop/desktop/issues/3752 about this batch file not being executed correctly for some users due to unexpected characters in the file path, but your file path seems to be fine looking at that dump from Git LFS.

**Comment by MattSowards** [comment]
I did
