### ISSUE TITLE
Spec URL points to invalid location

### ISSUE THREAD

**Issue by mlucool** [git-lfs/git-lfs#2877]
I see the following invalid url from commands like git blame: [https://git-lfs.github.com/spec/v1](https://git-lfs.github.com/spec/v1)

A quick [search](https://github.com/git-lfs/git-lfs/search?utf8=✓&q=https%3A%2F%2Fgit-lfs.github.com%2Fspec%2Fv1&type=) indicates this is only used in code in a few places so it should not be hard to replace.

**Comment by ttaylorr** [comment]
Hi @mlucool, thanks for opening this issue and letting me know! This URL is used to indicate a particular version of the LFS pointer format, so that if we changed the format in the future, we'd have a feature in the file that could distinguish the two. In other words, just the fact that the pointers currently generated by Git LFS _contain_ this string (whether or not it points to an extant location on the web) is what Git LFS cares about.

That all said, I think that we ought to put something on this page, or at least redirect it to https://git-lfs.github.com (which does contain content).

_That_ all said (😄) I think that the best place to have this discussion is https://github.com/git-lfs/git-lfs.github.com, where the website lives. Can you reopen this issue there?
