### ISSUE TITLE
git lfs migrate info returns cryptic errror... What does it mean?

### ISSUE THREAD

**Issue by jeffreydwalter** [git-lfs/git-lfs#2881]
If I run `git lfs migrate info`

I get the following output:
```
migrate: Fetching remote refs: ..., done                                                                                                                                                                                                    
Error in git rev-list --stdin --reverse --topo-order --do-walk --: exit status 128 fatal: bad revision '^refs/remotes/tags/origin/6.2.2008'
```

What does this message imply? How do I fix this issue?

**Comment by ttaylorr** [comment]
Hi @jeffreydwalter, thanks for opening this issue! This message comes from Git, and indicates that one fo the revisions that it tried to walk does not exist. Di you run the command with `--include-ref` or `--exclude-ref`, by chance? If not, could you share the repository with me (if it's open-source) so that I can give things a whirl?

**Comment by ttaylorr** [comment]
Hi @jeffreydwalter, thanks for opening this issue! This message comes from Git, and indicates that one fo the revisions that it tried to walk does not exist. Di you run the command with `--include-ref` or `--exclude-ref`, by chance? If not, could you share the repository with me (if it's open-source) so that I can give things a whirl?

**Comment by jeffreydwalter** [comment]
Hey @ttaylorr I think I figured out what was going on. I was actually trying to fix a missing LFS object issue I was having. My issue was caused because I had accidentally enabled Git LFS in bitbucket and had a .lfsconfig in my repo pointing to an Artifactory server. My object was missing because it got replicated to Artifactory, but the git lfs pull/fetch/etc commands were looking at the Git LFS server, and it wasn't there. VERY CONFUSING! :)

Going to close this one, thanks again!
