### ISSUE TITLE
pre-push hook behaviour for alternative LFS client implementation

### ISSUE THREAD

**Issue by palmin** [git-lfs/git-lfs#2886]
I'm working on a LFS client implementation for iOS and unsure as how to behave in the pre-push hook when the branch does not exist on the remote. Looking at
https://github.com/git-lfs/git-lfs/blob/2f7b3481866c07e96d05e25f840666ee3fce11e0/commands/command_pre_push.go#L36
I understand this to mean that all LFS-blobs from the current branch head and to the root commit should be pushed.

In many cases this seems like it would be almost all LFS-blobs that are pushed every time a new branch is pushed, which makes me think I do not understand this correctly.

It could also be the case that uploading already existing objects as cheap, such that it does not matter, or that only a few of the LFS objects will in practice be available in .git/lfs/objects/ 

Could anyone confirm the behaviour in the pre-push hook when pushing a new branch?

**Comment by ttaylorr** [comment]
Hi @palmin thanks for opening this, and giving me the chance to dig through some of this code -- the paths for determining which objects to scan and upload are quite lengthy, so it's good to get a refresher from time to time 😄. Here are two immediate answers to your questions:

> I understand this to mean that all LFS-blobs from the current branch head and to the root commit should be pushed.

This is not the case. In this case, LFS will eventually invoke Git with the command: `git rev-list ... --not --remotes=$remote`. This `--not --remotes=...` combination effectively prevents any objects (in `--objects` mode) present in any reference on the remote from being shared in the output ([[1]](https://git-scm.com/docs/git-rev-list#git-rev-list---not), [[2]](https://git-scm.com/docs/git-rev-list#git-rev-list---remotesltpatterngt)).

> It could also be the case that uploading already existing objects as cheap, such that it does not matter, or that only a few of the LFS objects will in practice be available in .git/lfs/objects/

This is somewhat the case. As much as LFS can reasonably do, it will attempt to prevent uploading/downloading objects that already exist on the remote, or locally (respectively). In the uploading case, implementers of the API specification are allowed to not respond with upload actions, which is meant to indicate to the client that the remote already has the object and is uninterested in it being uploaded again.

In other words, the price you'll pay in most implementations of the Git LFS API for attempting to upload an object that already exists is a few extra handfuls of bytes in your HTTP request.

##

Here's a longer explanation for what happens when Git contacts `git-lfs-pre-push(1)`:

1. We determine the set of updates to process, and then attempt to upload the associated objects https://github.com/git-lfs/git-lfs/blob/bbdad700b3e9d2c41bb57fea5f2190f8320ee275/commands/command_pre_push.go#L54-L58

2. We then call `ScanLeftToRemote()` to determine what Git objects we think the server does not have: https://github.com/git-lfs/git-lfs/blob/bbdad700b3e9d2c41bb57fea5f2190f8320ee275/commands/uploader.go#L57-L59

3. This eventually makes it way to create a new rev list scanner (which scans the output from `git-rev-list(1)`) here: https://github.com/git-lfs/git-lfs/blob/bbdad700b3e9d2c41bb57fea5f2190f8320ee275/lfs/gitscanner_refs.go?utf8=%E2%9C%93#L97-L105

4. This eventually makes it way to determine the list of arguments to pass to `git-rev-list(1)`, which (when given the `ScanLeftToRemote` scanning mode), appends `--not --remotes=...` as above: https://github.com/git-lfs/git-lfs/blob/bbdad700b3e9d2c41bb57fea5f2190f8320ee275/git/rev_list_scanner.go#L253-L262

##

Please let me know if that all seems reasonable, and if you have any other questions please don't hesitate to ping me here!

**Comment by palmin** [comment]
This is extremely illuminating and helpful.
Thank you @ttaylorr 🙏
