### ISSUE TITLE
Is it possible to tell git where to find the git-lfs binary?

### ISSUE THREAD

**Issue by jeffreydwalter** [git-lfs/git-lfs#2895]
I have a situation where I have multiple git repos using different versions of git-lfs on the same system. One repo is using a really old git-lfs (1.1.2) and can't be upgraded (the Artifactory server is out-of-date and can't be upgraded). The other repo is using Bitbucket's Git LFS and is using git-lfs (2.3.4).

**Comment by ttaylorr** [comment]
Hi @jeffreydwalter, thanks for opening this issue! I think a way to accomplish this is to reorder your `$PATH` environment variable so that the version of Git LFS you want appears earlier than the version of Git LFS that you don't want.

**Comment by jeffreydwalter** [comment]
@ttaylorr thanks for the suggestion, however that's not really a solution. I work on both repos simultaneously, as they are somewhat related. I am looking more for a way to explicitly specify where to find the git-lfs binary on a per repo basis, like in the .gitconfig or something along those lines. Sort of like you do today with actually specifying where to find the lfs server.

**Comment by ttaylorr** [comment]
> like in the .gitconfig or something along those lines.

This is not possible directly without modifying your $PATH variable based on the directory that you are in. If you'd like to go down that route, there are tools like `direnv(1)`, or scripting your prompt to modify the $PATH variables appropriately.

Beyond that, I'd recommend scripting your local `.git/config` file with the `alias` section [1](https://git-scm.com/docs/git-config#git-config-alias). It is not possible to overwrite the `git lfs` command (since it resolves to somewhere on your path), but it is possible to add `git lfs-local` via:

```sh
git config --local lfs-local /path/to/git-lfs
```

That said, the `/path/to/git-lfs` binary will interact with Git which will in turn call `git lfs` (_not_ `git lfs-local`) and may produce unintended side effects. Since the configuration pertaining to which program binary should be executed by Git is configured in Git, this is overridden by `git lfs install --local`.
