### ISSUE TITLE
Failures after upgrading to v2.4.0

### ISSUE THREAD

**Issue by goodtune** [git-lfs/git-lfs#2900]
This is not afflicting all users in our team however I have received reports from a few users since upgrading from 2.3.4 to 2.4.0 that pushes are failing.

Below is a traceback I've received.
```
panic: runtime error: index out of range 0 B/s
goroutine 34 [running]:
github.com/git-lfs/git-lfs/tools/humanize.FormatBytes(0xffffffffffffffff, 0xc4204de150, 0x6)
        /tmp/docker_run/src/github.com/git-lfs/git-lfs/tools/humanize/humanize.go:110 +0x1e5
github.com/git-lfs/git-lfs/tq.(*Meter).str(0xc420190360, 0xc420201b00, 0x4298ef)
        /tmp/docker_run/src/github.com/git-lfs/git-lfs/tq/meter.go:241 +0xed
github.com/git-lfs/git-lfs/tq.(*Meter).update(0xc420190360, 0xc42022f000)
        /tmp/docker_run/src/github.com/git-lfs/git-lfs/tq/meter.go:219 +0x4a
github.com/git-lfs/git-lfs/tq.(*Meter).Skip(0xc420190360, 0xffffffffffffffff)
        /tmp/docker_run/src/github.com/git-lfs/git-lfs/tq/meter.go:127 +0x6e
github.com/git-lfs/git-lfs/tq.(*TransferQueue).Skip(0xc420072c00, 0xffffffffffffffff)
        /tmp/docker_run/src/github.com/git-lfs/git-lfs/tq/transfer_queue.go:718 +0x39
github.com/git-lfs/git-lfs/tq.(*TransferQueue).enqueueAndCollectRetriesFor(0xc420072c00, 0xc420280000, 0x2, 0x64, 0x0, 0x0, 0x0, 0x0, 0x0)
        /tmp/docker_run/src/github.com/git-lfs/git-lfs/tq/transfer_queue.go:464 +0x68f
github.com/git-lfs/git-lfs/tq.(*TransferQueue).collectBatches.func1(0xc42027e7c0, 0xc420072c00, 0xc42027e000, 0xc4202c61e0)
        /tmp/docker_run/src/github.com/git-lfs/git-lfs/tq/transfer_queue.go:354 +0x54
created by github.com/git-lfs/git-lfs/tq.(*TransferQueue).collectBatches
        /tmp/docker_run/src/github.com/git-lfs/git-lfs/tq/transfer_queue.go:360 +0x36f
error: failed to push some refs to 'https://git/scm/proj/repo.git'
```
May be related to #2811 @ttaylorr?

**Comment by ttaylorr** [comment]
Hi @goodtune, thanks for opening this issue! I'm so sorry that this issue is preventing some of your teammates from pushing -- we're definitely going to get this fixed soon.

Here are some thoughts on what might be happening. Since this issue is only affecting some of your teammates, and I haven't myself been able to reproduce the issue locally, I think that this is an architecture-specific issue with floating point calculations. These calculations can be notoriously fragile (especially in the case of exponentiating to large powers, as is done in the LFS code), so I think that this is a machine specific problem.

I've provided a few builds below for different architectures that will log some extra information that will be useful in debugging what's going on. Can you have your teammates run any of the below builds of LFS and try to push with `GIT_TRACE=1` in their environment? If they're able to reproduce the problem, please have them post the log here (with the lines that start: `humanize.FormatBytes`).

Once again, thanks! We're going to get this fixed.

[Uploading git-lfs-darwin-386-2.4.0.tar.gz…]()
[git-lfs-darwin-amd64-2.4.0.tar.gz](https://github.com/git-lfs/git-lfs/files/1786788/git-lfs-darwin-amd64-2.4.0.tar.gz)
[git-lfs-freebsd-386-2.4.0.tar.gz](https://github.com/git-lfs/git-lfs/files/1786789/git-lfs-freebsd-386-2.4.0.tar.gz)
[git-lfs-freebsd-amd64-2.4.0.tar.gz](https://github.com/git-lfs/git-lfs/files/1786790/git-lfs-freebsd-amd64-2.4.0.tar.gz)
[git-lfs-linux-386-2.4.0.tar.gz](https://github.com/git-lfs/git-lfs/files/1786791/git-lfs-linux-386-2.4.0.tar.gz)
[git-lfs-linux-amd64-2.4.0.tar.gz](https://github.com/git-lfs/git-lfs/files/1786792/git-lfs-linux-amd64-2.4.0.tar.gz)
[git-lfs-windows-386-2.4.0.zip](https://github.com/git-lfs/git-lfs/files/1786793/git-lfs-windows-386-2.4.0.zip)
[git-lfs-windows-amd64-2.4.0.zip](https://github.com/git-lfs/git-lfs/files/1786794/git-lfs-windows-amd64-2.4.0.zip)

**Comment by goodtune** [comment]
Thanks @ttaylorr - have just put this build out. We are running on a shared server so all users are in the same boat arch wise. FYI we were:

```
git-lfs/2.4.0 (GitHub; linux amd64; go 1.8.3; git 1a98fa5c)
```

Adding this special build earlier on the PATH and we're now at

```
git-lfs/2.4.0 (GitHub; linux amd64; go 1.10; git d06c72e4)
```

Thanks for the prompt response!

**Comment by goodtune** [comment]
Ok, I've got some feedback from one of the afflicted users.

Firstly, it was a first time using LFS for this person. We have shared configuration so there wasn't an issue with his local git/git-lfs setup, but he was not in an appropriately permissioned group on the LFS server.

```
09:31:51.345533 trace git-lfs: tq: running as batched queue, batch size of 100
09:31:51.345813 trace git-lfs: run_command: git rev-list --stdin --objects --
09:31:51.346677 trace git-lfs: run_command: git cat-file --batch
09:31:51.360585 trace git-lfs: humanize.FormatBytes(0) -> e=0, unit=1, index=0
09:31:51.361186 trace git-lfs: tq: sending batch of size 1
09:31:51.361421 trace git-lfs: run_command: ssh -p 1339 -- git@artifactory git-lfs-authenticate artifactory/repo upload
09:31:51.477610 trace git-lfs: api: batch 1 files
09:31:51.477834 trace git-lfs: HTTP: POST https://artifactory/artifactory/api/lfs/repo/objects/batch
09:31:51.565146 trace git-lfs: HTTP: 200
09:31:51.565418 trace git-lfs: HTTP: {
  "objects" : [ {
    "oid" : "df6e8f3c3b7729b4f444c9eda7eda9601af3374156b8a598172394cac33386c2",
    "size" : -1,
    "error" : {
      "code" : 403,
      "message" : "You do not have deploy permissions for the requested path"
    }
  } ]
}
09:31:51.565609 trace git-lfs: humanize.FormatBytes(18446744073709551615) -> e=6, unit=1000000000000000000, index=6
panic: runtime error: index out of range
```

After putting him into the right groups and pushing I've traced this:

```
09:59:03.105407 trace git-lfs: HTTP: POST https://artifactory/artifactory/api/lfs/repo/objects/batch
09:59:03.196990 trace git-lfs: HTTP: 200
09:59:03.197393 trace git-lfs: HTTP: {
  "objects" : [ {
    "oid" : "df6e8f3c3b7729b4f444c9eda7eda9601af3374156b8a598172394cac33386c2",
    "size" : 25749736
  } ]
}
09:59:03.197509 trace git-lfs: humanize.FormatBytes(25749736) -> e=2, unit=1000000, index=2
09:59:03.197558 trace git-lfs: tq: starting transfer adapter "basic"
09:59:03.197641 trace git-lfs: humanize.FormatBytes(25749736) -> e=2, unit=1000000, index=2                                                                                      
09:59:03.197842 trace git-lfs: humanize.FormatBytes(25749736) -> e=2, unit=1000000, index=2
Uploading LFS objects: 100% (1/1), 26 MB | 0 B/s, done
```

Is it possible the issue is in the handling of a failure mode where a user is unable to push due to authorization failure? My gut is telling me that `size=-1` in the unauthorized flow is becoming `MAXINT` and the arithmetic to determine the units doesn't extend that far.

**Comment by ttaylorr** [comment]
@goodtune great find; I think I know what's going on. `size: -1` is _not_ a valid response from the LFS API, but I've opened up https://github.com/git-lfs/git-lfs/pull/2902 to harden Git LFS against this. Can you try any one of these builds and let me know how it goes?

[git-lfs-darwin-386-2.4.0.tar.gz](https://github.com/git-lfs/git-lfs/files/1787292/git-lfs-darwin-386-2.4.0.tar.gz)
[git-lfs-darwin-amd64-2.4.0.tar.gz](https://github.com/git-lfs/git-lfs/files/1787293/git-lfs-darwin-amd64-2.4.0.tar.gz)
[git-lfs-freebsd-386-2.4.0.tar.gz](https://github.com/git-lfs/git-lfs/files/1787294/git-lfs-freebsd-386-2.4.0.tar.gz)
[git-lfs-freebsd-amd64-2.4.0.tar.gz](https://github.com/git-lfs/git-lfs/files/1787295/git-lfs-freebsd-amd64-2.4.0.tar.gz)
[git-lfs-linux-386-2.4.0.tar.gz](https://github.com/git-lfs/git-lfs/files/1787296/git-lfs-linux-386-2.4.0.tar.gz)
[git-lfs-linux-amd64-2.4.0.tar.gz](https://github.com/git-lfs/git-lfs/files/1787297/git-lfs-linux-amd64-2.4.0.tar.gz)
[git-lfs-windows-386-2.4.0.zip](https://github.com/git-lfs/git-lfs/files/1787298/git-lfs-windows-386-2.4.0.zip)
[git-lfs-windows-amd64-2.4.0.zip](https://github.com/git-lfs/git-lfs/files/1787299/git-lfs-windows-amd64-2.4.0.zip)

**Comment by goodtune** [comment]
Excellent, worked like a treat.

```
12:12:37.557409 trace git-lfs: tq: running as batched queue, batch size of 100
12:12:37.557950 trace git-lfs: run_command: git rev-list --stdin --objects --
12:12:37.558650 trace git-lfs: run_command: git cat-file --batch
12:12:37.573480 trace git-lfs: tq: sending batch of size 1
12:12:37.573746 trace git-lfs: run_command: ssh -p 1339 -- git@artifactory git-lfs-authenticate artifactory/repo upload
12:12:37.689649 trace git-lfs: api: batch 1 files
12:12:37.689881 trace git-lfs: HTTP: POST https://artifactory/artifactory/api/lfs/repo/objects/batch
12:12:37.779918 trace git-lfs: HTTP: 200
12:12:37.781626 trace git-lfs: HTTP: {
  "objects" : [ {
    "oid" : "b1726556be7dc2ca0bb554c50ca00615830bf0989371f0e94f50b417cf4e7ba5",
    "size" : -1,
    "error" : {
      "code" : 403,
      "message" : "You do not have deploy permissions for the requested path"
    }
  } ]
}
12:12:37.781964 trace git-lfs: tq: starting transfer adapter "basic"
[b1726556be7dc2ca0bb554c50ca00615830bf0989371f0e94f50b417cf4e7ba5] You do not have deploy permissions for the requested path: [403] You do not have deploy permissions for the requested path
error: failed to push some refs to 'ssh://git@git/proj/repo.git'
```
