### ISSUE TITLE
git-lfs is giving me error because of ~/.netrc file

### ISSUE THREAD

**Issue by ankit-shah2** [git-lfs/git-lfs#2943]
[root@ip-192-168-1-136 infobright-test]# git lfs checkout
bad netrc file /root/.netrc: line 4: keyword expected; got protocol

I installed git-lfs and did git lfs install --local from the repo which is using git lfs.

Now I want all the actual contents , for which I am doing git lfs checkout then I am getting this error.

Contents of my .netrc file is -> 

machine github.com
login <my machine>
password <my access token>
protocol https

Please help

**Comment by ttaylorr** [comment]
Hi @ankit-shah2, thanks for opening this issue! I think that this is a valid error, since that is indeed a malformed `~/.netrc` file, and Git LFS can't confidently proceed without valid credentials. Specifically, I think that the `protocol` directive is undefined [[source](https://linux.die.net/man/5/netrc)].

Can you try removing the `protocol` line and running this again? If you run into anything else similar, please don't hesitate to comment on this issue. Thanks!
