### ISSUE TITLE
error: failed to push some refs to"..."

### ISSUE THREAD

**Issue by wenjinghy** [git-lfs/git-lfs#2946]
when I run git push origin master ,I got this error:
![git lfs](https://user-images.githubusercontent.com/31907394/37883591-e800854e-30dd-11e8-9dc4-23bffef4f579.png)
Thank you in advice.

**Comment by ttaylorr** [comment]
Hi @wenjinghy, thanks for opening this issue and I'm sorry that you're having trouble! It looks like you're using Git LFS correctly, although it appears that your repository has exceeded the amount of upload/download bandwidth that you have paid for.

You can purchase additional data packs for your repository [by following this guide](https://help.github.com/articles/purchasing-additional-storage-and-bandwidth-for-an-organization/). This will allow you to resume pushing and pulling.

That said, I think that it is worth noting that this repository provides support for Git LFS, not its implementation on GitHub. For more specific questions relating to Git LFS _on GitHub_, please don't hesitate to reach out to `support@github.com`, and they'd be happy to help out.

**Comment by wenjinghy** [comment]
@ttaylorr Thanks for your reply,it's very helpful for me.

**Comment by snehareddypalle** [comment]
what about if it is a public repository

**Comment by ttaylorr** [comment]
> what about if it is a public repository

I believe that the same advice would follow :-). If you're asking about
the particular error message above (i.e., the one that you would see if
you are over your data quota), you can purchase more datapacks on GitHub
for Git LFS usage on public and private repositories alike.

If you're asking about generalized support for Git LFS on GitHub (as it
pertains to public repositories) my advice also follows. This repository
(and its issue tracker) offers support for Git LFS the tool, not Git LFS
on GitHub.

For the later, I would recommend reaching out to
https://github.com/support.

**Comment by Owomugisha** [comment]
![error](https://user-images.githubusercontent.com/44451738/52515632-41ef7880-2bec-11e9-8e36-94dbfd0025c0.JPG)
i am getting this error message when trying to push

**Comment by ttaylorr** [comment]
> i am getting this error message when trying to push

I'm sorry that you're having trouble. Please make sure that (1) your repository exists, (2) that you have writeable access to it, and (3) that the `master` branch exists on the remote.

I am pretty sure that looking into one of those (3) above should be enough to solve the issue, but in the case that it's not I am pretty sure that this is an issue having to do with a Git configuration, not a bad interaction with Git LFS.

To confirm the later (if you are still having troubles), please make sure that you aren't able to push without using Git LFS (simply run `git lfs uninstall` to test, and then `git lfs install` to "undo" your changes).

Lastly, if you have any other questions, please don't hesitate to place them in a new issue. Since this issue is closed, it's better to surface it in a newer thread to avoid sending notifications to people who have had their issue since resolved. Thanks!

**Comment by akhiltodecode** [comment]
If still error exists then
$ git commit -m "first commit" has to be committed before pushing i.e git push -u origin master

**Comment by ghanashyam924** [comment]
![git](https://user-images.githubusercontent.com/55736833/69532037-1bdd6e00-0f9d-11ea-8904-aa7e4b4eb842.PNG)
i am getting this error message when trying to push

**Comment by bk2204** [comment]
As @ttaylorr mentioned, this is an issue with Git, and not Git LFS.  The message means that you're trying to push a branch `master` which doesn't exist on your local system.  That's what “src refspec does not match any” means.

**Comment by DanzTim** [comment]
Before you do `git push -u origin master` you need to do `git add .` and `git commit -m "First commit"`. The quick setup page after you make a repo only tells you to do git push without doing git add and git commit, which is wrong.

**Comment by dolarnold** [comment]
Thank you it works

**Comment by ghanashyam924** [comment]
😊😊

**Comment by hassanMetwally** [comment]
> Before `git push -u origin master` do `git add .` and `git commit -m "First commit"`. The quick setup page after you make a repo only tells you to do git push without doing git add and git commit, which is wrong.
Thank you it works
