### ISSUE TITLE
Fail install in Xcode 9.3

### ISSUE THREAD

**Issue by R-U-N** [git-lfs/git-lfs#2958]
I did git lfs install,but it show error as follow:

'git lfs ls-files' failed with code 2:'failed MSpanList_Insert 0x952000 0x43fae1ed2239 0x0 0x0
fatal error: MSpanList_Insert.

What can I do

**Comment by ttaylorr** [comment]
Hi @R-U-N, this looks like a known issue with particular versions of Go and Xcode (per: https://github.com/golang/go/issues/17182).

Can you try upgrading to the latest Go that Git LFS is built on (go1.10) and post here again if the issue persists?

Thanks!

**Comment by R-U-N** [comment]
Hi,this is my go version :go version go1.10.1 darwin/amd64,it is the latest,but the issue still occur.

**Comment by ttaylorr** [comment]
What about in Xcode 9.4? If the issue persists, I'd recommend that you open an issue on golang/go.

**Comment by vypah** [comment]
@R-U-N @ttaylorr Is there any update here. Just upgraded to high sierra and I am facing the same issue.

**Comment by ttaylorr** [comment]
From reading the golang/go issue that I linked above in this thread, it
looks like this a problem that is a combination of what version of
macOS, XCode and Go you are using to bootstrap your compilation.

Can someone please fiddle with various combinations of those (ISTM that
only the version of Go should matter, since this issue is narrowed down
to 9.3 and macOS High Sierra)?

In the meantime, I am going to close this issue, since I think that the
remediation is outside of Git LFS's responsibility.

If that isn't the case, please do not hesitate to let me know and I
would be more than happy to re-open this issue and help out with the
necessary bits. Thanks.

**Comment by R-U-N** [comment]
I have solve this problem by update my Sourcetree(a Git GUI).I think is the problem casue by Sourcetree
