### ISSUE TITLE
git-lfs tracked files not included in Source Code links in repo release

### ISSUE THREAD

**Issue by mpanning** [git-lfs/git-lfs#2966]
When I create a release of a repository including git-lfs tracked files, the Source Code links only include the pointer to the files, which don't work for people who download the link.  This release needs to include those large files for the rest of the codes to be useful.  Is there a workaround for this?  Web searching has revealed no obvious solutions for me so far.

**Comment by ttaylorr** [comment]
Hi @mpanning, thanks for opening this issue.

> the Source Code links only include the pointer to the files

I assume that you are referring to the archived downloads that GitHub provides, in which case I would recommend that you forward this request to support@github.com.

Since this repository only offers support pertaining to Git LFS, I can't offer you any official advice on whether or not this is something that GitHub plans to support.
