### ISSUE TITLE
Specification not citing p4

### ISSUE THREAD

**Issue by ppKrauss** [git-lfs/git-lfs#2988]
About the [docs/spec.md](https://github.com/git-lfs/git-lfs/blob/master/docs/spec.md), there are no link or citation of [git-p4](https://git-scm.com/docs/git-p4) conventions. Perhaps important some relationship with [git-scm.com/docs](https://git-scm.com/docs), as "main git spec".

**Comment by ttaylorr** [comment]
Hi @ppKrauss, thanks for your suggestion. I am a little unsure of why it would make sense to link to git-p4's documentation, since this project (and the specification document that you linked) doesn't have any relation to `git-p4`.

Could you clarify here, or open a pull request changing that file? Thanks.

**Comment by ppKrauss** [comment]
Hi @ttaylorr. Oops, "any relation to git-p4"?  Well, a little one,

> Specify the system that is used for large (binary) files. Please note that large file systems do not support the git p4 submit command. Only Git LFS is implemented right now (see https://git-lfs.github.com/ for more information). Download and install the Git LFS command line extension to use this option and configure it like this:
> `git config       git-p4.largeFileSystem GitLFS`

-----

I understand that the `man`-like Reference part of https://git-scm.com/docs  (e.g. [docs/git](https://git-scm.com/docs/git)) is a kind of "official specification" of *git*... (there are some other?).
 
I was looking for **"the official *git-LFS* specification"**, and see only git-p4 linking something... There are other "fundamentals of git-LFS" in this context?

**Comment by ppKrauss** [comment]
... Sorry, other words:  the Git LFS is not a Git project?   Is only a Github initiative?

(so there are no "git community standard" as reference?)

**Comment by larsxschneider** [comment]
@ppKrauss Git LFS is an extension to Git. The two projects are independently developed and maintained by different people.

I added Git LFS support to `git-p4` a few years ago because I've used `git-p4` to migrate source code with large binaries from Perforce Git. Back in the day there was no [`git-lfs-migrate`](https://github.com/git-lfs/git-lfs/blob/master/docs/man/git-lfs-migrate.1.ronn) tool and therefore I taught `git-p4` to generate a Git repo with Git LFS files. This is a very special "on time" use case and it is likely not interesting to the general Git LFS user. Amongst other things that is one reason why we don't mention `git-p4` in the Git LFS docs.

Does this make sense to you? Do you have a problem or question with the `git-p4` and Git LFS?

**Comment by ppKrauss** [comment]
Thanks @larsxschneider , good and sufficient explanation. The main point is

> Git LFS is an extension to Git. The two projects are independently developed and maintained by different people.

So, in nowadays, the term *"official"* is about this "extension community", not the "the Git community"... And there are no "connection point" (as git-p4 seems without your explanation). Perhaps in near future the LFS extension is "officialized" by Git community, but at this time is interesting to be explicit about the status of the LFS project in the context of the general Git project.

Summarizing my suggestion: **let's add your phrase to the README.md**, and add something also in the [official LFS specification](https://github.com/git-lfs/git-lfs/blob/master/docs/spec.md).

**Comment by ttaylorr** [comment]
> So, in nowadays, the term _"official"_ is about this "extension community", not the "the Git community"... And there are no "connection point" (as git-p4 seems without your explanation). Perhaps in near future the LFS extension is "officialized" by Git community, but at this time is interesting to be explicit about the status of the LFS project in the context of the general Git project.

I think that the current level of documentation is sufficient to indicate that the two projects are separate and developed by different groups of people. Let's close this for now.
