### ISSUE TITLE
Migration breaks symlinks stored in the repo

### ISSUE THREAD

**Issue by dutchscout** [git-lfs/git-lfs#3009]
**Problem**
When I run LFS migration, it breaks symlinks that have been checked into the repo.

**Example `ls -lah` output**
_Before_
`lrwxrwxrwx  1 user123 users   43 May 15 10:44 binary_huge.bmp -> /usr2/user123/sample-images/binary_huge.bmp`

_After_
`lrwxrwxrwx  1 user123 users 127 May 15 10:44 binary_huge.bmp ->` **`version https://git-lfs.github.com/spec/v1
oid sha256:d06c05e87574cf6220e24610a987dfd5bab9468378ed75b1534cfcd4b321f7fc`**

**Use case**
I'm trying to clean up a repo with a lot of large and/or binary files.  In the past, users replaced some large binary files with symlinks to outside the repo, as a way of keeping the repo size manageable.  Now, I need to migrate all of the binary files to LFS.  Unfortunately, it's not possible to avoid the symlinks in the import filter, since it looks like there is a mix of symlinks and non-symlinks, both in the same file type (some *.so are real, some are symlinks) and through history (some files used to be real, now are symlinks, and some probably used to be symlinks and are now real files).

**Steps to reproduce**
While our repo is large and messy, I managed to reproduce this in a short set of steps.

**_Prereqs:_**
- Artifactory or some other LFS-compatible repo set up to take files
- A picture file at ~/sample-images/binary_small.bmp
- A picture file at ~/sample-images/binary_huge.bmp

1. Set up and enter repo
`git init lfs-symlinks`
`cd lfs-symlinks`

2. Copy a real file to the repo
`cp ~/sample-images/binary_small.bmp .`
`git add binary_small.bmp`
`git commit -am "binary file"`

3. Create a symlink in the repo
`ln -s ~/sample-images/binary_huge.bmp binary_huge.bmp`
`git add binary_huge.bmp`
`git commit -am "symlink to binary"`

4. Add LFS
`git lfs install`
`git config -f .lfsconfig lfs.url "ssh://<artifactory_project_path>"`
`git add .lfsconfig`
`git commit -m "Track LFS files"`

5. Check status
`git status`
`git log`
`ls -lah`

6. Do migration
`git lfs migrate import --everything --verbose --include="*.bmp"`

7. Check status again
`git status`
`ls -lah`

**Comment by dutchscout** [comment]
Was using git 2.15.1 and git-lfs 2.4.0

**Comment by ttaylorr** [comment]
Hi @dutchscout, thanks for opening this issue. I'm sorry that you're having trouble with the `migrate` command. Recently, @patrickmarlier changed the behavior of `git lfs migrate` to avoid migrating symbolic links to files (see: https://github.com/git-lfs/git-lfs/pull/2983).

Since this hasn't been integrated into a published release of Git LFS yet, (the next would be v2.4.1), it is understandable that you'd be running into this issue.

To confirm that there wasn't anything particular about the test-case that you provided above (thank you), I wrote this test in `test/test-migrate-import.sh` and the resulting repository was correct:

```bash
set -e

mkdir -p "ext"
printf 1 > ext/1.dat
printf 2 > ext/2.dat

reponame="lfs-symlinks"
git init "$reponame"
cd "$reponame"

cp ../ext/1.dat 1.dat
git add 1.dat
git commit -m "1.dat: initial commit"

ln -s ../ext/2.dat 2.dat
git add 2.dat
git commit -m "2.dat: initial commit"

git lfs install
git config -f .lfsconfig lfs.url ssh://artifactory.local/my/repo.git
git add .lfsconfig
git commit -m "install lfs"

ls -lah
git lfs migrate import --everything --verbose --include="*.dat"
ls -lah
``` 

e.g.,

```ShellSession
$ ls -lah
total 24
drwxr-xr-x   7 ttaylorr  staff   224B May 16 19:01 .
drwxr-xr-x   8 ttaylorr  staff   256B May 16 19:01 ..
drwxr-xr-x  13 ttaylorr  staff   416B May 16 19:01 .git
-rw-r--r--   1 ttaylorr  staff    42B May 16 19:01 .gitattributes
-rw-r--r--   1 ttaylorr  staff    49B May 16 19:01 .lfsconfig
-rw-r--r--   1 ttaylorr  staff   126B May 16 19:01 1.dat
lrwxr-xr-x   1 ttaylorr  staff    12B May 16 19:01 2.dat -> ../ext/2.dat
```

Git LFS v2.4.1 will be released soon, and this issue should be resolved then. In the meantime, you can build Git LFS from source, the resulting binary of which should not have this issue.
