### ISSUE TITLE
Hardware accelerated hashing

### ISSUE THREAD

**Issue by m1h4** [git-lfs/git-lfs#3019]
Is Git-LFS using https://en.wikipedia.org/wiki/Intel_SHA_extensions where possible for hashing files?

Since by its nature, Git-LFS is used with possibly hundred or thousand megabyte files, having the fastes possible hashing implementation would significantly impact git operations and general developer experience.

**Comment by ttaylorr** [comment]
Hi @m1h4, thanks for pointing this out and opening this issue. It's a great idea; we don't currently use any hardware acceleration, since we rely on the `crypto/sha256` to do this type of work.

I found https://github.com/minio/sha256-simd, which seems to do what we want, i.e., "be a drop-in replacement that uses hardware acceleration where possible, and falls back to crypto/sha256 where it's not." 

I pushed a branch of in: https://github.com/git-lfs/git-lfs/pull/3021.

**Comment by ttaylorr** [comment]
@m1h4 interesting; I wasn't aware that Go had support for SIMD optimizations of this sort, but admit that I am only superficially aware of the `crypto/*` packages, not any of their specific details. I think that more measurement is worthwhile to see if there are speedups in a practical setting within Git LFS between `sha256-simd` and `crypto/sha256`.

**Comment by ttaylorr** [comment]
Closing per #3021.
