### ISSUE TITLE
Simple steps to uninstall Git LFS from your repository

### ISSUE THREAD

**Issue by chase-moskal** [git-lfs/git-lfs#3026]
it's time to settle this topic once and for all, because answers raised in previous issues about this have proven insufficiently formulated, or are simply outdated with deprecated commands (#316, #641, #910)

i was delighted when git lfs was so easy to install and get started with — but it starts to feel frustrating when git lfs is difficult and confusing to break up with — and boy am i confused

so let's make this easy together — and remember — its not you, it's me  
*ok ok.. i'm seeing someone else.. it's github pages!*

1. **`git lfs uninstall`**  
    this removes hooks and smudge/clean filter configuration  
    and this is only the beginning, mua-ha-ha

2. ***how can we reindex/re-commit lfs'd files to restore them???***  
    in [this comment](https://github.com/git-lfs/git-lfs/issues/910#issuecomment-238389388) @andyneff says:

    > you can probably remove the entries from .gitattributes and trigger the git index that every lfs file is different, and then add and commit those files. This is the same procedure in how you change the auto newlines in a git repo. I'll have to test this some, but this might get you in the right direction. The only caviate is you don't want to reset the .gitattributes files first.

    good thing i read just now that this must be done *before* the .gitattributes step  

    but how the heck do we do this? (sure don't want to accidentally change all my newlines, hah)

    is there a way that git lfs can do this for me? after all, it was the one who created this mess to begin with.. *ok, ok, i know that line never works in any relationship ;)*

    **edit:** ok, there's some talk [in this issue](https://github.com/git-lfs/git-lfs/issues/957) about a methodology

    - `git lfs ls-files` — view lfs files
    - for each file, use globs if you can:
      - `git rm --cached myfile.psd` — "remove" the lfs file
      - `git add myfile.psd` — add the "normal" file
    - `git commit -m "restore files from lfs"`

    let me know if that makes sense

3. **remove lfs `.gitattribute` entries**  
    this will apparently prevent lfs from resurrecting itself

4. ~~***how do we remove remaining files, seen via `git lfs ls-files`???***~~  
    i'm guessing we `git lfs untrack` them one-at-a-time  
    **edit:** nope, untrack doesn't remove them... hmm... what does it do?  
    maybe once i figure out step 2, this'll be done
    **edit:** yep, step 2 knocks this one out

5. ***what do we tell our fellow contributors to do???***  
    i'm guessing they just need to `git lfs uninstall`?  
    do they also need to `git lfs untrack` stored files or anything like that?

*also, i have no interest in rewriting history here, that's silly — i just want to move forward with my collaborators once this is taken care of*

*oh, and obviously, i need some help with the points ending in lots of question marks — once we work through this, i'd like to edit this post into a nice clean list of steps that people can follow — then maybe let's formalize this into some documentation*

*thanks fellas,*

*// chase*

**Comment by chase-moskal** [comment]
alright folks,

it looks like i successfully bumbled through the process on my own

i'll give this issue a day or two so some git-lfs contributors might see my train-of-thought, hopefully to shed some light on an old issue from a different perspective

then i'll edit the post to be much more clear, concise, and to-the-point with the numbered steps

i don't want to launch a pr for any documentation, but an equivalent to this issue should be formalized somewhere eventually — otherwise at least there's this issue for folks like me to seek out

cheers

**Comment by ttaylorr** [comment]
Hi @chase-moskal, thanks for opening this. I agree with the steps you outlined above, and left a few specific thoughts below. In one sense, I'm glad that we have this issue open in order to point people in the right direction should they want to uninstall Git LFS, but in another sense I think that this 5 (6?) step process is too complicated, and should be handled by Git LFS.

Another confusing aspect of this is that `git lfs uninstall` can be misleading in that it leads users to think that it is "uninstalling" Git LFS from your _repository_, when it is really uninstall Git LFS from your _system_. I think that the ultimate solution to this is a `git lfs migrate export` command.

As you noted, this does not rewrite history, so checking out previous revisions of your repository under Git LFS will check out pointers, not large objects.

Here are some specific thoughts:

> 3\. **remove lfs `.gitattribute` entries**
> this will apparently prevent lfs from resurrecting itself

This could occur before step (2) and instead of step(1), which would leave Git LFS installed on your system (in the case that you might interact with a repository that is using it in the future) but would make step (2) do what you expect. Even though Git LFS is configured in `$HOME/.gitconfig`, your repository doesn't have a `.gitattributes` telling Git to invoke Git LFS when you re-run `git add`, so your files are added as expected.

Another caveat of this case is that you must have a local cache of all Git LFS objects for this to work, which you can accomplish by `git lfs pull --all`.

> 5\.
> _**what do we tell our fellow contributors to do???**_
> i'm guessing they just need to `git lfs uninstall`?
> do they also need to `git lfs untrack` stored files or anything like that?

They should simply pull and checkout the new state of the world, their repository will work as-expected without Git LFS installed.

**Comment by fedor57** [comment]
Thanx, that helped me a lot while I was migrating from BitBucket to AWS CodeCommit. Some helpful hints:

- commit & push everything
- remove hooks
  `git lfs uninstall`
- remove lfs stuff from `.gitattributes`
- list lfs files using 
  `git lfs ls-files | sed -r 's/^.{13}//' > files.txt`
- run git rm --cached for each file 
  `while read line; do git rm --cached "$line"; done < files.txt` 
- run git add for each file 
  `while read line; do git add "$line"; done < files.txt` 
- commit everything 
  `git add .gitattributes`
  `git commit -m "unlfs"`
  `git push origin`
- check that no lfs files left
  `git lfs ls-files` 
- remove junk
  `rm -rf .git/lfs`
- you're all done 
  (but unlinked junk is within BitBucket Git LFS storage still)

**Comment by tchebb** [comment]
As of Git 2.16, the gnarly piece of this process—re-staging the files that were previously in LFS so their contents are in Git again—can be handled entirely using `git add --renormalize .`. See my Stack Overflow answer [here](https://stackoverflow.com/a/54119191/6568778) for more details.

**Comment by ttaylorr** [comment]
> can be handled entirely using `git add --renormalize .`

To clarify, this does _not_ affect earlier revisions of history: if you "remove" Git LFS from your repository and check out a historical revision of your repository, you will not see the large files, and instead only see the pointer representation.

`git lfs migrate export` _can_ do this, and more information on that is available via `man git-lfs-migrate`.

**Comment by altschuler** [comment]
LPT: do not remove `.git/lfs` before you push, or you'll be stuck with lfs failing to push

**Comment by everttrollip** [comment]
I summarised everything mentioned above into a gist, please check it out, maybe it helps others in the future like it helped me. Thanks everyone! https://gist.github.com/everttrollip/198ed9a09bba45d2663ccac99e662201

**Comment by long-nguyenxuan** [comment]
Especially thanks for your script, it saved ton of my times. @fedor57 
After do all your steps, I've get rid of LFS in my current repository and current remote, 
But because I need to push my repository to new remote (gitlab), then when I run push with `git push new-remote --all`, it throw error, Can you give a look on it? 

```console
longnx@DESKTOP-D46DU6R MINGW64 /d/git/working/edp-ibs-jidou (master)
$ git push gitlab
Enumerating objects: 444, done.
Counting objects: 100% (444/444), done.
Delta compression using up to 4 threads
Compressing objects: 100% (245/245), done.
Writing objects: 100% (444/444), 19.27 MiB | 4.65 MiB/s, done.
Total 444 (delta 190), reused 377 (delta 182), pack-reused 0
remote: Resolving deltas: 100% (190/190), done.
remote: GitLab: LFS objects are missing. Ensure LFS is properly set up or try a manual "git lfs push --all".
To https://gitlab.com/dps-ss/edp-ibs-jidou.git
 ! [remote rejected] master -> master (pre-receive hook declined)
error: failed to push some refs to 'https://gitlab.com/dps-ss/edp-ibs-jidou.git'

```

**Comment by kezakool** [comment]
easiest way to do it that worked for me : 
commit & push everything
git lfs uninstall
then manually remove lfs stuff from .gitattributes
git lfs untrack '<pattern>' (in my case, all files "*.*")
git add --renormalize .
git commit -m 'Restore file contents that were previously in LFS'

**Comment by bjennings76** [comment]
> Especially thanks for your script, it saved ton of my times. @fedor57
> After do all your steps, I've get rid of LFS in my current repository and current remote,
> But because I need to push my repository to new remote (gitlab), then when I run push with `git push new-remote --all`, it throw error, Can you give a look on it?
> 
> ```
> longnx@DESKTOP-D46DU6R MINGW64 /d/git/working/edp-ibs-jidou (master)
> $ git push gitlab
> Enumerating objects: 444, done.
> Counting objects: 100% (444/444), done.
> Delta compression using up to 4 threads
> Compressing objects: 100% (245/245), done.
> Writing objects: 100% (444/444), 19.27 MiB | 4.65 MiB/s, done.
> Total 444 (delta 190), reused 377 (delta 182), pack-reused 0
> remote: Resolving deltas: 100% (190/190), done.
> remote: GitLab: LFS objects are missing. Ensure LFS is properly set up or try a manual "git lfs push --all".
> To https://gitlab.com/dps-ss/edp-ibs-jidou.git
>  ! [remote rejected] master -> master (pre-receive hook declined)
> error: failed to push some refs to 'https://gitlab.com/dps-ss/edp-ibs-jidou.git'
> ```

FYI, I had this same error when I tried to push a repo to GitLab that at one time had LFS files in its history. I was able to finally fix it by:

1. Rebasing the entire repo back to when I originally added the .gitattribute file
2. During the rebase changed the .gitattribute file to remove all references to the LFS file type
3. Continued the rebase
4. Force-pushed the new commits up to the upstream repo

After that, I was able to push the repo up to GitLab without the `LSF objects are missing` error.

**Comment by gasilva** [comment]
> easiest way to do it that worked for me :
> first commit & push everything
> then
> 
> ```
> git lfs uninstall
> ```
> 
> then manually remove lfs stuff from .gitattributes
> 
> ```
> git lfs untrack '<pattern>' (in my case, all files "*.*")
> git add --renormalize .
> git commit -m 'Restore file contents that were previously in LFS' ```
> ```

That worked well!!! Thank you.

**Comment by pratik3098** [comment]
Removing  the following files worked for me:
.git/lfs
.git/hooks/pre-push

**Comment by hugomarquesdev** [comment]
> easiest way to do it that worked for me :
> first commit & push everything
> then
> 
> ```
> git lfs uninstall
> ```
> 
> then manually remove lfs stuff from .gitattributes
> 
> ```
> git lfs untrack '<pattern>' (in my case, all files "*.*")
> git add --renormalize .
> git commit -m 'Restore file contents that were previously in LFS' ```
> ```

So simple and it worked!! Thanks 😄

**Comment by gasilva** [comment]
The git add did not work.


Nothing specified, nothing added.

hint: Maybe you wanted to say 'git add .'?

hint: Turn this message off by running

hint: "git config advice.addEmptyPathspec false"


Guilherme A. Lima da Silva


Em ter., 1 de jun. de 2021 às 06:41, Hugo Marques ***@***.***>
escreveu:

**Comment by gasilva** [comment]
It was missing a dot after renormalize

git add --renormalize .

Now it worked


Guilherme A. Lima da Silva


Em ter., 1 de jun. de 2021 às 10:35, Guilherme Araujo Lima da Silva <
***@***.***> escreveu:

**Comment by gasilva** [comment]
But LFS it is still there

remote: Resolving deltas: 100% (90/90), completed with 46 local objects.

remote: *warning*: GH001: Large files detected. You may want to try Git
Large File Storage - https://git-lfs.github.com
<https://signaldmain.website/click?redirect=https%3A%2F%2Fgit-lfs.github.com&dID=1622556604166&linkName=https://git-lfs.github.com>
.

remote: *warning*: See http://git.io/iEPt8g
<https://signaldmain.website/click?redirect=http%3A%2F%2Fgit.io%2FiEPt8g&dID=1622556604166&linkName=http://git.io/iEPt8g>
for more information.

remote: *warning*: File countries/historyIC_v2.ipynb is 89.84 MB; this is
larger than GitHub's recommended maximum file size of 50.00 MB

remote: *error*: GH008: Your push referenced at least 10 unknown Git LFS
objects:

remote:     4d2cbfc64508dd56b52a298ff2c50b1f0610a7ec38dcc76d8218031b33b87ed1

remote:     25b74c60ba87ffc7e6d24da2ecffbc98e90833e890742d5d06f7d7fa8fbc1b96

remote:     4a6428cb65e7a4035753589d2f3af12f6441ba89b3712134006b0cb38134b983

remote:     ...

remote: Try to push them with 'git lfs push --all'.

To https://github.com/gasilva/dataAndModelsCovid19.git
<https://signaldmain.website/click?redirect=https%3A%2F%2Fgithub.com%2Fgasilva%2FdataAndModelsCovid19.git&dID=1622556604166&linkName=https://github.com/gasilva/dataAndModelsCovid19.git>


Guilherme A. Lima da Silva

Em ter., 1 de jun. de 2021 às 11:07, Guilherme Araujo Lima da Silva <
***@***.***> escreveu:

**Comment by andyneff** [comment]
@gasilva That error message is an error from the "GitHub server", not from you running the "git-lfs client".

That error message says you have a file the violated the GitHub max: `countries/historyIC_v2.ipynb`

GitHub has a policy, where they no longer allow you to push a commit that contains files larger than 50MB. So the "GitHub server" is telling you "You need git lfs"

**Comment by devBabinski** [comment]
This worked for me:

git lfs uninstall
git lfs uninstall --local
git rm --cached -r .        
git push origin main

**Comment by longtth** [comment]
> This worked for me:
> 
> git lfs uninstall
> git lfs uninstall --local
> git rm --cached -r .
> git push origin main

did you tried clone, update, commit, push from another local repo? 
I've tried this and it still stuck

**Comment by florianseidlschulz** [comment]
> Thanx, that helped me a lot while I was migrating from BitBucket to AWS CodeCommit. Some helpful hints:
> 
>     * commit & push everything
> 
>     * remove hooks
>       `git lfs uninstall`
> 
>     * remove lfs stuff from `.gitattributes`
> 
>     * list lfs files using
>       `git lfs ls-files | sed -r 's/^.{13}//' > files.txt`
> 
>     * run git rm --cached for each file
>       `while read line; do git rm --cached "$line"; done < files.txt`
> 
>     * run git add for each file
>       `while read line; do git add "$line"; done < files.txt`
> 
>     * commit everything
>       `git add .gitattributes`
>       `git commit -m "unlfs"`
>       `git push origin`
> 
>     * check that no lfs files left
>       `git lfs ls-files`
> 
>     * remove junk
>       `rm -rf .git/lfs`
> 
>     * you're all done
>       (but unlinked junk is within BitBucket Git LFS storage still)

This does not work, git lfs ls-files still produces a list of tracked files. Also misses a rm files.txt

**Comment by Aiyualive** [comment]
I just ended up git rm "<all the tracked git lfs tracked files>".

I dont want to deal with any git rewriting and this allows me to continue my work:)

**Comment by PasaOpasen** [comment]
I used

```
rm -rf .git/lfs .git/hooks/pre-push .gitattributes
```
+ it's necessary to have write access to .git directory

**Comment by tigerhawkvok** [comment]
Created a Python script to do this:

https://gist.github.com/tigerhawkvok/adb7905a2423312f237da1953d6a8eeb

Should work on all platforms (including Windows), and can generate a dry-run script for you  to inspect. (Note the dry-run script won't actually edit your `.gitattributes` or your `.git/lfs` folder,  it'll just show you the new contents of `.gitattributes` and verify the to-be-removed path)

**Comment by kretoskim** [comment]
Thank you!!!!!

**Comment by lemon-gith** [comment]
Just to say thank you so much for [your answer](https://github.com/git-lfs/git-lfs/issues/3026#issuecomment-451598434), this saved me from a massive headache today. I should've never inherited the Git LFS 'solution' from the original repo 🙏

**Comment by Arcitec** [comment]
# See: 🚀

`man git-lfs-migrate`

1. The Git LFS history exists in all old commits and all branches. To remove Git LFS from a repository, you **CAN'T** "just renormalize the current commit". It is **NECESSARY** to **rewrite ALL history** to convert Git LFS files to regular Git files, and then delete .gitattributes, and finally force push. Because if you don't rewrite the past history, your repository will still use Git LFS when anybody does `git clone` since the old commits will need to be downloaded via Git LFS!
2. You can see all Git LFS files with `git lfs ls-files --all` (but I don't think this command checks history or other branches)
3. The `git lfs migrate export` command converts a Git LFS history to regular Git history.
4. You should read the entire "DESCRIPTION" section of the `man git-lfs-migrate` page. Windows/Mac users can find it here: https://manpages.debian.org/unstable/git-lfs/git-lfs-migrate.1.en.html
5. You must convert EVERY branch and EVERY Git LFS file to the new format: `git lfs migrate export --everything --include="*"`
6. Verify your history afterwards (check all important branches with this): `git log --pretty=format:"%h %ad- %s [%an]"`
7. Now modify or delete your `.gitattributes` file to remove all LFS file filters from it, and then add that change as a commit. Be aware that `git lfs migrate` automatically modifies your `.gitattributes`, so you may not have to do anything - but since you're getting rid of LFS entirely, you can definitely remove all LFS-related entries from the file.
8. Finally, you must force push all branches to overwrite the online copy so that there's no more branches with Git LFS online: `git push origin --all --force` (beware that this will upload any private branches too, so you can replace `--all` with the name of a single branch (for example `main`) and upload the public branches one by one instead).
9. After doing all this, you can uninstall the local Git LFS hooks. (If you uninstall them before doing the other steps in this guide, you would not be able to push hehe.)

**Comment by setoelkahfi** [comment]
This [guy](https://www.ryangittings.co.uk/blog/removing-git-lfs-netlify/) helps me a lot. None of these answers solved my problems.

**Comment by Arcitec** [comment]
@setoelkahfi **Nope. That article is 100% wrong.**

If you want to remove Git LFS you need to follow my post, nothing else is correct:

https://github.com/git-lfs/git-lfs/issues/3026#issuecomment-3274789424

Literally the 1st point in my post tells you why that article you used is 100% wrong.

**Comment by setoelkahfi** [comment]
> [@setoelkahfi](https://github.com/setoelkahfi) **Nope. That article is 100% wrong.**
> 
> If you want to remove Git LFS you need to follow my post, nothing else is correct:
> 
> [#3026 (comment)](https://github.com/git-lfs/git-lfs/issues/3026#issuecomment-3274789424)
> 
> Literally the 1st point in my post tells you why that article you used is 100% wrong.

I disagree with you. Probably because you don't know my problem context. But I can see your point.

**Comment by walshandpartners888** [comment]
How can I completely remove Git LFS without rewriting history?

I’m having a similar problem trying to remove Git LFS from a repository and I’m struggling to work out the correct process.

The repository is for a major client of ours for a Cardiff based e-commerce business that sells diamond wedding rings and its products globally. We are a small team, just one developer at  [Walsh & Partners web](https://www.walshandpartners.co.uk/)site, and at some point Git LFS was enabled to handle some of the larger files. I now want to stop using LFS completely and return those files to normal Git tracking.

I’ve tried:

```bash
git lfs uninstall
```

My understanding is that this removes the Git LFS hooks and the clean/smudge filter configuration, but it doesn’t actually convert the existing LFS-tracked files back into normal Git files.

I can see the affected files using:

```bash
git lfs ls-files
```

From what I’ve read, I may need to remove the relevant LFS rules from `.gitattributes` and then somehow force Git to re-index the files so their actual contents are committed instead of the LFS pointers.

I’ve seen suggestions along the lines of:

```bash
git rm --cached <file>
git add <file>
```

followed by committing the changes, but I’m not confident about the correct order. I don’t want to accidentally delete files, corrupt anything, or create problems for anyone else working with the repository.

Importantly, I **don’t want to rewrite the repository’s Git history**. I’m happy for old commits to continue referencing LFS. I just want the current version of the repository, and all future commits, to use ordinary Git files.

What is the safest sequence of commands to completely stop using Git LFS, restore the currently tracked files to normal Git, and ensure LFS doesn’t start tracking them again?

**Comment by chrisd8088** [comment]
> Importantly, **I don’t want to rewrite the repository’s Git history**. I’m happy for old commits to continue referencing LFS. I just want the current version of the repository, and all future commits, to use ordinary Git files.
>
> What is the safest sequence of commands to completely stop using Git LFS, restore the currently tracked files to normal Git, and ensure LFS doesn’t start tracking them again?

@walshandpartners888 — Given your constraints, you likely need to remove all the lines with `filter=lfs` from your `.gitattributes` files and check in the full version of each file which formerly matched those lines' patterns.  You'll need to do this separately in every active branch.  (Also, note that it's possible to have multiple `.gitattributes` files, since they can appear in any directory, although typically users only have one in the top-level directory of their repository.)

I've tried to draft a simple example with two active branches and a single `.gitattributes` file in each branch.  One of these `.gitattributes` files has a line unrelated to Git LFS, so we need to leave that intact.

<details>

First, the following steps create our example repository with two branches:

```
$ git init test
$ cd test
$ git lfs track "*.bin"
$ echo foo >foo.bin
$ git add .gitattributes foo.bin
$ git commit -m init

$ git checkout -b other
$ echo "*.txt text" >>.gitattributes
$ echo foo >foo.txt
$ git add .gitattributes foo.txt
$ git commit -m text

$ mkdir dir
$ echo bar >dir/bar.bin
$ git add dir
$ git commit -m bar
```

Next, we convert the Git LFS objects back into regular files in both branches.  There are some extraneous steps in this example just to  show the state of the files before and after conversion.  Note that we need to update the modification timestamps of the working tree files with the `touch` command to ensure Git recognizes them as having changed.  (Alternatively, you could use the `git rm --cached` command on the files instead of the `touch` command.)

```
$ git checkout main
$ cat .gitattributes 
*.bin filter=lfs diff=lfs merge=lfs -text
$ git lfs ls-files
b5bb9d8014 * foo.bin
$ git show HEAD:foo.bin
version https://git-lfs.github.com/spec/v1
oid sha256:b5bb9d8014a0f9b1d61e21e796d78dccdf1352f23cd32812f4850b878ae4944c
size 4
$ cat foo.bin
foo

$ git rm .gitattributes
$ touch foo.bin
$ git add foo.bin
$ git commit -m convert

$ git show HEAD:foo.bin
foo
$ git lfs ls-files
# no output

$ git checkout other
$ cat .gitattributes 
*.bin filter=lfs diff=lfs merge=lfs -text
*.txt text
$ git check-attr -a foo.txt
foo.txt: text: set
$ git lfs ls-files
7d865e959b * dir/bar.bin
b5bb9d8014 * foo.bin
$ git show HEAD:foo.bin
version https://git-lfs.github.com/spec/v1
oid sha256:b5bb9d8014a0f9b1d61e21e796d78dccdf1352f23cd32812f4850b878ae4944c
size 4
$ git show HEAD:dir/bar.bin
version https://git-lfs.github.com/spec/v1
oid sha256:7d865e959b2466918c9863afca942d0fb89d7c9ac0c99bafc3749504ded97730
size 4
$ cat foo.bin 
foo
$ cat dir/bar.bin 
bar

$ grep -vF "filter=lfs" .gitattributes >.gitattributes.new
$ mv .gitattributes.new .gitattributes
$ touch foo.bin dir/bar.bin
$ git add .gitattributes foo.bin dir/bar.bin
$ git commit -m convert

$ cat .gitattributes 
*.txt text
$ git check-attr -a foo.txt
foo.txt: text: set
$ git show HEAD:foo.bin
foo
$ git show HEAD:dir/bar.bin
bar
$ git lfs ls-files
# no output
```

</details>
