### ISSUE TITLE
Pushed LFS files loading as "damaged"

### ISSUE THREAD

**Issue by alexfresa** [git-lfs/git-lfs#3030]
Hi there,

I installed Git LFS after realizing that I needed to upload a .pdf to my website (roughly 200MB) that would be available for download. I followed the given instructions, tracked the file type in my .gitattributes file, and pushed my changes to the repository via GitHub Desktop. 

Everything seemed to be uploading as if it were working correctly, but after everything was complete I went over to my site and encountered a strange error. When I would go to download the .pdf, a very tiny version of the file would download (130KB), and when I would try to open it I would receive an error message saying that the file "failed to load" and that it was possible that the file was either damaged or decoded incorrectly. 

I've tried this same process three times and I've gotten the same error each go. I'm certain that this is not a website issue either because it worked as intended when I attempted the same process with a smaller .pdf that was not put through Git LFS.

Am I missing something? I'm new to the extension so it's possible that this is my error, but I'm having trouble finding others who have encountered similar issues.

**Comment by shiftkey** [comment]
@alexfresa I'd recommend reaching out to the Git LFS project at https://github.com/git-lfs/git-lfs as I'm not experienced with debugging what Git LFS might have done here.

**Comment by ttaylorr** [comment]
Hi @alexfresa, thanks for opening this issue, and thanks @shiftkey for sending it this way. Git LFS works by turning large files into small "pointer" files that refer to the larger content just before Git can pick them up. The contents of the files themselves are stored elsewhere, and are checked out by Git on conversion from the index to your working copy, and therefore are not stored within the Git repository itself.

So, when you download the PDF file from your repository alone (outside of Git), the only thing that exists from this perspective is the pointer, not the contents of the file itself. I believe this is why you're experiencing the "failed to load" issue, since the file does not contain the contents expected.

Can you clarify what you mean by "downloading"? GitHub in particular does not serve Git LFS objects in archives of a repository or on GitHub pages, so these are known cases that are not supported. Perhaps you are trying to download a file from your repository in a different way, in which case we can discuss why it might not be working as expected.

Please let me know, thanks!

**Comment by alexfresa** [comment]
Hi @ttaylorr - I think I see what you're saying. Maybe if I explain what I'm trying to do it will make a little more sense.

The .pdf I'm referring to is a document I'm sharing publicly - those who would like to download and read the .pdf would be directed to the page where this download would be available. So essentially, for my purposes I need to make sure that this .pdf (the 200MB file put into Git LFS) is also available via download. 

However, I think according to what you're saying, they will not actually be able to download the file because the download link only contains the "pointer" link you're referring to. When I try and look at the file in my repository, everything works fine - the only time I am getting the file loading issue is when attempting to download the .pdf off of the site. 

If that's the case, do you know of an effective way around this? I would just leave the file to be viewed directly on the site, though the .pdf is optimized for Adobe Acrobat and needs to be opened in the program to work properly.

**Comment by ttaylorr** [comment]
> If that's the case, do you know of an effective way around this? I would just leave the file to be viewed directly on the site, though the .pdf is optimized for Adobe Acrobat and needs to be opened in the program to work properly.

No; GitHub does not provide access to Git LFS objects outside of normal Git operations. To share an a large file stored in Git LFS with another individual, they must be using Git+Git LFS and clone the repository itself.

I think that adding support for something like this on GitHub could certainly be interesting, though I can't comment on that any further here. If you'd like to discuss a GitHub-specific solution to this problem, please don't hesitate to send mail to `support@github.com`.

In the meantime, I don't think there is anything to do immediately that is pertinent to Git LFS, so I am going to close this issue for now. Please let me know here or via `support@` if you have any questions.
