### ISSUE TITLE
.git/lfs/objects folder is not created

### ISSUE THREAD

**Issue by vaburov** [git-lfs/git-lfs#3035]
For some reason I failed to add a folder to git lfs in my repo. 
Files are missing when I push and I've found that lfs/objects folder is missing.

```
> git-lfs version
git-lfs/2.4.0 (GitHub; linux 386; go 1.8.3; git 1a98fa5c)

> cd /tmp/myfolder
> git init
Initialized empty Git repository in /tmp/myfolder/.git/

> cat .gitattributes
storage/** filter=lfs diff=lfs merge=lfs -text

> tree -a storage
storage
|-- a.txt
`-- test
    `-- b.bin
1 directory, 2 files

> git add .
> git lfs ls-files
a36411aa15 - storage/a.txt
0f15384d18 - storage/test/b.bin

> tree -a .git/lfs
.git/lfs
`-- tmp
1 directory, 0 files
```

The strange thing is that the same instructions work for another repo with just few files (my one has a lot).
I was trying different scenarios, with commit, with "git lfs install" (though it is not needed, right?).
What could be the reason?

**Comment by vaburov** [comment]
Here is the scenario:
```
> tree .
.
|-- storage
|   |-- a.bin
|   |-- c.bin
`-- test.txt

>cat .gitattributes
storage/** filter=lfs diff=lfs merge=lfs -text

> git init
> git add .
```
Let's see what we have:
```
> git lfs ls-files
a36411aa15 - storage/a.bin
5891b5b522 * storage/c.bin

> tree -a .git/lfs/
.git/lfs/
|-- objects
|   `-- 58
|       `-- 91
|           `-- 5891b5b522d5df086d0ff0b110fbd9d21bb4fc7163af34d08286a2e846f6be03
`-- tmp

> git check-attr -a **/*
storage/a.bin: diff: lfs
storage/a.bin: merge: lfs
storage/a.bin: text: unset
storage/a.bin: filter: lfs
storage/c.bin: diff: lfs
storage/c.bin: merge: lfs
storage/c.bin: text: unset
storage/c.bin: filter: lfs
```
c.bin is tracked but a.bin is not! Why is that?
```
> cat storage/a.bin
version https://git-lfs.github.com/spec/v1
oid sha256:a36411aa1502369c3fc4ca1034ebcabf58b669fe772e1e64ad0b94077453926f
size 9
> cat storage/c.bin
hello
> cat .git/lfs/objects/58/91/5891b5b522d5df086d0ff0b110fbd9d21bb4fc7163af34d08286a2e846f6be03
hello
```
Looks like the content makes difference!
I have no Idea how that content appeared. At some moment the actual content of the file was replaced by it's meta information. If you know how that could be - please tell me.

Looks weird. Though a.bin content is specific, it is still a content.

**Comment by ttaylorr** [comment]
@vaburov Sorry that it's taken me a few days to get back to you, I was out of the office for the last week. Should this be a content-specific issue, I'm unsure where to proceed, since I don't know the contents of `storage/a.bin`.

Can you please either share the contents of storage/a.bin, or else write a script that exhibits this behavior? Thanks.

**Comment by vaburov** [comment]
Thanks Taylor,
I am not blocked by the issue, no I am just curios.
Here is the content of a.bin.
```
> cat storage/a.bin
version https://git-lfs.github.com/spec/v1
oid sha256:a36411aa1502369c3fc4ca1034ebcabf58b669fe772e1e64ad0b94077453926f
size 9
```
 It was above :) And as I said, i have no idea how I got it and that's also interesting. What could I do wrong?

**Comment by ttaylorr** [comment]
@vaburov thanks for the clarification; I was confused since that's an LFS pointer and I thought that this was the contents _after_ running `git add` with a pathspec that touched that file.

I believe, interestingly enough, that this is working as expected. You added two files: one which looks like a pointer file and one which does not. For the one that does not, Git LFS correctly turned it into a pointer file and stored the object in your local cache, ready to be pushed to the remote. For the one that did look like a pointer, Git LFS assumes that you didn't check out the large object into the working copy, and that the associated large object might be in your cache, or might be on the server. In this case, it assumes that the object is on the server, and does not alter the contents of what looks to be a valid pointer.

In this case, I am going to close this issue for now, but please do not hesitate to ping me here should you have any more questions in the future. Thanks!
