### ISSUE TITLE
Installation overrides system configs

### ISSUE THREAD

**Issue by shuhrat** [git-lfs/git-lfs#3036]
`git lfs install --system` (after installation) overrides `[filter=lfs]` section in `/etc/gitconfig`, however `--force` option is not passed.

```
$ cat /etc/gitconfig
[filter "lfs"]
  process = git-lfs filter-process --skip
  clean = git-lfs clean -- %f
  smudge = git-lfs smudge --skip %f
  required = true

$ git lfs install --system
Updated git hooks.
Git LFS initialized.

$ cat /etc/gitconfig
[filter "lfs"]
  process = git-lfs filter-process
  clean = git-lfs clean -- %f
  smudge = git-lfs smudge -- %f
  required = true
```

**Comment by ttaylorr** [comment]
Hi @shuhrat, can you please let me know which version of Git LFS you are running? There was a related bug fixed (https://github.com/git-lfs/git-lfs/pull/2994) recently, but this may be different.

In addition, please re-run the command with `GIT_TRACE=1` and post the relevant output here. Thanks!

**Comment by shuhrat** [comment]
> which version of Git LFS you are running? 

v2.4.1

**Comment by Vital88** [comment]
Yes but I don't now I am new

**Comment by ttaylorr** [comment]
Hi @shuhrat, thanks for waiting -- I was out of the office last week and am just catching up on things that I have missed. I believe what's going on here is that `git lfs filter-process --skip` is a value that we treat as upgrade-able, meaning "if we see it in a configuration file even without --force, it's OK to write over it".

This makes sense to me in practice, since if you disabled Git LFS via `--skip` in any layer of configuration and then run `git lfs install`, I would expect Git LFS to resume working.

Since this isn't a bug, I am going to close it for nwo,.
