### ISSUE TITLE
Insistently automatically edits /etc/git/hooks/pre-push

### ISSUE THREAD

**Issue by ethus3h** [git-lfs/git-lfs#3044]
Hi.

I don't use git-lfs. I only installed it as a dependency of another app. The only time I would ever want it to run is if I'm cloning a repository that used it, to download any required files.

However, it keeps inserting itself into /etc/git/hooks/pre-push, making it impossible for me to push any of my repositories until I empty that file. Even when I left it existing, as an empty file, it still got modified. This isn't an urgent issue for me, since I'm uninstalling it (editing that file every day to be able to keep working is simply unsustainable).

I thought I'd report this to let you know, though, that it would be nice if simply installing this tool and (judging by the source code of the dependent application) running `git lfs clone` — with no intention of ever pushing to a repository using it — didn't break git push for every repository on my system until I configure it (or whatever it wants, I haven't looked into it).

Thanks!

**Comment by ttaylorr** [comment]
Hi @ethus3h, thanks for opening this issue, and I'm sorry that you're having trouble! I think that what's going on here is that `git lfs clone` installs Git LFS in order to satisfy the installation steps that occur once per-repository-per-machine. Since it's common to use Git LFS with both pushing and pulling, we try and make that case as frictionless as possible.

You can disable this behavior with the `--skip-repo` option (i.e., `git lfs clone --skip-repo`), or avoid using `git lfs clone` altogether (since the command is deprecated, and can be replaced with `git clone` instead).

Please let me know if you have any other questions here, and I'd be more than happy to help out. Thanks!

**Comment by ethus3h** [comment]
Ahh, that sounds like something to report to the other app, then. Thank you! :)
