### ISSUE TITLE
lfs_storage_path not honored in config file

### ISSUE THREAD

**Issue by joeg1484** [git-lfs/git-lfs#3049]
Hi All,
We have configured lfs on our production server (GitLab Enterprise Edition 10.5.4-ee) and set the lfs_storage_path to a new location:
gitlab_rails['lfs_storage_path'] = "/gitlab-data/lfs-objects"

Re reconfigured the system and restarted the services, but no object directorys are being created/migrated over from the default location: /var/opt/gitlab/gitlab-rails/shared/lfs-objects .

The server we set this up on has never had lfs installed, so the object dirs should have went to the new location.

Any ideas? Let me know if you need additional info.

Thanks!
Joe

**Comment by joeg1484** [comment]
Ok, so we figured out that you have to rsync the data over from the old location (Needs to be in the instructions).

Once we did that and stopped and restarted the service, it works now

**Comment by ttaylorr** [comment]
Hi @joeg1484! I'm glad that you were able to get this issue resolved; I was out of the office last week hence my later-than-usual reply. It looks like this is a GitLab-specific issue, so for future reference, the GitLab support channels would be the best place to resolve this, since this repository provides support for the Git LFS command line tool, not its integration with GitHub, GitLab or similar. Thanks!
