### ISSUE TITLE
Git pull to merge repos with LFS

### ISSUE THREAD

**Issue by yoavartzi** [git-lfs/git-lfs#3058]
I use `git pull <source repo> <branch> --allow-unrelated-histories` to move files from one repo to another as suggested here:
https://gbayer.com/development/moving-files-from-one-git-repository-to-another-preserving-history/

However, this does not work if the source repo uses LFS. I this error: Object does not exist on the server: [404] Object does not exist on the server. 

The repo I am merging to has LFS installed and tracks a superset of the files tracked by the source repo. 

Any idea how I can merge repos with LFS?

**Comment by ttaylorr** [comment]
Hi @yoavartzi, unfortunately I don't think that Git LFS is able to support this. The error that you're seeing comes from the `process` filter, which is a utility provided by Git LFS that Git uses in order to convert from pointer files in your Git history to large files in your working copy.

By the time that this tool is invoked, Git LFS does not have an idea of what the remote that you pulled from (in your example `<source repo>`) is. Hence, it does not know which remote to further download Git LFS objects from, which is why it falls back to `origin` (in most cases) and tries to download an object that is likely to be missing, since it does not belong to that repository.

I hope that that explanation all sounds reasonable. Since this isn't possible with the tools that Git gives us today, I am going to close this issue for now. That said, please don't hesitate to send me a note here or elsewhere should you run into any questions or problems in the future. Thanks!
