### ISSUE TITLE
instruction to build from source

### ISSUE THREAD

**Issue by avilleret** [git-lfs/git-lfs#3069]
I need an arm binary of git-lfs and the build instruction are quite confusing.

First, only the [wiki](https://github.com/git-lfs/git-lfs/wiki/Installation#source) page contains relevant information to build, but nothing about installing.

[Install.md](https://github.com/git-lfs/git-lfs/blob/master/INSTALLING.md) talks about repository and magic script to install git-lfs from repository just as if it works everywhere (there no mention about the architecture restriction). Obviously is doesn't work on Debian based system running on arm architecture.

Concerning the [Readme.md](https://github.com/git-lfs/git-lfs/blob/master/README.md), it juste says : 

> This repository can also be built-from-source using the latest version of Go.

Without further instruction nor link to Wiki page.
Moreover the last statement :

> using the latest version of Go

is indeed wrong. At least it doesn't build with go1.10.3 (I got a "no compile command" error).
This advice also appear in the Installation.md : 

> For best results, use latest stable go to get all the patches

To help people building (and thus using) git-lfs on arm, I suggest to: 

  - note the need of go1.8 to build (I found this on an [issue](https://github.com/git-lfs/git-lfs/issues/1235))
  - add link to the Wiki page on main Readme.md
  - note the lack of arm binary on the Installation.md

My2cents

**Comment by ttaylorr** [comment]
Hi, @avilleret. Thanks for opening this issue and raising your concerns. I will respond in chunks:

> First, only the [wiki](https://github.com/git-lfs/git-lfs/wiki/Installation#source) page contains relevant information to build, but nothing about installing.

Good point. I haven't referred to this page myself in a while, so it was helpful to take another look. I updated the installation page (https://github.com/git-lfs/git-lfs/wiki/Installation#source) and have included instructions about how to install the code in a safer way, mostly due to the restriction of having to have your checkout appear in the right place within `$GOPATH`.

A frustrating thing is that we don't have hard-and-fast rules about when we are and are not allowed to depend on new Golang features, mostly as a function of the fact that we distribute our own binaries, and don't expect people to compile Git LFS theirselves on a regular basis. (Obviously, we hope to support this, but the official channel is to obtain a pre-compiled binary from the releases page). So, saying that we depend on "above Go 1.x" or similar is not likely to be true forever. I've settled on "a reasonably modern version of Go," which I think should be sufficient.

> Concerning the [Readme.md](https://github.com/git-lfs/git-lfs/blob/master/README.md), it juste says :
> 
> > This repository can also be built-from-source using the latest version of Go.

I've added a link to the relevant wiki page to the README in https://github.com/git-lfs/git-lfs/pull/3075.

> Without further instruction nor link to Wiki page.
> Moreover the last statement :
> 
> > using the latest version of Go
> 
> is indeed wrong. At least it doesn't build with go1.10.3 (I got a "no compile command" error).

Without more, I am confused by this error message. Can you please post specific information about your environment (`go env`) and the verbatim command you ran as well as the exact error message?

**Comment by itsho** [comment]
Hi.

I cannot find any instructions to compile it on windows.
tried to install `make` & `grep` (via chocolatey), but it is still unable to compile and produced the following errors:
[build-error.txt](https://github.com/git-lfs/git-lfs/files/4037068/build-error.txt)

last error is `make: *** [Makefile:247: resource.syso] Error 1`

**Comment by bk2204** [comment]
Hey,

To build on Windows, you need `goversioninfo`.  From somewhere outside of the `git-lfs` directory, run `go get github.com/josephspurrier/goversioninfo/cmd/goversioninfo`, which will install that binary into `$GOPATH/bin`.  If you then add that directory into your PATH, the build should be able to complete.

**Comment by bk2204** [comment]
I've updated the wiki to include that information.

**Comment by itsho** [comment]
Thanks! I'd also add to the wiki the part where you need to install `make` & `grep` somehow.

after doing your suggestion I got this errors - [error2.txt](https://github.com/git-lfs/git-lfs/files/4039059/error2.txt)

thanks again.

**Comment by bk2204** [comment]
Your shell in this case is `cmd`, and we require a Unix environment for building (i.e., one where the shell is `/bin/sh`).  Try running this in Git Bash, or otherwise where the shell used by `make` is a POSIX shell.

In general, anything with a Makefile generally assumes a standard Unix environment, although I can document that explicitly.

**Comment by itsho** [comment]
Hi. 
1. Thank you. I've managed to compile it by using `Git Bash`. please document it explicitly.
2. Please add a note that `Windows Subsystem Linux` (WSL) will generate a Linux file and not a Windows EXE file.
