### ISSUE TITLE
'missing protocol' errors when cloning lfs repos locally

### ISSUE THREAD

**Issue by Gaff** [git-lfs/git-lfs#3078]
I'm attempting to create a local clone of a lfs based repo. However I am getting missing protocol errors. I'm using a fairly generic linux setup.

To reproduce:

1. Switch off automatic smudge / process:

```
git config --global filter.lfs.smudge "git-lfs smudge --skip %f"
git config --global filter.lfs.process "git-lfs filter-process --skip"
```

2. Create a lfs repo:

```
mkdir test
cd test
git init
git lfs track *.bin
echo "wibble" > data.bin
git add data.bin
git commit -m test data.bin
```

3. Clone the repo:

```
cd ..
git clone test test2
cd test2
```

No files will be fetched yet because we switched off the automatic smudge earlier. However if we fetch them we get an error:

```
$ git lfs fetch
Fetching master
Git LFS: (0 of 1 files) 0 B / 7 B
batch request: missing protocol: "/home/bob/git/test.git/info/lfs"
error: failed to fetch some objects from '/home/bob/git/test.git/info/lfs'
```

The path given in the missing protocol error doesn't make any sense!

**Comment by ttaylorr** [comment]
> The path given in the missing protocol error doesn't make any sense!

I think that this error message is clear enough; the path that you gave is missing a protocol. In other words, you have to have a (support) protocol in order to use Git LFS. Today, this means that you can interact with Git over HTTP(s) and SSH, and LFS will translate both of those into the appropriate HTTP(s) endpoints.

We don't have support for local directory-to-directory clones, but this is something that I would not be opposed to supporting in the future. I don't have the time to work on this myself, but if a contributor is interested in getting started I (+ anyone from @git-lfs/core) would be more than happy to help them out.

In the meantime, you can use `lfs.storage` in order to configure a shared storage location on disk.

**Comment by Gaff** [comment]
@ttaylorr - thanks

The error is confusing since I'd expect it to be  `/home/bob/git/test**/**.git/info/lfs` - note the extra `/`
Perhaps an explicit note about supported protocols would be better?

This is doubly surprising since if you don't disable the smudge then the initial checkout works. The error just happens further on.

> In the meantime, you can use lfs.storage in order to configure a shared storage location on disk.

Have you got a link that explains how to set this up?

Thanks!

**Comment by ttaylorr** [comment]
> > In the meantime, you can use lfs.storage in order to configure a shared storage location on disk.
> 
> Have you got a link that explains how to set this up?

Sure, the information in `git lfs help config` under `lfs.storage` should be useful.
