### ISSUE TITLE
Cannot turn off automatic downloads

### ISSUE THREAD

**Issue by lenytu** [git-lfs/git-lfs#3085]
Hi,
A lot of existing issue talk about his problem and i tried a lot of propose solution. But I cannot work it  out.

I added the required lines to the gitconfig file by executing:
`git config --global filter.lfs.clean "git-lfs clean -- %f" `
`git config --global filter.lfs.process "git-lfs filter-process --skip"`
`git config --global filter.lfs.smudge "git-lfs smudge --skip %f"`

Here is the result of _git lfs env_
`git-lfs/2.4.2 (GitHub; windows amd64; go 1.8.3; git 6f4b2e98)
git version 2.18.0.windows.1

Endpoint=https://simsoft3d.visualstudio.com/defaultcollection/SS3D-Repository/_git/SS3D.git/info/lfs (auth=none)
LocalWorkingDir=C:\temp\tmp_lfs
LocalGitDir=C:\temp\tmp_lfs\.git
LocalGitStorageDir=C:\temp\tmp_lfs\.git
LocalMediaDir=C:\temp\tmp_lfs\.git\lfs\objects
LocalReferenceDir=
TempDir=C:\temp\tmp_lfs\.git\lfs\tmp
ConcurrentTransfers=3
TusTransfers=false
BasicTransfersOnly=false
SkipDownloadErrors=false
FetchRecentAlways=false
FetchRecentRefsDays=7
FetchRecentCommitsDays=0
FetchRecentRefsIncludeRemotes=true
PruneOffsetDays=3
PruneVerifyRemoteAlways=false
PruneRemoteName=origin
LfsStorageDir=C:\temp\tmp_lfs\.git\lfs
AccessDownload=none
AccessUpload=none
DownloadTransfers=basic
UploadTransfers=basic
GIT_EXEC_PATH=C:/Program Files/Git/mingw64/libexec/git-core
GIT_LFS_PATH=C:\Program Files\Git LFS
git config filter.lfs.process = "git-lfs filter-process --skip"
git config filter.lfs.smudge = "git-lfs smudge --skip %f"
git config filter.lfs.clean = "git-lfs clean -- %f"
`
Everytime I clone or pull the repository, all the tracked files are downloaded.
Could you please help me to find what is wrong with my LFS configuration or  usage in order to be able not to automatically download all LFS items when cloning/pulling?

Thank you

[update]
I run on Windows. 
git version : 2.18.0
git lfs version: 2.4.2

**Comment by ttaylorr** [comment]
Hi @lenytu; thanks for opening this issue and sorry that you're having some trouble. What's going on is this: the configuration that you posted above is the correct one for turning Git LFS "off," but the `git lfs clone` command overrides this configuration, because it assumes that you want to download Git LFS objects. 

Today, you can give invoke your clone as `git lfs clone --skip-repo`, which will tell Git LFS _not_ to install itself within your repository. That and the configuration that you posted above is sufficient to not download Git LFS objects.

However, the `git lfs clone` command is deprecated, and will be removed in v3.0.0, so I encourage using `git clone` instead. `git clone` does not have a `--skip-repo` flag (since it's LFS-specific), but also doesn't need one, since the Git LFS filters will respect your configuration.

**Comment by lenytu** [comment]
Thank you for your answer.
I was talking about `git clone` (not `git lfs clone`).
Git LFS filters seem not working when cloning the repo with `git clone` , all LFS objects are downloaded...

**Comment by ttaylorr** [comment]
> Git LFS filters seem not working when cloning the repo with `git clone` , all LFS objects are downloaded...

You can fix this with `git lfs install --skip-smudge --force`.

**Comment by lenytu** [comment]
I have just tested and same problem

i have a "corpora" folder which is tracked by LFS.
On the machine PC1, I added a new file "f5.txt" to "Corpora".
On the machine PC2, I did:

```
admin@DESKTOP-2GS5DLG MINGW64 /C/temp/tmp_lfs (LFS_test)
$ git lfs install --skip-smudge --force
Updated git hooks.
Git LFS initialized.
```

and finally I pull:
```
admin@DESKTOP-2GS5DLG MINGW64 /C/temp/tmp_lfs (LFS_test)
$ git pull
remote: Microsoft (R) Visual Studio (R) Team Services
remote: Found 3 objects to send. (956 ms)
Unpacking objects: 100% (3/3), done.
From https://XXXX.visualstudio.com/defaultcollection/XXXX-Repository/_git/XXX
   1d8c1aad4..52c7d10b5  LFS_test   -> origin/LFS_test
Updating 1d8c1aad4..52c7d10b5
Fast-forward
 Corpora/f5.txt | 3 +++
 1 file changed, 3 insertions(+)
 create mode 100644 Corpora/f5.txt
```
f5.txt is automatically downloaded and tracked...

```
$ git lfs ls-files
ba23d48c15 * Corpora/f1.txt
ba23d48c15 * Corpora/f2.txt
bbdf7b8c3c * Corpora/f3.txt
bbdf7b8c3c * Corpora/f4.txt
bbdf7b8c3c * Corpora/f5.txt
```

**Comment by ttaylorr** [comment]
Does `f5.txt` contain the contents that you expect it to? It appears to be three lines long, which is the length of an LFS pointer (indicating that it wasn't downloaded, since there is no LFS output in your attached message.)

If not, please re-run the command with `GIT_TRACE=1` in your environment and post the output here.
