### ISSUE TITLE
git lfs install only once: per project or system-wide?

### ISSUE THREAD

**Issue by ousia** [git-lfs/git-lfs#3087]
Sorry for the basic question

`git lfs install` has to be set only once.

Is this per project or per system?

I’m afraid that I pushed various commits in two different repositories without running the command and everything worked fine. After running the command, I’m not able to push a commit with LFS files in another repository.

**Comment by ttaylorr** [comment]
Hi @ousia, thanks for opening this and asking.

> Is this per project or per system?

You need only run `git lfs install` once per-system as the process invoked by Git to filter contents on checkout will install the necessary bits for your repository. If you're having trouble inside your repository, you can always run a "just-in-case" invocation of `git lfs install`, which should fix anything that's misbehaving.

**Comment by yoav-klein** [comment]
Hi @ttaylorr , [This document](https://www.atlassian.com/git/tutorials/git-lfs) states that you need to run `git-lfs install` for each new repository. Can you help me with my confusion?

**Comment by bk2204** [comment]
Hey,

When you run `git lfs install`, it installs the settings in the global (per-user) configuration file (unless you specify `--system` or `--local`).  As a result, you should only need to run it once per user per system.  However, if you do what I've done and include the settings in your `~/.gitconfig` in the dotfiles you use across machines, then you don't actually have to run it at all, since those settings will be present on every machine you use.

Hopefully that answers your question.
