### ISSUE TITLE
git lfs svn cloning file in history not lfs'ed

### ISSUE THREAD

**Issue by praveencasimir** [git-lfs/git-lfs#3106]
Hi Team,

I am cloning an svn repository using git svn clone repourl.
The SVN instance with all its history is cloned to the local git repo.
i then cd'ed into the repo folder and typed git lfs install and got installation successful.
under folder A then i tracked *.jfr files which is present under A/B/C/D/filename.jfr
i got confirmation that file is tracked. but now when i do git push origin master i am not able to push the whole repository i am getting error like below.

$ git push origin master
Enumerating objects: 45386, done.
Counting objects: 100% (45386/45386), done.
Delta compression using up to 4 threads.
Compressing objects: 100% (11435/11435), done.
Writing objects: 100% (45386/45386), 1.16 GiB | 5.35 MiB/s, done.
Total 45386 (delta 30318), reused 44502 (delta 29434)
remote: Resolving deltas: 100% (30318/30318), done.
remote: warning: File Testing/MockServerWorkspace/TestFramework/lib/wlfullclient.jar is 61.76 MB; this is larger than GitHub Enterprise's recommended maximum file size of 50.00 MB
remote: warning: File Testing/PerformanceTesting/JFR/DEV/03/EmailInbound-500_Fax-250_170151WebLogicServer21557_10Nov2017.jfr is 75.10 MB; this is larger than GitHub Enterprise's recommended maximum file size of 50.00 MB
remote: error: GH001: Large files detected. You may want to try Git Large File Storage - https://git-lfs.github.com.
remote: error: File Testing/PerformanceTesting/JFR/DEV/03/filename1.jfr is 151.02 MB; this exceeds GitHub Enterprise's file size limit of 100.00 MB
remote: error: File Testing/PerformanceTesting/JFR/DEV/04/filename2.jfr is 168.73 MB; this exceeds GitHub Enterprise's file size limit of 100.00 MB
To github.celgene.com:Organization/Project.git
 ! [remote rejected]   master -> master (pre-receive hook declined)
error: failed to push some refs to 'git@github.celgene.com:Organization/Project.git'

Kindly help

**Comment by ttaylorr** [comment]
Hi @praveencasimir, thanks for opening this issue and I'm sorry that you're having trouble! It looks like you issued the SVN->Git migration successfully, but there are still some larger files in your history.

> under folder A then i tracked *.jfr files which is present under A/B/C/D/filename.jfr
> i got confirmation that file is tracked. but now when i do git push origin master i am not able to push the whole repository i am getting error like below.

I see. This is because `git lfs track` only marks files added later in the history to be stored with Git LFS, not ones that already exist. To bring in existing history into LFS, you can issue the following command:

```ShellSession
$ git lfs migrate import --everything --include="*.jfr`
```

which will modify your existing repository history and include all `*.jfr` files in Git LFS. In the future, you will no longer have to run `git lfs migrate` or `git lfs track`, since Git LFS will be configured correctly and your history will be intact.

If you have any questions or run into any issues in the future, please do not hesitate to let me know here and I would be more than happy to help out! Thanks.

**Comment by praveencasimir** [comment]
This command worked.  Thanks a ton @ttaylorr
