### ISSUE TITLE
Obey rate-limits, instead of crashing

### ISSUE THREAD

**Issue by max-wittig** [git-lfs/git-lfs#3122]
Some Git LFS servers might be rate-limited. When that is the case and the HTTP response 429 (Too many requests) is send, Git LFS will just crash.

Instead it should wait as long as specified in the [Retry-After response HTTP header](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Retry-After), if this header was send by the server.

Example of a crash in Git LFS, when rate limit is exceeded. 

```
git clone https://git:MYTOKEN@code.somegit.com/example/example/example.git example
Cloning into 'example'...
remote: Counting objects: 1027, done.
remote: Compressing objects: 100% (885/885), done.
remote: Total 1027 (delta 91), reused 1017 (delta 86)
Receiving objects: 100% (1027/1027), 151.15 KiB | 2.19 MiB/s, done.
Resolving deltas: 100% (91/91), done.
Downloading example/data/example/class01/00000185.png (208 KB)
Error downloading object: example/data/example/class01/00000185.png (922316c): Smudge error: Error downloading example/data/example/class01/00000185.png
(942616ce675326ca5e8g31392aaa19eg3cfe3d17ae0p4e5991a930f716ca6eaa): batch response: Rate limit exceeded: https://git:MYTOKEN@code.somegit.com/example/example/example.git example/info/lfs/objects/batch

Errors logged to /home/example/code/tmp/example/.git/lfs/objects/logs/20180628T152316.531135072.log
Use `git lfs logs last` to view the log.
error: external filter 'git-lfs filter-process' failed
fatal: example/data/example/class01/00000185.png: smudge filter lfs failed
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry the checkout with 'git checkout -f HEAD'

```

**Comment by ttaylorr** [comment]
Hi @max-wittig, thanks for opening this. This looks like a good feature to add, though I do not think that I have the time myself to look at this now.

Perhaps someone else from @git-lfs/core would be interested? If not, any one of us would be more than happy to mentor a contributor though this change. Thanks!

**Comment by mathstuf** [comment]
In #3344 I propose supporting multiple `lfs.url` settings. If each is supported for reading, falling back to the next URL and only retrying rate limited servers after the timeout would be something to think about.

**Comment by max-wittig** [comment]
@mathstuf That sounds like a completely different topic to me. Having one url and it should also work and cause GitLFS to wait until the `Retry-After` Header was received.

**Comment by zkry** [comment]
@ttaylorr
 Hello. If possible I'd like to work on this. I'v been looking into this and I think I have at least a good starting point for a solution. I can send the PR in bit.

**Comment by lmbarns** [comment]
Why is this closed, it's still an issue people are facing and I see no solution?

**Comment by mathstuf** [comment]
Do you have at least git-lfs 2.7.0?

**Comment by lmbarns** [comment]
When I download the windows installer here at the bottom of the page for 2.8.0, it claims to be 2.8.0: git-lfs/git-lfs

| 
| 
| 
|  |  |

 |

 |
| 
|  | 
git-lfs/git-lfs

Git extension for versioning large files. Contribute to git-lfs/git-lfs development by creating an account on Gi...
 |

 |

 |


But when I install it and do git lfs env it shows :
git-lfs/2.0.1 (GitHub; windows amd64; go 1.8; git 678cdbd4)git version 2.12.2.windows.1
How do I otherwise get the 2.7+ version? 
ThanksLee

**Comment by lmbarns** [comment]
Tried downloading 2.7.1, uninstalled previous version, put new lfs exe in my folder, ran git lfs install again where I have the %PATH% variable set, env shows old version still, 
Image attached.

**Comment by mathstuf** [comment]
I don't think email attachments get posted to here; you'll have to attach it through the web interface. I suspect that the older version is in your `%PATH%` first somewhere. There's a `where` program on Windows apparently, but `where /?` should be consulted on how to get the information you need from it. That should get you a full path to the `git-lfs` that's being found and hopefully that can make it easier to figure out what needs upgraded.

**Comment by bk2204** [comment]
If you're on Windows, the easiest way to get a newer Git LFS is to update Git for Windows to the latest version.  Git for Windows installs the binary into `GIT_EXEC_PATH`, I believe, so installing a newer version has to go there, not into your `PATH`.

**Comment by lmbarns** [comment]
It apparently only happens with https links. I used the ssh link an it wasn't working, but made a new ssh certificate and added it to my account and magically it worked. The error wasn't really identifying that as the problem but it seems that it was. And the Unity 3d link to their FPS example never mentioned needing the ssh link instead of the default https one. I guess they should update their documentation. 
Thanks for your time.

**Comment by lmbarns** [comment]
I figured it out. For some reason it was related to ssh.  Initially I was trying to download from the https link, that failed midway through, tried with the ssh link and it was saying not authorized, so setup a new ssh key, added it to github account, tried again and it pulled successfully. Error it was giving wasn't entirely helpful, bandwidth exceeded rather than authentication failure, and Unity's documentation didn't mention you had to use the ssh link so they should update that.
Thanks for your time, Lee



    On Wednesday, October 9, 2019, 01:41:14 PM UTC, Ben Boeckel <notifications@github.com> wrote:  
 
 
I don't think email attachments get posted to here; you'll have to attach it through the web interface. I suspect that the older version is in your %PATH% first somewhere. There's a where program on Windows apparently, but where /? should be consulted on how to get the information you need from it. That should get you a full path to the git-lfs that's being found and hopefully that can make it easier to figure out what needs upgraded.

**Comment by dlouzan** [comment]
@bk2204 Based on some failed pipelines on our GitLab instance over the last weeks, we are suspecting that the [batch endpoint](https://github.com/git-lfs/git-lfs/blob/main/docs/api/batch.md) was not considered on #3449 is not properly handling the 429 throttle sent by the server on those requests.

Is this possible? We do not see any references to this scenario being tested on the source code, but maybe there was / is a specific reason for this? or is it just an oversight?

**Comment by bk2204** [comment]
It's definitely possible, but in that case, please open a new issue so we can track that, including appropriate reproduction steps.

**Comment by cowboy-ibm** [comment]
I'm seeing the errors pulling a repo that has ICU as a submodule:

Error downloading object: icu4j/main/tests/core/src/com/ibm/icu/dev/test/serializable/data/ICU_56.1/com.ibm.icu.util.UResourceTypeMismatchException.dat (7489b33): Smudge error: Error downloading icu4j/main/tests/core/src/com/ibm/icu/dev/test/serializable/data/ICU_56.1/com.ibm.icu.util.UResourceTypeMismatchException.dat (7489b33a9ba56159a9c485b1854090105088395179c5e7bcb13e76ba85e7bf82): batch response: Rate limit exceeded: https://github.com/unicode-org/icu.git/info/lfs/objects/batch

The server is a corporate github.
The issue affects clients at various git-lfs levels, the current one is 3.2.0, git 2.39.1

Is there a way to see if it is client or server causing the issue - I know it is a server messages, but the client may not be respecting any response to throttle itself

**Comment by bk2204** [comment]
In some sense, all messages of this type are a client problem because the client has made too many requests in a short period of time.  However, this is also the normal behaviour of the client.

The specific problem here is likely that this is a public repository and by default neither Git nor Git LFS will authenticate unless it's required, and so you're probably seeing a lower rate limit than you'd normally see if you were authenticated.  That's why SSH works: because you're always authenticated, and thus you have a higher rate limit from GitHub.

This is the same thing as #5261 and I believe the desire for a `Retry-After` header has already been reported to GitHub.

**Comment by cowboy-ibm** [comment]
Yes, the http pull was from github.com.

It makes sense that since they've a custom rate limiting, that they should be the ones to tell the client about it.

I am happy that I was able make all of my submodule origins ssh based and avoid the issue altogether

Thank your for your time, and the explanation
