### ISSUE TITLE
Git lfs migrate just delete a whole bunch of unstaged file changes out of my repository.

### ISSUE THREAD

**Issue by Merglasch** [git-lfs/git-lfs#3123]
What it says above. The uncommited changes weren't even in files that git lfs should track. I'm going a bit bonkers here. Does the migrate command just delete all changes that are uncommitted and unrelated to tracked filetypes without warning? Can I somehow undo this mess? 

lsf shows no tracked files.

Git LFS objects to be pushed to origin/develop:
also none

Git LFS objects to be committed:
also none

Git LFS objects not staged for commit:
also none

size of the lfs folder: 230 mb.

used commands:

git lfs migrate import --include="*psd"
migrate: Sorting commits: ..., done
migrate: Rewriting commits: NaN% (0/0), done
migrate: Updating refs: ..., done

git lfs migrate import --include="*.psd"
migrate: Sorting commits: ..., done
migrate: Rewriting commits: NaN% (0/0), done
migrate: Updating refs: ..., done

git lfs migrate import --include="*.png"
migrate: Sorting commits: ..., done
migrate: Rewriting commits: NaN% (0/0), done
migrate: Updating refs: ..., done

It seems to have thrown away every change that wasn't a newly added file

I'd be really thankful for some help

**Comment by esopalumpa** [comment]
Same here.
All files that are staged (added but not commited) get eliminiated by “git lfs migrate import …”

**Comment by ttaylorr** [comment]
Hi @Merglasch, thanks for opening this. Thanks also @esopalumpa for confirming the issue.

> Does the migrate command just delete all changes that are uncommitted and unrelated to tracked filetypes without warning?

Yes, by design the `git lfs migrate` command uses `git checkout --force` to refresh the working copy after a migration, which does throw away local changes.

Unfortunately, without a backup there is no way to recover thees missing files. I am hesitant to change the requirement and enforce "your working copy must be clean" before migrating, since a common problem is that a user's working copy is unable to be made clean without invasive change and hence requires a migration.

Instead, what about a warning? Perhaps, "your working copy is modified, do you wish to continue?"

**Comment by Merglasch** [comment]
For the love of god please change this.

git lfs migrate should either:
...not use git checkout --force at all. If it really is a requirement, then just prevent the migration and let the user do the force checkout themselves.
... offer a force option with that. Fail on a modified working copy without the force option, inform the user and request they clean their copy or try again with the force option.

If that is not an option you should at the very least as you said warn the user that you're about to perform a force checkout. Heck this is not even mentioned in the wiki! I've just lost a significant amount of work to this design decision. Yes I could have saved my lfs unrelated changes beforehand, but seriously the very last thing I want and expect my version control system to do is just silently deleting files from under my butt as a side effect from other tasks!

Sorry if that sounds aggressive, but I am incredibly angry right now...

**Comment by ttaylorr** [comment]
> If that is not an option you should at the very least as you said warn the user that you're about to perform a force checkout.

I think that's a great idea per your comment and mine above in https://github.com/git-lfs/git-lfs/issues/3123#issuecomment-403874400. I'm implementing such a warning as we speak and it looks like this:

```
~/src/repository (master!) $ git lfs migrate import
migrate: override changes in your working copy? [Y/n] y
migrate: changes in your working copy will be overridden ...
migrate: Fetching remote refs: ..., done
# ...
```

> I've just lost a significant amount of work to this design decision. Yes I could have saved my lfs unrelated changes beforehand, but seriously the very last thing I want and expect my version control system to do is just silently deleting files from under my butt as a side effect from other tasks!

I'm sorry that you've lost work due to this change, and we'll work to make sure that this doesn't happen again.

**Comment by ttaylorr** [comment]
https://github.com/git-lfs/git-lfs/pull/3124

**Comment by ttaylorr** [comment]
> A clear warning should be the least. something like “your working copy
> is modified, If you continue 24 files will be obliterated”. or
> something like this. This is not even mentioned in the man-page.

The pull request that I wrote to address this situation does roughly
this. It indicates that the working copy will be destroyed if and only
if the user chooses to proceed.

> Deleting files, that are not even part of the operation, without
> warning is the last one expects from a version control system.

Agreed; and once again I'm sorry that the tool didn't behave as you
expect.

**Comment by janosh** [comment]
I just lost a whole lot of work to this myself. I completely agree with @Merglasch and @esopalumpa that
> migrate: override changes in your working copy? [Y/n]

isn't nearly enough of a warning. No red lights, no ALL CAPS, no "Please be extra certain that you want to proceed at the peril of losing work" or something like that.

In the end it's my fault for not reading the warning carefully enough before continuing but the reason I didn't is precisely because it looked so ordinary. This really needs to attract more attention.

**Comment by janosh** [comment]
Also, what's wrong with using `git stash` to get a clean copy and then let the user reapply stored changes afterward rather than just discarding them?

**Comment by evo978** [comment]
[工作資料.pdf](https://github.com/git-lfs/git-lfs/files/3438566/default.pdf)

**Comment by evo978** [comment]
#3511

**Comment by evo978** [comment]
＃重複 @ #3739

**Comment by drone1** [comment]
Just lost work due to this command. Jesus christ. For some reason a git lfs pointer got screwed up on a file in my repo -- and note, I wasn't even messing about with git lfs or the file, or files that rely on git lfs in the first place --  and I ran 
```git lfs migrate import --include-ref=HEAD~10 --include=<my file path>```
git lfs asked me if I wanted to overwrite my working copy. I said yes, and it nuked all my unstaged changes. What in the hell kind of behavior is this?

**Comment by bk2204** [comment]
Hey,

I'm sorry to hear that you lost data here. That's never enjoyable. If y'all would like to see an improvement in the text for this situation, opening a new issue would be a great way for us to track that. I'm not sure that `git stash` is always going to save the files in this case (it may, but there may also be cases where it would not) since some of them may be LFS files, and stashing them might not be effective, but we would definitely be interested in improving the text if it's not clear enough what the consequences of saying yes are.

**Comment by janosh** [comment]
@bk2204 I just opened #3741.

**Comment by xuefeiyan** [comment]
@ttaylorr you are a son of bitch

**Comment by bk2204** [comment]
Hey, folks,

I realize that a lot of people visit this issue because they may have lost data and that's frustrating, but name-calling is not acceptable here.  We expect everyone participating in the Git LFS project to abide by the [code of conduct](https://github.com/git-lfs/git-lfs/blob/master/CODE-OF-CONDUCT.md).

If we can't keep things courteous, the core team will take appropriate steps, including, if necessary, locking issues or blocking folks.

Thanks for your co-operation.

**Comment by mcmanus-git** [comment]
Even with warning `migrate: override changes in your working copy?  All uncommitted changes will be lost! [y/N] y` and having committed all my changes, I've lost everything. I'm not sure why everything has been lost even though I've committed all my changes.  Pretty, frustrated/confused.

**Comment by Irashad** [comment]
> What it says above. The uncommited changes weren't even in files that git lfs should track. I'm going a bit bonkers here. Does the migrate command just delete all changes that are uncommitted and unrelated to tracked filetypes without warning? Can I somehow undo this mess?
> 
> lsf shows no tracked files.
> 
> Git LFS objects to be pushed to origin/develop: also none
> 
> Git LFS objects to be committed: also none
> 
> Git LFS objects not staged for commit: also none
> 
> size of the lfs folder: 230 mb.
> 
> used commands:
> 
> git lfs migrate import --include="*psd" migrate: Sorting commits: ..., done migrate: Rewriting commits: NaN% (0/0), done migrate: Updating refs: ..., done
> 
> git lfs migrate import --include="*.psd" migrate: Sorting commits: ..., done migrate: Rewriting commits: NaN% (0/0), done migrate: Updating refs: ..., done
> 
> git lfs migrate import --include="*.png" migrate: Sorting commits: ..., done migrate: Rewriting commits: NaN% (0/0), done migrate: Updating refs: ..., done
> 
> It seems to have thrown away every change that wasn't a newly added file
> 
> I'd be really thankful for some help

It destroyed whole game repository of mine. the most stupid tool eve
