### ISSUE TITLE
All pointer files

### ISSUE THREAD

**Issue by laynef** [git-lfs/git-lfs#3128]
I just lost my entire GitHub repo. Every file is a pointer file.

Like this:

version https://git-lfs.github.com/spec/v1
oid sha256:dd7b8ead14025a6b19822c1b1a37e8a30e081b746bc2408ecfd190c405c68bf6
size 1395

I don't have the original folder anymore just this repo of pointers.

How do I get my repo back to the original code?

**Comment by laynef** [comment]
And the github repo is all pointers and the objects do not exist on the server [404]

**Comment by ttaylorr** [comment]
Hi @laynef, thanks for opening this issue and I'm sorry that you're
having problems.

> I just lost my entire GitHub repo. Every file is a pointer file.

It sounds like what happened here is that you cloned a
repository using Git LFS without having `git lfs` properly installed on
your computer.

Git LFS relies on Git invoking the Git LFS binary in order to convert
from the pointer file (which you can see an example of below) to the
large contents as they appear in your working copy.

To ensure that you have Git LFS installed correctly, you can run

    $ git lfs install --system --skip-repo

And then Git commands should work as normal. Please don't hesitate to
contact me here if this isn't the case.

> Like this:
>
> version https://git-lfs.github.com/spec/v1
> oid sha256:dd7b8ead14025a6b19822c1b1a37e8a30e081b746bc2408ecfd190c405c68bf6
> size 1395

As mentioned above, this is the format of an un-converted Git LFS
object.

> I don't have the original folder anymore just this repo of pointers.
>
> [ ... ]
>
> How do I get my repo back to the original code?

Unfortunately, without an original copy of the repository, or a copy
pushed to a Git LFS remote, there is no way to recover the original
objects.

**Comment by RiberWang** [comment]
> I just lost my entire GitHub repo. Every file is a pointer file.
> 
> Like this:
> 
> version https://git-lfs.github.com/spec/v1
> oid sha256:dd7b8ead14025a6b19822c1b1a37e8a30e081b746bc2408ecfd190c405c68bf6
> size 1395
> 
> I don't have the original folder anymore just this repo of pointers.
> 
> How do I get my repo back to the original code?

I'm also meeting this, can you tell me how to resolve this problem?

**Comment by RiberWang** [comment]
How to recover the original objects. I push an original of the repository, but also like this:
version https://git-lfs.github.com/spec/v1
oid sha256:446a6063f3b698c388700d664a5173bd58a2f194808239a2073766021adca0ca
size 9195

Please excuse my poor English.

**Comment by bk2204** [comment]
As Taylor mentioned, you can use `git lfs install --system --skip-repo` to make sure Git LFS is installed. If you have your Git LFS data pushed to the `origin` remote, it should be possible to do a `git lfs fetch origin && git lfs checkout` and your data should be recoverable.

**Comment by RiberWang** [comment]
I don't think so, it's at the time I submit frameworks.How to put it to the frameworks correctly？

**Comment by bk2204** [comment]
> I don't think so, it's at the time I submit frameworks.How to put it to the frameworks correctly？

I'm not sure I understand what you're trying to say. If you're saying that this happens as soon as you make a commit, then you definitely need to run `git lfs install` to make sure that the repository is properly configured, and run `git lfs checkout` should check out the files that weren't written because `git lfs install` hadn't run.

If you're still seeing issues, please include the output of `git lfs env` and `git config -l` so that we can see what your configuration is like.
