### ISSUE TITLE
lfs migrate import doesn't work with subfolders

### ISSUE THREAD

**Issue by lcsondes** [git-lfs/git-lfs#3149]
I have a repo with a bunch of binary files.

After running this (directly from my process, so the quoted strings are passed verbatim to git's argv without any shell processing them):
```
"git" "lfs" "install"
"git" "lfs" "migrate" "import" "--skip-fetch" "--everything" "--include=*.dll,*.zip,Third_Party_Libraries/**"
"git" "reflog" "expire" "--expire=now" "--all"
"git" "gc" "--prune=now"
"git" "repack" "-a" "-d" "-f" "--depth=1000" "--window=1000"
```

I still have some binary files as Git objects:
```
All sizes are in kB's. The pack column is the size of the object, compressed, inside the pack file.
size   pack   SHA                                       location
20527  20420  4df0a802098afa854c48cb2ef49be5536fa91f16  Third_Party_Libraries/GDAL.Native.1.9.2/GDAL.Native.1.9.2.nupkg
1801   1794   e1374c5a23d4ca07c916083b34d87aead2912b3a  Third_Party_Libraries/NetTopologySuite.1.13.2/NetTopologySuite.1.13.2.nupkg
1376   1370   0b6dc21a5e284ac1d6a1ce7ce2514c01fdb3977b  Third_Party_Libraries/Newtonsoft.Json.4.5.11/Newtonsoft.Json.4.5.11.nupkg
1087   644    8acad0773ed01064e966c3c3d674636e6b7200cc  Third_Party_Libraries/GDAL.Native.1.9.2/gdal/share/ntv1_can.dat
```

It seems that the "*.extension" filters get applied but the "folder/**" ones don't. I have also tried using one --include for each filter (on a fresh repository), which had the same result. What's the correct syntax?

**Comment by ttaylorr** [comment]
Hi, thanks for opening this issue. I agree that the `*.nupkg` match should match in sub-folders, but this is a hold-over from the old pattern matching semantics which are deprecated and will change to match your expected behavior in v3.0.0.

That said, the last option `ThirdPartyLibraries/**` should work as expected. I set up the same directory structure on my computer and ran `git lfs migrate import` with that `--include` argument and it migrated files in that folder at arbitrary depth.

Can you please indicate what version of Git LFS you are on? If you're not on the most recent, please upgrade, since pattern matching semantics have changed slightly over time. If that's not the issue, please don't hesitate to ping me here and I'd be more than happy to help you out! Thanks.

**Comment by lcsondes** [comment]
Thanks for your response. My version is `git-lfs/2.4.2 (GitHub; linux amd64; go 1.10.3)`

**Comment by ttaylorr** [comment]
Hm, definitely the latest. Can you re-run with `GIT_TRACE=1` in your environment and post the output here?

**Comment by lcsondes** [comment]
`GIT_TRACE=1` was immensely useful! What happened is that the file in question was moved to its current location from another folder sometime in Git history. Adding the source folder to the --include list migrated it to LFS entirely.

Thank you so much for your help.
