### ISSUE TITLE
Documentation update: Bootstrap script still referred to in wiki

### ISSUE THREAD

**Issue by jameshclrk** [git-lfs/git-lfs#3161]
2235198650d8dfadded525cc308ae8dfa786da52 removed the bootstrap script (amongst others) however the wiki still references the old script.

Can new contributers edit the repo's wiki?

**Comment by ttaylorr** [comment]
> 2235198650d8dfadded525cc308ae8dfa786da52 removed the bootstrap script
> (amongst others) however the wiki still references the old script.

Thanks for letting me know :-). Since I forgot, I went ahead and updated
the 'Installation' page of the Wiki to replace `script/bootstrap` with
`make` (its new counterpart).

I also double-checked that everything else in the wiki is up-to-date,
which it is.

> Can new contributers edit the repo's wiki?

Great question! Yes. Anybody is welcome to edit the wiki productively.
