### ISSUE TITLE
Enhance migrate import to support a file-size threshold as an alternative to path matching

### ISSUE THREAD

**Issue by tcfurrer** [git-lfs/git-lfs#3170]
I have a pre-existing git repo that is very large.  It has >10,000 files, and the bare repo consumes >50GiB.  Also, there are a relatively small number of large files, and they have similar paths/extensions to 1000's of other files that are tiny.  Furthermore, some of those file types are human readable text, where most of them are tiny and really don't belong in LFS, while just a few are gigantic and must move to LFS.

So the normal strategy of uploading all files with a given set of extensions to an LFS server is pretty horrible for my case.  I'm trying to upload this repo to a server with a strict object size limit (much like GitHub's 100MB file size limit), and after several days of frustrating attempts this using various tools, I have not been able to succeed yet in migrating all of the necessary blobs to LFS while not also migrating excessive amounts of other data.  I'm still attempting to do that to enable myself in the short term, but I'm filing this issue mostly on behalf of other future users of git-lfs who might be in the same situation.

This request is for git lfs migrate import to simply directly support a simple option for specifying a file/object size threshold, as an alternative to the existing include/exclude options which are based only upon pathname matching.  The functionality should be carefully designed and implemented to guarantee that the repo will satisfy the server-side hook protecting against large file uploads, while also minimizing the number of files that go to LFS.  After this type of import, the .gitattributes file would contain fully specified paths, with no wildcards present.  Future users of that repo would have to bear the responsibility for adding LFS tracking on any new large files they need to commit and push.  But that is a reasonable burden in a case where the repo has a large number of files, and large files are very rare, and operations like "git lfs pull" need to remain as fast as possible.

Having an LFS server that provides slower download speeds than your git server, as is unfortunately sometimes the case, further exacerbates the need to minimize the number of files stored by LFS.

Just given how many informal scripts I've been able to find where people were trying to identify the large files in their repo, and accurately prune them after the LFS import before pushing.... it seems there are a significant number of LFS users out there who would benefit from this feature (import size threshold) which would remove a significant barrier to entry.

**Comment by Nitimar** [comment]
Enhance migrate import to support a file-size threshold as an alternative to path matching #3170

**Comment by tcfurrer** [comment]
I realized in my case, I was actually hitting the issue discussed here:
https://stackoverflow.com/questions/15125862/github-remote-push-pack-size-exceeded
However, I still think this ticket is relevant as-is.

It sure would be nice if the migration instructions covered common issues like these (max file size limit, max push size limit, max total repo size limit) and provided good solutions, so that everyone migrating their git repos doesn't have to reinvent/rediscover the wheel.

**Comment by ttaylorr** [comment]
> This request is for git lfs migrate import to simply directly support
> a simple option for specifying a file/object size threshold, as an
> alternative to the existing include/exclude options which are based
> only upon pathname matching.

I see. I think my original reading of this is that you'd like `git lfs
migrate` to accept an `[--above=<size>]` option, and infer filepaths or
wildmatch expressions based on which files were above the given
threshold.

It sounds like instead what you'd like is for Git LFS to migrate in
_literal filenames_ in `.gitattributes` based on whether or not they are
above a given threshold.

> After this type of import, the .gitattributes file would contain fully
> specified paths, with no wildcards present.  Future users of that repo
> would have to bear the responsibility for adding LFS tracking on any
> new large files they need to commit and push.

There is a similar proposal in [1] that would allievate this concern
somewhat, but would still leave non-trivial wildmatch expression in your
.gitattributes. For example:

    *.txt filter=lfs diff=lfs merge=lfs above=1MiB

This all said, I am inclined to not modify 'git lfs migrate' based on
this, without significant interest from the rest of the community. I
suggest this because we can script around "give me filename that's above
$threshold" and then give that as an argument to 'git lfs migrate'.

For example, to do so only on HEAD, this will work:

    git lfs migrate import --include="$( \
      git ls-tree -lr "$(git cat-file -p HEAD \
          | grep '^tree' \
          | awk '{ print $2 }')" \
        | awk '$4 > 1000 { print $5 }' \
        | tr '\n' ',')"

Or, in other words: there are other tools that can give us the
information that we need, and they can be plugged into 'git lfs migrate'
appropriately. So, I'd prefer to use that rather than adding new knobs
to 'git lfs migrate'.

I think my train of thought is motivated primarily by how I think that
people use 'git lfs migrate import', which may or may not be how people
_actually_ use 'git lfs migrate import'. So, if I'm wrong, we should add
this.

So, if there's signifiant interest in such a feature, I would be happy
to add that to our current list, and I'm sure that we could add such a
feature.

[1]: https://github.com/git-lfs/git-lfs/issues/282

**Comment by kirkilj** [comment]
I agree on its relevance, in our use case at least. I was hoping to have more options for filtering. I've seen a couple talks where the recommended cut-off size to balance tracking a large number of small binaries is around 500K to 1MB. Any binary more than that would be tracked by lfs, but we'd also like any source code text file, no matter what the size it is to be tracked in vanilla Git. In absence of such capability, I'm interested in reasonable workarounds that would minimize what needs to be installed on each workstation.

**Comment by ttaylorr** [comment]
> I agree on its relevance, in our use case at least.

Noted, and thank you for sharing your interest.

> In absence of such capability, I'm interested in reasonable
> workarounds that would minimize what needs to be installed on each
> workstation.

I'm curious what you mean, since any repository using Git LFS can be
cloned with Git installed and Git LFS uninstalled. The checked out copy
of the repository will have pointer files in place of locations that are
tracked with Git LFS.

Would you be interested in minimizing the installation process
post-download?

Currently, on macOS, you run:

    $ brew install git-lfs
    $ git lfs install --system

**Comment by sjackman** [comment]
I found it incongruous that `git lfs migrate info --above=1MB` works but `git lfs migrate import --above=1MB` does not. I used the workaround of finding all the large files first and giving those to `git lfs migrate import --include`.

```bash
git rev-list --objects master \
| git cat-file --batch-check='%(objecttype) %(objectsize) %(rest)' \
| awk '$1 == "blob" && $2 >= 1000000 { print $3 }' \
| sort -u
```
