### ISSUE TITLE
Error: SHA256 mismatch when installing git-lfs

### ISSUE THREAD

**Issue by IcyW** [git-lfs/git-lfs#3174]
I got 

> ==> Downloading https://github.com/git-lfs/git-lfs/archive/v2.1.1.tar.gz
==> Downloading from https://codeload.github.com/git-lfs/git-lfs/tar.gz/v2.1.1
######################################################################## 100.0%
Error: SHA256 mismatch
Expected: 655c1e9bf931afb958c2b81de5c1c38b3ebd6831a04ca5fdcf58cba05e2948d8
Actual: 096bb2bfbb61313ba299c919bcb49fa92cfb1bdcdcbe06d8375dfdb672886aa9

after `brew install git-lfs`.

Running on MacOS High Sierra, 10.13.6.

**Comment by ttaylorr** [comment]
> I got:
>
> [ ... ]
>
> Error: SHA256 mismatch
> Expected: 655c1e9bf931afb958c2b81de5c1c38b3ebd6831a04ca5fdcf58cba05e2948d8
> Actual: 096bb2bfbb61313ba299c919bcb49fa92cfb1bdcdcbe06d8375dfdb672886aa9

I'm sorry about that. It appears that you are trying to install Git LFS
v2.1.1, which is significantly out of date. Can you please run:

    $ brew update

and then:

    $ brew uninstall --force git-lfs
    $ brew install git-lfs

Which ought to install the latest version of Git LFS (at the time of
writing, that's v2.5.1).

If you still are having an issue, I'd recommend that you post an issue
in Homebrew/homebrew-core's issue tracker, since I'm not sure that
there's anything _we_ can do to fix a historical version of Git LFS.

**Comment by IcyW** [comment]
@ttaylorr Thank you for your reply.
I've tried `brew update` but everything is already up-to-date.
I will try seeking for help in Homebrew/homebrew-core's issue tracker.
