### ISSUE TITLE
How can I track a binary file when there is a folder with the same name?

### ISSUE THREAD

**Issue by sjzcv** [git-lfs/git-lfs#3180]
I got a repos with dir structure as below

```
iOS
├── name
│   ├── other stuff
│   ├── ...
└── name.framework
    ├── Headers
    ├── Info.plist
    └── name
```

where `name` under `name.framework` is binary file which I want to track with lfs, and there's a folder with the same name

I track with name or full path

``` shell
git lfs track name
```

and got error as below:

remote: GitLab: LFS objects are missing. Ensure LFS is properly set up or try a manual "git lfs push --all".
To xxx.xxxx.com:xxxxxx/xxxxxxxxx.git
 ! [remote rejected] feature/test_lfs_framework -> feature/test_lfs_framework (pre-receive hook declined)
error: failed to push some refs to 'git@xxxxxx'

**Comment by PastelMobileSuit** [comment]
@sjzcv Hey! Git LFS doesn't actually track directories, just files within directories, so the fact that you have a directory named `name` at your top level shouldn't be a problem. `git lfs track name` should track all files named `name` within your directory tree, including `name.framework/name`.

The error you're seeing is a GitLab server error that generally means the server is missing some LFS objects that it's expecting to have. Could you try running `git lfs push --all <remote> <branch>`? This should push up all Git LFS objects to your remote.

**Comment by sjzcv** [comment]
@PastelMobileSuit Thanks for your kindly reply. The problem is when I don't track the folder name I don't need to run `git lfs push --all <remote> <branch>`.  And I don't want to track files under the directory named `name` by lfs, only the file one. How can I accomplish that?

**Comment by ttaylorr** [comment]
> @sjzcv Hey! Git LFS doesn't actually track directories, just files
> within directories

A minor nit, since I think it's pertinent to the discussion :-). Git LFS
tracks filepath patterns (colloquially "wildmatches") based on the
contents of your repository's .gitattribute file(s).

So, when we say "Git LFS tracks files", that's true to the extent that
wildmatch patterns are functions from filename to a boolean, but it's
not quite the case to say that "Git LFS tracks files" in the sense that
Git LFS can't track more complicated things like sets of files, or files
in a directory.

> so the fact that you have a directory named `name`
> at your top level shouldn't be a problem. `git lfs track name` should
> track all files named `name` within your directory tree, including
> `name.framework/name`.

That's not quite the case. Running "git lfs track dirname" will _not_
track all files within a directory called "dirname", if run at the top
level. There are two ways to accomplish this, however:

  1. `git lfs track 'dirname/*'` from the parent directory of "dirname"
  2. `git lfs track '*'` from within "dirname".

Either one of these should accomplish that, but my reading of the issue
doesn't indicate that that's what you're trying to do. It sounds like
what you want to do is track a file called "name" inside of a directory
called "name.framework", which you can do via:

    $ git lfs track "name.framework/name"

from the parent directory of "name.framework", which I assume is the
root of your repository.

> The error you're seeing is a GitLab server error that generally means
> the server is missing some LFS objects that it's expecting to have.

I agree with that assessment. It sounds like you need to (1) track this
file, and then (2) make sure that it has been pushed at least once. If
that's not the case, then I think it makes sense to contact GitLab's
support instead of ours.
