### ISSUE TITLE
git lfs fails "to push some refs" and "to fetch some objects"

### ISSUE THREAD

**Issue by fmessmer** [git-lfs/git-lfs#3184]
since recently, i.e. using `git-lfs/2.5.1 (GitHub; linux amd64; go 1.10.3)`, we are experiencing weird `git push` behavior - most likely related to the lfs files tracked in that repo:

 - freshly cloning the repo works fine and all (currently) tracked files are downloaded
 - `git push` fails with
    ```
    open <path_to_file>: no such file or directory
    error: failed to push some refs to 'https://github.com/XX/YY'
    ```
 - `git lfs fetch --all` fails with several errors like this:
    ```
    fetch: # object(s) found, done                                                                                  
    fetch: Fetching all references...
    [2187746389b0118d51e6741ce06565bc7e20ffd7702507ef2f6d6286899524c9] Object does not exist on the server: [404] Object does not exist on the server
    .........
    error: failed to fetch some objects from 'https://github.com/XX/YY.git/info/lfs'
    ```

The <path_to_file> references files no longer present in the repo.
However, the <path_to_file> seems to reference an old artifact which existed before we (incorrectly?) moved files preserving git history using `git filter-branch`...

Any idea how we could cleanup the git lfs history and/or get rid of the invalid objects/artifacts?
Thanks

**Comment by ttaylorr** [comment]
> since recently, i.e. using `git-lfs/2.5.1 (GitHub; linux amd64; go
> 1.10.3)`, we are experiencing weird `git push` behavior - most likely
> related to the lfs files tracked in that repo:

Does the problem occur in versions older than v2.5.0? Off the top of my
head, I can't think of anything that went into the v2.5.0 release that
would have changed this behavior in a significant way.

The "could not open /path/to/file" errors are caused when Git LFS tries
to find an object in its local cache (.git/lfs/objects), but fails
because it wasn't downloaded or is a part of an older revision that
was never checked out or fetched manually.

If it needs to push an older object, Git LFS will (upon a cache-miss)
try to find the file corresponding to that object in your working copy
as a last resort. When it can't do this, it dutifully reports the error
that you are seeing above.

> The <path_to_file> references files no longer present in the repo.

So, I think what's going on here is some combination of missing files
and the above that I mentioned.

> Any idea how we could cleanup the git lfs history and/or get rid of
> the invalid objects/artifacts?

We don't currently have an facility to do so (though I suspect one could
be added to 'git lfs migrate' without much difficulty). You can manually
grok history and remove the affected files with 'git filter-branch', or
alternatively:

    $ git config --local lfs.allowincompletepush true

Which will disable warnings for incomplete transfers.
