### ISSUE TITLE
Error: Failed to call Git-Parse? No idea what this means..

### ISSUE THREAD

**Issue by Deygus** [git-lfs/git-lfs#3198]
A Developer I am working with has decided to start using Git for our game project because we are using UE4 and it's a rather small game for source control.

I found this tutorial https://www.youtube.com/watch?v=Hv_v3tPuNj4 but after getting to the LFS part of the install in Git Bash I received an error and I have no idea why.

Is this something I should be worried about if I am just connecting to the project to download the files on my end since it's using LFS?

I'm not that good at programming stuff. Or maybe there's an easier way instead of having to install 3 different programs. 

I left all the programs at their default settings except for changing the vim editor to notepad++. That was the only thing I changed.

Any ideas? Thank you for the help in advance.

![2018-08-26_10h54_45](https://user-images.githubusercontent.com/4062943/44629597-b5901880-a91f-11e8-8257-62fd63971031.png)

**Comment by Deygus** [comment]
UPDATE:

So after installing Github Desktop I connected to the Developers Git I am working with and cloned it to my end where it looks like it downloaded all of the files. 

Then it asked me if I wanted to " Intialize LFS " because it detected that the project uses it so I clicked yes and it went through some process that seems to have been successful because I didn't run into any further errors yet.

So am I fine now maybe? I am not entirely sure...

**Comment by ttaylorr** [comment]
Thanks for opening this. Here's my best guess at what's going on: since
'git lfs install' would like to be run within a Git repository (so that
it can install some githooks), 'git lfs' tries to figure out whether it
is in a repository or not.

To detect this, 'git lfs' will run 'git rev-parse --show-toplevel',
which will fail (with the error message that you sent here) if it is run
outside of a repository.

To fix this, you can either install Git LFS from GitHub Desktop (or
similar), which will manage the installation for you. You can also run
the command from within a repository, or run it as 'git lfs install
--skip-repo', which doesn't install the repository-specific
configuration.

There is an existing issue discussing this, which I think we can close
this in favor of: https://github.com/git-lfs/git-lfs/issues/3013#issuecomment-390802139.
