### ISSUE TITLE
standalone transfer: LFS status doesn't change

### ISSUE THREAD

**Issue by buchanae** [git-lfs/git-lfs#3205]
I'd like to use git LFS to upload files to swift/s3/etc without requiring any server. As I understand, a [custom, standalone transfer agent](https://github.com/git-lfs/git-lfs/blob/master/docs/custom-transfers.md) would be the way to accomplish this.

My toy agent is here: https://github.com/buchanae/tanker  
Right now it fakes the upload by alway returning "complete" immediately.

git lfs reports a successful upload, but the status doesn't change, and a subsequent `push` will upload the file again:
```
git lfs push origin master
Uploading LFS objects: 100% (1/1), 0 B | 0 B/s, done
```

but the status of the file doesn't change:
```
> lfstest (master)
git lfs status
On branch master
Git LFS objects to be pushed to origin/master:

	data/frog.bin (95f078591376febf2ac43001c68b3f0aaa8a94b3a01e9cdae8f37fadd8de8ba8)

Git LFS objects to be committed:


Git LFS objects not staged for commit:


> lfstest (master)
git lfs push origin master
Uploading LFS objects: 100% (1/1), 1.0 MB | 0 B/s, done

> lfstest (master)
git lfs push origin master
Uploading LFS objects: 100% (1/1), 1.0 MB | 0 B/s, done

> lfstest (master)
git lfs status
On branch master
Git LFS objects to be pushed to origin/master:

	data/frog.bin (95f078591376febf2ac43001c68b3f0aaa8a94b3a01e9cdae8f37fadd8de8ba8)

Git LFS objects to be committed:


Git LFS objects not staged for commit:
```

Is something wrong? Did I misunderstand the capability of custom transfer agents? Is the server always required maybe?

Thanks.

**Comment by buchanae** [comment]
Oh, I need to run `git push origin master` instead. Duh.

**Comment by ttaylorr** [comment]
Hi Alex, thanks for opening this issue. I'm sorry that it took longer
than usual for me to respond to your note.

You are exactly right: you need to ensure that you have also done a push
of the Git objects to your Git remote.

What is roughly going on to display that part of "git lfs status"'s
output is that we're running a

  $ git rev-list HEAD ^@{u}

Which gives a list of all commits that are present locally, but _not_
present on the remote tracking branch.

Then, we check all of the blobs in that range that are under a certain
threshold, see if they are parse-able as Git LFS pointers, and then
report them as unpushed.

In practice, this isn't quite accurate, since it is possible to do a
'git lfs push' before a 'git push', in which case 'git lfs status' would
report (incorrectly) that the server does not have a set of remote
files.

That all said, I'm not sure if there is a remedy to this problem. In the
case of specification-compliant servers, we could certainly have a 'git
lfs ls-remote' (or similar), that could tell us about a list of OIDs, or
etc., and use _that_ as a basis for comparison instead of the "git
rev-list" example that I showed above.

But, I don't think that this would be enough to cover your case, too,
which uses a custom transfer adapter, and thus has no way of knowing via
any standard mechanism which objects the server does and does not have.

We could introduce that as an optional component of the custom transfer
adapter, e.g., "if you wish to be a custom transfer adapter, you must
respond to queries of the form, 'please list all objects present
upstream'.", but I'm not sure that that is a reasonable requirement to
ask.

I think that making that an optional capability of custom transfer
adapters makes it so that it would be sensible to support in "git lfs
status".

I'd be curious to get the thoughts of @git-lfs/core, @bk2204, and
@PastelMobileSuit.

**Comment by bk2204** [comment]
Yeah, I think that might make a nice optional capability of transfer adapters.  Since it would be optional, we'd be no worse off than before if the adapter didn't implement it.

**Comment by ttaylorr** [comment]
> Since it would be optional, we'd be no worse off than before if the
> adapter didn't implement it.

Agreed. Do you think that we should write a proposal issue for it? I'm
not sure as to the number of people using custom transfer adapters, so
that would have to affect our planning.

**Comment by bk2204** [comment]
I think that would be good.  We'd be able to solicit opinions from others on how they'd like it to work so we could make sure we didn't miss an important use case.
