### ISSUE TITLE
remote: error: GH008: Your push referenced at least 3 unknown Git LFS objects:

### ISSUE THREAD

**Issue by xinguanxi** [git-lfs/git-lfs#3231]
i use git lfs to upload several files, git push a new branch (not master), but there is always a error GH008, which says  Your push referenced at least 3 unknown Git LFS objects, and i goolges a lot ,but no result about GH008 , how to solve this error

**Comment by xinguanxi** [comment]
![screenshot from 2018-09-06 22-45-05](https://user-images.githubusercontent.com/13413761/45165328-33f59000-b227-11e8-9c42-9258edb3eabd.png)

**Comment by xinguanxi** [comment]
just like the image up

**Comment by larsxschneider** [comment]
👋 @xinguanxi ! Thanks for opening this issue. We, GitHub, recently shipped a new feature which ensures on `git push` that all Git LFS objects have been successfully uploaded earlier.

That means either your Git LFS objects have not been uploaded properly or there is a bug in our new feature. It would be great if we could work together to figure this out. It would be awesome if you could answer the following questions 😊 

1. What exact push command do you use?
2. Does your new branch have a `.lfsconfig` file in its root directory?
3. Can you give us the output of `git config --list | grep lfs`?
4. Can you give us the output of `git lfs ls-files | grep 2bfce`?

**Comment by xinguanxi** [comment]
@larsxschneider  of course, 
1. git push -u origin my_new_branch_name
2.no, there is not a .lfsconfig file in root directory
3./home/xgx/Music/Screenshot from 2018-09-07 10-13-45.png
4. 2bfce729d1 * bin/MDL/180906/dgVReIDConfig.json

**Comment by xinguanxi** [comment]
![screenshot from 2018-09-07 10-13-45](https://user-images.githubusercontent.com/13413761/45194750-faed0800-b286-11e8-84b1-cd52da90cb26.png)

**Comment by xinguanxi** [comment]
![screenshot from 2018-09-07 10-16-17](https://user-images.githubusercontent.com/13413761/45194774-122bf580-b287-11e8-9d9d-7fd22afae15f.png)

**Comment by xinguanxi** [comment]
the two picture above is the answer of 3rd and 4th questions respectively, and thank u so much for your reply

**Comment by larsxschneider** [comment]
Thanks for the info @xinguanxi - that was very helpful! The problem is the following Git config line:
```
lfs.url=http://matrix:matrix@192.168.2.21:9999
```

This line instructs Git LFS to upload LFS files to the server `192.168.2.21` and **not** to GitHub. This config line is **local** on your machine and therefore GitHub doesn't know about it. Consequently, GitHub tries to find the files on its own servers and fails.
 
You can solve that problem storing the information where LFS files are located in your repository.  Add a file `.lfsconfig` to the root of your repository with the following content:
```
[lfs]
	url = http://matrix:matrix@192.168.2.21:9999
```

That has also the nice side effect that other repository users do not need to change their local Git config if they want to work with your repository. You can learn more about `.lfsconfig` [here](https://github.com/git-lfs/git-lfs/blob/master/docs/man/git-lfs-config.5.ronn) and more about Git LFS in general [here](https://www.youtube.com/watch?v=YQzNfb4IwEY).

Please let me know if this solution works for you 😊!

**Comment by xinguanxi** [comment]
@larsxschneider , awesome, it works , and i am convinced that it will help people a lot who use private lfs server, May git lfs stronger and better blush!

**Comment by beto-JVD** [comment]
I'm struggling with a similar error, clear the cache and track the files it tells me they are missing and nothing, I can't upload this project to another new repository, initially I had it in one repository, but I made the decision to change and it doesn't I managed to solve this, any recommendations sir?



Issue Summary
I am facing a persistent issue with Git LFS objects when pushing my repository to GitHub. Despite multiple attempts to resolve the issue, I continue to encounter the error GH008 related to unknown Git LFS objects.

Error Message
plaintext
Copiar código
remote: error: GH008: Your push referenced at least 2 unknown Git LFS objects:
remote:     619ee24c6d20e1087214ee3012db6273f6454925b610b3cdc855d9c0776f04ea
remote:     040873716d7524beef0403afa8d7f7e3b741320dbd17dd631ed9c552d4db56f4
remote: Try to push them with 'git lfs push --all'.
To https://github.com/beto-JVD/EcommerceLaravelV1.0.git
 ! [remote rejected]   main -> main (pre-receive hook declined)
error: failed to push some refs to 'https://github.com/beto-JVD/EcommerceLaravelV1.0.git'
Steps Taken to Resolve the Issue
Uninstall Git LFS:

git lfs uninstall
Verify and Modify LFS Configuration:

Verified LFS configuration with git config --list | findstr lfs
Created .lfsconfig with the following content:
plaintext
Copiar código
[lfs]
    url = https://github.com/beto-JVD/EcommerceLaravelV1.0.git
Removed all references to LFS from .gitattributes
Clean and Repack Repository:

Executed:
powershell
Copiar código
git reflog expire --expire=now --all
git gc --prune=now --aggressive
Push Changes to Remote Repository:

Attempted to push with:
powershell
Copiar código
git push -u origin main --force
Use BFG Repo-Cleaner:

Cloned the repository in mirror mode:
powershell
Copiar código
git clone --mirror https://github.com/beto-JVD/EcommerceLaravelV1.0.git
Used BFG Repo-Cleaner to delete problematic files:
powershell
Copiar código
java -jar bfg-1.13.0.jar --delete-files sample2.pdf --delete-files sample.pdf
Repacked and attempted to push again:
powershell
Copiar código
git reflog expire --expire=now --all
git gc --prune=now --aggressive
git push --force --all
Current Status
Despite all these attempts, I still receive the GH008 error indicating unknown Git LFS objects when trying to push to the remote repository. Any guidance or solutions to resolve this issue would be greatly appreciated.


![issue1](https://github.com/git-lfs/git-lfs/assets/140455840/d4792ee8-06fa-4c85-acd2-842732be2d9e)
![issue2](https://github.com/git-lfs/git-lfs/assets/140455840/948f66ec-6830-4aa7-beb4-ed17894140b7)

**Comment by Elhazinforever** [comment]
I swear by allah i don't know anything about it before only someone was
learning me to do something name article and i wasn't good in the English
and i was trying to translate the website but not accepted i was pushing
any words until i find my self inside this Wikipedia website and i know he
is the controller of everything but i was not saying because i want knowing
how i can enter the building to finish this guys the attack me and hack my
mobile during i sleep with help from girl and when i want go he was put my
persnel picture and my data on the Google map with editing Photoshop also
and i wasn't knowing anything about technology zero اقسم بالله العظيم also
they was watching me by the mobile camera and listen everything and more
but every body disturbed me even they was have the mak and watch and other
devices i was only have 2 iPhone I then i fixed my wife mobile they hack
also i swear by allah then some other contact me to help i was have old
labtop deel they said open and they was supmet my email and iCloud and by
Microsoft and they was fool me also to pust java and collect data and can
enter any devices around me and WiFi when i start catch destroyed and also
was transferring alot of data on my labtop to say  im the crimnal more and
more to

في السبت، ٨ يونيو ٢٠٢٤ ٦:٠٠ ص beto-JVD ***@***.***> كتب:

**Comment by Elhazinforever** [comment]
في السبت، ٨ يونيو ٢٠٢٤ ٧:٠١ ص adel elwakil ***@***.***> كتب:

**Comment by l0rem1psum** [comment]
I'm in a similar situation where I accidentally uploaded some of the LFS objects to Github's server instead of our own S3 bucket. However, the difference is that we are using the [`lfs-s3` custom transfer agent](https://github.com/nicolas-graves/lfs-s3). I'm currently stuck in a split state where I can't push new objects since Github is giving me the "error: GH008: Your push push referenced at least x unknown Git LFS object" error.

I have also created an issue at the `lfs-s3` repo: https://github.com/nicolas-graves/lfs-s3/issues/116

Any help is greatly appreciated.

**Comment by chrisd8088** [comment]
@l0rem1psum — I'm sorry you're having trouble.

From the sounds of it, you should probably reach out to GitHub Support via their [contact channels](https://support.github.com/request/landing) and ask them to remove the Git LFS objects from their storage.  That's not something we can help with, as this project is just for the open-source Git LFS client.
