### ISSUE TITLE
Cannot push lfs files

### ISSUE THREAD

**Issue by haleyyew** [git-lfs/git-lfs#3239]
Hi,
I was exceeding limit for lfs, then I deleted my repository and tried to push less number of files. But I got this error:
`batch response: Git LFS is disabled for this repository.`
Help is appreciated.

Haoran

**Comment by ttaylorr** [comment]
Hi Haoran, thanks for opening this issue and I'm sorry that you're
having trouble.

I believe that this is a GitHub-specific concern having to do with the
fact that we won't immediately delete Git LFS objects when deleting a
repository, in case you shortly change your mind.

Since this repository offers support only for Git LFS-specific
concerns, can you instead send an email containing same message to:
support@github.com?

They would be more than happy to help you out. Thanks!
