### ISSUE TITLE
Git LFS hooks being created in repo dir

### ISSUE THREAD

**Issue by dareenzo** [git-lfs/git-lfs#3240]
Hey all.

I've got a repo with LFS setup and working. I noticed that there's a folder inside my repo with LFS hooks that keeps getting created even if I delete it. The folder is `~/.dotfiles/git/hooks`. This path is familiar, it is the path I have on my main `gitconfig` for global hooks (`core.hooksPath`), but I don't understand why it keeps getting created every time inside my repo. If LFS creates these hooks I think the"normal" behavior would place them inside the `.git` folder. 

How can I go around this? Is this a configuration issue I have or does it have something to do with LFS?

**Comment by bk2204** [comment]
When you have a `core.hooksPath` set for a repository, whether that's in the repository itself or in a more global config file, that's the only place that Git looks for hooks; it ignores the `.git/hooks` directory altogether.  So when that's set in your main `.gitconfig`, Git LFS will install the hooks wherever `core.hooksPath` points so that they'll be used.

If you don't want those installed in `~/.dotfiles`, you can set `core.hooksPath` for your repositories using Git LFS to point to the `.git/hooks` directory for their respective repos.

I see how this behavior can be surprising, but it works this way because otherwise Git LFS wouldn't work in this case.

**Comment by ttaylorr** [comment]
Hi, Paulo. I am glad that you mentioned 'core.hooksPath', since that's
exactly what I was thinking was going when I saw the subject line of
your issue :-).

core.hooksPath is a new(-ish) configuration setting that tells Git an
alternate location to place your repository hooks instead of in
.git/hooks (within the repository).

Since it's set, Git LFS will respect it (as of ac301aa6 (Merge pull
request #1409 from github/install-custom-hooks-path, 2016-08-02)), but
you can override it from within your repository by saying:

  $ git config --local core.hooksPath "$(git rev-parse --git-dir)/hooks"

I was thinking that you could say instead:

  $ git config --local --unset core.hooksPath

But I don't think that would do the trick, for some uninteresting
reasons having to do with how we decide when a configuration value is
and isn't set.

**Comment by ttaylorr** [comment]
Oof. brian's advice is totally good, and I responded to the issue before
seeing that he had done so already. Sorry!
