### ISSUE TITLE
git lfs stuck at "migrate: Fetching remote refs: ..."

### ISSUE THREAD

**Issue by Cambesa** [git-lfs/git-lfs#3247]
When I try to migrate a repository from our bitbucket server (which is hosted locally) to gitlab, and implement LFS retroactively in order to decrease the repository size; git is stuck at "migrate: Fetching remote refs: ...". I've waited for an hour and nothing happens. There's no percentage indication either so I'm not sure if it's just calculating or actually stuck. Git and git-lfs are up to date. I was using the command: git lfs migrate import --include="*.jpg" --include="*.mp3" --include="*.wav" --include="*.tga" --include="*.png" --include="*.mp4"

**Comment by bk2204** [comment]
This message doesn't have a percentage indicator: it goes directly from the state you're seeing to done.  In order to find out what's going on in this case, could you run `git fetch --all` and see if that succeeds or fails?  That's not _exactly_ what's going on here, but I'm hoping it will show us what the problem is.

**Comment by Cambesa** [comment]
Thanks for your reply, I think it was an authorization problem because I had clone problems yesterday which were automatically resolved today, both _git fetch --all_ and the migrate command worked today

**Comment by bk2204** [comment]
That's great.  Glad you got it working.
