### ISSUE TITLE
[faile] git push origin master and git push lfs origin master

### ISSUE THREAD

**Issue by yut148** [git-lfs/git-lfs#3248]
everyone.
I tried it like this.

$ git push origin master

So it was displayed like this

batch response: Repository or object not found: https://[username]@[ipv4addr]/git/[gitrepo].git/info/lfs/objects/batch
Check that it exists and that you have proper access to it
error: failed to push some refs to 'https://[ipv4addr]/git/[gitrepo].git'

What are the possible causes?

I tried this with the latest version.
$ git lfs --version
$ git-lfs/2.5.1 (GitHub; linux amd64; go 1.10.3; git e1628484)

These will be replaced.
[username]
[ipv4addr]
[gitrepo]

**Comment by bk2204** [comment]
Thanks for reaching out to us about this issue.  I have a few questions so that we can figure out what's going on here:

- Are you sure that the repository exists on the server side?
- Can you attempt to clone the repository into another path using the URL "https://[username]@[ipv4addr]/git/[gitrepo].git"?
- What server software and version are you using on the server side?
- Does the server software support Git LFS?
- Does the server have Git LFS turned on for this repository?

**Comment by yut148** [comment]
I will answer the question.
>Are you sure that the repository exists on the server side?
yes. Run git int on my server. I was able to run git clone on the client side.
The following message was displayed on the client side.

# git clone https://[username]@[ipv4addr]/git/[gitrepo].git
Cloning into '[gitrepo]'...
warning: You appear to have cloned an empty repository.

It is empty because it was just initialized.

>Can you attempt to clone the repository into another path using the URL "https://[username]@[ipv4addr]/git/[gitrepo].git"?
no. I do not have any other servers. I have not run it elsewhere.
I can clone by changing the settings on the server side and changing the path.

git lfs version
# git lfs env
git-lfs/2.5.1 (GitHub; linux amd64; go 1.10.3; git e1628484)
git version 1.8.3.1

using this rpm.
git-lfs-2.5.1-1.el7.x86_64

server side git version
# git --version
git version 1.8.3.1

using this rpm.
git-1.8.3.1-13.el7.x86_64

>Does the server software support Git LFS?
I have set it myself, but there is a possibility that it is not correct.

>Does the server have Git LFS turned on for this repository?
Is there any other way to confirm that?
Is something incomplete?

**Comment by ttaylorr** [comment]
Hi @yut148, thanks for answering all of @bk2204's good questions. I
think that I know what's going on here:

Git LFS works out-of-band with normal Git operations, so it requires an
implementation of the Git LFS API specification to be running alongside
your Git repository on the remote end.

In other words: cloning from a Git repository on another machine without
installing and running a Git LFS _server_ will not work.

Since 'git push' (without running 'git lfs install', hence avoiding the
.git/hooks/pre-push phase) only performs a Git operation, it should work
without a hitch, but only upload LFS pointers. OTOH, 'git lfs push' will
perform _only_ the Git LFS part, which will fail without a Git LFS
server to receive them.

There are a few open-source implementations listed in the Git LFS wiki,
and there is documentation in the 'docs' folder about how Git LFS
discovers where those servers live.

Can you confirm that you are/are not running a Git LFS server?

**Comment by yut148** [comment]
@ttaylorr. @bk2204 Thank you for answering.
There was an error in my understanding.
I have understood that I need to run Git LFS server.
I reread the Git LFS wiki again.
https://github.com/git-lfs/git-lfs/wiki/Implementations
I used the git LFS TEST server in this.

I noticed that there are several places to watch out for.

It was necessary to align user name and password with Apache's BASIC authentication and Git LFS Test server.
It was necessary to set lfs.url with git client.
Could not execute hook / post update.
This was due to permalition, and the file name was post-update.sample.
I was not running git update-server-info.
Various operations were lacking.

The following software worked correctly.
git LFS Test Server Linux.AMD64.gz
httpd-tools-2.4.6-80.el7.centos.x86_64.rpm
httpd-2.4.6-80.el7.centos.x86_64.rpm
git-lfs-2.5.1-1.el7.x86_64.rpm
git-1.8.3.1-13.el7.x86_64.rpm

There was no problem with git clone, git lfs push.

Thank you very much for giving me the answer.
I would like to close this issue.
