### ISSUE TITLE
lfs.customtransfer.<name>.args handled incorrectly

### ISSUE THREAD

**Issue by artiommorozov** [git-lfs/git-lfs#3249]
This arg is passed as a string at custom.go
```
type customAdapter struct {
	*adapterBase
	path                string
	args                string
```
but later it goes to 
```
	cmd := subprocess.ExecCommand(a.path, a.args)
```
that expected args to be list of strings
```
func ExecCommand(name string, arg ...string) *Cmd {
	cmd := exec.Command(name, arg...)
```

That leads to dilemma: if you specify all your args on a single line in .gitconfig, you end up with all args quoted into single one. If you specify multiple 'args' variables in .gitconfig it gets cut at adapter level down to last single argument.

To reproduce, 
```
[lfs "customtransfer.abc"]
	path = C:/Users/user/AppData/Local/Programs/Python/Python37-32/python.exe 
	args = C:/Users/user/test.py 
	args = aaa
	args = bbb
	concurrent = false

[lfs "your_url_here"]
        standalonetransferagent = abc
```

with test.py
```
import sys
print(sys.argv[1:])
```

expected output is ['aaa', 'bbb'] but in fact python is called with single 'bbb'. 

Win10/git 2.18/lfs 2.4.2

**Comment by bk2204** [comment]
Thanks for reporting this.  I can confirm that this is an issue and that python gets invoked only with a single "bbb" argument.

There are really two possible directions to go here: one of them is to pass arguments to the shell, which allows multiple arguments, or we can allow multiple args options.  My only concern about the latter is that it might work oddly when inheriting across multiple config files.

@PastelMobileSuit, @ttaylorr, do you have any thoughts on the best way forward?

**Comment by ttaylorr** [comment]
> Thanks for reporting this. I can confirm that this is an issue and
> that python gets invoked only with a single "bbb" argument.

Thanks for confirming!

> There are really two possible directions to go here: one of them is to
> pass arguments to the shell, which allows multiple arguments

I think that's an OK approach, though I'm not somewhat concerned about
this as a potential new surface area for a vulnerability.

We avoid using a repository's .lfsconfig for roughly this reason, but I
am still made somewhat uncomfortable by the possibility of taking
directly from git configuration and sending it to the shell (though
certainly this isn't our worst offender.)

> or we can allow multiple args options.  My only concern about the
> latter is that it might work oddly when inheriting across multiple
> config files.

I share this concern. I don't suspect that many folks are using
this combination of feature in practice, but if we can come up with
something that avoids the inheritance ordering problem entirely, then I
think that'd be a preferable solution to either of those two.

Once such approach I can think of using `tools.ShellQuote()` (which I
believe you worked on as recently as 69b534ec (tools: add function to
perform shell quoting, 2018-08-27)). I think that using this function
would allow us to use a single variable in Git configuration to provide
multiple arguments (and handle the quoting of all that in a sane way).

I believe that would allow us to write configuration that looks like:

  [lfs "customtransfer.abc"]
    path = /path/to/program
    args = foo bar baz

And get on the shell:

  $ /path/to/program foo bar baz

Instead of:

  $ /path/to/program "foo bar baz"

What do you think?

**Comment by bk2204** [comment]
Yeah, that might be a viable approach forward.  `tools.ShellQuote()` doesn't do shell splitting, but if we quote the program name and then concatenate the `args` value using a space, we can get away without actually having to do any splitting.

If we agree that's a good way forward, I'll try to pick this up and then document the fact that this is passed to the shell.

**Comment by ttaylorr** [comment]
> I'll try to pick this up and then document the fact that this is
> passed to the shell.

Sounds good. Definitely you have my +1 on this, so I'd be curious to
hear @PastelMobileSuit's thoughts as well.

Thanks for volunteering to work on it, too.

**Comment by PastelMobileSuit** [comment]
Just getting caught up on this now, that sounds like a reasonable approach to me! 👍
