### ISSUE TITLE
git push fails for lfs tracked files otherwise pushes git blobs

### ISSUE THREAD

**Issue by dpanshu** [git-lfs/git-lfs#3250]
I am trying to store large files using lfs but get the following error when trying to push changes in local directory to origin. It works if the files are not lfs tracked but fails once any file is tracked using "git lfs track "*.file"". 

WARNING: Authentication error: Authentication required: Authorization error: https://company.com/scm/~user/personalrepo.git/info/lfs/locks/verify
Check that you have proper access to the repository
Fatal error: nullects:   0% (0/1), 0 B | 0 B/s
Uploading LFS objects:   0% (0/1), 0 B | 0 B/s, done
error: failed to push some refs to 'ssh://git@company.com/~user/personalrepo.git'

**Comment by ttaylorr** [comment]
> This message means that the server side is producing a 401 or 403
> error when trying to push.

The 401 should be OK, since Git LFS tries first to send requests as
unauthenticated, and treats a 401 as the server saying "No, you do need
to authenticate this call."

> Can you tell us a little bit about the server-side software that's
> running, specifically what software and what version are in use?

Historically issues like this have also been sometimes related to an
issue with your local credential helper, so I would be interested also
in what credential helper you are using (or if you have any relevant
bits in your ~/.netrc file).

> Also, it may be useful to try to run the push with `GIT_TRACE=1` to
> see if that provides more information about what's going on.

Ditto. I saw that there is a "null" that snuck into the output of your
command, so I'm curious where that's coming from, too.

**Comment by ttaylorr** [comment]
Hi @dpanshu, I'm going to close this issue since it's been a little while since we've heard anything. If this was resolved, we'd be curious to hear how you did it (and if there's anything we can do to make the situation better on the LFS side of things.) Otherwise, if the issue reoccurs in the future, please don't hesitate to let us know. Thanks!
