### ISSUE TITLE
CRLF will be replaced by LF on Mac

### ISSUE THREAD

**Issue by tcamin** [git-lfs/git-lfs#3251]
Hi,

I'm experimenting with LFS and the its migration feature but and I'm having some issues. Suppose I want all files in a folder to be tracked except *.png. Let's also say I want to migrate the existing repo which is created as follow:

``` 
mkdir test
cd test
git init
git lfs install
mkdir lfsfolder
touch a
git add .; git commit -am "Commit"
git lfs migrate import --include='lfsfolder/**/*' --exclude='*.png' --everything --verbose
```

Now add any PNG file to `lfsfolder`, `git add .`  and you'll get

```
warning: CRLF will be replaced by LF in lfsfolder/image.png.
The file will have its original line endings in your working directory
``` 

The generated .gitattributes:

``` 
lfsfolder/**/* filter=lfs diff=lfs merge=lfs -text
*.png text -filter -merge -diff
```

I suspect the issue is related to *.png being set as text instead of binary, is there a way to avoid this during migration?

I'm on macOS 10.13, git 2.18.0, git-lfs 2.5.1

**Comment by ttaylorr** [comment]
Hi Tomas, thanks for writing and sharing the steps you took to encounter
the problem.

I suspect what is going on is the following: when 'git lfs migrate
import' receives the '--exclude' option, it generates a line in your
.gitattributes as follows:

  *.ext text -filter -merge -diff

This is to "restore" the LFS-style attributes line:

  *.ext filter=lfs diff=lfs merge=lfs -text

But, I don't think that setting `text` for `*.png`'s in that directory
is the right thing for Git LFS to be doing in your case, since any
binary data in a .png should _not_ be normalized according to Git's line
ending rules.

So, I think you want either one of two things. (1) Replace the line
`*.png text` with `*.png`, or (2) perform that replacement over affected
parts of history, with:

  $ git filter-branch --tag-filter=cat \
      --tree-filter='
        sed -i "" -e "s/\*.png text/\*.png/g" .gitattributes
      '
