### ISSUE TITLE
Proposal: teach 'git lfs checkout' --{theirs,ours,base}

### ISSUE THREAD

**Issue by ttaylorr** [git-lfs/git-lfs#3258]
From some discussion upstream in https://public-inbox.org/git/20180916075604.GB18517@gmail.com/, it was suggested that:

> Combining changes is inherently file-format specific, and I suspect
> that native authoring tools are best used in those scenarios.
> Maybe LFS can help deal with binary conflicts by having short and sweet
> ways to grab the "base", "their" and "our" versions of the conflict
> files.
> 
> Example:
> 
> 	git lfs checkout --theirs --to theirs.wav conflict.wav
> 	git lfs checkout --ours --to ours.wav conflict.wav
> 	git lfs checkout --base --to base.wav conflict.wav
> 
> Then the user can use {ours,theirs,base}.wav to produce the
> resolved result using their usual authoring tools.

##

/cc @git-lfs/core

**Comment by yayadviga** [comment]
17.09.2018, 16:42, "Taylor Blau" <notifications@github.com>:From some discussion upstream in https://public-inbox.org/git/20180916075604.GB18517@gmail.com/, it was suggested that:

Combining changes is inherently file-format specific, and I suspect
that native authoring tools are best used in those scenarios.
Maybe LFS can help deal with binary conflicts by having short and sweet
ways to grab the "base", "their" and "our" versions of the conflict
files.
Example:
git lfs checkout --theirs --to theirs.wav conflict.wav
git lfs checkout --ours --to ours.wav conflict.wav
git lfs checkout --base --to base.wav conflict.wav
Then the user can use {ours,theirs,base}.wav to produce the
resolved result using their usual authoring tools.


/cc @git-lfs/core

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or mute the thread.

-- С уважением, Yadviha Khrapavitskaya+375298522946ykhrap@ya.ru

**Comment by bk2204** [comment]
Yes, I agree that would be a good idea.  Let’s do it.
