### ISSUE TITLE
Programatically verify that there is no mixed state of files

### ISSUE THREAD

**Issue by skashyap7** [git-lfs/git-lfs#3263]
Hi, 
Does there exist a full proof way to determine if the file is an LFS tracked file?
Our repository had the  ".gitattributes" file in an inconsistent state where someone tracked *.xml files as LFS but never added them as LFS files to the repository. 
At the current moment, lfs-track enlists these XML files as LFS tracked. However, the git check-attr output differs from what ls-files indicate
git check-attr filter -- data/test.xml
data/test.xml: filter: set

I am looking for a way where I can validate /warn when repository enters in such a state. Please let me know if you need more details

**Comment by ttaylorr** [comment]
Hi Suman, thanks for writing in.

> I am looking for a way where I can validate /warn when repository
> enters in such a state. Please let me know if you need more details

This is an extremely common situation which we can unfortunately only do
so much to help prevent or notify when we get into this state.

This will often manifest as Git LFS complaining on a computer who has
installed it correctly that, upon pulling, a file that was expected to
be a Git LFS pointer is, in fact, a large file instead.

Since the key way that this problem is introduced is by _not_ having Git
LFS configured correctly, there's not a lot that the Git LFS client can
do by itself to detect these problems _before_ they are introduced.

Instead, we do have the command:

  $ git lfs migrate import --fixup --everything

Which will scan all of history, and re-apply the Git LFS filters as they
should have been according to the repository's .gitattributes file(s)
_at each discrete point in history_.

If that is helpful to you, please do run it from time to time. If
everything is as it should be, 'git lfs migrate import' should do no
rewriting.

I'm going to close this issue for now, but please let me know if you
have any other questions, and I (or anyone else on @git-lfs/core) would
be more than happy to help out. Thanks!
