### ISSUE TITLE
git-lfs breaks when pushing to a local file path

### ISSUE THREAD

**Issue by kballard** [git-lfs/git-lfs#3275]
With the `git-lfs` `pre-push` hook installed, trying to use `git push` to push to a local file path is completely broken. This is very annoying as `git push . HEAD:foo` is a very convenient way to update a local branch without checking it out.

```bash
> git push . master:master
Invalid remote name ".": Invalid remote name: "."
error: failed to push some refs to '.'
> git push --no-verify . master:master
Everything up-to-date
```

The expected behavior is that `git-lfs` would simply do nothing when pushing to a local path.

git-lfs/2.5.2 (GitHub; darwin amd64; go 1.11)

**Comment by bk2204** [comment]
I think we’re tracking this issue as #2164.  The reason we don’t currently special-case local paths is because we don’t want someone to do the following:

- Push to a local path without copying LFS files.
- Delete the directory they pushed from.
- Try to push the local path somewhere else and find that they're missing the LFS files.

For your particular case, I’d recommend using `git branch -f foo HEAD` instead of `git push . HEAD:foo`.  That will do what you want without the hassle of invoking the hook.

**Comment by kballard** [comment]
`git branch -f foo HEAD` will not do the same thing. It has the pretty significant downside of not checking for fast-forwards. `git push . HEAD:foo` is really useful specifically because it enforces that this is a fast-forward.
