### ISSUE TITLE
git lfs migrate import (Error in git)

### ISSUE THREAD

**Issue by zezba9000** [git-lfs/git-lfs#3281]
I have broken git lfs objects and can't fix them. Running command below is broken.

$ git lfs migrate import
migrate: override changes in your working copy? [Y/n] Y
migrate: changes in your working copy will be overridden ...
migrate: Fetching remote refs: ..., done
Error in git rev-list --stdin --reverse --topo-order --do-walk --: exit status 128 fatal: bad revision '^refs/remotes/tags/origin/v1.0'

Windows 10 x64
Git 2.19.0.windows.1
Git LFS 2.5.1

**Comment by ttaylorr** [comment]
Hi, Andrew -- thanks for writing in. In truth, I'm a little puzzled with
what to do here, and I'd love some feedback from @git-lfs/core on the
best way to go forward.

What's going on here is an complicated interaction between a few things:
(1) that we don't track the remote that a *git.Ref belongs to, (2) that
we hacked *git.Ref.Name to _include_ the remote name as a prefix, and
(3) that we then call `(*git.Ref) Refspec()` in order to get out a name
that we can then give back to 'git-rev-parse(1)'.

I think that a fix would look something like the following:

  - Teach getRemoteRefs() to return a map[string][]*git.Ref (i.e., a
    mapping from remote name to a slice of references belonging to that
    remote).

  - Teach formatRefName() to special case both types of remote
    references that Git LFS knows about (e.g., git.RefTypeRemoteBranch,
    and git.RefTypeRemoteTag).

  - Call formatRefName() on each reference in the return value from
    getRemoteRefs(), falling back to r.Refspec() when we're in a local
    reference.

  - Undo our hackery to prepend the remote name to the reference name.

But all of this said, here's my confusion: I can't find anywhere in the
modern Git codebase that creates a
refs/remotes/tags/<remotename>/<tagname> remote, _other_ than
'git-svn(1)', with --prefix prior to Git 2.0.0.

My understanding is that we should instead be treating remote "tag"
references as:

  refs/remotes/<remote>/tags/<tag>

Hence, we can remove _both_ git.RefTypeRemoteBranch and
git.RefTypeRemoteTag in favor of git.RefTypeRemote and call Refspec() on
that. Having removed the prefix "refs/remotes/", we'll be left with
"<remote>/tags/<tag>" which we can append to the aforementioned prefix
to get a round-trippable reference name.

Thoughts?

**Comment by bk2204** [comment]
I think that your proposed analysis and fix are spot on.  I wonder if wrapping the `map[string][]*git.Ref` in some sort of type alias or object would make working with the type a bit easier.

As for the reference name, I'm not sure it's safe to assume that something under `refs/remotes/<remote>/tags` is necessarily a tag.  Technically, `refs/remotes/<remote>` is for heads; tags don't have namespacing.  While I would say that it is probably a bad idea to create branches named `tags/foo`, sometimes people do things we don't expect, and I would suggest that we try to avoid making such assumptions if possible.

**Comment by ttaylorr** [comment]
> As for the reference name, I'm not sure it's safe to assume that
> something under `refs/remotes/<remote>/tags` is necessarily a tag.
> Technically, `refs/remotes/<remote>` is for heads; tags don't have
> namespacing.

Sounds good. For posterity's sake, we paired on this together, and the
resulting artifact is available at: https://github.com/git-lfs/git-lfs/pull/3285.
