### ISSUE TITLE
Pointer file error: Unable to parse pointer at: "xxx"

### ISSUE THREAD

**Issue by linjinze999** [git-lfs/git-lfs#3292]
## version
1. **git**: git version 2.10.1
2. **git-lfs**: git-lfs/2.5.1 (GitHub; linux amd64; go devel +bd98a81dc2 Thu Jul 26 17:13:12 2018 +0000; git e1628484)

## describe
When I clone a repository, I got some "Pointer file error". Then  I reset the git, some error file become successful. My repository has not been touched by someone who doesn't have LFS installed. Are these error bug?
ps: Not every repository has the problem. I operate the repository by git, no git-lfs.

## steps
1. get a repo : clone / checkout / reset ...  (some file error)
$ git checkout sp/master
Pointer file error: Unable to parse pointer at: "1.apk"
Pointer file error: Unable to parse pointer at: "2.apk"
Pointer file error: Unable to parse pointer at: "3.apk"
2. status: 
Git LFS objects not staged for commit:
	1.apk (Git: d4595d9 -> File: d4595d9)
	2.apk (Git: 6aba752 -> File: 6aba752)
	3.apk (Git: a577764 -> File: a577764)
3. reset : $ git reset --hard HEAD
4. status:   (some error file become successful)
Git LFS objects not staged for commit:
	2.apk (Git: 6aba752 -> File: 6aba752)

**Comment by ttaylorr** [comment]
Hi @JinzeLin, thanks for writing in.

> My repository has not been touched by someone who doesn't have LFS
> installed. Are these error bug?

Usually this type of problem is caused by a case wherein a cloner of the
repository who doesn't have Git LFS installed correctly commits a
non-LFS-ified version of a file, and causes the repository to become
corrupt.

But, since you say that it wasn't touched by someone who doesn't have
LFS installed, it's possible that there is something else going on.

Here's a few thoughts:

> Git LFS objects not staged for commit:

It was a good idea to run 'git lfs status', because that will give us a
better indication of which sides of each file (e.g., the index's and the
working copy's) are Git blobs, or Git blobs containing LFS pointers.

But, since you haven't staged any of the files (i.e., through 'git add
--all .', or similar), Git hasn't tried to clean any of your files to
see if they should be Git LFS-ified.

Can you please run the following and send back the output?

  $ git add --all .
  $ git lfs status

If you see any "LFS <sha1> -> Git <sha2>" (where <sha1> is equal to
<sha2>), that means that someone did commit a large object into the
repository on accident. You can fix this situation up with the
one-liner:

  $ git lfs migrate import --fixup --everything

Which will infer which files were supposed to be stored in Git LFS, but
weren't, and automatically apply the change.

**Comment by linjinze999** [comment]
Thanks! This issue can be closed.

$ git add --all .
$  git lfs status
On branch master
Git LFS objects to be pushed to origin/sp/master:


Git LFS objects to be committed:

	1so (Git: 02acc9b -> LFS: 02acc9b)
	2.so (Git: 62ad6c7 -> LFS: 62ad6c7)
	3.so (Git: 3404be1 -> LFS: 3404be1)
	4.so (Git: 6aba752 -> LFS: 6aba752)
	5.so (Git: a577764 -> LFS: a577764)

Git LFS objects not staged for commit:

**Comment by praveena2j** [comment]
Hello, I am getting this error while downloading a dataset from huggingface using git lfs. I did git add --all and git lfs status, this is my output 

Objects to be committed:
        LAVISHData (?: <missing>)
Objects not staged for commit:

Any help would be greatly appreciated

**Comment by bk2204** [comment]
Hey,

Instead of commenting on a closed issue, could you please open a new issue for this, filling out the issue template, including the output of `git lfs env`, a full output of any commands run, and any appropriate reproduction steps (including the repository URL)?  The issue you're seeing is different from the issue here because it's for a totally different version and I believe the behaviour has changed.

**Comment by praveena2j** [comment]
ok i am closing this issue
