### ISSUE TITLE
Percentage Completion

### ISSUE THREAD

**Issue by SammyHass** [git-lfs/git-lfs#3294]
Please can the percentage completion when pushing to LFS be based on the total file size of the upload as opposed to the total number of files. (Sorry, I recognise its nitpicking but it would be a great help)

Thanks.

**Comment by ttaylorr** [comment]
Hi Sammy, thanks for writing in.

> Please can the percentage completion when pushing to LFS be based on
> the total file size of the upload as opposed to the total number of
> files.

This is a similar request to that issued in:

  https://github.com/git-lfs/git-lfs/issues/3221

I had closed the aforementioned issue a little while ago, but since it
seems that there is more feedback, I've re-opened it, in the hopes that
we have this discussion there, instead.

> (Sorry, I recognise its nitpicking but it would be a great help)

You're not nitpicking (and even if you were, it would be welcome here).
I think that it's reflected in everyone on @git-lfs/core that we
certainly welcome any suggestion to make Git LFS easier to use.

Thank you again for taking the time to share your feedback.
