### ISSUE TITLE
git lfs push of large file fails with HTTP 401

### ISSUE THREAD

**Issue by mbbvn** [git-lfs/git-lfs#3339]
Git LFS push of a really large file of 2.8 GB fails with HTTP 401; git retries for 8 times and eventually gives up with i/o timeout.

```
i/o timeout
error: failed to push some refs to ............... 
```

Issue is pretty much as described in issue #2259 and issue #2753, except this is against a TFS Git repo.

Tried increasing `lfs.activitytimeout` to 600 (and also 6000) with no luck.

GIT LFS plugin v2.5.2. 

Enabling GIT_TRACE and GIT_CURL_VERBOSE shows HTTP 401 error along with HTTP 200. Can someone shed some light on this please?
[git-lfs.txt](https://github.com/git-lfs/git-lfs/files/2510327/git-lfs.txt)

**Comment by bk2204** [comment]
Hey, sorry to hear you're having trouble.  Let me take a look at what's going on.

First, the 401s you're seeing are normal.  Git doesn't send authentication unless it needs it, and you're using NTLM, which looks like it needs a multi-stage negotiation process (much like Kerberos); you'll get several back-and-forth messages with 401s until the authentication succeeds.

I don't know how TFS and VSTS are related; the fact that they're both now called Azure DevOps may indicate that they share code or implementation, or not.  It's possible that the issue you're seeing is indeed the same as #2259.  However, in order to find out, could you run with `GIT_TRACE`, `GIT_CURL_VERBOSE`, and also `GIT_TRANSFER_TRACE` at the same time?  Git LFS, not using libcurl, doesn't pay any attention to `GIT_CURL_VERBOSE`.

**Comment by bk2204** [comment]
This looks like an NTLM issue, and we no longer support NTLM, so I'm going to close this.
