### ISSUE TITLE
ERROR: EXCEEDS GITS LIMIT

### ISSUE THREAD

**Issue by markcagatandavis** [git-lfs/git-lfs#3342]
Hey Guys,

I have installed and configured Git LFS but for some reason when I push, I still get the error stating file is larger than 100MB.

`Hey Guys,

I have installed and configured Git LFS but for some reason when I push, I still get the error stating file is larger than 100MB.

Sir.Dominar@Sir_Dominar MINGW64 /c/github/nihon-no-shiai (master)
$ git lfs track "*.assets.resS"
Tracking "*.assets.resS"

Sir.Dominar@Sir_Dominar MINGW64 /c/github/nihon-no-shiai (master)
$ git add Library/PlayerDataCache/Win64/Data/sharedassets1.assets.resS

Sir.Dominar@Sir_Dominar MINGW64 /c/github/nihon-no-shiai (master)
$ git commit -m "Add design File"
[master 583953a] Add design File
 2 files changed, 2 insertions(+)
 rewrite Library/PlayerDataCache/Win64/Data/sharedassets1.assets.resS (99%)

Sir.Dominar@Sir_Dominar MINGW64 /c/github/nihon-no-shiai (master)
$ git push
Uploading LFS objects: 100% (8/8), 408 MB | 1.3 MB/s, done
Enumerating objects: 1425, done.
Counting objects: 100% (1425/1425), done.
Delta compression using up to 8 threads
Compressing objects: 100% (1231/1231), done.
Writing objects: 100% (1237/1237), 220.47 MiB | 1.19 MiB/s, done.
Total 1237 (delta 416), reused 0 (delta 0)
remote: Resolving deltas: 100% (416/416), completed with 84 local objects.
remote: error: GH001: Large files detected. You may want to try Git Large File Storage - https://git-lfs.github.com.
remote: error: Trace: b212b35706d8ff8585e90b1cc4bef43e
remote: error: See http://git.io/iEPt8g for more information.
remote: error: File Library/PlayerDataCache/Win64/Data/sharedassets1.assets.resS is 384.67 MB; this exceeds GitHub's file size limit of 100.00 MB
To https://github.com/markcagatandavis/Nihon-no-shiai.git
 ! [remote rejected] master -> master (pre-receive hook declined)
error: failed to push some refs to 'https://github.com/markcagatandavis/Nihon-no-shiai.git'

`

**Comment by markcagatandavis** [comment]
Unsure why LFS wasn't working on this repository. I ended up creating a new repository and applied LFS before adding files and all worked smoothly. I was reading and looks like this is a common issue, when adding LFS to a pre-existing repository for some reason.

**Comment by ttaylorr** [comment]
Hi @markcagatandavis, thanks for opening this up. I'm glad that you were able to get things working. In the future, if this comes up, you can run the:

```ShellSession
$ git lfs migrate import --include="*.ext"
```

command, which will import files in your Git history named `"*.ext"` into Git LFS. Installing Git LFS can confusingly be a two stage process: first run `git lfs install` once on your system (or once per repository), and _then_ take existing large history into Git LFS (in general required, if you have objects over 100 MB, or optional otherwise) via `git lfs migrate import`.

Please let us know if you have any other questions or run into problems; we'd be more than happy to help!
