### ISSUE TITLE
git-lfs has been correctly set up criteria

### ISSUE THREAD

**Issue by verbaloid** [git-lfs/git-lfs#3343]
What is a correct verification test (criteria/command) for making sure git-lfs is installed well?

**Comment by ttaylorr** [comment]
Hi @verbaloid, thanks for your question. There are a few components to making sure that Git LFS is installed correctly:

If you run:

    git config --list | grep lfs\.filter

You should be able to see something like the following:

```
filter.lfs.clean=git-lfs clean -- %f
filter.lfs.smudge=git-lfs smudge -- %f
filter.lfs.process=git-lfs filter-process
filter.lfs.required=true
```

And if you don't, you can run `git lfs install` (with `--skip-repo` when run outside your repository, or without that argument otherwise) to fix it.

Make sure also that you have run `git lfs install` within your repository to ensure that your `.git/hooks/pre-push` (etc.) have been updated to run Git LFS commands.

Finally, you can make sure that you don't have large objects lurking in your history by running `git lfs migrate info --everything`, and running `git lfs migrate import ...` over suspect extensions to fix them.
