### ISSUE TITLE
What are "locking support detected" messages for and is there a way to turn them off?

### ISSUE THREAD

**Issue by verbaloid** [git-lfs/git-lfs#3346]
To my understanding git-lfs has ability to lock/unlock files according to configuration set in .gitattributes file - "Git LFS will verify that you're not modifying a file locked by another user when pushing".
Suppose i am not interested (not setting "lockable" attribute in .gitattributes next to file extension) in this functionality. 
Shall me or any other user of current repository keep seeing these messages on every push?
Is there a way to turn mentioned messaging off?

Here is a full message text:

PS D:\Repos\xxxxx> git push
Locking support detected on remote "origin". Consider enabling it with:
  $ git config lfs.http://xxxxx/info/lfs.locksverify true
LFS: seek D:\Repos\xxxxx.git\lfs\objects\7b\ab\7bab116d550e9088cc27a1dcbdfebe551a94605e9b4b79b0a01527780ca2b954: file already closed

**Comment by bk2204** [comment]
Hey,

Your understanding is completely correct on what's going on.  I understand that these messages can be bothersome.  If you set the variable, either to `true` or `false`, then the messages will go away.  So if you're not planning on using locking, you can simply set the value to `false`, and you won't see the message anymore.

If you looked for an answer in the documentation, can you tell me where it is you looked?  I'd like to update the documentation to make things a bit clearer in the future.

**Comment by verbaloid** [comment]
Thank you. Mainly here https://github.com/git-lfs/git-lfs/wiki/File-Locking. 
Can you provide details like where, names, syntax?

**Comment by bk2204** [comment]
Sure.  The easiest way is to use `git config` to set it:

- `git config lfs.http://xxxxx/info/lfs.locksverify false` (on a per-repository basis)
- `git config --global lfs.http://xxxxx/info/lfs.locksverify false` (on a per-user basis)
- `git config --system lfs.http://xxxxx/info/lfs.locksverify false` (on a systemwide basis; may require administrator privileges)

You can also edit any of those files by hand, in which case it will look like the following:

```ini
[lfs "http://xxxxx/info/lfs"]
	locksverify = false
```

Since these are stored in the same way as other Git configuration, `git config --help` can tell you all about setting them and the files involved, should you want to set them by hand or just learn more.

**Comment by verbaloid** [comment]
Does "systemwide" mean machine wide? 
This current repository is a remote one - but repository based .git/config is not pushable.
So how do i configure this at once for all user distributed repositories?

**Comment by ttaylorr** [comment]
@verbaloid system-wide does mean that, and @bk2204's suggestion of using `--global` as an option to `git config` will instruct Git to remember that setting in _all_ repositories (unless overridden in a particular repository).

You can read more about that hierarchy here: https://git-scm.com/docs/git-config#FILES.

Since I think that your question is answered, I'm going to close this issue for now. If something else comes up or you have any other problems in the future, please let us know here (or in a new issue) and we'd be more than happy to help out. Thanks!
