### ISSUE TITLE
Problem with patterns

### ISSUE THREAD

**Issue by quicknir** [git-lfs/git-lfs#3348]
Hi, I'm running git-lfs 2.3.3 and git 2.17.1 (sorry for lack of full git lfs env output; it has some company information in it so I'd prefer not to paste unless necessary). I've run git lfs install. I'm trying to have all my output in certain directories tracked by git-lfs. I add a pattern and then commit .gitattributes, currently I have:

```
cat .gitattributes
foo/bar/** filter=lfs diff=lfs merge=lfs -text
```

Now, I want to add a file that lives in a directory in my repo (but is currently untracked, i.e. not committed yet): `foo/bar/baz/2018/10/11/blub.fmt`. I add this file and commit it, and immediately after run `git lfs ls-files`. This returns nothing, showing that `blub.fmt` is actually being tracked normally by git.

I've tried adding the simple pattern `*.fmt`, and verified that if I copy `blub.fmt` into the repo root directory and add it and commit it, then `git lfs ls-files` does in fact show that file. I've also tried creating a .gitignore file (since the patterns used are supposed to be mostly the same), and I copied the `foo/bar/**` pattern there. When I do that, all the files are ignored (stop showing up as untracked in git status) as expected, which indicates to me the pattern is correct.

Any idea what might be going wrong? I appreciate that 2.3.3 is not the latest version; is this some kind of bug that was fixed since?

**Comment by ttaylorr** [comment]
Hi @quicknir, thanks for opening this and I'm sorry to hear that you are having trouble. There could be a number of things going on here, so I think that we may have to do some digging to figure out what the culprit is in this particular case.

Just to double check: are you able to reproduce the issue on a isolated repository? I tried to do so myself, but was unable to replicate the issue:

```ShellSession
$ cat .gitattributes
foo/bar/** filter=lfs diff=lfs merge=lfs -text

$ git check-attr -a foo/bar/baz/2018/10/11/blub.fmt
foo/bar/baz/2018/10/11/blub.fmt: diff: lfs
foo/bar/baz/2018/10/11/blub.fmt: merge: lfs
foo/bar/baz/2018/10/11/blub.fmt: text: unset
foo/bar/baz/2018/10/11/blub.fmt: filter: lfs

$ git cat-file -p :foo/bar/baz/2018/10/11/blub.fmt
version https://git-lfs.github.com/spec/v1
oid sha256:b5bb9d8014a0f9b1d61e21e796d78dccdf1352f23cd32812f4850b878ae4944c
size 4
```

There are roughly three things that could be causing this to go awry:

1. You didn't run `git lfs install` correctly, or something else overwrote it. I mention this as it _is_ a possibility, but I don't think that this is likely to be what's going on in this case, since you mentioned that you ran it explicitly.

2. `blub.fmt` (in the subdirectory) is empty. A historical quirk of Git LFS is that empty files do _not_ resolve to pointers: instead the empty file's pointer _is_ the empty pointer. For another reason, these types of files do not show up in `git lfs ls-files` (for example, when in the above setup I overwrote the file to be empty, it no longer appeared when I ran `git lfs ls-files`).

3. Another `.gitattributes` file between the root directory and the location of the file `blub.fmt` is unsetting the Git LFS attributes. This can be done by writing a `.gitattributes` file as follows:

    ```
    foo/bar/** !filter !diff !merge text
    ```

So, if a file like that ☝️ exists between the root of the repository and the directory of the file in question, that could cause Git LFS to ignore it. You can verify that something like this might be going on by running `git check-attr -a /path/to/file` and seeing whether or not something containing `lfs` is mentioned.

**Comment by quicknir** [comment]
@ttaylorr I'm really sorry, this is totally my fault, I did something rather strange/stupid in using a symlink as my test file :-). It pointed to another file in the same directory; I didn't even notice. AFAICS git-lfs seems to ignore symlinks (which makes perfect sense). Thanks for your detailed reply and really hope it didn't take up too much of your time. Cheers!

**Comment by ttaylorr** [comment]
> Thanks for your detailed reply and really hope it didn't take up too much of your time. Cheers!

Of course, it's my pleasure to help out!
