### ISSUE TITLE
Can't push even after deleting large file

### ISSUE THREAD

**Issue by mk24934** [git-lfs/git-lfs#3352]
I tried adding a 2.3GB .csv file to a repository, however it was too large so I found I should try git-lfs.  However even having installed it and tracking it I receive the following error, which did not go away even when I deleted the .csv file:

```
Uploading LFS objects: 100% (52/52), 2.3 GB | 0 B/s, done                       
[3683a61ee197da0908dcff559b6931321e9de7d4bed7a3132c16a7d0bd0f0759] Size must be less than 2147483648: [422] Size must be less than 2147483648
```

So now I am unable to push this repository to Github.  I am new to Github, kindly let me know what information you would like me to provide.  I am on Mac using git version 2.19.0

**Comment by bk2204** [comment]
Hey, sorry you're having trouble.  This 422 message comes from the server side.  Currently, GitHub limits large files to 2 GiB, even with large file support.  There isn't currently a way around this limit, other than compressing the file.

We are aware of a desire to raise that limit, so if you'd like that, please feel free to reach out to support@github.com and let them know.  This project focuses on the open source command-line client instead of the server-side implementations.

**Comment by grantjtrainer** [comment]
How do you fix it? The title says "Can't push even after deleting large files".
