### ISSUE TITLE
use-case: git-lfs for photo collections

### ISSUE THREAD

**Issue by neogeek83** [git-lfs/git-lfs#3363]
I have a use case I am interested in using `git-lfs` for, and wanted to propose the use-case for begin the conversation if I should be trying to do this in `git-lfs` in the first place.  Let's say you put in charge of management the digital phones for a large family or group. Everyone has some photos on their phone, some on their computer downloaded from their SLR Camera, or  Facebook, or Instagram. Some of these photos have already been shared between members of the group, so you have a bunch of copies flowing around, likely renamed as they got shifted about. Okay, so that's the situation... Now the goals for what i mean by management:
 
- De-Duplication so you only have a single copy of each photo
- Easy importing from each member in a logical way that gives source attribution 
- Each member can maintain their own organizational structure (some people like folders by activity, some like by date first, some like a folder with both in name, etc)
- Easy sync'ing of photos that allows for editing

Possible way to implement in `git-lfs`:
- each family member has their own git branch for their copy of the collection
- a server hosts the git bare repo and lfs back end
- PR are used to 'sync' someone else's photos for download (however if they had a different directory structure, this might be problematic to convert, e.g. John has: My Pictures\2017.12_Christmas\blah but Nancy likes: My Pictures\2017\December\Christmas\blah. Is there anyway to have standard transforms when merging between branches? 
- Some data within a file constantly changed by the main pictures are not( rotation info, face tagging, location info, and other metadata), it would be ideal to separate that data out when saving so each branch could have their own metadata for a single image, but then choose to merge someone else's updates if they desire (file renames, rotations, tagging, etc)

So, that's my idea, am I onto something or barking up the wrong tree? Any ideas for how I should go about implementing this -- specifically the transforms in FS structure and metadata extraction from the files?

**Comment by bk2204** [comment]
Hey, thanks for an interesting question.  What you want to do is possible, although there are some potential sharp edges.  Here are some thoughts I have:

- Git LFS, like core Git, provides de-duplication when data is stored in the repository by labeling it with a cryptographic hash (Git LFS with SHA-256, and Git with SHA-1).  It's still possible to have multiple versions of a file on disk, and you'd have to have some way of dealing with that.
- Git LFS, like core Git and many other tools, works best when people agree on how files are to be laid out.  It's possible to fix up mislabeled directories with `git mv`, but there isn't a way to do this automatically on merge (you can, of course, manually do an [evil merge](https://git-scm.com/docs/gitglossary#gitglossary-aiddefevilmergeaevilmerge)).
- You could theoretically export EXIF data into a plain text file that lives beside the images and reimport it, but because Git and Git LFS don't merge binary files, there isn't a way to automatically merge the images, so you'll just get a conflict.

So my recommendation is that if you're going to be mostly with technical folks who can keep files unmodified and honor a consistent directory structure, you'll be okay, but if you have people who are modifying the images themselves, you're going to be unhappy.  In my experience, Git and Git LFS are hard to use for nontechnical folk (which is a shame, because I think there are a lot of places they could be useful) and trying to train them to work within the limitations of the tools may be frustrating for all involved.

I hope that was helpful, if maybe not the answer you were expecting.
