### ISSUE TITLE
Adding 150mb CSV file

### ISSUE THREAD

**Issue by medavidcook** [git-lfs/git-lfs#3371]
Hello,

I am trying to add a 150mb csv dataset to a repo I have.

I have installed the lfs but after tracking and committing it shows nothing but when I push I get 

$ git push
Enumerating objects: 21, done.
Counting objects: 100% (21/21), done.
Delta compression using up to 8 threads
Compressing objects: 100% (13/13), done.
Writing objects: 100% (17/17), 23.47 MiB | 1.06 MiB/s, done.
Total 17 (delta 8), reused 0 (delta 0)
remote: Resolving deltas: 100% (8/8), completed with 3 local objects.
remote: error: GH001: Large files detected. You may want to try Git Large File Storage - https://git-lfs.github.com.
remote: error: Trace: 3668122de691be0280d4aca70a6e8770
remote: error: See http://git.io/iEPt8g for more information.
remote: error: File Git_Projects/PyData-Book/datasets/fec/P00000001-ALL.csv is 150.56 MB; this exceeds GitHub's file size limit of 100.00 MB

Any ideas?

**Comment by bk2204** [comment]
Hey, sorry to hear you're having trouble.

In order to upload your repository, you'll need to migrate the history to use Git LFS.  The easiest way to do that is to run `git lfs migrate import --include="*.csv"` (or whatever format you're using for CSV files).  That will rewrite your history to make all CSV files handled by Git LFS, and then you can push to GitHub.  If you want to handle multiple types of files, you can use something like `git lfs migrate import --include="*.csv,*.tsv"`.

**Comment by ttaylorr** [comment]
Hi @medavidcook, I am also sorry that you are having issues pushing to GitHub using Git LFS. I think that @bk2204's advice above is good, and you can learn more about this behavior in [this](https://github.com/git-lfs/git-lfs#example-usage) section of our README.

Since I am fairly confident that the above will resolve your situation, I am going to close this issue for now, but please do not hesitate to ping us here if you are unable to get this resolved, or have any other problems in the future. Thanks!

**Comment by medavidcook** [comment]
Ok, thank you.

**Comment by HabibRh26** [comment]
it worked for me at last,tried a lot but couldnt figure out why it is denying to push the csv dataset file to repo though i tracked the csv file.thanks a lot @bk2204

**Comment by raposofrct** [comment]
> Hey, sorry to hear you're having trouble.
> 
> In order to upload your repository, you'll need to migrate the history to use Git LFS. The easiest way to do that is to run `git lfs migrate import --include="*.csv"` (or whatever format you're using for CSV files). That will rewrite your history to make all CSV files handled by Git LFS, and then you can push to GitHub. If you want to handle multiple types of files, you can use something like `git lfs migrate import --include="*.csv,*.tsv"`.

Thanks so much, it worked!
