### ISSUE TITLE
should .dat file be tracked by LFS?

### ISSUE THREAD

**Issue by sunzhaolin** [git-lfs/git-lfs#3388]
if we have some .dat files in LFS store and some are not in our Git repo. how to sync up them to all LFS tracked?

**Comment by bk2204** [comment]
Hey, thanks for writing in.

I'm not quite sure I understand what you're asking.  It sounds to me like that you have some files in your LFS store that aren't in the Git repo and this is a concern.  That's a normal case; sometimes older versions of a file can end up in the LFS store if a branch is force-pushed.  You can ask the person hosting your server to clean them up for you; in some cases, they may be pruned on their own.

It's also possible that your store is something like Artifactory, which hosts both LFS and non-LFS objects and some of those objects are not in your repository when you want them to be.  If you want to add those files to your repository, you'd copy them to the place in your working tree where you want them stored and then run `git add` as normal, which should add them as LFS files.

I hope this answers your question.

**Comment by ttaylorr** [comment]
> I wonder how to clean up them. at least make them consistent either all in LFS store or all not.

Hi @sunzhaolin, I think that you can totally accomplish this within your `.gitattributes` file, if you're still wondering about a resolution here.

You can indicate that any pattern over filepaths can be _negated_, like so:

```
*.dat filter=lfs diff=lfs merge=lfs -tex
foo.dat !filter !diff !merge text
```

Where the `*.dat` lines _sets_ the `filter`, `diff`, and `merge` options instructing Git LFS to take over. Likewise, the `foo.dat` line _unsets_ `filter`, `diff`, and `merge`; Git LFS will henceforth ignore these entries, and you should be all set!

Since I think that this should work well, I am going to close this issue for now, but please do let us know here if it doesn't, and we'd be happy to dig in further! Thanks.
