### ISSUE TITLE
Finding the right way to relocate LFS storage dir

### ISSUE THREAD

**Issue by daelomin** [git-lfs/git-lfs#3393]
Finding the right way to relocate LFS storage dir has been an issue for us.

We installed git-lfs but we do not want to store the large files into .git/lfs

I've tried going through the documentation and it seems I can do "lfs.storage" to relocate it. Then git lfs env returns an "LfsStorageDir" variable, so I'm confused.  I tried both and tried to exit the local repo by doing either : 
- storage = "../../LFS"
or storage = "/tmp/LFS"

Each time, I get the same message: 
```


WARNING: These unsafe lfsconfig keys were ignored:

  lfs.storage
  lfs.lfsstoragedir
```

Any pointers on how to achieve what I'm trying to do?

Thanks

ps : FYI my git lfs env:

``
 [root@METOCNOMADE04 install_steps]# git lfs env
git-lfs/2.6.0 (GitHub; linux amd64; go 1.11.1; git 93702d75)
git version 2.18.0

WARNING: These unsafe lfsconfig keys were ignored:

  lfs.storage
  lfs.lfsstoragedir
Endpoint=https://gitlab.mfi.local/METOC/installer_METOC.git/info/lfs (auth=none)
  SSH=git@gitlab.mfi.local:METOC/installer_METOC.git
LocalWorkingDir=/home/install/RM/install_steps
LocalGitDir=/home/install/RM/install_steps/.git
LocalGitStorageDir=/home/install/RM/install_steps/.git
LocalMediaDir=/home/install/RM/install_steps/.git/lfs/objects
LocalReferenceDirs=
TempDir=/home/install/RM/install_steps/.git/lfs/tmp
ConcurrentTransfers=3
TusTransfers=false
BasicTransfersOnly=false
SkipDownloadErrors=false
FetchRecentAlways=false
FetchRecentRefsDays=7
FetchRecentCommitsDays=0
FetchRecentRefsIncludeRemotes=true
PruneOffsetDays=3
PruneVerifyRemoteAlways=false
PruneRemoteName=origin
LfsStorageDir=/home/install/RM/install_steps/.git/lfs
AccessDownload=none
AccessUpload=none
DownloadTransfers=basic
UploadTransfers=basic
GIT_EXEC_PATH=/usr/libexec/git-core
git config filter.lfs.process = "git-lfs filter-process"
git config filter.lfs.smudge = "git-lfs smudge -- %f"

``

**Comment by bk2204** [comment]
Hey, sorry to hear you're having trouble with this.

I think the issue you're having is that you're trying to place this setting in the `.lfsconfig` file in the repository.  That file allows only a certain number of keys to be specified for security reasons.  For example, we don't allow `lfs.storage` to be set there, since an attacker with a malicious repository could overwrite files on your system when the repository is cloned by using that value.

You can, however, set this option in any Git config file, either by using `git config` (e.g. `git config lfs.storage /tmp/LFS`) or by editing the files directly.  I'll try to update the documentation so this is a bit clearer, since I've noticed that other people have been confused as well.

**Comment by Thaodan** [comment]
> Hey, sorry to hear you're having trouble with this.
> 
> I think the issue you're having is that you're trying to place this setting in the `.lfsconfig` file in the repository. That file allows only a certain number of keys to be specified for security reasons. For example, we don't allow `lfs.storage` to be set there, since an attacker with a malicious repository could overwrite files on your system when the repository is cloned by using that value.
> 
> You can, however, set this option in any Git config file, either by using `git config` (e.g. `git config lfs.storage /tmp/LFS`) or by editing the files directly. I'll try to update the documentation so this is a bit clearer, since I've noticed that other people have been confused as well.

Which file? I tried ~/.gitconfig $repo_dir/.git/config all are ignored.

**Comment by Thaodan** [comment]
I cloned a local directory with --shared that didn't use the proper `LocalReferenceDirs` for the local bare I cloned, the lfs storage dir would be here `/var/lib/gitea/data/lfs`. 

All in all using git lfs locally is pain.

**Comment by bk2204** [comment]
Hey,

The `lfs.storage` path has to contain data in a particular format.  It's likely that Gitea's internal LFS storage doesn't use the same format and thus using it as `lfs.storage` won't work.  We've had people trying to do the same thing with GitLab's storage, which doesn't work, either.

You'll probably want to do a normal clone from Gitea using HTTPS or SSH instead, which should work properly.

As mentioned in the contributing documentation, please open a new discussion here instead of commenting on closed issues, and we'll try to help.  If you do that, please include the structure of `/var/lib/gitea/data/lfs` (for example, where a specific object is located under that path) so we can advise as to whether that will work in this situation.

**Comment by Thaodan** [comment]
> Hey,
> 
> The `lfs.storage` path has to contain data in a particular format.  It's
> likely that Gitea's internal LFS storage doesn't use the same format and
> thus using it as `lfs.storage` won't work.  We've had people trying to do
> the same thing with GitLab's storage, which doesn't work, either.

At least from inspecting the directory structure it looked very similar.

> You'll probably want to do a normal clone from Gitea using HTTPS or SSH
> instead, which should work properly.

That would require a round trip from the same host over the same network only 
resulting in duplicated data usage, very inefficient.

> As mentioned in the contributing documentation, please open a new discussion
> here instead of commenting on closed issues, and we'll try to help.  If you
> do that, please include the structure of `/var/lib/gitea/data/lfs` (for
> example, where a specific object is located under that path) so we can
> advise as to whether that will work in this situation.

I already opened another issue under #5100, I commented on this issue since at 
least partially it is related to the original issue.
Opening another issue for each related bug doesn't seem quite right.

I can comment on the bug I created for anything else.
