### ISSUE TITLE
Remote "origin" does not support the LFS locking API. Consider disabling it with:

### ISSUE THREAD

**Issue by SBee** [git-lfs/git-lfs#3400]

**Comment by SBee** [comment]
hello having issues pushing a few larger files with lfs. 

I have it installed correctly, i can confirm it is tracking the files i would like it to.
Every time I try a push, I get these errors:

Remote "origin" does not support the LFS locking API. Consider disabling it with: 

I use the suggested command to disable, and try to push again, same error - along with this one:

Uploading LFS objects:   0% (0/15), 0 B | 0 B/s, done                                                                         
batch response: Post https://github.com/SBee/TotalForcePC_LFS_test.git/info/lfs/objects/batch: x509: certificate signed by unknown authority

really not sure what to try next - Thanks for your help!

**Comment by bk2204** [comment]
Hey, sorry to hear you're having trouble.

Are you perhaps using Linux, and if so, do you have your distribution's `ca-certificates` package installed?  The certificate failure generally means that either the root CA certificates are not installed for your system or you're in a corporate environment with its own root CA that man-in-the-middles your connections, and that certificate isn't installed.

**Comment by SBee** [comment]
Thank you for the quick reply! (yes Unix)  I think you are right about the CA certificate issue. I believe there is a man-in-the-middle issue. 

Here is my output:

credential.helper=osxkeychain
filter.lfs.clean=git-lfs clean -- %f
filter.lfs.smudge=git-lfs smudge -- %f
filter.lfs.process=git-lfs filter-process
filter.lfs.required=true
user.name=SBee
credential.helper=osxkeychain
core.repositoryformatversion=0
core.filemode=true
core.bare=false
core.logallrefupdates=true
core.ignorecase=true
core.precomposeunicode=true
submodule.active=.
remote.origin.url=https://github.com/SBee/TotalForcePC_LFS_test.git
remote.origin.fetch=+refs/heads/*:refs/remotes/origin/*
branch.master.remote=origin
branch.master.merge=refs/heads/master
lfs.https://github.com/SBee/TotalForcePC_LFS_test.git/info/lfs.locksverify=false
lfs.https://github.com/SBee/TotalForcePC_LFS_test.git/info/lfs.access=basic
http.sslverify=false

Thank you again!

**Comment by bk2204** [comment]
Since GitHub does indeed support the lock verification API, the lock verification error should go away once you're able to push to GitHub.  I notice you're using `http.sslverify=false`.  Does that resolve your push problems?

If not, since it looks like you're using macOS, you'll need to add the MITM root certificate to the OS X Keychain, if it's not already there.  That should address the issue you're seeing with certificate validation.

**Comment by Zinenda** [comment]
Im using Windows and facing same problem

**Comment by bk2204** [comment]
Generally, adding the MITM root certificate to the system certificate store is the way to go here, since Go uses that certificate store when resolving certificates. Alternatively, you can set `http.sslverify` to `false` and that should ignore the problem, but note that this creates a large security hole. The latter should work because we do use it in the tests.

**Comment by phillipjohnston** [comment]
This just started happening to me out of the blue. How do we get the certificate?

**Comment by phillipjohnston** [comment]
I also cannot clone LFS repositories. Is that related to the certificate?

On clone:

```
08:37:48 ea$ git clone git@github.com:embeddedartistry/libc.git
Cloning into 'libc'...
remote: Enumerating objects: 188, done.
remote: Counting objects: 100% (188/188), done.
remote: Compressing objects: 100% (118/118), done.
remote: Total 2316 (delta 97), reused 143 (delta 70), pack-reused 2128
Receiving objects: 100% (2316/2316), 482.87 KiB | 3.09 MiB/s, done.
Resolving deltas: 100% (1449/1449), done.
Downloading docs/software_inventory.xlsx (11 KB)
Error downloading object: docs/software_inventory.xlsx (f2502de): Smudge error: Error downloading docs/software_inventory.xlsx (f2502de842ce8b3d9837d4b97861f70a6ceba9f1023470e49862dccc9dcab462): batch response: Client error: https://lfs.github.com/embeddedartistry/libc/objects/batch

Errors logged to /Users/pjohnston/src/ea/libc/.git/lfs/logs/20190701T083804.055429.log
Use `git lfs logs last` to view the log.
error: external filter 'git-lfs filter-process' failed
fatal: docs/software_inventory.xlsx: smudge filter lfs failed
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry the checkout with 'git checkout -f HEAD'
```

**Comment by dmartin-isp** [comment]
This just started happening to me out of the blue as well.  I tried http.sslverify=false and it didn't help.  Co worker is able to push changes, no problem.  He's on a Mac.  I'm on ubuntu 18.04.  Other affected folks, are you on Ubuntu?

**Comment by twpayne** [comment]
It's just started happening to me. I'm also on Ubuntu 18.04.2 LTS.

**Comment by alexlongshaw** [comment]
Happend to me too on 18.04. I pulled the latest updates and restarted which resolved the issue for me.

**Comment by VLukianenko** [comment]
This started to happen to me too on Windows 10, but then (without doing anything) it stopped happening after half an hour or so.

**Comment by bk2204** [comment]
Hi, folks. If you're just starting to see this when connecting to GitHub, that's a GitHub issue that was just resolved.

**Comment by bruno-harvey** [comment]
Hey @bk2204, is there post-mortem on that or a github issue? I'd like to read more about it if I could

**Comment by bk2204** [comment]
@bruno-harvey There is an internal one, but not one that we have publicly at the moment.

**Comment by agiridharan** [comment]
This just started happening for me on a Windows 10 machine

**Comment by ttaylorr** [comment]
> This just started happening for me on a Windows 10 machine

Can you clarify if you are pushing to GitHub or not? If not, please
reach out to your Git host. If you are, please send an email to
support@github.com.

**Comment by companytest1206** [comment]
Hello got the same error on windows 10 when I was trying to push larger file on got using lfs .I had also download and install lfs and follow all the step as mention on documentation.

Remote "origin" does not support the LFS locking API. Consider disabling it with:
  $ git config lfs.https://github.com/******.git/info/lfs.locksverify false

is anyone got a solution about this error?

**Comment by sofyanlabs** [comment]
> Hello got the same error on windows 10 when I was trying to push larger file on github using lfs .I had also download and install lfs and follow all the step as mention on documentation.
> 
> Remote "origin" does not support the LFS locking API. Consider disabling it with:
> $ git config lfs.https://github.com/******.git/info/lfs.locksverify false
> 
> is anyone got a solution about this error?

same here, how to fix this error

**Comment by bk2204** [comment]
Hi, folks. If you're _unable to push_ and seeing this error, please see @ttaylorr's response here: https://github.com/git-lfs/git-lfs/issues/3400#issuecomment-510141360. That's the best way for you to get help to solve the problem. This is not a client issue and there's nothing we can do to help you fix it.

If you're _able to push_, but you're seeing this error anyway, please follow the directions in the message to make it go away.

**Comment by dbrwn** [comment]
For what it's worth, I was having this same issue as many people above are reporting.
I found that the url-specific locksverify setting did not resolve my issue.  But as mentioned [here](https://github.com/desktop/desktop/issues/2812#issuecomment-332239726), I was able to use `git config lfs.locksverify false` to proceed and have the local commit successfully push to origin.

My setup was:
Windows 10, GitKraken client, pushing lfs files to a private github.com repo I am an administrator on.

**Comment by admacdon** [comment]
> For what it's worth, I was having this same issue as many people above are reporting.
> I found that the url-specific locksverify setting did not resolve my issue. But as mentioned [here](https://github.com/desktop/desktop/issues/2812#issuecomment-332239726), I was able to use `git config lfs.locksverify false` to proceed and have the local commit successfully push to origin.
> 
> My setup was:
> Windows 10, GitKraken client, pushing lfs files to a private github.com repo I am an administrator on.

This worked for me! thanks

**Comment by nvirth** [comment]
> 
> 
> I am on Windows, this issue to me is simply because I was not using the latest version of Git.

Was the case for me too. After upgrading to git 2.24.1, the issue disappeared

**Comment by WatchaGames** [comment]
Installed 2.25 problem disapearded.

**Comment by dhicks** [comment]
I'm getting this with git 2.25.1 and git-lfs 2.10.0, both freshly installed using homebrew.  This is the first time I'm using LFS, so I'm open to the possibility that I did something wrong with the installation.

**Comment by bk2204** [comment]
Hi, folks.

I'm going to close this issue, since the original reporter hasn't come back to report an ongoing problem.  This message by and large does not itself indicate a problem; it does not intrinsically mean that anything is wrong.

To quote my previous comment: 

> Hi, folks. If you're _unable to push_ and seeing this error, please see @ttaylorr's response here: [#3400 (comment)](https://github.com/git-lfs/git-lfs/issues/3400#issuecomment-510141360). That's the best way for you to get help to solve the problem. This is not a client issue and there's nothing we can do to help you fix it.
> 
> If you're _able to push_, but you're seeing this error anyway, please follow the directions in the message to make it go away.

If, _after doing all of that_ (including contacting your host if you can't push), you're still having problems, please open a new issue.  Please don't continue to post on this issue.

**Comment by abobakrd** [comment]
Resolved this issue on Git on Windows 10 by starting the ssh-agent in powershell first before pushing, like so: `start-ssh-agent`. Type in your SSH password, then push and it should work.

**Comment by tfgstudios** [comment]
> 

yes.

**Comment by tfgstudios** [comment]
> Resolved this issue on Git on Windows 10 by starting the ssh-agent in powershell first before pushing, like so: `start-ssh-agent`. Type in your SSH password, then push and it should work.

yes.

**Comment by Shoab02** [comment]
> Resolved this issue on Git on Windows 10 by starting the ssh-agent in powershell first before pushing, like so: `start-ssh-agent`. Type in your SSH password, then push and it should work.

This works on windows 10. Thank you

**Comment by uberflut** [comment]
Git 2.36.0 on Windows 10. Just happened this and as some commets before said as quickly as it came, it's gone.

**Comment by axkibe** [comment]
I just had a related issue, out of some reason unknown to me, git-lfs-authenticate running from Ubuntu added a '/' to the repository to authenticate against. "/myrepo.git" instead of "myrepo.git" (as I was used to (tested from Debian). Was easily fixable on serverside to ignore a leading '/', but no idea why the client differs here.

**Comment by axkibe** [comment]
Thanks for explaining the issue, one other minor note tough, git-lfs-authenticate denying the user (because in this case of misunderstood repository) should IMO not report as "does not support the LFS locking API error". 

I know on the calling API there aren't error codes like when in HTTP world.. still the message is a bit misleading (as my software does support, it only denied the user because of the /)

**Comment by bk2204** [comment]
I'm pretty sure that the error is in fact followed by a different error that tells you what the problem is.  However, the error you see first is in fact that the server doesn't support the locking API because the locking API failed.  We can't distinguish between "it failed because you're not authenticated" and "it failed because the server doesn't support the API", since those pretty much look identical.

However, I am going to lock this issue because I've already asked above that people not post on this closed issue, and that's also documented in the contributing documentation.  If folks continue to have problems, please open a new issue as directed.
