### ISSUE TITLE
How to call git-lfs api in C++?

### ISSUE THREAD

**Issue by TerryChan** [git-lfs/git-lfs#3404]
I want to write a Git tool to support git-lfs with C++, but I didn't find the api of git-lfs for C++. Is there any guidline to integrate git-lfs in C++?

**Comment by bk2204** [comment]
Git LFS is written in Go as a binary, so it doesn't have an API in C++ (or really, in any other language, including Go).  You can call out to the binaries much like you'd call out to a Git binary from your program or library, which might work for your needs.  If you have a C++ library which calls out to Git (as opposed to using libgit2), it can probably also be leveraged to invoke the `git lfs` commands.

Hopefully this is useful, if not the answer you were hoping for.

**Comment by TerryChan** [comment]
Thanks for your reply, it's useful.
But i still have another question, if I use the command line solution, does that mens I also need to contain golang to my installation package, and install golang on user's machine? So that the git lfs command can work , right?

**Comment by bk2204** [comment]
You can choose to distribute Git LFS as source code, in which case you'd need to compile it with Go (and have some Go runtime available to build it), or you could distribute it as a binary, in which case it shouldn't require any dependencies.  Git LFS should be a static binary on Linux and Windows and require only libSystem on macOS.

We provide binaries from our releases pages which you can distribute, and which on Windows are signed, if you would like to use those instead of building your own.
