### ISSUE TITLE
version https://git-lfs.github.com/spec/v1

### ISSUE THREAD

**Issue by YUFENGZHANG** [git-lfs/git-lfs#3408]
hello,I have meeting the follow problem,what should I do. Thank you!

Downloading android/arm64-v8a/lib/liba.so (996 KB)
Error downloading object: android/arm64-v8a/lib/liba.so (e9ea38b): Smudge error: Error downloading android/arm64-v8a/lib/liba.so (e9ea38b6120e75f0e1d57c98dda3190fe85fa899530102f5f1bcb353b148cbae): batch response: Access forbidden. Check your access level.

Errors logged to /Users/a/.git/lfs/logs/20181204T092218.974399105.log
Use `git lfs logs last` to view the log.
error: external filter git-lfs smudge -- %f failed 2
error: external filter git-lfs smudge -- %f failed
fatal: android/arm64-v8a/lib/liba.so: smudge filter lfs failed

**Comment by bk2204** [comment]
Hey, sorry to hear you're having trouble.

The error message that comes from "batch response" is from the server.  From the message, it looks like you're using a GitLab instance, and this message usually indicates that Git LFS isn't enabled on the server side, or there's a permissions problem.  If this is your repository, you'll probably want to ensure Git LFS is enabled in the settings; otherwise, you'll want to contact the owner of the repository or instance and ask them why this error is occurring.

**Comment by luoxz-ai** [comment]
batch response: This repository is over its data quota. Account responsible for LFS bandwidth should purchase more data packs to restore access.
error: failed to fetch some objects from 'https://github.com/******.git/info/lfs'

**Comment by bk2204** [comment]
Hey,

As mentioned, you'll want to talk to GitHub about anything that says, “batch response”.  In this case, that means that you've used your data quota and need to purchase more.  You can read the documentation at docs.github.com.

**Comment by luoxz-ai** [comment]
Other people's repositories , can I fork the lfs in the repositories ??

**Comment by bk2204** [comment]
Hey,

If you have questions about GitHub or its support for LFS, please either see the documentation or contact GitHub Support.  This repository is only for the open source Git LFS client, not for any server implementations.

**Comment by luoxz-ai** [comment]
that means that you've used your data quota and need to purchase more. Other people's repositories.

**Comment by luoxz-ai** [comment]
fork other people's repositories of lfs.

**Comment by luoxz-ai** [comment]
fork other people's repositories of lfs.
