### ISSUE TITLE
git lfs status wrong on OSX

### ISSUE THREAD

**Issue by sambonfire** [git-lfs/git-lfs#3412]
I've tested this in the same repository on both OSX and Windows and this only happens in OSX.  Maybe someone can just explain what's going on?

Starting off in a clean branch:

```
$ git lfs status
On branch master
Git LFS objects to be pushed to origin/master:


Git LFS objects to be committed:


Git LFS objects not staged for commit:


```

And git status is clean:

```
$ git status
On branch master
Your branch is up to date with 'origin/master'.

nothing to commit, working tree clean
```

Next, lock a file in the repo:

```
$ git lfs lock XXX.bin
Locked XXX.bin
```

List locks; they look valid:

```
$ git lfs locks
XXX.bin	Jojo McCreedy	ID:5b130448c9641f8f1ae297c66c8480093db6effa03d5e623528e9f6d94e8dd22
```

Next, git lfs status:

```
$ git lfs status
On branch master
Git LFS objects to be pushed to origin/master:


Git LFS objects to be committed:


Git LFS objects not staged for commit:

	XXX.bin (LFS: a37f200 -> File: a37f200)
```

I'm not sure why it shows that the LFS object has changed?  Can anyone explain this?

Then, the weird thing: if I run 'git status' and then 'git lfs status' again, the difference disappears:

```
$ git status
On branch master
Your branch is up to date with 'origin/master'.

nothing to commit, working tree clean
$ git lfs status
On branch master
Git LFS objects to be pushed to origin/master:


Git LFS objects to be committed:


Git LFS objects not staged for commit:


```

Again; this only seems to happen on OSX; I tested the same steps/repo on a windows box and it's fine.

Version info:
```
$ git version
git version 2.19.2
$ git lfs version
git-lfs/2.6.1 (GitHub; darwin amd64; go 1.11.2)
```

**Comment by bk2204** [comment]
Hey, thanks for writing in.  This is a really interesting bug you've discovered.

When we lock a file in this case, we change the permission bits. In doing so, we make the index entry stale, so when we perform a `git diff-index -M` against HEAD, we determine that the file has changed. We misinterpret that change as a file staged for commit, but it's not.  Running `git status` refreshes the index, so the output goes away. This probably doesn't happen on Windows because the index likely doesn't contain Unix permissions there, whereas it does on a Unix system.

I'll mark it accordingly and we'll see if we can get it fixed.
