### ISSUE TITLE
Git LFS file suddenly missing: HTTP 404 error

### ISSUE THREAD

**Issue by HarjyotKaur** [git-lfs/git-lfs#3419]
Hi,

The link for a data file (.txt) stored on GitHub using large file storage was visible until yesterday.

Today, when I opened my repo to the "View Raw" link gave me a HTTP 404 error. 
I pushed the file again, with a different name, but still now able to view file.

Any idea, what the issue might be?

**Comment by bk2204** [comment]
Hey, sorry to hear that this wasn't working for you.

This was due to an issue on the GitHub server side that's been fixed. Just for future reference, if you have a problem with the GitHub server side, it's better to reach out to support@github.com, since they'll be able to help you more effectively with getting those issues fixed. We only handle the client side in this repository and may not be able to help as quickly or effectively with server-side issues.
