### ISSUE TITLE
Image files fail to render on github's online interface

### ISSUE THREAD

**Issue by DavidRitzwoller** [git-lfs/git-lfs#3420]
All the pdfs/pngs/etc in my organization's repos are failing to render on github's online interface.
<img width="1053" alt="screen shot 2018-12-08 at 8 35 33 am" src="https://user-images.githubusercontent.com/35339599/49688297-95e2c180-fac4-11e8-96a4-b0b3c149e117.png">
The files are visible and uncorrupted when we clone. Does anyone have any ideas as to why this might be happening?

@mengsongouyang

EDIT: Image files stored without git-lfs are able to render, whereas those stored with git-lfs are not.

**Comment by bk2204** [comment]
Hey, sorry about this.

This was an issue on the GitHub server side that's been fixed. Just for future reference, if you have a problem with the GitHub server side, it's better to reach out to support@github.com, rather than us, since we only handle the client side here. You're more likely to get a faster response and better visibility that way.
