### ISSUE TITLE
Cloning locals lfs repository, not working when checkout lfs file on the cloned one

### ISSUE THREAD

**Issue by nhatkhai** [git-lfs/git-lfs#3438]
Cloning locals lfs repository, not working when I try to checkout lfs file on the cloned folder.
It work fine, if I add remote to a git server. But that not what I like to do. It like lfs should be able to use the lfs object from the local repository first (if it available). Then automatically down the lfs object using the original local repository setting for find lfs files server and download it.

**Comment by bk2204** [comment]
When you clone a repository with Git LFS, we only pull down the files that you need for your given checkout, since they may be large. Because of that, it's dangerous for us to handle a local clone in the same way as a clone from a remote server, since if we did, you could clone a repository, pull down only some LFS objects, delete the original repository, and then be stuck permanently missing data.

If you want this behavior anyway, and you're sure the original clone won't disappear, you can handle this case by using the `--shared` option to `git clone`, in which case the files will be copied from the other directory. However, you should read the Git documentation for that option and be sure that's the behavior you want.

**Comment by nhatkhai** [comment]
So what if I need to share my repos directly to my colleague through share network? Should it be at least "read-only" type of thing for lfs to work without the servers. What it server down? For truthfully distributed, I think we need lfs to be able to download from the local/share repositories too.

**Comment by bk2204** [comment]
In newer versions of Git LFS, trying to use a local clone prints the following:

```
hint: The remote resolves to a file:// URL, which can only work with a
hint: standalone transfer agent.  See section "Using a Custom Transfer Type
hint: without the API server" in custom-transfers.md for details.
```

You can look at [custom transport documentation](https://github.com/git-lfs/git-lfs/blob/master/docs/custom-transfers.md) for how to set up the a custom transport. We do have plans to make this easier and are tracking them in #1207.
