### ISSUE TITLE
Need way to rebase a non lfs files onto the branch using lfs of the same file.

### ISSUE THREAD

**Issue by nhatkhai** [git-lfs/git-lfs#3439]
I need to take my colleague changes into my master branch. But my colleague branch commit the file as binary. My branch are store these file in lfs. I don't need to diff them, I just want to take all my colleague change by using rebase, but it giving error: "have been pointers, but weren't" for couple commits, and eventually when it rebase to the commit with the same file change again, it fail the rebase, and keep telling me all the files are modified. git checkout -f, reset --hard... none are help. So I cannot rebase!

**Comment by bk2204** [comment]
The easiest way to handle this is to take your colleague's branch and run it through `git lfs migrate import`. You can specify just the one branch by using `--include` and `--exclude`. Then it will be in the right format for you to do a rebase, since the files will have been converted to LFS files, and the rebase should succeed.

**Comment by nhatkhai** [comment]
Thank for the hint on the other of calling rebase after migrate. It seem to work better.
I'm however, in my case, I need migrate take .gitattributes as input or use .gitattributes already there would be perfectly work better for me. Otherwise, I'm had to convert into "filter" list but it very smelly code.

**Comment by bk2204** [comment]
That sounds like a nice improvement. I've captured that suggestion as #3442 so that we don't lose track of it.
