### ISSUE TITLE
Can smudge using hard link for faster operation?

### ISSUE THREAD

**Issue by nhatkhai** [git-lfs/git-lfs#3450]

**Comment by nhatkhai** [comment]
I like to have some caching way to this to be faster. I seem to me copy if much faster than smudge, so why don't have have a kind of cached system to make it faster, and use gc to clean them up ?

**Comment by bk2204** [comment]
Git doesn't expect the files it operates on to be hard links, so trying to use those to speed things up is likely to lead to corruption.

The performance of the smudge filter is limited by the need to download files and by Git's internal smudge functionality. It is, however, significantly faster in recent versions of Git due to the filter-process handler.

We use this functionality because it's built into Git, and building our own caching system around it would mean that it wouldn't work with a core Git. If you'd like to reach out to Git upstream to see if they can improve the performance further, you're welcome to do so.

**Comment by nhatkhai** [comment]
What about giving use a option in smudge to use windows hard-link and/or with a "read-only" file mode. I'm use people have some special use case that need this feature. If not, they may have to force them-self implement or use for straight tool to accomplish it.

**Comment by nhatkhai** [comment]
Another use case: https://discourse.slicer.org/t/should-we-use-git-lfs-to-manage-data/2448

**Comment by nhatkhai** [comment]
Another one: https://git-annex.branchable.com/

**Comment by bk2204** [comment]
There is the `git lfs dedup` command which can be used if you're using ReFS on Windows as well as on other operating systems if your goal is to save space.

Git LFS doesn't control the smudge process; Git hands pointer files to Git LFS and then gets the file contents back, which are written to the file system.  It is possible to smudge manually using `git lfs checkout`, but we wouldn't implement hard linking because of the risk of data corruption, even with marking the file read-only.

We already use the file cloning functionality that's used in `git lfs dedup` if your file system supports it, so if you use a ReFS file system on Windows, running `git lfs checkout` should be significantly faster.

**Comment by nhatkhai** [comment]
Interesting ReFS, thank for sharing.

**Comment by nhatkhai** [comment]
However, I would think introducing a ~```git lfs smudge --usehardlink fileABC``` may also good for people like me still on the NTFS drive, and Linux Filesystem...
I had design the "git filter process" that cheat the git by first give it a same content as "clean" filter. While ran a child process to actually smudge files at the end of the filter process.
It is cheating, and made git confuse a little bit but no thing major. This hack can be apply for hardlink too. I can do this perl filter script but it would be a deep hack without some thing like ```git lfs smudge --useharklink fileABC```

**Comment by bk2204** [comment]
The problem is that it's very easy to introduce data corruption this way, even if you set the files read-only.  Editing a file in Vim and using `:w!` will change the read-only flag and write through the hard link, corrupting the file in the LFS object store.

I understand the desire for performance here and making this less expensive, but we can't have performance at the risk of data loss or corruption.  There are safe opportunities to make this faster if you're using ReFS, Btrfs, ZFS, or APFS, and if you need that performance, you can use those file systems.  I'm just not comfortable introducing options that make it very easy to silently corrupt data.  Even Git doesn't provide those kinds of options or capabilities.

**Comment by nhatkhai** [comment]
I'm not sure the argument sound. I remember Git design to allow the disk got corrupted and able to detect and move on. That are what SHA1 hash for. I remember the creator of GIT had tell use that many time on youtube.

**Comment by bk2204** [comment]
Git does allow easy detection of corruption via `git fsck`, and so does Git LFS.  However, Git doesn't provide any way for the user to write objects into the data store which don't match their hash, nor does it provide a way for users to modify the working tree through normal editing and as a result corrupt the data store, which is what we're discussing here.  I don't believe they would add such an option, either.

I'm very confident in saying this, since I've been contributing to upstream Git for some time.  I appreciate that we have different opinions on the desirability of hard linking here, and you're welcome to propose a patch and try to get one of the other members of @git-lfs/core to accept it provided you point them to this conversation so they can see my reservations.  However, because I believe this is ultimately a foot-gun, I have no plans to implement it or merge such a patch myself.

**Comment by kyotov** [comment]
merits of the approach aside, is this even possible to implement in the current git realm?

i thought the filter needed to write the contents to stdout and git takes care of creating the file... which would not be enough to create a hard link... i think.

the file path in question is passed by if you have %f in the configuration, but you can't use that since git will simply overwrite it with what you have written to standard out... i would assume.

thoughts?

**Comment by bk2204** [comment]
No, it is not possible to implement in the current realm using the filter processes.  It could be done with `git lfs checkout`, which currently prefers to use copy-on-write semantics when available; those are safe, while hard linking is not.  Of course, whether copy-on-write semantics are used depends entirely on your file system and its capabilities.

**Comment by kyotov** [comment]
thanks for confirming!

that means that every time you checkout something from git that has LFs, it will true-copy them the expensive way, even if your filesystem supports cloning?

or do you have a mode where you checkout the pointers only and then perhaps some hook can run the `git lfs checkout` to populate the actual content and replace the pointer files?

**Comment by bk2204** [comment]
> that means that every time you checkout something from git that has LFs, it will true-copy them the expensive way, even if your filesystem supports cloning?

Yes, that's how Git works.  Git has no way to be instructed to clone files because (a) that's highly OS specific and (b) the filtering mechanism isn't intended, in general, to be used the way Git LFS has used it.  The usual custom usage is to perform some simple transformation, such as adding and removing dates or other data from files.
 
> or do you have a mode where you checkout the pointers only and then perhaps some hook can run the `git lfs checkout` to populate the actual content and replace the pointer files?

You can run `git lfs install --skip-smudge` so that when Git runs it leaves the pointer files in the tree and then run `git lfs checkout` or `git lfs pull`, but there's no automatic way to do it.

**Comment by kyotov** [comment]
I reached the same conclusion investigating it, but did not want to taint you with my understanding ;) Thanks!

What about this git hook... will that not be a good time to run the `git lfs pull` / `git lfs checkout`

> After you run a successful git checkout, the post-checkout hook runs; you can use it to set up your working directory properly for your project environment. This may mean moving in large binary files that you don’t want source controlled, auto-generating documentation, or something along those lines.

**Comment by bk2204** [comment]
I think you could do that if you wanted, although I'm not sure if it covers all possible edge cases.

**Comment by rmedaer** [comment]
Meaning we could actually:

  > You can run git lfs install --skip-smudge so that when Git runs it leaves the pointer files 

  1. skip smudge/filter; keep the file content (pointer) stored in Git storage,

  > What about this git hook... will that not be a good time to run the `git lfs pull` / `git lfs checkout`

  2. do the hard-linking in a Git hook

In this case, I guess Git will see files as "changed". No ?

**Comment by kyotov** [comment]
I thought that git runs things through the smudge/clean filter before
deciding if they have changed, so I think no... I think it will convert
them back to pointers and realize that they have not changed, no?

**Comment by rmedaer** [comment]
Hi @kyotov,  I accidentally deleted my previous comment. Thanks to your email reply, it's well attached. Anyway,...

> I think it will convert them back to pointers and realize that they have not changed, no?

I don't know but I would enjoy to test it. Furthermore, I'm going to do some experiments around [the "read-only issue"/hard-link solution](https://github.com/git-lfs/git-lfs/issues/3450#issuecomment-552969227). Indeed, even if it works with a hard-link, it becomes an issue if you try to modify the file (in your stage). Instead of the "read-only" solution, we could use "reflink" (copy-on-write) available on some file systems like _btrfs_ or _xfs_. Instead of breaking the original file in `.git/lfs/objects/...`, it would copy if you change your local copy. But indeed, it's file-system-dependent.

**Comment by bk2204** [comment]
> I don't know but I would enjoy to test it. Furthermore, I'm going to do some experiments around [the "read-only issue"/hard-link solution](https://github.com/git-lfs/git-lfs/issues/3450#issuecomment-552969227). Indeed, even if it works with a hard-link, it becomes an issue if you try to modify the file (in your stage). Instead of the "read-only" solution, we could use "reflink" (copy-on-write) available on some file systems like _btrfs_ or _xfs_. Instead of breaking the original file in `.git/lfs/objects/...`, it would copy if you change your local copy. But indeed, it's file-system-dependent.

We already use the reflink solution if you use `git lfs checkout`, `git lfs pull`, or `git lfs dedup`.  There's similar functionality in APFS and in ReFS on Windows.

**Comment by Pierrci** [comment]
Hi @bk2204, I've been experimenting (on a Macbook with APFS filesystem) with `git lfs pull` in a repo with large files after cloning it with `GIT_LFS_SKIP_SMUDGE=1`. I checked the total space available on the disk before/after `git lfs pull`, and it looks like no reflinks are used: the available disk space decreases by 2x the size of the pulled files, where I was expecting it to decrease by only 1x because of the use of reflinks. Are my expectations wrong / am I missing something? cc @julien-c

(when I do a `cp -c` (which uses [clonefile(2)](https://www.manpagez.com/man/2/clonefile/)) on a big file, the remaining available disk space doesn't change, as expected)

**Comment by bk2204** [comment]
Hey,

The code is designed to fall back to using a normal copy if for whatever reason the `clonefile(2)` call (or your operating system's equivalent) fails.  You can try `git lfs dedup --test` to see what an example operation looks like for Git LFS on your system.

I will point out that if you're using a binary without cgo support, then this won't work.  Some of our older binaries were built on a Linux system and therefore lacked support for this operation; you may need to look for a newer binary of ours, which is built on macOS, or a Homebrew version (which I believe should work).
