### ISSUE TITLE
OAuth credentials in extraheader cause fetch to fail

### ISSUE THREAD

**Issue by pjquirk** [git-lfs/git-lfs#3454]
Given the following commands:

    git init
    git remote add origin https://github.com/unicode-org/icu
    git lfs install --local
    git -c http.extraheader="AUTHORIZATION: basic %AUTH%" fetch --tags --prune --progress --no-recurse-submodules --depth=1 origin
    git -c http.https://github.com.extraheader="AUTHORIZATION: basic %AUTH%" lfs fetch origin 2e86b08fcda87e279efdcb8f9f3310cb6b9150af

When I use a base64-encoded credential of `PersonalAccessToken:<my personal access token>`, the script above succeeds.  

When I use a base64-encoded credential of `OAuth:<my oauth token>`, the script above fails with the following output:

    > git -c http.https://github.com.extraheader="AUTHORIZATION: basic ***" lfs fetch origin 2e86b08fcda87e279efdcb8f9f3310cb6b9150af
    fetch: Fetching reference 2e86b08fcda87e279efdcb8f9f3310cb6b9150af
    batch response: Not Found  0% (0/234), 0 B | 0 B/s
    batch response: Not Found
    batch response: Not Found
    batch response: Not Found
    error: failed to fetch some objects from 'https://github.com/unicode-org/icu.git/info/lfs'

`git lfs logs last` returns "No logs to show".  I'm not the owner of that repo (I'm helping troubleshoot a different problem), and I can't reproduce it by just enabling it on a [test repository](https://github.com/pjquirk/vsts-playground/commit/9e501d609b352ba8f396ea5dcb0ce339afa05a30).

[Here](https://github.com/git-lfs/git-lfs/files/2722018/trace.txt) is the trace for this script (with credentials replaced with *****).

Am I missing something, or is this a bug?

Versions:
git version 2.19.0.windows.1
git-lfs/2.5.1 (GitHub; windows amd64; go 1.10.3; git e1628484)

**Comment by bk2204** [comment]
Hey, sorry to hear you're having trouble.

The `http.extraheader` option for Git doesn't apply to Git LFS, so it has no effect on authentication for LFS. In all likelihood, what's happening is that your authentication to github.com is granted based on an existing credential that's in your credential helper in one case and not the other, which is causing the failure you're seeing.

If you want to pass an OAuth token, the best way would be to have a credential helper or `.netrc` file provide that username and the token as a password.

**Comment by pjquirk** [comment]
Support for `http.extraheader` was added in #2159, right? Looks like it should be supported for >=v2.1.0.

**Comment by bk2204** [comment]
I apologize, you're right. My grepping of the codebase didn't take into account that we spell it in mixed case (we usually spell the variables in lower case since it makes tests easier to write).

In that case, if it works with a personal access token but doesn't work with an OAuth token, then it's probably that your OAuth token isn't scoped correctly or that it doesn't have access to the repo in question. Those kinds of questions are better addressed to GitHub Support (`support@github.com`), since they're more familiar with those issues and will be better able to help you. We only deal with the open source Git LFS project in this repo.
