### ISSUE TITLE
Git LFS push uses different remote URL than Git LFS pull

### ISSUE THREAD

**Issue by VultureX** [git-lfs/git-lfs#3457]
Hi all,

I'm running a Gitea server (v1.6.2). The server can be reached via the local ip address inside the local network and via the public ip address from outside the network. I do not have a domain name registered, so I'm using explicit IPs.
But whenever I try to execute git lfs push on a repository hosted by the server with a computer inside the local network the push operation fails, because it's using the public IP that's defined by the ROOT_URL property defined in Gitea's app.ini.
I can change the ROOT_URL to point to the local address, but then computers from outside obviously can't connect. I'm not sure whether this is a problem with Gitea or with Git LFS or with the self-signed security certificate. All other operations (such as git lfs pull) work correctly. Is there a way to solve this?

`"D:\Programs\Git\bin\git.exe" push --recurse-submodules=check --progress "origin" refs/heads/master:refs/heads/master Uploading LFS objects: 0% (0/1), 0 B | 0 B/s, done LFS: Put https://xxx.xxx.xxx.xxx:3000/XX/Test.git/info/lfs/objects/aed286ac1fa67fe7050ff63cac3056decd38d37743525fd06de777c80265a189: dial tcp xxx.xxx.xxx.xxx:3000: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond. error: failed to push some refs to 'https://192.168.192.49:3000/XX/Test.git' Done`

app.ini

```
[server] 
ROOT_URL = https://xxx.xxx.xxx.xxx:3000/
```

Here is my git lfs environment:

```
git-lfs/2.6.1 (GitHub; windows amd64; go 1.11.1; git dc072c3e)
git version 2.20.1.windows.1

Endpoint=https://192.168.192.49:3000/XX/Test.git/info/lfs (auth=basic)
LocalWorkingDir=D:\Repositories\Gitea\Test
LocalGitDir=D:\Repositories\Gitea\Test\.git
LocalGitStorageDir=D:\Repositories\Gitea\Test\.git
LocalMediaDir=D:\Repositories\Gitea\Test\.git\lfs\objects
LocalReferenceDirs=
TempDir=D:\Repositories\Gitea\Test\.git\lfs\tmp
ConcurrentTransfers=3
TusTransfers=false
BasicTransfersOnly=false
SkipDownloadErrors=false
FetchRecentAlways=false
FetchRecentRefsDays=7
FetchRecentCommitsDays=0
FetchRecentRefsIncludeRemotes=true
PruneOffsetDays=3
PruneVerifyRemoteAlways=false
PruneRemoteName=origin
LfsStorageDir=D:\Repositories\Gitea\Test\.git\lfs
AccessDownload=basic
AccessUpload=basic
DownloadTransfers=basic
UploadTransfers=basic
GIT_EXEC_PATH=D:/Programs/Git/mingw64/libexec/git-core
GIT_SSH=D:\Programs\GitExtensions\PuTTY\plink.exe
git config filter.lfs.process = "git-lfs filter-process"
git config filter.lfs.smudge = "git-lfs smudge -- %f"
git config filter.lfs.clean = "git-lfs clean -- %f"
```

**Comment by bk2204** [comment]
Hey, sorry to hear you're having problems.

Git LFS uses a batch API request to find the place it should upload files to and download files from. It sounds like Gitea uses the ROOT_URL setting to determine the root of these URLs.

Git LFS doesn't provide any way to override these URLs, since even if they share the same root with the endpoint, we don't know that if they're changed by the user, that they'll continue to work. I'd recommend reaching out to Gitea about this and seeing if they can help you with this, since it sounds like you want to have a ROOT_URL setting that's customized depending on the incoming interface.

**Comment by kemin711** [comment]
Not sure my question is related to this one.  How do you push to repo on the same computer (computer R) for lfs objects?  Say if I can push, pull from computer X to R without any problem. But when pushing to R::repo(with lfs) from the same computer, where the remote is /home/git/myrepo(with or without .git).  How should I configure the database of lfs.  LFS_METADB=lfs.db. It seem information is in this variable.

**Comment by bk2204** [comment]
If you just want to push to a local path, you don't need lfs-test-server.  You can simply push to a path like `/home/git/myrepo` from the Git client, but it must be a regular (bare or non-bare) Git repository.  However, you cannot use the same storage for lfs-test-server and regular remotes, since the former has to be managed by the server and the latter is not.

You also require at least version 2.10 if you use the `file:///` syntax (e.g., `file:///home/git/myrepo`), and a newer version (I forget which) to add a plain path.

**Comment by kemin711** [comment]
@bk2204 Thanks.  I am trying to do both (local plus lfs remote).  I experimented, seems the local and lfs-server is storing the objects in different locations.  On the server machine, I was pushing from a different account to git bare-shared repository that is also the same for lfs repo from a remote machine.  So the final word is that local and lfs is mutually exclusive with regards to binary objects.  This should not be a problem; I will host the lfs in a separate server.  Another question: has anyone written or contributed a daemon for the start up script?  Once it passed test, we will need the service to be started on reboot of the server.

**Comment by bk2204** [comment]
I'm not aware of a startup script for lfs-test-server.

And yes, `scutiger-lfs` stores data in a regular repository, so you can push and pull either over SSH or via a file URL.

I'd like to ask you to move this to a discussion, if you would, since this is not really on topic for this issue.

**Comment by kemin711** [comment]
@bk2204  Grateful for your help. I will use the discussion in the future.
