### ISSUE TITLE
How to stop git-lfs and back to git without file lost?

### ISSUE THREAD

**Issue by gitbobo** [git-lfs/git-lfs#3463]
As git-lfs has lots of problem when I use it( I am newbee), I decide to stop and remove  `git lfs`.  
But `git lfs` already tracked part of files,how to move those files back to git?  
What I need is a tutorial.   
Thanks in advance!

**Comment by bk2204** [comment]
Sorry to hear that you're having trouble.

If you want to move back to storing your files in Git instead of Git LFS, you can use `git lfs migrate export`, which turns all of the Git LFS pointer files back into the original files. Note that if your main remote isn't `origin`, you'll need to specify the `--remote` options. You can see [the docs in the repository](https://github.com/git-lfs/git-lfs/blob/master/docs/man/git-lfs-migrate.1.ronn#export).

If there are things we can do to make the experience better in the future, please let us know.

**Comment by ggrrll** [comment]
`git lfs migrate export --include [file]` is not working for me :/
