### ISSUE TITLE
Git LFS is not enabled on this GitLab server, contact your admin.

### ISSUE THREAD

**Issue by hemanz** [git-lfs/git-lfs#3465]
git-lfs/2.3.4 (GitHub; darwin amd64; go 1.9.1; git d2f6752f)
git version 2.19.2

$ git-lfs filter-process
Error downloading object: LivenessWithWrapperReleaseAndTest/libLivenessDetectorOffline/libLivenessDetector.a (1db3ce7): Smudge error: Error downloading LivenessWithWrapperReleaseAndTest/libLivenessDetectorOffline/libLivenessDetector.a (1db3ce7a79aff5e1ccc6a3b48028d8aaf7370bb1c77eed52fdeb3f9418bc354a): batch response: Git LFS is not enabled on this GitLab server, contact your admin.

**Comment by bk2204** [comment]
Hey,

As the message mentions, this is a configuration of the server (GitLab) such that it doesn't have Git LFS enabled on the server or repository. Since this repository is only for the Git LFS client, you'll probably want to reach out to your server admin (or GitLab themselves, if it's the cloud version) to see if you can get it enabled on your instance.
