### ISSUE TITLE
Error download object Smudge Error

### ISSUE THREAD

**Issue by Envenger** [git-lfs/git-lfs#3491]
Hello, so I am having problems pulling files from online repo. I have gotten the smudge error repeatedly on some of my projects and needed to to recreate repos for those projects.

![image](https://user-images.githubusercontent.com/7002742/51639252-6f9ab780-1f86-11e9-9820-aa5730182805.png)

I have gone through some of related issues but in my case, the file is absent on the online repository.
The problem is something like this.

System1: Has the file correctly and pushes the file.
Repository: Doesn't receive the file.
System2: When I pull I don't receive the file.

If i change the file in System1 to at-least make it recommit that also doesn't work.
The issue happens randomly and on random files. Files of the same type work but a particular file randomly gets this issue.

**Comment by ttaylorr** [comment]
Hi @Envenger, thanks for opening this issue and sorry that you're having trouble. It looks like the problem is described here:

> System1: Has the file correctly and pushes the file.
> Repository: Doesn't receive the file.

Since the first Git LFS client found and correctly pushed the file, I am inclined to believe that the implementation of the Git LFS protocol that you are using has a bug in it. My assumption here is that that bug is causing it (the server) to avoid storing the file, which would explain why the other Git LFS client fails to pick it up.

One thing that we could try quickly is the following:

1. On the client that has Git LFS installed and _has_ the file, make sure that the remote (`git remote -v`) is configured correctly, and re-push the file with `git lfs push --all`.
2. On the client that has Git LFS installed and _does not_ have the file, make sure that the remote is again configured correctly, and try to `git pull` (or `git lfs pull`, if you have the most recent history).

If that doesn't work, I'd recommend reaching out to your Git LFS hosting provider, and seeing what they think. Thanks, and be sure to let us know if you have any more questions here!
