### ISSUE TITLE
re-upload LFS Files

### ISSUE THREAD

**Issue by darshannnn** [git-lfs/git-lfs#3493]
Hi there, since the lfs server does not remove lfs-objects when LFS files are deleted and pushed from a client. I wrote a post-receive server hook to delete the lfs-object from the server lfs storage.

Now if I re-add the deleted files to the repo and push, LFS files is not added back to the LFS server store. This behavior has been reported on a previous issue: How to force LFS to re-upload binary assets #2703

As mentioned there I did try, 'git lfs push --all', but the file is still not added to the LFS Store.
Is this because the server is reporting it has the files? We are using an on premise GitLab server.
Should I report a bug on GitLab?

**Comment by ttaylorr** [comment]
Hi @darshannnn, thanks for asking.

> Is this because the server is reporting it has the files? We are using an on premise GitLab server.

That's right: when you run `git lfs push --all`, the following happens:

1. Git LFS scans _all_ history, (instead of just the unpushed bits, that's what `--all` does here) to try and find Git LFS pointers that it can attempt to upload.
2. Of the list that we found, we ask the server to produce a set of locations for which we can upload the binary data associated with each pointer.
3. The server can respond with whatever it wants, but most implementations tend to only provide links for Git LFS objects that it does not currently have.

In (3), if the client doesn't receive an upload link for any particular object, it will assume that the server already has it and does not want another copy.

So I think that this isn't technically a "bug", but I don't think that it's something that we can quite help with either. In this case, I'd recommend getting in touch with someone at GitLab and seeing what they can do.

Please let us know if you have any other questions! Thanks.

**Comment by bbodenmiller** [comment]
@darshannnn how did you end up fixing this?

**Comment by SteezyCougar** [comment]
I seem to be in a similar situation

**Comment by darshannnn** [comment]
> @darshannnn how did you end up fixing this?

ended up doing this
https://github.com/darshannnn/GitLabLFS-custom_hooks
