### ISSUE TITLE
git-lfs doesn't work with Github Pages

### ISSUE THREAD

**Issue by LinuxUserGD** [git-lfs/git-lfs#3498]
git-lfs doesn't store the full file, so running a game inside of the browser doesn't work with git-lfs.

**Comment by ttaylorr** [comment]
GitHub Pages does not support embedding Git LFS objects in your page (c.f., duplicate https://github.com/git-lfs/git-lfs/issues/2725).

Since this repository is for Git LFS support, there's not much more that we can do, other than recommend you send an email to support@github.com, who can note your interest in this feature.

**Comment by srghma** [comment]
github pages should return json/text files correctly, will contact support

![2021-12-03-05pm-32-47-screenshot](https://user-images.githubusercontent.com/7573215/144629389-1ca1ef83-9155-431e-bdf1-4aefcfd52bb9.png)
![2021-12-03-05pm-32-11-screenshot](https://user-images.githubusercontent.com/7573215/144629391-e78ff46f-eb57-4c3d-ac47-ec441d512a8c.png)
