### ISSUE TITLE
[Suggestion] Provide a way to check if a blob is an LFS pointer

### ISSUE THREAD

**Issue by markonius** [git-lfs/git-lfs#3500]
I can get a regular old file with `git cat-file blob <blob_hash>`, but I need a way to check if that blob is an LFS pointer so that I know whether I need to pipe it into `git lfs smudge`.  
Something like `git lfs pointer --check <pointer_contents>`

I'm sorry if something like this is already possible, I couldn't find that functionality.

**Comment by vbjay** [comment]
```git cat-file -p $TREE_SHA1:.gitattributes | git check-attr --stdin -- $FILENAME | grep "filter: lfs"```

This is a great idea.  Could even accept a blob sha.  

```bash
git lfs pointer --check <blob sha>
git lfs pointer --check <file contents>
```

**Comment by ttaylorr** [comment]
> `git cat-file -p $TREE_SHA1:.gitattributes | git check-attr --stdin -- $FILENAME | grep "filter: lfs"`

I'm not quite sure this is doing exactly what @markonius was asking for. Your command seems to look for all entries in the `.gitattributes` file that are affected with the Git LFS filter. I think that this can be slightly simplified to:

```ShellSession
$ git check-attr filter -- $filename
```

In any case, this doesn't dictate whether or not `$filename` is a Git LFS pointer in the history at all points in time, since a user can bypass the `.gitattributes` mechanism in a number of ways, e.g., by not having Git LFS installed, disabling their clean filter, and so on.

> I need a way to check if that blob is an LFS pointer so that I know whether I need to pipe it into `git lfs smudge`.

I think what `git lfs pointer --check` might do is something like this: read in a file, and report whether or not it is parse-able as a valid pointer. I can recommend some hack-y ways to do this sort of thing, but really this sort of behavior should live within Git LFS, since it can act as an authoritative source on whether or not something is a pointer.

I implemented such a functionality in https://github.com/git-lfs/git-lfs/pull/3501.

**Comment by vbjay** [comment]
No.  I was using it as a reverse point of what can be used to find out if pathx is lfs tracked.  We would LOVE for the feature of I have blob sha(sha from git-ls-tree that is a blob)

**Comment by ttaylorr** [comment]
@vbjay I think that this feature is not Git LFS specific (in other words, whereas @markonius's request is asking what _Git LFS_ thinks about something, this is asking only about what _Git_ thinks of the world).

One thing you could do is:

```ShellSession
$ git ls-tree -r HEAD | grep $blobid | cut -f 2 | xargs git check-attr filter --
```

**Comment by vbjay** [comment]
Please read https://github.com/gitextensions/gitextensions/pull/6189 for full context.

**Comment by markonius** [comment]
Yes, @ttaylorr , #3501 does what I originally suggested. But it seems I haven't thought it through 100%.  

If a random file were to be checked by piping it to your new command, this requires opening the file and what happens if the file is huge? Does your implementation stop reading early?

But, a more iportant point is the one @vbjay brought up, that it's not enough for us to know that a file is a parsable pointer, it is important to know if it is a valid pointer within a repository, i.e. whether it actually points to something.  
For that, we would need to know if a certain file at a certain point in history was tracked by LFS. This file is uniquely identifiable by its blob sha, so that's why @vbjay was asking for your implementation to accept it.

OK, so that was me trying to clear things up. Aside from that, thank you for implementing this so fast, you've done exactly what I originally asked for.

**Comment by markonius** [comment]
> For that, we would need to know if a certain file at a certain point in history was tracked by LFS. This file is uniquely identifiable by its blob sha, so that's why @vbjay was asking for your implementation to accept it.

Would this be possible? A way around this is to check the .gitattributes at that point in history, but that is a bit fiddly. Is there some hope that you have a cleaner internal solution?
