### ISSUE TITLE
Add a way to automatically escape/quote filenames given to git lfs track

### ISSUE THREAD

**Issue by mitar** [git-lfs/git-lfs#3506]
We use the following simple command to track all files larger than 100 KB in our repo:

```bash
$ find * -type f -size +100k -exec git lfs track '{}' +
```

The issue is that `git lfs track` in fact expects a git pattern and not filename as an argument. So if a filename contains special characters it can happen that this does not configure git lfs to really track a file. For example, if file has a filename `foo[bar].jpg`, calling `git lfs track foo[bar].jpg` will in fact not configure it to track that file.

I would suggest an argument is made to `git lfs track` to allow passing filenames and `git lfs track` would then make sure to properly escape/quote the filename before storing it into `.gitattributes` file. For example, something like `git lfs track --filename` or something like that.

**Comment by bk2204** [comment]
Hey, thanks for writing in.

I think this is something we can consider. I think this could be useful for people who are tracking names with things such as spaces or other special characters.

I would like to point out, though, that matching a large number of individual files may cause poorer performance from Git than you'd like, since I believe the matching for `.gitattributes` is O(N²). It may be useful to consider minimizing the number of rules you add.

**Comment by bk2204** [comment]
If it works for you, that's great. I just thought I'd point it out in case an improvement could help you get better performance.

**Comment by mitar** [comment]
Thanks!

**Comment by ttaylorr** [comment]
I think that it's a good idea, too. Unfortunately, I think we need the `--filename` flag, since we need some way to distinguish between escape characters in attribute patterns, and escaped characters in filenames.

I started looking at the code myself to implement this, but I am reminded of how much `git lfs track` (in particular, `commands/command_track.go` and its friends) have grown in complexity. This is natural over time, of course, but it's becoming prohibitively complex that I think we ought to start from scratch with `git lfs track`.

@bk2204 what do you think?

**Comment by bk2204** [comment]
> I think that it's a good idea, too. Unfortunately, I think we need the `--filename` flag, since we need some way to distinguish between escape characters in attribute patterns, and escaped characters in filenames.

Yes, I agree that a flag would be useful here. I had imagined that as the direction to go in the first place, but hadn't explicitly mentioned it.
 
> I started looking at the code myself to implement this, but I am reminded of how much `git lfs track` (in particular, `commands/command_track.go` and its friends) have grown in complexity. This is natural over time, of course, but it's becoming prohibitively complex that I think we ought to start from scratch with `git lfs track`.

I definitely think a refactor (or even a rewrite) could be helpful; the code is, as you point out, rather complex. It's not super likely that I'll get time to do that soon, but you or anyone else are welcome to do so. Or we could just shoehorn another option in there and punt until later.

**Comment by ttaylorr** [comment]
> It's not super likely that I'll get time to do that soon, but you or anyone else are welcome to do so.

Indeed, it's unlikely that I'll be able to get to it much sooner than you :-). It's hard to say what to do here (though I feel badly about suggesting something I do not have the time myself to complete).

On one hand, perhaps we could squeeze this in the existing code. This doesn't feel like a great option to me: we increase the likelihood of breakage, a hefty price to pay for implementing a feature for which I have only seen one request.

On the other hand, we could make this feature wait on a larger rewrite of the command (at still high risk of breakage, and perhaps higher). I'm not sure where to go from here.
