### ISSUE TITLE
Files stay as pointers

### ISSUE THREAD

**Issue by Danl2620** [git-lfs/git-lfs#3508]
This may be a dumb question, but in my working repo with many files controlled by LFS, I have a directory of LFS files that is stored as pointers and I can't seem to get them to convert to the binaries. Is there some setting or command I've gotten stuck with and can get unstuck?

git lfs env:

```
git-lfs/2.3.4 (GitHub; darwin amd64; go 1.9.1; git d2f6752f)
git version 2.18.0

Endpoint=https://github.com/WSStudios/tdp1.git/info/lfs (auth=basic)
Endpoint (wslib)=https://github.com/WSStudios/wslib.git/info/lfs (auth=none)
LocalWorkingDir=/Users/danl/proj/ws/tdp1
LocalGitDir=/Users/danl/proj/ws/tdp1/.git
LocalGitStorageDir=/Users/danl/proj/ws/tdp1/.git
LocalMediaDir=/Users/danl/proj/ws/tdp1/.git/lfs/objects
LocalReferenceDir=
TempDir=/Users/danl/proj/ws/tdp1/.git/lfs/tmp
ConcurrentTransfers=32
TusTransfers=false
BasicTransfersOnly=false
SkipDownloadErrors=false
FetchRecentAlways=false
FetchRecentRefsDays=7
FetchRecentCommitsDays=0
FetchRecentRefsIncludeRemotes=true
PruneOffsetDays=3
PruneVerifyRemoteAlways=false
PruneRemoteName=origin
LfsStorageDir=/Users/danl/proj/ws/tdp1/.git/lfs
AccessDownload=basic
AccessUpload=basic
DownloadTransfers=basic
UploadTransfers=basic
FetchExclude=content
GIT_EXEC_PATH=/nix/store/393j8xi0jwkn5yn754bfjzsnl5zvssbr-git-2.18.0/libexec/git-core
git config filter.lfs.process = "git-lfs filter-process"
git config filter.lfs.smudge = "git-lfs smudge -- %f"
git config filter.lfs.clean = "git-lfs clean -- %f"
```

**Comment by ttaylorr** [comment]
> This may be a dumb question

Not at all. The nature of Git LFS and its interactions with Git can be finicky. This isn't a fault of either tool, both are trying to be the most general that they can be while still working with one another. In any case, you're certainly not the first to run into this :-).

> I have a directory of LFS files that is stored as pointers and I can't seem to get them to convert to the binaries

This could be a couple of things. Let's try the following (note that some of these are redundant based on the output of `git lfs env` above, but I want this issue to serve as a reference for anybody in the future who gets stuck on a similar issue. I'm also not explicitly familiar with your operating system, so some of these might be worth double checking anyway.)

1. Make sure that you have run `git lfs install`. This makes sure that your system-wide Git configuration knows where to find the `git-lfs` program it needs to convert pointers into large files. Double check that that's set (and that `git config filter.lfs.process` looks sane).

2. Make sure that the pointer files in question are indeed tracked by Git LFS. Git decides whether or not this is the case by inspection of the applied attributes to a given path, and you can check these with `git check-attr -a /path/to/file`. So long as it says `filter=lfs`, you should be OK.

3. Lastly, double check that you're not explicitly excluding this file (or set of files) from checkout. You can do this by running `git config lfs.fetchexclude`, and making sure that there aren't any paths you're interested in there.

4. A bonus! You can double check to make sure that you haven't explicitly disabled conversion repository-wide by running `echo $GIT_LFS_SKIP_SMUDGE`. Make sure that this is unset.

If none of those seem to be what's happening and after checking through things you're still not able to make things work, please let us know by dropping a comment here, and I'd be happy to re-open this issue and we can look further. Thanks!

**Comment by Danl2620** [comment]
Yes, it was `lfs.fetchexclude`!  I forgot how this feature worked, but remember adding the files to the exclude list. Thanks!

**Comment by jm991** [comment]
Hi @ttaylorr , I'm on @Danl2620 's team and I was also running into this issue, even after running your 4 steps listed above. I also ran `git lfs pull`, but it didn't work and I got a lot of `Could not check out "FILE.ext"` errors.

I noticed that all of the lfs pointer files in my repo were Read-Only in the Windows file property viewer.
The only way I could fix this problem was to right click all the files I wanted to convert from pointers to real files, and uncheck the "Read Only" checkbox in the Windows file property viewer. After doing that, `git lfs pull` worked like a charm and the correct files appeared.

**Comment by jm991** [comment]
to be clear, I never set these files as Read Only - I'm not sure how they got in that state.

**Comment by ttaylorr** [comment]
> to be clear, I never set these files as Read Only - I'm not sure how
> they got in that state.

One way this can happen is if some of the files in your repository are
marked as 'lockable' by Git LFS.

By default (and you can read more about this in `git-lfs-config(5)`),
files that are marked as lockable loose their write bit just after the
checkout phase (in Git LFS's .git/hooks/post-checkout) through the 'git
lfs post-checkout' command.

If you don't want those files to be lockable, you can remove the
'lockable' attribute in your .gitattributes file(s), and then checkout
the tree again.

**Comment by eliasnas** [comment]
Hey guys,

I have been facing this problem for several days, and I tried the 4 steps above and all seems ok.
After cloning with get, I try to run "git-lfs pull" and when I do so, I get stuck at "Downloading LFS objects 0% ".

Any Idea?

Regards,
Elias

**Comment by chrisd8088** [comment]
@eliasnas -- This is an old, closed issue.  If you're having problems with a current version of Git LFS, please open a new issue and make sure to fill in all the requested sections of the issue template, such as the output of `git lfs env` and full details as to what steps you're performing and their output.  Thank you!

**Comment by Pyr3z** [comment]
Strange.

I was having this issue on a test fresh pull of a repo using LFS, and I suppose I forgot to call `git lfs install` before using some PNGs because they were still just pointers—it wasn't clear before that fresh cloners need to call `git lfs install` (and an additional `git add .`) no matter what before using their worktree. Also, before and after running `install`, `git lfs env` looked identical.

Might need to move this to a separate question thread, but is there a way to automate this for fresh cloners? Like if someone whose git environment is already configured for LFS pulls a fresh clone, is there a way to have their repo-level git hooks auto-populated for LFS as well?

**Comment by bk2204** [comment]
If you've run `git lfs install` for your user at least once before, then things should work automatically, unless you've overwritten your `~/.gitconfig` since then.  If they're not, please open a new issue and fill out all of the information in the issue template, and we'll work with you to figure why it's not.
