### ISSUE TITLE
Uploading LFS file taking forever, got client error and a URL?

### ISSUE THREAD

**Issue by RobRoseKnows** [git-lfs/git-lfs#3512]
I've been trying to push to GitHub LFS the past couple days and I'm having quite a bit of trouble with it, I think my internet connection is just bad though, and itt's a ~500MB file. so every time it fails it needs to start over. Today I got a weird error though:

> LFS: Client error: https://github-cloud.s3.amazonaws.com/alambic/media/137910649/c2/17/c2173be93a4197b479360a1a24d54205819df834967f3991b3b90c80f11689fc?actor_id=1022908

What does this mean? I can't access the URL, I get an access denied message.

**Comment by ttaylorr** [comment]
Hi @RobRoseKnows, thanks for opening this issue and sorry that you're having trouble. This is a GitHub URL, so I think that whatever this problem is it's related to GitHub and not Git LFS.

Since this set of issues is for the later and not the former, would you mind instead forwarding this to support@github.com? They should be happy to help you out.

**Comment by RobRoseKnows** [comment]
Will do, was going to submit there first but there's a big yellow notice on the support page for Git-Lfs issues: https://github.com/contact. Thanks though!
