### ISSUE TITLE
Git lfs does not respect custom port over https

### ISSUE THREAD

**Issue by Frame42** [git-lfs/git-lfs#3526]
I have a git repo with LFS enabled behind a firewall with just port 7443 open.
`git clone` or `git lfs clone` operations hang forever with git-lfs.exe trying to connect to the git server at port 443. 
In Sysinternals ProcessExplorer, I can see one connection established over port 7443 and one connection over port 443 being tried, timeout and replaced by a new one. The process stack looks like:
> git clone https://redacted.com:7443/some/path/MyProject.git MyProject
> __ sh -c "git-lfs filter-process" "git-lfs filter-process"
> ____ git-lfs "filter-process"

Below are my logs for both operations + the content of my .git/config files.

> user@server MINGW64 ~
> $ git --version
> git version 2.20.1.windows.1
> 
> user@server MINGW64 ~
> $ git lfs --version
> git-lfs/2.6.1 (GitHub; windows amd64; go 1.11.1; git dc072c3e)
> 
> user@server MINGW64 ~
> $ git clone https://redacted.com:7443/some/path/MyProject.git MyProject
> Cloning into 'MyProject'...
> remote: Counting objects: 2890, done.
> remote: Compressing objects: 100% (273/273), done.
> remote: Total 2890 (delta 182), reused 259 (delta 105)
> Receiving objects: 100% (2890/2890), 280.18 MiB | 55.70 MiB/s, done.
> Resolving deltas: 100% (1471/1471), done.
> warning: Clone succeeded, but checkout failed.
> You can inspect what was checked out with 'git status'
> and retry the checkout with 'git checkout -f HEAD'
> 
> warning: Clone succeeded, but checkout failed.
> You can inspect what was checked out with 'git status'
> and retry the checkout with 'git checkout -f HEAD'
> 
> user@server MINGW64 ~
> $ cat MyProject/.git/config
> [core]
>         repositoryformatversion = 0
>         filemode = false
>         bare = false
>         logallrefupdates = true
>         symlinks = false
>         ignorecase = true
> [remote "origin"]
>         url = https://redacted.com:7443/some/path/MyProject.git
>         fetch = +refs/heads/*:refs/remotes/origin/*
> [branch "master"]
>         remote = origin
>         merge = refs/heads/master
> [lfs "https://redacted.com:7443/some/path/MyProject.git/info/lfs"]
>         access = basic
> 
> user@server MINGW64 ~
> $ git lfs clone https://redacted.com:7443/some/path/MyProject.git MyProject2
> WARNING: 'git lfs clone' is deprecated and will not be updated
>           with new flags from 'git clone'
> 
> 'git clone' has been updated in upstream Git to have comparable
> speeds to 'git lfs clone'.
> Cloning into 'MyProject2'...
> remote: Counting objects: 2890, done.
> remote: Compressing objects: 100% (273/273), done.
> remote: Total 2890 (delta 182), reused 259 (delta 105)
> Receiving objects: 100% (2890/2890), 280.18 MiB | 57.00 MiB/s, done.
> Resolving deltas: 100% (1471/1471), done.
> Downloading LFS objects:   0% (0/248), 0 B | 0 B/s
> Exiting because of "interrupt" signal.
> 
> user@server MINGW64 ~
> $ cat MyProject2/.git/config
> [core]
>         repositoryformatversion = 0
>         filemode = false
>         bare = false
>         logallrefupdates = true
>         symlinks = false
>         ignorecase = true
> [remote "origin"]
>         url = https://redacted.com:7443/some/path/MyProject.git
>         fetch = +refs/heads/*:refs/remotes/origin/*
> [branch "master"]
>         remote = origin
>         merge = refs/heads/master
> [lfs "https://redacted.com:7443/some/path/MyProject.git/info/lfs"]
>         access = basic

`

**Comment by bk2204** [comment]
What happens when you connect to the LFS server for a batch request is that it provides additional URLs for each of the things to download. This differs from Git where all of the data is sent over a single connection. I suspect what's happening is that when you connect to the LFS server, the URLs that the server provides you are not specified over port 7443.

You can confirm this by running `GIT_TRACE=1 GIT_TRANSFER_TRACE=1 GIT_CURL_VERBOSE=1 git lfs clone` and then your remote URL. Git LFS doesn't provide a way to override this functionality, since there isn't a generally applicable way of doing so that works for all users, and there are lots of places where such an option, even if it existed, would not work correctly.

The only thing I can suggest is that you could try installing a proxy on the local machine (and configuring it using the environment variables "http_proxy" and "https_proxy") that maps requests to port 443 to use port 7443 instead. I'm sorry I don't have a more helpful solution for this case.
