### ISSUE TITLE
Git submodule update downloads all files instead of just the references

### ISSUE THREAD

**Issue by betasix** [git-lfs/git-lfs#3536]
Hey there

sorry if this is a stupid question/bug report but I'm fairly new to git lfs. I'm having a repository which has a git lfs as a submodule. I expect the lfs submodule to only fetch the references instead of all the file's content when doing a git submodule update in a freshly cloned repo. I already added the following lines to my .gitconfig file without success.

[lfs]
fetchexclude = *

Regards

**Comment by bk2204** [comment]
Hey, sorry to hear you're having trouble.

By default, Git LFS will download and check out the LFS files when you perform a checkout (whether that's due to a clone or otherwise). This is because Git asks Git LFS to smudge the pointers into objects.

If you don't want that behavior, you have a couple of options. You can use `git clone --no-checkout`, which will prevent things from being checked out. You can also set `GIT_LFS_SKIP_SMUDGE=1` when cloning, which prevents Git LFS from checking out files, and then run `git lfs checkout` when you're ready to work with the large files. And finally, you can set the `filter.lfs.smudge` and `filter.lfs.process` config options to use the `--skip` flag, which does the same thing as `GIT_LFS_SKIP_SMUDGE`.
