### ISSUE TITLE
Is it possible to use lfs migrate import --fixup to retroactively convert an entire repository to LFS?

### ISSUE THREAD

**Issue by duclong793** [git-lfs/git-lfs#3543]
Hello,

I'm currently trying to converting alot of files types in a non-LFS repository to LFS and wanted to ask if it is possible to use a pre-made `.gitattributes` file to use in combination with `git lfs migrate import --fixup` to convert all including file types in the `.gitattributes` file to LFS. My main intention is to avoid using `git lfs migrate import --everything --include="[all file types]"` as I'd like to use the gitattributes file that I have made already. From the documentation it seems to me that the flag `--fixup` would do just that, but I my first attempt didn't result in any changes that could be pushed.

Here is the attempt that I have tried:
1) Make .gitattributes file with all tracked filetypes and put into root of repository
2) Commit said .gitattribute file
2) Run `git lfs migrate import --everything --fixup`
3) After completion my repository looked excatly the same

Thank you in advance!

**Comment by ttaylorr** [comment]
Hi @duclong793, thanks for opening this issue and sorry that it took us a little while to get back to you.

I think that your usage here is mostly correct, but `--fixup` isn't working quite like how you think it is. `--fixup` works by making the repository match its .gitattributes files at each discrete point in history. Since you're adding the `.gitattributes` file at the most recent point in history, `git lfs migrate --fixup` isn't doing anything for most of the time.

I think that there are two things that you could do instead:

1. Instead of `--fixup`, you could give explicit `--include` and `--exclude` arguments, and have Git LFS create your `.gitattributes` file for you. You note that you don't want to use this option, but it should be fine in practice: Git LFS will modify your .gitattributes, but not in a way that's redundant (e.g., if the entries we'd like to add are already present, then Git LFS will do nothing).

2. Alternatively, you could move the commit that introduces the .gitattributes earlier in history with a `git rebase`, and _then_ run `git lfs migrate --import --everything`. Since the `.gitattributes` changes you're introducing would be present earlier, `--fixup` _would_ convert the files that you want.

Let me know if that doesn't quite get everything working for you, and post another comment here if that's the case. Since I'm pretty sure that this should get you going again, I'm going to close this issue for now.

**Comment by norru** [comment]
Why was this closed? Has anyone tested the suggestion above? I have tried and what I get is a failed rebase, with lots of "Encountered xx file(s) that should have been pointers, but weren't:"

**Comment by vivi90** [comment]
> Hi @duclong793, thanks for opening this issue and sorry that it took us a little while to get back to you.
> 
> I think that your usage here is mostly correct, but `--fixup` isn't working quite like how you think it is. `--fixup` works by making the repository match its .gitattributes files at each discrete point in history. Since you're adding the `.gitattributes` file at the most recent point in history, `git lfs migrate --fixup` isn't doing anything for most of the time.
> 
> I think that there are two things that you could do instead:
> 
>     1. Instead of `--fixup`, you could give explicit `--include` and `--exclude` arguments, and have Git LFS create your `.gitattributes` file for you. You note that you don't want to use this option, but it should be fine in practice: Git LFS will modify your .gitattributes, but not in a way that's redundant (e.g., if the entries we'd like to add are already present, then Git LFS will do nothing).
> 
>     2. Alternatively, you could move the commit that introduces the .gitattributes earlier in history with a `git rebase`, and _then_ run `git lfs migrate --import --everything`. Since the `.gitattributes` changes you're introducing would be present earlier, `--fixup` _would_ convert the files that you want.
> 
> 
> Let me know if that doesn't quite get everything working for you, and post another comment here if that's the case. Since I'm pretty sure that this should get you going again, I'm going to close this issue for now.

The is a mistake:
Needs to be `git lfs migrate import --everything` instead of `git lfs migrate --import --everything`.

**Comment by RuRo** [comment]
> There is a mistake:
> Needs to be `git lfs migrate import --everything` instead of `git lfs migrate --import --everything`.

This doesn't help. The rebase that pushes the commit earlier in the repository history is failing before the `git lfs migrate` command is run. So it doesn't matter what arguments it has.

**Comment by bk2204** [comment]
It's possible that in your particular situation, the rebase is failing, but in general, it need not fail and the answer is correct.  If you're having some trouble, feel free to open a question on the Discussion page with the relevant information and we'll try to help out.

**Comment by RuRo** [comment]
```sh
# Make some fake history
git init .
touch README.md && git add README.md && git commit -m "initial commit"
echo "1" > 1.txt && git add 1.txt && git commit -m "1.txt"

# Pretend 2.dat contains binary data
echo "2" > 2.dat && git add 2.dat && git commit -m "2.dat"
echo "changed" > 2.dat && git add 2.dat && git commit -m "2.dat (changed)"
```

Now lets say, that I want to rewrite the commit history (migrate), starting from the commit that introduced `2.dat` so that `2.dat` is tracked under LFS (and I already have a `.gitattributes` file which I want to be the result of this history rewrite). This seems to be exactly the use case, which OP described.

Now, since I want to use my `.gitattributes` file instead of `--include`/`--exclude`, I will try to follow the instructions provided by ttaylorr and vivi90 (the second option).

```sh
echo '*.dat filter=lfs diff=lfs merge=lfs -text' > .gitattributes
git add .gitattributes
git commit -m "the commit that adds .gitattributes"
```

> move the commit that introduces the .gitattributes earlier in history with a `git rebase`

But attempting to rebase the commit fails with
```
Encountered 1 file(s) that should have been pointers, but weren't:
	2.dat
```

And as OP mentioned, running `git lfs migrate import --fixup` before rebasing literally doesn't do anything.

---

To be honest, I don't really understand, what is the supposed correct usage for `git lfs migrate import --fixup`. Based on the `man` pages and all the explanations, it seems like `git lfs migrate import --fixup` only actually does something, if you have a git repository in an invalid state (there are files, which should have been tracked according to `.gitattributes`, but aren't).

But from my experiments, it's almost impossible to actually get your history into this state without getting "stuck" since almost every operation that touches such files or commits instantly fails with `Encountered X file(s) that should have been pointers, but weren't`.

Also, if you get this error while doing something (say during a `rebase`/`merge`), it's really hard to get yourself into a valid state again without aborting whatever you were doing since you can't `reset` or `checkout` it to a "clean" state.

---

I think, that I was able to do what I was trying to do by performing a manual `filter-branch` and then a `git lfs migrate import --fixup` (similar to what was described in [this comment](https://github.com/git-lfs/git-lfs/issues/3442#issuecomment-579082902)), but that was a really ugly solution for what should have been a trivial operation IMO.

**Comment by bk2204** [comment]
Yes, you need to also do `git add --renormalize .` when that happens and then amend the commit.  That's why I would suggest using the `--include` and `--exclude` options in this case because they're much easier to use.  `--fixup` is useful for the scenario where people have checked in files that are listed in `.gitattributes`, but it's not a great option for other uses.

**Comment by RuRo** [comment]
`git add --renormalize .` still doesn't solve the problem. Try it on the example, that I provided. It "fixes" the first `1.dat` commit but then trying to apply `2.dat (changed)` on top of that results in a merge conflict like so:
```
<<<<<<< HEAD
version https://git-lfs.github.com/spec/v1
oid sha256:53c234e5e8472b6ac51c1ae1cab3fe06fad053beb8ebfd8977b010655bfdd3c3
size 2
||||||| parent of fd70e94 (2.dat (changed))
2
=======
changed
>>>>>>> fd70e94 (2.dat (changed))
```
and `git add --renormalize .` doesn't do anything.

Using `--include`/`--exclude` is a pain at best and doesn't work at worst (unless I am misunderstanding something). What if I need my `.gitattributes` to be in a subdirectory? What if I don't want to rewrite the whole history, but only the part that introduced the files which should be tracked? Changing the root commit is waaaay more intrusive compared to a regular history rewrite.

**Comment by nikolay-pv** [comment]
Just leaving it here for anybody who follows. Try disable lfs at all `git lfs uninstall` rebase the branch, then enable it again with `git lfs install`, then run `git lfs migrate import --fixup` (at this point the `.gitattributes` will be in the past and the history should change)

----
For full info.
I needed to integrate a history of say `repoB` into `repoA`, where `repoA` has lfs enabled (and `repoB` doesn't but has some files which should be tracked).
I tried repeatedly to rebase the orphan branch but got the errors of "should have been pointers", and since the to-be-rebased branch had 700 commits, resolving conflicts wasn't an option.
 
It seems the `--fixup` option can be use like this:
* run `git lfs uninstall` - disable lfs integration
* clone `repoA`
* add `repoB` as a remote and fetch the main
* remove the `repoB` remote and `origin` (can be added later)
* rebase normally - here lfs is not in play and no conflicts happen
* now assuming `repoA` has `.gitattributes`, the `git lfs migrate import --fixup` called while in the rebased branch will do the right thing and migrate all the binaries to pointers in the current branch
* run `git lfs install` to restore
* work with the branch as usual

I assume the same trick with disabling / enabling the whole lfs integration can fix the rebase suggested as a solution above.

**Comment by jon-eric** [comment]
These comments helped me a lot! I used `filter-branch` instead of `rebase`, as [suggested by this answer](https://stackoverflow.com/a/42343830/99377).

1. First use **`--index-filter`** to add .gitattributes to each commit:
`git filter-branch --index-filter "cp /abs/path/to/.gitattributes . && git add .gitattributes" --tag-name-filter cat --prune-empty -- --all`
2. Then use **`--fixup`** to convert to lfs according to .gitattributes:
`git lfs migrate import --fixup`

**Comment by Kaspazza** [comment]
> These comments helped me a lot! I used `filter-branch` instead of `rebase`, as [suggested by this answer](https://stackoverflow.com/a/42343830/99377).
> 
> 1. First use **`--index-filter`** to add .gitattributes to each commit:
>    `git filter-branch --index-filter "cp /abs/path/to/.gitattributes . && git add .gitattributes" --tag-name-filter cat --prune-empty -- --all`
> 2. Then use **`--fixup`** to convert to lfs according to .gitattributes:
>    `git lfs migrate import --everything --fixup`

Now instead of filter-branch, the filter-repo is suggested to use.
So, if anyone is wondering how to write this command in filter-repo, here it is:

`git filter-repo --force --commit-callback "if not commit.parents: commit.file_changes.append(FileChange(b'M', $RELATIVE_TO_PROJECT_ROOT_PATHNAME, b'$(git hash-object -w $FILENAME)', b'100644'))"
`

**Comment by meruiden** [comment]
This worked for me

``` bash
HASH=$(git hash-object -w "$(pwd)/.gitattributes")
git filter-repo --force --commit-callback "commit.file_changes.append(FileChange(b'M', b'.gitattributes', b'${HASH}', b'100644'))"
``` 

note that this uses pwd. so cd to where .gitattributes is located. and then run this
