### ISSUE TITLE
Smudge Error: Object does not exist on server [404] - object is definitely visible in LFS file list

### ISSUE THREAD

**Issue by darbotron** [git-lfs/git-lfs#3544]
Hi

We're currently unable to pull from our bitbucket repo because we're getting an error when Sourcetree calls git-lfs filter-process.

The file OID it claims it can't download is clearly visible in the LFS files section of the repo's settings and if I manually download it by clicking on the arrow next to its OID then rename it the file seems to be fine.

Running the git commands which are shown when choosing the "find local references" causes the following output:
`$ git log -p --all -S fd365de7ea55b95a3fc9f0e23939fa3fc4779fb33b5b64edac75b93878 f06325
commit b3fe4c9c3fab772610b97b29346219365a2ae8b9
Author: XXXXX
Date:   Sun Feb 17 23:23:51 2019 +0000
added dirt parameters to player car windows
diff --git a/RoadTrip/Assets/RoadTrip/Meshes/Vehicles/vehi_PlayerCar01.fbx b/RoadTrip/Assets/RoadTrip/Meshes/Vehicles/vehi_PlayerCar01.fbx
index 9a115bb..587c111 100644

--- a/RoadTrip/Assets/RoadTrip/Meshes/Vehicles/vehi_PlayerCar01.fbx
+++ b/RoadTrip/Assets/RoadTrip/Meshes/Vehicles/vehi_PlayerCar01.fbx
@@ -1,3 +1,3 @@
version https://git-lfs.github.com/spec/v1
-oid sha256:372221a0e53ca8fec7b000ac61c254b5dd50cd49bfe9c4ead57ce93093d77dc3
-size 3839200
+oid sha256:fd365de7ea55b95a3fc9f0e23939fa3fc4779fb33b5b64edac75b93878f06325
+size 3839360`

I tried updating to the latest version of Sourcetree, and the latest embedded git / git LFS and it still gives the same error. I have also tried it both with and without "Enable the Bitbucket LFS MEdia Adapter" checked and I get the same result.

I use SSH but most other people on the project use HTTPS.

Here's the latest log [20190225T111620.964857.log](https://github.com/git-lfs/git-lfs/files/2900273/20190225T111620.964857.log)

What workarounds are there for this situation?

e.g. is it possible to: 
roll back the LFS link on the server's repo?
find out why it's not downloading?
pull everything except the problem problem file then replace it in a merge so I can keep working?

**Comment by bk2204** [comment]
Hey, sorry to hear you're having trouble.

This message from the server means that you are missing one of the LFS objects on your client and the server doesn't have it either.

I'm not that familiar with SourceTree, but if what it's telling you is that you (or someone else) have this object locally, you can push it to the server by using a command like `git lfs push --all origin` (if your LFS remote is `origin`). However, the fact that you're getting this message usually means you don't have the object, so you should see if you can find someone else who does have the object and have them push it.

I don't know about Bitbucket, but some server implementations prevent you from pushing if you haven't uploaded all the objects you need. If Bitbucket is like this, then your object is likely somewhere and the server is having trouble finding it, in which case I'd recommend reaching out to Bitbucket support.

You can roll back the LFS link by rewriting the history not to include that commit and force-pushing it. Unfortunately, due to the way that checkouts work, it's not possible to do a partial checkout. You can run with `GIT_LFS_SKIP_SMUDGE=1` to prevent Git LFS from checking out files and then replace it if you like. However, if you do so and you don't recover the object, then it won't be possible to check out the revisions which had the missing file.

**Comment by darbotron** [comment]
Thanks for getting back to me - am now bothering bitbucket's support people... 

I actually found this when googling for the smudge error & just posted without looking into it properly - my bad! ;)
