### ISSUE TITLE
gitobj: no such object

### ISSUE THREAD

**Issue by jonathan-koppenhaver** [git-lfs/git-lfs#3553]
I'm trying to migrate an existing Git repository to LFS, using self-hosted Bitbucket as the host and Artifactory via SSH for LFS storage. I'm running an import command that looks like this:
`git lfs migrate import --everything --include="*.exe,*.a,*.so,*.dll,some/path/**"`
The real version includes ~50 file types and a few paths.

The import gets through `sorting commits` and about 30% through `migrating commits` (out of about 140k commits) before it fails with `gitobj: no such object {hash}`.

I tried running import with `GIT_TRACE=1` but the output isn't telling me much - prior to the error is just a long list of 
`trace git-lfs: filepathfilter: rejecting "filename" via [*.exe *.a *.so {other-paths}]`

To confirm my Artifactory configuration, I created a new repo with the same `.lfsconfig` and was able to successfully upload a couple files to Artifactory via `git lfs push origin master`.

I'm using Git version 2.21.0 and Git LFS version 2.6.1.

Do you have any suggestions for diagnosing this problem further?

Thanks for your time.

**Comment by Abakajerom** [comment]
Not yet

**Comment by bk2204** [comment]
This error message usually means that we can't find one or more of the Git objects that we're looking for. This could mean that there's an issue with your repo. Can you try running `git fsck` to see if it thinks that your repository is in a good state?

Also, are you using any uncommon features, like multi-pack index, that change the way objects are stored?

**Comment by Abakajerom** [comment]
No

**Comment by ttaylorr** [comment]
> This error message usually means that we can't find one or more of the
> Git objects that we're looking for.

I had started to write a comment about how it would be nice if we could
handle this case better by e.g., "migrating" a tree who has missing
entries, so long as they aren't matched by the given '--include' and
'--exclude' flags.

But in fact, when I looked in Git LFS's git/githistory/rewriter.go to
start writing a patch to that effect, I discovered something curious.
In fact, this _is_ what we do for objects that don't match the
`--include` or `--exclude` paths given. In particular, we write:

  if !r.allows(entry.Type(), fullpath) {
    entries = append(entries, copyEntry(entry))
    continue
  }

Before even trying to open the blob or sub-tree, which is where we'd
find the missing error!

So, I think with that out of the way (and since we log the SHA-1 of the
missing object under consideration), this is likely an issue with your
copy of the repository missing objects, and I think that Git LFS handles
it sufficiently.

**Comment by jonathan-koppenhaver** [comment]
Thanks for looking into my issue. After 2 straight weeks of failures, the conversion process has been working flawlessly since @bk2204 responded. I wish I knew better what my problem actually was caused by, but I agree that the issue was likely on my end somewhere. Somehow @bk2204 managed to scare my hardware straight, so I appreciate that.

**Comment by bk2204** [comment]
I'm glad things are working for you now. This is not the first time I've looked into a problem and suddenly things start working, but if that means you can get your repository migrated, then that's great.

If it turns out we have an issue here nevertheless, please feel free to reach out.

**Comment by stefanzugal** [comment]
We are currently migrating our svn to git - and stumbled over this issue. It seems that our issue was that we used the BFG repo cleaner (https://rtyley.github.io/bfg-repo-cleaner/) for removing unwanted file, and then run `git lfs migrate` right away. From what I read in the comments, this might have somehow damaged the repository (?) and running the following command - between cleaning the repo with BFG repo cleaner and before running `git lfs migrate` resolved the problem:

`git reflog expire --expire=now --all && git gc --prune=now --aggressive`

I thought this might be helpful for other people, so I added the comment here (it was the first hit on Google).
