### ISSUE TITLE
LFS looks in the working directory for other commit pointer queries

### ISSUE THREAD

**Issue by mathstuf** [git-lfs/git-lfs#3557]
Originally [a comment](https://github.com/git-lfs/git-lfs/issues/1113#issuecomment-366791563) on #1113 which was closed by #3398. Opening a new issue for proper tracking.

> I think the core issue is that LFS is trying to read from the disk (working tree) when looking at a given hash. There's no guarantee that the observed hash is currently checked out. Git-lfs should query the index or relevant tree object for the content of the file.

Cc: @ttaylorr

**Comment by bk2204** [comment]
We only look at the working tree if we don't already have a copy of the LFS object. The alternative is to simply fail if the user is lacking the object in the LFS storage.

I did open #3468 so that we don't need to upload files we know the server already has, which means that this case will be triggered less often. However, if the user lacks the object still, then they'll need to download it from somewhere else by running `git lfs fetch --all` before pushing.

**Comment by mathstuf** [comment]
Ah, OK. Looking at #3398's diff closer, it seems the error message improvement should help avoid the confusion (had to deal with this again yesterday hence the activity). I'll suggest LFS upgrades in the future. #3468 would indeed solve the problem as far as I'm concerned. Thanks.
