### ISSUE TITLE
Newly initialized clone doesn't install LFS

### ISSUE THREAD

**Issue by rcdailey** [git-lfs/git-lfs#3558]
I switched a submodule of mine to a new URL which uses LFS. When I `git submodule update --init` that new submodule, it only pulls down the LFS reference files, but not the actual binary files. Is this because `git lfs install` has to be run in the submodule first? Why doesn't this happen automatically for submodules in existing clones? How do I solve this problem?

Apologies for the question, I'm still fairly new to Git LFS.

**Comment by rcdailey** [comment]
Yeah the more I read about `git lfs install`, the more confused I get. Apparently a lot about LFS has changed in the past 2-3 years so there's a lot of dated information.

Seems like users are required to run `git lfs install` per-repository to install the hooks. Is there no way to automate this? Git LFS breaks all my CI/CD build scripts and I have to add special checkout/submodule update logic because the hooks are not automatically present when submodules are cloned (`submodule update --init`).

**Comment by rcdailey** [comment]
@bk2204 Sorry to ping you, but would love some help on this one if you have a spare few minutes. Thanks !!

**Comment by bk2204** [comment]
Sorry for the delay in responding; I've been out on vacation.

In general, if you have run `git lfs install` at least once for your user and the entries have been added into your `~/.gitconfig`, it should automatically install the hooks for you so that things work. If your situation is CI and CD, it may be useful to run `git lfs install --skip-repo` before the checkout stage, since that will install the filters on a per-user basis and make sure that the hooks are installed in the repo.

Whether your particular CI or CD system allows you to do that is another question. Some systems recognize Git LFS and will already be configured to do the right thing, and others may require some manual configuration.
