### ISSUE TITLE
Authentication without git lfs server

### ISSUE THREAD

**Issue by sebhahn** [git-lfs/git-lfs#3566]
Is there any other way than using a git lfs server to manage/setup the authentication on a git bare repository hosted on e.g. a webserver?

My use case is hosting large test files on a webserver, which are downloaded/used during CI on Github/Travis. I started setting up a bare git repository on the webserver (also using `git lfs install`) which I've mounted locally before. However, after cloning the remote using a local path (i.e. `git clone /path/to/bare.git`) pushing fails with the message: `batch request: missing protocol: "/path/to/bare.git/info/lfs"`. Going through the documentation it seems a git lfs server is needed managing https authentication, but is there any other way to solve this problem?

**Comment by bk2204** [comment]
Hey, thanks for writing in.

Git LFS needs a server not so much to manage authentication but to manage the LFS protocol, which uses HTTP to upload and download the files. Usually authentication will be involved, but it need not be if you're using a custom server that doesn't need it.

There are two potential ways to work with your current setup. First, you can use `git clone --shared`, which will clone a shared repository, which will copy or reference the LFS objects. Second, you can use a custom transfer adapter to clone from a local URL or using a protocol other than HTTP.

Note that either way, if you're using a local URL, you'll need to specify the URL using the `file:///` protocol instead of specifying a bare path. Because Git LFS discovers the URL to work with by modifying the URL provided, what you provide to Git must actually be a URL instead of a bare path.

**Comment by sebhahn** [comment]
Thanks a lot for the explanation, but what is a custom transfer adapter? Basically I'd like to avoid other people pushing whatever they want on the public bare repository. Is this the case for option one and two? 

I guess the `file:///` protocol is defined on the client side?

**Comment by bk2204** [comment]
The `file:///` protocol is just the standard nomenclature for files on the local system. Git LFS only handles full URLs because we use Go's URL handling library.

When you use `git clone --shared`, you cannot push objects to the remote, only read objects. It does require that the original be present as long as the clone is present, since the Git portion uses alternates. This will prevent anyone from using this to push.

If you want to use a custom transfer adapter, we have [documentation on the protocol](https://github.com/git-lfs/git-lfs/blob/5b92bc4743a3bab3b7c921eebf31de769bfc66a8/docs/custom-transfers.md). It basically consists of making a custom tool that understands the Git LFS protocol and uses something other than the standard HTTPS API. Whether a user can push depends on your custom transfer tool and whether you choose to implement pushing or access control for it.
