### ISSUE TITLE
git lfs locks returns user IDs rather than usernames

### ISSUE THREAD

**Issue by CianNoonan** [git-lfs/git-lfs#3578]
When running git lfs locks to see which files are locked by who in the repo I am given the following rather than a username: 
`Github User XXXXXXX`

Is there a config I'm missing to have this display actual usernames?

**Comment by bk2204** [comment]
Hey, thanks for writing in.

The name of the user here comes entirely from the server side and as such is entirely up to what the server provides. When I create a lock, it shows me as “bk2204”, and I think it should typically do that for most users, although it's possible that if the user can't be looked up for some reason, then the server would return a user ID. Since this is a GitHub issue, and not an issue with the Git LFS client, it's best to reach out to support@github.com about this so they can figure out what's going on and help you or open an internal issue if necessary.

**Comment by CianNoonan** [comment]
Thanks for taking the time to respond bk2204

**Comment by bk2204** [comment]
Sure, happy to do it. Sorry I couldn't be of more help.

**Comment by jurcaua** [comment]
Hey @CianNoonan! 

Did you end up fixing this issue? 
Did you end up going through support or was there some local configuration you were able to do to fix this?

Running into the same issue currently...

**Comment by CianNoonan** [comment]
There was some rest call we could make to retrieve the name from the ID, I'll drop a code snippet when back on my pc

**Comment by CianNoonan** [comment]
`        static async Task<string> GetUsernameByID(string userId)
        {
            var uri = new Uri($"https://api.github.com/user/{userId}");

            using (var hc = new HttpClient())
            {
                hc.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));
                hc.DefaultRequestHeaders.TryAddWithoutValidation("User-Agent", "http://developer.github.com/v3/#user-agent-required");

                var resultTask = await hc.GetStringAsync(uri);
                if (!string.IsNullOrEmpty(resultTask))
                {
                    dynamic githubUser = JObject.Parse(resultTask);
                    return (string)githubUser.login;
                }
                else
                {
                    return userId;
                }
            }
        }`

JObject is Newtonsoft, basically, I'm just receiving a json object and parsing it and reading "login". You could manually define the schema of the object and parse it normally.

**Comment by jurcaua** [comment]
I see, thanks for sending this over! I'm currently waiting on some support from Github as well, but looks like we'll need to do something on our side as well in the meantime... appreciate the help (even though this was so long ago 😝)!!
