### ISSUE TITLE
Can't lfs install if repo contains git.js file

### ISSUE THREAD

**Issue by PavelAleksandrovMSK** [git-lfs/git-lfs#3580]
I've repository, which contain a lot of files and one of them calls <Git.JS>
When i run "GIT LFS INSTALL" i see "Error getting git version: fork/exec git.js: %1 is not a valid Win32 application."

OS Windows 10
git version 2.21.0.windows.1
git-lfs/2.7.1 (GitHub; windows amd64; go 1.11.5; git 6b7fb6e3)
So, i'm unable to use LFS in the repo.
Maybe someone knows, how to work with that, cause i can't remove git.js file

**Comment by bk2204** [comment]
Hey, sorry to hear you're having trouble.

It looks like what's happening here is that Windows thinks that `Git.JS` is potentially an executable file of some sort. It's my understanding that on Windows, when trying to run a command, if it looks like there's an executable in the current directory that has an appropriate name, it runs that command, even if the current directory is not in `PATH` or is later in `PATH`. I don't believe this behavior can be overridden, unfortunately.

We can't fix this by using an absolute path because we don't know where the user will have installed Git. They could be using Git for Windows, Cygwin, MSYS, or some other configuration, any of which could be installed in virtually any directory.

My recommendation here is that you use `fsutil` to mark the directory as case-sensitive, which means that `Git.JS` will no longer match `git`; remove the association for `.js` files that makes Windows think they're executable; work from a different directory in this repo; or use Windows Subsystem for Linux to edit this project, since it won't have this behavior.

It is theoretically possible for us to update Git LFS to use `git.exe` when invoking Git on Windows instead of plain `git`, but I'd very much prefer not to do that. Doing so prevents people from overriding `git` with a script that may meet their needs better than the standard binary, and it also introduces a potentially sharp edge case that we'll have to carry in the code.

**Comment by PavelAleksandrovMSK** [comment]
Hey!
Thank you for quick reply.
I've made folder as case-sensitive and everything works fine! But then i've faced problem when my TFS was trying to get source with "Checkout files from LFS" parameter (cause its getting files to another random build machine)
Doesn't matter.
And FYI, if i put this Git.JS file into subfolder, everything works correctly, its just if someone will face the same troubles.
Anyway, thank you for your help!
