### ISSUE TITLE
Pull error

### ISSUE THREAD

**Issue by rock420** [git-lfs/git-lfs#3581]
$ git lfs pull
Could not pull

Errors logged to C:\Users\DELL\.git\lfs\objects\logs\20190328T212413.7886684.log
Use `git lfs logs last` to view the log.

-----I am getting this error when trying to pull a large file, anyone can please suggest how to resolve this issue?

**Comment by bk2204** [comment]
Hey, thanks for writing in and sorry you're having trouble.

Could you provide the output from that log file? Also, are you on a branch, or on a detached head? This message means we can't resolve the HEAD reference, which is generally a bad sign. Does running `git fsck` indicate anything other than dangling objects?

**Comment by rock420** [comment]
![2019-03-29 (1)](https://user-images.githubusercontent.com/35620678/55186999-f1dd6d00-51bd-11e9-8dea-881e302b496d.png)

I think the problem is due to the HEAD reference. please suggest how to resolve it.

**Comment by bk2204** [comment]
It sounds like currently you've checked out a branch which doesn't have any commits (`master`, in your case). Due to the way `git lfs pull` works, it requires a branch with commits, since it has to download LFS objects for the current branch (or other ref). If there are no commits, then there can be nothing for `git lfs pull` to do, since there will be no LFS objects to pull.

You can check out a branch with commits (e.g. `git checkout another-branch`) or otherwise get commits onto your current branch (e.g. `git merge origin/master`), and then `git lfs pull` will work.
