### ISSUE TITLE
Clone appears to hang: username prompt is invisible

### ISSUE THREAD

**Issue by cowlinator** [git-lfs/git-lfs#3585]
We are using github enterprise as the git remote repo, but we are using artifactory "on prem" as the lfs file storage server.

When cloning the repo, the clone appears to hang after the "checkout" phase is complete.

I discovered that it is actually asking the user for their credentials for artifactory, but the prompt is invisible (blank).

Here is some example output:
```
C:\Temp>git clone https://github.[REDACTED].com/org/repo.git .
Cloning into '.'...
Username for 'https://github.[REDACTED].com': me
Password for 'https://me@github.[REDACTED].com':
remote: Enumerating objects: 31, done.
remote: Counting objects: 100% (31/31), done.
remote: Compressing objects: 100% (30/30), done.
remote: Total 6140 (delta 2), reused 26 (delta 1), pack-reused 6109
Receiving objects: 100% (6140/6140), 3.26 MiB | 729.00 KiB/s, done.
Resolving deltas: 100% (337/337), done.
Checking out files: 100% (7537/7537), done.com': Checking out files:  12% (949/7537)

```

After typing my username into the blank line after the "Checking out files" line, the clone then correctly prompts for my artifactory password:
`Password for 'https://me@artifactory.[redacted].com':`
and then the clone continues and succeeds.

You can also see that the "Checking out files" line contains the string fragment `.com':`, which I think means that the prompt is being overwritten.

Expected result:
    The user is actually prompted for credentials
Actual result:
    The user is expected to enter credentials with no prompt or indication of any kind.

Windows 10 v1803
git-lfs/2.7.1
git version 2.21.0.windows.1

**Comment by bk2204** [comment]
Hey, thanks for writing in.

This is an interesting interaction that occurs with Git. What happens is that Git performs multiple smudge commands asynchronously, and one of those commands invokes Git LFS, which in turn requests credentials using Git's credential helper. However, the checkout process continues asynchronously, printing more progress.

Unfortunately, there isn't really a good way to handle this on our end. Git is responsible for printing all these messages, but it doesn't know that we'll be asking for credentials. Even if we printed a newline before prompting for credentials, that likely wouldn't fix this problem, since Git would overwrite this data.

You can try using a credential manager instead of having it prompt for a username and password, which will avoid the need for the prompt all but the first time. You can also try cloning with `-q`, which will result in less printing. Other than that, I don't have any suggestions for how to avoid this problem, unfortunately. You could ask Git upstream (or Git for Windows) if they'd be willing to not print the “Checking out files” text in this scenario, and they might be willing to do so.

**Comment by cowlinator** [comment]
Ok, thank you for your help bk2204.  I will close this issue, since it seems to be a Git issue.

**Comment by patricklangsonos** [comment]
I have been trying to work around this with credential managers, and so far not a single person has been able to do it successfully. Everyone is used to doing `git clone` without having to go pre-cache credentials, so it hangs, then they eventually ctrl-c the clone. https://github.com/git-lfs/git-lfs/issues/2834 said this could be fixed in a future release so I'll watch that issue.
