### ISSUE TITLE
Lfs files remain as pointer after clone

### ISSUE THREAD

**Issue by joshcamas** [git-lfs/git-lfs#3589]
I've cloned my repository from github, and no matter what I do, I get this error when I try fetching/pulling all of the large files:
`Object does not exist on the server: [404] Object does not exist on the server`

The files remain as pointers.

I've tried `git lfs install`, `git lfs fetch`, `git lfs pull`, `git lfs fetch --all`, etc.

Any ways I can try to get this working?

**Comment by bk2204** [comment]
Hey, sorry to hear you're having trouble.

This error means that the objects you're trying to pull don't exist on the server. Since you're using GitHub, I'd suggest reaching out to support@github.com to ask them about this. GitHub, as of fairly recently, should reject pushes where the LFS objects haven't been pushed, but it's possible that this was an older repository where that wasn't checked. Regardless, GitHub support would be able to help you better, since this repository is for the Git LFS client and what you're seeing is a server-side issue.

**Comment by joshcamas** [comment]
I would have assumed so, but I'm not sure if this is the case - I had this problem with another clone, and since I had an old clone laying around with the lfs files, I popped them into my local repo, and that seemed to make it work, with no errors about any objects not existing. So I'm not sure if it is a server issue. However I will indeed reach out to GitHub as well. Thank you.

**Comment by bk2204** [comment]
If you have an old clone, you can run `git lfs push --all` with those objects to push them to the remote if they're missing. That's the usual way that this can be fixed.

**Comment by joshcamas** [comment]
Sadly when I try that it results in an error due to changed files, since the old clone is too old now
