### ISSUE TITLE
Pointer spec clarification

### ISSUE THREAD

**Issue by saracen** [git-lfs/git-lfs#3597]
The spec states:
> Lines of key/value pairs MUST be sorted alphabetically in ascending order (with the exception of version, which is always first)

I'm wondering if by alphabetical sorted, the spec means lexicographical or a natural sort order?

I saw this issue of when the "alphabetically sorted" requirement was first discussed (https://github.com/git-lfs/git-lfs/issues/233).

@technoweenie commented that:
> I want different Git LFS implementations to generate the exact same pointer file, such that it hashes to the same Git blob oid

To solve this, it was suggested that inspiration be taken from AWS's RESTAuthentication document, where lexicographic sort order is important so that everybody recreates an identical signature.

However, I think an important characteristic of a Pointer file should be that they're also human readable and easy to understand. Looking at the pointer extension addition, the code only manages to achieve lexicographical order because it is limited to an arbitrary 10 extensions. If it allowed 1 more extension, the current code would sort the extensions in _natural sort order_, breaking the spec requirement and the tests associated with reading those values. If "fixed" (if the requirement is actually lexicographic ordering), the Pointer file would be less human-readable, as extension `ext-10-bar` would appear immediately after `ext-1-foo`. 

The current spec could just be updated to specify that the file is natural order sorted. However, from what I understand, natural sort order is hard to do right? 

I know this isn't _really_ an issue because the extension limit is conveniently 10, but with future additions to the Pointer file, that may not always be the case. An argument could be made that it isn't important that the file is human-readable, but it's difficult to assume that might be the case for future additions.

Maybe sort isn't required? I think the case used to be that order was explicitly defined. The spec already mentions that tools that re-encode the file should leave keys it doesn't understand alone - maybe they could leave the order of keys they don't understand alone too?

**Comment by bk2204** [comment]
Hey,

I think the way I would interpret this is that it should be sorted according to Unicode codepoint value. Since we're using UTF-8, that means that it also sorts by byte value. I realize this makes extensions less human readable, but ideally humans are not reading the pointer files at all. Also, sorting by codepoint has the benefit that it's independent of language, because human-friendly sorting requires a variety of language- and locale-dependent behavior that we don't want to have.

I believe the restriction on the number of extensions is because we currently only check blobs that are 1024 bytes in size or less to prevent having to read and decompress arbitrarily large blobs.

If we handle additional extensions, I think we should fix it such that it preserves the behavior I described above.

Other folks on @git-lfs/core, is this interpretation consistent with your interpretation?

**Comment by saracen** [comment]
It certainly makes it easier for encoders. I was hoping to borrow the pointer format for something similar I'm working on at the moment, but the sorting isn't ideal for me. That's not a concern for git-lfs though :)

> I believe the restriction on the number of extensions is because we currently only check blobs that are 1024 bytes in size or less to prevent having to read and decompress arbitrarily large blobs.

When do arbitrarily large blobs need reading? Are all modified files considered and checked to see if they're pointers during the pre-push step? I'd assumed only files that matched in .gitattributes were considered.

**Comment by bk2204** [comment]
> When do arbitrarily large blobs need reading? Are all modified files considered and checked to see if they're pointers during the pre-push step? I'd assumed only files that matched in .gitattributes were considered.

We scan all small blobs at that stage, and simply skip them if they don't look like pointer files. This is more performant than matching every file (O(n) instead of O(n^2)). Also, technically, it's possible that the user is using a global or system-wide `gitattributes` file that doesn't get checked into the repo, and that's a valid configuration (although, of course, not recommended). Scanning everything that looks like a pointer helps people who may have misconfigured these config files at the expense of not accepting valid pointer files that are not actually for LFS.

**Comment by saracen** [comment]
Thank's for the explanation, I'd never considered `gitattributes` living elsewhere!

> We scan all small blobs at that stage, and simply skip them if they don't look like pointer files. This is more performant than matching every file (O(n) instead of O(n^2)).

You still have to perform a stat call though, right? If so, you still have to check every file, it's just an fstat vs. fopen, fread and fclose. Given only the first line of a file would need to be checked (very few bytes), I wonder how much of a gain there really is in practice.

**Comment by bk2204** [comment]
> You still have to perform a stat call though, right? If so, you still have to check every file, it's just an fstat vs. fopen, fread and fclose. Given only the first line of a file would need to be checked (very few bytes), I wonder how much of a gain there really is in practice.

No, we actually scan from Git itself. First we ask `git cat-file --batch-check` what the name and size are, and if they're small enough, we open and scan the objects to read them. We used to use Git for this entire operation, and Git will give you the entire file even if you want only the first N bytes, so we scan only small files.

**Comment by saracen** [comment]
I see, that makes a lot of sense. Thanks :)
