### ISSUE TITLE
Allow overriding the push remote for LFS

### ISSUE THREAD

**Issue by rcdailey** [git-lfs/git-lfs#3602]
I use the fork/origin workflow. Specifically with Bitbucket, you have to have a premium plan to have enough storage to push LFS files. This means forks do not have any LFS storage space. My workflow right now is:

1. Push incomplete work to my fork using `git push fork --no-verify`
1. Push the LFS files to origin (where we have space for LFS files): `git lfs push origin HEAD`

Similarly, I would like `pull` to always attempt to resolve LFS objects from `origin`, not `fork`. My fork is really just for storing branches, but `origin` should be used for LFS storage (in push *and* pull).

Is there a way to configure Git LFS to work this way? If not, please consider this a feature request! There's really no "good" or even recommended LFS workflow for fork-based development, which is really troubling. This is part of my attempt to come up with something reasonable, given various storage limitations imposed by repository hosts.

**Comment by bk2204** [comment]
Hey, thanks for writing in.

There are a couple of ways you can do this. One is to set the `lfs.url` or `remote.<remote>.lfsurl` option in your Git config, or in `.lfsconfig` in your repo. That will result in Git LFS always pushing to that URL.

Another way is to use `url.<url>.insteadof`. If your URL contains the `/info/lfs` portion (e.g. `https://github.com/git-lfs/git-lfs.git/info/lfs`, then Git LFS will use it to look up the remote, while Git will not, so you'll be able to push your Git objects to a different place than your LFS objects.

Hopefully one of these solutions works for you.

**Comment by rcdailey** [comment]
Thanks for the quick response.

I thought about `lfs.url`, but I didn't like that it makes you repeat the whole URL. If I change my remote URL, that means I also have to update LFS configuration. I'd prefer an approach where I can specify a remote instead of URL. Basically a setting that says "Always push to `origin`".

`insteadof` [doesn't seem to be documented](https://github.com/git-lfs/git-lfs/blob/master/docs/man/git-lfs-config.5.ronn), so I didn't know about that one. The setting confuses me though. Can you give an example of how it works? Is it saying use `<url>` "instead of" the value, which is another URL? And what did you mean by "If your URL contains the `/info/lfs` portion`? Which URL? There's many URLs here, I think, I'm not sure which one  you're referring to each time it is mentioned.

**Comment by rcdailey** [comment]
Oh and to throw another wrench in this, I use `ssh` protocol for all my remote URLs. I cannot use HTTPS. I find that if I ever explicitly specify a URL for LFS, I can't use `ssh` for it. When LFS deduces the proper LFS URL to use on its own, it somehow makes SSH work. I don't know what it does in this case, but it's been hands-free for me. Authentication is going to be a headache I think. If you can shed light on this, that would be helpful as well.

**Comment by bk2204** [comment]
`insteadOf` is a Git feature and so is documented in [the Git documentation](https://git-scm.com/docs/git-config#Documentation/git-config.txt-urlltbasegtinsteadOf). As an extension, we handle rewriting the `/info/lfs` endpoint in preference to the standard Git endpoint (which we also accept). This should also work with SSH as long as you use a remote in the form `ssh://git@github.com/git-lfs/git-lfs.git/info/lfs`.

An example is this:
```
[url "https://github.com/git-lfs/git-lfs.git/info/lfs"]
    insteadOf = https://github.com/bk2204/git-lfs.git/info/lfs
```

Now if I try to push an LFS object to my remote, Git LFS will realize that I should instead push it to the main repository, but my Git objects will still go to my remote, because only the LFS portion of the URL is rewritten.

If I write the following: 
```
[url "https://github.com/git-lfs/git-lfs.git"]
    insteadOf = https://github.com/bk2204/git-lfs.git
```
any attempt to push to my remote will be rewritten (both by Git and Git LFS) to point to the main repository.

I believe the one potential wart with using SSH remotes with Git LFS and rewriting is that we'll attempt to authenticate you using SSH against the original remote instead of the rewritten one. You can try it and see if it works for you; otherwise, you may need to set up HTTPS authentication whether you use URL rewriting or `lfs.url`. I believe Bitbucket should allow you to issue personal access tokens that you can use to access repos.

Unfortunately, we don't have an option to always force a particular remote; you'll have to use some way of specifying a URL if you don't want to use autodiscovery.
