### ISSUE TITLE
How to see the real change after using LFS :-)

### ISSUE THREAD

**Issue by servoz** [git-lfs/git-lfs#3609]
Dear folks

It's not really an issue (rather a question that others might ask themselves, may be ... !).

[I followed the general guide](https://github.com/git-lfs/git-lfs/wiki/Tutorial) to replace large files from our repository ([the data_tests in the popule_mia repository](https://github.com/populse/populse_mia/tree/master/data_tests)).

Everything seems to have worked well, for example, in local,  the command `git lfs ls-files` return all desired files (all in data_tests), and in GitHub part, it is possible to see the tag  **_Stored with Git LFS_** on all desired files (all in data_tests).

However, if I want to see the actual size of the repository in GitHub (with the command  `echo https://github.com/populse/populse_mia.git | perl -ne'print $1 if m!([^/]+/[^/]+/[^/]+?)(?:\.git)?$!' | xargs -i curl -s -k https://api.github.com/repos/'{}' | grep size`) I do not observe a size change. Also, I cloned the new version of our repository, (the one using LFS) and, in local,  by doing the classical linux `du  -s` command I didn't see any change either! !!!

How I can clearly observe a change after using LFS ?

**Comment by bk2204** [comment]
Hey, thanks for writing in.

It looks like the way you migrated the repository didn't rewrite the history of the project. Since this is an open-source project that's already publicly available, that's probably the right move, but that means that all of the history with the large files in it is still present in the repository. If you want to shrink the repository, you'll have to rewrite the history all the way back to the beginning.

As I mentioned above, this is probably fine and not a cause for concern.

**Comment by servoz** [comment]
Dear @bk2204,
Thanks a lot for your very clear answer !

**Comment by francocar** [comment]
Non riesco a scrvere sul telefonino , tu stai bene o hai già preso fuoco
con Notre Dame?

Il Lun 15 Apr 2019, 20:40 brian m. carlson <notifications@github.com> ha
scritto:
