### ISSUE TITLE
error: failed to push some refs

### ISSUE THREAD

**Issue by lvictorino** [git-lfs/git-lfs#3613]
Hey there. I came across several posts about that error message but none fixed mine.
I use a GitLab server that I host on one of my machines... LFS works fine on my desktop computer and on many other machines but on my laptop, and on one of my coworker's computer it's impossible for us to push files. This morning everything worked fine, but now I can't push anymore.

error message is:

```
Fatal error: Server error: https://gitlab.monkeymoon.net/nightcall/nightcall-game.git/gitlab-lfs/objects/3852b7a2af861f452d8dfeead5cf1e469384225a34228a4a591756185fb9c175/765487
Uploading LFS objects:   0% (0/1), 0 B | 15 KB/s, done
error: failed to push some refs to 'git@gitlab.monkeymoon.net:nightcall/nightcall-game.git'
```

I'd like to share the content of `$ GIT_CURL_VERBOSE=1  git push origin lvictorino/integration-test` too, but is there something I'd need to obfuscate first for security?

Thanks for your help.

**Comment by bk2204** [comment]
Hey, thanks for writing in.

The most helpful output would come from `GIT_TRACE=1 GIT_TRANSFER_TRACE=1 GIT_CURL_VERBOSE=1 git push origin lvictorino/integration-test`. If you see any output that contains an `Authorization` header, you'll probably want to obfuscate that, since that will contain credentials that are just Base64-encoded.

**Comment by berrylaw** [comment]
Kevin lee 是我當初識的他嗎？

**Comment by lvictorino** [comment]
Hey @bk2204 thanks for your quick reply.
Here you'll find the output of the `push` command.
Thanks for your help.
[dump_safe.txt](https://github.com/git-lfs/git-lfs/files/3088451/dump_safe.txt)

**Comment by bk2204** [comment]
Thanks for providing that output.

This output shows we're getting a 500 error:

```
> PUT /nightcall/nightcall-game.git/gitlab-lfs/objects/3852b7a2af861f452d8dfeead5cf1e469384225a34228a4a591756185fb9c175/765487 HTTP/1.1
> Host: gitlab.monkeymoon.net
> Authorization: Basic * * * * *
> Content-Length: 765487
> Content-Type: image/png
> User-Agent: git-lfs/2.7.1 (GitHub; windows amd64; go 1.11.5; git 6b7fb6e3)
>
09:42:25.794072 trace git-lfs: xfer: adapter "basic" worker 1 auth signal received
09:42:25.795068 trace git-lfs: xfer: adapter "basic" worker 3 auth signal received
09:42:25.795068 trace git-lfs: xfer: adapter "basic" worker 7 auth signal received
09:42:25.795068 trace git-lfs: xfer: adapter "basic" worker 4 auth signal received
09:42:25.795068 trace git-lfs: xfer: adapter "basic" worker 5 auth signal received
09:42:25.795068 trace git-lfs: xfer: adapter "basic" worker 6 auth signal received
09:42:25.795068 trace git-lfs: xfer: adapter "basic" worker 2 auth signal received
09:42:26.825220 trace git-lfs: HTTP: 500


< HTTP/1.1 500 Internal Server Error
< Content-Length: 2902
< Cache-Control: no-cache, no-store, max-age=0, must-revalidate
< Connection: keep-alive
< Content-Type: text/html; charset=utf-8
< Date: Wed, 17 Apr 2019 07:42:27 GMT
< Expires: Fri, 01 Jan 1990 00:00:00 GMT
< Pragma: no-cache
< Server: nginx
< X-Request-Id: 179250b4-2400-4c9d-b700-300ed61a86f8
< X-Runtime: 0.060360
```

This looks like a server-side issue and the client is just passing it on. Since you're the one hosting the server, I'd definitely look at the logs for the GitLab server and see what's happening when you get this 500 error. It may be worth reaching out to GitLab to see if they can help you track down the issue, or if there's documentation that can provide more insight into what's going on.

I'm sorry I can't be of more help in this situation, but I hope this at least points you in the right direction.

**Comment by lvictorino** [comment]
Don't worry, thanks for your help @bk2204 
I find it weird that every other machines (except 2) can push without any issue :S

**Comment by bk2204** [comment]
I think it may be something related to the file that's being pushed (the type, size, or object ID for it), but that's just a guess.
