### ISSUE TITLE
git lfs install --system returns zero exit code on failure

### ISSUE THREAD

**Issue by r0nw** [git-lfs/git-lfs#3622]
Trying to install LFS system-wide on windows without sufficient access rights fails with reasonable error message, however returns zero exit code. That's a bit unpleasant when one wants to do it in a script.

Git-LFS version: 2.7.1 (included in Git for Windows 2.21.0)

```
C:\>git lfs install --system
WARNING: current user is not root/admin, system install is likely to fail.
WARNING: Error running C:\Program Files\Git\mingw64\libexec\git-core\git.exe 'config' '--system' '--replace-all' 'filter.lfs.required' 'true': 'error: could not lock config file C:/Program Files/Git/mingw64/etc/gitconfig: Permission denied' 'exit status 255'
Run `git lfs install --force` to reset git config.

C:\>echo %ERRORLEVEL%
0
```

A somewhat related cosmetic issue is, that when the access rights are sufficient, it still wrongly prints the warning that they are not, but then succeeds:
```
C:\>git lfs install --system
WARNING: current user is not root/admin, system install is likely to fail.
Git LFS initialized.
```
Observed on Windows 10 1809 x64 & Windows 7 x64, also with Git-LFS 2.7.1.

**Comment by bk2204** [comment]
Hey, thanks for writing in.

I agree that we should be exiting nonzero in the first case. That should be easy to fix. The second case looks to be because `os.Geteuid` returns -1 on Windows, which is not 0. I think it should be fine to simply skip printing that message on Windows, since it's just a warning.

I'll see if I can spend some time fixing those issues.
