### ISSUE TITLE
LFS pre-push hook called with REMOTE-LOCATION REMOTE-LOCATION try to push all LFS files

### ISSUE THREAD

**Issue by anb0s** [git-lfs/git-lfs#3625]
I'm trying to use native git-lfs with JGit (Eclipse) and see that the pre-push hook is called with "REMOTE-LOCATION REMOTE-LOCATION" instead of "REMOTE-NAME REMOTE-LOCATION" like done in native git. See too: https://bugs.eclipse.org/bugs/show_bug.cgi?id=546566

This use case is valid, see https://git-scm.com/docs/githooks#_pre_push
> if a named remote is not being used both values will be the same

The parameters are passed to the hook and inside hook it looks like:
Native Git hook call: `git lfs pre-push origin https://myserver/myrepo.git`
JGit Git hook call:     `git lfs pre-push https://myserver/myrepo.git https://myserver/myrepo.git`

native git trace output:
```
11:06:52.571531 trace git-lfs: exec: git 'version'
11:06:52.688537 trace git-lfs: exec: git '-c' 'filter.lfs.smudge=' '-c' 'filter.lfs.clean=' '-c' 'filter.lfs.process=' '-c' 'filter.lfs.required=false' 'rev-parse' 'HEAD' '--symbolic-full-name' 'HEAD'
11:06:52.785543 trace git-lfs: exec: git 'config' '-l'
11:06:52.832546 trace git-lfs: pre-push: refs/heads/jgit_lfs 73e7e71578ef06082156fcb967d521a712dcf092 refs/heads/jgit_lfs 4b6e83212e9e5caaa7a3bed34de2c35e0ef42d8a
11:06:53.615590 trace git-lfs: tq: running as batched queue, batch size of 100
11:06:53.615590 trace git-lfs: run_command: git rev-list --stdin --objects --not --remotes=origin --
11:06:53.829603 trace git-lfs: tq: sending batch of size 1
11:06:53.829603 trace git-lfs: api: batch 1 files
```

jgit trace output:
```
11:05:12.289795 trace git-lfs: exec: git 'version'
11:05:12.426803 trace git-lfs: exec: git '-c' 'filter.lfs.smudge=' '-c' 'filter.lfs.clean=' '-c' 'filter.lfs.process=' '-c' 'filter.lfs.required=false' 'rev-parse' 'HEAD' '--symbolic-full-name' 'HEAD'
11:05:12.517808 trace git-lfs: exec: git 'config' '-l'
11:05:12.574811 trace git-lfs: pre-push: refs/heads/jgit_lfs 73e7e71578ef06082156fcb967d521a712dcf092 refs/heads/jgit_lfs 4b6e83212e9e5caaa7a3bed34de2c35e0ef42d8a
11:05:13.347856 trace git-lfs: tq: running as batched queue, batch size of 100
11:05:13.347856 trace git-lfs: run_command: git rev-list --stdin --objects --not --remotes=https://myserver/myrepo.git --
11:05:13.408859 trace git-lfs: tq: sending batch of size 100
11:05:13.411859 trace git-lfs: api: batch 100 files
```

You see the difference that `git rev-list` is called with `--remotes=origin` or `--remotes=https://myserver/myrepo.git` parameter.

This causes to transfer `api: batch 1 files` in good case and `api: batch 100 files` in bad case. 

If you try this commands at command line, e.g. here instead of `--stdin` do `git rev-list 73e7e71578ef06082156fcb967d521a712dcf092 --objects --not --remotes=origin --` then it will return the right diff (sha1) with one file.

With `git rev-list  73e7e71578ef06082156fcb967d521a712dcf092  --objects --not --remotes=https://myserver/myrepo.git` it will return the whole history with all commits and try to push all LFS files!

**Comment by bk2204** [comment]
Hey, thanks for writing in.

I think what you're seeing here is a limitation of how Git LFS works. We can ask Git to ignore objects for a given remote if that's a named remote, but there isn't anything we can do for an unnamed remote, because we don't know in the general case what objects are present.

The behavior we have here is correct, but inefficient. The server side should tell us which objects it already has and which it doesn't, so we won't upload the existing files again. Instead, we'll just send potentially multiple large batch requests that consist mostly of files that we won't need to do anything with. Only the single file that requires upload will actually be transferred.

If you want to avoid the multiple batch requests, then you'll need to convince the JGit folks to use a named remote in this case.

**Comment by anb0s** [comment]
Thanks for the explanations, unfortunately this also does not work with native Git and LFS pre-push hook if valid git command with URL instead of remote is used, e.g.:

`git push https://myserver/myrepo.git jgit_lfs`

then it push again all the binary files to LFS server:
```
22:37:39.762959 trace git-lfs: exec: git 'version'
22:37:39.867965 trace git-lfs: exec: git '-c' 'filter.lfs.smudge=' '-c' 'filter.lfs.clean=' '-c' 'filter.lfs.process=' '-c' 'filter.lfs.required=false' 'rev-parse' 'HEAD' '--symbolic-full-name' 'HEAD'
22:37:40.153981 trace git-lfs: exec: git 'config' '-l'
22:37:40.293989 trace git-lfs: pre-push: refs/heads/jgit_lfs 8c8cefc4081980939db8b19306fd7ab0c009f598 refs/heads/jgit_lfs 1e9d7f6b4247807b392e474cc421fce825003fb1
22:37:41.041032 trace git-lfs: tq: running as batched queue, batch size of 100
22:37:41.041032 trace git-lfs: run_command: git rev-list --stdin --objects --not --remotes=https://myserver/myrepo.git --
22:37:41.168039 trace git-lfs: tq: sending batch of size 100
22:37:41.168039 trace git-lfs: api: batch 100 files
```

It looks like this should be fixed in the git-lfs command executed, like `git rev-list` to support remote-URL use cases.

**Comment by bk2204** [comment]
I agree that this also happens when a user uses a URL as a remote. Unfortunately, as I mentioned, this isn't avoidable without trying to autodiscover all existing named remotes and match them to the remote that's being used. Doing so, however, has a large number of pitfalls and problems which make it inefficient and problematic. For example, there are edge cases if the URL given on the command line matches a rewrite rule that applies to a remote; the user may be intentionally ignoring the rewrite rule for a good reason, and matching it would do the wrong thing and not push enough data. Since Git has no data saved for a URL remote, we cannot safely perform the optimization that we do for a named remote.

While we do send large batch requests, the server and client will correctly determine in this case that only one object needs to be uploaded. The batch requests are very small and generally fast to respond to, so while things are not as efficient as they could be if you used a named remote, they are not wildly inefficient.

I appreciate that this is inconvenient, but it is a limitation that also applies to Git and its submodule functionality, which uses the same technique as an optimization. If you think you can come up with an algorithm that is performant, safe, and better than what we have, I'm happy to review a pull request with such a change.

**Comment by anb0s** [comment]
> While we do send large batch requests, the server and client will correctly determine in this case that only one object needs to be uploaded. The batch requests are very small and generally fast to respond to, so while things are not as efficient as they could be if you used a named remote, they are not wildly inefficient.

You talk about the whole push of all files to the server if remote-URL is used? Yes this is maybe not performant, but this also does not work for us, because then it just aborts for first file not in LFS cache. If we use `git lfs fetch --all` then it works, but then we do not need LFS. I think we try to workaround this in Eclipse, but still user can go wrong if he uses the remote-URL...

> I appreciate that this is inconvenient, but it is a limitation that also applies to Git and its submodule functionality, which uses the same technique as an optimization. If you think you can come up with an algorithm that is performant, safe, and better than what we have, I'm happy to review a pull request with such a change.

I'm not familiar with native Git and LFS implementation, i've patched only some simple parts of JGit/EGit, but as a daily user of Git i will try to understand the core problem...

Thank You for your support and explanations!

**Comment by bk2204** [comment]
> You talk about the whole push of all files to the server if remote-URL is used? Yes this is maybe not performant, but this also does not work for us, because then it just aborts for first file not in LFS cache. If we use `git lfs fetch --all` then it works, but then we do not need LFS. I think we try to workaround this in Eclipse, but still user can go wrong if he uses the remote-URL...

We're tracking an improvement to this as #3468, so you need not have files you don't actually need to push.

**Comment by anb0s** [comment]
> I appreciate that this is inconvenient, but it is a limitation that also applies to Git and its submodule functionality, which uses the same technique as an optimization. If you think you can come up with an algorithm that is performant, safe, and better than what we have, I'm happy to review a pull request with such a change.

I've tried following with unnamed-remote and want to ask if it makes sense for Git experts? Thanks in advance.

- check if the first passed parameter is a remote-name, e.g. execute `git remote get-url --push <first-param>`
  - if succeded: it returns the URL (optionally that can be compared to the second-parameter) --> **USE normal behavior** with `git rev-list --stdin --objects --not --remotes=<remote-name> --`
  - if failed: it returns `fatal: No such remote '<remote-location>'` --> **USE new behavior below**

**new behavior**
- use the parameters from the command passed via stdin, see above from log :`pre-push: <local-ref-spec> <local-comit-id> <remote-ref-spec> <remote-commit-id>`
- execute `git rev-list <local-commit-id> --objects --not <remote-commit-id> --`
  - if succeded: you have the same revisions like with named remote --> **DONE :)**
  - if failed: it returns `fatal: bad revision '<remote-commit-id>'` --> **USE new optional fetch**

**new optional fetch**
- may be as opt-in or opt-out (user does not want to fetch, but abort etc.)
- execute `git fetch <remote-location> <remote-ref-spec>`
- execute  `git rev-list <local-comit-id> --objects --not FETCH_HEAD --`
--> **you have the same revisions like with named remote :)**

I've tried it all manually with command line and it worked for tested use cases, like remote-is-up-to date or remote has new commits etc...

**Comment by bk2204** [comment]
Sorry it's taken me so long to get back to this.

I think instead of performing an additional fetch, it would be better to simply not try to push objects that the server already has, which is the issue I mentioned (#3468). I've just pushed up #3634, which implements this. If you could try with that version and see if it works for you, that would be great.

**Comment by anb0s** [comment]
I've tried the version from pull request (replaced only git-lfs.exe), but had no luck, because of other error:
`trace git-lfs: api error: Post <server-URL>/objects/batch: Bad Gateway`
It stops / freezes here, i've to interrupt the process via Ctrl+C.

The new version is: `git-lfs/2.7.0 (GitHub; windows amd64; go 1.12.4; git 8c2764e2)`

If using original version it works until first binary file not found locally: `git-lfs/2.7.1 (GitHub; windows amd64; go 1.11.5; git 6b7fb6e3)`

**Comment by anb0s** [comment]
OK, it looks like also the same `trace git-lfs: api error: Post <server-URL>/objects/batch: Bad Gateway` is reported in the "old" version, but then it continues with `trace git-lfs: tq: sending batch of size 100`...

**Comment by bk2204** [comment]
Yeah, due to the new code, anything that causes a network error during the batch operation is going to cause the process to abort. That's required in order for us to handle this situation cleanly.

Do you know why you're getting a 502 Bad Gateway on the first request?

**Comment by anb0s** [comment]
I've checked out the old traces i made last week and do not see any "Bad Gateway" messages. Something is not working today with our Artifactory server i think, but because of "May 1st public holiday in Germany" i have to wait and try it again tomorrow...

**Comment by anb0s** [comment]
About my proposal from https://github.com/git-lfs/git-lfs/issues/3625#issuecomment-486991669 : is it useful for the valid "pre-push-hook remote-location" use case described in this issue? I think yes, because then we have the right diff before we push to LFS server in case remote is up-to-date. The optional fetch can be added too if configured. Your solution from #3634 is then the needed  optimization if fetch is not wanted or `push -all` used etc. What do you think? Thanks!

**Comment by bk2204** [comment]
My preference is not to add an automatic fetch, because doing so is complex and potentially invasive. It also modifies `FETCH_HEAD`, which users may not want or expect when doing a push, and it potentially ignores the user's desire for different fetch and push remotes (e.g. when a read-only mirror is closer).

I think it's better to try to avoid the need for the fetch altogether in this case by not pushing any LFS objects we don't need. We will still traverse the history, but that's not too terrible.

**Comment by anb0s** [comment]
> Sorry it's taken me so long to get back to this.
> 
> I think instead of performing an additional fetch, it would be better to simply not try to push objects that the server already has, which is the issue I mentioned (#3468). I've just pushed up #3634, which implements this. If you could try with that version and see if it works for you, that would be great.

I've tried the new version with `git push <remote-location>` and it worked! Now it does not abort if file is not available locally and available at server. Thanks!

The only drawback i still see, that it does lot of operations (traversing the whole history) and the run tooks about 40 Seconds (here we have ~ 3600 binaries) to upload only one changed binary file. But as last workaround it's OK for us.

I will need the proposed changes to support the "not named remote" use case without fetch step. I'm new to Go-Language and will try to understand how to start with it and the git-lfs sources.
Please let me know if you want implement this by yourself and have time, or if i should try to do this...

**Comment by bk2204** [comment]
If you wanted to implement an automatic detection of remote, you could do that by seeing if the current remote is a URL and then using the endpoint code to find the push location for each remote and then checking to see if they match and then passing down the remote name to the code that calls `git rev-list`. Note that this should probably be configured behind an option, since as mentioned, it may have side effects.

I don't plan on implementing this, although you are welcome to send a pull request if you like.

**Comment by anb0s** [comment]
> If you wanted to implement an automatic detection of remote, you could do that by seeing if the current remote is a URL and then using the endpoint code to find the push location for each remote and then checking to see if they match and then passing down the remote name to the code that calls `git rev-list`. Note that this should probably be configured behind an option, since as mentioned, it may have side effects.
> 

I understand that we can have side effects and do not want to implement an automatic detection of remote! Please see my proposal that goes to other direction: https://github.com/git-lfs/git-lfs/issues/3625#issuecomment-486991669
 
> I don't plan on implementing this, although you are welcome to send a pull request if you like.

I will try to add this as described in my proposal except the optional fetch step.

**Comment by bk2204** [comment]
Sorry, I misread the proposal. I read "remote-commit-id" as "remote". I think it's fine to implement that; the code you're looking for is this:

https://github.com/git-lfs/git-lfs/blob/fe8f7002c6efb083feadc0a078fa2fbb389127c7/commands/uploader.go#L57-L59

You'll want to replace `ScanLeftToRemote` with something that works a little differently, and remove the function if it's no longer used.

**Comment by anb0s** [comment]
It looks like "named remote for URL" is [merged](https://github.com/git-lfs/git-lfs/pull/4103) :)
Thank You! I will try the JGit use cases with pre-push hook.
