### ISSUE TITLE
git-lfs failed to install due to no Release file.

### ISSUE THREAD

**Issue by aveach** [git-lfs/git-lfs#3630]
Steps to reproduce:
1. Install git-lfs using: `curl -s https://packagecloud.io/install/repositories/github/git-lfs/script.deb.sh | sudo bash`
2. Observe that the install seems to work just fine
3. Run `which git-lfs` and observe it is not found
4. Run `sudo apt-get update` and observe it fails with: 
```sh
W: The repository 'https://packagecloud.io/github/git-lfs/raspbian stretch Release' does not have a Release file.
N: Data from such a repository can't be authenticated and is therefore potentially dangerous to use.
```

Environment:
- Linux 4.14.98-v7+ #1200 SMP Tue Feb 12 20:27:48 GMT 2019 armv7l GNU/Linux
- Raspbian GNU/Linux 9 (stretch)

**Comment by bk2204** [comment]
Hey, thanks for writing in, and sorry to hear you're having trouble.

I think this is because we don't ship any packages for Raspbian. We provide binaries for arm64, but not for 32-bit ARM. Also, since the binaries are built in Docker containers on the maintainers' boxes, we're limited in the ability to build full ARM Debian packages.

I realize this is confusing; the script unfortunately doesn't seem to handle this very well, and it doesn't check that there are packages for an OS before providing the `sources.list` entry. This script is provided by PackageCloud and there's not a lot we can do about this shortcoming.

What I can recommend is using the Debian unstable package archives for this; the Debian maintainer is usually very good about keeping the package up to date (as long as there's not a freeze going on), and there should be `armhf` packages available.

Hopefully this is helpful; sorry again for the confusion.
