### ISSUE TITLE
remote: fatal: ambiguous argument 'origin': unknown revision or path not in the working tree.

### ISSUE THREAD

**Issue by Hemanth211** [git-lfs/git-lfs#3632]
Hi, I'm doing the pre-receive hook, when I create new branch the old rev is 0. When I try to read all the latest commit hashes using this line in python.

new_branch_revs = 'git rev-list origin' + ".." + newrev
all_revs = subprocess.Popen(new_branch_revs, shell=True, stdout=subprocess.PIPE)
new_rev = all_revs.stdout.read().rstrip('\n')

 I'm getting the following exception:

remote: fatal: ambiguous argument 'origin': unknown revision or path not in the working tree.

Please help me where I'm doing wrong.

**Comment by bk2204** [comment]
Hey,

This issue tracker is for the Git LFS project, which is separate from the Git project. We don't really deal with `pre-receive` hooks here, since they're not within the scope of Git LFS. If you have questions about hooks, you can ask on Stack Overflow or ask on the [Git mailing list](https://git-scm.com/community).
