### ISSUE TITLE
I continue to get an error with git lfs where it says it's not installed

### ISSUE THREAD

**Issue by Arniox** [git-lfs/git-lfs#3641]
I have re-built my entire repository 3 times now and recloned over 5 times now to try to wipe any remaining data. Git lfs has been installed and I am tracking a couple of different file types. 

I am able to commit anything small and anything not being tracked but as soon as I try commit and push a large file that is being tracked, such as an mp4, it fails to push and just lfs is not installed when it CLEARLY is. Git lfs status also lets me know it is installed and correctly tracking files that are in need of commit or push.

I'm not sure what's causing it anymore. Plz help.

**Comment by bk2204** [comment]
Hey, sorry to hear you're having trouble.

Can you provide the output you're seeing when the push fails, including setting `GIT_TRACE=1` and `GIT_CURL_VERBOSE=1`, and can you also provide the output of running `git lfs env`? Having that information will help me figure out why things aren't working for you.

**Comment by Arniox** [comment]
Not sure where to set GIT_TRACE=1 and GIT_CURL_VERBOSE=1 but here's some out:

First when running git status with a new file (with one traced mp4 video), then adding the untracked file, and committing, the output works and is so: [1](https://i.gyazo.com/39cd7905fb2c03c7076ca1d3f8830a50.png) and [2](https://i.gyazo.com/7b9bd10884599865b04da7d245e68a58.png)

But as soon as I try to push this, this is one of the outputs I get: [here](https://i.gyazo.com/5fc84c3827cd4eb37baa77cb436b59f4.png)

`git lfs env` output is shown [here:](https://i.gyazo.com/bc2515c005ff952d10f4efe60a0dad26.png)

**Comment by bk2204** [comment]
Hey,

This error message is from the server side, which in this case is GitHub, since it says "batch response". As mentioned [in our troubleshooting documentation](https://github.com/git-lfs/git-lfs/wiki/Troubleshooting#server-side-issues), the best way to get help with server-side GitHub issues is to [contact GitHub's support team](https://github.com/contact). This repository is only for the open source client project and we can't help with server side issues.
