### ISSUE TITLE
What's the point in ref name when deleting a lock?

### ISSUE THREAD

**Issue by slonopotamus** [git-lfs/git-lfs#3645]
[Delete lock](https://github.com/git-lfs/git-lfs/blob/master/docs/api/locking.md#delete-lock) request has `ref` parameter, however I cannot imagine any sensible logic that could use it. When lock was created, it was already created for some ref.

1. What is supposed to happen when you pass a different `ref` in delete request? Must the request be rejected?
2. What is supposed to happen if lock was created with `ref` specified but delete request has `force`=`false` and doesn't specify `ref`? Must the request be rejected?

If both are YES, the only value `ref` is allowed to have in unlock request is the same value it had when lock was created, so why send it at all? Am I missing something?

My suggestion: remove `ref` parameter from delete request.

**Comment by bk2204** [comment]
Hey,

Currently, locks in Git LFS are global: even if a ref is specified, the behavior is that all branches are locked. Consequently, this parameter is currently optional and so can be specified or not specified as the client sees fit. It can be helpful for implementing server-specific policy if that's useful, but is otherwise currently ignored.

Removing the `ref` object as an option would be incompatible with existing clients, so the earliest we could do it would be 3.0. Since it isn't harming anything and can be useful for policy reasons, as mentioned, I think we'll probably leave it.

**Comment by slonopotamus** [comment]
<blockquote>helpful for implementing server-specific policy</blockquote>

As an implementor of LFS server, that's what I am asking about - what kind of  behavior could be done with ref name? "can be useful" is a weak argument, it justifies sending _anything_.

**Comment by bk2204** [comment]
For example, you could require that the user not have any open pull requests related to that branch; if any existed, they'd have to be merged or closed for the lock to be released. This would be useful with large binary assets that can't be merged easily.

The goal is, eventually, to support branch-specific locks, which is why it's there, but as previously mentioned, they're not implemented yet.
