### ISSUE TITLE
git push gets stuck in "waiting for Auth"

### ISSUE THREAD

**Issue by mitar** [git-lfs/git-lfs#3649]
In our CI job pushing git lfs to gitlab LFS-enabled repository we observe that push just hangs. See attached log for details.

I am unable to understand why.

[47400.log.gz](https://github.com/git-lfs/git-lfs/files/3180819/47400.log.gz)

**Comment by bk2204** [comment]
Hey, sorry to hear you're having trouble.

Can you provide the output of `ulimit -a` in this case? Does running `ulimit -n unlimited` fix the problem? We had some problems where running out of file descriptors could cause this in the past, which we should have fixed, but it's possible we missed something.

**Comment by mitar** [comment]
Thanks in taking time to help me. This is output of `ulimit -a`.

```
System info
core file size          (blocks, -c) unlimited
data seg size           (kbytes, -d) unlimited
scheduling priority             (-e) 0
file size               (blocks, -f) unlimited
pending signals                 (-i) 201200
max locked memory       (kbytes, -l) 64
max memory size         (kbytes, -m) unlimited
open files                      (-n) 1048576
pipe size            (512 bytes, -p) 8
POSIX message queues     (bytes, -q) 819200
real-time priority              (-r) 0
stack size              (kbytes, -s) 8192
cpu time               (seconds, -t) unlimited
max user processes              (-u) unlimited
virtual memory          (kbytes, -v) unlimited
file locks                      (-x) unlimited
```

I have now a reproducible environment to play with this. So I can try something else as well.

**Comment by mitar** [comment]
One other system I have `-n` set to `1024` but I succeeded in pushing the same change. So I do not think in this case this the number of files is a problem.

**Comment by bk2204** [comment]
So this is the interesting part:

```
22:57:01.534863 trace git-lfs: xfer: adapter "basic" Begin() with 8 workers
22:57:01.534879 trace git-lfs: xfer: adapter "basic" started
22:57:01.534902 trace git-lfs: xfer: adapter "basic" worker 0 starting
22:57:01.534925 trace git-lfs: xfer: adapter "basic" worker 5 starting
22:57:01.534934 trace git-lfs: xfer: adapter "basic" worker 5 waiting for Auth
22:57:01.534937 trace git-lfs: xfer: adapter "basic" worker 6 starting
22:57:01.534945 trace git-lfs: xfer: adapter "basic" worker 6 waiting for Auth
22:57:01.534949 trace git-lfs: xfer: adapter "basic" worker 7 starting
22:57:01.534955 trace git-lfs: xfer: adapter "basic" worker 7 waiting for Auth
22:57:01.534959 trace git-lfs: xfer: adapter "basic" worker 2 starting
22:57:01.534969 trace git-lfs: xfer: adapter "basic" worker 2 waiting for Auth
22:57:01.534972 trace git-lfs: xfer: adapter "basic" worker 1 starting
22:57:01.534979 trace git-lfs: xfer: adapter "basic" worker 1 waiting for Auth
22:57:01.534983 trace git-lfs: xfer: adapter "basic" worker 3 starting
22:57:01.534990 trace git-lfs: xfer: adapter "basic" worker 3 waiting for Auth
22:57:01.534915 trace git-lfs: xfer: adapter "basic" worker 4 starting
22:57:01.535039 trace git-lfs: xfer: adapter "basic" worker 4 waiting for Auth
```

You'll notice that worker 0 never seems to complete. All workers will wait for worker 0 so that if there's an authentication prompt for whatever reason, only one will be shown. Unfortunately, that doesn't tell us very much about why worker 0 didn't complete; presumably it should have made a batch request, but it didn't. It does mean that we didn't successfully upload at least one byte of data.

Is it possible that something's causing the connection to be closed or that the server's simply not accepting a connection, perhaps due to rate-limiting? One thing I noticed is that the failing push is using a URL as the remote, which can cause a large amount of batch requests to be exchanged with the server. Does this reoccur for you if you use a URL when pushing, and does it go away if you use a named remote?

**Comment by mitar** [comment]
> One thing I noticed is that the failing push is using a URL as the remote, which can cause a large amount of batch requests to be exchanged with the server. Does this reoccur for you if you use a URL when pushing, and does it go away if you use a named remote?

Interesting. I didn't know that there is a difference between pushing to the URI or pushing to the named remote. Why is there a difference?

**Comment by mitar** [comment]
I do not think there is any rate-limit, but I am not sure (it is private gitlab instance).

But using named remote worked!

**Comment by bk2204** [comment]
> Interesting. I didn't know that there is a difference between pushing to the URI or pushing to the named remote. Why is there a difference?

Currently, we traverse the Git entire history if you use a URL as the remote, in order to discover which LFS objects are mentioned and need to be checked for pushing. If you use a named remote, we have an optimization that avoids doing that by using the heads of the remote tracking branches and traverse only the new Git objects that are being pushed. This means fewer LFS objects will be considered, and fewer batch requests will be issued.

Improving this optimization to cover more cases is a thing we'd like to do, and I've opened #3661 to capture this.

**Comment by mitar** [comment]
Interesting. I do not know why many requests are a problem in our case. We had developers complain that sometimes they cannot clone the repo as well, especially if SSH is used. It starts throwing auth issues. I checked and server is returning correct auth tokens with expiration timestamps. So no idea about that as well. It might be some issues with gitlab server side implementation.

Anyway, should we close this issue?

**Comment by bk2204** [comment]
Yeah, the auth problem sounds like a server-side issue. We do retry the batch request if necessary to refresh tokens, so auth failures shouldn't be an issue, even with long running requests.

And yes, I think closing this issue is fine.
