### ISSUE TITLE
Git-LFS Storage indicator is not working

### ISSUE THREAD

**Issue by TheAuteur** [git-lfs/git-lfs#3659]
Hi, started using git-lfs for unity. I used the windows github client to migrate my unity project onto git-lfs(I also installed git-lfs for my system via the installer).  Using a .gitattributes file to specify which files go to lfs. Everything works as it was intended to. 

But for some reason, when I go to settings -> Billing, under Git-LFS,  the storage used is shown as 0.0 out of 1GB. And bandwidth is 0 too. 

In github, whenever I navigate to images/3d models/audio files etc in my repo, it shows the message "Stored with Git LFS". 

I cloned my repo to a different directory locally and the github client downloaded all files from lfs. Like 300mb in total. But the storage and bandwidth is still showing 0.0 of 1GB used.

**Comment by bk2204** [comment]
Hey, thanks for writing in.

This repository is for the development of the open source Git LFS client. Since you're seeing an issue with GitHub, could you reach out to GitHub support via support@github.com? They're better equipped to deal with these issues.

**Comment by jacksonnexhip** [comment]
The same thing is happening for me. The storage bar is empty but in the drop down arrow I am told I am using 330mb of git-LFS storage in my repos. 

![image](https://user-images.githubusercontent.com/63436961/209734788-0bffe81d-cccf-4df4-ba70-f438edd0501b.png)

**Comment by chrisd8088** [comment]
@jacksonnexhip -- I'm sorry you're having trouble.  Unfortunately, as noted in the reply above, this repository is only for the open source Git LFS client, so you'll need to contact GitHub and their Support team for an answer regarding their storage service (assuming you're using GitHub; it looks like it to me from the screenshot).

In order to avoid future confusion, I'm going to lock this issue, since it's not something we can help with.
