### ISSUE TITLE
worktree checkout with hardlinks

### ISSUE THREAD

**Issue by rokroskar** [git-lfs/git-lfs#3664]
Our use-case is to have large data stored in git-lfs and imported as submodules into repositories where data analysis is being carried out. We are concerned about data copies and I'm a bit confused on the specifics of the git-lfs implementation. 

My understanding is that with `git lfs fetch` data blobs are fetched from the remote. With `checkout` they are *copied* to the working copy. Are there any plans to make this a hard link instead of a copy? 

If I then use `git worktree` to create a parallel checkout of the same repo, it will not re-download the LFS objects but it will, afaik, make another copy on `git lfs checkout`. So now I have three copies of the same data - the LFS blob, the first working copy and the second copy in the worktree. Is this correct? Is there any way around this situation? I saw in an old issue [a comment](https://github.com/git-lfs/git-lfs/issues/766#issuecomment-151099184) that hard links were being used in `git-lob` to alleviate these problems.

**Comment by bk2204** [comment]
Hey, thanks for writing in.

Git LFS is based around the idea of a smudge/clean filter. That basically means that when Git checks out a file, it asks a filter process (Git LFS) to provide the content for it, and then it writes it into the tree. You're correct that this results in multiple copies: one in the object store and one for each worktree. But without some cooperation on the part of Git, it isn't possible to use hardlinks in the general case.

Even if that were possible, I'm not sure it would be a good idea. The files in the object store are essentially immutable, but we don't know that you won't change those files in the worktree. If we used hardlinks, any change to the worktree file would change any other worktree as well as potentially the file in the object store. That would likely result in data corruption.

The one place we can safely use hardlinks is with `git clone --shared`, which does indeed use hardlinks to copy LFS objects.

What may be possible (and I haven't tested) is instead of checking out the submodule as part of the worktree creation, you could try an approach which involves [modifying the gitlink and worktree for the submodule](https://stackoverflow.com/questions/27379818/git-possible-to-use-same-submodule-working-copy-by-multiple-projects). Of course, as mentioned there, there are some sharp edges, but if your data changes infrequently, it may be suitable for your needs.

**Comment by rokroskar** [comment]
Thanks @bk2204 for the quick and very helpful response. I'll give those suggestions a try!
