### ISSUE TITLE
Can I disable LFS per remote?

### ISSUE THREAD

**Issue by yacoob** [git-lfs/git-lfs#3665]
I have a repository that has 3 different remotes defined. One of them is github. All of the remotes have LFS enabled, although github's allowance is rather paltry (1GB) unless you fork up some cash. I'd like to keep github as remote, but without necessarily paying for the extra LFS storage. In order for this to work, I'd need to disable LFS pushing for that remote. This doesn't seem to be an option currently. Is there any chance of getting such option?

In general, from what I see, once you start using LFS, all of the remotes need to support it. This makes a lot of sense, as it makes sure all remotes have a *complete* history (including the LFS blobs). This also means that currently you can't add an ssh-only remote, or local fs remote, because LFS doesn't support them at all.

I've found [this suggestion](https://stackoverflow.com/questions/36626793/disable-git-lfs-for-a-remote) for working around that problem. It works, but purely due to the way LFS is implemented (a hook), so relying on it might be a bit brittle :D 

Does my request make sense, or is it something that you'd actively like to avoid to prevent people from creating remotes that don't contain the entire state?

Thanks!

**Comment by bk2204** [comment]
Hey, thanks for writing in.

There isn't currently an option to disable LFS pushing for a remote. It is possible to edit the `pre-push` hook not to perform the LFS push if you get a certain remote name or URL if you want to do that. That could look like this:

```shell
#!/bin/sh

[ "$1" = github ] && exit 0

# rest of hook here
```
Git LFS will honor your modifications to the hooks, provided you don't run `git lfs update --force`.

As you've suspected, though, we don't want this as an option in the codebase, since it's easy to accidentally lose data by doing that, and we very much would like to avoid options that make it easier to lose data.

One note is that we do support SSH remotes, but the LFS portion of the protocol still operates over HTTPS. There are plans for a protocol that tunnels the entire exchange entirely over SSH, but we haven't implemented that yet. It's also possible to use local remotes with a custom transport adapter, but it's not super easy to do.

**Comment by yacoob** [comment]
Thanks for the hook edit suggestion. :)

**Comment by daggerjames** [comment]
However, after I tried this solution, Github still reject my push as 

```
remote: Resolving deltas: 100% (395/395), done.
remote: error: GH008: Your push referenced at least 1 unknown Git LFS object:
remote:     09af600f3c4158de98ee0ad9300c4982bde2fa1bc4d3e6e831e85eddf4227a16
remote: Try to push them with 'git lfs push --all'.
To github.com:xxx/xxx.git
 ! [remote rejected] master -> master (pre-receive hook declined)
```

Any idea? Thanks!

**Comment by daggerjames** [comment]
> However, after I tried this solution, Github still reject my push as
> 
> ```
> remote: Resolving deltas: 100% (395/395), done.
> remote: error: GH008: Your push referenced at least 1 unknown Git LFS object:
> remote:     09af600f3c4158de98ee0ad9300c4982bde2fa1bc4d3e6e831e85eddf4227a16
> remote: Try to push them with 'git lfs push --all'.
> To github.com:xxx/xxx.git
>  ! [remote rejected] master -> master (pre-receive hook declined)
> ```
> 
> Any idea? Thanks!

And I believe that [this policy](https://github.blog/changelog/2019-06-26-git-lfs-integrity-check/) caused my confuse. Any workaround?

**Comment by bk2204** [comment]
GitHub does support not using their LFS and using a different LFS server instead, but only if you've uploaded no LFS blobs to GitHub.  If you're normally using Git LFS with GitHub but are just missing objects, then you'll need to ensure your history doesn't contain any missing objects.  There are closed issues which mention how to handle this case; if you have trouble, please open a new issue and we'll try to help out.

**Comment by XeonG** [comment]
annoying you can't in the config for the repo disable lfs per remote url setup, exact same reason as op

**Comment by daviddwlee84** [comment]
This workaround works for me

```bash
git push --no-verify
```

[git lfs - Disable Git LFS for a remote - Stack Overflow](https://stackoverflow.com/questions/36626793/disable-git-lfs-for-a-remote)
