### ISSUE TITLE
git-lfs filter-process very slow after docker volume mount

### ISSUE THREAD

**Issue by jasonfisherjlf** [git-lfs/git-lfs#3675]
This isn't a groundbreaking issue, but it is quite annoying to deal with nonetheless...

Whenever mounting our git repository to docker using the mount type of volume drastically increases the time it takes for git-lfs filter-process to complete. As an example of what I'm seeing:
```
$ time git status
On branch testBranch
Your branch is up to date with 'origin/testBranch'.

nothing to commit, working tree clean

real	0m0.206s
user	0m0.107s
sys	0m0.163s
$ docker run -it --rm --hostname `hostname` --dns=1.1.1.1 -e USER_ID=`id -u` -e GROUP_ID=`id -g` -e USER_NAME=`whoami` --privileged -v /home/jason/git/testRepo/:/build/repo testBuild:1.1.0 " cd /build; bash"
bash-4.3$ exit
exit
$ time git status
On branch testBranch
Your branch is up to date with 'origin/testBranch'.

nothing to commit, working tree clean

real	1m48.396s
user	1m54.134s
sys	0m29.420s
```

The docker image doesn't do anything fancy, it simply has a standard environment for building consistently. The docker command then mounts our git repository with the `-v` argument and opens up into the interactive mode, which I exit immediately without doing anything. The docker instance is cleaned up and nothing is left over from the docker image, yet it increases the `git status` command from 0m0.1s to 1m48.4s... (and that's a good example. Sometimes it increases it to around 6+ minutes!) A quick look at htop reveals the culprit to be git-lfs filter-process, which is taking around 125% CPU on my computer for the entire duration.

Exploring this issue, we have found that it seems to be stemming from the act of simply mounting that repository in docker. Without mounting (removing the `-v` argument) there isn't any slowdown to git status speed. Looking deeper, it seems the only change that is happening is that when docker mounts the repository to its instance, it modifies the access time of a large majority of folders and files within the repository! I have no idea why, but running `ls -lu` makes this very clear to see the updated access times.

That is all I could find regarding this drastic slowdown, and thus I find myself with 2 options that I can see:
1) Is there a way to prevent the docker mount command from modifying the access time when mounting? (and still be able to have read/write access. Read-only isn't an option in our situation)
2) Why is git-lfs filter-process going off of access time instead of modify time? This seems silly to me, since the only time you need to worry about it is when it is modified.

Please help me understand what is going on so that we can fix our workflow. Thanks!

**Comment by bk2204** [comment]
Hey, thanks for writing in.

I'm not 100% sure what's going on here, but I think I have a guess, so I'm going to offer that. Git doesn't track the access time of files in the index, but it does track the change time. I think what may be happening here is that the change time (which tracks things like owner and group) may be changing as well, which is causing `git status` to need to rebuild the index. When it does so, it needs to check all the LFS files by filtering them (cleaning them, in this case) to see if they've been modified.

In other words, I don't think this is intrinsically a Git LFS issue, but more of an artifact with how Git manages the index. You'd likely see the same problem if you had non-LFS large files using a working tree encoding or CRLF translation as well. There are potentially some workarounds that may help, though. You could try setting `core.trustctime` to `false`, `core.checkstat` to `minimal`, or both. (I would recommend trying in that order.) That may help Git learn to track only the relevant changes to your repository. Once you make those changes, you may need to run `git status` once for them to take effect.

I'm not aware of any way to make Docker not modify this data, since it's usually a kernel operation that would make those changes to the timestamps, but hopefully you can make things work with Git so changes aren't needed to Docker.

Hopefully this is helpful in tracking down what's going on with your repo.

**Comment by jasonfisherjlf** [comment]
@bk2204 THANK YOU!!! That was definitely the issue we were seeing. I ran `git config --global core.trustctime false` and it fixed the issue completely!

**Comment by bk2204** [comment]
Okay, great. Glad everything's working for you now.

**Comment by MrYutz** [comment]
I ended up here b/c my WSL2 instance was reporting git-lfs using 100% of 3 cores every time i changed directories, or even just did an ls -alh.

The suggestion from @bk2204 worked like a champ.

`git config --global core.trustctime false`
`git status`
