### ISSUE TITLE
How do I check the storage usage for each repository? 

### ISSUE THREAD

**Issue by jakepan1994** [git-lfs/git-lfs#3681]
When I push, I received "This repository is over its data quota." I checked Github under setting/billing and it says 5+GB lfs storage was used in total. So I intended to delete some of the old lfs-tracked files. But first, I don't know which repository takes that much data. Is there a way that I can directly check the usage of each repository and if I can locate the repository, how can I delete the history version of lfs-tracked files?

**Comment by bk2204** [comment]
Hey,

As for deleting the historical versions of files, you'd need to rewrite your history and squash it down in order to remove the references to those old files. Git LFS intentionally doesn't provide a way of deleting old LFS files, because the goal of Git and Git LFS is to preserve the entire history of your project.

For getting information on repository usage, could you reach out to support@github.com and ask them? That's a GitHub-specific question, and this repository is only for the Git LFS client, and we aren't able to help with GitHub-specific issues.

**Comment by omundy** [comment]
Check your repositories here
https://github.com/settings/repositories

**Comment by gokul656** [comment]
Thanks @omundy !
