### ISSUE TITLE
git-lfs migrate "forgets" executable bit changes

### ISSUE THREAD

**Issue by larsxschneider** [git-lfs/git-lfs#3691]
It looks like as if `git lfs migrate` "forgets" changes made to the executable bit of a file.

Consider this test:
```
# Generate test repo
git init .
echo "foo" >foo.dat
git add .
git commit -m "add file"

# Make the file executable
chmod u+x foo.dat
git add .
git commit -m "make file executable"

# Check executable bits
ls -la

# Migrate
git lfs migrate import --everything --include="*.dat"

# Check executable bits, again
ls -la
```

After the migration the executable bit is gone 😢:
```
Initialized empty Git repository in /path/to/test/
[master (root-commit) 9b52e84] add file
 1 file changed, 1 insertion(+)
 create mode 100644 foo.dat
[master cfe2de2] make file executable
 1 file changed, 0 insertions(+), 0 deletions(-)
 mode change 100644 => 100755 foo.dat
total 8
drwxr-xr-x   4 larsxschneider  staff  128 Jun 24 19:02 .
drwxr-xr-x  18 larsxschneider  staff  576 Jun 24 19:02 ..
drwxr-xr-x  12 larsxschneider  staff  384 Jun 24 19:02 .git
-rwxr--r--   1 larsxschneider  staff    4 Jun 24 19:02 foo.dat          <<<<<<<
   ^
migrate: Sorting commits: ..., done
migrate: Rewriting commits: 100% (2/2), done
  master    cfe2de2f724461bbb6b9f002806bfd06b2d2f3ef -> a658f883965d96ae229b4f6100e6837eead71e67
migrate: Updating refs: ..., done
migrate: checkout: ..., done
total 16
drwxr-xr-x   5 larsxschneider  staff  160 Jun 24 19:02 .
drwxr-xr-x  18 larsxschneider  staff  576 Jun 24 19:02 ..
drwxr-xr-x  13 larsxschneider  staff  416 Jun 24 19:02 .git
-rw-r--r--   1 larsxschneider  staff   42 Jun 24 19:02 .gitattributes
-rw-r--r--   1 larsxschneider  staff  126 Jun 24 19:02 foo.dat          <<<<<<<
   ^
```

My environment:
```
$ git --version
git version 2.22.0

$ git lfs version
git-lfs/2.4.0 (GitHub; darwin amd64; go 1.10.3)
```

**Comment by bk2204** [comment]
Yeah, I can confirm this. From looking at the code, we should preserve this value, but for whatever reason we're not.

I'll try to see if I can find some time to put in a fix before the next release.

**Comment by ttaylorr** [comment]
I can confirm it, too, but this defect only occurs in certain
circumstances. Here's an example that reproduces the behavior for me:

  $ git ls-tree -r HEAD
  100755 blob 257cc5642cb1a054f08cc83f2d943e56fd3ebe99    foo
  100644 blob 257cc5642cb1a054f08cc83f2d943e56fd3ebe99    sub/foo

  $ git lfs migrate import --include="**/foo" --everything
  # ...

  $ git ls-tree -r HEAD
  100644 blob c4c05499cc0d0ff1573a489be4d39db1b2fb9b2c    .gitattributes
  100644 blob ad483a923bcf4e7ef83182817802d740ee4d2ec6    foo
  100644 blob ad483a923bcf4e7ef83182817802d740ee4d2ec6    sub/foo

One can set this up by running

  $ git init repo && cd repo
  $ mkdir -p sub
  $ echo "foo" >sub/foo
  $ git commit -am "initial commit"
  $ cp sub/foo foo
  $ chmod +x foo
  $ git commit -am "second commit"

and then migrating with:

  $ git lfs migrate import --include="**/foo" --everything

Both 'foo' and 'sub/foo' are blobs that have the same contents
(specifically, "foo\n") and share the same entry name, relative to the
tree in which they reside.

But! The commit introducing 'sub/foo' precedes the commit introducing
'foo', so we migrate 'sub/foo' before 'foo' as well. When migrating
'sub/foo', we do so normally, having never seen any objects before. Once
we're done, we insert a cache entry "foo:<oid>", and then use the cached
migration to migrate "foo" in the same manner.

But! That cache entry introduced from migrating 'sub/foo' keeps the mode
bits, and so we blindly copy those over when migrating 'foo', when we
should respect the mode bits already present on the tree entry in 'foo'.

I think that there are two approaches to fixing this:

  - add the tree entry's mode bits to the cache key, which means that
    migrating 'foo' would be a cache-miss and force us to use _its_ mode
    bits instead of 'sub/foo''s.

  - re-apply information that isn't held in the cache key (e.g.,
    specifically the mode bits) when we have a cache-hit.

I'm partial to the second option more than the first, since there's no
reason that we should have to have both (1) more cache entries and (2)
spend more time migrating when both are redundant.

I pushed up a demonstration of a fix along the lines of the second
approach in 'ttaylorr/uncache-with-mode', which anybody is welcome to
pick up.
