### ISSUE TITLE
Is it possible to install git-lfs on CoreOS?

### ISSUE THREAD

**Issue by skilip** [git-lfs/git-lfs#3692]
Like the subject of this issue kind of reveals, I'm trying to get git-lfs installed on a CoreOS server. I can't find any manual though. Is it actually possible?

**Comment by bk2204** [comment]
Hey, thanks for writing in.

While I haven't tried myself, it should be possible to do. We provide statically linked binaries for Linux that are available from the releases page, or if you prefer to compile things yourself, you can compile the binaries on any suitable Linux system and copy the binaries to a CoreOS system, since Go uses static linking.

We don't provide packages for CoreOS specifically, although it's my understanding that CoreOS doesn't have packages. Definitely try out the archives we have and let us know if things work out for you.
