### ISSUE TITLE
make: *** [lint] Error 1

### ISSUE THREAD

**Issue by DavidOzc95** [git-lfs/git-lfs#3693]
I'm trying to build git-lfs from source.
After "go get github.com/git-lfs/git-lfs", I type "make" command and get "make: *** [lint] Error 1"
The version I am trying to build is git-lfs 2.7.2 and go version is 1.12.6.
What should I do to solve this problem?
Thank You.

**Comment by bk2204** [comment]
Hey, sorry to hear you're having trouble.

This target ensures that you have all the dependencies vendored in, since it's a common mistake when developing to introduce dependencies that are not vendored. If you're building without the vendor directory, you have two options: you can either run `make all` instead of `make` and take only the binary you want, or you can remove the `lint` target as a dependency of the `fmt` targets.

If you're seeing names of packages right before this error and you're building with the vendor directory, it would be helpful to know what those are (usually they'll be in a URL form without the `https://`, like `github.com/git-lfs/git-lfs`.

**Comment by wulmer** [comment]
Thanks for the hint. `make all` worked for me.

**Comment by bk2204** [comment]
Hey,

It doesn't look like there's been a response to this recently, so I'm going to close it.  If you can provide the additional information we've requested, let us know and we'll reopen.
