### ISSUE TITLE
LFS error "failed to push some refs" troubleshooting

### ISSUE THREAD

**Issue by grzewolo** [git-lfs/git-lfs#3699]
After installing GIT on a new computer (Windows 8.1 Pro) I am getting the following error while trying to push:

```
$ git push origin master
Uploading LFS objects:   0% (0/1), 0 B | 0 B/s, done
Fatal error: Server error: http://git.servername.com/root/3D.git/gitlab-lfs/obj
ects/f26bc4fdbe520d3e6c5c622245ddbf0011a576b72b6d80e831487049f59c81bd/119567
error: failed to push some refs to 'http://username@git.servername.com/root/3D.git
'
```

The push operation works fine with small files, however when it comes to larger ones (requiring LFS) I end up having the error. The curious thing is that I am still able to push large files from the old machine. I have tried reinstalling GIT as well as deleting and cloning the repository again, but nothing worked. I can see some 'failed to push some refs' issues here, but they seem to be related to different problems.

I will appreciate any hints, suggestions on how to troubleshoot and solve this issue.

**Comment by bk2204** [comment]
Hey, sorry to hear you're having trouble.

The message "Server error" means that the remote server (in your case, the GitLab instance) returned a 500 error. Since those are unexpected, the best way to try to troubleshoot this is to inspect the logs for the GitLab service and see why it's returning a 500 error. It's possible that either the service itself or the nginx proxy in front of it have some sort of trouble with the LFS files which is preventing it from handling them properly.

I don't think there's much troubleshooting on the client side that can be done otherwise, since this is the server basically admitting that it can't handle the request properly.
