### ISSUE TITLE
Discussion : Is this repo affiliated with GitHub?

### ISSUE THREAD

**Issue by mancoast** [git-lfs/git-lfs#3705]
It wasn't clear to me so maybe I missed something obvious, or this information should be included more boldly?

**Comment by bk2204** [comment]
Hey,

The Git LFS project, much like Electron, is supported primarily by GitHub and most of the core team are GitHub employees, but there are also folks that contribute that are not GitHub employees, and we encourage contributions by anyone that would like to do so.

We also do have several teams of implementers who represent alternative server or client implementations as well as some vendors (e.g., Linux distros), so that's another reason that not everyone who is on a team for this project is necessarily associated with GitHub.

So the answer is, essentially, "sort of".

**Comment by mancoast** [comment]
OK thanks!
