### ISSUE TITLE
git push slowness when enabling LFS

### ISSUE THREAD

**Issue by traviscrawford** [git-lfs/git-lfs#3707]
While working with @larsxschneider to migrate a repo to LFS, we discovered the initial `git push` after enabling LFS takes _hours_. Is there anything we can do to speed this up (e.g.: increase batch size)? Also, can you help me better understand what's happening during this time-consuming operation?

During testing, I migrated 11 images to LFS, in a repo with ~7000 commits.

```
$ git config lfs.locksverify false
$ git lfs migrate import --everything --include="*.gif"
$ git lfs ls-files | wc -l
11
$ git remote add cleaned $CLEANED_REPO_URL
$ sudo GIT_TRACE=1 GIT_TRANSFER_TRACE=1 GIT_TRACE_PACKET=1 GIT_CURL_VERBOSE=1 git push --mirror $CLEANED_REPO_URL
```

The actual push command has been showing logs like these for hours:

```
11:06:14.044334 trace git-lfs: run_command: git rev-list --stdin --objects --not --remotes=git@hostname:travis-testorg/test-cleanup-4.git --
11:06:15.253912 trace git-lfs: tq: running as batched queue, batch size of 100
```

Any idea what's happening that takes so long, and are there knobs to tune, or things we can do to the repo to speed up the push?

Here's the env we're using:

```
$ git lfs env
git-lfs/2.7.2 (GitHub; linux amd64; go 1.12.4)
git version 2.22.0

LocalWorkingDir=
LocalGitDir=
LocalGitStorageDir=
LocalMediaDir=lfs/objects
LocalReferenceDirs=
TempDir=lfs/tmp
ConcurrentTransfers=3
TusTransfers=false
BasicTransfersOnly=false
SkipDownloadErrors=false
FetchRecentAlways=false
FetchRecentRefsDays=7
FetchRecentCommitsDays=0
FetchRecentRefsIncludeRemotes=true
PruneOffsetDays=3
PruneVerifyRemoteAlways=false
PruneRemoteName=origin
LfsStorageDir=lfs
AccessDownload=none
AccessUpload=none
DownloadTransfers=basic
UploadTransfers=basic
GIT_EXEC_PATH=/usr/lib/git-core
git config filter.lfs.process = "git-lfs filter-process"
git config filter.lfs.smudge = "git-lfs smudge -- %f"
git config filter.lfs.clean = "git-lfs clean -- %f"
```

**Comment by traviscrawford** [comment]
Additional info: there are ~2700 branches in this repo. I'll try deleting all branches except `master` and trying again.

**Comment by traviscrawford** [comment]
After deleting all non-master branches, as well as the pull-request "hidden" branches, the push with LFS was very fast. I used the same commands as above, but after removing these:

```
git branch | tr -d ' ' | egrep -v '^\*master' | xargs git branch -D
git show-ref | awk '{ print $2 }' | grep '^refs/pull/' | xargs -n1 git update-ref -d
```

**Comment by bk2204** [comment]
Hey,

When we're pushing a repository that's newly rewritten, we're going to traverse every blob that exists that's less than 1024 bytes so that we can determine if an LFS object is in that object. That's likely a part of the delay you see, and there's also likely some expense if there are a large number of batch requests, of which there will be done per hundred objects.

There isn't a way to increase the batch size, since certain server implementations limit the number of objects in a batch request to keep requests cheap. You may be able to avoid the expense of traversing a lot of the Git objects mentioned above by pushing `master` and tags first using a named remote, and then pushing other branches afterwards. Git LFS shouldn't need to traverse objects it knows the remote already has, but it can only perform that optimization if you use a named remote.

It's also possible that you have a lot of LFS objects that are specific to branches and therefore you spend a lot of time performing batch requests but not a large amount of time traversing objects, and if so, there wouldn't really be a good way to speed that up.

**Comment by traviscrawford** [comment]
Thanks for the info about why this operation is expensive. Your tip about pushing `master` to a named remote sounds interesting, I'll give that a try!
