### ISSUE TITLE
GIT LFS file lock/unlocking and unable to write the file after unlock with --force option. 

### ISSUE THREAD

**Issue by ghost** [git-lfs/git-lfs#3733]
LFS file lock/unlocking

•	Locking file/files by one user, make sure another user won’t be able to push the changes for the file 

•	File can be unlocked by another user using with force option command “git lfs unlock <filename> --force”. But this does not fully solve the issue. This makes the file only read-only . 

•	To edit the file again by the user, he/she has to clone the branch/repo again to edit the unlocked file. ( Checked with Scenarios in GIT )

Please help me to provide the steps after unlock the file to make editable with using --force option.

Let me know if need more information.

Thanks,
Saravanan
M:+91-9611702211

**Comment by bk2204** [comment]
Hey,

As mentioned, I think we can automatically make files read-write when we use `--force` to unlock.

**Comment by bk2204** [comment]
So I'm looking at the code here, and I think we're already setting the bits properly in this case. If you have the option to change permissions of lockable files turned on, a lockable file is always read-only unless _you_ have it locked. So just because you unlocked the file with `--force` doesn't mean you acquired your own lock. Since there's now no lock in place, you should be able to acquire it with `git lfs lock PATH` and then the file should be made read-write.

Can you confirm that works for you?

**Comment by sarvanguru** [comment]
sorry, I am not clear your answer. could you bit more elaborate? 

Thanks!

**Comment by bk2204** [comment]
Sure. When you have `lfs.setlockablereadonly` set to true, a lockable file is read-only unless you have the lock. If there are no locks, the file will always be read-only.

If you unlock the file with `git lfs unlock --force`, that doesn't give you the lock; it only makes it such that _nobody_ has the lock. Consequently, the file remains read-only, since there are no locks.

If you run `git lfs unlock --force` (to unlock the file) and then `git lfs lock`, you should be able to acquire the lock, which should make your file read-write. Does that work for you?

**Comment by AbiVickery** [comment]
Recently, I have been unable to push some repositories up to GitHub via GitHub Desktop because they keep locking without reason. I tried unlocking them using the git lfs unlock commands on git BASH but its not working. Any suggestions?

**Comment by bk2204** [comment]
Hey,

As mentioned above, when you're setting lockable files read-only, they're read only unless _you_ have the lock.  If you want to modify them, you need to take the lock by locking them yourself.  You can view the locks that are held with `git lfs locks` to be sure that you're the one locking them.

**Comment by bk2204** [comment]
Sure, I'll close this.

**Comment by AbiVickery** [comment]
Why did I receive this email? I’m really confused. Does this have anything
to do with my GitHub projects???

**Comment by bk2204** [comment]
You commented on this issue on GitHub and that usually subscribes you to notifications.  When I made a comment and closed this issue, you were notified.  If you don't want emails for GitHub notifications, you can adjust them in the settings to disable them.
