### ISSUE TITLE
lfs pre-push implementation

### ISSUE THREAD

**Issue by xppt** [git-lfs/git-lfs#3734]
Why `git lfs pre-push` is ignoring its fourth stdin parameter (remote revision sha1) while choosing objects to send?

Instead it uses `git rev-list --not --remote <remote>` which could find too many objects if remote is not registered in git (or not fetched into refs/heads/remote/*)

I'm using git automation without any named remotes, so my `git push` starts to fail because of missing objects in the lfs cache. Seems like such failures were just fixed in #3634, but this solution still requires processing all objects ever been in repo.

Is it possible to consider remote revision sha1, excluding reachable revisions from it?

**Comment by bk2204** [comment]
I'm not 100% sure why we do this, but I'm going to make a guess, and maybe @ttaylorr can tell me if I'm wrong. My guess is that this is an optimization for the common case where you're using a named remote and pushing a new branch. Without this optimization, every new branch would require traversing the entire history, since the ref doesn't exist on the server. Of course, in this case, it also makes working with URL remotes more painful.

This is also the technique that `git submodule` uses, although it works a little differently there.

I think we're tracking the improvement to this as #3661.

**Comment by ttaylorr** [comment]
> My guess is that this is an optimization for the common case where you're using a named remote and pushing a new branch.

That sounds plausible, but this predates my contributions to the project by at least a couple of years! I tried to scan through some of the commit messages touching our pre-push implementation, but didn't find any details one way or another.

**Comment by bk2204** [comment]
Okay, I'm going to close this in favor of #3661, since we're already tracking this.
