### ISSUE TITLE
Improve warning that git lfs migrate will destroy uncommitted changes

### ISSUE THREAD

**Issue by janosh** [git-lfs/git-lfs#3741]
As suggested by @bk2204's [comment](https://github.com/git-lfs/git-lfs/issues/3123#issuecomment-515999144), this issue is a follow-up to #3123.

There, [I asked](https://github.com/git-lfs/git-lfs/issues/3123#issuecomment-515707490) that the warning for the command `git lfs migrate import --include="*.csv"` (or other extensions) about deleting uncommitted changes should be a lot more flashy! Perhaps a red color and/or all-caps message asking for confirmation twice that the user understands proceeding with the migration can result in loss of data.

**Comment by bk2204** [comment]
Hey,

Since coloring can cause accessibility issues, I'd like to focus on improving the text here. Maybe we could do something like `migrate: override changes in your working copy? All uncommitted changes will be lost! [y/N]` (and change the default to "no").

I also want to strike a balance between preventing users from accidentally destroying data and impeding usability. We want people to be able to easily script things, for example.

**Comment by janosh** [comment]
Definitely change the default to "no"!

I would make the warning even more explicit:

> migrate: Warning! Detected uncommitted changes in your directory. During the migration, all uncommitted changes will be lost! To prevent loss of changes please ensure a clean working state before migrating by first committing or stashing all changes. (When stashing LFS files, these changes may still be lost.) [y/N]

**Comment by sladyn98** [comment]
@bk2204 hey is this an issue that is beginner friendly, if yes I could give it a shot

**Comment by bk2204** [comment]
I think it's possible to pick it up reasonably easily if you make the change I suggested.  You're certainly welcome to make a PR and if there's any issues, we can help you through them.

**Comment by markgrossnickle** [comment]
Just lost over 4 hours on a tight deadline because of this.  

I saw the 'override changes in your working copy?' but ignorantly assumed that meant just the files stored on LFS. It didn't occur to me that it would wipe out everything I had done today. Even files unrelated not stored on LFS.  That was the part that was not clear to me.
