### ISSUE TITLE
git lfs clean not work

### ISSUE THREAD

**Issue by yunshan** [git-lfs/git-lfs#3762]
I'm trying to clean two binary files in git lfs storage, but no luck, the lfs clean seems not work as expected.

```Bash
// case 1 (file1.exe ~ 550MB)
$ time git lfs clean file1.exe

Exiting because of "interrupt" signal.

real    42m13.349s
user    0m0.000s
sys     0m0.000s
```

```Bash
// case 2 (file2.mp4 ~ 220MB)
$ time git lfs clean file2.mp4

Exiting because of "interrupt" signal.

real    778m24.900s
user    0m0.015s
sys     0m0.000s
```

```Bash
$ git lfs env
git-lfs/2.7.2 (GitHub; windows amd64; go 1.12.2; git 08a08ae0)
git version 2.22.0.windows.1

Endpoint=http://*.*.com/*/demo.git/info/lfs (auth=basic)
LocalWorkingDir=F:\workspace\demo2
LocalGitDir=F:\workspace\demo2\.git
LocalGitStorageDir=F:\workspace\demo2\.git
LocalMediaDir=F:\workspace\demo2\.git\lfs\objects
LocalReferenceDirs=
TempDir=F:\workspace\demo2\.git\lfs\tmp
ConcurrentTransfers=3
TusTransfers=false
BasicTransfersOnly=false
SkipDownloadErrors=false
FetchRecentAlways=false
FetchRecentRefsDays=7
FetchRecentCommitsDays=0
FetchRecentRefsIncludeRemotes=true
PruneOffsetDays=3
PruneVerifyRemoteAlways=false
PruneRemoteName=origin
LfsStorageDir=F:\workspace\demo2\.git\lfs
AccessDownload=basic
AccessUpload=basic
DownloadTransfers=basic
UploadTransfers=basic
GIT_EXEC_PATH=C:/Program Files/Git/mingw64/libexec/git-core
GIT_LFS_PATH=C:\Program Files\Git LFS
GIT_TRAC=1
git config filter.lfs.process = "git-lfs filter-process"
git config filter.lfs.smudge = "git-lfs smudge -- %f"
git config filter.lfs.clean = "git-lfs clean -- %f"
```

**Comment by bk2204** [comment]
Hey,

The `git lfs clean` command is meant to be run only by Git and not by end users. It's the "clean" part of the smudge and clean filters that Git uses to make Git LFS work. The command is hanging because it's trying to read from standard input.

It's not exactly clear to me what you're trying to do when you say that you're "trying to clean two binary files". If you no longer want to store them, you can remove them from Git using `git rm` and the commit, and no future versions will be stored. If you want to delete them from your history entirely, you'll have to rewrite history, which you can do with `git filter-branch` or BFG.

If I've misunderstood and you're trying to do something else, please say a little more about what it is that you're trying to do and I can offer a suggestion.

**Comment by yunshan** [comment]
> Hi BK, 
Thanks for your response, I want to covert the local LFS binary files to pointers in order to release some spaces.
Similar to this question: https://stackoverflow.com/questions/43377619/reset-git-lfs-repository-to-pointers
