### ISSUE TITLE
Git lfs 2.8 on windows is not updating

### ISSUE THREAD

**Issue by Wadimich** [git-lfs/git-lfs#3767]
I am using Windows 10 with Git for Windows 2.22. Git LFS won't update by itself, only by manually copying new executable into Program Files/Git directory.

Can you please fix it somehow?

**Comment by bk2204** [comment]
Hey,

Git LFS doesn't provide an automatic update system. We prefer to use the system package manager to provide that functionality, since it's better integrated and it means we don't have to manage our own privileged update code.

If you want automatic updates on Windows, you can use Chocolatey as a package manager, or you can simply use the version that comes with Git for Windows and wait for updates to Git LFS to be included in those packages.
