### ISSUE TITLE
Cannot Push while using git-lfs

### ISSUE THREAD

**Issue by AndrewSuper77** [git-lfs/git-lfs#3770]
Hello, I am using a repo that utilizes git lfs. This morning, I could no longer push anything at all. 

Below is the error message that shows when I attempt to push, <...> are project specific and not relevant to the issue:
git --no-optional-locks -c color.branch=false -c color.diff=false -c color.status=false -c diff.mnemonicprefix=false -c core.quotepath=false -c credential.helper=sourcetree -c lfs.customtransfer.bitbucket-media-api.path=/Applications/Sourcetree.app/Contents/Resources/git_local/git-lfs/git-lfs-bitbucket-media-api push -v --tags <...> refs/heads/develop:refs/heads/develop 
Pushing to https:/<...>.git
Fatal error: Server error: https://bitbucket.org/%7B%7D/%7B2150fbb3-0801-4187-8999-eb56f8b5725e%7D/info/lfs/object/verify?upload_id=a1870849-aa6c-4d89-a2e0-777a50dad6db

Errors logged to /<...>/.git/lfs/logs/20190813T132309.233093.log
Use `git lfs logs last` to view the log.
error: failed to push some refs to 'https://<...>.git'
Uploading LFS objects:   0% (0/1), 109 KB | 0 B/s, done
Completed with errors, see above

Log attached below
[20190813T132309.233093.log](https://github.com/git-lfs/git-lfs/files/3498183/20190813T132309.233093.log)

**Comment by bk2204** [comment]
Hey,

The message "Fatal error: Server error" means that the server you're pushing to sent a 500 Internal Server Error response. That means that there's some sort of problem server side, since a properly functioning server shouldn't report this error. It's probably best to reach out to Bitbucket support, since they're the only ones who know why this is occurring and they're best suited to help you with this problem.
