### ISSUE TITLE
`git lfs pull` does not work on long path (windows)

### ISSUE THREAD

**Issue by prusse-martin** [git-lfs/git-lfs#3772]
This is a problem observed on windows 10 machines.
Some of our repos have some long file names.
While running locally we have no problems since we use the default smudge filter and just do `git clone ...` / `git checkout ...` / ...
But on the CI we have the machines provisioned with `git lfs install --skip-smudge --skip-repo --force` and let jenkins do his stuff =).
Most builds doesn't have problems but since we add the branch name in the workspace folder name used once in a while some path hit the 260 windows limit.

When hitting long paths `git lfs pull origin` will output:

```
Could not check out "alfasim_data/initial_aaaaaaaaa_ssss/dddddddddddddd/initial-fffffffffffffffffffffffffffffffffffffffffffffffffffffffff.ext"
Could not check out "alfasim_data/initial_aaaaaaaaa_ssss/dddddddddddddd/initial-ggggggggggggggggggggggggggggggggggggggggggggggggggggggggg.ext"
...
Downloading LFS objects: 100% (146/146), 137 MB | 33 MB/s
```

Return `0` as error code and left the mentioned files unchanged.

Doing the same procedure using a short workspace folder name does not show problems.
Note that the error messages have been collected locally using makeshift names since jenkins itself show no outputs for this error and the jobs will just fail when some of those files are used.

With `git lfs install --force` clone and checkout will apply correctly the filters.

**Comment by bk2204** [comment]
Hey,

I think this is because we use a relative path, and Windows can't handle relative paths that are longer than 260 characters unless you explicitly enable that functionality. UNC paths have to be absolute.

I suppose we could switch to using an absolute path in this case, but I'm a little nervous about that. I'll try to take a look and see if there's a good way to solve this, but do be aware that there may be other cases where we use relative paths and fixing them all is not necessarily trivial.
