### ISSUE TITLE
LFS through ssh tunnel

### ISSUE THREAD

**Issue by PathosV** [git-lfs/git-lfs#3773]
I have a Gitea server with LFS enabled  located on "server1" on port "xxxx".
My localhost is located within a private network, as is "server1". Accessing my Gitea server from my localhost does not require any extra setup, all good here. This includes using LFS.

Most of my work however is performed on "server2", which is on a different private network that I connect to via SSH. I have already figured out how to forward ports for both ssh and http protocols to allow me to access my Gitea instance from server2 through my localhost.
I even have my ~/.ssh/config and ~/.gitconfig files setup so I can redirect commands pointing from "server1" to localhost and the required port without any edits.

The problem occurs when working with LFS enabled repos. I understand that LFS needs http to communicate and figure out the LFS server location, and with this setup I have not been able to point git in the right direction. The closest I can consistently get is getting the following response from the server:

```
Locking support detected on remote "origin". Consider enabling it with:
  $ git config lfs.https://username@localhost:3000/username/test.git/info/lfs.locksverify true
LFS: Put https://server1:3000/username/test.git/info/lfs/objects/db2bf58344683983170fc476ec4fa25628e639850818265dff84a458e8603b0a: dial tcp: lookup server1 on 172.27.0.1:53: no such host
error: failed to push some refs to 'https://username@localhost:3000/username/test.git'
```

From my understanding, I am connecting to the server, but LFS then asks the server where it's located and redirects to  https://server1:3000, which is unreachable from server2. Further it is ignoring the URL redirect that I have set in ~/.gitconfig that again works fine when not using LFS.
```
[url "https://username@localhost:3000/"]
  insteadOf = https://server1:3000/
```

Setting the LFS URL with
```
git config lfs.url = "https://username@localhost:3000/username/test.git/info/lfs"
```
or
```
git config remote.origin.lfsurl https://username@localhost:3000/username/test.git
```
does not seem to do anything, the final http call is still to server1.

**Comment by bk2204** [comment]
Hey,

I think what's happening here is that your server is providing a different URL than you're expecting. Normally, the server knows where its endpoints are and is canonical, but there are times when it isn't. If you're using Git LFS 2.8.0, you can set `lfs.transfer.enablehrefrewrite` to true and the Git settings for `insteadOf` and `pushInsteadOf` will be honored.

This isn't the default because if someone has a configuration that rewrites HTTPS URLs to SSH URLs, Git will work fine, but Git LFS won't work, since there isn't currently an SSH-only protocol for accessing the objects themselves.

**Comment by PathosV** [comment]
Hi Brain, this worked for me thank you.

The default behavior of ignoring `insteadOf ` even when I'm not replacing HTTPS with an SSH address does seem overly conservative though. Would it not be better to honor `insteadOf` requests by default, but throw an error if SSH replacement was occurring?

**Comment by bk2204** [comment]
Unfortunately, honoring it by default would break a lot of users who use `insteadOf`, since many folks wholesale rewrite entire domains to use SSH. Also, the way rewrites work, a prefix of the URL causes the URL to be rewritten, and since the LFS endpoint is under the main repository URL, it's very difficult to rewrite a large set of repositories such that the main repos use SSH but the LFS endpoints don't.

I think if we start supporting an SSH-based protocol (which we just haven't implemented yet), then we can revisit whether to turn this option on by default.
