### ISSUE TITLE
Question about how to delete files stored using git lfs

### ISSUE THREAD

**Issue by nearridge** [git-lfs/git-lfs#3776]
Please excuse me if this is a stupid question or is being posted in the wrong place – I'm a github beginner trying to figure things out still. If someone could point me in the right direction if that's the case, I'd appreciate it. 

How does one go about removing files stored with git lfs so that they don't take up storage space? I'm storing some data across two different repositories but that data is redundant, so I wish to delete it in one of those repositories so I can get back under the storage quota for git lfs.

**Comment by bk2204** [comment]
Hey,

Git LFS doesn't natively provide a way to delete objects, because our goal (and Git's) is to preserve the history of your project.

However, having said that, you can squash together older commits into one (using `git rebase -i`, `git filter-branch`, or hacks with `git fast-import`), which will remove the pointers to some of the old files. Once you've pushed the modified branch that no longer has the old pointer files, you can the contact GitHub support to remove the old LFS objects you're no longer using.

There unfortunately isn't a way to do this without rewriting history.
