### ISSUE TITLE
tracking specific files and paths, not patterns? 

### ISSUE THREAD

**Issue by matanster** [git-lfs/git-lfs#3805]
Hi,

Is it legit to specify specific paths or files on the `git lfs track` command, instead of patterns?
I have tried this, but am not sure judging from the results. 

What I see in my specific case, is that after I've done that, the output of `git lfs status` shows _all_ files staged for commit in my project, not only those that I've issued `git lfs track` for. Whereas the content of `.gitattributes` does reflect only the `git lfs track` commands I've actually issued. So it's a little confusing to me.

I've not tried pushing yet after witnessing this state of affairs.

Thanks!

**Comment by matanster** [comment]
I would add that not having to modify my file extensions or names for managing them in git lfs, would be kind of a plus, in those scenarios where there is no direct correlation between the file names and size thresholds meriting git-lfs handling. Imagine just a repo where some files are huge but they are not all psd or such, but have different extensions that make sense to preserve.

**Comment by bk2204** [comment]
Hey,

At the moment, you can only specify patterns to `git lfs track`, although there's a change in `master` that will allow you to specify a `--filename` flag to specify a filename instead.  However, having said that, since most filenames are patterns that match themselves, it's possible to specify a filename on the command line if it doesn't contain one of the following characters: `*`, `[`, or `?`.  If it does contain one of those characters, it's possible to put a backslash before it to escape it.

For example, you could specify `git lfs track foo.png` and that would add `foo.png`.

As for `git lfs status`, it may show non-LFS files, but it will list them as being of type "Git", not "LFS".

**Comment by matanster** [comment]
Thanks, this is awesome. I think the documentation and how-to snippets should mentions this key detail for those who might assume otherwise (e.g. I also tried giving a path hoping that all files under it will be taken, which obviously doesn't happen) before just supplying each file as its own pattern. 

Thanks for the other clarification too!
> As for git lfs status, it may show non-LFS files, but it will list them as being of type "Git", not "LFS".

I guess this will be made less brittle in future versions, by removing the mild obscurity of "may show non-LFS files" altogether. 

Thanks for all of this, it really helps make working with git and large files sane again.

**Comment by bk2204** [comment]
> Thanks, this is awesome. I think the documentation and how-to snippets should mentions this key detail for those who might assume otherwise (e.g. I also tried giving a path hoping that all files under it will be taken, which obviously doesn't happen) before just supplying each file as its own pattern.

Is there a particular place you think needs to be improved?  We recently updated [the man page](https://github.com/git-lfs/git-lfs/blob/b4358e1a6bb3caf89fb8744428042c3be37d4b83/docs/man/git-lfs-track.1.ronn) for `--filename`, but is there somewhere else we should update as well?
 
> > As for git lfs status, it may show non-LFS files, but it will list them as being of type "Git", not "LFS".
> 
> I guess this will be made less brittle in future versions, by removing the mild obscurity of "may show non-LFS files" altogether.

Sorry, the way I said that was inartful.  It does intentionally show non-LFS files, but marks them as "Git" instead of "LFS".  That functionality exists so you don't have to run both `git status` and `git lfs status` to get a complete idea of what's going to be committed.
