### ISSUE TITLE
How to resolve non-ASCII strings match issue?

### ISSUE THREAD

**Issue by TerryChan** [git-lfs/git-lfs#3814]
I got the same issue as bug #3794, and I found you have resolved the issue in #16, but you didn't release the bug fix yet. I used the git-lfs.exe in my NodeJS application (imported with a npm package), I know it still needs more days to receive the fixed release, but I can't wait to fix this issue in my application. Is it feasible to use any workaround the fix this issue in my application side? such as I convert the file path with Chinese charachters to correct encoding in my application(NodeJS/Javascript), and then pass the encoded path to "git lfs pull -I“ command. Could you give some guidelines？Since you are familar with how to fix this issue. Thanks.

**Comment by bk2204** [comment]
Hey,

Right now, the only solution is to use a general pattern (e.g. `*.png`) instead of a specific filename.  The problem is that we've had some refactoring work done to improve the wildmatch code, but it's currently incompatible with the current code we're using, so a simple update to master can't be done.

What I'll likely do is to create a `v1` branch in that repository and then cherry-pick the fix to that version so that we can update to the newer code on a more leisurely schedule.  You're welcome at that point to build your own Git LFS from the `master` branch and use that instead of the released version if you can't wait.

I'll try to get to this over the next couple days.
