### ISSUE TITLE
Add multiple formula versions for Homebrew 

### ISSUE THREAD

**Issue by sukov** [git-lfs/git-lfs#3822]
I have issues and would like to switch to other versions on macOS. Currently that is not possible because there is only one version available using `brew search git-lfs`.

**Comment by bk2204** [comment]
Hey,

Homebrew only offers one version of a particular piece of software.  We don't have any plans to support multiple formula versions at the moment, although nothing prevents folks from hosting their own formulae for that.

We are interested in hearing about any issues you're having, since we'd like to fix them if possible.

**Comment by sukov** [comment]
I had major problems with LFS hanging on 0% on git push and pull. Switching to older versions of Git LFS with manual install didn't hang on 0%, instead I received 422 error. Solved the issue by completely deleting the repo and cloning it again with git lfs clone (probably would achieve the same result using git clone). I'm not sure what was the cause for the issue, but if this helps for you to investigate this further here is what I used: Mojave(10.14.5) | git version 2.20.1 | git-lfs/2.8.0 .
