### ISSUE TITLE
No Credentials are available when signed in with Microsoft Account

### ISSUE THREAD

**Issue by MatBenAtos** [git-lfs/git-lfs#3829]
Hi there,
I'm currently facing a somehow weird issue. I tried to clone a repository that uses git lfs, but checkout fails with the message `api error: No credentials are available in the security package`

credential.helper is set to "manager"

The credentials for the repository are stored in the windows credential manager. Access to repositories on the same server that do not use git lfs are successful.

The error only occurs if the windows user is signed in with a Microsoft Account on Windows 10.

Git Version: 2.23.0.windows1
Git lfs Version: 2.8.0
Git Credential Manager Version: 1.19.0

When using a local user account on the same machine, everything works as expected.

**Comment by ddevyatyar** [comment]
пт, 20 сент. 2019 г., 16:05 MatBenAtos <notifications@github.com>:

**Comment by bk2204** [comment]
Hey,

Are you trying to use Kerberos, NTLM, or Basic authentication?  Running the command with `GIT_CURL_VERBOSE=1 GIT_TRACE=1 GIT_TRANSFER_TRACE=1` should show which auth type you're using. If you get `Negotiate` and the Base64-encoded part starts with `TlRM`, then you're using NTLM; otherwise, you're using Kerberos.

I suspect what's going on here is that you're trying to use Kerberos and Git LFS doesn't support that at the moment.  If that's the case, you'll probably want to either use NTLM or Basic authentication.

**Comment by MatBenAtos** [comment]
Hi,
that would not why it works with the same configuration on a non MS Microsoft Account.
Anyway, I did a test having the switches you mentioned.
The result is as expected.
The server requests authentication by LFS-Authenticate: NTLM
The client sends the request with a www-Authenticate header `Www-Authenticate: NTLM TlRM*****`

So NTLM is used as expected.
Regards,
Matthias

**Comment by bk2204** [comment]
I'm really not sure why this is occurring.  This message is from the remote server when performing a batch request, so for some reason the server is (presumably) complaining about your credentials.

None of the maintainers use NTLM with Git LFS, so while we're happy to accept patches for NTLM-related issues, we aren't really able to troubleshoot them.  I'd suggest trying a different authentication mechanism or reaching out to your Git server admin for assistance.

**Comment by MatBenAtos** [comment]
Probably it is complaining, because it is not correct. ;) I do know the different authentication mechanisms and how they work. The question is, why are the correct credentials used, with a local or domain windows account, wheres it is not on an MS Account. Maybe, I'll track that down in code on my own - but that might take a while.

**Comment by bk2204** [comment]
I have a guess about what might be the problem here.  Can you build #3881 and see if that works for you when pushing?

**Comment by arashmhashemi** [comment]
@bk2204 @MatBenAtos, I have the same problem (signed in with Microsoft account on win 10)

Downgraded to git-lfs/2.7.2, it prompted for user/password twice and worked fine after.

**Comment by bk2204** [comment]
As mentioned in #3881, we'll need someone who can build and test with NTLM to troubleshoot this problem.  None of the core team members use NTLM, so without someone willing to fix this, it will remain as it is.

**Comment by MatBenAtos** [comment]
I'll give it a try; but will probably need till the weekend. Will come back with results asap.

**Comment by MovGP0** [comment]
When using user `FOO\user` on an non domain joined machine and wanting to access an resource with user `BAR\user`, GIT LFS is supposed to use the credentials in the Windows Credential manager. GIT properly uses those, but GIT LFS seems to ignore them. 
![image](https://user-images.githubusercontent.com/83339/120328731-686cdc80-c2eb-11eb-87a0-66f6aff5053d.png)

**Comment by bk2204** [comment]
NTLM is going to be removed in the next release (as outlined in #4247), which is likely to happen June (this month) or July.  So there will be no further fixes forthcoming here, and as a result I'm going to close this issue.

**Comment by ganegaar** [comment]
I got the error in git-lfs. I found the issue to be because of Windows Hello login. When I disabled the Windows Hello, and used password to login to domain account, the issue got resolved. More details about why this happens is here:
[https://katystech.blog/azure/azure-ad-and-windows-hello-sso-to-on-premise-resources](https://katystech.blog/azure/azure-ad-and-windows-hello-sso-to-on-premise-resources)
