### ISSUE TITLE
Files do not have the readonly attribute after clone

### ISSUE THREAD

**Issue by S2-** [git-lfs/git-lfs#3830]
We would like to lock some files without using the `lfs` feature. For example for `sql` files.

With a `.gitattributes` file like this
```
*.sql lockable
```

`sql` files are not set to readonly after a repository clone on a new workstation.

We found a workaround that seems to work for us:
If, after the steps above, we create a file named `ReadMe.NotDeleteNeededForReadOnly`, and then add this line to `.gitattributes`
```
*.sql lockable
*.NotDeleteNeededForReadOnly filter=lfs diff=lfs merge=lfs -text lockable
```
and then git add & push the new file and the changes made to `.gitattributes`, a fresh clone has `sql` files correctly set to readonly.

```
>git lfs env
git-lfs/2.8.0 (GitHub; windows amd64; go 1.12.2; git 30af66bb)
git version 2.23.0.windows.1

Endpoint=https://<redacted>/deploymentdiagram.git/info/lfs (auth=none)
  SSH=git@<redacted>:<redacted>/deploymentdiagram.git
LocalWorkingDir=C:\Temp\lfs\deploymentdiagram
LocalGitDir=C:\Temp\lfs\deploymentdiagram\.git
LocalGitStorageDir=C:\Temp\lfs\deploymentdiagram\.git
LocalMediaDir=C:\Temp\lfs\deploymentdiagram\.git\lfs\objects
LocalReferenceDirs=
TempDir=C:\Temp\lfs\deploymentdiagram\.git\lfs\tmp
ConcurrentTransfers=3
TusTransfers=false
BasicTransfersOnly=false
SkipDownloadErrors=false
FetchRecentAlways=false
FetchRecentRefsDays=7
FetchRecentCommitsDays=0
FetchRecentRefsIncludeRemotes=true
PruneOffsetDays=3
PruneVerifyRemoteAlways=false
PruneRemoteName=origin
LfsStorageDir=C:\Temp\lfs\deploymentdiagram\.git\lfs
AccessDownload=none
AccessUpload=none
DownloadTransfers=basic
UploadTransfers=basic
GIT_EXEC_PATH=C:/Program Files/Git/mingw64/libexec/git-core
git config filter.lfs.process = "git-lfs filter-process"
git config filter.lfs.smudge = "git-lfs smudge -- %f"
git config filter.lfs.clean = "git-lfs clean -- %f"
```

**Comment by bk2204** [comment]
Hey,

I think this is an artifact of how clones without large files work.  Git LFS needs to install some hooks in order to make files read only.  It does this whenever it's invoked.  However, if your repository contains no large files, Git LFS isn't invoked by Git during the checkout process and therefore no hooks are installed.  This is a limitation of how Git LFS works with Git and can't really be avoided.

There are a couple of workarounds that you can try:

- Use `git lfs clone` instead of `git clone`.
- Run `git init` and `git lfs install`, and then add a remote and pull.
- Use a global set of hooks with `core.hooksPath`.

**Comment by S2-** [comment]
Thanks @bk2204 
Linking #3555 here which is related.
