### ISSUE TITLE
git/info/lfs/objects/batch: x509: certificate signed by unknown authority

### ISSUE THREAD

**Issue by Prash45** [git-lfs/git-lfs#3848]
Hi All, 

Trying to use Git LFS and getting the following error. Please advise. 

Thank you

```
$ git push origin master --verbose
Pushing to https://mygit.company.com/ms_teams/valid.git
Remote "origin" does not support the LFS locking API. Consider disabling it with:
  $ git config lfs.https://mygit.company.com/ms_teams/valid.git/info/lfs.locksverify false
Uploading LFS objects:   0% (0/2), 0 B | 0 B/s, done
batch response: Post https://mygit.company.com/ms_teams/valid.git/info/lfs/objects/batch: x509: certificate signed by unknown authority
error: failed to push some refs to 'https://mygit.company.com/ms_teams/valid.git'

```

**Comment by bk2204** [comment]
Hey,

I think this is because either (a) the server is using a certificate which doesn't chain to a known certificate authority or (b) you're on a network with a MITM proxy.  You can use the standard Git configuration options `http.sslCAInfo` and `http.sslCAPath` to set the CA configuration, and then these will be used for both Git and Git LFS.  You can also use per-URL options, such as `http.https://mygit.company.com/.sslCAPath`.
