### ISSUE TITLE
LFS files not part of the tag/release zip-file?

### ISSUE THREAD

**Issue by rustcat** [git-lfs/git-lfs#3877]
I used Git-LFS successfully and pushing/cloning repos with large files works fine.  However, it seems the large files are not included in the tag/release zip files?  I only see a line referencing the LFS server location.  

Is there a way to ensure large files are included in the zip-file in Github tag/releases?  Or is this just possible?

Thanks, 

Joe

**Comment by bk2204** [comment]
Hey,

As mentioned in #1322, Git will emit the LFS objects into the archive if the client is installed, but GitHub doesn't currently do that.  That's an issue that's known, and since it's about GitHub, not the open source Git LFS client, it's best addressed to GitHub support if anywhere.

It's possible to create your own tarballs for releases that include large files as part of them as a workaround.
