### ISSUE TITLE
update README.md

### ISSUE THREAD

**Issue by alan23273850** [git-lfs/git-lfs#3883]
The command ($ git lfs migrate import --include="*.psd") in README.md

should be modified to ($ git lfs migrate import --include="*.psd" **--include-ref=master**)

otherwise the command doesn't work.

Thank you very much!

**Comment by bk2204** [comment]
Hey,

Thanks for the report, and sorry I didn't get to your PR in time.  I agree that we'd want to have something here, probably `--everything`, since that's usually what folks want to do.

If you want to reopen your PR with that change, I'm happy to merge it; otherwise, I'll try to get a PR open within the next day or two to get it fixed.

**Comment by alan23273850** [comment]
Hello! I closed my PR since one of the build check will fail after some new progress of the official master branch, so I think it will be better for you to modify directly!

Thank you very much!
