### ISSUE TITLE
t-fetch.sh is flaky on CI

### ISSUE THREAD

**Issue by slonopotamus** [git-lfs/git-lfs#3891]
`t-fetch.sh` [passed in my fork](https://github.com/slonopotamus/git-lfs/runs/279294656) but [failed in PR](https://github.com/git-lfs/git-lfs/pull/3890/checks?check_run_id=279295133) in exactly the same Git commit.

**Comment by slonopotamus** [comment]
Same test also failed [here](https://github.com/git-lfs/git-lfs/runs/277639661).

**Comment by bk2204** [comment]
Oh, yeah, for some reason grepping for the "Downloading LFS objects" message is flaky in CI.  It probably has been since even before we used Actions, but those assertions fail more commonly in Actions.

In other tests, I've removed a lot of those assertions in favor of testing that the objects are present in the repo, and I'll do that here as well.
