### ISSUE TITLE
can't push because of Git LFS

### ISSUE THREAD

**Issue by yernaraldabergenov** [git-lfs/git-lfs#3901]
Hello,

When I try to push some commits to my remote repository I’m getting the message “batch response: Git LFS is disabled for this repository.
error: failed to push some refs to 'https://github.com/yernaraldabergenov/PlatformerJumperGame.git'”.

I’ve checked the usage of storage, and I’ve used 0.14 GB of 1GB. The repository: 'https://github.com/yernaraldabergenov/PlatformerJumperGame.git'. Please help me.

**Comment by bk2204** [comment]
Hey,

This message comes from GitHub.  It's possible that while your storage is under 1 GB, your bandwidth usage exceeds 1 GB, in which case you'd need to follow the steps [here](https://help.github.com/en/github/setting-up-and-managing-billing-and-payments-on-github/upgrading-git-large-file-storage).

Since this repository is for the Git LFS open-source project and not for GitHub, if you have additional questions about the GitHub implementation, please reach out to GitHub's support folks.

**Comment by yernaraldabergenov** [comment]
![image](https://user-images.githubusercontent.com/46201281/68144650-56d02100-ff5e-11e9-9cf2-49c552e884a4.png)
But I'm not exceeding 1 GB

**Comment by bk2204** [comment]
As mentioned, I'd definitely reach out to GitHub support on this.  This repo is for the client, not the GitHub server implementation.  They'll be able to help you figure out what's going on.
