### ISSUE TITLE
Pushing branch to new repo takes forever

### ISSUE THREAD

**Issue by rcdailey** [git-lfs/git-lfs#3915]
I'm pushing to a new repository on Gitlab. I have about 1.5GB of LFS files locally. All I'm doing is:

    $ git push gitlab master

Where `gitlab` is my remote name for the gitlab repo. In the initial push, it pushed up all the LFS files and then was stuck at 100% for about 10-20 minutes before I finally canceled it (CTRL+C). When I push again after that, it shows that all the LFS files are pushed, but then won't move to pushing the actual Git objects. When I enable `GIT_TRACE`, I see it is spamming these 2 lines over and over again:

```
13:58:09.663763 trace git-lfs: tq: running as batched queue, batch size of 100
13:58:09.663763 trace git-lfs: run_command: git rev-list --stdin --objects --not --remotes=gitlab --
```

It doesn't seem to stop doing this. Is there a reason why this is going to slow? I am attaching logs here (note that the process hasn't completed yet at the time of the attachment).

[LOG.TXT](https://github.com/git-lfs/git-lfs/files/3837989/LOG.TXT)

**Comment by rcdailey** [comment]
It did eventually finish at 14:13 local time (correlate to the attached logs from the OP). So that's roughly 26 minutes of really nothing at all. No files being pushed to the LFS repo on Gitlab server. No Git objects being pushed. Just CPU time locally. Not sure what is going on. Here's the new logs.

[LOG.TXT](https://github.com/git-lfs/git-lfs/files/3838042/LOG.TXT)

**Comment by bk2204** [comment]
Hey,

What it looks like is happening is that we're traversing the entire history to see what objects need to be pushed.  If you have a large repository with a large history, that can be expensive.  It's unfortunately unavoidable, since we need to know which objects have to be pushed, and the only way to know that is to read all of the pointer files from all of the unpushed history.

We have an optimization that queries which objects are already on the remote side and ignores them, since we assume that if the remote side has the Git objects, it also has the Git LFS objects.  You can see that with the `--not --remotes=gitlab`.  With a new repository, though, there's no data on the remote side to help that optimization, so it can be slow.

**Comment by rcdailey** [comment]
Yeah our history is pretty big, 4+ years of it. And if this is all working as designed, I'm happy to close this. It just seemed unusual to me so I opened an issue. And it also works much faster once at least 1 branch has been pushed.

Thanks for your time and explanation.
