### ISSUE TITLE
git-lfs with forks

### ISSUE THREAD

**Issue by phillipjohnston** [git-lfs/git-lfs#3916]
What is the plan for git-lfs support with forks?

Given that GitHub supports git-lfs, and forking is a core part of git-lfs, the inability to update abandoned projects to use git-lfs objects is... strange.

**Comment by bk2204** [comment]
Hey,

I'm not sure what you're asking.  If you're asking about GitHub's support of Git LFS in forks, that would be better addressed to GitHub support, since this repository is about the open source client project only.  If you're asking about something else, can you explain a little more about the behavior you're seeing and the behavior you're expecting?
