### ISSUE TITLE
LFS does not respect PORT in URL while uploading large files

### ISSUE THREAD

**Issue by Iridescens** [git-lfs/git-lfs#3922]
Client: git version 2.23.0.windows.1; git-lfs/2.8.0 (GitHub; windows amd64; go 1.12.2; git 30af66bb)
Backend: GitLab Community Edition 12.4.2 on-premise K8s with port forwarding shenanigans

```
$ git lfs env
git-lfs/2.8.0 (GitHub; windows amd64; go 1.12.2; git 30af66bb)
git version 2.23.0.windows.1

Endpoint=http://gitlab.my.svc.cluster.local:30501/root/test-project-1-pue.git/info/lfs (auth=basic)
LocalWorkingDir=D:\testRepo\test-project-1-pue
LocalGitDir=D:\testRepo\test-project-1-pue\.git
LocalGitStorageDir=D:\testRepo\test-project-1-pue\.git
LocalMediaDir=D:\testRepo\test-project-1-pue\.git\lfs\objects
LocalReferenceDirs=
TempDir=D:\testRepo\test-project-1-pue\.git\lfs\tmp
ConcurrentTransfers=3
TusTransfers=false
BasicTransfersOnly=false
SkipDownloadErrors=false
FetchRecentAlways=false
FetchRecentRefsDays=7
FetchRecentCommitsDays=0
FetchRecentRefsIncludeRemotes=true
PruneOffsetDays=3
PruneVerifyRemoteAlways=false
PruneRemoteName=origin
LfsStorageDir=D:\testRepo\test-project-1-pue\.git\lfs
AccessDownload=basic
AccessUpload=basic
DownloadTransfers=basic
UploadTransfers=basic
GIT_EXEC_PATH=D:/Progs/!Portables/Git/mingw64/libexec/git-core
git config filter.lfs.process = "git-lfs filter-process"
git config filter.lfs.smudge = "git-lfs smudge -- %f"
git config filter.lfs.clean = "git-lfs clean -- %f"
```

I was trying to test LFS with on-premise Kubernetized Gitlab on non-standard ports and got error
```
$ git add alt-8.1.0-20190829-cliff-server-11100-01-x86_64-ru-install-cd.iso

Iridescens@Iridescens-PC MINGW64 /d/testRepo/test-project-1-pue (master)
$ git lfs ls-files
38a5519169 * alt-8.1.0-20190829-cliff-server-11100-01-x86_64-ru-install-cd.iso

Iridescens@Iridescens-PC MINGW64 /d/testRepo/test-project-1-pue (master)
$ git commit -m "Really test to track *.iso using LFS"
[master b10e466] Really test to track *.iso using LFS
 1 file changed, 3 insertions(+)
 create mode 100644 alt-8.1.0-20190829-cliff-server-11100-01-x86_64-ru-install-cd.iso

Iridescens@Iridescens-PC MINGW64 /d/testRepo/test-project-1-pue (master)
$ git push origin master
Locking support detected on remote "origin". Consider enabling it with:
  $ git config lfs.http://gitlab.my.svc.cluster.local:30501/root/test-project-1-pue.git/info/lfs.locksverify true
Uploading LFS objects:   0% (0/1), 0 B | 0 B/s, done
LFS: Put http://gitlab.my.svc.cluster.local/root/test-project-1-pue.git/gitlab-lfs/objects/38a5519169df6a1d0a56158c992cb9df78fd5ef5b387638f519eff996a56af32/1089454080: dial tcp 172.29.11.79:80: connectex: No connection could be made because the target machine actively refused it.
error: failed to push some refs to 'http://gitlab.my.svc.cluster.local:30501/root/test-project-1-pue.git'

```
Notice that string "LFS: Put..." does not contain PORT reference after FQDN, and fails expectedly.
I see a serious bug there, correct me if I'm wrong.

**Comment by bk2204** [comment]
Hey,

I think what's going on here is that your GitLab server is returning a URL that points to port 80.  The way Git LFS works is that is makes a batch request to the server, and then the server returns a list of URLs for upload and download.  If the server doesn't provide a port, then we won't use an explicit port, since presumably the server knows where its data should be uploaded.  This design is used to allow the server to use a different storage location than the main server; for example, for GitHub, the data is actually uploaded directly to S3. 

You can verify that this is the case by running your command with `GIT_TRACE=1 GIT_TRANSFER_TRACE=1 GIT_CURL_VERBOSE=1` and looking at the JSON returned from the batch request.  It will likely lack a port number in the `href` elements.

There are two ways to make this work.  The easiest is to configure the server to correctly return the desired URL, which you should be able to do in the GitLab configuration.  The other is to set the Git config option `lfs.transfer.enablehrefrewrite` to `true` and then setting `http.http://gitlab.my.svc.cluster.local/root/test-project-1-pue.git:30501/gitlab-lfs.insteadOf` to `http://gitlab.my.svc.cluster.local/root/test-project-1-pue.git/gitlab-lfs`, which should rewrite the object URL to use the appropriate port on the client side.

By default, we don't allow href rewriting because it's backwards incompatible and it would break pushes where folks rewrite from HTTPS to SSH, but in this case, it should be fine and get you back up and running.

**Comment by Iridescens** [comment]
Oh, that was exactly my case, it didn't return proper port-suffixed URL, as it thinks  that it resides in normal-ish env.
On a side node, I got this covered by ruling out a correct routing via K8s ingresses and some hostPort magic (it is WAY too similar to nodePort and easily missed and/or misunderstood). Thanks for clarification, the example of GitHub really helped!
