### ISSUE TITLE
A command to expand all LFS pointers with on-demand download

### ISSUE THREAD

**Issue by slonopotamus** [git-lfs/git-lfs#3925]
I'm looking for a command somewhere in-between `git lfs checkout` and `git lfs pull` that will expand all existing LFS pointers in working copy and download LFS objects if it is required for expansion.

On one hand, `git lfs checkout` doesn't do the downloading part. On the other hand, `git lfs pull` is too greedy and downloads _all_ LFS objects for current HEAD.

There's no such command currently, right?

P.S. What are the use-cases for current `git lfs checkout` at all? I don't find it to be much useful because it leaves working copy in unpredictable state with some files being expanded while others not.

**Comment by bk2204** [comment]
Hey,

It is possible to restrict `git lfs pull` using the `-I` and `-X` options to restrict which files are downloaded.  But beyond that, it will indeed download all the objects for the current revision, and there isn't a tool to download objects for arbitrary pointers.

`git lfs checkout` is often convenient on Windows when you know you have the LFS files on your system but due to Git's lack of large file support, the files can't be checked out in the normal Git checkout process.

**Comment by slonopotamus** [comment]
> using the -I and -X
That's still too greedy.

Do you have thoughts from what side to tackle this problem? Add optional download mode to `git lfs checkout` or teach `git lfs pull` to download less or introduce a separate command? I'd personally prefer to improve `git lfs checkout`.

**Comment by bk2204** [comment]
I don't think we want to teach `git lfs checkout` to download data.  I would like to know more about the use case for this situation.  It may be that `git lfs fetch` with suitable options followed by `git lfs checkout` with similar options is the best choice if you need a lot of fine-grained control, in which case improving `git lfs fetch` or `git lfs pull` may be the right choice.

**Comment by slonopotamus** [comment]
We sometimes get raw LFS pointers in working copies even though those files are tracked by LFS. The problem with such files is that git itself seems everything is fine, `git status` shows no modified files. In order to make sure that working copy is sane, we run `git lfs pull`. But it does much more work than required (and thus is slower than it needs to be). Jenkins, for example, has an explicit option to run `git lfs pull` after checkout. Exact conditions leading to such corrupted working copy state are not yet known, unfortunately. I am aware of #3743, but this is not our case.

I think such situation can be constructed manually by running something like `git pull` with `GIT_LFS_SKIP_SMUDGE=1`. If you want to repair your working copy after that, you need to expand LFS pointer files scattered in unknown locations across all working copy, so path-based filtering doesn't help in any way.

**Comment by slonopotamus** [comment]
@bk2204 was that info enough to convince you that there's an actual need for such command?

**Comment by bk2204** [comment]
I'd rather not introduce a new command as a workaround for an unknown bug.  I'd much rather we fix the bug wherever it may lie, whether in Git LFS or elsewhere.

If you've run `git pull` with `GIT_LFS_SKIP_SMUDGE=1`, then `git lfs pull` is the right thing to do, since you'll need to fetch and check out the objects for the current branch.  I'm not sure of a way to do less work than that if you want the LFS files checked out.

As for running `git lfs pull`, that's useful where you have files larger than 4 GB on Windows, so I can see that as a legitimate option to have in Jenkins.

**Comment by slonopotamus** [comment]
> If you've run git pull with `GIT_LFS_SKIP_SMUDGE=1`, then `git lfs pull` is the right thing to do

The difference between what I want and `git lfs pull` can be seen if you did `rm -rf .git/lfs` in the past. `git lfs pull` will download all objects for `HEAD`. This is more than required to deal with "working copy has some unexpanded pointers".

**Comment by bk2204** [comment]
> The difference between what I want and `git lfs pull` can be seen if you did `rm -rf .git/lfs` in the past. `git lfs pull` will download all objects for `HEAD`. This is more than required to deal with "working copy has some unexpanded pointers".

I don't think we want to support folks deleting `.git/lfs`, and if they do, it's okay if they download more than necessary to recover from that.

In general, it's impossible to know if a file is in the proper state in the working tree without hashing it, since it could have been modified.  Even if it looks like a pointer file, we can't assume it's the _right_ pointer file.  So there are two things we can do: hash the object, and download and check it out if it's wrong, or just download and check out all the files necessary.  The first is very expensive in the common case, because usually all the files are large, and we have to hash a lot of data needlessly, but it sounds like that's what you want to do.

**Comment by slonopotamus** [comment]
Okay.

**Comment by maximveksler** [comment]
Hello,

I'm not sure if this https://github.com/actions/checkout/issues/270 issue is directly related to this discussion on this topic but indeed the checkout vs. pull behavior is strangely implemented and leading to confusion.

**Comment by bk2204** [comment]
Hey,

That problem is not this issue.  This issue is a feature request for a new functionality.  The Actions issue sounds like it's potentially a misconfiguration.
