### ISSUE TITLE
`git pull` error: [404] Object does not exist on the server

### ISSUE THREAD

**Issue by khteh** [git-lfs/git-lfs#3931]
I migrated first *.html to git lfs and then 2 weeks later added *.svg to it. These 2 days when I try to `git pull`, I get a long list of `[404] Object does not exist on the server` with some hash value in front of it. Sample:
```
<snip>
[d1bad3a16cade6d446c0d1f28915e5af25bf157000f8b664c5099f689954b673] Object does not exist on the server: [404] Object does not exist on the server
<snip>
```
```
$ git lfs migrate info --everything --include="*.{html,svg}"
migrate: Sorting commits: ..., done                                                                                                                                                                                
migrate: Examining commits: 100% (9523/9523), done                                                                                                                                                                 
$ g push --force --all
Everything up-to-date
$ g lfs status
On branch UpgradeDotNetCore
Git LFS objects to be pushed to origin/UpgradeDotNetCore:


Git LFS objects to be committed:


Git LFS objects not staged for commit:
```
`git lfs ls-files` show some files with '*' and some with '-'.

**Comment by bk2204** [comment]
Hey,

If you have the objects in a local directory, you probably want to use `git lfs push --all` (instead of `git push --all`) to push all the objects to the remote.  That will ensure you have all of the objects required on the server.

If you don't have a clone with those objects, then they're probably missing and you'd want to talk to your server administrator or hosting provider to see if they have a backup copy somewhere.  Some hosting providers prevent you from pushing Git objects without the corresponding Git LFS objects, but others don't, so it's possible they may have never made it to the server, in which case they may be lost totally.
