### ISSUE TITLE
Git lfs file protocol error

### ISSUE THREAD

**Issue by darim1** [git-lfs/git-lfs#3946]
We are trying to re-direct lfs to a file directory and encounter some problems. 

We are using:

git version 2.24.0.windows.2
git-lfs/2.9.1 (GitHub; windows amd64; go 1.12.7; git 7b479cc8)

During push we get the following error:

hint: The remote resolves to a file:// URL, which can only work with a
hint: standalone transfer agent.  See section "Using a Custom Transfer Type
hint: without the API server" in custom-transfers.md for details.
batch request: missing protocol: "file:///O%3a/TestCases/lfs"

To our understanding, it is not neccessary to configure any custom transfer agent. We assume that the lfs installer contains everything required, when using file protocol. 

Is this understanding correct?

What are we doing wrong?

Thanks,
Daniel

**Comment by bk2204** [comment]
Hey,

Sorry to hear you're having trouble.  Can you provide the output of `git lfs env`?  There are some tricky parts to working with the file protocol on Windows, and it would be helpful to see what the remote information is.

**Comment by darim1** [comment]
$ git lfs env
git-lfs/2.9.1 (GitHub; windows amd64; go 1.12.7; git 7b479cc8)
git version 2.24.0.windows.2

Endpoint=file:///O%3a/TestCases/lfs (auth=none)
LocalWorkingDir=D:\gitLfsTest
LocalGitDir=D:\gitLfsTest\.git
LocalGitStorageDir=D:\gitLfsTest\.git
LocalMediaDir=D:\gitLfsTest\.git\lfs\objects
LocalReferenceDirs=
TempDir=D:\gitLfsTest\.git\lfs\tmp
ConcurrentTransfers=3
TusTransfers=false
BasicTransfersOnly=false
SkipDownloadErrors=false
FetchRecentAlways=false
FetchRecentRefsDays=7
FetchRecentCommitsDays=0
FetchRecentRefsIncludeRemotes=true
PruneOffsetDays=3
PruneVerifyRemoteAlways=false
PruneRemoteName=origin
LfsStorageDir=D:\gitLfsTest\.git\lfs
AccessDownload=none
AccessUpload=none
DownloadTransfers=basic,lfs-standalone-file
UploadTransfers=basic,lfs-standalone-file
GIT_EXEC_PATH=C:/Program Files/Git/mingw64/libexec/git-core
GIT_LFS_PATH=C:\Program Files\Git LFS
git config filter.lfs.process = "git-lfs filter-process"
git config filter.lfs.smudge = "git-lfs smudge -- %f"
git config filter.lfs.clean = "git-lfs clean -- %f"

**Comment by bk2204** [comment]
Okay, that looks sane.  Can you run the command with the environment variables `GIT_TRACE=1` and `GIT_TRANSFER_TRACE=1` and include the output here (possibly as an attachment)?  That should provide more information to help us figure out what's going on.

**Comment by darim1** [comment]
Hey, thanks for the quick reply! I attached the trace.
[git_trace.txt](https://github.com/git-lfs/git-lfs/files/3949908/git_trace.txt)

**Comment by bk2204** [comment]
It looks from the trace like your remote is an HTTP remote.  Is that correct?  Are you trying to use `lfs.url` to redirect the LFS files to a local URL as well?  If so, it's known that currently `lfs.url` doesn't work with file URLs in 2.9.0 and 2.9.1.  You can either build from `master` (where it was fixed with #3905), grab one of the CI artifacts from `master` and use it, or wait for 2.10, which will likely be out sometime in January.

**Comment by darim1** [comment]
Sorry, I made a mistake when replacing the url. It actually is an https remote...

Yes, we are trying to redirect the lfs files to a local directory. All lfs content from this git project shall be hosted exclusievely on that directory and not on the it server. We tried this by setting lfs.url via "git lfs config". 

I understand, that this will likely work starting from version 2.10. in january. 

Thanks a lot!!

**Comment by bk2204** [comment]
Okay, I'm going to close this, since we've already fixed it and it should be in a future version.

**Comment by darim1** [comment]
Out of curiosity, I downloaded the CI git-lfs artefact for [#3905](https://github.com/git-lfs/git-lfs/pull/3905/checks?check_run_id=291784311)  and replaced the stable executable in my /Program/ folder. It appears that a suitable transfer agent is selected but the push fails in some later stage now. I attached the new trace below.

13:47:24.478287 trace git-lfs: xfer[git-lfs]: error creating handler: failed to call git rev-parse --git-dir: exit status 128

 
[git_trace2.txt](https://github.com/git-lfs/git-lfs/files/3968090/git_trace2.txt)

Any help is appreciated! Thanks!

**Comment by bk2204** [comment]
Can you try with the latest `master`'s artifacts?  I think what you're seeing may be fixed by #3940.

**Comment by darim1** [comment]
I grabbed from [here](https://github.com/git-lfs/git-lfs/pull/3953/checks) without success. Sorry!
[git_trace3.txt](https://github.com/git-lfs/git-lfs/files/3972766/git_trace3.txt)

**Comment by nikyta777** [comment]
Отправлено со смартфона Samsung Galaxy.
-------- Исходное сообщение --------От: darim1 <notifications@github.com> Дата: 17.12.2019  12:32  (GMT+02:00) Кому: git-lfs/git-lfs <git-lfs@noreply.github.com> Копия: Subscribed <subscribed@noreply.github.com> Тема: Re: [git-lfs/git-lfs] Git lfs file protocol error (#3946) I grabbed from here without success. Sorry!
git_trace3.txt

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/git-lfs/git-lfs/issues/3946?email_source=notifications\u0026email_token=ANZNE2SRTQV2I4EJFC237I3QZCTE7A5CNFSM4JY7NC32YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEHB5NUA#issuecomment-566482640",
"url": "https://github.com/git-lfs/git-lfs/issues/3946?email_source=notifications\u0026email_token=ANZNE2SRTQV2I4EJFC237I3QZCTE7A5CNFSM4JY7NC32YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEHB5NUA#issuecomment-566482640",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by bk2204** [comment]
Is the remote directory a Git repository?  Currently, support for file URLs requires that it be one, but it looks like it we can't find one in your destination directory.

**Comment by darim1** [comment]
Yes, the remote is a GIT repository over https. Do you mean that both, the git and the lfs have to be file?

**Comment by bk2204** [comment]
Yes, I mean that the file remote has to be a Git repository.  We store the data inside the Git repository just like inside your working tree.

**Comment by darim1** [comment]
I created an empty repository at the file url and the upload seems to be fine. Now my git remote complains about missing lfs files: [git_trace4.txt](https://github.com/git-lfs/git-lfs/files/3975755/git_trace4.txt) 

Git remote over https:// and lfs remote over file:/// is a bad idea then?

**Comment by bk2204** [comment]
This setup works fine for the Git LFS client.  However, some server implementations check that you've uploaded LFS files to them before the Git objects are uploaded.  I know GitHub skips this if the remote repository doesn't contain any existing LFS objects, but I don't know about GitLab.

If you have questions about GitLab and how it works with Git LFS (such as how you can disable or change this functionality), you'd need to talk to them about it.

**Comment by darim1** [comment]
Sorry, my bad. I apologize for the inconvenience!

I disabled lfs on the server side and everything works fine, now. Whoooop....This is pretty cool!

Apart from using the latest CI artifact, the trick is indeed creating a git repo at the lfs endpoint. Both types, normal or bare work.

Thanks again, 
Daniel

**Comment by bk2204** [comment]
Great, I'm glad you got this working the way you wanted.
