### ISSUE TITLE
Git LFS + Github: how to set up Personal Access Token?

### ISSUE THREAD

**Issue by alsuhr-c** [git-lfs/git-lfs#3955]
**Describe the issue**
How do I set up a personal access token for Git LFS?

Just now after using git LFS for a repo on Github (I've used Git-LFS for several months now), I received an email from Github saying:

"You recently used a password to access an endpoint through the GitHub API using git-lfs/2.7.1 (GitHub; darwin amd64; go 1.12; git 6b7fb6e3). We will deprecate basic authentication using password to this endpoint soon"

It links to the place to set up a personal access token, but I don't really know where to go from there. I can't find anything on the Git LFS documentation regarding Github personal access tokens (only thing I could find is that I need to use it if I have 2FA, which I don't) and when I go to the page to generate a new one, there are tons of scopes I could add to the personal token. I doubt Git LFS needs all of these (e.g., updating user profile data). Which ones does Git LFS need? 

Once I get the token, how can I update my installation of Git LFS to use this token instead of whatever I have already (I guess authentication using a password?)

**System environment**
I use Git LFS on OS X 10.14.6 and Ubuntu 16.04.5 LTS (GNU/Linux 4.15.0-65-generic x86_64). But I will focus on the OS X machine for now. I think I can replicate whatever the fix is on the Ubuntu machine.

**Output of `git lfs env`**
```
git-lfs/2.7.1 (GitHub; darwin amd64; go 1.12; git 6b7fb6e3)
git version 2.20.1 (Apple Git-117)

Endpoint=https://github.com/lil-lab/cerealbar.git/info/lfs (auth=basic)
LocalWorkingDir=/Users/alsuhr/Documents/research/my_projects/cerealbar
LocalGitDir=/Users/alsuhr/Documents/research/my_projects/cerealbar/.git
LocalGitStorageDir=/Users/alsuhr/Documents/research/my_projects/cerealbar/.git
LocalMediaDir=/Users/alsuhr/Documents/research/my_projects/cerealbar/.git/lfs/objects
LocalReferenceDirs=
TempDir=/Users/alsuhr/Documents/research/my_projects/cerealbar/.git/lfs/tmp
ConcurrentTransfers=3
TusTransfers=false
BasicTransfersOnly=false
SkipDownloadErrors=false
FetchRecentAlways=false
FetchRecentRefsDays=7
FetchRecentCommitsDays=0
FetchRecentRefsIncludeRemotes=true
PruneOffsetDays=3
PruneVerifyRemoteAlways=false
PruneRemoteName=origin
LfsStorageDir=/Users/alsuhr/Documents/research/my_projects/cerealbar/.git/lfs
AccessDownload=basic
AccessUpload=basic
DownloadTransfers=basic
UploadTransfers=basic
GIT_EXEC_PATH=/Library/Developer/CommandLineTools/usr/libexec/git-core
git config filter.lfs.process = "git-lfs filter-process"
git config filter.lfs.smudge = "git-lfs smudge -- %f"
git config filter.lfs.clean = "git-lfs clean -- %f"
```

Thanks!

**Comment by bk2204** [comment]
Hey,

This question is best addressed to GitHub, since this is mostly about GitHub, and not the open source client, but I'll try to answer as much as I can.  You'll need the `repo` scope for access, and you should delete the username and password for GitHub from the Keychain Access app on macOS.  Then, when prompted for a username and password, enter a dummy username (either yours or something like `token`) and the token as the password.  These credentials will also be used for Git access.

**Comment by alsuhr-c** [comment]
Thanks, I wasn't sure if this was a Git LFS specific thing or more broadly Github (haven't seen it for other Github things I've tried). I will reach out to Github if I can't figure it out with this advice.

Thanks!

**Comment by bk2204** [comment]
Just so you know, following any sort of tutorial online relevant to your operating system and credential manager about changing Git credentials in the credential manager should be applicable here.

**Comment by bitsboxscott** [comment]
I have the exact same question, because I got the exact same email.

I'm nervous about messing with auth in LFS at the risk of messing up auth for git/github in general.

Wouldn't changing to a personal access token in Mac Keychain be changing the auth method for all github access? I don't see multiple keychain entries for github vs LFS. So if I create a PAT with only repo access, might other github commands start failing? On the other hand, if I create a PAT with all rights active, would I be creating a security risk?

I've reached our to github customer support for clarity.  :) I'll try to remember to update this thread if they get back to me. If anyone else reading this has some insights or links to share, please do!

**Comment by bk2204** [comment]
Yes, generally the same credentials are used for both Git and Git LFS.  Switching to a token would likely affect both.  Adding the token with `repo` scope should be sufficient; I use such a token myself, as do numerous other people who have 2FA enabled (where a password cannot be used at all).

The thing with using as password as authentication is that you're essentially using a token with all scopes, plus the ability to log into the web interface and change your password.  So using a plain password instead of a token is a security risk, which is why GitHub is asking you to change.
