### ISSUE TITLE
lfs track doesn't recognize folders and subfolders.

### ISSUE THREAD

**Issue by SlaggyG** [git-lfs/git-lfs#3963]
**Describe the issue**
Recently I came up with some kind of error I'd say. I am trying to track a folder and subfolders with a lot of files on it (more than 16GiB of files) so I need to know how can this be done. It only works if I track the .gitattributes but not anything else , maybe I am just doing it bad but well.. 

**System environment**
linux amd64;

**Output of `git lfs env`**
`LocalWorkingDir=/home/Dener`
`LocalGitDir=/home/Dener/.git`
`LocalGitStorageDir=/home/Dener/.git`
`LocalMediaDir=/home/Dener/.git/lfs/objects`
`LocalReferenceDirs=`
`TempDir=/home/Dener/.git/lfs/tmp`
`ConcurrentTransfers=3`
`TusTransfers=false`
`BasicTransfersOnly=false`
`SkipDownloadErrors=false`
`FetchRecentAlways=false`
`FetchRecentRefsDays=7`
`FetchRecentCommitsDays=0`
`FetchRecentRefsIncludeRemotes=true`
`PruneOffsetDays=3`
`PruneVerifyRemoteAlways=false`
`PruneRemoteName=origin`
`LfsStorageDir=/home/Dener/.git/lfs`
`AccessDownload=basic`
`AccessUpload=basic`
`DownloadTransfers=basic,lfs-standalone-file`
`UploadTransfers=basic,lfs-standalone-file`
`git config filter.lfs.process = "git-lfs filter-process"`
`git config filter.lfs.smudge = "git-lfs smudge -- %f"`
`git config filter.lfs.clean = "git-lfs clean -- %f"`

**Additional note of mine:**
I don't know that much about this so please don't be mad at me 😨

**Comment by legolego88** [comment]
...Hey..

**Comment by bk2204** [comment]
Hey,

You don't want to track the `.gitattributes` file, since Git requires that to be unfiltered for things to work.  If you want to track a directory and all of its contents, you can use `git lfs track 'foo/**'` to track all te files under the directory `foo`.  That should result in an entry in `.gitattributes` starting with `foo/**`.

If you're still seeing additional problems, please feel free to copy and paste in the error text in a code block and we'll look.  As a note, most of us are off until January 3, so we'll check back in at that point.
