### ISSUE TITLE
https://git-lfs.github.com/spec/v1 is not a valid attribute name

### ISSUE THREAD

**Issue by Intotheunknown** [git-lfs/git-lfs#3974]
Greetings!

As the tittle says, I'm having trouble at the moment of doing a git clone of my repo.
I have a 2GB directory (that it wasn't in the repo's history before) that I wanted to track with **lfs**, and I did a git lfs install, then git lfs track and then add/commit/push. 
Bitbucket repo webpage says that now I have 2GB located on my Git LFS, so it was successfully tracked with lfs.

But, the problem is when I want to clone it on another local environment.
I do git lfs clone (because git clone takes too much time) and it clones well but this error appears:

`https://git-lfs.github.com/spec/v1 is not a valid attribute name <longpath>/.gitattributes:1
sha256:c3a8990ebdbfb140ade4719a26aaf3f7a1bb6288acee7201955240d84c67167a is not a valid attribute name: <samelongpathasbefore>/.gitattribute:2`

I read old posts that said something about spaces in the .gitattributes, but I think none of it is happening on my case.

I'm going to leave the .gitattributes file here attached
Greetings!
[mygitattributes.txt](https://github.com/git-lfs/git-lfs/files/4042091/mygitattributes.txt)

Thanks!

**Comment by bk2204** [comment]
Hey,

I think your `.gitattributes` file has somehow ended up as an LFS file.  I'm not sure how that happened, but that can't work, since Git can't read the contents of the `.gitattributes` file to find out which files are LFS files when it's an LFS file itself.  If you have a `.gitattributes` file in a subdirectory, that also needs to be untracked by Git LFS.

You can verify this by running the following: `git cat-file blob HEAD:<longpath>/.gitattributes` and seeing if it looks like an LFS pointer file (that is, it has `version https://git-lfs.github.com/spec/v1` at the top). If so, you probably want to remove that subdirectory's `.gitattributes` file and put the patterns in the top level one instead, making sure that you don't specify any files starting with `.git` in the patterns.

**Comment by Intotheunknown** [comment]
Hey,

First of all, thank you very much for the quick answer!

It looks like you are right. That .gitattributes file I was talking about, it has a pattern for .gitignore and .gitattributes as you said, and I bet that is the problem.

But, I also used the **find** command in order to search for more .gitattributes, and there are more of them:

- ./scripts/reportes/capacidad/scripts/savic_frontend/frontend/savic/bower_components/materialize/.gitattributes
- ./scripts/phpreportes/php-reports-master/vendor/adodb/adodb-php/.gitattributes   
- ./scripts/phpreportes/php-reports-master/vendor/phpoffice/phpexcel/.gitattributes   
- ./scripts/phpreportes/php-reports-master/vendor/swiftmailer/swiftmailer/.gitattributes   
- ./.gitattributes
(the first line is the one generating problems... The other ones don't have a pattern starting with .git on it, so they are there but don't cause troubles)

I wonder If I have to delete all of them, or just delete the one we were talking about, because all of them were generated automatically.

Remembering how I made the lfs stuff, I followed the next steps:
- git lfs install
- git lfs track "scripts/**" (Because I want to lfs track the entire scripts directory with its subdirectories)
- git add . && git commit && git push (I know, I first pushed without adding the scripts to the staging because I thought it was going to add the directory automatically)

Then, I realized I had to push the scripts directory in order to lfs track it, and add/commit/push it

Did I do wrong and because of that it generated all those .gitattributes files by itself?

Greetings and thank you again!

**Comment by bk2204** [comment]
The problem you're having is due to the `git lfs track "scripts/**"`, which tracks all files under `scripts/`, including the `.gitattributes` files.  You can either find your original clone and change that pattern to `scripts/**/[!.]*`, which will match all non-dotfiles instead, and then `git add --renormalize .` (verifying that the files are rewritten to normal `.gitattributes` files)  and commit, or you can move the patterns out as suggested.

We don't generate the `.gitattributes` files in those subdirectories; they're probably from the code that you imported.

**Comment by Intotheunknown** [comment]
Hey,

again, you were right. The repo itself contains like 4 github repos inside, and all of them have a .gitattributes on it.
The only one giving problems was the one I mentioned, because of the pattern on it, and I solved it doing what you said.

Thank you very much for the efficient and quick answers, I really appreciated your help!
