### ISSUE TITLE
How do you get more data?

### ISSUE THREAD

**Issue by AwesomeKalin** [git-lfs/git-lfs#3979]
**Describe the issue**
I got a message saying that I have used gone over my data quota. I checked Github and it says I have used 1.76GB of my 1GB. How do I free up more storage without deleting my files or is it possible to delete old commits to free up storage?

**System environment**
I'm using Windows 10 1903 and I'm using UE4 and it's a private repository

**Comment by bk2204** [comment]
Hey,

This sounds like an issue with GitHub, not an issue with Git LFS.  In general, issues with hosting providers such as GitHub should be addressed to their support teams, since this repo is for the open-source project only.  You'd want to tell them specifically whether you're over your bandwidth quota or data storage quota so they can look into it.
