### ISSUE TITLE
Prompt Existing File With Different Names

### ISSUE THREAD

**Issue by pxwee5** [git-lfs/git-lfs#3985]
Apparently the same file containing different names. E.g. Renaming dog.jpg to 
dog1.jpg and dog2.jpg

Then commit & push dog1.jpg first

When I want to commit & push dog2.jpg. LFS ignores uploading it because it is the same file. 
At the same time, LFS did not output anything, so we all thought it was a bug on our setup. 

Can we get some output from LFS if the source is the same, but it has different names?

**Comment by bk2204** [comment]
Hey,

Sorry for the confusion here.  It is the case that we try hard not to upload files the server has, since not doing so can result in cases where pushing isn't possible without fetching first.

As for your request, I'm not sure that it would be very efficient for us to do that, and if we did, it would be quite noisy.  The reason is that in some cases, the number of items being traversed is very large and we'd be warning about many, many files that aren't being pushed.  So while in your case it would be a benign warning, it would be a problem in the common case.

Also, in your case, we wouldn't even know that there's a duplicate because we intentionally avoid traversing history we know the remote side has.  In your example, you've already pushed the commit with dog1.jpg, so when we go to look at the history we need to traverse, we ignore it since the remote side has it.  It would be very slow for us to do this duplicate check, since we'd have to walk the entire history.

So while I'm sympathetic to this problem, I don't think it would be a good idea for us to implement this.
