### ISSUE TITLE
Make lfs track less verbose

### ISSUE THREAD

**Issue by mitar** [git-lfs/git-lfs#3997]
**Describe the issue**

We are regularly marking all large files as git LFS files. The easiest to do so is to simply run `git lfs track` on everything we would like to be tracked. But this issues many "already supported" messages.

I would prefer if this could be disabled somehow, so that it is easier to find messages of what has been added.

**System environment**

Ubuntu Linux.

**Output of `git lfs env`**

```
git-lfs/2.9.2 (GitHub; linux amd64; go 1.13.1)
git version 2.17.1

Error: Failed to call git rev-parse --git-dir: exit status 128 
LocalWorkingDir=
LocalGitDir=
LocalGitStorageDir=
LocalMediaDir=lfs/objects
LocalReferenceDirs=
TempDir=lfs/tmp
ConcurrentTransfers=3
TusTransfers=false
BasicTransfersOnly=false
SkipDownloadErrors=false
FetchRecentAlways=false
FetchRecentRefsDays=7
FetchRecentCommitsDays=0
FetchRecentRefsIncludeRemotes=true
PruneOffsetDays=3
PruneVerifyRemoteAlways=false
PruneRemoteName=origin
LfsStorageDir=lfs
AccessDownload=none
AccessUpload=none
DownloadTransfers=basic,lfs-standalone-file
UploadTransfers=basic,lfs-standalone-file
git config filter.lfs.process = "git-lfs filter-process"
git config filter.lfs.smudge = "git-lfs smudge -- %f"
git config filter.lfs.clean = "git-lfs clean -- %f"
```

**Comment by bk2204** [comment]
Hey,

To help me understand a little better what output you want to see, can you tell me if there's any output you want to receive?  I'm trying to determine whether it would be better for you to just redirect standard output to `/dev/null` or whether there's value in adding a `--quiet` flag, and if so, what should be affected by that.

**Comment by mitar** [comment]
I would like to see all errors (like something not being able to be added to the .gitattributes file because disk is full, or because .gitattributes is malformed). And I would like to see a message like:

```
Tracking "foobar.jpg"
```

But not:

```
"foobar.jpg" already supported
```

**Comment by bk2204** [comment]
Okay, thanks for that information.  I suspect that such a change isn't going to be generally applicable to most folks, since most folks are going to either want to see both or none.  So I'd recommend in this case that you run the output through grep (e.g., `grep -v 'already supported'`) or create a Git alias to do that instead of having us implement an option for that case.

**Comment by mitar** [comment]
I mean, both is already there, none is redirect to dev null. So that is already supported. But having idempotent (quiet) operations is useful as well. :-)

**Comment by bk2204** [comment]
I appreciate where you're coming from, but I don't think adding an option `--quiet` would be accurate if it just filtered out that message without filtering out other messages, too.  I'm having trouble thinking of a good option name for such a mode, which indicates to me that (a) it will be hard to pick an obvious name and therefore won't be discoverable and (b) that it's not likely to gain a lot of use.

There is indeed no porcelain mode for `git lfs track`.  However, it is possible to filter against the end of the string, such as `grep -v 'already supported$'`, which should not match any file names, since they'll be quoted.  I think this is the best and easiest way to get the behavior you want, with some messages filtered and others not.

**Comment by mitar** [comment]
> I'm having trouble thinking of a good option name for such a mode

`--idempotent`

**Comment by bk2204** [comment]
The name `--idempotent` describes to me that we want `git lfs track` to operate in an idempotent mode, which it already does: if the pattern exists, we don't add it.  If we add such an option to adjust logging in this case, users will question why the default mode isn't idempotent when it actually is.

As mentioned, I don't think an option is the right choice here.  There's one particular message which you'd like to filter out, and `grep` is ideal for that case.  Since I don't believe there's anything that we should change here in Git LFS, I'm going to close this issue.
