### ISSUE TITLE
i uploaded some large csv files within a folder using git lfs but i renamed and moved some files to other folder in the same local working directory,but i noticed that no changes occured in the remote when i moved or deleted things but changes occured only when i add something new.is  there any solution or it is a bug so far?

### ISSUE THREAD

**Issue by HabibRh26** [git-lfs/git-lfs#4008]
**Describe the issue**
A clear and concise description of why you wrote in today.

**System environment**
The version of your operating system, plus any relevant information about platform or configuration (e.g., container or CI usage, Cygwin, WSL, or non-Basic authentication).  If relevant, include the output of `git config -l` as a code block.

**Output of `git lfs env`**
The output of running `git lfs env` as a code block.

**Additional context**
Any other relevant context about the problem here.

**Comment by bk2204** [comment]
Hey,

Git LFS stores objects based on their SHA-256 hash and tries not to upload the same file twice.  So if you've just moved files around without changing their contents and haven't added anything, then it will determine that nothing new needs to be uploaded.  This is by design and is intended to make operations as fast and efficient as possible.

Hopefully this answers your question, but if there's anything that's unclear, please let us know.
