### ISSUE TITLE
Error: "apt-get -o Acquire::http::AllowRedirect=false update"

### ISSUE THREAD

**Issue by vikivivi** [git-lfs/git-lfs#4024]
Encountering error when using ubuntu apt-get with option which disabled "AllowRedirect". 
All other apt-get repositories has no issue, except packagecloud.io/github/git-lfs

```bash
$ sudo apt-get -o Acquire::http::AllowRedirect=false update
.....
Hit:7 http://ppa.launchpad.net/git-core/ppa/ubuntu bionic InRelease
Err:8 https://packagecloud.io/github/git-lfs/ubuntu bionic InRelease                                                                                                                                       
  302  Found [IP: 52.8.147.134 443]
.....
Reading package lists... Done                                                                                                                                                                              
E: Failed to fetch https://packagecloud.io/github/git-lfs/ubuntu/dists/bionic/InRelease  302  Found [IP: 52.8.147.134 443]
E: The repository 'https://packagecloud.io/github/git-lfs/ubuntu bionic InRelease' is no longer signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
```

There will be no error if I use "$ sudo apt-get update" which has the default option "Acquire::http::AllowRedirect=true"

$ cat /etc/os-release 
NAME="Ubuntu"
VERSION="18.04.4 LTS (Bionic Beaver)"

**Comment by bk2204** [comment]
Hey,

Unfortunately, I don't think there's anything we can do to solve this problem.  This is the way packagecloud.io works, and we aren't able to control it.  It appears that they do this to handle serving these files with a CDN.  This should be secure since the redirect comes over a secure connection and is to another secure site.

If you can't use our Debian packages, you can try using the binaries we have on our download page.
