### ISSUE TITLE
Issues with binary install on Alpine

### ISSUE THREAD

**Issue by james-crowley** [git-lfs/git-lfs#4025]
**Describe the bug**
When performing a binary install on Alpine, I get the following error:

```
bash-5.0# ./install.sh
fatal: 'lfs' appears to be a git command, but we were not
able to execute it. Maybe git-lfs is broken?
```

I tried two methods to install `git-lfs`. First I tried to follow the official method of using the `install.sh` file. After that failed I tried to do it manually by moving `git-lfs` into `/usr/bin/` and then updating the `PATH`. Both seemed to produce the above error.

Manually, steps followed:

```
curl -fsSLO https://github.com/git-lfs/git-lfs/releases/download/v2.10.0/git-lfs-linux-amd64-v2.10.0.tar.gz
tar -zvxf git-lfs-linux-amd64-v2.10.0.tar.gz
mv git-lfs /usr/bin/ 
export PATH=$PATH:/usr/bin
```   

**To Reproduce**
See above ^^^

**Expected behavior**
I expect either install method to work. This install method works on `debian` based system just fine. 

**System environment**
Testing out in a Docker image: `alpine:latest`

**Output of `git lfs env`**
N/A

**Additional context**
A work around is just to use `apk add git-lfs`. This works but deviates how we install `git-lfs` in our other Dockefiles for [Jenkins](https://github.com/jenkinsci/docker).

**Comment by james-crowley** [comment]
@bk2204 I think this might be a `musl` vs `glibc` error. I am came across a couple errors like this. I am not a GO expert, but I think it usually has to do with how the binary is compiled. 

When building the binary does it produce a statically linked file?

**Comment by james-crowley** [comment]
Here is a my test Dockerfile I been trying to get the binary built with. 

```
# Build Git LFS from source
FROM golang:alpine AS GIT_LFS

ARG GIT_LFS_VERSION=v2.10.0
ENV GIT_LFS_VERSION=$GIT_LFS_VERSION

WORKDIR $GOPATH/src/github.com/git-lfs/git-lfs/
RUN apk add --no-cache git make gcc \
    && rm -rf /tmp/*.apk /var/cache/apk/* \
    && git clone https://github.com/git-lfs/git-lfs.git ./ \
    && git checkout ${GIT_LFS_VERSION}

RUN make

```

**Comment by bk2204** [comment]
Hey,

The problem you're seeing here is that you're using musl.  When we compile Linux binaries, we use CGo, because that's required for the `git lfs dedup` command to work.  As a result, the binary is linked against libc.  It is possible to compile without CGo if you set `CGO_ENABLED=0` when compiling, in which case the `git lfs dedup` command won't function, but the binary is statically linked.  We've opted to provide a more functional binary over a more portable binary.

Since Alpine doesn't provide reasonably long-term stable versions, we don't build packages for it.  If you need packages that work on Alpine, you'll probably have to compile from source or use the version provided by Alpine themselves.

**Comment by james-crowley** [comment]
I was able to compile `git-lfs` using the above Dockerfile. I did not modify any of the build commands, just used `make`. 

By doing so, what functionality I am missing? When I call `git lfs dedup` the command does not throw any type of error. How is this any different then install the `git-lfs` provide in the Alpine packages? 

Alpine does support each release for 2 years. While they are not marking it like `Ubuntu` does as `lts`, they do support the releases for 2 years and provide security patches.  Is this not enough to support releasing a `musl` based binary?

**Comment by bk2204** [comment]
The `git lfs dedup` command requires the `FICLONE` ioctl to clone files. If CGo is disabled, you're unable to deduplicate files on certain filesystems, such as Btrfs and OCFS2.  I think I've found a way to avoid the need for CGo, though, and will send a patch shortly.

In your case, it's fine to compile your binary against musl, since it will link against the appropriate libc, but the binaries we distribute link against glibc.  So you aren't currently able to use our binaries, although compiling your own should be fine.

I've also just looked, and packagecloud.io doesn't support Alpine packages, so we wouldn't be able to distribute packages for it, even if we wanted to.

**Comment by james-crowley** [comment]
@bk2204 Thanks for the work of looking into this and doing a patch.

It is a shame that packagecloud.io does not support Alpine packages. I saw this a couple days ago, as I was going to raise a PR/Issue to get Alpine binaries pushed. 

What would be helpful is for you to release the binaries on GitHub like you do for `s390x` and other architectures. This is how we are grabbing them, via curl, and putting them into Jenkins Dockerfiles.

**Comment by bk2204** [comment]
I'm planning to make the binaries static again so we don't have to build two binaries.  That work is in #4026.  Building non-static binaries for musl is going to add a lot of complexity and time to our build process (because we'll have to add a bunch of tooling around Docker to that step) and I'd like to avoid that if possible.

**Comment by james-crowley** [comment]
@bk2204 Just to confirm what you said on the PR:

> This series allows us to stop using cgo on amd64 Linux, which makes our binaries static and therefore portable to musl-based systems

Will removing CGO allow me to just use the binaries published on the GitHub releases on Alpine without building it from source? If so, could this fix be apply for the other architectures, `s390x`, `ppc64le`, etc., too?

**Comment by bk2204** [comment]
Yes, that's the goal.  If we don't compile with cgo, then the binaries won't depend on which libc you're using, since they'll be static.  All of the non-amd64 binaries are already static, since in order to use cgo, you have to have a compiler and libc. Right now we cross-compile those binaries and don't have those components, so there's no possibility of using cgo.

**Comment by james-crowley** [comment]
@bk2204 Thanks great! Thanks for all this work. 

One slightly off topic question the Jenkins team had was, is `git lfs install` required to "fully" install `git-lfs`? We are wondering if it is something we need to include in our Dockerfile. Additionally, from looking at the man page, it seems to interact with the global git config. Does that mean I do not need to run it twice, once for the `root` user and then again on the `jenkins` user? Just running it on the `root` user would be fine?

**Comment by bk2204** [comment]
`git lfs install` sets the configuration settings that make Git invoke Git LFS.  Without those settings being set, either by `git lfs install` or otherwise, Git won't invoke Git LFS, and you'll end up with LFS pointer files instead of the large files.  So yes, it's required if you want things to work seamlessly.

The configuration it uses by default is the global configuration, which is Git's confusing terminology for the per-user configuration.  If you want it to be applied to the full system, then use the `--system` flag, which sets the system-wide configuration.

**Comment by andyneff** [comment]
Should git-lfs v2.11 work on musl now?

**Comment by bk2204** [comment]
It should, although I haven't tested.

**Comment by james-crowley** [comment]
@andyneff and @bk2204 I can confirm this works. Was testing it the other day for a Jenkins image.

**Comment by bk2204** [comment]
Awesome.  That was probably the easiest possible fix we could adopt, so I'm glad it's working.
