### ISSUE TITLE
I   cannot download the the stored files using oids in pointer 

### ISSUE THREAD

**Issue by aliyurtsevenn** [git-lfs/git-lfs#4038]
Hello, I am trying to run a program called Omics Integrator 2. This program requires interactome data, which is stored as pointers in github. I didn't see how I get the files from github using oid in pointers. Can someone explain me where I can find the steps for downloading the files from github  using oids in pointes. 

I uploaded the pointer I have in text format, thank you in advance. 
[pointer.txt](https://github.com/git-lfs/git-lfs/files/4243645/pointer.txt)

**Describe the issue**
A clear and concise description of why you wrote in today.

**System environment**
The version of your operating system, plus any relevant information about platform or configuration (e.g., container or CI usage, Cygwin, WSL, or non-Basic authentication).  If relevant, include the output of `git config -l` as a code block.

**Output of `git lfs env`**
The output of running `git lfs env` as a code block.

**Additional context**
Any other relevant context about the problem here.

**Comment by bk2204** [comment]
Hey,

If you've installed Git LFS and run `git lfs install` as [specified in the wiki](https://github.com/git-lfs/git-lfs/wiki/Installation), then when you clone the repository or change branches, it should automatically replace the pointer files with the large files you're looking for.  If you did that after cloning the repository, you can use `git lfs pull` to pull down the large files.

If you're looking for a way to download a specific file directly, there's not really a specific way to do that; you have to [speak the protocol](https://github.com/git-lfs/git-lfs/tree/master/docs/api) to do that.  GitHub does provide download links which you can try if you're just downloading a specific file, although this is not a good idea if you're trying to download a large number of files, because it's not very efficient.

**Comment by johnbent** [comment]
Hello @bk2204 , I see you closed this but I also see that you mention "GitHub does provide download links which you can try if you're just downloading a specific file".  This is the exact functionality I'm looking for but I can't figure out how to create the download link.  Can you help please?

**Comment by bk2204** [comment]
Hey,

If you're trying to perform this in an automated fashion, those links aren't designed for that.  The download links generate and embed a per-user token that's time-limited.  You'll need to speak at least the fetch portion of the protocol properly if you want to fetch the data in an automated process.

**Comment by johnbent** [comment]
Bummer!  Is there a script anywhere to make this at least somewhat easier?

**Comment by johnbent** [comment]
Also, thanks for the super fast reply!

**Comment by bk2204** [comment]
I don't think there is.  The protocol isn't super complex, but because it involves JSON, scripting it isn't immediately trivial in shell.  It'll require either `curl` and `jq`, or your language's support for JSON and an HTTPS library.

**Comment by johnbent** [comment]
Bummer.  Thanks for the super fast replies though!  Since our file is larger than 2GB and since we want a downloadable URL, looks like there is no way to do this with github . . . . If there is, I'd certainly love to know about it!
