### ISSUE TITLE
Clarification on the significance of the OID/Hash in regards to the actual file's content

### ISSUE THREAD

**Issue by Southclaws** [git-lfs/git-lfs#4089]
**Describe the issue**

This is more of a question than anything, but it may lead to documentation stuff.

I'm wondering what the significance of the OID is to the actual file - I built a little PoC where I swap out an image for a compressed version and LFS was happy to pull down the new file, even though the contents had changed.

Now I didn't set out to think about validity and integrity checks but could that be an issue?

And, say I wanted to go ahead and rewrite files at will, is that behaviour I can depend on? Or should I actually also update the pointer file with a new hash.

**System environment**

Not _that_ relevant, but I'm using [rudolfs](https://github.com/jasonwhite/rudolfs) as my LFS server and rewriting the files in S3 with a small Go program.

---

Thanks!

**Comment by bk2204** [comment]
Hey,

It's very important that the OID represent the actual hash of the file.  `git lfs fsck` will complain if your data is modified in any way, and some server implementations, like `lfs-test-server`, will reject your data if doesn't match the hash.  In addition, the size will likely change if you compress files, and while the hash may not be checked as frequently, the size is checked all the time.

So it's not a good idea to do this, since it's considered corruption.

**Comment by Southclaws** [comment]
Thanks for your reply! That confirms my original suspicions then. I was just surprised that my PoC worked with a modified file. I suppose it was just a matter of time before it would have failed (the file size went down).

I'll build a more resilient and conformative solution, thanks!
