### ISSUE TITLE
LFS files show as modified when trying to switch branches

### ISSUE THREAD

**Issue by gamiller0** [git-lfs/git-lfs#4090]
**Describe the issue**
Not sure if this is a bug or something I am doing wrong.  

I am consistently getting errors when trying to switch between branches in my LFS enabled repository.  I will be on my current branch, everything is committed and pushed, but when I switch branches I get an error about modified files.  I can revert the change and try to switch again and the same thing happens.  It seems I can commit the file and then switch branches, but I'm not sure that is the right thing to do.  I have no idea why this is happening and it is getting very frustrating.  I have not found a specific pattern yet, but will complain about different files at different times.  

git.exe checkout HTMS_PostProcess --
error: Your local changes to the following files would be overwritten by checkout:
Fews-SA/Config/ColdStateFiles/RiverWare/RW_6Hour_Import_State_Opt Default.zip
Please commit your changes or stash them before you switch branches.
Aborting

**System environment**
Windows 10. Git version 2.25.1.windows.1.  My git server is an internal TFS (visual studio) enterprise verison

**Output of `git lfs env`**
$ git lfs env
git-lfs/2.10.0 (GitHub; windows amd64; go 1.12.7; git a526ba6b)
git version 2.25.1.windows.1

Endpoint=(InternalServerNameXXX)/RFSCONFIG.git/info/lfs (auth=ntlm)
LocalWorkingDir=C:\Projects\FEWS\GIT\RFSCONFIG
LocalGitDir=C:\Projects\FEWS\GIT\RFSCONFIG\.git
LocalGitStorageDir=C:\Projects\FEWS\GIT\RFSCONFIG\.git
LocalMediaDir=C:\Projects\FEWS\GIT\RFSCONFIG\.git\lfs\objects
LocalReferenceDirs=
TempDir=C:\Projects\FEWS\GIT\RFSCONFIG\.git\lfs\tmp
ConcurrentTransfers=8
TusTransfers=false
BasicTransfersOnly=false
SkipDownloadErrors=false
FetchRecentAlways=false
FetchRecentRefsDays=7
FetchRecentCommitsDays=0
FetchRecentRefsIncludeRemotes=true
PruneOffsetDays=3
PruneVerifyRemoteAlways=false
PruneRemoteName=origin
LfsStorageDir=C:\Projects\FEWS\GIT\RFSCONFIG\.git\lfs
AccessDownload=ntlm
AccessUpload=ntlm
DownloadTransfers=basic,lfs-standalone-file
UploadTransfers=basic,lfs-standalone-file
GIT_EXEC_PATH=C:/Program Files/Git/mingw64/libexec/git-core
git config filter.lfs.process = "git-lfs filter-process"
git config filter.lfs.smudge = "git-lfs smudge -- %f"
git config filter.lfs.clean = "git-lfs clean -- %f"

**Additional context**
Any other relevant context about the problem here.

**Comment by bk2204** [comment]
Hey,

This often occurs because some files that are checked in are marked as using LFS but are actually stored as Git files.  Often times you'll see a message that one or more files "should have been pointers, but weren't".  This more frequently happens on Windows for reasons that aren't clear to me, but probably has to do with timestamps and the Git index.

The usual way to fix this, if it is what you're seeing, is to take a clean tree and run `git add --renormalize .`.  You can then run `git lfs status` and it will show the affected files with an entry like `(Git: b5bb9d8 -> LFS: b5bb9d8)`.  If you then commit, everything will be back to normal and you shouldn't see any more modified files.

**Comment by gamiller0** [comment]
thanks for the quick response!  that appears to have fixed it!
