### ISSUE TITLE
Add runnable check for invalid files (blob instead of pointers)

### ISSUE THREAD

**Issue by Flamefire** [git-lfs/git-lfs#4091]
**Describe the issue**
Currently git will show a "Encountered 29 file(s) that should have been pointers, but weren't:" message for "invalid" files. 

To prevent this from happening I'd like to add an appropriate check on CI (travis, GHA) that fails, if any file that should be on LFS is actually in the repo.

Could there be something like `git lfs check` which does what is currently done on git checkout (or whenever the above message would appear) but can be invoked manually, checks for non-pointer files that should be pointers, print those and exit with non-zero if anything was found?

**Comment by VJH123** [comment]
да мне это ненадо меня просто взломали и всё тут если что вообще все эти темы можете удалить сами

**Comment by bk2204** [comment]
Hey,

This seems like a good idea.  This isn't the first time we've seen this request; I've also seen it show up on Stack Overflow.  Perhaps we should add this as part of `git lfs fsck`, since it seems like another kind of integrity check.

In the mean time, there is this invocation, which is hideously complex, but will exit zero and print nothing if the files are properly configured and exit nonzero and print the broken filenames if there's a problem:

```console
$ git ls-files -z | git check-attr --stdin -z filter | \
    perl -n0 -e 'chomp; push @x, $_; if (@x == 3) { print "$x[0]$/" if $x[2] eq "lfs"; @x=(); }' | \
    xargs -0 -L1 sh -c 'git cat-file blob HEAD:$0 | git lfs pointer --check --stdin || { echo $0; false; }'
```

**Comment by zapp42** [comment]
Hi All,
can anybody tell me if and how I can check for the "blob instead of pointer" in a pre-receive hook? We often face this problem when users without a working LFS setup clone a lfs-enabled repository and push binary files that should have been LFS tracked files.

I tried to modify the mentioned commands only to notice that git check-attr does not work in pre-receive hook context.

Any hint is appreciated.

**Comment by bk2204** [comment]
Hey,

I believe this occurs because `git check-attr` requires an index and a bare repository doesn't have one.  You could probably do something like this, assuming that the revision to check is an argument (i.e., this is a script, not a hook):

```
#!/bin/sh -e

DIR="$(mktemp -d)"
export GIT_INDEX_FILE="$DIR/index"

trap EXIT 'rm -fr "$DIR"'

git read-tree "$1"
git ls-files -z | git check-attr --cached --stdin -z filter | \
    perl -n0 -e 'chomp; push @x, $_; if (@x == 3) { print "$x[0]$/" if $x[2] eq "lfs"; @x=(); }' | \
    xargs -0 -L1 sh -c 'git cat-file blob "HEAD:$0" | git lfs pointer --check --stdin || { echo "$0"; false; }'
```

You could turn this into a hook by processing each revision in turn.  This isn't going to be very performant, though, especially for large pushes.

**Comment by calve** [comment]
Hi, https://github.com/git-lfs/git-lfs/issues/4091#issuecomment-610479406 fails on paths containing spaces and the call to git-cat-file must be escaped;

```
git ls-files -z | git check-attr --stdin -z filter | \
perl -n0 -e 'chomp; push @x, $_; if (@x == 3) { print "$x[0]$/" if $x[2] eq "lfs"; @x=(); }' | \
xargs -0 -L1 sh -c 'git cat-file blob "HEAD:$0" | git lfs pointer --check --stdin || { echo $0; false; }'
```

Othewise I support the idea of a dedicated command, would be great for CI jobs.

**Comment by Ka55i0peia** [comment]
@calve 👍 

One extra: When this repository does not contains a git lfs indexed file, `xargs` shall pass nothing. For this add a `--no-run-if-empty` option to avoid this. (Honor to a colleague in our intergration team!)
