### ISSUE TITLE
[404] LFS object not found

### ISSUE THREAD

**Issue by serge750** [git-lfs/git-lfs#4099]
Hello,

We encounter some issue with getting files from LFS repository.

**Current satuation.**
We have migrated our TFS server 2017(update 2) to Azure DevOps 2019 on-premise 
We have updated the .lfsconfig file to point to the new restored tfs collection, containing lfs objects. 
We are using :

- htps connection
- git version 2.26.0
- git lfs version 2.10.0
- Microsoft Credential Manager for Windows 1.20.0

**Problem**
The build definition raises errors when getting lfs objects from repository. 
I’ve activates on build server the following git configuration.
GIT_CURL_VERBOSE = 1
GIT_TRACE = 1
GIT_TRANSFER_TRACE = 1

> [2af413f07383b397c3efcda5bfe14056c59515abe3ba121b7bfebc1b6bdf842e] LFS object not found: [404] LFS object not found
Logs file: [2_Checkout.txt](https://github.com/git-lfs/git-lfs/files/4487483/2_Checkout.txt)

This error is raised  during the `lfs fetch` command. I executed buil definition git commands manually with the same user and get the same error. We have no errors when we `git clone` the sources.

Can you advise a solution, because it’s really blocking for us.
I'm available to give more details if necessary.

Thanks in adavnce for your help.

regards,
Serge

**Comment by bk2204** [comment]
Hey,

This error means pretty much what it says: the server doesn't have the object.  It's possible that the object wasn't uploaded, or that it wasn't copied from one server to the other, or that it otherwise went missing.  If you have someone that might have the object, you can run `git lfs push --all` to push all of the objects they have up.

This is definitely a server-side issue, though, and the client is just reporting the message it got from the server.

If the object really is totally missing, you'd need to either avoid trying to check out any revision with that object or you'd need to remove the revision which created that object by rewriting the Git history.  You may want to ask the Azure DevOps folks to see if there might be a bug which prevents the data from being transferred correctly.

Sorry I don't have better news, but hopefully this is helpful.

**Comment by serge750** [comment]
> 
> 
> Hey,
> 
> This error means pretty much what it says: the server doesn't have the object. It's possible that the object wasn't uploaded, or that it wasn't copied from one server to the other, or that it otherwise went missing. If you have someone that might have the object, you can run `git lfs push --all` to push all of the objects they have up.
> 
> This is definitely a server-side issue, though, and the client is just reporting the message it got from the server.
> 
> If the object really is totally missing, you'd need to either avoid trying to check out any revision with that object or you'd need to remove the revision which created that object by rewriting the Git history. You may want to ask the Azure DevOps folks to see if there might be a bug which prevents the data from being transferred correctly.
> 
> Sorry I don't have better news, but hopefully this is helpful.

Thanks for your quick feedback.
The TFS collection containing lfs objects was restored from database backup. And when i `git clone` i manage to get lfs ojects without issue (two .exe files).
So somthing is strange for me and i cant's understand. If the lfs objects are missing on the LFS server, i should get the same error during clone operation, no?
I added the logs of `git clone` cmd execution result
[cmdGitLogs.txt](https://github.com/git-lfs/git-lfs/files/4491825/cmdGitLogs.txt)

Thank you.

**Comment by bk2204** [comment]
Unlike Git, Git LFS only downloads the files it needs to check out the current revision; it doesn't check out all the objects in the entire history.  This is because you may have multiple terabytes worth of data in LFS objects.

So the likely issue is that your CI system is checking out a different revision that has missing files, while your typical clone does not.  If you try to check out that same revision, you'll likely see the same problem.

**Comment by Endll** [comment]
I may have the same problem @bk2204 
**Current satuation**
We migrated the Git server from one machine to another through full file copying
Git server software: Gitea
**old:**
git-lfs/2.13.3 (GitHub;  windows amd64; go 1.16.2; git a5e65851)
git version 2.31.1.windows.1
**new:**
git-lfs/3.5.1 (GitHub;  windows amd64; go 1.21.7; git e237bb3a)
git version 2.46.0.windows.1
**Problem**
When I clone a repo, there are no issues.
When I add a new remote to a repository and doing git checkout or git pull from the new remote, a 404 error appears
**log:**
```
git-lfs/2.13.3 (GitHub;  windows amd64; go 1.16.2; git a5e65851)
git version 2.31.1.windows.1
$ git-lfs.exe filter-process
Error downloading object: ... (acc168a): Smudge error: Error downloading ....... (acc168aefd2251bbe7116e25394ac9a5be44b7071aee17f05c1608a78b854dce): [acc168aefd2251bbe7116e25394ac9a5be44b7071aee17f05c1608a78b854dce] Not Found: [404] Not Found
[404] Not Found
[acc168aefd2251bbe7116e25394ac9a5be44b7071aee17f05c1608a78b854dce] Not Found
github.com/git-lfs/git-lfs/errors.newWrappedError
D:/a/git-lfs/git-lfs/errors/types.go:198
github.com/git-lfs/git-lfs/errors.Wrapf
D:/a/git-lfs/git-lfs/errors/errors.go:85
github.com/git-lfs/git-lfs/tq.(*TransferQueue).enqueueAndCollectRetriesFor
D:/a/git-lfs/git-lfs/tq/transfer_queue.go:607
github.com/git-lfs/git-lfs/tq.(*TransferQueue).collectBatches.func1
D:/a/git-lfs/git-lfs/tq/transfer_queue.go:453
runtime.goexit
go/src/runtime/asm_amd64.s:1371
```
I'm sure it's the same version because both clone and pull operate on the latest version of the same branch.
Clone is fine, but as an additional remote pull for other repositories, there are issues, which is too strange.
Thanks in adavnce for help! .

**Comment by Endll** [comment]
I did this operation `git lfs push --all`, but it seems that nothing happened and the problem still exists.
It seems like nothing has been pushed.
log:
```
$ git lfs push origin master --all
Locking support detected on remote "origin". Consider enabling it with:
  $ git config lfs.http://***.git/info/lfs.locksverify true
Uploading LFS objects: 100% (14930/14930), 164 GB | 0 B/s, done.

```

**Comment by chrisd8088** [comment]
@Endll -- I'm sorry you're having trouble.

Rather than comment on an old, closed issue, if you're still having trouble, please open a new discussion or issue, and provide the output of `git lfs env` (when run within the repository's working tree) and a fuller description of the problem.

For instance, you say you're now using Git LFS 3.5.1 (that's what you put under your "new" heading) but then your error report shows your old Git LFS version.  And you say that nothing was pushed, but the line `Uploading LFS objects: 100% (14930/14930), 164 GB | 0 B/s, done.` would indicate otherwise.  I think we'll need a much more clear and complete explanation of exactly what steps you took in order to be able to offer any help.

I'll also just note that if you're having problems with Gitea specifically, you may want to reach out their support team for assistance.

**Comment by Endll** [comment]
> @Endll -- I'm sorry you're having trouble.
> 
> Rather than comment on an old, closed issue, if you're still having trouble, please open a new discussion or issue, and provide the output of `git lfs env` (when run within the repository's working tree) and a fuller description of the problem.
> 
> For instance, you say you're now using Git LFS 3.5.1 (that's what you put under your "new" heading) but then your error report shows your old Git LFS version. And you say that nothing was pushed, but the line `Uploading LFS objects: 100% (14930/14930), 164 GB | 0 B/s, done.` would indicate otherwise. I think we'll need a much more clear and complete explanation of exactly what steps you took in order to be able to offer any help.
> 
> I'll also just note that if you're having problems with Gitea specifically, you may want to reach out their support team for assistance.

Thank you for your reply! Sorry, my description may not be very clear.
The Git versions of old and new that I wrote above are the server Git version.
The Git version in the log is the client Git version that executed the `git lfs push`. 
The client has not been modified, so I don't think it will affect it either?
I apologize again for my unclear description, and I will bring more logs to open a new issue
