### ISSUE TITLE
Specify required Git version

### ISSUE THREAD

**Issue by technoweenie** [git-lfs/git-lfs#410]
Git v1.8+ is required for solid smart https protocol support and credential caching. Need to figure out what Git version added support for the `pre-push` hook too.

Ideally Git LFS could detect an inferior git version and warn the user about it.  Missing support for `pre-push` is especially dangerous because a typical `git push` will happily push the Git repo without any LFS objects because it doesn't know to check for a pre push hook.

**Comment by technoweenie** [comment]
v1.8.2 introduced the pre-push hook. I think that's the earliest version of Git that Git LFS will support.

**Comment by jhoblitt** [comment]
The oldest version I have tested with is `git-1.8.3.1-4.el7.x86_64` from el7, which appears to function as expected.  Some functionality is 1.9+ is needed so I haven't gone back any further.  I have also successfully tested with 2.2.2, 2.4.3 (fedora 22), 2.5.2, & 2.6.2 all built from source unless noted otherwise.

**Comment by technoweenie** [comment]
> Some functionality in 1.9+ is needed

Do you mean something in Git LFS, or something only related to your setup or project?

**Comment by jhoblitt** [comment]
The 1.9+ requirement is for purely for our internal build tool chain.

**Comment by ttaylorr** [comment]
Added to the roadmap in #1438

**Comment by technoweenie** [comment]
Re-opening after adding this to a GH Project.
