### ISSUE TITLE
[Proposal] Set up optional unlocking of attributes upon successful push to remote

### ISSUE THREAD

**Issue by Jlalond** [git-lfs/git-lfs#4106]
#2671 has been open for quite some time, but since post-push hooks have been added I believe there is a way to be able to achieve this.

I propose we allow auto-unlocking behavior to be configured via `.gitattributes`

Similar to how:
`*.lisp text = auto` will auto configure a file extension to behave like text, I believe allowing glob and direct paths for auto-unlock to be beneficial.

EX:
`*.uasset autoUnlock = true`
or 
`~/MyPath/SomeFile.txt autoUnlock = true`

For any item not configured in this way, we would still support the current behavior of requiring unlocking manually.

**Comment by Jlalond** [comment]
@bk2204

**Comment by bk2204** [comment]
Hey,

I don't see `post-push` anywhere in Git's source tree, and I don't see any documentation for those hooks.  I agree that they'd be a logical place to put this if they existed.  Since they don't, how do we plan on implementing this without server-side support?

I'm wondering if it might just be better to have this as a config option instead of a `.gitattributes` option.  Can you tell me more about your use cases and why you'd want this behavior for some files but not others?

**Comment by Jlalond** [comment]
Hey Brian,

My plan was to implement using post-receive on master, basically after a merged PR or even a push to master I assume we can parse a configuration and run an unlock,

Something like this: (Bash scripting isn't my forte but I hope you get the intent) 
```
brnch=$(git rev-parse --abbrev-ref HEAD);
echo $brnch
if [ "$brnch" != "master" ]; then
	echo "Exiting as branch is not master"
	exit 0
fi

files=$(git diff-tree --no-commit-id --name-only -r HEAD^^)
for fl in $files; do 
	git lfs unlock $fl
done
```
On the config note, I'm down really any config, even rolling our own config file. I thought attributes was the closest without adding a new file but I'm open to opinions on that one

**Comment by bk2204** [comment]
The client configuration wouldn't be stored in the repository, so that would preclude using it for this purpose.  I think we'd want some way to let the client choose this behavior and report it to the server, so we'd need a way to get that client information to the server somehow, possibly via some LFS server API request.

`post-receive` hooks aren't impossible to do, but they do necessarily involve some complexity, since most server implementations don't support arbitrary hooks.  So we'd need some way to get that information to the LFS server, since the LFS server need not be the same server as the Git machine (we allow them to be separate and folks rely on this).  In a lot of cases, webhoooks could be used for that, but that would still require support for letting the LFS server know that this was a desired behavior.

**Comment by Jlalond** [comment]
I think you're right, and this is much trickier than I originally considered so I apologize about my naivety.

Now unless I'm wrong we'd still commit a reference/link to our file into master. Would it be a simple solution for an upstream hook on our actual git source repo calling out to our lfs server to unlock it? Or as you suggested broadcasting a web hook? The web hook solution introduces an issue around exposing configuration data to LFS vs our git repo itself. 

Lastly, thanks for your patience and collaborating with me to create a solution for this behavior

**Comment by bk2204** [comment]
Yeah, the way I'm imagining this would work is that the Git server would have some way of letting the LFS server know that the files should be unlocked.  We'd need to define such endpoints for administrative access, and we'd also need a way to tell the LFS server from the client that the client would like it to unlock the locks on push so that the LFS server can do it or not, as requested.

**Comment by Jlalond** [comment]
I think taking a git repo proper approach would actually work better, because if we made it so anyone could arbitrarily run hooks on their upstream master repo I think this makes it as flexible as possible.

For example, in my project I could write my own custom git attributes, or another file, or really anything I want to config in my repo.

I think the only LFS change needed here is a way for the upstream repo to call and unlock a set enumeration of files. 

I think this is the skinniest build to make this possible

**Comment by Jlalond** [comment]
Hey @bk2204 circling back on this, I think we should close this issue. What I found works well is to have a list of files that are on our LFS, and for the ones we want to automatically unlock, our upstream repo makes calls to unlock them. I think this pattern is enough to support behavior that people would want

**Comment by bk2204** [comment]
Okay, thanks.  If you decide you want to work on this proposal in the future, we can reopen.
