### ISSUE TITLE
LFS upload failed:

### ISSUE THREAD

**Issue by FENGZHIJIE1998** [git-lfs/git-lfs#4125]
**git push -u origin master:**
$ git push -u origin master
Locking support detected on remote "origin". Consider enabling it with:
  $ git config lfs.http://gitlab.qiancheng.com/FengZhiJie/test_lfs.git/info/lfs.locksverify true
Git LFS: (0 of 3 files, 719 skipped) 0 B / 15.96 MB, 10.88 MB skipped
LFS upload failed:
  (missing) public/kdxf-osx-amd64 (eaec7e011f005b54391f244c56ebf6cdfec061d2cfa8059ab89f039d9907433b)
  (missing) public/kdxf-linux-amd64 (fbb83d7dee78bdcc0b926295e6636b24374ddb2d4314dfc3a111dc0777632464)
  (missing) public/tcpecho/tcpecho (1cacd517dd554edd0261699eafaecd7963c36bafc3671007cb98d810963527e2)
error: failed to push some refs to 'http://gitlab.qiancheng.com/FengZhiJie/test_lfs.git'

**git lfs fsck :**
$ git lfs fsck
Object public/kdxf-linux-amd64 (fbb83d7dee78bdcc0b926295e6636b24374ddb2d4314dfc3a111dc0777632464) could not be checked: The system cannot find the file specified.
Object public/kdxf-osx-amd64 (eaec7e011f005b54391f244c56ebf6cdfec061d2cfa8059ab89f039d9907433b) could not be checked: The system cannot find the file specified.
Object public/tcpecho/tcpecho (1cacd517dd554edd0261699eafaecd7963c36bafc3671007cb98d810963527e2) could not be checked: The system cannot find the file specified.
Moving corrupt objects to C:\Users\Administrator\Desktop\GZAudio-api\GZAudio-api\.git\lfs\bad
rename C:\Users\Administrator\Desktop\GZAudio-api\GZAudio-api\.git\lfs\objects\fb\b8\fbb83d7dee78bdcc0b926295e6636b24374ddb2d4314dfc3a111dc0777632464 C:\Users\Administrator\Desktop\GZAudio-api\GZAudio-api\.git\lfs\bad\fbb83d7dee78bdcc0b926295e6636b24374ddb2d4314dfc3a111dc0777632464: The system cannot find the file specified.

**Comment by bk2204** [comment]
Hey,

It sounds like you're missing some objects in your local copy.  If these objects are available on the server, you can try doing a `git fetch --all` to fetch them.  If they're something newly created in your repository, then you may have some disk or file system problems that you'll want to check out.

**Comment by legolego88** [comment]
HeyVon meinem Samsung Galaxy Smartphone gesendet.
-------- Ursprüngliche Nachricht --------Von: "brian m. carlson" <notifications@github.com> Datum: 07.05.20  23:25  (GMT+01:00) An: git-lfs/git-lfs <git-lfs@noreply.github.com> Cc: Subscribed <subscribed@noreply.github.com> Betreff: Re: [git-lfs/git-lfs] LFS upload failed: (#4125) 
Closed #4125.

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/git-lfs/git-lfs/issues/4125#event-3314715358",
"url": "https://github.com/git-lfs/git-lfs/issues/4125#event-3314715358",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]
