### ISSUE TITLE
git push fails with "Unable to find Source" for files deleted earlier when using a new remote

### ISSUE THREAD

**Issue by ChristianSchenk711** [git-lfs/git-lfs#4142]
I want to push my repo's master branch to a completely new repository. What I want to do is:
```
git clone https://user@dev.azure.com/user/test/_git/source
cd source
git remote add target https://user@dev.azure.com/user/test/_git/target
git push copy master
```

This fails during push, if my source repository did contain an LFS file at some point in its history, which is deleted in the latest commit.

I can make the push work using `git config lfs.allowincompletepush false` and then I can see a message about the missing files:
```
  (missing) abc.bin (edeaaff3f1774ad2888673770c6d64097e391bc362d7d6fb34982ddf0efd18cb)
```
In this particular example my repository contained a file abc.bin at some point which I deleted later.
I could also do a `git lfs fetch --all` before pushing, but due to the repository size, I would like to avoid that.

The root cause seems to be that clone will download only the LFS objects that are part of the current commit. But the pre-push hook uses something like "git rev-list <mycommitid> --objects" and since the history still contains the deleted file it somehow gets picked up (I didn't analyse what happens in detail).

I generally would expect, that I can do the above steps without failure. More specifically I would expect the pre-push hook to push only those files that are present in the current commit.

Another remark: later I want to use a bare repository for the above steps. That should work as well as far as I understand, but currently leads into the same trouble.

(Using git-lfs 2.10.0 and git 2.11.0 in this case)

**Comment by ChristianSchenk711** [comment]
Just FYI: this is how I set up my source repo for testing:
``` 
git clone ...my initial repo (contains only a readme)...                                                                                              
git lfs install                                                                                                                                                                                   
git lfs track *.bin                                                                                        
echo "abc" > abc.bin && git add . && git commit -m "a"                                                     
git push                                                                                                   
echo "def" > def.bin && git add . && git commit -m "d"                                                     
git push                                                                                                   
rm abc.bin                                                                                                 
git add .                                                                                                  
git commit -m 'removed abc'                                                                                
git push                                                                                                   
```

**Comment by bk2204** [comment]
Hey,

When you push to a new repo, you need to push all of the LFS objects in the history.  Otherwise, if you didn't, you wouldn't be able to check out the old revisions of the repository.  Some servers allow you to not push all of the objects, but most prevent you from doing that since it destroys your history.

It is true that cloning a repository doesn't copy all of the LFS files; that's by design, since part of the goal of Git LFS is to help people have smaller checkouts.  In this case, since you're pushing to a new repository, you're definitely going to need to do a `git lfs fetch --all` before pushing, since you'll need to push every object in order to push into the new repository.

So while this may not be what you were looking for as a solution, it is the expected and intentional behavior and you'll need to use `git lfs fetch --all` before pushing.

**Comment by ChristianSchenk711** [comment]
Yes, not what I was hoping for, but thanks for the quick response! 👍
