### ISSUE TITLE
Determine `git clone --mirror` has lfs objects.

### ISSUE THREAD

**Issue by bartoszek** [git-lfs/git-lfs#4161]
**What would be a correct solution to determine if `git clone --mirror` has lfs objects that need to be fetched ?**
My first solution looks really crude and fragile🧷
```sh
grep -q "filter=lfs" <(git -C "$dir" show HEAD:.gitattributes) && ! git -C "$dir" lfs pull;
```
[I'm writing a build environment extension for Arch Linux packaging system and need some insight from git-lfs devs](https://github.com/bartoszek/pacman/blob/9e9acbc47bf004722b69fb0ca5b7128214111077/scripts/libmakepkg/source/git.sh.in#L55)

**Comment by bk2204** [comment]
Hey,

Are you looking to see whether you need to fetch any objects for a certain revision (e.g., `HEAD`), or whether the repository as a whole has LFS objects?  If the former, your command is fine, although I would put a space at the front of the pattern.  If the latter, that won't work, because old revisions may have LFS objects even though `HEAD` does not.

It looks like you want the former, based on your code.  If so and you want something more elegant, you can try this:

```
git ls-files | git check-attr --stdin filter | awk -F': ' '$3 ~ /lfs/ { print; }'
```

That will be empty (i.e., no output) if there are no LFS objects and non-empty if there are, assuming that your paths don't contain the string `: ` (colon-space).
