### ISSUE TITLE
Files with no extension always cloned as pointers

### ISSUE THREAD

**Issue by loic-lefort** [git-lfs/git-lfs#4166]
I have  created a repo with binaries all managed by LFS.
When cloning this repo, files with no extension are not uploaded, they are left as pointers.
Files with an extension are correctly uploaded.

```
$ git lfs --version
git-lfs/2.11.0 (GitHub; windows amd64; go 1.14.2; git 48b28d97)

$ git config --global --get lfs.fetchinclude
*arch32,*.bin,*.stm32,*.img,*.elf,*.dtb,*basic,*defconfig
```

I also tried without any lfs.fetchinclude and lfs.fetchexclude defined, same problem: files *arch32, *basic and *defconfig are left as pointers while other files are correctly uploaded.

If I run "git lfs fetch; git lfs checkout" after my git clone, pointers are correctly replaced by files.

How to upload files with no extension during git clone ?

**Comment by chrisd8088** [comment]
Hey, I'm sorry you're having trouble.  Would you be able to include the output of `git config -l` (minus any sensitive information like your email) and also `git lfs env`?

You might then try running your clone with `GIT_TRACE=1`, that is, `GIT_TRACE=1 git clone ...`.  There will be a lot of private info in that output, so please don't paste it all, but I would be interested in the lines that look like:
```
trace git-lfs: filepathfilter: accepting "..."
trace git-lfs: filepathfilter: rejecting "..." via [...]
```
(particularly the `rejecting` lines!)

**Comment by loic-lefort** [comment]
```
$ git config -l
http.sslbackend=openssl
diff.astextplain.textconv=astextplain
filter.lfs.clean=git-lfs clean -- %f
filter.lfs.smudge=git-lfs smudge -- %f
filter.lfs.process=git-lfs filter-process
filter.lfs.required=true
credential.helper=manager
core.autocrlf=true
core.fscache=true
core.symlinks=false
pull.rebase=false
filter.lfs.clean=git-lfs clean -- %f
filter.lfs.smudge=git-lfs smudge -- %f
filter.lfs.process=git-lfs filter-process
filter.lfs.required=true
http.https://codex-test.cro.st.com/.sslverify=false
lfs.https://codex-test.cro.st.com/*.locksverify=true
```

```
$ git lfs env
git-lfs/2.11.0 (GitHub; windows amd64; go 1.14.2; git 48b28d97)
git version 2.27.0.windows.1

LocalWorkingDir=
LocalGitDir=
LocalGitStorageDir=
LocalMediaDir=lfs\objects
LocalReferenceDirs=
TempDir=lfs\tmp
ConcurrentTransfers=8
TusTransfers=false
BasicTransfersOnly=false
SkipDownloadErrors=false
FetchRecentAlways=false
FetchRecentRefsDays=7
FetchRecentCommitsDays=0
FetchRecentRefsIncludeRemotes=true
PruneOffsetDays=3
PruneVerifyRemoteAlways=false
PruneRemoteName=origin
LfsStorageDir=lfs
AccessDownload=none
AccessUpload=none
DownloadTransfers=basic,lfs-standalone-file
UploadTransfers=basic,lfs-standalone-file
GIT_EXEC_PATH=C:/Users/frq09419/AppData/Local/Programs/Git/mingw64/libexec/git-core
git config filter.lfs.process = "git-lfs filter-process"
git config filter.lfs.smudge = "git-lfs smudge -- %f"
git config filter.lfs.clean = "git-lfs clean -- %f"
```
You can find attached trace of my git clone command (I have not seen any rejecting line inside). 
[clone_trace.txt](https://github.com/git-lfs/git-lfs/files/4803035/clone_trace.txt)

**Comment by chrisd8088** [comment]
That all seems reasonable; nothing jumps out at me there.  May I ask what's in your repo's `.gitattributes` file?

**Comment by loic-lefort** [comment]
```
$ cat .gitattributes
*.elf filter=lfs diff=lfs merge=lfs -text
*.img filter=lfs diff=lfs merge=lfs -text
*.bin filter=lfs diff=lfs merge=lfs -text
*.stm32 filter=lfs diff=lfs merge=lfs -text
*.dtb filter=lfs diff=lfs merge=lfs -text
```

That's strange as in an earlier step, I have migrated my repo to LFS using commands
```
git lfs track "*arch32" "*.bin" "*.stm32" "*.img" "*.elf" "*.dtb" "*basic" "*defconfig"
git lfs migrate import --everything
```
I have played again migration on my original repo and can confirm .gitattributes was correct before "git lfs migrate" but lines about files with no extension have disappeared from .gitattributes file after migration.

In any case, all files were correctly migrated to LFS so they shall be uploaded by git clone even if they are not specified in .gitattributes, no ?

**Comment by chrisd8088** [comment]
Taking your comments in reverse order:
> In any case, all files were correctly migrated to LFS so they shall be uploaded by git clone even if they are not specified in .gitattributes, no ?

IIUC, when you run `git clone` the `Filtering content` step, where the Git LFS smudge filter is called to convert LFS pointer files into full files, will only execute on files which match patterns in `.gitattributes`.  After all, that's the only way Git itself knows anything about Git LFS -- it matches files based on `.gitattributes` patterns, sees `filter=lfs`, and hands off the Git LFS filtetr to do the conversions back and forth between pointer and full files.

So it makes perfect sense to me that if your `.gitatttributes` only lists the file extensions you show in the previous comment, then those are the only things that will get converted into full files on clone or checkout.  In other words, no, just because a pointer file was created at some step doesn't imply in and of itself that Git will notice it and hand it to Git LFS to do something.  Git treats pointer files as just regular Git content; it's the `.gitattributes` patterns which do the work of triggering Git LFS.

---

Now, as to why your `.gitattributes` file would change after running `git lfs migrate`, that's presumably because `git lfs migrate import` will, by default, construct its own list of file extensions.  From the man page for `git-lfs-migrate(1)`:

> If `--no-rewrite` is not provided and `--include` or `--exclude` (`-I`, `-X`, respectively) are given, the `.gitattributes` will be modified to include any new filepath patterns as given by those flags.
>
> If `--no-rewrite` is not provided and neither of those flags are given, the `.gitattributes` will be incrementally modified to include new filepath extensions as they are rewritten in history.

The contents of `.gitattributes` may therefore vary in different branches, depending on their contents and histories, and the history of `.gitattributes` will also change so that file extensions are registered at the same time (i.e., in the same rewritten commit) as corresponding large files are converted to LFS pointer files in the history.

If you can reproduce the exact behaviour you're seeing with a small test repository (which could share), that might be helpful in determining if what you're reporting is actually a bug, or at least confusing behaviour that could be better documented, or if it's just the expected behaviour of `git lfs migrate import` given your specific repository's history and structure.

**Comment by loic-lefort** [comment]
I understand for git clone.

I have created a test repository to reproduce my "git lfs migrate" problem. You can find it attached.
[mig.tar.gz](https://github.com/git-lfs/git-lfs/files/4865363/mig.tar.gz)

To reproduce problem:
tar xzf mig.tar.gz
git clone mig.git
cd mig
git lfs track "*.bin" "*basic"
git lfs migrate import --everything

After "git lfs migrate", rules in .gitattributes about files with no extension have disappeared.

**Comment by chrisd8088** [comment]
Thanks for the test repository!  I was able to reproduce at least some of the inconsistent behaviour you've seen with it.

To be a bit more explicit, one type of problem shows up as follows -- note though that I'm committing the changes created by `git lfs track` before the migration:
```
$ tar xzf mig.tar.gz
$ git clone mig.git
$ cd mig
$ git lfs track "*.bin" "*basic"
$ git add .
$ git commit -m 'add attribs'
$ git lfs migrate import --everything
$ cat .gitattributes
*.bin filter=lfs diff=lfs merge=lfs -text
*basic filter=lfs diff=lfs merge=lfs -text 
```
At this point, things seem OK on the surface -- the `*basic` entry is still in `.gitattributes` --  but if you look back in the rewritten history, the initial commit only includes the `*.bin` entry in `.gitattributes`, but the `1kbasic` file has been converted to an LFS pointer file in that commit.  Which in turn causes problems if you do:
```
$ git rm 1kbasic
$ git commit -m 'delete 1kbasic'
$ git checkout HEAD^^^
$ cat .gitattributes
*.bin filter=lfs diff=lfs merge=lfs -text
$ git lfs ls-files
6356600427 * 1k.bin
b9454f2202 - 1kbasic
```
Now `1kbasic` has been restored into the working tree, but it hasn't been smudged into a full file because `.gitattributes` (as of the current, initial commit) doesn't list the `*basic` entry.  So in this case, although we've retained the no-extension entries in the latest revision of `.gitattributes` (i.e., we're not seeing the problem as you describe it), older commits have been rewritten such that their `.gitattributes` revisions don't match the full set of files which have been converted into LFS pointer files in those commits.  (Note that the `git lfs ls-files` command uses a hyphen to indicate that the file is a pointer that hasn't been converted into a full file.)

---

Conversely, if you don't commit the `git lfs track` changes and then accept the `git lfs migrate import` prompt to overwrite your working copy, well, it's sort of expected that whatever was in `.gitattributes` will be lost.  So I don't find it too surprising in this case (because we didn't commit the `.gitattributes` as it was created by `git lfs track`) that it only shows the `*.bin` filter entry.

However, what seems unfortunate to me is that (a) the `1kbasic` file is still converted into an LFS pointer file, and (b) none of the LFS pointer files are smudged into full files:
```
$ tar xzf mig.tar.gz
$ git clone mig.git
$ cd mig
$ git lfs track "*.bin" "*basic"
$ git lfs migrate import --everything
migrate: override changes in your working copy? [Y/n] y
$ cat .gitattributes 
*.bin filter=lfs diff=lfs merge=lfs -text
$ git lfs ls-files
8a39daadb5 - 1k.bin
b9454f2202 - 1kbasic
cc09c1ed15 - 2k.bin
```

We also have the same problem as in the other case where the older commits have been rewritten too such that the `1kbasic` files has been converted, but `.gitattributes` doesn't list an appropriate filter entry, so checking out those commits leaves the files as pointers:
```
$ git checkout HEAD^
$ cat .gitattributes 
*.bin filter=lfs diff=lfs merge=lfs -text
$ git lfs ls-files
6356600427 * 1k.bin
b9454f2202 - 1kbasic
```

All of which is just to say, thanks again for the test repo, this does help illustrate some issues with the migration command, at least to my mind.  It may take us a while to track down the source of this behaviour, so I'll leave this issue open until then, and we either have some improvements which resolve the issues and/or documentation which describes how to resolve or work around them.

**Comment by vamPierchen** [comment]
I ran into this issue recently. With file system cache disabled (i.e. `core.fscache=false`), actual files pull/clone just fine. With `core.fscache=true` only the pointers are cloned/pulled for extension-less files.

I hope this detail helps narrowing down the range of possible causes.

**Comment by bk2204** [comment]
`core.fscache` is a Git for Windows-specific option and isn't in upstream Git.  If disabling that means that things work for you, then this is probably a Git for Windows bug and not a Git LFS bug unless you can also reproduce it on macOS or Linux.

@chrisd8088, do you perchance remember if you tested the above on Windows or Linux to reproduce?

**Comment by chrisd8088** [comment]
I would have tested the steps in https://github.com/git-lfs/git-lfs/issues/4166#issuecomment-654072795 above on macOS, with circa Git LFS 2.10.  Testing again now with a recent Git LFS shows much better behaviour, where `/1kbasic filter=lfs diff=lfs merge=lfs -text` appears in the `.gitattributes` from the initial (rewritten) commit onwards, so the `1kbasic` file is correctly smudged if you checkout the first commit.

**Comment by bk2204** [comment]
It sounds like this is a bug in Git for Windows, and I'd encourage you to report it there.  If `core.fscache` exhibits broken behaviour, then that's a thing that we can't work around in Git LFS.
