### ISSUE TITLE
git lfs client can build lfs.url with http?

### ISSUE THREAD

**Issue by SURA907** [git-lfs/git-lfs#4173]
**Describe the issue**
git lfs client can build lfs.url with http?

**Additional context**
Hello,
I'm working on Internal network, the server support ssh but not support https
the lfs client build lfs.url with https, like `https://xx/xx/xx.git/info/lfs`
But as I said before  server don't support https, so i should run `git config -f .lfsconfig lfs.url "http://xx/xx/xx.git/info/lfs"` to set lfs.url
after it, when i use ssh to clone repo ,  i have to input username and password againa
it's strange when i use ssh but client ask me username and password
so can i set some config to make lfs.url build with http? I can't find it in git-lfs config.
thanks

**Comment by bk2204** [comment]
Hey,

Currently we don't have support for a pure-SSH based protocol, so an LFS server will authenticate over SSH and then use HTTP or HTTPS to actually speak the LFS protocol.  The SSH endpoint will tell the client what the proper URL is, so if your server is reporting that it's HTTPS, then you need to fix the configuration on your server such that it doesn't report that it uses HTTPS.  You can see an example of the output the remote server sends by running this:

```
$ ssh git@github.com git-lfs-authenticate git-lfs/git-lfs.git download
{
  "href": "https://lfs.github.com/git-lfs/git-lfs",
  "header": {
    "Authorization": "RemoteAuth <sanitized>"
  },
  "expires_at": "2020-06-29T14:30:11Z",
  "expires_in": 599
}
```

If you specifically specify `lfs.url` instead of letting the client autodiscover the URL, then you're telling the client that you want to use a different LFS server than the default and it assumes that autodiscovery isn't appropriate, so authentication has to be done differently.  So if you specify an HTTP URL there, you'll need to authenticate with a username and password (or other credentials, such as Kerberos).  A credential manager may be helpful if you still want to go this route.

You may be able to remove the `lfs.url` option and rewrite URLs using something like the following (in Git configuration, not in `.lfsconfig`):

```
git config lfs.transfer.enablehrefrewrite true
git config lfs.http://xx/.insteadOf https://xx/
```

However, while you're welcome to try it, I don't believe that this affects the batch endpoints, only the object endpoints, so I'm doubtful it will work.

**Comment by SURA907** [comment]
> Hey,
> 
> Currently we don't have support for a pure-SSH based protocol, so an LFS server will authenticate over SSH and then use HTTP or HTTPS to actually speak the LFS protocol. The SSH endpoint will tell the client what the proper URL is, so if your server is reporting that it's HTTPS, then you need to fix the configuration on your server such that it doesn't report that it uses HTTPS. You can see an example of the output the remote server sends by running this:
> 
> ```
> $ ssh git@github.com git-lfs-authenticate git-lfs/git-lfs.git download
> {
>   "href": "https://lfs.github.com/git-lfs/git-lfs",
>   "header": {
>     "Authorization": "RemoteAuth <sanitized>"
>   },
>   "expires_at": "2020-06-29T14:30:11Z",
>   "expires_in": 599
> }
> ```
> 
> If you specifically specify `lfs.url` instead of letting the client autodiscover the URL, then you're telling the client that you want to use a different LFS server than the default and it assumes that autodiscovery isn't appropriate, so authentication has to be done differently. So if you specify an HTTP URL there, you'll need to authenticate with a username and password (or other credentials, such as Kerberos). A credential manager may be helpful if you still want to go this route.
> 
> You may be able to remove the `lfs.url` option and rewrite URLs using something like the following (in Git configuration, not in `.lfsconfig`):
> 
> ```
> git config lfs.transfer.enablehrefrewrite true
> git config lfs.http://xx/.insteadOf https://xx/
> ```
> 
> However, while you're welcome to try it, I don't believe that this affects the batch endpoints, only the object endpoints, so I'm doubtful it will work.
- Thank you very much, the href field is not returned by the intranet server, I will try to append it

**Comment by SURA907** [comment]
@bk2204 it works! thank u!

**Comment by ideepblue** [comment]
> You may be able to remove the `lfs.url` option and rewrite URLs using something like the following (in Git configuration, not in `.lfsconfig`):
> 
> ```
> git config lfs.transfer.enablehrefrewrite true
> git config lfs.http://xx/.insteadOf https://xx/
> ```
> 
> However, while you're welcome to try it, I don't believe that this affects the batch endpoints, only the object endpoints, so I'm doubtful it will work.

I tried `lfs.transfer.enablehrefwrite`. The corresponding rewrite config should be `git config url.http://xx/.insteadOf https://xx/`

**Therefore, the following commands are correct.**

```
git config lfs.transfer.enablehrefrewrite true
git config url.http://xx/.insteadOf https://xx/
```

It was mentioned in docs https://github.com/git-lfs/git-lfs/blob/main/docs/man/git-lfs-config.adoc:

> * `lfs.transfer.enablehrefrewrite`
>
> If set to true, this enables rewriting href of LFS objects using `url.*.insteadof/pushinsteadof` config. `pushinsteadof` is used only for uploading, and `insteadof` is used for downloading and for uploading when `pushinsteadof` is not set.
