### ISSUE TITLE
Roadmap & planned deprecations?

### ISSUE THREAD

**Issue by patricklangsonos** [git-lfs/git-lfs#4189]
**Describe the issue**

I'm trying to get some more details on what the roadmap is for Git-LFS since I'm working on some plugin updates to make it work in Jenkins. Right now we're speculating (https://issues.jenkins-ci.org/browse/JENKINS-59139) that since git-lfs-clone was deprecated, that other commands such as git-lfs-checkout, pull or fetch could also be slated for deprecation. https://github.com/git-lfs/git-lfs/pull/3303 seems to indicate that checkout is no longer deprecated, but that doesn't provide any clarification around fetch or pull.

I see a GitHub project here, but it has no updates since 2019. Is there anything you can share so that other open source projects can help align their support with the current & future usage of LFS? I'm also happy to take this to another forum (public Zoom meeting, mailing list, ...) if there's a better place for this discussion. Thanks for any help you can provide!

**Comment by bk2204** [comment]
Hey,

We aren't currently using the project board and are instead tracking things in issues.  That isn't much help, I know, but it's what we're doing.

`git lfs clone` is no longer deprecated, but we won't be adding additional `git clone` flags that may come up.  Unless you need the `-I` or `-X` flags, you should definitely just be using `git clone`; those flags are the reason we decided to rescind the deprecation.

The other tools are not deprecated and can be used as normal.  The manual pages describe their state accurately (and we try hard to keep them up to date).  We do recommend using the standard Git commands when those meet your needs.

There likely won't be a 3.0 until we add the native SSH protocol; that is planned but for an indefinite point in the future.  Since that requires a major amount of work and we're preferring smaller projects right now, there isn't a definite plan for a timeline.  Because we honor SemVer, we won't be making breaking changes (that aren't actual bug fixes) until 3.0.

**Comment by patricklangsonos** [comment]
thanks! That helps. When you do move to 3.0 - will there be some strategy such as using a lfs3 alias or some other Git setting to choose what version to use?

**Comment by bk2204** [comment]
No, we don't plan on using an alias.  Almost nobody is going to ship multiple versions of Git LFS (or most other software) and so folks will have to deal with any incompatibilities at that point.  Adding such a capability would benefit very few users, and we didn't add one for v2.  I will say that due to the way Git works, it's unlikely that we'd be able to make substantial breaking changes anyway, and that was true of v2 as well.
