### ISSUE TITLE
Can't restore access to specific assets because they are broken containing a GIT LFS HASH and nothing more.

### ISSUE THREAD

**Issue by nicolaefilat** [git-lfs/git-lfs#4191]
**Describe the issue**
I am openning this issue because I want to remove git lfs from my repo and continue working only with the code base and the assets and stuff to be saved locally not on the cloud. The issue I am experiencing is that once I used git lfs to track files with extension .unity, .fbx and now those files are broken and I can't use them.

This is an example of what an .fbx file contains

```
version https://git-lfs.github.com/spec/v1
oid sha256:e4f63c2798a985227ae82ee1d696dc25572516e2e9c90647855dcad3b28a7f36
size 14171552
```
Now,I can't open the file and can't do anything with it unfortunately. I tried running `git migrate export --include=".fbx" --everything` and the same for .unity.
Funny thing, it asks me for the changes to override my directory but nothing really happens in my directory. The file is still broken and I can't open it in any program because the contents were replaced by the text above.

**command log** 
```
migrate: override changes in your working copy? [Y/n] y
migrate: changes in your working copy will be overridden ...
migrate: Sorting commits: ..., done
migrate: Rewriting commits: 100% (209/209), done
  IBehaviour_Implementation     ebe56684d43fb6053867da218df6a09abcefa6d0 -> 1ffca423bd66babcadb015a622a4847b13e4ecf5
  animations                    16a6e5dea7c0d68688ea4b7c5557da91e8511420 -> bdffe54f7269ae987cd4249c65b0db5e3a14eef8
  improvednavigation            414ae802cfc18e441e617e7e141b52a69c89e6f9 -> 21c3d2d52ac66db12878edc15d20ffe485f384b4
  master                        ea4db185548d3d3aa60b1f66af2cb01e88c7837c -> 2402ef095e50d2f23169f590c05051d6385a4857
migrate: Updating refs: ..., done
migrate: checkout: ..., done
prune: 335 local object(s), 337 retained, done
```

**Output of `git lfs env`**
```
git-lfs/2.7.1 (GitHub; windows amd64; go 1.11.5; git 6b7fb6e3)
git version 2.21.0.windows.1

Endpoint=https://github.com/nickk2002/AI-Covid-19.git/info/lfs (auth=none)
LocalWorkingDir=E:\Quick access\Documents\Info\GitHub\AI-Covid-19
LocalGitDir=E:\Quick access\Documents\Info\GitHub\AI-Covid-19\.git
LocalGitStorageDir=E:\Quick access\Documents\Info\GitHub\AI-Covid-19\.git
LocalMediaDir=E:\Quick access\Documents\Info\GitHub\AI-Covid-19\.git\lfs\objects
LocalReferenceDirs=
TempDir=E:\Quick access\Documents\Info\GitHub\AI-Covid-19\.git\lfs\tmp
ConcurrentTransfers=3
TusTransfers=false
BasicTransfersOnly=false
SkipDownloadErrors=false
FetchRecentAlways=false
FetchRecentRefsDays=7
FetchRecentCommitsDays=0
FetchRecentRefsIncludeRemotes=true
PruneOffsetDays=3
PruneVerifyRemoteAlways=false
PruneRemoteName=origin
LfsStorageDir=E:\Quick access\Documents\Info\GitHub\AI-Covid-19\.git\lfs
AccessDownload=none
AccessUpload=none
DownloadTransfers=basic
UploadTransfers=basic
GIT_EXEC_PATH=C:/Program Files/Git/mingw64/libexec/git-core
GIT_LFS_PATH=C:\Program Files\Git LFS
git config filter.lfs.process = ""
git config filter.lfs.smudge = ""
git config filter.lfs.clean = ""
```

**Additional context**
Any other relevant context about the problem here.
Although I ran `git lfs uninstall` and deleted all the lfs related stuff in the .gitattributes they magically appeared again in the file.
Initially when I was trying to run migrate export command I got an out of data quota error. I purchased from github data only to be able to run the command and remove git lfs from system.

**Comment by chrisd8088** [comment]
Hey, I'm sorry to hear you're having trouble.

One quick thing ... have you tried running `git lfs migrate export --include="*.fbx,*.unity" --everything`, making sure to include the `*` wildcard character?  Otherwise I don't believe `git lfs migrate` will match your files.

I would also double-check to make sure you've listed all the file extensions from `.gitattributes`, in case there are others which your initial `git lfs migrate import` may have migrated for you.  You're looking for lines like `*.fbx filter=lfs diff=lfs merge=lfs -text` in `.gitattributes`.

The short text file contents you describe are the way Git LFS works -- large files are replaced in the Git repository itself with short text "pointer" files, and then in your working tree, the pointer text is replaced with the expected file contents whenever you fetch, checkout, etc.  The large file contents are not in the Git repo at all; they're in separate storage from which they are fetched on demand to flesh out the files in your working tree.

I would think that a good first step before trying to export and uninstall is to start by ensuring you have Git LFS installed on your local machine (i.e., `git lfs env` works) and then making a fresh clone of your repo.  Assuming Git LFS is installed correctly, you should see your LFS-managed files populating your working tree with their expected full contents.  However, doing something like the following should reveal that it's being handled as a pointer file in the Git repo itself:
```
$ git show 'HEAD:/path/to/file.fbx'

version https://git-lfs.github.com/spec/v1
oid sha256:e4f63c2798a985227ae82ee1d696dc25572516e2e9c90647855dcad3b28a7f36
size 14171552
```

Now if you run `git lfs migrate export --everything --include '*.fbx,*.unity,*.png,...'` (making sure to list all the relevant file extensions from `.gitattributes`, and using wildcards for each) that should migrate everything back to a full file in the Git repository.

**Comment by nickk2002** [comment]
Hi thank you for the comment.
I run the command as set but it did not retrieve my files back. I can't clone the git repo because it only contains the code and no assets. So I can't clone to get back the assets. Why does the `git lfs migrate export ` not work? I am pretty sure that git lfs is properly installed on my system.

**Comment by chrisd8088** [comment]
Does `git lfs env` still report:
```
git config filter.lfs.process = ""
git config filter.lfs.smudge = ""
git config filter.lfs.clean = ""
```

If so, you will need to re-install Git LFS to ensure those read:
```
git config filter.lfs.process = "git-lfs filter-process"
git config filter.lfs.smudge = "git-lfs smudge -- %f"
git config filter.lfs.clean = "git-lfs clean -- %f"
```

That sets up Git (not Git LFS, but Git itself) so that when you clone, fetch, etc., the "smudge" filter will kick in for any LFS pointer files found in the working tree and convert them into full files in your working tree by downloading the actual large file content from the LFS server.

Because your repo is public I took the liberty of cloning a copy myself, and it was correctly populated by Git LFS with full files, and then I was able to successfully run `git lfs migrate export --everything --include '*.fbx,*.unity,*.png,*.tga'`.  But I had to start with a clone and a working Git LFS setup first.
