### ISSUE TITLE
Feature Request: Retry HTTP/2 413's with HTTP/1.1

### ISSUE THREAD

**Issue by damccorm** [git-lfs/git-lfs#4211]
**Describe the issue**
Right now, HTTP/2 is the default for LFS. This means that when it sends requests, it includes a content-length, which can be quite large for large files. This causes some issues for some server management software, notably IIS. IIS, for example, by default [restricts content-length to <30MB](https://docs.microsoft.com/en-us/iis/configuration/system.webserver/security/requestfiltering/requestlimits/#attributes). I'm writing from the Azure DevOps repos team, where that limit has been bumped to 128 MB, but is still causing all sorts of issues - see [here](https://developercommunity.visualstudio.com/content/problem/862165/cant-push-large-git-lfs-files-to-repository-from-p.html) and some conversation downthread  in #3875 - basically, it means that any file >128MB can't be pushed. We could up that limit further, but by doing so we'd be upping our exposure to DOS attacks, and we don't want to raise it arbitrarily high.

When these failures do occur, they fail with a 413 error code - I'm suggesting retrying any of these 413s that occur with HTTP/2 using HTTP/1.1. Since HTTP/1.1 uses chunked transfer, that avoids this limitation (since each chunk is relatively small).

**System environment**
I reproed on an Azure Pipelines hosted Ubuntu-18.04 machine, full spec [here](https://github.com/actions/virtual-environments/blob/main/images/linux/Ubuntu1804-README.md), and a link to the repro [here](https://dev.azure.com/damccorm-repros/lfs-afd/_build/results?buildId=896&view=logs&j=12f1170f-54f2-53f3-20dd-22fc7dff55f9&t=5caf77c8-9b10-50ef-b5c7-ca89c63e1c86)

**Output of `git lfs env`**
```
git-lfs/2.11.0 (GitHub; linux amd64; go 1.13.4)
git version 2.28.0

Endpoint=https://damccorm-repros@dev.azure.com/damccorm-repros/lfs-afd/_git/lfs-afd.git/info/lfs (auth=none)
LocalWorkingDir=/home/vsts/work/1/s
LocalGitDir=/home/vsts/work/1/s/.git
LocalGitStorageDir=/home/vsts/work/1/s/.git
LocalMediaDir=/home/vsts/work/1/s/.git/lfs/objects
LocalReferenceDirs=
TempDir=/home/vsts/work/1/s/.git/lfs/tmp
ConcurrentTransfers=8
TusTransfers=false
BasicTransfersOnly=false
SkipDownloadErrors=false
FetchRecentAlways=false
FetchRecentRefsDays=7
FetchRecentCommitsDays=0
FetchRecentRefsIncludeRemotes=true
PruneOffsetDays=3
PruneVerifyRemoteAlways=false
PruneRemoteName=origin
LfsStorageDir=/home/vsts/work/1/s/.git/lfs
AccessDownload=none
AccessUpload=none
DownloadTransfers=basic,lfs-standalone-file
UploadTransfers=basic,lfs-standalone-file
BUILD_REPOSITORY_GIT_SUBMODULECHECKOUT=False
GIT_EXEC_PATH=/usr/lib/git-core
GIT_TERMINAL_PROMPT=0
git config filter.lfs.process = "git-lfs filter-process"
git config filter.lfs.smudge = "git-lfs smudge -- %f"
git config filter.lfs.clean = "git-lfs clean -- %f"
```

**Comment by bk2204** [comment]
Hey,

I'm not sure that we want to do this, and let me explain a little bit why.

First of all, this repository is the reference implementation of Git LFS, but it is far from the only client implementation.  There are various others, and any change we made here to do this would need to be replicated across every client.  We really try hard not to special-case implementations, including GitHub's, unless we introduced an incompatible change.  We did add an option to turn off non-application/octet-stream Content-Type headers (which broke Bitbucket) when we made that change, but I believe there's already an option for HTTP/1.1 that makes Azure DevOps work.

Additionally, HTTP 413 by itself means that the request payload is too large, and since this is a client error, the client generally should not repeat the request without doing something different.  While for Azure DevOps it means that the file should be retried over HTTP/1.1, for GitHub it means that the batch request has too many objects in it.  So there isn't a single behavior that works here for all servers and provides a uniform semantic meaning.  (And I should point out that at GitHub, we do see users sending batch request sizes that are larger than this client sends that get a 413, so this means that people are using other clients).

Finally, when I'm unsure about what decision to make while working with Git LFS, I generally try to consider what Git has done, and learn from that.  Several years back, Git turned off sending the `Expect: 100-continue` header because Google's HTTP servers didn't speak HTTP/1.1 properly.  However, we later found that doing so broke Negotiate (Kerberos) support, which requires that header be sent so authentication works properly with large pushes.  So having seen (and fixed) that special case behavior, I'm not inclined to repeat adding a special case here.  We don't know that we won't accidentally break or DDoS some other server implementation by making such a change.

If I may offer some experience, implementer-to-implementer, it may be helpful to put your LFS bulk transfers on their own subdomain and front them with something like HAProxy.  That would allow your general backends to limit the DDoS potential by using a much smaller Content-Length, while allowing your LFS bulk data transfers to have a much larger limit.  The LFS protocol is designed to let that work.

That doesn't deal with the infidelities of IIS and Kerberos and NTLM support, which don't work over HTTP/2.  I don't have a good solution for this except possibly disabling HTTP/2 support for your LFS endpoints or fronting them with a different HTTP server (or fixing IIS).  Since users have to force HTTP/1.1 in this situation anyway, that seems to be another reason not to add a special case here.  We (and Git) have an option to do that, so there is a way to make things work, even if it's inconvenient.

I appreciate that this probably wasn't the response you were hoping for, but I think for the reasons I've mentioned, adding a special case here for Azure DevOps isn't a good idea.  Hopefully y'all can find a good way forward, and if we can offer any advice on how to make things work better, please let us know.

**Comment by damccorm** [comment]
Thanks for the thoughtful response - that definitely makes sense, I can't say I'm shocked that you don't want to do this. Appreciate you taking the time to clarify/make some suggestions

**Comment by edorgeville** [comment]
Leaving a comment here as this known issue is undocumented on Azure's side. 
I was facing this HTTP/2 413 issue using git-lfs with Azure Devops.
The following workaround allowed me to push my 500MB+ files:
```bash
git config http.version HTTP/1.1
git config http.postBuffer 629145600 # Set this to something higher than your largest file
git config lfs.concurrenttransfers 1
```
