### ISSUE TITLE
How to modify batch size through command line parameters

### ISSUE THREAD

**Issue by lamick** [git-lfs/git-lfs#4225]
How to modify batch size through command line parameters, not by modifying the source code. My project has a lot of files, I hope the batch size can be greater than 100.

**Comment by bk2204** [comment]
Hey,

The batch size is not configurable.  It wouldn't be useful to configure from the command line because usually the push happens via `git push`, which doesn't allow passing command-line arguments to the hook that actually does the LFS pushing.

In addition, some implementations, such as GitHub's reject batches that are larger than the default.  You can imagine that a 10000-item batch might cause performance problems for a server implementation, for example.
