### ISSUE TITLE
Include man pages in release binaries

### ISSUE THREAD

**Issue by lunaryorn** [git-lfs/git-lfs#4228]
**Describe the issue**
Would you mind to include built manpages in the binary tarballs published on Github releases?

This'd make manpages available to folks which install git lfs locally into their $HOME.

**System environment**
n.a.

**Output of `git lfs env`**
n.a.

**Additional context**
n.a.

**Comment by bk2204** [comment]
Hey,

I'm not intrinsically opposed to the idea, but currently this is a little tricky since we must build Windows binaries on Windows and macOS binaries on macOS (for signing purposes) and neither one has the tools to build the man pages installed by default.  I'll look into what's involved in doing this, and of course we're happy to accept a suitable patch if someone gets to it before me.

**Comment by lunaryorn** [comment]
@bk2204 I'd be perfectly happy if the Linux binaries shipped the manpages :blush:

**Comment by bk2204** [comment]
The `make release` target builds all of the binaries for every platform, so it needs to work across all platforms since we build all of them the same way.  I should have a PR open fairly shortly.
