### ISSUE TITLE
Upload beyoned filesize

### ISSUE THREAD

**Issue by ThomasStrasser** [git-lfs/git-lfs#4233]
**Describe the issue**
Several times if I upload a file or multiple files with git-lfs, they are far beyond their summary filesize. E.g. I added one file with  115MB and it still uploads with 1.0GB !!!
  UploadUploading LFS objects:   0% (0/1), 1.0 GB | 637 KB/s

**System environment**
openSUSE Leap 15.0

**Output of `git lfs env`**
git-lfs/2.7.1 (GitHub; linux amd64; go 1.12; git 6b7fb6e3)
git version 2.28.0

LocalWorkingDir=
LocalGitDir=
LocalGitStorageDir=
LocalMediaDir=lfs/objects
LocalReferenceDirs=
TempDir=lfs/tmp
ConcurrentTransfers=3
TusTransfers=false
BasicTransfersOnly=false
SkipDownloadErrors=false
FetchRecentAlways=false
FetchRecentRefsDays=7
FetchRecentCommitsDays=0
FetchRecentRefsIncludeRemotes=true
PruneOffsetDays=3
PruneVerifyRemoteAlways=false
PruneRemoteName=origin
LfsStorageDir=lfs
AccessDownload=none
AccessUpload=none
DownloadTransfers=basic
UploadTransfers=basic
GIT_BRANCH=
GIT_EXEC_PATH=/opt/work/git-2.28.0
git config filter.lfs.process = "git-lfs filter-process"
git config filter.lfs.smudge = "git-lfs smudge -- %f"
git config filter.lfs.clean = "git-lfs clean -- %f"

**Additional context**
It would be nice if git-lfs can show more information: e.g. which files are uploading? + status how much of the current file is uploaded.

**Comment by bk2204** [comment]
Hey,

This is because, for whatever reason, the upload is failing.  We retry several times to upload the file, and if all of them fail, we'll then print an error message.  We have really uploaded a full gigabyte of data in this case, but it's failed at some point.  If you want to see which files are causing problems and the output, you can use `GIT_TRACE=1 GIT_TRANSFER_TRACE=1 GIT_CURL_VERBOSE=1` to see more.

**Comment by bk2204** [comment]
Hey,

Since this hasn't seen any response in over a year, I'm closing it.  If you still have questions, please open a new discussion.
