### ISSUE TITLE
problem using git lfs in azure pipeline

### ISSUE THREAD

**Issue by luzlozanothermo** [git-lfs/git-lfs#4239]
I have an azure git repo where i'm using lfs for large .zip files, for this git repo i have an azure pipeline which pipeline.yaml  build the docker container that uses the large .zip files, the check out of the pipeline job is failing with the following message:

git checkout --progress --force c1ad4b1b6d7c15e359ed3add19c09c3d61d8f4ca
git-lfs filter-process: 1: git-lfs filter-process: git-lfs: not found
error: packet write with format failed
error: Could not write client identification
error: initialization for subprocess 'git-lfs filter-process' failed
fatal: myFile.zip: smudge filter lfs failed
##[error]Git checkout failed with exit code: 128

I have tried with checkout step enabling lfs as follow
`steps:
- checkout: self
  lfs: true
- task: Docker@2 
  inputs:
    command: 'build'
    Dockerfile: '**/Dockerfile'
    arguments: '-t $(imageName):$(tag) --build-arg MY_VAR=value --no-cache'
    disableAutoCwd: true
    cwd: '$(system.DefaultWorkingDirectory)'  `
but i keep getting the error 
`git lfs install --local
  git: 'lfs' is not a git command. See 'git --help'.
  The most similar command is
	log
##[error]Git-lfs installation failed with exit code: 1
`

**Additional context**
I have seen many other having the same issue but no clear answer on how to solve it, i saw someone said "manually installing git and lfs" i tried with a cmd task but i had the same error "lfs is not a git command"

**Comment by bk2204** [comment]
Hey,

This error message means that Git LFS isn't installed.  I don't know why that would be the case for Azure Pipelines, since it should be, but this is probably a question you want to ask the Azure Pipelines folks.  They should ship an appropriate version of Git LFS and configure it appropriately in the path so it can be found.  I don't really use Azure Pipelines, and as such am not qualified to speak on why it hasn't been configured appropriately.
