### ISSUE TITLE
Feature to list files with missing pointers

### ISSUE THREAD

**Issue by ArinCantCode** [git-lfs/git-lfs#4241]
**description**
I often run into following issue when checking out:

```
Encountered 15 file(s) that should have been pointers, but weren't:
       <path>.png
       <path>.png
       <path>.png
       <path>.png
       <path>.png
       <path>.png
       <path>.png
       <path>.png
       <path>.png
       <path>.png
       <path>.png
       <path>.png
       <path>.png
       <path>.ttf
       <path>.ttf
```

Which i want to solve by running `git lfs migrate import --no-rewrite <file paths>`
Right now i need to use `git reset --hard` to get list of those files that have missing pointers (i'm doing that during gitlab job after initial checkout) as there is no command or at least none that i'm aware of that would give me exactly this list.

**System environment**
Ubuntu 20.04
git-lfs 2.12.0

**summary**
Create command to list files that should have been pointers but weren't

**Comment by bk2204** [comment]
Hey,

I think this is covered pretty much by #4091, which we're already tracking.  It's a lot easier to do when filtering files because we get things which aren't pointers, but I think we should be able to add something in the future to check which files have problems.

I'm going to close this in favor of that issue, since I think fixing it will address your needs as well.  In the mean time, there's a complicated shell script you could use in that issue if you want to verify this without needing to invoke `git reset --hard`.
