### ISSUE TITLE
Untitled issue

### ISSUE THREAD

**Issue by kitkat1011** [git-lfs/git-lfs#4252]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**System environment**
The version of your operating system, plus any relevant information about platform or configuration (e.g., container or CI usage, Cygwin, WSL, or non-Basic authentication).  If relevant, include the output of `git config -l` as a code block.

**Output of `git lfs env`**
The output of running `git lfs env` as a code block.

**Additional context**
Any other relevant context about the problem here.

**Comment by bk2204** [comment]
Hey,

This issue doesn't describe an actual problem, since you didn't fill out the issue template.  In addition, we try not to include folks' personal information in the title of issues.

Consequently, I'm going to close this issue.  If you can edit this issue to describe an actual problem, we'll be happy to reopen it.
