### ISSUE TITLE
HELP! All files in project are now file pointers

### ISSUE THREAD

**Issue by frios** [git-lfs/git-lfs#4286]
I was trying to push a project up to GitHub and it was rejected due to a large file. So i went through the process of adding large file support. I ran the git lfs migrate command and snow the whole project consists of files like so:

```
version https://git-lfs.github.com/spec/v1
oid sha256:f2eb81f8b428f247ae24b7f8de7f3fe52452f99d4e3aa73400c72f4cb880afed
size 402

```

How do I get my project file back?

**Comment by bk2204** [comment]
Hey,

You probably forgot to run `git lfs install`, which sets up Git so that Git LFS files are checked out automatically.  Once you've done that, try running `git lfs checkout` (or `git lfs pull`) to fix this particular situation.

**Comment by frios** [comment]
That worked great. Am I stuck with LFS now? is there a way I can get back to just regular git?

**Comment by bk2204** [comment]
You can run `git lfs migrate export --everything` to turn things back to Git objects.  Do note that GitHub requires Git LFS for objects over 100 MB; if the file is one you'd rather omit (because it's a binary dependency or something else you didn't really want in your repo), you can use `git filter-branch` to remove it from the history once you've run `git lfs migrate export`.

**Comment by frios** [comment]
Thanks for that information. When I run that command ```git lfs migrate export --everything``` I get the following response:
```fatal: one or more files must be specified with --include```

I thought the ```--everything``` flag would take care of that. Ideas?

**Comment by frios** [comment]
OK I used --include="*.*" and that seems to have done the trick

**Comment by bk2204** [comment]
It sounds like you've got this working, so I'm going to close this issue.
