### ISSUE TITLE
Excessive LFS locking prompt

### ISSUE THREAD

**Issue by oliversalzburg** [git-lfs/git-lfs#4295]
**Describe the issue**
I'm super tired of seeing thid message: 

> Locking support detected on remote "origin". Consider enabling it with: ...

**System environment**
Linux, Windows, any version

**Output of `git lfs env`**
```
git-lfs/2.9.2 (GitHub; linux amd64; go 1.13.5)
git version 2.25.1

Error: Failed to call git rev-parse --git-dir: exit status 128
LocalWorkingDir=
LocalGitDir=
LocalGitStorageDir=
LocalMediaDir=lfs/objects
LocalReferenceDirs=
TempDir=lfs/tmp
ConcurrentTransfers=3
TusTransfers=false
BasicTransfersOnly=false
SkipDownloadErrors=false
FetchRecentAlways=false
FetchRecentRefsDays=7
FetchRecentCommitsDays=0
FetchRecentRefsIncludeRemotes=true
PruneOffsetDays=3
PruneVerifyRemoteAlways=false
PruneRemoteName=origin
LfsStorageDir=lfs
AccessDownload=none
AccessUpload=none
DownloadTransfers=basic,lfs-standalone-file
UploadTransfers=basic,lfs-standalone-file
GIT_EXEC_PATH=/usr/lib/git-core
git config filter.lfs.process = "git-lfs filter-process"
git config filter.lfs.smudge = "git-lfs smudge -- %f"
git config filter.lfs.clean = "git-lfs clean -- %f"
```

**Additional context**

Every single time I clone a project with LFS and then push a commit, I run into this message. I get it! The repo supports LFS! Pretty much every repo in our entire organization does.

What can I do to have this automatically and/or globally enabled? Or how do I suppress the message forever? I don't need this guidance on every single push I make.

**Comment by bk2204** [comment]
Hey,

Sorry to hear this is annoying to you.  I've turned it off myself.  I believe, since this uses the urlconfig code, it should be sufficient for you to set `lfs.locksverify` to `true` (e.g., with `git config --global lfs.locksverify true`).  If you'd like to scope it to a specific server, you should be able to do something like `git config --global lfs.https://github.com/.locksverify true`.  If you don't want to use locking, use `false` instead.

I will point out that we fairly recently did some improvements on the matching there so that it should now work just like the `http.*` options in Git, but the global syntax should work decently far back.

**Comment by oliversalzburg** [comment]
Awesome! I'll give that a try. Thanks

**Comment by oliversalzburg** [comment]
Well that works perfectly for me. Thank you very much

**Comment by GIT-WHITERABBIT** [comment]
Worked perfectly for me Thanks!, though I got stuck on large file issue now and resolve it by splitting file size.

**Comment by NathanSweet** [comment]
Needing to configure every client to not be nagged is not very good.
