### ISSUE TITLE
ident attribute not working for LFS lock enabled files

### ISSUE THREAD

**Issue by bjsenger** [git-lfs/git-lfs#4300]
We have the string "$Id$" embedded within several files. We also have the appropriate "<file_pattern> ident" entry within the .gitattributes file. When a file matching <file_pattern> is cloned, pulled or checked out into a local repository, the "$Id$" is replaced by the latest Commit ID. This works fine for files that are not LFS lock enabled. Unfortunately, this is NOT working for LFS lock enabled files.  We enable a file for locking using the following entry in the .gitattributes file:

<file_pattern> filter=lfs diff=lfs merge=lfs -text lockable

Please help.

**Comment by chrisd8088** [comment]
Hey, I'm sorry to hear you're having this trouble.  Unfortunately I think this is a consequence of the way Git itself handles the `ident` attribute and the corresponding internally-implemented filter, namely, that the `ident` filter runs [first](https://github.com/git/git/blob/e31aba42fb12bdeb0f850829e008e1e3f43af500/convert.c#L1481) and then the `smudge` filter defined by LFS runs [later](https://github.com/git/git/blob/e31aba42fb12bdeb0f850829e008e1e3f43af500/convert.c#L1505-L1506).

So the consequence is that on checkout, the contents of the LFS-managed file -- i.e., a Git LFS "pointer file", which is all that's in the Git repository itself -- is passed to the `ident` filter.  Since these small pointer files have contents which look like the following, there's nothing for the `ident` filter to do.  Here's an example pointer file:
```
version https://git-lfs.github.com/spec/v1
oid sha256:864154b81b91ae782cd8fc7f265912aafa6c36078168f96951d452cab5d99dc7
size 4
```

Then the `smudge` filter defined by Git LFS's entry in your Git configuration file is run; it's passed the pointer file contents which it reads and uses to download the contents of the data file managed in the LFS storage server.  That gets written out into your working tree, and since the `ident` filter has already been run, it isn't run a second time, so there's no chance for it to parse the contents of your data.

You can experiment with this leaving Git LFS completely out of the picture and just using native Git, and see what's going on.  First here's an example which includes both the `ident` attribute and a custom filter, and because the custom filter's `smudge` just writes out its input without change (that's the `cat -` command), the `ident` filter's changes are visible in the file written into the working tree.
```
$ cp ~/.gitconfig ~/.gitconfig.BAK
$ >>~/.gitconfig cat <<EOF
[filter "smudger"]
        required = true
        clean = cat -
        smudge = cat -
EOF

$ git init ident-ok
$ cd ident-ok
$ >.gitattributes echo '*.txt filter=smudger ident'
$ >foo.txt echo 'abc $Id$ def'
$ git add .
$ git commit -m initial

$ cd ..
$ git clone ident-ok ident-ok-copy
$ mv ~/.gitconfig.BAK ~/.gitconfig

$ cat ident-ok-copy/foo.txt 
abc $Id: 7ffd4a080052ec48144eb7c76b3c198fe46a7506 $ def
```

Now let's change the custom filter so that it "smudges" the file's data and replaces it with the string `smudged $Id$ xyz`, and repeat the other test steps:
```
$ cp ~/.gitconfig ~/.gitconfig.BAK
$ >>~/.gitconfig cat <<EOF
[filter "smudger"]
        required = true
        clean = cat -
        smudge = echo 'smudged \$Id\$ xyz'
EOF

$ git init ident-notok
$ cd ident-notok
$ >.gitattributes echo '*.txt filter=smudger ident'
$ >foo.txt echo 'abc $Id$ def'
$ git add .
$ git commit -m initial

$ cd ..
$ git clone ident-notok ident-notok-copy
$ mv ~/.gitconfig.BAK ~/.gitconfig

$ cat ident-notok-copy/foo.txt
smudged $Id$ xyz
```

This time, because our filter replaced the contents of the file _after_ the `ident` filter ran, even though we included a `$Id$` marker in the contents it was never parsed and interpolated by the `ident` filter, so we see `$Id$` in the file contents in the working tree.

Since this is a consequence of how Git implements these filters, I don't think there's anything we can do in Git LFS to ameliorate the problem, and so I'm going to close this issue.  If you find a workaround, though, by all means add a comment!
