### ISSUE TITLE
Hooks in repository

### ISSUE THREAD

**Issue by MonkAlex** [git-lfs/git-lfs#4311]
**Describe the bug**
Sh not run git lfs from hooks.

**To Reproduce**
1. Install git-lfs on PC
2. Init
3. Try to pull existing repo.

Then, git run sh script with sh.exe
sh.exe run some sh.exe
and nothing. sh not run git\git-lfs
Just wait 10 hours, nothing.

**Expected behavior**
Just work.

**System environment**
Windows10
git 2.27
lfs 2.10

**Output of `git lfs env`**
Sorry, its work PC, cannot copy.

**Additional context**
When i replace `git lfs ...` in hooks to `exec git lfs ...`, all completed success. But i not understand, hooks do it work or i broke it?
git-lfs.exe run, but i not see any errors\log output, no idea, do it something or not.

**Comment by bk2204** [comment]
Hey,

I'm not sure why this would be happening.  Things do work correctly on my test system and presumably they work for other people.

It's known that some types of antivirus, firewall programs, and monitoring tools can interfere with Git, the MSYS runtime (including `sh`), and Go binaries such as Git LFS.  Do you have a third-party (i.e., not Windows Defender) antivirus, firewall, or some monitoring tool?

**Comment by MonkAlex** [comment]
Yes, its Kaspersky ENDPOINT SECURITY and i can't disable it on work PC.

Try to search any errors with procmon, but sh just run (find lfs) and do nothing, no idea, why.

So, can u say, when i just run `exec git lfs post-merge...`, its the same logic as `git lfs post-merge...` or not?

**Comment by francocar** [comment]
Il giorno mer 18 nov 2020 alle ore 20:58 MonkAlex <notifications@github.com>
ha scritto:

**Comment by bk2204** [comment]
The behavior is the same if you are not running any commands after the command that uses `exec`.  For our basic hooks, that should be the case.

That may be the best solution if you can't disable any sort of potentially interfering software.  Kaspersky is known to break both WSL and certain Windows programs running in the shell.  If you see this with non-Git LFS invocations in shell scripts, then I'd report this to Git for Windows, since it would be better solved there.
