### ISSUE TITLE
Smudge Error downloading LFS object. Unable to parse pointer at unknown file.

### ISSUE THREAD

**Issue by shawnpan333** [git-lfs/git-lfs#4317]
**Describe the issue**
I can not download a LFS object from my repo on Bitbucket. There is a Smudge Error: Error downloading <filename> (<file id>): EOF.
This happened when I tried to pull latest changes to my local repository. 

**System environment**
Mac mini(M1 2020)
Big Sur: 11.0.1
Git Server: Bitbucket
Git Software: Sourcetree
git config -l:
```
credential.helper=osxkeychain
user.name=<username>
user.email=<email>
core.excludesfile=/Users/<username>/.gitignore_global
difftool.sourcetree.cmd=opendiff "$LOCAL" "$REMOTE"
difftool.sourcetree.path=
mergetool.sourcetree.cmd=/Applications/Sourcetree.app/Contents/Resources/opendiff-w.sh "$LOCAL" "$REMOTE" -ancestor "$BASE" -merge "$MERGED"
mergetool.sourcetree.trustexitcode=true
filter.lfs.clean=git-lfs clean -- %f
filter.lfs.smudge=git-lfs smudge -- %f
filter.lfs.process=git-lfs filter-process
filter.lfs.required=true
commit.template=/Users/<username>/.stCommitMsg
core.repositoryformatversion=0
core.filemode=true
core.bare=false
core.logallrefupdates=true
core.ignorecase=true
core.precomposeunicode=true
remote.origin.url=<url>
remote.origin.fetch=+refs/heads/*:refs/remotes/origin/*
branch.master.remote=origin
:
```

**Output of `git lfs env`**(Sorry, I can not put this section into a code block)
```
git-lfs/2.12.1 (GitHub; darwin amd64; go 1.15.3; git 85b28e06)
git version 2.24.3 (Apple Git-128)

Endpoint=https://<url>/info/lfs (auth=basic)
LocalWorkingDir=/<local path>
LocalGitDir=<local path>
LocalGitStorageDir=<local path>
LocalMediaDir=<local path>/lfs/objects
LocalReferenceDirs=
TempDir=<local path>/lfs/tmp
ConcurrentTransfers=8
TusTransfers=false
BasicTransfersOnly=false
SkipDownloadErrors=false
FetchRecentAlways=false
FetchRecentRefsDays=7
FetchRecentCommitsDays=0
FetchRecentRefsIncludeRemotes=true
PruneOffsetDays=3
PruneVerifyRemoteAlways=false
PruneRemoteName=origin
LfsStorageDir=<local storage dir>/.git/lfs
AccessDownload=basic
AccessUpload=basic
DownloadTransfers=basic,lfs-standalone-file
UploadTransfers=basic,lfs-standalone-file
GIT_EXEC_PATH=/Applications/Xcode.app/Contents/Developer/usr/libexec/git-core
git config filter.lfs.process = "git-lfs filter-process"
git config filter.lfs.smudge = "git-lfs smudge -- %f"
git config filter.lfs.clean = "git-lfs clean -- %f"
```

**Additional context**
The result of running `GIT_CURL_VERBOSE=1 GIT_TRACE=1 git-lfs smudge <  "Pinball Demo/Assets/Resources/Font/TMP Font/DoHyeon-Regular SDF.asset"`:
```
11:26:21.106674 trace git-lfs: exec: git 'version'
11:26:21.134292 trace git-lfs: exec: git '-c' 'filter.lfs.smudge=' '-c' 'filter.lfs.clean=' '-c' 'filter.lfs.process=' '-c' 'filter.lfs.required=false' 'rev-parse' '--git-dir' '--show-toplevel'
11:26:21.155578 trace git-lfs: exec: git 'config' '-l'
11:26:21.172395 trace git-lfs: exec: git 'rev-parse' '--is-bare-repository'
11:26:21.188148 trace git-lfs: exec: git 'config' '-l' '--blob' ':.lfsconfig'
11:26:21.205838 trace git-lfs: exec: git 'config' '-l' '--blob' 'HEAD:.lfsconfig'
11:26:21.222550 trace git-lfs: Install hook: pre-push, force=false, path=<local path>/.git/hooks/pre-push, upgrading...
11:26:21.222730 trace git-lfs: Install hook: post-checkout, force=false, path=<local path>/.git/hooks/post-checkout, upgrading...
11:26:21.222811 trace git-lfs: Install hook: post-commit, force=false, path=<local path>/.git/hooks/post-commit, upgrading...
11:26:21.222887 trace git-lfs: Install hook: post-merge, force=false, path=<local path>/.git/hooks/post-merge, upgrading...
**file data**(The file data can be downloaded, and is identical to the file on another computer)
Pointer file error: Unable to parse pointer at: "<unknown file>"
```

**Comment by duc811997** [comment]
[Uploading wallet.txt…]()

**Comment by chrisd8088** [comment]
Hey, I'm sorry to hear you're having trouble.  Looking around at some similar error [reports](https://github.com/git-lfs/git-lfs/issues/1915), I wonder if you are either experiencing network issues or have one or more bad data files stored in Bitbucket.  You don't give the full error message but I'm guessing you see the EOF on the `Pinball Demo/Assets/Resources/Font/TMP Font/DoHyeon-Regular SDF.asset` file you mention later.  Would you be able to provide an example session using `git clone` or `git fetch` or whatever is reporting the error message?

It might also be helpful to look at (and post here, if possible) the results from `git lfs logs last`.

---

I think you're on the right track trying to track down the specifics by testing `git-lfs smudge` on a specific file.  However, what you would need to pass on stdin to the smudge filter is not the contents of the data file, but the corresponding pointer data.

Assuming you have a good, complete copy of the `DoHyeon-Regular SDF.asset` file in your working tree then you can then generate the corresponding pointer data with `git lfs pointer`.  For example, `git lfs pointer --file "DoHyeon-Regular SDF.asset"` will output the LFS pointer data, which is what is actually stored in the Git repository instead of the full file data.  You should also be able to view this pointer data by using Git to show the contents of the file, e.g., `git show HEAD:"Pinball Demo/Assets/Resources/Font/TMP Font/DoHyeon-Regular SDF.asset"`.  It should look something like:
```
version https://git-lfs.github.com/spec/v1
oid sha256:864154b81b91ae782cd8fc7f265912aafa6c36078168f96951d452cab5d99dc7
size 102949
```

If you now pass that to `git lfs smudge`, you can force it to try downloading the data again from the Bitbucket LFS server, as I think you were trying to do.  For instance, either of these might work:
```
$ git show HEAD:"Pinball Demo/Assets/Resources/Font/TMP Font/DoHyeon-Regular SDF.asset" | \
  GIT_TRACE=1 GIT_TRANSFER_TRACE=1 GIT_CURL_VERBOSE=1 git lfs smudge

$ git lfs pointer --file "Pinball Demo/Assets/Resources/Font/TMP Font/DoHyeon-Regular SDF.asset" | \
  GIT_TRACE=1 GIT_TRANSFER_TRACE=1 GIT_CURL_VERBOSE=1 git lfs smudge
```

One thing to note is that once Git LFS has successfully downloaded the data for the file, it will have a cached copy under `.git/lfs/objects`.  At this point `git lfs smudge` won't need to try downloading as it can just use the cached local copy.  So if you don't get the EOF error on a particular file when testing with `git lfs smudge`, that may be the reason.

**Comment by chrisd8088** [comment]
Closing this as there's been no followup; please re-open if the problem persists.
