### ISSUE TITLE
smudge filter lfs failed.Clone failed, with a problen big file could not be checked out.

### ISSUE THREAD

**Issue by dongxuan0807** [git-lfs/git-lfs#4321]
when i clone the project, due to a big file ,I could not clone successfully.Thank for everyone who can help to resovel this issue.

Downloading *********_Car_Settings/Application/lib/Win32/GL_vs2015_Debug/AndroidDataSource.lib (28 MB)
Error downloading object: *********_Car_Settings/Application/lib/Win32/GL_vs2015_Debug/AndroidDataSource.lib (8593ae7): Smudge error: Error downloading *********_Car_Settings/Application/lib/Win32/GL_vs2015_Debug/AndroidDataSource.lib (8593ae7fcea1dbe9a368d65e9a1bfe70fb80c66aaf198610316e0bc84a5f39b6): batch response: This repository is over its data quota. Account responsible for LFS bandwidth should purchase more data packs to restore access.

Errors logged to C:\_work\_*********\*********_3D_UI\.git\lfs\logs\20201126T161246.1437314.log
Use `git lfs logs last` to view the log.
error: external filter 'git-lfs filter-process' failed
fatal: *********_Car_Settings/Application/lib/Win32/GL_vs2015_Debug/AndroidDataSource.lib: smudge filter lfs failed
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry with 'git restore --source=HEAD :/'

**Comment by chrisd8088** [comment]
Hey, I'm sorry you're having trouble.  It sounds like the problem here is that the account you're using (which I'm guessing is a GitHub account, but maybe not?) has exhausted the LFS storage space which is offered for free, and now is asking you to pay for additional usage.  The key error message is: `This repository is over its data quota. Account responsible for LFS bandwidth should purchase more data packs to restore access.`

You'll need to contact your hosting platform's support team to help, since this repository is only for the open source Git LFS project itself and not any particular LFS hosting platform like GitLab or GitHub.  So if you're using GitHub, you should reach out to [GitHub Support](https://support.github.com/).

**Comment by sshekha3** [comment]
Hey @chrisd8088 
Actually I was creating a new workspace, but it shows the following error

[sshekha3@bgl-ads-1575 polaris_repo]$ git worktree add /nobackup/sshekha3/polaris_repo_upd -b polaris_dev_upd origin/s2c/polaris_dev
Preparing worktree (new branch 'polaris_dev_upd')
Branch 'polaris_dev_upd' set up to track remote branch 's2c/polaris_dev' from 'origin'.
Updating files: 100% (436881/436881), done.

Downloading binos/cman/rp/ngwc/starfleet/device/firmware/io_fpga.upgrade_vulcan_cr1.bin (6.8 MB)

Error downloading object: binos/cman/rp/ngwc/starfleet/device/firmware/io_fpga.upgrade_vulcan_cr1.bin (ba3462e):
Smudge error: Error downloading binos/cman/rp/ngwc/starfleet/device/firmware/io_fpga.upgrade_vulcan_cr1.bin
(ba3462e82c842e2b9ca0a603f3ce929971d8a1e77005869f48858ad4eba0a64d): batch response: Git LFS is disabled for your instance.

Errors logged to /nobackup/sshekha3/polaris_repo/.git/lfs/logs/20210105T135842.078948821.log
Use git lfs logs last to view the log.
error: external filter 'git-lfs filter-process' failed
fatal: binos/cman/rp/ngwc/starfleet/device/firmware/io_fpga.upgrade_vulcan_cr1.bin: smudge filter lfs failed
