### ISSUE TITLE
git lfs migrate import fails if two refs have the same name but are case insensitive

### ISSUE THREAD

**Issue by IAmHughes** [git-lfs/git-lfs#4330]
**Describe the bug**
When working in a repository that has large files, performining `git lfs migrate import --everything --include <extensions>` will go through every `ref` and rewrite history to create lfs pointers. However, due to git on Windows (and I believe Mac) not recognizing case sensitivity, two refs named: `feature1` and `Feature1` are treated as a single ref by the `git lfs migrate import` command.

The problem leads to having a ref that has been rewritten, but then another that has not and needs to be cleaned up manually by editing the `packed-refs` file.

**To Reproduce**
1. Star with a repository that has large files in two branches that are not in LFS, and the two branches with the same name but different case sensitivity (i.e. `feature1` and `Feature1`
2. Run `git lfs migrate import --everything --include <extension>`
3. Run `git log --numstat --all -- <ref/large-file>`
4. Note two shas with the same timestamp and message, however one has been rewritten to a lfs pointer (3 lines) and the other hasn't

**Expected behavior**
When running a `git lfs migrate --everything`, I would expect all refs to be migrated appropriately.

**System environment**
- Windows 10
- Git Bash for Windows (git v2.27, may have been v2.29)

**Output of `git lfs env`**
This was ran on a machine I don't have access too, I can't do this command unfortunately.

**Additional context**
Case sensitivity seems like the root of the issue, though I'm unsure of a path to fix it.

/cc @larsxschneider as you found this for me while debugging.

**Comment by bk2204** [comment]
Hey,

This is unfortunately a limitation of Git on Windows.  Git doesn't support multiple refs differing in case if your file system doesn't preserve them.  While they can happen to exist in the `packed-refs` file, as soon as the ref needs to be rewritten, it will be rewritten as a loose ref in the file system, which takes precedence over the old value in the `packed-refs` file.  Since it's not possible to represent both refs in the file system, it's not possible to rewrite both refs, and when Git LFS tries to do so, it rewrites only the one.  This would likely also happen if you used `git filter-branch`.

If you need to support refs differing only in case, you need to use a case-sensitive file system or (on Windows) directory.  On Windows, you can do this by using WSL as well.

**Comment by larsxschneider** [comment]
@bk2204 Could it be a solution to delete the `packed-refs` file on Windows if `--everything` is passed?

**Comment by bk2204** [comment]
I'm not comfortable tampering with the `.git` directory in that way, since there's a possibility that it could lead to data loss if we make a mistake.  We don't write refs ourselves; this is something we call out to Git to do, so the behavior you're seeing is the behavior that Git has.

**Comment by larsxschneider** [comment]
Yeah, I understand that argument @bk2204 .

What do you think about running something like the following as last action in a `git lfs migrate --import` call on macOS and Windows?
```
$ git show-ref | cut -c 42- | sort --ignore-case | uniq -ic | grep -v '1 refs/'
```
If this commands outputs a result, then we could warn the user about the problem?

**Comment by bk2204** [comment]
Unfortunately, it's not possible to do this in the general case for a couple of reasons:

* We need to use a UTF-8 locale, but it cannot be the user's locale, since the user could be using Turkish, which does not case fold like most Germanic and Romance languages, since it has both a dotted and dotless I.  Unfortunately, we don't know that such a locale exists on the system.
* On Windows, the version of Unicode used in the file system that's used depends on when the file system was formatted.  For example, the behavior could very well differ between a file system formatted under Windows 7 which is then upgraded to Windows 10 and one formatted under Windows 10 originally.
* On some versions of Windows, you can have unmatched surrogates, which can't be mapped to UTF-8 at all.
* On macOS, we need to use a set of custom decomposition rules for Unicode that isn't widely implemented and that also depends on the OS version and the file system in use.  For example, APFS will work differently from HFS+.

So it's nontrivial to perform any sort of case folding the way the file system does without asking the kernel exactly what should be done.  We will invariably produce incorrect results in some circumstances.

**Comment by larsxschneider** [comment]
Thanks for this thorough answer. I also understand and agree to those arguments.

I know I risk to annoy you, but one last try: Would you accept a PR that warns on the `git lfs migrate` `man` page about the issue?

**Comment by bk2204** [comment]
Sure, that's fine.  I think it's fine to state there that Git and Git LFS won't handle refs differing in case when the file system does case folding.
