### ISSUE TITLE
ARM64 native version of git-lfs needed to resolve issues with large files

### ISSUE THREAD

**Issue by walbourn** [git-lfs/git-lfs#4353]
**Describe the bug**
For Surface Pro X or other "Windows on ARM64" devices, the x86 version of git & git-lfs functions for basic scenarios. However, it can easily run out of memory when working with large files. For x64 native the solution is to run the 64-bit native version. There's a git for Windows with arm64 native coming soon, and we need an arm64 version of git-lfs as well.

https://github.com/git-for-windows/git/issues/2346

**To Reproduce**
1. Install git for Windows and git-lfs on a Surface Pro X
2. From a developer command-prompt, try to clone this repo:

```
git clone https://github.com/walbourn/directxtexmedia.git
```

**Expected behavior**
The clone should succeed.

**System environment**
Windows 10 for ARM64 (18363)

**Comment by bk2204** [comment]
Hey,

I think we can probably provide an ARM64 binary here, although since we lack an actual ARM64 platform to build it on, we can't provide an installer or test it to verify it works.  Whether we can sign it depends on whether an AMD64 Windows machine can sign ARM64 binaries.  Knowing what little I do about code signing, I assume that it probably can.

We can revisit the installer and tests if GitHub Actions supports ARM64 Windows in the future and Chocolatey is updated to provide ARM64 binaries for the dependencies we need.

**Comment by bk2204** [comment]
Actually, I just noticed that there isn't currently a port of Go to ARM64 on Windows, so this can't be fixed until golang/go#36439 is fixed.  It appears how quickly that issue progresses depends on Microsoft.

In the meantime, I'd suggest using WSL on ARM64 Windows; it appears that should work and Git LFS should work just fine under an ARM64 Debian.

**Comment by bk2204** [comment]
I think we've release ARM64 Windows binaries, so I'm closing this.
