### ISSUE TITLE
Git-lfs pre-push command hangs in certain repositories

### ISSUE THREAD

**Issue by parnic** [git-lfs/git-lfs#4355]
**Describe the bug**
When attempting to run pre-push hooks in some of my repos, git-lfs hangs and must be ctrl+c'd.

**To Reproduce**
1. Run `git lfs pre-push [remote] [remote_url]`

**Expected behavior**
Push to complete normally.

**System environment**
Windows 10 Version 20H2 (19042.685)

**Output of `git lfs env`**
```
20:52:32.932997 exec-cmd.c:237          trace: resolved executable dir: C:/Program Files/Git/mingw64/bin
20:52:32.937955 git.c:730               trace: exec: git-lfs env
20:52:32.937955 run-command.c:664       trace: run_command: git-lfs env
20:52:32.986824 trace git-lfs: exec: git 'version'
git-lfs/2.13.1 (GitHub; windows amd64; go 1.14.12; git e896fc7a)
git version 2.30.0.windows.1

20:52:33.042817 trace git-lfs: exec: git '-c' 'filter.lfs.smudge=' '-c' 'filter.lfs.clean=' '-c' 'filter.lfs.process=' '-c' 'filter.lfs.required=false' 'rev-parse' 'HEAD' '--symbolic-full-name' 'HEAD'
20:52:33.084728 trace git-lfs: exec: git '-c' 'filter.lfs.smudge=' '-c' 'filter.lfs.clean=' '-c' 'filter.lfs.process=' '-c' 'filter.lfs.required=false' 'rev-parse' '--git-dir' '--show-toplevel'
20:52:33.140555 trace git-lfs: exec: uname
20:52:33.282199 trace git-lfs: exec: cygpath '-w' '.git'
20:52:33.376441 trace git-lfs: exec: cygpath '-w' '[repo_path]'
20:52:33.429366 trace git-lfs: exec: git 'config' '-l'
20:52:33.470226 trace git-lfs: exec: git 'rev-parse' '--is-bare-repository'
20:52:33.509122 trace git-lfs: exec: git 'config' '-l' '--blob' ':.lfsconfig'
20:52:33.551011 trace git-lfs: exec: git 'config' '-l' '--blob' 'HEAD:.lfsconfig'
Endpoint (origin)=[https_origin_url]/info/lfs (auth=basic)
Endpoint (stash)=[https_remote_url]/info/lfs (auth=basic)
LocalWorkingDir=[repo_path]
LocalGitDir=[repo_path]
LocalGitStorageDir=[repo_path]\.git
LocalMediaDir=[repo_path]\.git\lfs\objects
LocalReferenceDirs=
TempDir=[repo_path]\.git\lfs\tmp
ConcurrentTransfers=8
TusTransfers=false
BasicTransfersOnly=false
SkipDownloadErrors=false
FetchRecentAlways=false
FetchRecentRefsDays=7
FetchRecentCommitsDays=0
FetchRecentRefsIncludeRemotes=true
PruneOffsetDays=3
PruneVerifyRemoteAlways=false
PruneRemoteName=origin
LfsStorageDir=[repo_path]\.git\lfs
AccessDownload=basic
AccessUpload=basic
DownloadTransfers=basic,lfs-standalone-file
UploadTransfers=basic,lfs-standalone-file
GIT_CURL_VERBOSE=1
GIT_EXEC_PATH=C:/Program Files/Git/mingw64/libexec/git-core
GIT_SSH=C:\Program Files\PuTTY\plink.exe
GIT_TRACE=1
GIT_TRANSFER_TRACE=1
git config filter.lfs.process = "git-lfs filter-process"
git config filter.lfs.smudge = "git-lfs smudge -- %f"
git config filter.lfs.clean = "git-lfs clean -- %f"
20:52:33.599951 trace git-lfs: filepathfilter: rewrite ".git" as "**/.git/**" (strict: false)
20:52:33.599951 trace git-lfs: filepathfilter: rewrite "**/.git" as "**/.git" (strict: false)
20:52:33.599951 trace git-lfs: filepathfilter: accepting "tmp"
```

**Additional context**
This originally manifested as a Git client (Sublime Merge) hanging when trying to push to certain repos. For the repos that have this problem, I can manually `git push` from the command line without issue, but trying to run the pre-push hook myself (from the same command line) causes the hang.

Issue is similar to #4027, #4020

Full output with tracing (`GIT_TRACE=1 GIT_TRANSFER_TRACE=1 GIT_CURL_VERBOSE=1`) when trying to pre-push:

```
20:49:05.847187 exec-cmd.c:237          trace: resolved executable dir: C:/Program Files/Git/mingw64/bin
20:49:05.852070 git.c:730               trace: exec: git-lfs pre-push [remote] [https_remote_url]
20:49:05.852070 run-command.c:664       trace: run_command: git-lfs pre-push [remote] [https_remote_url]
20:49:05.901926 trace git-lfs: exec: git 'version'
20:49:05.959265 trace git-lfs: exec: git '-c' 'filter.lfs.smudge=' '-c' 'filter.lfs.clean=' '-c' 'filter.lfs.process=' '-c' 'filter.lfs.required=false' 'remote' '-v'
20:49:06.006143 trace git-lfs: exec: git '-c' 'filter.lfs.smudge=' '-c' 'filter.lfs.clean=' '-c' 'filter.lfs.process=' '-c' 'filter.lfs.required=false' 'remote'
20:49:06.056006 trace git-lfs: exec: git '-c' 'filter.lfs.smudge=' '-c' 'filter.lfs.clean=' '-c' 'filter.lfs.process=' '-c' 'filter.lfs.required=false' 'rev-parse' 'HEAD' '--symbolic-full-name' 'HEAD'
20:49:06.098894 trace git-lfs: exec: git '-c' 'filter.lfs.smudge=' '-c' 'filter.lfs.clean=' '-c' 'filter.lfs.process=' '-c' 'filter.lfs.required=false' 'rev-parse' '--git-dir' '--show-toplevel'
20:49:06.154857 trace git-lfs: exec: uname
20:49:06.313604 trace git-lfs: exec: cygpath '-w' '.git'
20:49:06.402733 trace git-lfs: exec: cygpath '-w' '[repo_path]'
20:49:06.481335 trace git-lfs: exec: git 'config' '-l'
20:49:06.527209 trace git-lfs: exec: git 'rev-parse' '--is-bare-repository'
20:49:06.567074 trace git-lfs: exec: git 'config' '-l' '--blob' ':.lfsconfig'
20:49:06.609122 trace git-lfs: exec: git 'config' '-l' '--blob' 'HEAD:.lfsconfig'
```

I've also tried cleaning/unsetting my global/local gitconfig as much as possible to no avail.

**Comment by chrisd8088** [comment]
Hey, I'm sorry you're having trouble.  I fear there's not much to go on here without some more info.

If you run `git lfs pre-push [remote]` manually (replacing `[remote]` with the name of your Git remote), it should normally pause while it waits for input on stdin (as described in the [man page](https://github.com/git-lfs/git-lfs/blob/master/docs/man/git-lfs-pre-push.1.ronn)).  If you hit Ctrl-D (on Unix) or maybe Ctrl-Z on Windows, that should send an EOF and allow the program to proceed.  So I wonder if the "hang" you're experiencing when trying to run it in a manual, standalone manner for testing purposes might just be due to its waiting for input.  Please give this a try to see if a manual invocation of `git lfs pre-push` at least exits normally when sent an EOF.

Are you certain that the stall/hang you experience when running the Sublime Merge program and trying to push is actually caused by the Git LFS `pre-push` hook?  I'm not at all familiar with Sublime's product but I would first start (if you haven't already) by trying to get debug/trace logs from it to nail down the actual point at which it hangs.

One other note -- I notice the trace output you provided suggests there is a `.lfsconfig` file in your repo; you might want to review that as well as the output from `git config -l` to look for anything unexpected there.

If you can confirm that `git lfs pre-push` is truly hanging, and not just waiting for input on stdin, please do include all the relevant configs and logs and we can take another look.

**Comment by parnic** [comment]
Thanks so much for your reply @chrisd8088 

> Hey, I'm sorry you're having trouble. I fear there's not much to go on here without some more info.
> 
> If you run `git lfs pre-push [remote]` manually (replacing `[remote]` with the name of your Git remote), it should normally pause while it waits for input on stdin (as described in the [man page](https://github.com/git-lfs/git-lfs/blob/master/docs/man/git-lfs-pre-push.1.ronn)). If you hit Ctrl-D (on Unix) or maybe Ctrl-Z on Windows, that should send an EOF and allow the program to proceed. So I wonder if the "hang" you're experiencing when trying to run it in a manual, standalone manner for testing purposes might just be due to its waiting for input. Please give this a try to see if a manual invocation of `git lfs pre-push` at least exits normally when sent an EOF.

Ah, I didn't realize that. Yes, I can confirm that sending a ctrl+z on windows allows this command to exit normally.

> Are you certain that the stall/hang you experience when running the Sublime Merge program and trying to push is actually caused by the Git LFS `pre-push` hook? I'm not at all familiar with Sublime's product but I would first start (if you haven't already) by trying to get debug/trace logs from it to nail down the actual point at which it hangs.

If I comment out the contents of my pre-push hook, Sublime Merge is able to complete a push without issue. As soon as I uncomment the `git lfs pre-push "$@"` line in `pre-push`, Sublime Merge starts hanging again on push. That's as far as I've been able to track the issue for the moment. (Note: I'm trying to work with the authors of this program on this as well: https://github.com/sublimehq/sublime_merge/issues/924)

If this is an issue with the client and not git-lfs, please feel free to close this issue.

> One other note -- I notice the trace output you provided suggests there is a `.lfsconfig` file in your repo; you might want to review that as well as the output from `git config -l` to look for anything unexpected there.

There's no .lfsconfig file anywhere on my system, interestingly. Here's a slightly redacted version of my git config output, after removing a few config files to try and reduce the set of variables as much as possible:

```
http.sslbackend=schannel
credential.helper=manager-core
diff.astextplain.textconv=astextplain
filter.lfs.clean=git-lfs clean -- %f
filter.lfs.smudge=git-lfs smudge -- %f
filter.lfs.process=git-lfs filter-process
filter.lfs.required=true
core.editor="C:\\Program Files\\Sublime Text 3\\subl.exe" -w
core.autocrlf=true
core.fscache=true
core.symlinks=true
pull.rebase=true
credential.https://dev.azure.com.usehttppath=true
init.defaultbranch=main
ssh.variant=putty
core.repositoryformatversion=0
core.filemode=false
core.bare=false
core.logallrefupdates=true
core.ignorecase=true
remote.origin.url=[https_origin_url]
remote.origin.fetch=+refs/heads/*:refs/remotes/origin/*
lfs.[https_origin_url]/info/lfs.access=basic
lfs.[https_origin_url]/info/lfs.locksverify=true
branch.main.remote=origin
branch.main.merge=refs/heads/main
user.name=parnic
user.email=github@parnic.com
remote.[remote].url=[https_remote_url]
remote.[remote].fetch=+refs/heads/*:refs/remotes/stash/*
branch.prototyping.remote=[remote]
branch.prototyping.merge=refs/heads/prototyping
lfs.[https_origin_url]/info/lfs.access=basic
```

**Comment by chrisd8088** [comment]
OK, good to know the Ctrl-Z EOF input works as expected.  While you're trying to debug the issue with Sublime Merge, one small idea which occurred to me is that you could edit your `pre-push` hook so that it runs the command with all tracing output captured into a temp log file.  Then you could execute your push in Sublime's client and look at the log to see if and where the `pre-push` command is stalling.

I believe Git on Windows executes hook programs using a version of the bash shell, so you might be able to write something which used Unix-style shell redirections, i.e., changing the `git lfs pre-push "$@"` line in the hook to something like:
```
GIT_TRACE=1 GIT_TRANSFER_TRACE=1 GIT_CURL_VERBOSE=1 git lfs pre-push "$@" 2>/path/to/logs/pre-push.log
```

I don't know if that will help, but it seemed like something you could tinker with until you can capture trace logs from the `pre-push` command *as run by* the Sublime client; maybe those would then give you an answer as to whether it's running at all, running in part, or completing successfully.

**Comment by parnic** [comment]
Great idea! I've done just that. Here's what it spits out:

```
15:49:25.922296 exec-cmd.c:237          trace: resolved executable dir: C:/Program Files/Sublime Merge/Git/mingw64/bin
15:49:25.927306 git.c:703               trace: exec: git-lfs pre-push [remote] [remote_url]
15:49:25.928298 run-command.c:663       trace: run_command: git-lfs pre-push [remote] [remote_url]
15:49:26.011057 trace git-lfs: exec: git 'version'
15:49:26.068926 trace git-lfs: exec: git '-c' 'filter.lfs.smudge=' '-c' 'filter.lfs.clean=' '-c' 'filter.lfs.process=' '-c' 'filter.lfs.required=false' 'remote' '-v'
15:49:26.109793 trace git-lfs: exec: git '-c' 'filter.lfs.smudge=' '-c' 'filter.lfs.clean=' '-c' 'filter.lfs.process=' '-c' 'filter.lfs.required=false' 'remote'
15:49:26.155698 trace git-lfs: exec: git '-c' 'filter.lfs.smudge=' '-c' 'filter.lfs.clean=' '-c' 'filter.lfs.process=' '-c' 'filter.lfs.required=false' 'rev-parse' 'HEAD' '--symbolic-full-name' 'HEAD'
15:49:26.195592 trace git-lfs: exec: git '-c' 'filter.lfs.smudge=' '-c' 'filter.lfs.clean=' '-c' 'filter.lfs.process=' '-c' 'filter.lfs.required=false' 'rev-parse' '--git-dir' '--show-toplevel'
15:49:26.243774 trace git-lfs: exec: uname 
15:49:26.380402 trace git-lfs: exec: cygpath '-w' '.git'
15:49:26.441242 trace git-lfs: exec: cygpath '-w' '[repo_path]'
15:49:26.518031 trace git-lfs: exec: git 'config' '-l'
15:49:26.560894 trace git-lfs: exec: git 'rev-parse' '--is-bare-repository'
15:49:26.600788 trace git-lfs: exec: git 'config' '-l' '--blob' ':.lfsconfig'
15:49:26.643673 trace git-lfs: exec: git 'config' '-l' '--blob' 'HEAD:.lfsconfig'
15:49:26.687556 trace git-lfs: exec: git '-c' 'filter.lfs.smudge=' '-c' 'filter.lfs.clean=' '-c' 'filter.lfs.process=' '-c' 'filter.lfs.required=false' 'show-ref'
15:49:26.741439 trace git-lfs: exec: git '-c' 'filter.lfs.smudge=' '-c' 'filter.lfs.clean=' '-c' 'filter.lfs.process=' '-c' 'filter.lfs.required=false' 'ls-remote' '--heads' '--tags' '-q' '[remote]'
```

**Comment by chrisd8088** [comment]
Yeah, that seems like it's waiting for input on stdin which never comes (those last three `filepathfilter` lines are what you normally get when the `pre-push` command is exiting).  So I would think you'd want next to communicate with the Sublime folks to determine what's going on there -- it seems as though they may be waiting for input *from* Git, instead of sending it, or just somehow not sending an EOF to close the `pre-push` hook's input stream, so you get a stalled pair of processes.  But why that's happening I don't know.

As a workaround, is there a chance your workflow would allow you to just disable the `pre-push` hook entirely?  If not, I guess you'll have to drill further into what's going on with Sublime.

**Comment by parnic** [comment]
I appreciate your time. For now, I'll disable the hook while trying to talk through the issue with them.
