### ISSUE TITLE
Skip uploading of LFS objects to forks, which are known to original repository

### ISSUE THREAD

**Issue by nhnb** [git-lfs/git-lfs#4362]
## 💡 Feature Request

It should be possible to skip uploading of LFS objects to a fork, when the objects are already known to the origin of the fork. This is based on the assumption that both fork and origin share the same LFS storage. This is the case on Github and Gitlab.

An alternative solution would be to check whether the object is known before attempting an upload.

## 🔬 Motivation
 
A rather common Git workflow consists of pulling from an origin remote. But pushing changes to a personal fork of this repository in order to create a pull request.

As a consequence LFS objects are pulled from the original repository and uploaded to the fork. This is problematic because of asynchronous Internet speed. For example on a DSL connection, the maximum downstream might be 16MBit/s, but the upstream may be limited to 1MBit/s. So downloading something may be done in less than four minutes. But uploading it again will take more than an hour.

On Github and Gitlab, both the original repository and the fork, share the same data storage. Therefore uploading LFS objects to the fork, which have been downloaded from the origin, is not necessary. (However, this may not be true in all situations).

Note: There is already some logic in place, which prevents the upload of objects that are known to be available on the server because of other remote branches in the same remote.

**Comment by bk2204** [comment]
Hey,

This is best sent as a feature request to those respective platforms.  The Git LFS client says which objects it wants to upload and the server side reports whether the object exists (in which case, it doesn't provide a URL to upload) or whether the object should be uploaded (in which case, it provides a URL to do so).  That means it's entirely up to the server whether these objects get uploaded again or not and the client has no control over it.

We can't assume on the client side that remotes other than the one we're pushing to share objects, since there's no standard way to tell if two repositories are part of the same repository network, or even if the server side has such a concept.  To do that requires a platform-specific API call and in general we don't know what hosting platform the remote side is using to make that call, nor do we really want to learn how to do that for each platform.

I agree this would be a valuable feature, but since this project is only for the open source Git LFS client, I'd recommend sending this as a feature request to GitHub and GitLab, since they're the ones best equipped to implement it.
