### ISSUE TITLE
Git LFS push extremely slow (20kbps)

### ISSUE THREAD

**Issue by thekiwicoder0** [git-lfs/git-lfs#4363]
I am trying to initialise a repository with a few files around 1 Meg each and storing them in git lfs. 

Running gif-lfs push results super slow transfer and ultimately times outs 

The speed starts around 90k and then drops down to 20/40k.

What could be causing this and how do I debug it?

GIT-LFS ENV:

git-lfs/2.13.1 (GitHub; windows amd64; go 1.14.12; git e896fc7a)
git version 2.19.1.windows.1

Endpoint=https://github.com/TheKiwiCoder-Patreon/Unity.git/info/lfs (auth=basic)
LocalWorkingDir=C:\Dev\TheKiwiCoder\TheKiwiCoderPatreon\Unity
LocalGitDir=C:\Dev\TheKiwiCoder\TheKiwiCoderPatreon\Unity\.git
LocalGitStorageDir=C:\Dev\TheKiwiCoder\TheKiwiCoderPatreon\Unity\.git
LocalMediaDir=C:\Dev\TheKiwiCoder\TheKiwiCoderPatreon\Unity\.git\lfs\objects
LocalReferenceDirs=
TempDir=C:\Dev\TheKiwiCoder\TheKiwiCoderPatreon\Unity\.git\lfs\tmp
ConcurrentTransfers=8
TusTransfers=false
BasicTransfersOnly=false
SkipDownloadErrors=false
FetchRecentAlways=false
FetchRecentRefsDays=7
FetchRecentCommitsDays=0
FetchRecentRefsIncludeRemotes=true
PruneOffsetDays=3
PruneVerifyRemoteAlways=false
PruneRemoteName=origin
LfsStorageDir=C:\Dev\TheKiwiCoder\TheKiwiCoderPatreon\Unity\.git\lfs
AccessDownload=basic
AccessUpload=basic
DownloadTransfers=basic,lfs-standalone-file
UploadTransfers=basic,lfs-standalone-file
GIT_EXEC_PATH=C:/Program Files/Git/mingw64/libexec/git-core
GIT_INSTALL_ROOT=C:\Program Files\Git
GIT_LFS_PATH=C:\Program Files\Git LFS
git config filter.lfs.process = "git-lfs filter-process"
git config filter.lfs.smudge = "git-lfs smudge -- %f"
git config filter.lfs.clean = "git-lfs clean -- %f"

**Comment by bk2204** [comment]
Hey,

Sorry for the delay.  This is likely a network problem of some sort.  Since you're using GitHub, which currently uses Amazon S3 for storage and provides URLs directly there for uploads, you're likely going to be wanting to check network performance to us-east-1.  I believe the domain name is github-cloud.s3.amazonaws.com.

You may also want to check https://github-debug.com/ to see if that shows any particular problems.

If that shows something, I'd suggest contacting your ISP to see if there's a problem; some European ISPs have poor connectivity to Amazon's us-east-1.

Hopefully that's helpful information.
