### ISSUE TITLE
"UnpicklingError: invalid load key, 'v'"

### ISSUE THREAD

**Issue by amaze2** [git-lfs/git-lfs#4366]
Hi and happy new year,
My [Streamlit app ](https://share.streamlit.io/amaze2/concordiensis2/concordy_processor_term_over_time.py)is not working because my Python code cannot open the data, which is in Pickled format, and which I uploaded to GitHub via git-lfs. Instead, I get the following error message: "UnpicklingError: invalid load key, 'v'"; (see attached screenshot). 
I believe the git-lfs upload causing this error; may I ask for your help with this?
Thank you!
Adam
<img width="748" alt="Screen Shot 2021-01-07 at 2 42 50 PM" src="https://user-images.githubusercontent.com/43005538/104225702-bce2ee80-5414-11eb-959d-19b09cc6339c.png">

**Comment by bk2204** [comment]
Hey,

I think this error comes from the fact that Git LFS is not installed on the remote system to check out the Git LFS files, which causes Python's pickle module to try to read the pointer file instead.  I believe that's because, [according to this article](https://discuss.streamlit.io/t/best-practices-for-fetching-artifacts-requried-for-the-app/6538/6), Streamlit may not support Git LFS yet.  I'm unfortunately not at all familiar with Streamlit, so you'd have to ask them the best way to handle this situation.

Sorry I can't be of more help.
