### ISSUE TITLE
Git LFS tries to push all LFS objects back to the repository when a push is initiated from a bare repository worktree

### ISSUE THREAD

**Issue by okcompute** [git-lfs/git-lfs#4377]
**Describe the bug**

I have a local **bare** repository cloned from a very large project with a lot of LFS objects. If I create a worktree from this bare repository and try to push any changes from it, git lfs will try to upload all the LFS objects history:

```git push 
Uploading LFS objects:  98% (15401/15672), 306 GB | 0 B/s                                                                                                     
```
Note: The upload speed is 0 B/s. So probably nothing gets really uploaded. But still, this operation takes an infinite amount of time to complete.

On the other hand, if I create a worktree from a **regular/non-bare** repository, everything works as I would expect (i.e. no attempt to push LFS objects on the remote is made and the push completes immediately).

With my team, we tried to understand the **bare** repository issue to define if this was exclusive to my machine. We were able to reproduce the issue on a colleague's machine with older versions of Git LFS and Git (on macOS Big Sur). On another colleague's machine, with the exact same version of Git LFS and Git, we were not able to reproduce. It turns out, the only difference was the `worktree.guessremote=true` configuration that I had missing. I did set this value in my configuration file and the issue disappeared! It is not clear to me why this configuration resolves the issue!?

So, I have a fix. But I still wanted to share the issue to see if this could be fixed permanently. I will probably forget the solution the next time I create the same setup and this could save times to others :P

**To Reproduce**
Steps to reproduce the behaviour:
1. Clone a bare repository (`git clone --bare <URL>`) 
2. Create a worktree from this bare repository (`git worktree add <path>`)
3. Make a change in the worktree and push to the remote (`git push`). The change doesn't need to apply to an LFS object.
4. See Git LFS trying to push all objects history to the remote repository 

**Expected behaviour**
Since the same steps on a non-bare repository work just fine, I would expect this to work in a bare repository too.

**System environment**
macOS Big Sure (version 11.1)
git 2.30.0
git-lfs 2.13.1

Thank you very much in advance for your assistance!

**Comment by bk2204** [comment]
Hey.

When we push data with Git LFS, we need to push everything that the remote side doesn't have, which means we need to look through the history between any points we know the remote side has (e.g., the old side of the ref being pushed and any remote-tracking branches for that remote) and the new item being pushed.

When you create a bare repository, no remote-tracking branches are created and we therefore must rely on the old value of what's being pushed.  When you use `worktree.guessremote`, the branch is created instead of from `HEAD`, the default branch, to be based off a branch from the same name, if one exists.  As a result, you'll be pushing a reference that already exists, and Git LFS can take advantage of the fact that only the objects between the old and new values need to be pushed.

So this isn't really easily fixable in Git LFS because we have limited information about what's available on the server when you push a single new ref without any history or remote-tracking branches.  You'd be better off either not using a bare repository here or performing a `git fetch origin` to fill in the remote-tracking branches so that Git LFS can optimize the things it pushes that way.

**Comment by okcompute** [comment]
@bk2204 Gotcha! Thank you very much for the explanation and the suggestions. Make sense. I'll close the issue.

**Comment by mbargiel** [comment]
If someone runs into this after cloning a bare repo and `git fetch origin` doesn't actually fix it, make sure the bare repo config includes the following :
```
[remote "origin"]
	fetch = +refs/heads/*:refs/remotes/origin/*
```
In my case, `git fetch origin` was suspiciously fast, and doing nothing. That was strange for a repo that actually has a lot of activity, until I discovered there was no fetch refspec configured. Adding the missing config fixed it, and that in turned solved my Git LFS issue (consistent with @bk2204's answer above).
