### ISSUE TITLE
Git pushing git files into repository.

### ISSUE THREAD

**Issue by Magixxz** [git-lfs/git-lfs#4380]
I only have **_2-3 files_** I am pushing into my repository, but when I go to push it says I have **_7k objects_** getting pushed. I only want **_my files_** and not the **_git files._** _**How do I solve this?**_

**Comment by Magixxz** [comment]
By the way I am working with **_Visual Studio Code_** and pushing **_a bot into my github repository._**

**Comment by bk2204** [comment]
Hey,

Is your question about Git or Git LFS?  If your question is about Git LFS, please fill out the issue template so we can help you.  If your question is about Git and doesn't involve Git LFS, then it would be better to post the output you're seeing in an email to the [Git mailing list](https://git-scm.com/community), since this repository is only for Git LFS, the large file extension.

**Comment by Magixxz** [comment]
@bk2204 Oh okay, thanks.
