### ISSUE TITLE
Where can I find the git-lfs-authenticate command?

### ISSUE THREAD

**Issue by JaapJoris** [git-lfs/git-lfs#4388]
I can successfully push a git repository that uses Git LFS to Github, but when I try to push it to my own server I get the following error: `git-lfs-authenticate: not found`.

    $ git push origin main |& cat
    batch request: sh: 1: git-lfs-authenticate: not found: exit status 127
    Uploading LFS objects:   0% (0/1), 0 B | 0 B/s, done.
    error: failed to push some refs to 'git.example.com:'

On the local host, I use `git-lfs/2.13.2` and on the remote host `git-lfs/2.7.1`. These are the current versions of Debian 10 and 11, respectively. I have tried using [the latest version of Git LFS][1] on both hosts by placing the `git-lfs` binary in `/usr/local/bin`. The output is now slightly different, but I still get the same error:

    $ git push origin main |& cat
    batch request: sh: 1: git-lfs-authenticate: not found: exit status 127
    error: failed to push some refs to 'git.example.com:'

I have also tried searching for a binary named `git-lfs-authenticate` but it is not present in any of the releases of Git LFS. I have also tried reading the [Git LFS Server Documentation][2] which mentions the `git-lfs-authenticate` command, but it doesn't explain where to find it or how to implement it.

Finally, I have tried posting this question to StackOverflow, but I didn't get much response. Since the stated goal in the link above is _"One of the Git LFS goals is to work with supporting Git remotes with as few required configuration properties as possible"_, I'm hoping that someone here can help me figure this out. 

  [1]: https://github.com/git-lfs/git-lfs/releases/latest
  [2]: https://github.com/git-lfs/git-lfs/blob/master/docs/api/server-discovery.md

**Comment by bk2204** [comment]
Hey,

Currently we don't have a pure SSH-based protocol; the feature for that is being tracked in #1044.  As a result, the `git-lfs-authenticate` command creates some sort of temporary token to use with the HTTP-based protocol.  Because of this, the nature of how this command works is specific to your HTTP server implementation since the tokens it issues have to be integrated with the HTTP server.

Depending on your Git LFS HTTP server implementation, you can write your own program to issue appropriate tokens.

My hope is to get to #1044 soon, which should make things a little easier for your use case.

**Comment by JaapJoris** [comment]
Is there _any_ way I can use Git LFS with a server other than GitHub? I don't care if the protocol if SSH, HTTP, or freakin' FidoNet. I would just like to know whether it's an intended use case of Git LFS to transfer large files between two git repositories and, if it is, where I can find the documentation. Thank you!

**Comment by bk2204** [comment]
Yes.  There's an HTTP server implementation you can use at https://github.com/git-lfs/lfs-test-server/.  Despite the name, some folks are using it in production.

**Comment by JaapJoris** [comment]
I am somewhat disappointed. I thought Git LFS was a tool to manage large files in _any_ Git repository. As it currently stands, it seems to be primarily a tool to manage large files in repositories hosted by GitHub. Perhaps the home page and documentation should clarify that **Git LFS is meant to be used with Github only and is not suited for general use**. Or am I mistaken?

**Comment by bk2204** [comment]
No, that's not the case at all.  There are [a variety of implementations, both server and client](https://github.com/git-lfs/git-lfs/wiki/Implementations).  You can mount the remote repository over SFTP (e.g., with SSHFS) and push to it locally; you can use an HTTP-based implementation with the lfs-test-server repository, GitHub, GitLab, Bitbucket, Gitea, or other implementations; or you can use an implementation that's a proxy for a cloud storage bucket.  We just don't support a native SSH-based protocol at the moment, but there are still a lot of options.

**Comment by gebi** [comment]
we are using lfs-test-server together with gitolite eg. on some pretty large installations sinces ages together with our own `git-lfs-authenticate` implementation at https://github.com/mgit-at/lfs-test-server/tree/master/git-lfs-authenticate

@JaapJoris have fun and just ping me if you need some help.

btw... having everything via ssh would be a huge plus, just because a host is reachable via ssh is no guarantee that you can also reach it via http(s) and slurping that via https and a different address (you can point to anything on the ssh side of git-lfs) is really tedious...

**Comment by kemin711** [comment]
Somewhile ago, I installed some program on the server (bare+shared), then I can pull remotely from a different computer with git used as client.  It worked fine. I usually push locally. Now I am retiring this computer.  Replacing it with identical repository, but encountered the same problem discussed in this group.  I could not figure out how exactly I made it to work.  My system is all command line, not involving any https protocol.  I would appreciate some solution only using ssh like the plain old git.  I am not using any fancy git, just the command line version git.  It work very productively for a very long time.  Please let me know if the auth command is implemented. Or any one can tell me the requirements for the git-lfs-authenticate.  I should be able to write the program in any language required in a reasonable amount of time.

**Comment by bk2204** [comment]
We don't ship an actual `git-lfs-authenticate` binary because in general, there's no way to know how to issue tokens for an HTTP server based only on SSH.  You are, of course, free to implement your own.

However, there is a `git-lfs-transfer` binary which can operate over SSH if you're using Git LFS 3.0 or newer.  The reference implementation is [in Rust and called Scutiger](https://github.com/bk2204/scutiger), and, if you have Rust installed, can be installed with `cargo install scutiger-lfs`.

**Comment by kemin711** [comment]
Thanks, I will try both methods.  I should be able to write my own git-lfs-authenticate.
Kemin Zhou 510 862-2276
 

    On Wednesday, January 3, 2024 at 06:44:25 AM PST, brian m. carlson ***@***.***> wrote:  
 
 


We don't ship an actual git-lfs-authenticate binary because in general, there's no way to know how to issue tokens for an HTTP server based only on SSH. You are, of course, free to implement your own.

However, there is a git-lfs-transfer binary which can operate over SSH if you're using Git LFS 3.0 or newer. The reference implementation is in Rust and called Scutiger, and, if you have Rust installed, can be installed with cargo install scutiger-lfs.

**Comment by gebi** [comment]
@kemin711 code for `git-lfs-authenticate` binary ist at https://github.com/mgit-at/lfs-test-server/tree/master/git-lfs-authenticate

it creates a JWT and even encodes permissions into it which our enhanced version of `lfs-test-server` can decode. we needed that years ago because we wanted lfs functionality in gitolite (that's what we are using it for, without the need for huge sw packages like gitlab)

**Comment by kemin711** [comment]
@gebi this is great.  I build a lots of softwares, in most cases, the user does not have to do anything.

**Comment by kemin711** [comment]
@gebi look the original https lfs can be set up, but could not be used failed to checkout (still several days to figure this out).  Now trying the git-lfs-autheticate method.  Do I need to start up the patched lfs-test-server?  If try to start it up, I am getting segfault:

```
./run.sh
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x79a3c0]

goroutine 1 [running]:
debug/elf.(*Section).ReadAt(0xc00022e000?, {0xc000240000?, 0x10400?, 0xc0001ba000?}, 0xb7e119?)
	<autogenerated>:1 +0x20
archive/zip.readDirectoryEnd({0x9330c0, 0xc0001acd80}, 0x214)
	/usr/local/go/src/archive/zip/reader.go:576 +0xf9
archive/zip.(*Reader).init(0xc000194f50, {0x9330c0?, 0xc0001acd80}, 0x214)
	/usr/local/go/src/archive/zip/reader.go:119 +0x50
archive/zip.NewReader({0x9330c0, 0xc0001acd80}, 0x214)
	/usr/local/go/src/archive/zip/reader.go:112 +0x5e
github.com/daaku/go%2ezipexe.zipExeReaderElf({0x932f20?, 0xc0000ac420}, 0xb8e519)
	/home/kzhou/go/pkg/mod/github.com/daaku/go.zipexe@v0.0.0-20150329023125-a5fe2436ffcb/zipexe.go:128 +0x85
github.com/daaku/go%2ezipexe.NewReader({0x932f20, 0xc0000ac420}, 0x0?)
	/home/kzhou/go/pkg/mod/github.com/daaku/go.zipexe@v0.0.0-20150329023125-a5fe2436ffcb/zipexe.go:48 +0x91
github.com/daaku/go%2ezipexe.OpenCloser({0xc000030180?, 0xc00019dd40?})
	/home/kzhou/go/pkg/mod/github.com/daaku/go.zipexe@v0.0.0-20150329023125-a5fe2436ffcb/zipexe.go:30 +0x56
github.com/GeertJohan/go%2erice.init.0()
	/home/kzhou/go/pkg/mod/github.com/!geert!johan/go.rice@v0.0.0-20150223153050-b4a18af23143/appended.go:38 +0x3b
```
I followed the instruction for the run script.

**Comment by kemin711** [comment]
When using lfs-test-server via https, Do we have to use the same ssh key for the git server and the http server?

**Comment by gebi** [comment]
our fork of `lfs-test-server` is thought to be used together with gitolite, did you make the necessary integrations as documented in https://github.com/mgit-at/lfs-test-server/tree/master/git-lfs-authenticate ?

How this all works is, that the client git will execute `git-lfs-authenticate` via ssh, which you need to add as admin defined command to your gitolite (see doku above) and there it get's the jwt to access the lfs objects from our for of `lfs-test-server`.

does the adc (admin defined command) in your gitolite work?

**Comment by kemin711** [comment]
@gebi thanks.  I still got a long way to go.

**Comment by gebi** [comment]
it's not that complicated, our way to deploy is gitolite, so you need to install gitolite https://gitolite.com/gitolite/install.html

That is basically a git config management tool that you "install" into it's own user and which lets you define permissions who can push/pull repos down to the branch level (for push).
so create one dedicated linux user on your remote server, install gitolite into it and clone the gitolite-admin.git repo.

then install the `git-lfs-authenticate` on the server into gitolite as admin defined command (adc) with [this documentation](https://github.com/mgit-at/lfs-test-server/tree/master/git-lfs-authenticate)

then install our forked git-lfs-server and make it reachable via https.
(and no, the ssh key can, or better should not be used for https ;), use eg. let's encrypt for that.
We have all our git-lfs-server behind some nginx proxy and running in a systemd service.

we use something like this to for the systemd unit
```# /etc/systemd/system/lfs-server@.service
[Unit]
Description=GIT LFS Server for %I
After=network.target

[Service]
User=lfs-%i
WorkingDirectory=/srv/lfs/%i
EnvironmentFile=/etc/default/lfs-%i
ExecStart=/opt/lfs/lfs-server
Restart=always
RestartSec=1
PrivateTmp=true
PrivateDevices=true
ProtectSystem=full
ProtectHome=true
CapabilityBoundingSet=~CAP_SYS_ADMIN CAP_DAC_OVERRIDE CAP_SYS_PTRACE
NoNewPrivileges=true
Slice=service.slice

[Install]
WantedBy=multi-user.target
```

that config expects the `lfs-server` config in `/etc/default/lfs-<NAME>`
```LFS_LISTEN=tcp://127.0.0.1:8101
LFS_HOST=git.yourdomain.com
LFS_PATH=/lfs/<NAME>
LFS_SCHEME=https
LFS_SECRET=<create one with openssl rand -base64 32>
LFS_METADB=/srv/lfsmeta/<NAME>.db
LFS_CONTENTPATH=/srv/lfs/<NAME>/content
LFS_PUBLIC=0
LFS_ADMINUSER=
LFS_ADMINPASS=
LFS_USETUS=0
LFS_TUSHOST=localhost:1080
```

we need to have lfs metadata and lfs content on different paths (really volumes) for performance reasons ;)
