### ISSUE TITLE
How does Git-LFS Handle blob updates in a pull request (PR)

### ISSUE THREAD

**Issue by pdemro** [git-lfs/git-lfs#4402]
**Describe the issue**
See below for the scenario.  I am wondering in general if anyone has experience with this and how GitHub/BitBucket/Git-LFS handles this.

1. Repository "A" has a Git-LFS blob, "blob a"
2. Alice Forks Repository A
3. Alice makes an update to "blob a" and pushes
4. Alice opens a PR to Repository A
5. PR is merged into Repository A

**System environment**
OSX.  We are using both BitBucket LFS and GitHub LFS

**Output of `git lfs env`**
This is an exploratory question, I have not set it up yet

**Additional context**
Happy to answer any questions in the area below.  Thanks for looking!

**Comment by chrisd8088** [comment]
Since this is a repo just for work on the Git LFS client, I'm going to close this issue, but you might want to start a [discussion](https://github.com/git-lfs/git-lfs/discussions) if you care to.

For what it's worth, GitHub describes their policies for pushing LFS blobs to forks of a repository in their [documentation](https://docs.github.com/en/github/managing-large-files/collaboration-with-git-large-file-storage#pushing-large-files-to-forks).  I would suggest reaching out to the support teams from them and other LFS service providers if you have specific questions about how they handle these situations.
