### ISSUE TITLE
Error while pulling lfs files with lfs-folderstore plugin

### ISSUE THREAD

**Issue by Tarrke** [git-lfs/git-lfs#4404]
**Describe the issue**
We are two dev using gitlab.com as repository and Mega synced folder as lfs storage. I use the lfs-folder plugin to make this works. The other dev pushed to the repo and the sync folder some large files. When I try to get the files (git pull or git lfs pull) I get errors :
error transferring "9c1f0b8b6d7458c95d1bb17f86538f9650a8c21c725a5910fb73cd4fbd92bbd2": [5] Error creating temp file for "F:\\MegaSyncLOTTS\\9c\\1f\\9c1f0b8b6d7458c95d1bb17f86538f9650a8c21c725a5910fb73cd4fbd92bbd2": open F:\UE Project\lotts\.git\lfs\tmp\9c1f0b8b6d7458c95d1bb17f86538f9650a8c21c725a5910fb73cd4fbd92bbd2.tmp: The file exists.

**System environment**
We are both runing windows 10 and git for Windows.
`http.sslcainfo=C:/Program Files/Git/mingw64/ssl/certs/ca-bundle.crt
http.sslbackend=openssl
diff.astextplain.textconv=astextplain
filter.lfs.clean=git-lfs clean -- %f
filter.lfs.smudge=git-lfs smudge -- %f
filter.lfs.process=git-lfs filter-process
filter.lfs.required=true
core.autocrlf=true
core.fscache=true
core.symlinks=false
core.editor="C:\\Program Files\\Microsoft VS Code\\Code.exe" --wait
pull.rebase=false
credential.helper=manager-core
credential.https://dev.azure.com.usehttppath=true
init.defaultbranch=master
user.name=Tarrke
user.email=Tarrke@gmail.com
filter.lfs.clean=git-lfs clean -- %f
filter.lfs.smudge=git-lfs smudge -- %f
filter.lfs.process=git-lfs filter-process
filter.lfs.required=true
credential.helper=manager
pull.rebase=true
rebase.autostash=true
merge.autostash=true
core.repositoryformatversion=0
core.filemode=false
core.bare=false
core.logallrefupdates=true
core.symlinks=false
core.ignorecase=true
remote.origin.url=git@gitlab.com:exposuregames/lotts.git
remote.origin.fetch=+refs/heads/*:refs/remotes/origin/*
branch.master.remote=origin
branch.master.merge=refs/heads/master
lfs.customtransfer.lfs-folder.path=lfs-folderstore
lfs.customtransfer.lfs-folder.args=F:/MegaSyncLOTTS
lfs.standalonetransferagent=lfs-folder
gui.wmstate=normal
gui.geometry=1261x677+555+132 455 196`

**Output of `git lfs env`**
`git-lfs/2.13.2 (GitHub; windows amd64; go 1.14.13; git fc664697)
git version 2.30.1.windows.1

Endpoint=https://gitlab.com/exposuregames/lotts.git/info/lfs (auth=none)
  SSH=git@gitlab.com:exposuregames/lotts.git
LocalWorkingDir=F:\UE Project\lotts
LocalGitDir=F:\UE Project\lotts\.git
LocalGitStorageDir=F:\UE Project\lotts\.git
LocalMediaDir=F:\UE Project\lotts\.git\lfs\objects
LocalReferenceDirs=
TempDir=F:\UE Project\lotts\.git\lfs\tmp
ConcurrentTransfers=8
TusTransfers=false
BasicTransfersOnly=false
SkipDownloadErrors=false
FetchRecentAlways=false
FetchRecentRefsDays=7
FetchRecentCommitsDays=0
FetchRecentRefsIncludeRemotes=true
PruneOffsetDays=3
PruneVerifyRemoteAlways=false
PruneRemoteName=origin
LfsStorageDir=F:\UE Project\lotts\.git\lfs
AccessDownload=none
AccessUpload=none
DownloadTransfers=basic,lfs-folder,lfs-standalone-file
UploadTransfers=basic,lfs-folder,lfs-standalone-file
GIT_EXEC_PATH=C:/Program Files/Git/mingw64/libexec/git-core
GIT_LFS_PATH=C:\Program Files\Git LFS
git config filter.lfs.process = "git-lfs filter-process"
git config filter.lfs.smudge = "git-lfs smudge -- %f"
git config filter.lfs.clean = "git-lfs clean -- %f"`

**Additional context**
The error araise from either :
* git clone
* git pull
* git lfs pull

I tried to google the error, but did not find any relevant result. I'm hopping someone can help me fix the error. I check the synced folder, the files are there with their correct hashes and sizes.

`Tarrke@Korriban MINGW64 /f/UE Project/lotts (master)
$ ll .git/lfs/tmp/
total 0
drwxr-xr-x 1 Tarrke 197121 0 févr. 18 17:10 objects/

Tarrke@Korriban MINGW64 /f/UE Project/lotts (master)
$ ll .git/lfs/tmp/objects/
total 0
Tarrke@Korriban MINGW64 /f/UE Project/lotts (master)
$ git lfs pull
downloaded file failed checks: file "F:\\UE Project\\lotts\\.git\\lfs\\tmp\\fb208a512edf786eb0475f52ddb39873debea633b732217456a29cf34bfffa2e.tmp" has an invalid hash 8b26871bf993b4ca9d10ac653a969e530af7bd6188ea7779f78fa8487d022066, expected fb208a512edf786eb0475f52ddb39873debea633b732217456a29cf34bfffa2e
downloaded file failed checks: file "F:\\UE Project\\lotts\\.git\\lfs\\tmp\\c600aa2210bee478677af53130049d83809dfaaea751a109ba84dae5b6dec549.tmp" has an invalid hash 043730510588684f7125efa73b50bc4f963cb48b884e71ee4e825e088556d36f, expected c600aa2210bee478677af53130049d83809dfaaea751a109ba84dae5b6dec549
(...)
error: failed to fetch some objects from 'https://gitlab.com/exposuregames/lotts.git/info/lfs'`

**Comment by chrisd8088** [comment]
Hey, I'm sorry you're having trouble.  This sounds like a somewhat custom configuration using [MegaSync](https://help.mega.nz/megasync/) and maybe something like the `sinbad/lfs-folderstore` [project](https://github.com/sinbad/lfs-folderstore), which none of the Git LFS core team have experience with, so it will be hard to provide concrete assistance.

The specific `"downloaded file failed checks"` error message you describe is [reported](https://github.com/git-lfs/git-lfs/blob/7b112ed239f4bd34609978925d5ae2d37e1d3cf1/tq/custom.go#L317) by the Git LFS client when it is using a custom transfer adaptor, such as it sounds like you have in place.  And the `"Error creating temp file"` error message looks like it is [coming](https://github.com/sinbad/lfs-folderstore/blob/cd771dd5bf32fe34a40689ef7a855c1b801925f2/service/service.go#L97) from your custom `lfs-folder` adaptor.

Since that strongly suggests to me that this is something which needs to be resolved in the custom transfer adaptor and how it interacts with MegaSync, I'm going to close this issue, but you might want to open a fresh one in the `sinbad/lfs-folderstore` project, describing how you're using it with MegaSync.

If it turns out this is actually a specific problem with the generic Git LFS client, though, please do feel free to come back and re-open this issue with additional details.  Good luck!

**Comment by Tarrke** [comment]
Thanks for the update
