### ISSUE TITLE
git lfs makes unchanged files as modified, and make git status very slow

### ISSUE THREAD

**Issue by mit10000** [git-lfs/git-lfs#4409]
=========Versions
OS ubuntu 16.04
git 2.23.0
git-lfs 2.13.2

========Description:
Existing git folder contains:
a.py
b,.py
x.pb
y.pb
in which .pb are binary large file (around 200M)

After install LFS, to setup LFS

```
git lfs track "*.pb"
git add .gitattributes
git commit -m "track *.pb file by LFS"
```

Then add a new .pb file:
```
cp /home/z.pb .
git add z.pb
git commit -m "add z.pb as LFS"
git push origin master
```

Check LFS file:

git lfs ls-files
0b8b0babf3 *  z.pb

Up to now, everything is OK. But when I try to check status

`git status`

modified: x.pb
modified: y.pb

Problems are 
1
the git status need 3 minutes to finish, sooooo slow. Before LFS, git status takes around 0.1 second
2
why x.pb and y.pb are modified? I did not change them at all. 

Thanks for help!

**Comment by mit10000** [comment]
Tried to config git as

```
core.checkstat=minimal
core.trustctime=false
```

This did not help.

**Comment by bk2204** [comment]
Hey,

If you run `git lfs track` and there are already files with that extension, you need to run `git add --renormalize .` and then commit to turn those files into LFS files.  Otherwise, your files are actually plain Git files, not LFS files, and then Git tries to force them through LFS, causing them to be perpetually modified.  This is a limitation of Git and [it's outlined in the Git FAQ](https://git-scm.com/docs/gitfaq#Documentation/gitfaq.txt-WhydoIhaveafilethat8217salwaysmodified).

**Comment by mit10000** [comment]
Thanks for replying.

In my case, if I want to convert all existing .pb file to LFS, can I use the command

`git lfs migrate import --include="*.pb" --everything`

as shown in LFS introduction?

**Comment by bk2204** [comment]
Yes, you can indeed use that.  That will rewrite history, whereas my suggestion above will not.  You can also use the `--no-rewrite` option if you don't want to rewrite history.  But if you do want to remove the large files from history, then that's the correct command.

**Comment by mit10000** [comment]
Thanks!
