### ISSUE TITLE
Git LFS file matches forbidden file

### ISSUE THREAD

**Issue by MXP2095onetechguy** [git-lfs/git-lfs#4410]
I am uploading a unity project and
what does this mean
Pattern FPS be untitled/Library/ matches forbidden file FPS be untitled/Library/PackageCache/com.unity.cinemachine@2.6.3/.gitattributes. If you would like to track FPS be untitled/Library/PackageCache/com.unity.cinemachine@2.6.3/.gitattributes, modify .gitattributes manually.

**Comment by chrisd8088** [comment]
Hey, I'm sorry you're having trouble.  Usually the `matches forbidden file` message means you have added a Git LFS matching pattern to your `.gitattributes` file which is matching the `.gitattributes` file itself, or another `.gitattributes` file, and Git LFS is not allowed to modify those (since that would cause a lot of recursive havoc).

In this case, I'm guessing from your message that you have added a pattern something like the following into your top-level `.gitattributes` file:
```
"FPS be untitled/Library/" filter=lfs diff=lfs merge=lfs -text
```

And, further, that you have a file named:
```
FPS be untitled/Library/PackageCache/com.unity.cinemachine@2.6.3/.gitattributes
```

Git LFS notices that the pattern would include the second `.gitattributes` file deeper in the file hierarchy and refuses to proceed.

You will likely need to refine your matching pattern to be more specific so that it doesn't include that file or anything else in those subdirectories which you don't want to track with Git LFS.
