### ISSUE TITLE
Git push only the pointer files to bitbucket

### ISSUE THREAD

**Issue by cedricliu** [git-lfs/git-lfs#4415]
Hi, I tried to push lfs files to the remote server on bitbucket. Most of the files were able to get pushed, but some files I have made modification only push as the pointer file. I tried the --renormalize function but the issue remains. Is there anything I can check to solve this issue? The lfs file is .uasset and .umap from Unreal engine, no source control was activated.

**Comment by bk2204** [comment]
Hey,

Here are a couple things you could try to do:

* You could run `git lfs fsck` to verify that everything is okay for the current revision and that all of the expected objects exist on your local system.
* You could run `git lfs push --all` to make sure all of the objects you need to push are pushed.

Between those, that should make sure that at least all of the objects for the current revision are pushed.  It's possible that if you've vendored dependencies that one or more of those dependencies incorrectly included the LFS pointer files instead of the LFS objects as well, but it would be hard to say without looking at the repository itself.

**Comment by cedricliu** [comment]
Hi Brian,

the `git LFS fsck` returns OK, and I also run the second option you have here. git LFS has been initialized so everything environment-wise looks fine. It's just a few objects that have newer timestamp was only pushing the pointer file. I think you are right it's a vendor dependency issue, I will check with Epic for this issue.  Thanks!
