### ISSUE TITLE
LFS and subst on Windows

### ISSUE THREAD

**Issue by douglaslassance** [git-lfs/git-lfs#4417]
The [subst](https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/subst) command allows mounting a folder as a drive. It seems to confuse Git LFS when it's time to lock a file with `git lfs lock <filename>`. The resulting error `Rel: can't make subst/path relative to actual/path` is displayed. Is this something I should never expect support for, or something you have not encountered?

**Comment by bk2204** [comment]
Hey,

This is a problem that people have reported to us previously as #4238, which is almost certainly a case of #4012.  There may be some improvements we can make in some cases, but since Go has steadfastly refused to fix the problem upstream (which was tracked in golang/go#42201), this is not likely to be fixed any time soon unless someone implements proper path canonicalization in Go.

Since there are two other issues tracking this, I'm going to close this in favor of those.
