### ISSUE TITLE
Documentation lacks instructions on how to remove git lfs

### ISSUE THREAD

**Issue by jerkstorecaller** [git-lfs/git-lfs#4426]
The markdown doc and "git lfs help" explain how I can start using lfs and hook it into my git repo. Great.

But they don't tell me what I should do if I decide git lfs is more trouble than it's worth and I want to stop using it. Let's say I converted my repo to lfs using import --everything, then added 200 commits, some files tracked by lfs, some not. 

Now I want to stop using lfs and want my repo to be the way it would've been if I had been using plain git from the start: so for every commit in history, to have lfs-tracked files replaced by normal "managed by plain git" files.

I'd like to use this tool but I'm apprehensive about it because I don't have the technical knowledge / git expertise to stop using it. So please fix this glaring omission from the doc. It's a best practice anyway to show how to uninstall your app.

**Comment by bk2204** [comment]
Hey,

Thanks for the feedback.  We do have that documentation, and it's in the same manual page.  The command is `git lfs migrate export`, and it works very similarly to `git lfs migrate import`.  I've added an [entry to the FAQ in the Wiki](https://github.com/git-lfs/git-lfs/wiki/FAQ), and I'll get something added to the README shortly, since I've been needing to do some updates to some of those files anyway.

**Comment by bk2204** [comment]
I've got a PR open that includes this as well as other changes in #4427, and I'll mark it appropriately to close this issue.

**Comment by jerkstorecaller** [comment]
Thanks, I had seen both uninstall and migrate, but didn't understand if that would stop future use, or fix all past history. I don't have the git knowledge to analyze repos. With those clear steps in the README, it's better for casual git users like me :)
