### ISSUE TITLE
Is it possible to run `git fetch` between commits?

### ISSUE THREAD

**Issue by samaursa** [git-lfs/git-lfs#4440]
**Describe the issue**

Assume my `.git/lfs` folder does **not** exist.

If I am on `master` but behind `origin/master` by a few commits and I do a `git pull origin master --ff-only`, `lfs` only downloads the files necessary.

But if I try `git lfs pull origin master` or `git lfs fetch origin master` then _all_ files are downloaded. Is it possible to get the same behavior as `git pull`?

I realize there is this command: `git lfs fetch -I ./path/to.file`

However, that requires a custom script to be written to grab all the files between 2 commits and then pass it to the command. Is there a better way?

**Why am I interested in this?**

Deleting the `.git/lfs` folder has given us back more than `300GB` of space for our repository. That is a _lot_ of space that LFS keeps consuming which then needs to be pruned daily.

We now delete the `.git/lfs` folder and things work great! Until somebody wants to fetch (i.e. they don't want to pull and merge, just fetch the new files) and then `lfs` goes ahead and fetches _everything_. Is there a way to get the same lfs behavior as when we run `git pull origin master` where `lfs` only downloads the changed files and nothing more?

**Comment by bk2204** [comment]
Hey,

This isn't possible in the general case.  When you run `git lfs fetch`, you're asking to fetch the objects in that revision so that you can then, in the future, run `git lfs checkout`.  `git lfs pull` does both.

Now, you might ask, why can't `git lfs checkout` not just ignore things that are unchanged in the index?  Well, the problem is that some people use `GIT_LFS_SKIP_SMUDGE=1` to avoid smudging the files in the working directory.  This is even required with certain files on Windows because there Git itself is not capable of processing files larger than a certain size.

We therefore don't know whether the object in the working tree is actually the object that we want, and therefore we need to do a full checkout of every LFS object every time, and in order to do that, we need all of the objects.  Git doesn't have this problem because it doesn't have to handle the case where smudging is skipped and therefore it can make many more assumptions about the state of the index and working tree.

Is there a reason you can't just let Git invoke Git LFS to download the files when you need them?  If that's the behavior you want, then it would make the most sense to let it download things on demand, which is the intended way that things work anyway.

**Comment by samaursa** [comment]
Thanks @bk2204 

The main reason for the original request was to fetch files but not use `git merge` (i.e. a `git pull` which in turn is `git fetch` and `git merge`, unless I am mistaken). This is because people cannot merge while they have their game editor open. Asking them to close it, stash their files, pull and merge, and then re-open everything is a huge time sink.

But then, why fetch at all? It reduces the get time when a developer is ready to do a get latest where the merge will happen. It also is safer. If we fetch and the connection dies (e.g. VPN disconnect), it's okay, we can keep repeating the fetch as many times as we want.

A failed merge however is painful for all developers involved. While merging, if the connection (to the VPN for e.g.) is lost, it can leave the repo in a bad state where a `reset --hard` must be done and another get performed. On any given day, multiple GBs of data can be submitted which can turn the above process really painful. The fetch helps in this case.

Is there another workflow you recommend? Is it possible to download things on demand but _not_ merge?

**Comment by bk2204** [comment]
I don't really have a good suggestion for what you want to do.  It's not really intended that you just delete the `.git/lfs` directory because that may remove data that isn't pushed and is still valuable, and we reserve the right to add additional data to that directory which you may destroy with this technique.  (Similarly, Git doesn't permit you to just remove whatever you like from the `.git` directory without using an appropriate tool.)  So your entire approach here is outside of a normal use case, which is to use `git lfs prune`.  I realize that you're having some trouble with that at the moment, which we're happy to fix if we can get suitable reproduction steps, but that is the appropriate way to handle excessive disk usage.

If you really want to download only the minimal amount of data, then you have to do that using the normal Git filtering mechanism into the same working tree, or you have to not delete the data already used for the current HEAD.  `git lfs fetch` doesn't download data that's already on disk.  Using a separate working tree or index won't solve this problem in this case, because you can't immediately rely on taking advantage of the index.

You can always try scripting the output of `git diff --raw` by extracting the particular changed file paths and passing that to `git lfs fetch -I`, but that's the best I think you can do with your use case.

**Comment by samaursa** [comment]
@bk2204 if `git lfs` allowed us to keep a 0 size cache, so that we are not storing the data twice, I would agree - but as it stands, there is no way for us to not waste a ton of space just because it is duplicated by lfs. In our current repo, even after prunes, the cache size is almost `300GB`.

I understand that there are limitations from git itself, but it would be great if `lfs` can have _some_ option for us to say "please don't cache files, we don't need them - always query `origin` and grab the files from there".

**Comment by bk2204** [comment]
What you're asking for is tracked as #2147, but hasn't been implemented yet.  If you use a suitable file system, you can use `git lfs dedup` to reduce the disk space needed, but that requires that your operating system and file system support that.

**Comment by samaursa** [comment]
thanks @bk2204 

in the issue #2147 you talk about the force command, has that been removed?

**Comment by bk2204** [comment]
No, but it hasn't been shipped in a release yet.  It will be in 3.0.0.

**Comment by samaursa** [comment]
got it, thanks
