### ISSUE TITLE
git-lfs: v2.3.4 works, but 2.13.2 does not

### ISSUE THREAD

**Issue by FredSRichardson** [git-lfs/git-lfs#4460]
Hello,

I'm running git-lfs on two nearly identical servers.  One has git-lfs 2.3.4 and the other has git-lfs 2.13.2.  Bot have identical OSs (Ubuntu 16.04) and the same environment variable settings.

With git 2.3.4 I'm able to clone a repository that uses git-lfs without any issues.  With git-lfs 2.13.2 the cloning process hangs at an `HTTP POST` step.  Using the environment variable settings `GIT_TRACE=1 GIT_TRANSFER_TRACE=1 GIT_CURL_VERBOSE=1`, the attempted POST message where the cloning hangs is:

```
TIMESTAMP trace git-lfs: HTTP: POST https://SERVER/_lfs/PROJECT/objects/batch
> POST /_lfs/PROJECT/objects/batch HTTP/1.1
> Host: SERVER
> Accept: application/vnd.git-lfs+json; charset=utf-8
> Authorization: RemoteAuth #############################
> Content-Length: 206
> Content-Type: application/vnd.git-lfs+json; charset=utf-8
> User-Agent: git-lfs/2.13.2 (GitHub; linux amd64; go 1.15.5)
>
```
and with v2.3.4 the successful clone uses this similar POST message:
```
TIMESTAMP trace git-lfs: HTTP: POST https://SERVER/_lfs/PROJECT/objects/batch
> POST /_lfs/PROJECT/objects/batch HTTP/1.1
> Host: SERVER
> Accept: application/vnd.git-lfs+json; charset=utf-8
> Authorization: RemoteAuth #############################
> Content-Length: 127
> Content-Type: application/vnd.git-lfs+json; charset=utf-8
> User-Agent: git-lfs/2.3.4 (GitHub; linux amd64; go 1.8.3)
>
{"operation":"download","objects":[{"oid":"<long-string>","size":INT}]}TIMESTAMP trace git-lfs: HTTP: 200
...
```

One solution is to revert to v2.3.4 on the v2.13.2 server, but that doesn't seem right for a lot of reasons.  

Any idea of what's going on and/or how to debug it?

Thanks!

-Fred

**Comment by FredSRichardson** [comment]
Quick update - I reverted git-lfs to 2.3.4 on the other machine that was not working and I still hang at the HTTP POST stage.  So this has nothing to do with git-lfs versions - apologies for the distraction!

Any advice on debugging is very welcome - I'm asking my admins to check our server logs since the environments seem to match very closely otherwise.

**Comment by bk2204** [comment]
Hey,

Sorry about the delay and thanks for the update.  I'd definitely check all of the standard network things, like any proxy settings or MTUs on your network.  You might also try to look at any logs you might have on the server if it's self-hosted to see if a connection is being made.  (My guess, based on your dump, is that it's a GitHub Enterprise Server instance, but I could be wrong.)  You can also try setting `http.version` to `HTTP/1.1`, although I don't believe 2.3.4 supports HTTP/2, so it's probably not likely to be the problem.

If nothing else shows up, you can always use tcpdump to trace the output, but of course since you're using HTTPS, the data won't be visible.

Hopefully this helps and you can track down what's causing problems for you.

**Comment by FredSRichardson** [comment]
@bk2204  - Thank you for the help with this!  We finally figured it out and our problem had everything to do with our network configuration and nothing to do with the GitHub server or git/git-lfs client configuration.  It's almost what you would expect!  I really don't think others are at all likely to find our specific solution helpful but suffice it to say a careful comparison of the files under /etc/ revealed a subtle but significant difference between the server that worked and the one that didn't.
