### ISSUE TITLE
Files are Locked Across Branches

### ISSUE THREAD

**Issue by actsciguy** [git-lfs/git-lfs#4481]
Hi all,
I have two feature branches (A & B) where I'm trying to implement git LFS functionality with locking so that we can lock Power BI (.pbix) files. On branch A, I have files report_1.pbix and report_2.pbix locked. When in branch B, if I run a `git lfs locks` command, the branch A locked files are shown. This also stops me from pushing changes to these files on branch B since they're locked on branch A.

Is this expected? My understanding  is locking only works within each branch and not across branches.

Thank you!

**Comment by bk2204** [comment]
Hey,

Yes, that's intentional.  The typical case that people want this feature for is where they're modifying some sort of binary file that can't be merged.  If I've locked the file on branch `bk2204/project-a` but you could lock it separately on `actsciguy/project-b`, then that wouldn't prevent us from conflicting when we merged, which is the goal.

Specifically, since the server side implementation gets the ref on which files are locked, it's possible for a remote server to implement locking specific to a branch, but I'm not aware of any server-side implementations which do that.
