### ISSUE TITLE
Removing "lockable" from .gitattributes does not rever back privilges to READ/WRITE

### ISSUE THREAD

**Issue by taherbs** [git-lfs/git-lfs#4484]
**Describe the bug**
I've removed the "lockable" option from the .gitattributes file and pushed the changes.
When cloning the repo from scratch the privileges of the previously lockable files are READ/WRITE
but for already cloned repos the privileges stay on READ ONLY.

**To Reproduce**
1. edit .gitattributes add "lockable" to a particular file extension
2. commit + push
3. do "ls -al" - you should see that your lockable file privileges changed into READ ONLY
4. edit .gitattributes remove "lockable" attribute
5. commit + push
6. do "ls -al" - The privileges of the previously lockable files still READ ONLY even after a ```git fetch --force```
7. The ```git lfs track --lockable``` command still shows that the previous lock files are lockable.
```
$ C
Listing tracked patterns
    *.lockfile (.gitattributes)
Listing excluded patterns
```

**Expected behavior**
* Previously lockable files get back READ/WRITE privileges.
* "git lfs track --lockable" cache get cleared/updated

**System environment**
* OS: Microsoft Windows 10 Professionnel
* GIT LSF VERSION: git-lfs/2.13.2 (GitHub; windows amd64; go 1.14.13; git fc664697)

**Output of `git lfs env`**
```
git-lfs/2.13.2 (GitHub; windows amd64; go 1.14.13; git fc664697)
git version 2.30.0.windows.2

Endpoint=https://git.XXX.com/IT/testlockfeature.git/info/lfs (auth=none)
  SSH=git@git.XXX.com:IT/testlockfeature.git
LocalWorkingDir=C:\Users\tbensalem\Documents\test2
LocalGitDir=C:\Users\tbensalem\Documents\test2\.git
LocalGitStorageDir=C:\Users\tbensalem\Documents\test2\.git
LocalMediaDir=C:\Users\tbensalem\Documents\test2\.git\lfs\objects
LocalReferenceDirs=
TempDir=C:\Users\tbensalem\Documents\test2\.git\lfs\tmp
ConcurrentTransfers=8
TusTransfers=false
BasicTransfersOnly=false
SkipDownloadErrors=false
FetchRecentAlways=false
FetchRecentRefsDays=7
FetchRecentCommitsDays=0
FetchRecentRefsIncludeRemotes=true
PruneOffsetDays=3
PruneVerifyRemoteAlways=false
PruneRemoteName=origin
LfsStorageDir=C:\Users\tbensalem\Documents\test2\.git\lfs
AccessDownload=none
AccessUpload=none
DownloadTransfers=basic,lfs-standalone-file
UploadTransfers=basic,lfs-standalone-file
GIT_EXEC_PATH=C:/Program Files/Git/mingw64/libexec/git-core
GIT_LFS_PATH=C:\Program Files\Git LFS
GIT_LFS_SET_LOCKABLE_READONLY=true
git config filter.lfs.process = "git-lfs filter-process"
git config filter.lfs.smudge = "git-lfs smudge -- %f"
git config filter.lfs.clean = "git-lfs clean -- %f"
```

**Comment by chrisd8088** [comment]
Hey, I'm sorry you're having trouble.  Would you be able to provide a more detailed description of the steps you are taking, and also provide the contents of `.gitattributes` after each step?

One thing to note is that `git lfs track --lockable` doesn't do anything different than `git lfs track`, and both of those commands, when run without any filename patterns, will simply output a user-friendly list of the contents of `.gitattributes`.

It might also be helpful to run `git check-attr -a -- <file>` on a file you think should be lockable or unlockable, to see what the attributes are.

Another thing to note is that using `git lfs track --lockable <pattern>` and `git lfs track --not-lockable <pattern>` (plus maybe `git lfs untrack <pattern>`) may be more valuable in terms of adding and removing the `lockable` attribute than editing `.gitattributes` directly.  That's because they [run](https://github.com/git-lfs/git-lfs/blob/94245ec834c7f938ec3a7808f73e9bd1d2b04f0a/commands/command_track.go#L215-L217) a final step to look for files whose permissions should be modified.

At a guess, I wonder if you are relying on the `git-lfs-post-commit` hook to do the work instead of using `git lfs track` to add/remove file permissions.  That hook, I believe, [exits early](https://github.com/git-lfs/git-lfs/blob/94245ec834c7f938ec3a7808f73e9bd1d2b04f0a/commands/command_post_commit.go#L29-L32) if there are no patterns in `.gitattributes` with the `lockable` attributes.  It can't know which attributes which been removed, though, so there's no way for it to restore read-write permissions when `lockable` has been deleted from `.gitatttributes`.  As the [docs](https://github.com/git-lfs/git-lfs/blob/94245ec834c7f938ec3a7808f73e9bd1d2b04f0a/docs/man/git-lfs-post-commit.1.ronn#description) for hook say:

>  It makes sure that any files which are marked as lockable by `git lfs track` are read-only in the working copy, if not currently locked by the local user.

So, as an example session, this appears to work for me on Linux:
```
$  ls -l README.md 
-rw-r--r--  1 chrisd  staff  13 27 Apr 12:13 README.md

$ git lfs track --lockable README.md
Tracking "README.md"
$ ls -l README.md 
-r--r--r--  1 chrisd  staff  13 27 Apr 12:14 README.md
$ git lfs track
Listing tracked patterns
    readme.md [lockable] (.gitattributes)
Listing excluded patterns

$ git lfs track --not-lockable README.md
Tracking "README.md"
$ ls -l README.md 
-rw-r--r--  1 chrisd  staff  13 27 Apr 12:14 README.md
$ git lfs track
Listing tracked patterns
    readme.md (.gitattributes)
Listing excluded patterns

$ git lfs untrack README.md
Untracking "README.md"
$ git lfs track
Listing tracked patterns
Listing excluded patterns
```

**Comment by taherbs** [comment]
Hi 
using the `git lfs track --not-lockable "*.md"` makes the files READ/WRITE again, but editing the .gitattribute file (with an editor) and removing the "lockable" attribute than pushing does not affect the file privileges.
You need absolutely to run the `git lfs track --not-lockable "*.md"` or reclone the project.
Attached screenshots of my tests:

![image](https://user-images.githubusercontent.com/10932086/117507713-6f573800-af55-11eb-84b6-7f0eae942357.png)

![image](https://user-images.githubusercontent.com/10932086/117507788-8ac24300-af55-11eb-98ba-4487d5f2b1da.png)
