### ISSUE TITLE
Is there a way or option to store only hashes and not lfs objects on local system?

### ISSUE THREAD

**Issue by msams-v** [git-lfs/git-lfs#4485]
Hello,
I would like to ask if there is a way or option to store only hashes and not lfs objects on local system?
The reason I ask, there is a repository with the size of 1.2TB where 400GB are lfs objects under .git folder.
I am aware that it could be moved to another location, but I would like to ask in general,  maybe some options I am missing:
* it would be good to say with option, binary files are different if hash is different. Collisions included (fine for me)
* do not store lfs objects only download on demand if asked with without specific option. For instance, it never needed to be compared binary, but I assume for some re-calculation sometimes it would need original file.
* the main goal is to reduce the occupied disk space, but it's fine to use network more often to download things from the server

It would be good to hear your opinions or even solutions for this problem I have.
Thank you!

**Comment by bk2204** [comment]
Hey,

If you don't want to check out the files on the local system, you can use `GIT_LFS_SKIP_SMUDGE=1` to skip checking out those files.  If your goal is to minimize the storage on the local disk, you can try either `git lfs dedup`, if you're on a file system that supports copy on write, or you can build the latest `main` branch and try `git lfs prune --force` if you like; the latter will be in 3.0.0.

I think the feature you're actually looking for is #2147, and since that's already being tracked, I'm going to close this issue in favor of that one.
