### ISSUE TITLE
ERROR GH001:  Large files detected. You may want to try Git Large File Storage - https://git-lfs.github.com.

### ISSUE THREAD

**Issue by MatildeFrancois** [git-lfs/git-lfs#4491]
While I m trying to share a PyCharm project on GitHub I report this error:

Can't finish GitHub sharing process
			Successfully created project 'nameofproject' on GitHub, but initial push failed:
			Total 11926 (delta 1182), reused 11916 (delta 1178), pack-reused 0
			remote: error: GH001: Large files detected. You may want to try Git Large File Storage - https://git-lfs.github.com.
			remote: error: Trace: a4665dccb33083259ba3ed8f5ac805776a55d3abc89340645937543999294576
			remote: error: See http://git.io/iEPt8g for more information.
			remote: error: File venv/Lib/site-packages/torch/lib/torch_cpu.dll is 192.43 MB; this exceeds GitHub's file size limit of 100.00 MB
			remote: error: File venv/Lib/site-packages/torch/lib/dnnl.lib is 303.82 MB; this exceeds GitHub's file size limit of 100.00 MB
			failed to push some refs to 'https://github.com/myusername/myproject.git'

Please help me to fix it

**Comment by chrisd8088** [comment]
Hey, I'm sorry you're having trouble.  It sounds like you are trying to push files above GitHub's file size limit, just as the error message says.  You should probably reach our to GitHub support for assistance, and you can also read both their [documentation](https://docs.github.com/en/github/managing-large-files/about-git-large-file-storage) as well the docs on the Git LFS [site](https://git-lfs.github.com/) and in the manual [pages](https://github.com/git-lfs/git-lfs/tree/94245ec834c7f938ec3a7808f73e9bd1d2b04f0a/docs/man) and the [wiki](https://github.com/git-lfs/git-lfs/wiki).  Plus you can open a [discussion](https://github.com/git-lfs/git-lfs/discussions) thread, and check for help on sites like StackOverflow.

Since this isn't a bug in the Git LFS client itself, I'm going to close this issue.  Good luck and by all means open another issue if you run into a problem with the Git LFS client software itself.
