### ISSUE TITLE
export doesn't seem to work on just HEAD

### ISSUE THREAD

**Issue by jasonkarns** [git-lfs/git-lfs#4500]
**Describe the bug**

Attempting to export large files out of LFS from current HEAD, but export seemingly does nothing.

Repo had history rewritten with `git lfs migrate import --everything --above=1Mb` and force-pushed.

<details>
<summary>.gitattributes:</summary>

```
*.png filter=lfs diff=lfs merge=lfs -text
*.jpg filter=lfs diff=lfs merge=lfs -text
*.eps filter=lfs diff=lfs merge=lfs -text
*.zip filter=lfs diff=lfs merge=lfs -text
*.gif filter=lfs diff=lfs merge=lfs -text
```
</details>

Only two files in HEAD are currently managed by lfs, which I want to be exported from lfs and committed normally.

```
$ git lfs ls-files
11e042b391 - static/blog/assets/img/ali-at-abstractions.png
f1f01dd312 - static/site/app/img/team/company-key-west.jpg
```

**To Reproduce**
1. After everything was imported and force pushed
2. With clean working directory and lfs installed
3. 
```
$ git lfs migrate export -I "*"
migrate: Fetching remote refs: ..., done.                                                                                                                                       
migrate: Sorting commits: ..., done.                                                                                                                                            
migrate: Rewriting commits: 100% (0/0), done.                                                                                                                                   
migrate: Updating refs: ..., done.                                                                                                                                              
migrate: checkout: ..., done.                                                                                                                                                   
prune: 2 local object(s), 2 retained, done.                                                                                                                                     
```

**Expected behavior**
I expected the two pointer files to be replaced with their full contents.
I expected gitattributes to be modified (somehow).

**System environment**
```
$ git lfs version
git-lfs/2.13.3 (GitHub; darwin amd64; go 1.16.2)
```

**Output of `git lfs env`**
<details>
<summary>$ git lfs env | pbcopy </summary>

```
git-lfs/2.13.3 (GitHub; darwin amd64; go 1.16.2)
git version 2.31.1

Endpoint=https://github.com/jasonkarns/web.git/info/lfs (auth=basic)
Endpoint (upstream)=https://github.com/testdouble/web.git/info/lfs (auth=none)
LocalWorkingDir=/private/var/folders/g5/hjyp2_y91ggcbxmqnrxs54dh0000gn/T/tmp.OEiSS2uE/web-lfs
LocalGitDir=/private/var/folders/g5/hjyp2_y91ggcbxmqnrxs54dh0000gn/T/tmp.OEiSS2uE/web-lfs/.git
LocalGitStorageDir=/private/var/folders/g5/hjyp2_y91ggcbxmqnrxs54dh0000gn/T/tmp.OEiSS2uE/web-lfs/.git
LocalMediaDir=/private/var/folders/g5/hjyp2_y91ggcbxmqnrxs54dh0000gn/T/tmp.OEiSS2uE/web-lfs/.git/lfs/objects
LocalReferenceDirs=
TempDir=/private/var/folders/g5/hjyp2_y91ggcbxmqnrxs54dh0000gn/T/tmp.OEiSS2uE/web-lfs/.git/lfs/tmp
ConcurrentTransfers=8
TusTransfers=false
BasicTransfersOnly=false
SkipDownloadErrors=false
FetchRecentAlways=false
FetchRecentRefsDays=7
FetchRecentCommitsDays=0
FetchRecentRefsIncludeRemotes=true
PruneOffsetDays=3
PruneVerifyRemoteAlways=false
PruneRemoteName=origin
LfsStorageDir=/private/var/folders/g5/hjyp2_y91ggcbxmqnrxs54dh0000gn/T/tmp.OEiSS2uE/web-lfs/.git/lfs
AccessDownload=basic
AccessUpload=basic
DownloadTransfers=basic,lfs-standalone-file
UploadTransfers=basic,lfs-standalone-file
GIT_EXEC_PATH=/usr/local/Cellar/git/2.31.1/libexec/git-core
git config filter.lfs.process = "git-lfs filter-process"
git config filter.lfs.smudge = "git-lfs smudge -- %f"
git config filter.lfs.clean = "git-lfs clean -- %f"
```

**Additional context**

To be clear, I don't want `export --everything`. I want to leave history as-is, with large files remaining in LFS. I only want to export from current HEAD.

**Comment by chrisd8088** [comment]
Hey, I'm sorry you're having trouble.  I think the immediate issue is that, by default, `git lfs migrate` (in all modes) only operates on files or LFS objects which do not exist on any remote.  Since you've done a full force-push, the remote has the two objects you want to convert back to being files, so `git lfs migrate export` skips them.  To change that behaviour, you could use something like `--include-ref=HEAD` so that you're explicitly asking it to look for LFS objects on all refs reachable from `HEAD`.  You could then exclude certain parts of your history by using `--exclude-ref` as well, so that you're choosing just the specific parts of your history for which you want the export to be performed.

However, I note that you also say that you "want to leave history as-is".  Be cautious that `git lfs migrate export` also rewrites history, even without `--everything`!  (All that `--everything` is doing is effectively supplying `--include-ref` for all local and remote refs.)

So I wondered if perhaps the issue you're facing is not that you want to rewrite history on just the `HEAD` branch to undo what the import did, but actually just to "recover" the imported files in your working tree?  If the `git lfs migrate import` command has left certain files in your working tree as containing Git LFS pointers instead of their original contents, you might try `git lfs checkout` to convert them (via the smudge filter) back to their contents.  For example, I need to do that here:
```
$ git init test
$ cd test
$ echo foo > foo.txt
$ echo bar > bar.txt
$ git add *.txt
$ git commit -m init

$ git lfs migrate import --everything
...
$ cat foo.txt
version https://git-lfs.github.com/spec/v1
oid sha256:b5bb9d8014a0f9b1d61e21e796d78dccdf1352f23cd32812f4850b878ae4944c
size 4

$ git lfs checkout
Checking out LFS objects: 100% (2/2), 8 B | 0 B/s, done.    
$ cat foo.txt
foo
```

**Comment by jasonkarns** [comment]
@chrisd8088 ah, thanks. The docs make that a bit confusing:

> In all modes, by default git lfs migrate operates only on the currently checked-out branch

made me think I didn't need to provide a ref; though I conveniently skimmed over the next bit:

> and only on files [...] added in commits which do not exist on any remote

I had tried checkout which indeed brought back the content as expected, but git still considered the files unchanged (still storing only the pointers in index). After some more thought, presumably we just need to remove the .gitattributes rules prior to the `lfs checkout`? That should ensure we have the content locally, but allow us to save the real content back into git normally?

So the end result that we're aiming for is for LFS to not really be used day-to-day. Basically we want to import old objects in history into LFS, but for HEAD (and forward) to not have anything in LFS. (ie, leveraging lfs like [bfg](https://rtyley.github.io/bfg-repo-cleaner/), but without losing access to the content)

**Comment by chrisd8088** [comment]
OK ... it sounds like you don't just want full file content in your working tree, which is the typical case (this is where `git lfs checkout` might help post-import), you really do want to "undo" the import on a specific branch, in this case, `HEAD`.

So `git lfs migrate export` would be the right tool for that at this point, since you've already run a full import with `--everything`.  What you probably need to do is determine the point in your history where you want to "stop" using Git LFS and supply that in `--exclude-ref`.  For example, here's a simple demo which "stops" at `HEAD^`.  Note that using `git lfs migrate export` does not *remove* lines from `.gitattributes` but instead adds an override line.

```
$ git init test
$ cd test
$ echo foo > foo.txt
$ git add foo.txt; git commit -m foo
$ echo bar > bar.txt
$ git add bar.txt; git commit -m bar
$ git lfs migrate import --everything
$ git lfs migrate export -I '*.txt' --exclude-ref=HEAD^ --include-ref=HEAD

$ git show HEAD^:foo.txt
version https://git-lfs.github.com/spec/v1
oid sha256:b5bb9d8014a0f9b1d61e21e796d78dccdf1352f23cd32812f4850b878ae4944c
size 4
$ git show HEAD:foo.txt
foo
$ git show HEAD:bar.txt
bar

$ git show HEAD^:.gitattributes
*.txt filter=lfs diff=lfs merge=lfs -text

$ git show HEAD:.gitattributes
*.txt filter=lfs diff=lfs merge=lfs -text
*.txt !text !filter !merge !diff
```

**Comment by jasonkarns** [comment]
Thanks, I appreciate the help!

for posterity, what I ended up doing was:

```
$ git lfs migrate import --include-ref HEAD --above=1Mb
$ git push --force-with-lease origin
$ git rm .gitattributes
$ git lfs checkout
$ git ci -m "LFS Checkpoint"
$ git push
```
