### ISSUE TITLE
GIT LFS ignores --no-pager option

### ISSUE THREAD

**Issue by Ironeer** [git-lfs/git-lfs#4516]
**Describe the bug**
Git can be forced to use no pager for progress, for example with 'git --no-pager push'. With LFS this is not possible, it writes progress on one line and updates it. I don't know whether this is configurable in another way but I thought lfs should work like plain git.

**To Reproduce**
1. Commit anything that is in the '.gitattributes'
2. use 'git --no-pager push'

**Expected behavior**
Respect the --no-pager setting that git offers.

**Comment by bk2204** [comment]
Hey,

Git LFS never calls a pager when it's operating.  While I can't think of a situation when this would happen, it's possible that Git itself invokes a pager for output, including the output of Git LFS as part of it, but that would be controlled by the `--no-pager` option of Git.  In any event, since we never invoke a pager in the first place, there's no way we can control whether one is invoked.

What it sounds like you're requesting is that you'd like no progress to be printed to the output.  Is that the case?

**Comment by Ironeer** [comment]
Thank you for your quick response! I tried to read the output of 'git push' with my python program. But the LFS progress is printed in one line which is continuously updated. Therefore python is not able to retrieve the progress live, only when the line is finally added completely. With git I discovered that `--no-pager` configured the output to create a new line for each progress update. I hoped this is possible with lfs also.

### Current output:
`Uploading LFS objects:   0% (0/1), 1.0 MB | 197 KB/s` which is updated continuously

### Goal
```
Uploading LFS objects:   0% (0/1), 1.0 MB | 197 KB/s
Uploading LFS objects:   1% (0/1), 1.0 MB | 195 KB/s
...
```

**Comment by bk2204** [comment]
Both Git and Git LFS use the same approach to print their progress meters.  They print a line with a carriage return (`\r`) at the end to move the cursor to the beginning of the same line, and then print the next line, which writes over it.  Your code will probably work just fine if you read it by splitting on carriage returns rather than newlines.  You may also need `GIT_LFS_FORCE_PROGRESS=1` in the environment.

`--no-pager` should not have an effect on Git like this, so if you're relying on that functionality, I wouldn't, since it's definitely not intended to work that way (and is probably a bug).  If you're not using a terminal here to capture the output, then I suspect the behavior you're seeing is linked to that and not the option.  Without seeing the code in question, it's hard to say.

**Comment by Ironeer** [comment]
Again, thank you for the answer. Clearly I found a wrong source online. 
I tried to implement it differently with your tips by reading not by line but by byte and I set `GIT_LFS_FORCE_PROGRESS=1`. 

I had `GIT_LFS_PROGRESS` already set and in mind as my second approach. But as reading from the file while LFS writes to it seemed less straight forward for me I did not try.

I know it is not your work to explain it, but here is my (not working) shortened result.
I want to get the live output of the execution to the terminal but also be able to analyse the result when `git push` is done:

### My shortened script
```
import os
import subprocess

abspath = os.path.abspath(__file__)
dirName = os.path.dirname(abspath)
os.chdir(dirName)

cmd = ["git", "push"]
outputAfterwards = ""
process = subprocess.Popen(
    cmd,
    stderr=subprocess.STDOUT,
    stdout=subprocess.PIPE)

print("Output of " + " ".join(cmd) + ":\n")
while True:
    output = process.stdout.read(1).decode("utf8")
    if output == '' and process.poll() is not None:
        break
    if output:
        print(output, end="")
        outputAfterwards += output
print()

print("Complete output afterwards:")
print(outputAfterwards)
````

### The output
At first during execution of `git push`:
`Output of git push:`

Then (it is showing real time output but not the changing progress):
```
Output of git push:

Uploading LFS objects: 100% (1/1), 1.6 MB | 214 KB/s, done.
```

When the execution finished:
```
Output of git push:

Uploading LFS objects: 100% (1/1), 1.6 MB | 214 KB/s, done.
remote: . Processing 1 references        
remote: Processed 1 references in total        
To git.disroot.org:Maxi/aex.git
   f7d809e..8dc7ad3  master -> master

Complete output afterwards:
Uploading LFS objects: 100% (1/1), 1.6 MB | 214 KB/s, done.
remote: . Processing 1 references        
remote: Processed 1 references in total        
To git.disroot.org:Maxi/aex.git
   f7d809e..8dc7ad3  master -> master
```

Thanks in advance

**Comment by bk2204** [comment]
The problem with your code is that you're printing out exactly what you've received to the terminal.  When you receive the input with the carriage return and then you print that to the terminal, you're moving the cursor to the beginning of the line.  When you print the next bit of text, you're overwriting it when it appears on the terminal.

If you don't want your program to overwrite the output, you'll need to change any instances of carriage returns to newlines there.  So something like this:

```python
#!/usr/bin/python3
import os
import subprocess

cmd = ["git", "push", "origin", "HEAD"]
outputAfterwards = ""
process = subprocess.Popen(
    cmd,
    stderr=subprocess.STDOUT,
    stdout=subprocess.PIPE)

print("Output of " + " ".join(cmd) + ":\n")
while True:
    output = process.stdout.read(1).decode("utf8")
    if output == '' and process.poll() is not None:
        break
    if output == "\r":
        output = "\n"
    if output:
        print(output, end="")
        outputAfterwards += output
print()

print("Complete output afterwards:")
print(outputAfterwards)
```

will produce this on my system when run with `GIT_LFS_FORCE_PROGRESS=1`:

```
Output of git push origin HEAD:

Uploading LFS objects:   0% (0/1), 0 B | 0 B/s
Uploading LFS objects: 100% (100/100), 792 B | 0 B/s
Uploading LFS objects: 100% (100/100), 792 B | 0 B/s, done.
To https://github.com/git-lfs/pull-bug.git
   83a5a54..99832d2  HEAD -> temp

Complete output afterwards:
Uploading LFS objects:   0% (0/1), 0 B | 0 B/s
Uploading LFS objects: 100% (100/100), 792 B | 0 B/s
Uploading LFS objects: 100% (100/100), 792 B | 0 B/s, done.
To https://github.com/git-lfs/pull-bug.git
   83a5a54..99832d2  HEAD -> temp
```

Note that your program is capturing the data just fine (although, due to the byte-by-byte read, extremely inefficiently).  It's just that displaying it to the terminal causes things to look different than you expect because the output contains escape codes for the terminal.

**Comment by Ironeer** [comment]
Thank you very much!
