### ISSUE TITLE
Fails on macOS 10.11.6 because of `clock_gettime()`

### ISSUE THREAD

**Issue by elder-n00b** [git-lfs/git-lfs#4520]
**Describe the issue**
Fails with error `dyld: lazy symbol binding failed: Symbol not found: _clock_gettime`.

**System environment**
macOS 10.11.6 (x64)

**Output of `git lfs env`**
`/Applications/GitHub\ Desktop.app/Contents/Resources/app/git/libexec/git-core/git lfs env`
```
git: 'lfs' is not a git command. See 'git --help'.

The most similar command is
	log
```

**Additional context**
Encountered this with the last GitHub Desktop automatic update (see [issue 12346](https://github.com/desktop/desktop/issues/12346) there).
I found [Drop obsolete OS support #4328](https://github.com/git-lfs/git-lfs/pull/4328) here but it only mentions CentOS 6 and Debian 8.
Assuming this is the only incompatibility, perhaps a fallback implementation like [this one](https://gist.github.com/alfwatt/3588c5aa1f7a1ef7a3bb) could help.

**Comment by chrisd8088** [comment]
Hey, thanks for the report.  I assume this is due to #4437 which switched the release builds to use Go 1.16, but perhaps stems from an earlier change.  Would you be able to install Git LFS directly (not as part of GitHub Desktop) and help us determine the last working Git LFS release on your hardware?

That said, we may not find a simple workaround, as the call to the `_clock_gettime()` function is not in the Git LFS code directly; rather, it's just pulled in via basic Go dependencies, specifically from the `x/sys` [package](https://github.com/golang/sys/blob/aa57babbf139f2cf189f7cc4dce7ad03fec65ed6/unix/zsyscall_darwin_amd64.go#L875).  And Go 1.15 now [requires](https://golang.org/doc/go1.15#darwin) macOS 10.12 or later.

So we would have to find a way to support both newer Apple hardware (which requires newer Go releases) and older hardware -- and maybe this would even require a separate build and signed release, just for older Apple hardware, which in turn complicates packaging.  I suppose we might be able to build for Darwin AMD with an older Go, and for Darwin ARM with Go 1.16, at least for a while ... but as I say, that would definitely introduce complexity into our support, since we'd then have one flavour of macOS using a different version of Go than all other clients.  And since this is an open-source project with a limited number of people providing support, I don't think we would want to introduce that kind of discrepancy into our support matrix.

If you are able to build Git LFS locally, it should work with Go 1.14 or earlier (as far back as 1.11), which all should in turn support macOS 10.11, I believe.  Is that possible in your case?

**Comment by elder-n00b** [comment]
`git-lfs/2.13.2 (GitHub; darwin amd64; go 1.15.5; git fc664697)` (release) seems to work.
I have not installed it yet, only run `git-lfs` at the command line. I think it's safe to assume it works?

> Would you be able to install Git LFS directly [...]

Yes, I'll do that later today.  
Should I only run `install.sh` or do `git lfs install --skip-repo` like GitHub Desktop does?  
I'm not familiar with `git` internals at all.

> If you are able to build Git LFS locally [...]

Tried building current `main` branch with `go version go1.15.2 darwin/amd64`.  
It builds, but then misses `_clonefileat` when run.

**Comment by chrisd8088** [comment]
> `git-lfs/2.13.2 (GitHub; darwin amd64; go 1.15.5; git fc664697)` (release) seems to work.

OK, that checks out with #4437 being the likely cause.

> Should I only run `install.sh` or do `git lfs install --skip-repo` like GitHub Desktop does?

You would want to run `./install.sh` from the binary release package, because that will install the `git-lfs` binary and then also run `git lfs install`.  (Running `git lfs install` requires that the `git-lfs` binary already be installed because `git lfs install` is a command executed by that binary to do some additional setup, such as installing the Git hooks needed to use Git LFS.  Since you already have a prior version of Git LFS installed, those hooks should be in place already, so you should probably only need to replace the binary.)

> Tried building current `main` branch with go version `go1.15.2 darwin/amd64`.
> It builds, but then misses `_clonefileat` when run.

Hmm.  I wonder if that's due to #4387?  If you're able, could you try reverting that change from your `main` branch and see if it helps?

**Comment by elder-n00b** [comment]
> try reverting that change

I will.

Meanwhile, I tried building v2.13.2 with the same compiler and got `fatal error: 'sys/clonefile.h' file not found`.  
Not sure if I'm doing something wrong, I simply used `git clone --depth 1 --branch v2.13.2 https://github.com/git-lfs/git-lfs.git` and then `make` as before.<details>
```
$ git clone --depth 1 --branch v2.13.2 https://github.com/git-lfs/git-lfs.git
Cloning into 'git-lfs'...
remote: Enumerating objects: 1636, done.
remote: Counting objects: 100% (1636/1636), done.
remote: Compressing objects: 100% (1371/1371), done.
remote: Total 1636 (delta 224), reused 902 (delta 136), pack-reused 0
Receiving objects: 100% (1636/1636), 2.55 MiB | 1.43 MiB/s, done.
Resolving deltas: 100% (224/224), done.
Checking connectivity... done.
Note: checking out 'fc664697ed2c2081ee9633010de0a7f9debea72a'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b <new-branch-name>

$ cd git-lfs/

$ make
git-lfs: skipping fmt, no goimports found at `goimports` ...
go generate github.com/git-lfs/git-lfs/commands
GOOS= GOARCH= go build -ldflags=" -X github.com/git-lfs/git-lfs/config.GitCommit=fc66469 -s -w " -gcflags="all=-trimpath="$HOME" " -asmflags="all=-trimpath="$HOME"" -trimpath -o ./bin/git-lfs ./git-lfs.go
# github.com/git-lfs/git-lfs/tools
tools/util_darwin.go:21:10: fatal error: 'sys/clonefile.h' file not found
#include <sys/clonefile.h>
         ^
1 error generated.
make: *** [bin/git-lfs] Error 2
```
</details>

**Comment by bk2204** [comment]
You probably want to set `CGO_ENABLED=0` when running `make`.  That header won't be available on 10.11, so you'll want to avoid building with cgo.  That does mean that `git lfs dedup` won't work, but everything else should otherwise be functional.

Go doesn't have a good way to handle conditional compilation for C-specific features like this, and this is what I've suggested in #3999 and #4204, which are the previous issues where folks have requested help for 10.11.  We don't officially support such old versions of macOS because we have no way of testing them and we wouldn't want to put machines without security updates on the Internet anyway, but this should get you mostly up and running.

**Comment by elder-n00b** [comment]
Thank you @bk2204.  

HEAD with #4387 reverted and your hint now compiles and runs, reporting itself as `git-lfs/2.13.0 (GitHub; darwin amd64; go 1.15.2; git 373de0c)`. (2.13.**0**?)
v2.13.3, again with #4387 reverted and `CGO_ENABLED=0`, also compiles and runs, reporting itself as `git-lfs/2.13.3 (GitHub; darwin amd64; go 1.15.2; git a5e6585)`.

---

I'm a bit confused as to why it works though, as the reverted files refer to `cgo`. Then again, I don't know go.  

I'm also puzzled by the `checkCloneFileSupported()` ("return iff Mac OS version is greater or equal to 10.12.x Sierra").  
That should already take care of the problem but it seems to me that if go tries to dyld those missing functions anyway it defeats the purpose of checking, which is sad because it means no single binary to support old and new systems even though git-lfs itself apparently could.  
I'm not sure if technically possible and worth the trouble, but perhaps there's a way to link those functions "by hand" in code?  
I remember having done that with a Windows dll, but I don't know about macOS.

**Comment by bk2204** [comment]
Part of this is related to the fact that on macOS binaries can't be statically linked.  So if we use a function in the codebase, it ends up creating a reference to libc.  The way to avoid this is to typically compile for the oldest OS you want to support, but we can't do that, since GitHub Actions doesn't build things on macOS 10.11, and we use that for building our Mac binaries.

As for dynamic loading, it certainly is possible to load symbols with `dlsym`, but I don't think we want to do that.  In general, we've had other requests to support systems that are no longer security supported, and in #3999, I said the following:

> Having said that, if you can come up with a way to make this work out of the box without impacting newer systems negatively, we're happy to accept a PR to do so.

I think that summarizes our position here.  We won't actively support such systems, but for this project, we're not a hard no if other folks want to send patches.

So since we don't consider this a bug, I'm going to close this, but you are welcome to send a patch as I mentioned if you'd like better support for this case.
