### ISSUE TITLE
[feature request] add option to always dedup

### ISSUE THREAD

**Issue by greyltc** [git-lfs/git-lfs#4528]
I'm a new user of git-lfs and today I came to the git-lfs issues list looking for explanations for the perplexing problem of why my git local LFS enabled repo stores my large files on disk two times. I found https://github.com/git-lfs/git-lfs/issues/2147 which I think captures the problem nicely.

I saw [this comment](https://github.com/git-lfs/git-lfs/issues/2147#issuecomment-767032537) suggesting I run `git lfs dedup` and boom the problem is solved!

Shouldn't taking advantage of the file system features to prevent double storage be enabled by default? If there is some drawback to this, is there a way to choose to turn it on permanently? If not, this is a request for that. If I understand correctly, when I clone a new repo it will still initially have double storage cost on disk until I run the dedup command and then I need to run it periodically manually to keep things unduplicated.

**Comment by bk2204** [comment]
Hey,

Git LFS will automatically take advantage of the copy-on-write feature of the file system if you use `git lfs checkout` or `git lfs pull`.  This is equivalent to running `git lfs dedup`.

However, if you want Git to check out the files automatically, then this isn't possible.  Git smudge filters involve Git sending us the pointer file on standard input and us writing the proper data on standard output, at which point Git writes it into the working tree.  Since Git doesn't have an option to just copy the data on disk, you can't automatically take advantage of deduplication if you have the smudge feature enabled.

While it's possible to deduplicate automatically by putting the `git lfs dedup` command in the `post-checkout` hook, this will lead to Git re-reading all of those files into the index, which may be very expensive, so we don't do it by default.

You do understand correctly that until you run `git lfs dedup`, you will have the files stored twice on disk and it does need to be run manually unless you're using `git lfs checkout` or `git lfs pull`.

So I'm going to close this since it isn't currently possible in an efficient way due to limitations in Git.
