### ISSUE TITLE
Publish arm64 linux packages to packagecloud

### ISSUE THREAD

**Issue by timja** [git-lfs/git-lfs#4546]
**Describe the issue**
I can't install recent git-lfs via package on arm64

(I assume same for s390x and ppc would be good to get those sorted too)

**System environment**
The version of your operating system, plus any relevant information about platform or configuration (e.g., container or CI usage, Cygwin, WSL, or non-Basic authentication).  If relevant, include the output of `git config -l` as a code block.

macOs big sur 11.4
M1 mac
arm64

**Output of `git lfs env`**
The output of running `git lfs env` as a code block.
not relevant

**Additional context**
I've tested on the debian:buster-slim and centos:8.3.2011 images and cannot find the corresponding package.

```
docker run -it debian:buster-slim bash
apt install -y curl
curl -s https://packagecloud.io/install/repositories/github/git-lfs/script.deb.sh | bash
apt-cache showpkg git-lfs
```

If I run on an amd64 machine all works fine

Work around for docker:

```dockerfile
ARG TARGETARCH
ARG GIT_LFS_VERSION=2.13.3

# required for multi-arch support, revert to package cloud after:
# https://github.com/git-lfs/git-lfs/issues/4546
RUN GIT_LFS_ARCHIVE="git-lfs-linux-${TARGETARCH}-v${GIT_LFS_VERSION}.tar.gz" \
    GIT_LFS_RELEASE_URL="https://github.com/git-lfs/git-lfs/releases/download/v${GIT_LFS_VERSION}/${GIT_LFS_ARCHIVE}"\
    set -x; curl --quiet --fail --location --show-error --output "/tmp/${GIT_LFS_ARCHIVE}" "${GIT_LFS_RELEASE_URL}" && \
    mkdir -p /tmp/git-lfs && \
    tar xzvf "/tmp/${GIT_LFS_ARCHIVE}" -C /tmp/git-lfs && \
    bash -x /tmp/git-lfs/install.sh && \
    rm -rf /tmp/git-lfs*
```

**Comment by bk2204** [comment]
Hey,

This is pretty much expected.  We don't currently build packages except on amd64 because we use GitHub Actions, which doesn't currently support arm64 Linux.  It is of course possible for us to build them in emulation, but that is extremely slow (in another project, a job that takes less than 10 minutes on amd64 takes over an hour and a half on arm64 in emulation).  Because our Linux package CI job is already one of our slowest, I'm not especially excited about adding another one that's ten times slower, if that's even possible on GitHub Actions without timing out.

However, we do provide released binaries for multiple architectures, which you may wish to use instead.  Alternatively, you could use the Debian-provided packages, which, while not completely up to date, may meet your needs.

I do want to be clear that I'm very much in favor of portability and I'm happy to support other architectures if GitHub Actions adds support for them, but I can't justify making our CI jobs and release process take seven and a half hours by running them in emulation.

I'll mark this as an enhancement to keep track of it for the future.

**Comment by timja** [comment]
Thanks we are fetching directly from releases for now, but that means we have to maintain the version rather than get regular updates.

the Debian version is far too old and has a known issue that we don’t want our users to hit. 

Thanks for the feedback looking forward to it at some point :)

**Comment by Benny1Blanco** [comment]
GIT-LFS(1)GIT-LFS(1)
NAME
git-lfs - Work with large files in Git repositories

SYNOPSIS
git lfs command [args]

DESCRIPTION
Git LFS is a system for managing and versioning large files in association with a Git repository. Instead of storing the large files within the Git repository as blobs, Git LFS stores special "pointer files" in the repository, while storing the actual file contents on a Git LFS server. The contents of the large file are downloaded automatically when needed, for example when a Git branch containing the large file is checked out.

Git LFS works by using a "smudge" filter to look up the large file contents based on the pointer file, and a "clean" filter to create a new version of the pointer file when the large file's contents change. It also uses a pre-push hook to upload the large file contents to the Git LFS server whenever a commit containing a new large file version is about to be pushed to the corresponding Git server.

COMMANDS
Like Git, Git LFS commands are separated into high level ("porcelain") commands and low level ("plumbing") commands.

High level commands (porcelain)
git-lfs-env(1)
Display the Git LFS environment.
git-lfs-checkout(1)
Populate working copy with real content from Git LFS files.
git-lfs-dedup(1)
De-duplicate Git LFS files.
git-lfs-ext(1)
Display Git LFS extension details.
git-lfs-fetch(1)
Download Git LFS files from a remote.
git-lfs-fsck(1)
Check Git LFS files for consistency.
git-lfs-install(1)
Install Git LFS configuration.
git-lfs-lock(1)
Set a file as "locked" on the Git LFS server.
git-lfs-locks(1)
List currently "locked" files from the Git LFS server.
git-lfs-logs(1)
Show errors from the Git LFS command.
git-lfs-ls-files(1)
Show information about Git LFS files in the index and working tree.
git-lfs-migrate(1)
Migrate history to or from Git LFS
git-lfs-prune(1)
Delete old Git LFS files from local storage
git-lfs-pull(1)
Fetch Git LFS changes from the remote & checkout any required working tree files.
git-lfs-push(1)
Push queued large files to the Git LFS endpoint.
git-lfs-status(1)
Show the status of Git LFS files in the working tree.
git-lfs-track(1)
View or add Git LFS paths to Git attributes.
git-lfs-uninstall(1)
Uninstall Git LFS by removing hooks and smudge/clean filter configuration.
git-lfs-unlock(1)
Remove "locked" setting for a file on the Git LFS server.
git-lfs-untrack(1)
Remove Git LFS paths from Git Attributes.
git-lfs-update(1)
Update Git hooks for the current Git repository.
git-lfs-version(1)
Report the version number.
Low level commands (plumbing)
git-lfs-clean(1)
Git clean filter that converts large files to pointers.
git-lfs-filter-process(1)
Git process filter that converts between large files and pointers.
git-lfs-pointer(1)
Build and compare pointers.
git-lfs-post-checkout(1)
Git post-checkout hook implementation.
git-lfs-post-commit(1)
Git post-commit hook implementation.
git-lfs-post-merge(1)
Git post-merge hook implementation.
git-lfs-pre-push(1)
Git pre-push hook implementation.
git-lfs-smudge(1)
Git smudge filter that converts pointer in blobs to the actual content.
git-lfs-standalone-file(1)
Git LFS standalone transfer adapter for file URLs (local paths).
EXAMPLES
To get started with Git LFS, the following commands can be used.

Setup Git LFS on your system. You only have to do this once per repository per machine:

git lfs install
Choose the type of files you want to track, for examples all ISO images, with git-lfs-track(1):

git lfs track "*.iso"
The above stores this information in gitattributes(5) files, so that file need to be added to the repository:

git add .gitattributes
Commit, push and work with the files normally:

git add file.iso
git commit -m "Add disk image"
git push
