### ISSUE TITLE
Failed to commit Invalid checksum

### ISSUE THREAD

**Issue by TechXero** [git-lfs/git-lfs#4553]
**Describe the issue**
I pushed a 320mb package for testing LFS, it pushes correctly but when I try to install I get the following error :

``:: File /var/cache/pacman/pkg/proton-ge-custom-1:6.12.GE.1-1-x86_64.pkg.tar.zst is corrupted (invalid or corrupted package (checksum)).
Do you want to delete it? [Y/n] 
error: failed to commit transaction (invalid or corrupted package (checksum))
Errors occurred, no packages were upgraded.``

**System environment**
I am on ArchLinux on a fairly recent system. 

That's my repo if you want to check files :
`https://github.com/xerolinux/xerolinux_xl`

**Output of `git lfs env`**

`````
git-lfs/2.13.3 (GitHub; linux amd64; go 1.16.4)
git version 2.32.0

Endpoint=https://github.com/xerolinux/xerolinux_xl.git/info/lfs (auth=none)
LocalWorkingDir=/home/techxero/xerolinux_xl
LocalGitDir=/home/techxero/xerolinux_xl/.git
LocalGitStorageDir=/home/techxero/xerolinux_xl/.git
LocalMediaDir=/home/techxero/xerolinux_xl/.git/lfs/objects
LocalReferenceDirs=
TempDir=/home/techxero/xerolinux_xl/.git/lfs/tmp
ConcurrentTransfers=8
TusTransfers=false
BasicTransfersOnly=false
SkipDownloadErrors=false
FetchRecentAlways=false
FetchRecentRefsDays=7
FetchRecentCommitsDays=0
FetchRecentRefsIncludeRemotes=true
PruneOffsetDays=3
PruneVerifyRemoteAlways=false
PruneRemoteName=origin
LfsStorageDir=/home/techxero/xerolinux_xl/.git/lfs
AccessDownload=none
AccessUpload=none
DownloadTransfers=basic,lfs-standalone-file
UploadTransfers=basic,lfs-standalone-file
GIT_EXEC_PATH=/usr/lib/git-core
git config filter.lfs.process = "git-lfs filter-process"
git config filter.lfs.smudge = "git-lfs smudge -- %f"
git config filter.lfs.clean = "git-lfs clean -- %f" f 
`````

**Additional context**
Not that I can think of...

**Comment by bk2204** [comment]
Hey, 

It looks like the problem is this:

```
Downloading x86_64/proton-ge-custom-1:6.12.GE.1-2-x86_64.pkg.tar.zst (336 MB)
Error downloading object: x86_64/proton-ge-custom-1:6.12.GE.1-2-x86_64.pkg.tar.zst (5f5a157): Smudge error: Error downloading x86_64/proton-ge-custom-1:6.12.GE.1-2-x86_64.pkg.tar.zst (5f5a15766c3d78f339b104b368df69effc5254aa88dcb3ae12b56205db04f418): batch response: This repository is over its data quota. Account responsible for LFS bandwidth should purchase more data packs to restore access.
```

GitHub has a limit of 1 GB worth of free LFS bandwidth, and you're over your limit, which is preventing your files from being checked out into your repository.  That's why the file in your tree is remaining as the pointer file that LFS uses to track things instead of being replaced with the actual file content.  If you're interested in reading more about this, [you can see the relevant page on the GitHub documentation](https://docs.github.com/en/github/managing-large-files/versioning-large-files/about-storage-and-bandwidth-usage).

This isn't really a problem with the Git LFS client, and since we don't provide support for any specific hosting platforms here, if you have further questions, please contact GitHub Support.
