### ISSUE TITLE
Using api to get git LFS download url issue

### ISSUE THREAD

**Issue by dodozhang21** [git-lfs/git-lfs#4561]
Hi, I used the API e.g. https://api.github.com/repos/{REPO}/{filePath} to get the download url. It works well locally but when I use github action do the work using github token, the download URL/token appears to expire after a period of time.

Is this expected or did I do something wrong?

**System environment**
github action runner

**Comment by bk2204** [comment]
Hey,

This sounds like a question about GitHub.  This repository is only for the open source Git LFS client, not any server implementation, like GitHub.

I believe that the answer is that it's intentional that the token expires.  If you have more questions about GitHub or GitHub's implementation of Git LFS, please contact GitHub Support for more details.
