### ISSUE TITLE
GIT LFS slowing down for files having size more than 60-80gb

### ISSUE THREAD

**Issue by karthikthota-3** [git-lfs/git-lfs#4630]
Is there capacity limitation for Git LFS? Or some other side effect?

It's not giving desired result for files of sizes > 50gb , when trying to push files of size 80gb process is ending abruptly and push logs showing it's trying to push size more than double(220gb) to actual file size.

For directory having big size(150-200gb) having multiple small files, git lfs is working but taking lot of time.

Is there any work around to reduce git lfs mechanism time for big size directories.

**Comment by bk2204** [comment]
Hey,

There is no intrinsic limitation of the size of files in Git LFS.  However, the server to which you're pushing may have such a limit, or you may be having a network problem.  To see what the problem is, you'd need to run with `GIT_TRACE=1 GIT_TRANSFER_TRACE=1 GIT_CURL_VERBOSE=1` to see the response from the server.  I suspect the case is that the server is just not willing to handle files that large.

If the problem you're seeing is that Git LFS is taking a long time for `git add`, then we do plan to improve that in the future for systems that have native SHA extensions, such as newer Intel and AMD systems and some ARM64 systems, but otherwise it's pretty much unavoidable.  If the problem is that it takes a long time to push, then that's likely due to the network, although there could possibly be some places where we could improve performance.
