### ISSUE TITLE
Instructions for verifying a release do not work, cannot get keys

### ISSUE THREAD

**Issue by Chuxel** [git-lfs/git-lfs#4632]
If you follow the instructions in the README to verify a release, it says that you can get the required public keys as follows:

```
curl -L https://api.github.com/repos/git-lfs/git-lfs/tarball/core-gpg-keys | tar -Ozxf -
```

Unfortunately, `https://api.github.com/repos/git-lfs/git-lfs/tarball/core-gpg-keys` 404s. Not sure if this is docs being out of date or a bug.  I'm looking to get Linux arm64 builds and given apt-get packages are x86 only, I need to fall back to this method.

**Comment by bk2204** [comment]
Hey,

Thanks for the report.  It actually returns a 500 on the API side, which is a bug in GitHub.  I'll report this to see if I can get it fixed.

**Comment by bk2204** [comment]
In the mean time, while that's being fixed, you can clone the repository and run `git archive refs/tags/core-gpg-keys | tar -Ozxf` to get the GnuPG keys for the core team, or you can download them from the links under the pictures under the core team members in the README.

**Comment by Chuxel** [comment]
One challenge here too is that api.github.com has rate limits.  One thing I do see other projects do is have a file with the keys in main available to simply `curl` down in automation scenarios.  e.g. for Helm: https://raw.githubusercontent.com/helm/helm/main/KEYS

**Comment by bk2204** [comment]
Yes, it does have rate limits.  Those rate limits are 5000 per hour if you authenticate, which should be sufficient for anyone's needs.  If you need to deploy a large number of builds to a large number of machines, I recommend that you either build packages using our packaging tooling, or otherwise deploy some sort of packaging of our builds on your own infrastructure.

I'm a member of the team that runs the service that powers archives and raw file handling at GitHub and I made a specific decision to do it this way because excessive use of the raw endpoints is a problem for us, whereas the approach I used forces people to go through rate limiting, which prevents excessive use.  So it is fully intentional that people will be rate limited and that if they need to make many requests, that they will have to authenticate, so as to prevent abuse of that service and provide a point of contact in case folks use too many resources.

**Comment by Chuxel** [comment]
Yeah in this case, this is for a user script for use in GitHub Codespaces and VS Code Remote - Containers (the latter needing arm64). Unfortunately we can't assume a sign in realistically here since its in a Docker build. This is end user driven rather than CI driven.

**Comment by bk2204** [comment]
I appreciate that this design adds some complexity, but I will point out that the raw endpoints also have rate limits here, even if the enforcement isn't exactly identical, so you're really not guaranteed to be able to make more requests than the API.

It is unlikely that the core team members' keys will change frequently, so you could choose to hard-code those in the script if you like and then verify the signatures with those keys.  Practically, I am the person who does the releases and I intend to continue to do them, so they are almost always signed with my key, although of course I could encounter some bad luck and get hit by a bus, in which case someone else would need to do them.

**Comment by bk2204** [comment]
I've verified that the URL and command you've provided do now work as before and that they no longer return a 500 error, so I'm going to close this.
