### ISSUE TITLE
Reindexing files existing in git repo upon adding .gitattributes does not handle various case variants for file extensions

### ISSUE THREAD

**Issue by yourhumblebugspotter** [git-lfs/git-lfs#4659]
1. A new git repository contained a number of files, including *.fbx and *.FBX files, and no .gitattributes initially.
2. .gitattributes file was added to the repo and "git rm --cached -r ." and "git add -A" was applied.
3. .gitattributes file had the following relevant lines, note - macro is used for clarity as .gitattributes specifies a large number of extensions and other macro are in use (which do not include fbx).
    [attr]macro_lfs filter=lfs diff=lfs merge=lfs -text
    *.fbx macro_lfs
4. git lfs started tracking *.fbx files, but ignored *.FBX which existed in the repository already which was obvious when viewing output of "git lfs ls-files" and checking which files were known to git.
5. Observed on Ubuntu 20.04 with git-lfs/2.9.2 (GitHub; linux amd64; go 1.13.5); git version 2.25.1

Testing was done on another repository using "*.fbx" mask for new files and adding *.FBX files was handled normally as one would expect - with LFS starting tracking any case automatically.

A workaround for any future reuse of .gitattributes file was put in place manually to use file extension mask ".[Ff][Bb][Xx]" explicitly.

As it did not seem that "git lfs" provided an option to track/untrack files ignoring the capitalisation, it confirmed the idea that it should be handled internally, which would make sense, so .gitattributes would stay as simple as possible with only a single extension, hence the problem of capitalisation not being handled correctly for files already in the repo could constitute a bug.

**Comment by KalleOlaviNiemitalo** [comment]
It should be consistent with what `git check-attr` does.

**Comment by KalleOlaviNiemitalo** [comment]
[gitattributes](https://git-scm.com/docs/gitattributes) says the pattern matching is almost the same as in [gitignore](https://git-scm.com/docs/gitignore), which does not say whether it is case-sensitive. Does [core.ignoreCase](https://git-scm.com/docs/git-config#Documentation/git-config.txt-coreignoreCase) affect this?

**Comment by bk2204** [comment]
What you've done here is sort of equivalent to `git add --renormalize .`, which is a better way to do this.  However, Linux is typically case sensitive, so Git's pattern matching won't match case insensitively.  Note that the decision with `git add` is made by Git, and not Git LFS.  Git tells Git LFS which files to filter, and Git LFS does it.

If your repository is intended to work cross platform, you're much better off requiring a fixed case for all file names because of this issue.  The question of which files are filtered is an artifact of `core.ignorecase`, which is set by Git (and which should not be modified) to adjust whether it think the file system is case insensitive or not.
