### ISSUE TITLE
No git-lfs progress meter during `git clone`

### ISSUE THREAD

**Issue by gobenji** [git-lfs/git-lfs#4696]
**Describe the bug**
When cloning a repository that contains lfs files, there is no progress meter displayed while git-lfs is fetching files. Since the fetch can take a while, it would be helpful to provide some feedback to the user while the operation is in progress.

In some cases, depending on the repository that I clone, there is a progress meter that's output **after** the operation is completed:
```
Filtering content: 100% (2/2), 181.87 MiB | 442.00 KiB/s, done.
```
In other cases, there's nothing at all.

**To Reproduce**
```git clone <url>```

**Expected behavior**
When doing
```
GIT_LFS_SKIP_SMUDGE=1 git clone [...]
cd <repo>
git lfs fetch
```
There is a progress meter that is printed and updated throughout the fetching operation. I would expect the same kind of behavior when the git-lfs fetch happens as part of the clone.

**System environment**
Debian GNU/Linux bookworm/sid
git-lfs/2.13.3 (GitHub; linux amd64; go 1.15.15)
git version 2.33.0

If it's any help, while the clone is taking place, there is the following process tree:
```
627486  ?        \_ xterm -class UXTerm -title uxterm -u8
627490  pts/8    |   \_ bash
627518  pts/8    |       \_ git clone <url>
627531  pts/8    |           \_ /bin/sh -c git-lfs filter-process git-lfs filter-process
627532  pts/8    |               \_ git-lfs filter-process
```

Files for the git-lfs process are:
```
ben@d3:~$ l /proc/627532/fd/
total 0
dr-x------ 2 ben ben  0 Oct 21 10:19 .
dr-xr-xr-x 9 ben ben  0 Oct 21 10:17 ..
lr-x------ 1 ben ben 64 Oct 21 10:19 0 -> pipe:[4664239]
l-wx------ 1 ben ben 64 Oct 21 10:19 1 -> pipe:[4664240]
lrwx------ 1 ben ben 64 Oct 21 10:19 2 -> /dev/pts/8
lrwx------ 1 ben ben 64 Oct 21 10:19 3 -> socket:[4655859]
lrwx------ 1 ben ben 64 Oct 21 10:19 4 -> anon_inode:[eventpoll]
lr-x------ 1 ben ben 64 Oct 21 10:19 5 -> pipe:[4663214]
l-wx------ 1 ben ben 64 Oct 21 10:19 6 -> pipe:[4663214]
lrwx------ 1 ben ben 64 Oct 21 10:19 7 -> /tmp/repo/.git/lfs/incomplete/<hash>
```
fd 0, 1 are pipes with the `git clone` process.

Using strace, I can see that git writes its progress ("Receiving objects:", ...) to stderr. In cases where it does, git-lfs also writes its progress to stderr but it makes only two updates:
```
write(2, "Filtering content: 100% (2/2), 181.87 MiB | 473.00 KiB/s\r", 57) = 57
write(2, "Filtering content: 100% (2/2), 181.87 MiB | 470.00 KiB/s, done.\n", 64) = 64
```

**Comment by bk2204** [comment]
Hey,

The “Filtering content” message comes from Git itself, not from Git LFS.  If it isn't showing up, then that's a report you'd want to make to the Git mailing list, since we don't have any control over it.  It is supposed to be delayed unless it takes a while, so perhaps that's what's happening here, especially since you have only two files.

In fact, unless you invoke Git LFS manually, we can't effectively print any sort of message here because Git's message will overwrite it and both will become hard to read.  We normally perform the fetch during the “Filtering content” message, so that's the message that you should expect to see in this case.

I'd recommend that you report this to the Git mailing list and see what they have to say about this.

**Comment by gobenji** [comment]
> The “Filtering content” message comes from Git itself, not from Git LFS.

Thanks for pointing that out.
Looking at `finish_delayed_checkout()` in the git source, it seems that the progress meter is only updated with a file-level granularity.
