### ISSUE TITLE
Cannot use *netrc.Netrc value as type netrcfinder in return argument

### ISSUE THREAD

**Issue by Cactusinhand** [git-lfs/git-lfs#4716]
**Describe the issue**
```bash
$ go get github.com/git-lfs/git-lfs                                                                                                                
github.com/git-lfs/git-lfs/config
../gowork/pkg/mod/github.com/git-lfs/git-lfs@v2.5.2+incompatible/config/netrc.go:31:2: cannot use *netrc.Netrc value as type netrcfinder in return argument:
        *netrc.Netrc does not implement netrcfinder (wrong type for FindMachine method)
                have FindMachine(string, string) *netrc.Machine
                want FindMachine(string) *netrc.Machine
```
**System environment**
Linux 5.10.16.3-microsoft-standard-WSL2 
x86_64 x86_64 x86_64 GNU/Linux

**Output of `git lfs env`**
```bash
$ git lfs env                                                                                                                                                                                        
git-lfs/3.0.0 (GitHub; linux amd64; go 1.17)
git version 2.33.0

Endpoint=https://gitee.com/oschina/git-clean-repo.git/info/lfs (auth=none)
  SSH=git@gitee.com:oschina/git-clean-repo.git
LocalWorkingDir=/home/git/git-clean-repo
LocalGitDir=/home/git/git-clean-repo/.git
LocalGitStorageDir=/home/git/git-clean-repo/.git
LocalMediaDir=/home/git/git-clean-repo/.git/lfs/objects
LocalReferenceDirs=
TempDir=/home/git/git-clean-repo/.git/lfs/tmp
ConcurrentTransfers=8
TusTransfers=false
BasicTransfersOnly=false
SkipDownloadErrors=false
FetchRecentAlways=false
FetchRecentRefsDays=7
FetchRecentCommitsDays=0
FetchRecentRefsIncludeRemotes=true
PruneOffsetDays=3
PruneVerifyRemoteAlways=false
PruneRemoteName=origin
LfsStorageDir=/home/git/git-clean-repo/.git/lfs
AccessDownload=none
AccessUpload=none
DownloadTransfers=basic,lfs-standalone-file,ssh
UploadTransfers=basic,lfs-standalone-file,ssh
GIT_EXEC_PATH=/usr/local/libexec/git-core
git config filter.lfs.process = "git-lfs filter-process"
git config filter.lfs.smudge = "git-lfs smudge -- %f"
git config filter.lfs.clean = "git-lfs clean -- %f"
```
**Additional context**
None

**Comment by chrisd8088** [comment]
Hey, I'm sorry you're having trouble.  I notice you're trying to use `go get` and the version of the Git LFS source code being returning is very old (2.5.2) and no longer supported.

Not long ago we had a report of problems with `go get` in #4574 and determined that due to some metadata issues, the latest version cached there under `github.com/git-lfs/git-lfs` was very old (and still is, and will continue to be).

The recommended approach to retrieving Git LFS source code is to use `git clone`, i.e., `git clone https://github.com/git-lfs/git-lfs`.  But please note the [limitation](https://github.com/git-lfs/git-lfs#limitations) described in our `README` that this project is not a conventional Go module and no guarantee of a stable API is possible.

That all said, if you must use `go get`, at least use the latest version by using the `/v3` suffix, i.e., `go get github.com/git-lfs/git-lfs/v3`.

**Comment by Cactusinhand** [comment]
@chrisd8088  Thanks for your reply, it's helpful for me!
Can you please take a look at my question in Discussions [here](https://github.com/git-lfs/git-lfs/discussions/4715#discussion-3658087)?
