### ISSUE TITLE
changelog is not updated with 3.0.1 and 3.0.2 

### ISSUE THREAD

**Issue by berndschatz** [git-lfs/git-lfs#4727]
**Describe the bug**
Missing entries in changelog for 3.0.1 and 3.0.2 releases.

**To Reproduce**
see -->  https://github.com/git-lfs/git-lfs/blob/main/CHANGELOG.md

**Comment by KalleOlaviNiemitalo** [comment]
The entries could be copied from the releases on GitHub:

* <https://github.com/git-lfs/git-lfs/releases/tag/v3.0.1>
* <https://github.com/git-lfs/git-lfs/releases/tag/v3.0.2>

**Comment by bk2204** [comment]
Hey,

It's intentional that we don't update the CHANGELOG entries on the `main` branch until we do a release off that branch.  They are, however, available on the `release-3.0` branch if you're curious: https://github.com/git-lfs/git-lfs/blob/release-3.0/CHANGELOG.md.  That's the branch off of which we built 3.0.1 and 3.0.2.
