### ISSUE TITLE
LFS object push is skipped after deleting it remotely

### ISSUE THREAD

**Issue by xzy57369** [git-lfs/git-lfs#4742]
**Describe the issue**
Hi!
I meet a situation which causes a little bit confusing. 

Consider that we successfully uploaded a Git LFS object (say, `a.bin` ) to the remote, 
then delete it directly on the object storage remote (such as S3).
Then we rename `a.bin` to `b.bin` locally and do a normal git push procedure.

In this case, the push procedure will skip the lfs push process, since the OID is not changed 
and LFS thoughts it has been uploaded to the server right? 

So, what confusing me here is that how LFS remember which obejcts have been pushed to the 
remote server? After all, it won't write some file to record this information.

And does this situation behaved expectedly? For the git point of view, `b.bin` is a new file and have 
been pushed successfully. But the reality is we only got two pointers which points to a non-exist bin file.

**System environment**

**Output of `git lfs env`**

**Additional context**

**Comment by dyrone** [comment]
Hi @bk2204 

Thanks for the reply.

I took a look at the conversation, so do you think if it is possible to contribute new/append some documentation modifications about this issue in the project?

**Comment by bk2204** [comment]
We'd be happy to accept a patch, but I wouldn't characterize this as an "issue".  It's an intentional decision to improve performance, and usually users complain that the optimizations aren't effective enough, not that some things aren't pushed.

If your remote is deleting objects that are still referenced, that's not considered a supported situation, and you should avoid having your remote do that (or doing it manually).

**Comment by dyrone** [comment]
I see. 
Thanks, Brian.
