### ISSUE TITLE
git lfs migrate import include filter issue starting with version 3.0.1

### ISSUE THREAD

**Issue by rolandas-rimkus** [git-lfs/git-lfs#4751]
**Describe the bug**
Starting with version 3.0.1 of Git LFS running **git lfs migrate import** with a include pattern like *.extension started affecting directory names that also end with the same pattern. For example if *.model is used all files under a directory VS.Project.Parse.Model would be added under Git LFS. This was not the case in version 2.13.3.

The documentation for [gitattributes ](https://git-scm.com/docs/gitattributes) seems to indicate that using *.extension should not affect directories so it seems like a bug was introduced in the version 3.0.1 of Git LFS.

**To Reproduce**
1. Install Git version 2.33.1 or newer from: https://github.com/git-for-windows/git/releases
2. Run the following commands under a Windows Command Prompt
```
git init D:\GitLfsBug
mkdir D:\GitLfsBug\Data
mkdir D:\GitLfsBug\VS.Project.Parse.Model
echo Test > D:\GitLfsBug\Data\aaa.model
echo Test > D:\GitLfsBug\Data\aaa.txt
echo Test > D:\GitLfsBug\VS.Project.Parse.Model\bbb.txt
echo Test > D:\GitLfsBug\VS.Project.Parse.Model\ccc.txt
git -C D:\GitLfsBug add --all .
git -C D:\GitLfsBug commit -m "Test" --all
git -C D:\GitLfsBug lfs install
git -C D:\GitLfsBug lfs migrate import --yes --include="*.model"
git -C D:\GitLfsBug lfs ls-files --size --long
```
3. Note down that the files tracked under LFS are: Data\aaa.model, VS.Project.Parse.Model\bbb.txt and VS.Project.Parse.Model\ccc.txt
4. Download Git LFS version 2.13.3 from https://github.com/git-lfs/git-lfs/releases/download/v2.13.3/git-lfs-windows-amd64-v2.13.3.zip
5. Apply the git-lfs.exe file on top of mingw64\bin\git-lfs.exe in the install location of Git
6. Repeat step 2
7. Note down that the only file tracked under LFS is: Data\aaa.model

**Expected behavior**
Directories that match the file filter passed into git lfs migrate import should not be tracked under Git LFS as was the case in versions up to 3.0.1.

**System environment**
Windows 10 v1909

**Output of `git lfs env`**
git-lfs/3.0.1 (GitHub; windows amd64; go 1.17.1)
git version 2.33.1.windows.1

LocalWorkingDir=D:\Work\GitLfsBug
LocalGitDir=D:\Work\GitLfsBug\.git
LocalGitStorageDir=D:\Work\GitLfsBug\.git
LocalMediaDir=D:\Work\GitLfsBug\.git\lfs\objects
LocalReferenceDirs=
TempDir=D:\Work\GitLfsBug\.git\lfs\tmp
ConcurrentTransfers=8
TusTransfers=false
BasicTransfersOnly=false
SkipDownloadErrors=false
FetchRecentAlways=false
FetchRecentRefsDays=7
FetchRecentCommitsDays=0
FetchRecentRefsIncludeRemotes=true
PruneOffsetDays=3
PruneVerifyRemoteAlways=false
PruneRemoteName=origin
LfsStorageDir=D:\Work\GitLfsBug\.git\lfs
AccessDownload=none
AccessUpload=none
DownloadTransfers=basic,lfs-standalone-file,ssh
UploadTransfers=basic,lfs-standalone-file,ssh
GIT_EXE="C:\Git\Git-2.33.1\cmd\git.exe"
GIT_EXEC_PATH=C:/Git/Git-2.33.1/mingw64/libexec/git-core
git config filter.lfs.process = "git-lfs filter-process"
git config filter.lfs.smudge = "git-lfs smudge -- %f"
git config filter.lfs.clean = "git-lfs clean -- %f"

**Additional context**
This issue seems to be independent from Git version itself as I managed to reproduce the same issue with replacing the Git LFS delivered in Git versions 2.33.0, 2.33.1, 2.34.0 and 2.34.1. So currently both 3.0.1 and 3.0.2 is affected no matter with which Git version it is being used.

This is a breaking change that might cause files to be tracked under Git LFS when they were not suppose to and requiring a full remigration of a Git repository using an older version.

**Comment by KalleOlaviNiemitalo** [comment]
> The documentation for [gitattributes](https://git-scm.com/docs/gitattributes) seems to indicate that using *.extension should not affect directories

\*.extension in .gitattributes affects directories all right.

```
Kalle@computer MINGW64 ~
$ mkdir attrdemo

Kalle@computer MINGW64 ~
$ cd attrdemo

Kalle@computer MINGW64 ~/attrdemo
$ git init
Initialized empty Git repository in C:/Users/Kalle/attrdemo/.git/

Kalle@computer MINGW64 ~/attrdemo (master)
$ mkdir demo.ext

Kalle@computer MINGW64 ~/attrdemo (master)
$ touch demo.ext\file

Kalle@computer MINGW64 ~/attrdemo (master)
$ echo '*.ext fancy=true' > .gitattributes

Kalle@computer MINGW64 ~/attrdemo (master)
$ git check-attr -a demo.ext
starting fsmonitor-daemon in 'C:/Users/Kalle/attrdemo'
demo.ext: fancy: true
```

**Comment by rolandas-rimkus** [comment]
@KalleOlaviNiemitalo correct but using your own example the file itself is still not affected as `git check-attr -a demo.ext\file' returns nothing. 

I would still consider this a regression in Git LFS as even if the directory is affected by Git LFS unless you specify something like "demo.ext/**" I would not expect it to recursively affect all files under a directory.

**Comment by KalleOlaviNiemitalo** [comment]
I see. That does look like a bug, then. The [git-lfs-migrate documentation](https://github.com/git-lfs/git-lfs/blob/main/docs/man/git-lfs-migrate.1.ronn) even states that _"the `path/**` format may be used to match recursively"_, implying that a directory path without `**` will not match the files within.

**Comment by chrisd8088** [comment]
Hey, thanks for the report; from a first look, this does sound like unintentional behaviour.  The goal with v3.0 is to make Git LFS wildmatch parsing follow the `gitattributes(5)` and `gitignore(5)` rules exactly (with the specific case determining which set of rules apply).

All of the `git lfs` commands which take the `--include/-I` and `--exclude/-X` options, like `git lfs fetch`, `git lfs pull`, `git lfs ls-files`, etc., use a common `buildFilepathFilter()` helper function which was revised in #4556 to explicitly request `gitignore`-style matching.  For one thing, that's in line with how Git's own `git ls-files` works when you specify the `-o --exclude="..."` options.  So it's possible we need to update some of the documentation, at a minimum, such as for `git lfs migrate`.

But I can also see that in the case of `git lfs migrate`, the `gitignore` style of matching would be confusing at best, because what that command's `import` and `export` sub-commands do is, of course, generate `.gitattributes` files based on what the user requests and/or what is found in the Git history.

Arguably we should have taken the opportunity of v3.0 to rename the `git lfs migrate` options for including or excluding file paths to something else, like `--include-path`/`--exclude-path`, both to better to distinguish them from the `--include-ref`/`--exclude-ref` options, and to clarify that they follow different rules than other commands' options like `git lfs fetch --include`.

I think this is something it would be good if the other @git-lfs/core folks had a chance to consider, because I'm not sure what the right solution is at this point.

**Comment by bk2204** [comment]
I think the question here is, do we insert the patterns given into the `.gitattributes` file?  If so, then it's a bug that they aren't gitattributes-style patterns, since we're not transforming all the files we'd be expected to.

**Comment by rolandas-rimkus** [comment]
Yes the pattern gets inserted into the `.gitattributes` file. And because of that there is also a divergence between `git lfs track` and `git lfs migrate import` as this still runs as expected and only has a single file tracked:
```
git init D:\GitLfsBug
mkdir D:\GitLfsBug\Data
mkdir D:\GitLfsBug\VS.Project.Parse.Model
git -C D:\GitLfsBug lfs install
git -C D:\GitLfsBug lfs track "*.model"
git -C D:\GitLfsBug add --all .
git -C D:\GitLfsBug commit -m "Initial commit" --all
echo Test > D:\GitLfsBug\Data\aaa.model
echo Test > D:\GitLfsBug\Data\aaa.txt
echo Test > D:\GitLfsBug\VS.Project.Parse.Model\bbb.txt
echo Test > D:\GitLfsBug\VS.Project.Parse.Model\ccc.txt
git -C D:\GitLfsBug add --all .
git -C D:\GitLfsBug commit -m "Test" --all
git -C D:\GitLfsBug lfs ls-files --size --long
```

**Comment by chrisd8088** [comment]
IIUC the concern here is that the `git lfs migrate` command uses `buildFilepathFilter()` to parse the `--include` and `--exclude` options, like various other commands, and that [always](https://github.com/git-lfs/git-lfs/blob/b97f5f4e5557b41a486bf87512a96981e9e1d9d9/commands/commands.go#L133) sets the wildmatch pattern matching to the `gitignore(5)` style of matching.

That pattern-matching filter is then [passed](https://github.com/git-lfs/git-lfs/blob/b97f5f4e5557b41a486bf87512a96981e9e1d9d9/commands/command_migrate.go#L310-L313) to the Git history rewriter, which [uses](https://github.com/git-lfs/git-lfs/blob/b97f5f4e5557b41a486bf87512a96981e9e1d9d9/git/githistory/rewriter.go#L445-L4460 it on each blob it examines to determine if the blob's full file path matches, and if so, puts it into the set of paths from which it then deduces what to put into `.gitattributes`.  But that means `gitignore(5)` matching rules are being used to deduce what to insert into files that will then be parsed by Git using `gitattributes(5)` matching rules.

So again, if I understand correctly, specifying `--include="*.bin"` creates a `.gitignore`-style wildmatch filter which then matches against a blob's path such as `foo.bin/bar.txt`, and so (a) that file is migrated to a Git LFS object, regardless of the `*.txt` extension, and (b) the filter that matched is written into `.gitattributes`, i.e., `*.bin`.

```
$ git init test
$ cd test
$ mkdir foo.bin bar
$ echo abc > foo.bin/abc.txt
$ echo def > foo.bin/def
$ echo ghi > bar/ghi.txt
$ echo xyz > bar/xyz.bin
$ git add .
$ git commit -m init

$ git lfs migrate import --include="*.bin"

$ cat .gitattributes 
*.bin filter=lfs diff=lfs merge=lfs -text

$ git lfs ls-files
f34fe622a8 - bar/xyz.bin
edeaaff3f1 - foo.bin/abc.txt
da1464fd7c - foo.bin/def
```

Assuming that's accurate (and I haven't located the specific code which causes the specified filter pattern to be included in `.gitattributes`), it occurred to me that one possibility would be to have `buildFilepathFilter()` take an `PatternType` kind of argument, like `filepathfilter` [supports](https://github.com/git-lfs/git-lfs/blob/b97f5f4e5557b41a486bf87512a96981e9e1d9d9/filepathfilter/filepathfilter.go#L23-L35), and pass that down to the new filter.  Then most commands could pass `GitIgnore` to `buildFilepathFilter()` but `git lfs migrate` could pass `GitAttributes`.

However ... that means `--include`/`-I` and `--exclude`/`-X` for `git lfs migrate` are more obviously different from other commands' options of the same name.  They already are rather different in what they do, but now they'd be really different.  So that's why I started musing above in https://github.com/git-lfs/git-lfs/issues/4751#issuecomment-979782408 about renaming them entirely to something like `--include-path`/`--exclude-path` to clarify a bit that they are distinct in their functionality.
