### ISSUE TITLE
How to undo git lfs migrate import fbx - models are gone

### ISSUE THREAD

**Issue by bwdev77** [git-lfs/git-lfs#4752]
Hey guys, I made stupid things... I have been stucked when I tryed to push 250MB fbx files with Git lfs on. Nothing worked.
Then I was searching the solution so I found and try **lfs migrate import**, specifically **lfs migrate import="*.fxb"**
Suddenly every single .fbx has no model inside (just 1kb file) and Im still choked and stressed what to do to reverse it. 
Did it worked for **all** branches???  I am afraid to do something on repository right now. I dont know what to do...

**Comment by bwdev77** [comment]
This is what I have done and the result.

$ git lfs migrate import --include="*.fbx"
migrate: override changes in your working copy?  All uncommitted changes will be lost! [y/N] y
migrate: changes in your working copy will be overridden ...
migrate: Fetching remote refs: ..., done.
migrate: Sorting commits: ..., done.
migrate: Rewriting commits: 100% (2/2), done.
  bw_workspace                          4a7788b2c8c7c2f6dbe211dbe0c611dccc86b06e -> 6b3bf7a648a170724a91b26044f9de1fb9504ed4
migrate: Updating refs: ..., done.
migrate: checkout: ..., done.

**Comment by chrisd8088** [comment]
Hey, I'm sorry you're having trouble.  To answer one of your questions first, the command you ran (`git lfs migrate import --include="*.fbx"`) will not have affected all branches, because you didn't supply the `--everything` option.  By default, `git lfs migrate` operates only on the checked-out branch.

It might be useful to review the man [page](https://github.com/git-lfs/git-lfs/blob/main/docs/man/git-lfs-migrate.1.ronn) which covers a number of details like that.

You mention that all your `*.fbx` files are small now -- that's because they were converted into Git LFS pointer files.  The actual data resides in Git LFS object files, which will be stored in `.git/lfs/objects` and referenced by hash.  Your situation sounds like it might be described in this [section](https://github.com/git-lfs/git-lfs/blob/main/docs/man/git-lfs-migrate.1.ronn#migrate-unpushed-commits) of the man page:
> If after conversion you find that some files in your working directory have been replaced with Git LFS pointers, this is normal, and the working copies of these files can be repopulated with their full expected contents by using `git lfs checkout`.

So you could try `git lfs checkout` to see if it replaces the Git LFS pointer files in your working tree with the contents from the Git LFS object files.  Note that this won't change anything that's actually in your Git history or Git LFS; it's just "re-inflating" your checked-out working tree after the `import` command.  All the file data is already in the Git LFS object files under `.git/lfs/objects`.

You could also try `git lfs ls-files` to see what's listed, and 

---

Now you asked about reversing the import step.  This is where it's useful to understand what it did.  As noted in the man page:
> When converting files to or from Git LFS, the `git lfs migrate` command will only make changes to your local repository and working copy, never any remotes. This is intentional as the `import` and `export `modes are generally "destructive" in the sense that they rewrite your Git history, changing commits and generating new commit SHAs....
>
> You should therefore always first commit or stash any uncommitted work before using the `import` or `export` modes, and then validate the result of the migration before pushing the changes to your remotes, for instance by running the info mode and by examining your rewritten commit history.
>
> Once you are satisfied with the changes, you will need to force-push the new Git history of any rewritten branches to all your remotes. This is a step which should be taken with care, since you will be altering the Git history on your remotes.

So the `git lfs migrate import` command will have rewritten the history of your currently checked-out branch.  That means the SHA IDs of any commits with `*.fbx` files will have changed.  So depending on where in your branch you added those files, and when you last pushed to your remote, you may well not be able to just push your migrated branch ... but it really depends on your specific Git history and the state of your remote.  (That is, if you added all the `*.fbx` files since you last pushed, you might be OK to just push to your remote, because the rewritten commit history will only apply to commits you added locally and which your Git remote doesn't know about yet.  But if there were `*.fbx` files back further in your history, in commits you've previously pushed, then you'd have to force-push, and I wouldn't recommend that unless you are certain you want to rewrite the history on your remote.)

There is a `git lfs migrate export` command which "reverses" an import, but it does so by again rewriting your commit history, not by restoring the exact set of commits and their IDs which existed prior to your import.  (That's why the manual calls these steps "destructive".)

What you might want to do instead is just rename your rewritten branch to something else and check out the branch from your remote again, in the state it was in when you last pushed.  If your remote is named `origin`, perhaps something like:
```
$ git branch -m bw_workspace_lfs_rewritten
$ git checkout --track origin/bw_workspace
```

---

On the other hand, if your branch was entirely local and you never pushed it, you won't be able to "undo" the import just by checking it out from the remote again.

In that case, if you want to reverse the import, `git lfs migrate export --include="*.fbx"` would rewrite your branch's history again, this time putting the data files back into Git proper and removing the Git LFS object and pointer files.
