### ISSUE TITLE
Why does git lfs track not ignore untracked files in git

### ISSUE THREAD

**Issue by rainwf** [git-lfs/git-lfs#4757]
The description of the LFS post-checkout hook is "Responds to Git post-checkout events. It makes sure that any files which are marked as lockable by git lfs track are read-only in the working copy, if not currently locked by the local user."

This makes sense for git tracked files.  Apparently though, it applies to git untracked files in the working copy.

echo tracked > tracked.txt
git add tracked.txt
git commit tracked.txt -m "tracked"
echo untracked > untracked.txt
ls -l  
total 2
-r--r--r-- 1 My Name 1049089 8 Dec 2 09:17 tracked.txt
-rw-r--r-- 1 My Name 1049089 10 Dec 2 09:18 untracked.txt

git checkout master -- tracked.txt
ls -l
total 2
-r--r--r-- 1 My Name 1049089 8 Dec 2 09:17 tracked.txt
-r--r--r-- 1 My Name 1049089 10 Dec 2 09:18 untracked.txt

.gitattributes
    * filter=lfs diff=lfs merge=lfs -text lockable
    .gitattributes -filter -diff -merge -text
    .gitattributes export-ignore
    README.md export-ignore

**Comment by bk2204** [comment]
Hey,

Git LFS has the option to handle ignored files as well as tracked files.  This is controlled by the option `lfs.lockignoredfiles`, which defaults to false (that is, this behavior should be disabled by default).  This exists because users have asked for the behavior.

However, we probably shouldn't handle untracked but not ignored files.  I'll see if I can get a PR opened to fix this relatively soon.
