### ISSUE TITLE
ntlm challenge not answered

### ISSUE THREAD

**Issue by BMBurstein** [git-lfs/git-lfs#4777]
**Describe the bug**
Using git-lfs 3.0.1, I am unable to clone a repo with lfs. I am getting an error "authorization error".
I tried 2.12.0 and I was able to clone it.
I am using git for Windows. The repo I am cloning is on a local Azure. The whole thing is on a local network, so I can't copy-paste logs to here.
I tried sniffing the traffic, and I see that with 2.12, the sequence is

```
-> HTTP POST
<- 401 (WWW-Authenticate includes NTLM)
-> HTTP POST (NTLM negotiate)
<- 401 (NTLM challenge)
-> HTTP POST (NTLM response)
<- 200
```

while with the 3.0.1 version, the sequence is

```
-> HTTP POST
<- 401 (WWW-Authenticate includes NTLM)
-> HTTP POST (NTLM negotiate)
<- 401 (NTLM challenge)
-> HTTP POST (NTLM negotiate)
<- 401 (NTLM challenge)
```

I know NTLM was supposedly removed, but it looks to me like it may have been only partially removed. It looks like lfs still responds to the NTLM authentication option, but not to the NTLM challenge.

**Comment by bk2204** [comment]
Hey,

NTLM was indeed removed and it won't work.  We removed it because it was broken and nobody volunteered to fix it.  The likely reason you're seeing this is because there's Negotiate authentication in `WWW-Authenticate`, and that can cover Kerberos as well, which we do support (although it is untested on Windows, but it should work).

You'll have to pick a different type of authentication instead of NTLM, such as Kerberos or Basic.  Since NTLM is also completely insecure, you'd probably want to do that anyway.

**Comment by BMBurstein** [comment]
@bk2204 Thanks for the response. The server indeed responds with four `WWW-Authenticate` options: `Bearer`, `Basic`, `Negotiate` and `NTLM`. However, it is the client that choose to use NTLM and not one of the other options. If NTLM was removed, shouldn't it *not* choose that one?

Or maybe my understanding is wrong? I am no expert on this. I am seeing in Wireshark an NTLMSSP_NEGOTIATE from the client and assumed it had chosen NTLM. Maybe that is actually the `Negotiate` option?

**Comment by bk2204** [comment]
I'm almost certain the client doesn't choose to use `NTLM` here (since there's no longer any code to do so).  It probably chooses to use `Negotiate`, and the response it gets from the server is an NTLM-style `Negotiate` instead of a Kerberos-style `Negotiate`, which it can't handle.  I'm pretty sure that's what NTLMSSP_NEGOTIATE means, but you can verify by looking at the challenge the server provides with `Negotiate` and seeing if it starts with the Base64 encoding of `NTLM`.

It is known that we don't currently fall back to `Basic` in any case when `Negotiate` fails, and we'll of course happily accept a patch to do so.
