### ISSUE TITLE
How can I get "git diff --binary --patch commi1 commit2" to include fully binary patches for LFS binary files 

### ISSUE THREAD

**Issue by sarvi** [git-lfs/git-lfs#4784]
**Describe the issue**
I would like to be able to do "git diff --binary -patch commit1 commit2" in repository repoA/ that have
`*.tgz filter=lfs diff=lfs merge=lfs -text`
that is store in a private lfs/artifactory server
And I want to be able to take this diff that includes *.tgz binaries and apply it to another 3rd party repository
that may not have *.tgz marked for LFS or possibly is pointing to a different LFS/aritifactory server.

The point being it is not sufficient if the "git diff" contained in changes to OID values.
I would rather the the patch contains the ascii encoded whole binary so that it can be patched/applied into any destination repo, irrespective of wether the files are marked for LFS  or not in the destination repository.

What is the best way to generated a diff/patch that contains the whole encoded binary, as if the file wasnt marked for LFS
And how do I apply it to target repo that may or may not have those files marked for LFS or not.

**Comment by bk2204** [comment]
Hey,

Sorry for the delay in getting back to you.  I'm not aware of any way to get Git to produce a binary patch for an LFS file.  You can get Git to produce a normal text-based diff, even if the file is binary, by running `git config diff.lfs.textconv cat`.

Unfortunately, this doesn't typically apply to a file with an LFS repository, since Git applies it to the index, but you can then apply the patch with a standard `patch -p1` invocation, or you can simply set `GIT_DIR=` in the environment to get Git to apply it to the working tree.
