### ISSUE TITLE
Have to use git lfs pull everytime

### ISSUE THREAD

**Issue by Lewisracing** [git-lfs/git-lfs#4785]
I'm setting up my new machine.

I installed LFS but turns out I have to use git lfs pull everytime I check out a branch.
On my old machine I don't have to do this.
What am I missing??
Last time I had this issue on my old machine, I ran a kind of reinstall reinitialize command and it fixed (might not be accurate I can't rememeber clearly) 

Basically how to make lfs pull default?

**Comment by bk2204** [comment]
Hey,

Usually this means you haven't run `git lfs install` on your local machine.  If you run that, it should set up your configuration such that when a repository is cloned, the hooks and other necessary functionality is set up for it.

Note that since that command modifies `~/.gitconfig`, if you keep your dotfiles in a separate repo and sync them across machines, then you'll probably want to just make the appropriate changes to your `~/.gitconfig` version in your dotfiles so you don't have to do this on every new machine.
