### ISSUE TITLE
[Security] Workflow release.yml is using vulnerable action actions/checkout

### ISSUE THREAD

**Issue by akulpillai** [git-lfs/git-lfs#4789]
The workflow release.yml is referencing action actions/checkout using references v1. However this reference is missing the commit [a6747255bd19d7a757dbdda8c654a9f84db19839](https://github.com/actions/checkout/commits/a6747255bd19d7a757dbdda8c654a9f84db19839) which may contain fix to the some vulnerability. 
The vulnerability fix that is missing by actions version could be related to: 
(1) CVE fix 
(2) upgrade of vulnerable dependency 
(3) fix to secret leak and others. 
Please consider to update the reference to the action.

**Comment by bk2204** [comment]
Hey,

We can look into an upgrade, but from looking at the commit, it looks like this is simply exposing some data on the command line, which as far as I can tell should not be a problem since Actions VMs are single tenant.  Can you explain some more about what exactly the vulnerability is and how you think it affects us?

**Comment by bk2204** [comment]
We will be needing to revert this change absent any forthcoming information about the nature of the vulnerability and its impact.  v2 breaks annotated tags and `git describe`.
