### ISSUE TITLE
How to download a single file from git-lfs using Python?

### ISSUE THREAD

**Issue by shaked571** [git-lfs/git-lfs#4804]
Hi,
I am tracking some `.csv` and `.json` file using LFS in my repo, and I wish to download a single file.

Because I'm running on a cluster, which I need to initial every time, I wish that the download would happen within the code. 

Im getting back
``` 
version https://git-lfs.github.com/spec/v1
oid sha256:376e3b8d27dfa7ca45c68d28466a2327832a08a92ef252502588937eeb78c8943
size  175233
```
which from what I understood is a pointer to the data.
my lfs env looks like:
``` 
git-lfs/3.0.2 (GitHub; darwin amd64; go 1.17.2)
git version 2.30.1 (Apple Git-130)

Endpoint=https://gecgithub01.walmart.com/usr/datasets.git/info/lfs (auth=none)
  SSH=git@gecgithub01.walmart.com:usr/datasets.git
LocalWorkingDir=/Users/usr/Dev/datasets
LocalGitDir=/Users/s0g0a87/Dev/datasets/.git
LocalGitStorageDir=/Users/usr/Dev/datasets/.git
LocalMediaDir=/Users/usr/Dev/datasets/.git/lfs/objects
LocalReferenceDirs=
TempDir=/Users/s0g0a87/Dev/datasets/.git/lfs/tmp
ConcurrentTransfers=8
TusTransfers=false
BasicTransfersOnly=false
SkipDownloadErrors=false
FetchRecentAlways=false
FetchRecentRefsDays=7
FetchRecentCommitsDays=0
FetchRecentRefsIncludeRemotes=true
PruneOffsetDays=3
PruneVerifyRemoteAlways=false
PruneRemoteName=origin
LfsStorageDir=/Users/usr/Dev/datasets/.git/lfs
AccessDownload=none
AccessUpload=none
DownloadTransfers=basic,lfs-standalone-file,ssh
UploadTransfers=basic,lfs-standalone-file,ssh
GIT_EXEC_PATH=/Library/Developer/CommandLineTools/usr/libexec/git-core
git config filter.lfs.process = "git-lfs filter-process"
git config filter.lfs.smudge = "git-lfs smudge -- %f"
git config filter.lfs.clean = "git-lfs clean -- %f"

```
Where should I go from now?(tried to work also with python's packages such as `giftless_client` but I didnt manage to make the download method to work)

**Comment by chrisd8088** [comment]
Hey, I'm sorry you're having trouble.  If you're writing in Python, I'm not sure we'll be of much help here, since this project is for the Git LFS client itself.

It looked to me as though the `giftless_client` [project](https://github.com/datopian/giftless-client) had some notes on how to make [requests](https://github.com/datopian/giftless-client#sending-an-lfs-batch-api-request) to your LFS server's batch API endpoint, and how to [download](https://github.com/datopian/giftless-client#downloading-a-file-from-lfs-storage) files.  If you have questions about how to use that package, I would open an issue [there](https://github.com/datopian/giftless-client/issues) instead.

Another Python package appears to be the `python-git-lfs` [project](https://github.com/andrewshadura/python-git-lfs).

If you need info on how the batch API works, take a look at the API [specification](https://github.com/git-lfs/git-lfs/blob/046847c7faf9acc1d0bd6083385f713a9cd20cac/docs/api/batch.md).  In brief, the client makes a JSON request to the LFS batch API for certain pointer IDs (as found in the LFS pointer files) and gets back JSON telling the client where to download the actual file data.

As for the Git LFS client (i.e., this project), one can use `--include` with `git lfs pull` to retrieve specific file paths.  For instance, if I cloned a repo with `GIT_LFS_SKIP_SMUDGE=1` so that all the Git LFS objects were left as pointer files in the working tree, and I could then fetch and checkout a specific Git LFS file like this; the `git lfs ls-files` commands will show files that are pointers with `-` and those which have been "smudged" into full files with `*`:
```
$ GIT_LFS_SKIP_SMUDGE=1 git clone https://example.com/path/to/repo
$ cd repo
$ git lfs ls-files
181210f8f9 - 123.bin
052c91fb20 - 234.bin
$ cat 123.bin
version https://git-lfs.github.com/spec/v1
oid sha256:181210f8f9c779c26da1d9b2075bde0127302ee0e3fca38c9a83f5b1dd8e5d3b
size 4

$ git lfs pull --include=123.bin
$ git lfs ls-files
181210f8f9 * 123.bin
052c91fb20 - 234.bin
$ cat 123.bin
123
```

I hope that helps, and by all means read through the manual [pages](https://github.com/git-lfs/git-lfs/tree/046847c7faf9acc1d0bd6083385f713a9cd20cac/docs/man), such as the one for `git lfs pull`.
