### ISSUE TITLE
Provide a merge driver for LFS tracked text files

### ISSUE THREAD

**Issue by dr-dime** [git-lfs/git-lfs#4820]
We have lots of large text files stored in LFS and want to merge them in a more natural way. 

Currently, we have a custom merge driver to do this, and the workflow is very straightforward:

- `git lfs smudge ${files}`
- `git merge-file ${files}`
- `git lfs clean ${merged_file}`

For all the LFS manged text files, we use `diff=lfs-text merge=lfs-text` in .gitattributes. We haven't
found any significant issue with this approach so far. IMHO, this should be part of the lfs release,
and make those configs part of the `git lfs install`.

**Comment by bk2204** [comment]
Hey,

I don't know of any reason we couldn't offer a merge driver in this case.  Because of the way Git's merges work, this wouldn't permit renames to work, which might be inconvenient for some folks.

However, I don't think we can turn it on by default, since some LFS files are binary and it's not possible to determine easily which those are.  Having said that, I definitely think this is something we can consider for the future and I'm marking it as an enhancement.

**Comment by dr-dime** [comment]
Ah, that's right. However rename detection for git is always inaccurate, so this is no big deal IMO.

Actually, we can turn it on by default, as long as we give this diff/merge filter a new name. For our case is `lfs-text`. And our global gitconfig looks like following:

```ini
[diff "lfs-text"]
	textconv = cat
[merge "lfs-text"]
	driver = merge_lfs_text_file %O %A %B %L %P
```

**Comment by dr-dime** [comment]
I'd love to send a PR for this, but I need to go through the corp opensource process first. May I ask where is the CLA for git-lfs? It's not mentioned in CONTRIBUTING.md.

**Comment by bk2204** [comment]
We don't have a CLA.  We expect that when you submit code, you do it under the terms of the license as specified in the LICENSE file.
