### ISSUE TITLE
Authentication problems with DevOps Server and LFS Client >= v3.0

### ISSUE THREAD

**Issue by ssrmm** [git-lfs/git-lfs#4853]
**Describe the issue**
We are having some trouble getting the 3.x versions of LFS to work with on-premise Azure DevOps Server instances.
This is the case for at least three server instances that were setup/are adminstrated independently by different people.
As far as I can tell the problem is related to the removal of NTLM authentication.

When I'm fetching LFS files after creating a fresh clone (`git init`, `git remote add` and `git fetch`) LFS seemingly gets stuck for a while and eventually spits out several identical error lines:

```
$ git lfs fetch origin origin/master
fetch: Fetching reference refs/remotes/origin/master
Downloading LFS objects:   0% (0/3605), 0 B | 0 B/
batch response: Post "https://<remote-url>/info/lfs/objects/batch": lookup <ip4-address>: dnsquery: DNS Name Does Not Exist.
  [36 identical lines trunctated]
batch response: Post "https://<remote-url>/info/lfs/objects/batch": lookup <ip4-address>: dnsquery: DNS Name Does Not Exist.
error: failed to fetch some objects from 'https://<remote-url>/info/lfs'
```

When I push a LFS tracked file to the server I get the same error as well
```
Uploading LFS objects:   0% (0/1), 0 B | 0 B/s, done.
batch response: Post "https://<remote-url>/info/lfs/objects/batch": lookup <ip4-address>: dnsquery: DNS Name Does Not Exist.
error: failed to push some refs to 'https://<remote-url>'
```

I have also tried using the binary from the latest CI Build because it seemd like #4815 would be relevant to the problem.
Using that build I now get endless authentication prompts instead of the error messages, but the build still does not work.
Older 2.x versions work correctly.

The DevOps Server currently sends the following authentication related headers:
```
www-authenticate: Bearer
www-authenticate: Basic realm="https://<server-domain>/tfs"
www-authenticate: Negotiate
www-authenticate: NTLM
lfs-authenticate: NTLM
```

The general advice that I have seen in related issues is to reconfigure the server to allow Kerberos or Basic authentication.
Unfortunately it seems to be non-trivial to find a setting for that in on-premise Azure DevOps Servers.

Has anyone been able to get LFS 3.x to work with on-premise Azure DevOps Server?
Can you provide some guidance on  where to find/how to change that setting?

**System environment**
Various Windows 10 clients
Azure DevOps Server 2020 Update 1.1 (latest release)

**Output of `git lfs env`**
<details>
<summary>Expand</summary>

```
$ git lfs env
git-lfs/3.0.2 (GitHub; windows amd64; go 1.17.2)
git version 2.35.1.windows.2

Endpoint=https://<remote-url>/info/lfs (auth=none)
LocalWorkingDir=<path-to-repository>
LocalGitDir=<path-to-repository>\.git
LocalGitStorageDir=<path-to-repository>\.git
LocalMediaDir=<path-to-repository>\.git\lfs\objects
LocalReferenceDirs=
TempDir=<path-to-repository>\.git\lfs\tmp
ConcurrentTransfers=8
TusTransfers=false
BasicTransfersOnly=false
SkipDownloadErrors=false
FetchRecentAlways=false
FetchRecentRefsDays=7
FetchRecentCommitsDays=0
FetchRecentRefsIncludeRemotes=true
PruneOffsetDays=3
PruneVerifyRemoteAlways=false
PruneRemoteName=origin
LfsStorageDir=<path-to-repository>\.git\lfs
AccessDownload=none
AccessUpload=none
DownloadTransfers=basic,lfs-standalone-file,ssh
UploadTransfers=basic,lfs-standalone-file,ssh
GIT_EXEC_PATH=C:/Program Files/Git/mingw64/libexec/git-core
git config filter.lfs.process = "git-lfs filter-process"
git config filter.lfs.smudge = "git-lfs smudge -- %f"
git config filter.lfs.clean = "git-lfs clean -- %f"
```
</details>

**Comment by damccorm** [comment]
I don't work on Azure DevOps right now and don't have a great way to get insight into this particular problem. I'd recommend filing a ticket here - https://developercommunity.visualstudio.com/report?space=21&entry=problem for help.

> If Azure DevOps folks would like to be on our implementers group, we're happy to have them, and they'll get pinged about new releases and can work with us to address those issues, but so far they haven't asked, and we don't have any contact with them, so it's hard for us to speak to how best to work with that platform.

Also tagging @mmrazik in case this is something he (or someone else on the team) would be interested in doing.

**Comment by ssrmm** [comment]
>  then you should be able to use a username and PAT, just like for Git

Based on your suggestion I've tried to play around with a PAT,  but couldn't get it to work, even just with Git itself. Though that may be a server configuration issue, I'm not sure.

> I'd recommend filing a ticket here - https://developercommunity.visualstudio.com/report?space=21&entry=problem for help.

While browsing there, I've found the following existing ticket: https://developercommunity.visualstudio.com/t/Support-for-Kerberos-for-Git-LFS/1214853
People there seem to indicate that NTLM is the only authentication method supported by on-prem DevOps servers at the moment.  Which would mean it is impossible to get LFS 3.0 to work with it.

That ticket is in a weird state, being new for 1.5 years despite the last status change setting it to closed. And it didn't really get a proper response either. I've tried opening a new ticket in an attempt to get some more information. Unfortunately something seems to be busted there right now. I'm seeing a whole bunch of errors in the browser console, some of which are HTTP 500 with "Service temporarily unavailable" in the payload. I guess I'll try again next week.

**Comment by janniksam** [comment]
One of my coworkers ran into the exact same issue today, when pushing a LFS-tracked file.

We had issues with versions 2.8.0 a couple of times now, and he seemed to have installed a different version than we recommended. He will try to downgrade now.

Nethertheless it would be nice to be able to update sooner or later ;-)

**Comment by jdx-john** [comment]
I had been advised that 3.1 was going to add a fall-back to standard authentication in the NTLM case rather than simply failing... but it seems the new 3.1.1 contains only one trivial bugfix. Is that correct? It seemed a bit odd to jump from 3.0.x to 3.1.x for one bug.

#4815 is the ticket I was thinking off, already mentioned above and I see it's merged... but is it released? How do I tell if it's in a particular release without cloning the repo locally and digging around?

Downgrading to an older LFS version seems to work but is not great. We ran into issues testing LFS on DevOps because it worked for one of us and not the rest, purely because they installed LFS just a few days earlier than us, and we got 3.0 rather than their 2.x!

**Comment by KalleOlaviNiemitalo** [comment]
> How do I tell if it's in a particular release without cloning the repo locally and digging around?

At <https://github.com/git-lfs/git-lfs/pull/4815>, if you click the commit ID in ["bk2204 merged commit 4a3701b into git-lfs:main 25 days ago"](https://github.com/git-lfs/git-lfs/pull/4815#event-5932362766), it leads to <https://github.com/git-lfs/git-lfs/commit/4a3701b555a5f2ac0307b5e2181df7fa3d4d2f45>, which shows that the commit is included in the tags "v3.1.1 v3.1.0".

**Comment by ssrmm** [comment]
> I've tried opening a new ticket in an attempt to get some more information. Unfortunately something seems to be busted there right now.

I've been able to open a ticket  by now. Unfortunately, I haven't gotten any useful additional information so far: https://developercommunity.visualstudio.com/t/authentication-problems-with-git-lfs-v30/1659021

I'll post an update here if anything new comes of it.

If you are affected by the problem, feel free to upvote the ticket so we can raise its priority for Microsoft.

> I had been advised that 3.1 was going to add a fall-back to standard authentication in the NTLM case rather than simply failing... 

@jdx-john  have you or anyone else been able to get the new release to work with your DevOps servers? I have tried it with binaries from a CI build when opening this ticket, but couldn't get things to work with it either.

**Comment by jdx-john** [comment]
@ssrmm not tried yet - only noticed 3.1 was out today so we haven't had a chance to test.

**Comment by jdx-john** [comment]
> > We don't test with Azure DevOps Server instances since none of the core team members have access to them.
> 
> [MS Azure DevOps Server Express](https://docs.microsoft.com/en-us/azure/devops/server/download/azuredevopsserver?view=azure-devops) is free for small teams.

I have a feeling they stated before that none of the developers actually work in Windows _at all_... though I can't find where so may be wrong.

It is frustrating that MS actively recommend LFS for large files, and support it in Azure, but haven't seemingly noticed it's not actually usable since 2.x. Some might say BAU for MS ;)

**Comment by bk2204** [comment]
> > > We don't test with Azure DevOps Server instances since none of the core team members have access to them.
> > 
> > 
> > [MS Azure DevOps Server Express](https://docs.microsoft.com/en-us/azure/devops/server/download/azuredevopsserver?view=azure-devops) is free for small teams.
> 
> I have a feeling they stated before that none of the developers actually work in Windows _at all_... though I can't find where so may be wrong.

I personally have a Windows 10 VM specifically for testing Git LFS-related things.  However, it runs on my laptop and doesn't have a lot of resources, so isn't going to be suitable for running any sort of hosting platform, such as Azure DevOps Server Express.  Other core team members may also have a similar VM setup.  Otherwise, we don't run Windows on a day-to-day basis at all: we're either Mac or Linux users.  None of our internal systems run Windows, either, so running a test VM or container somewhere there isn't really an option.

Also, it sounds more and more like this needs a fix (or at least documentation) on the Microsoft side.  I know somebody who happens to know some people at Azure DevOps, and I've asked them to chime in here and see if they can help, since we'd love to see this working again, but we're kind of stuck until they do.

**Comment by jdx-john** [comment]
I don't suppose MS would like to donate an Azure cloud node or something for this, if nothing else?! 
Is there a big problem with falling back to the last 2.x version to get NTLM support - or realistically would this be quite reasonable even for a longer period?

Is it a deliberate decision that you have no Windows people or is it just the way things turned out with people who were interested all coming from a core Git background which is heavily Linux-oriented? But then I have no idea if you are a team of 20 full-time devs or 2 people doing at at the weekend!

I'll see if 3.1 works on our setup today, we have a local Azure Devops server which causes its own special cases (no HTTPS) so no idea if it is likely to work.

**Comment by jdx-john** [comment]
@bk2204 interesting - I found the team details but had no idea of the GitHub link. I did think a lot of Macs seemed a bit unusual given the context. 

Anyway back on topic, I tested 3.1.1 today and as far as I can see it allows me to push using username/PAT - a credential popup is raised every-time both from git lfs command-line or my visual Git client (Kraken). I'm under the impression I can cache that.

Again, this is an on-premises non-HTTPS Azure Devops server installation. It seems to work for us, I've no way to test on a hosted collection.

**Comment by duckfist** [comment]
My team is also experiencing this issue, on Git-LFS 3.1.2, with Azure DevOps Server 2020 (on premises). On pull, it hangs indefinitely on any LFS files. If you install LFS with --skip-smudge, the pull works without downloading the large files, then a separate "git lfs pull" will cite authentication required/error.

Our workaround will be to roll everyone back to 2.13.3 for the time being. You'd think MS would be interested in helping fix this. Thank you for your hard work.

**Comment by jdx-john** [comment]
An update is that there are annoying authentication issues I am not sure who to blame for. As I said, the first time I ran `git lfs`  I was prompted for credentials, and was able to use a my Azure Devops username/PAT (but not password):

![image](https://user-images.githubusercontent.com/1654627/155513456-44bd4efa-e644-428d-a0b3-31920f0fe2db.png)

However the next time I used git (not LFS) I got an authentication error (redacted):
>fatal: Authentication failed for 'http://XXXX:8080/tfs/XXXX/_git/XXXX/'

I ran the same command a 2nd time and got the same authentication prompt... but this one only accepts my username and _password_. After that, git continued working as normal but the next time I wanted to do a LFS operation, it failed:

> \>git lfs locks
Error while retrieving locks: Authorization error: http://XXXX:8080/tfs/XXXX/_git/gitlfstest.git/info/lfs/locks?refspec=refs%2Fheads%2Fmaster
Check that you have proper access to the repository

Again, running the same command a 2nd time now brings up the authentication prompt that wants my PAT.

It seems to be a cycle that whenever I provide authentication for git/LFS it loses sved authentication for the other, and that I always have to run the command twice to get an authentication prompt.

I am not sure if the fact it's the same root URL for Git and GitLFS or something else is going on. I didn't get round to trying a credential manager so I'll see if that helps otherwise it's going to be pretty annoying especially as the authentication prompt is identical in both cases so you don't know which 'password' it wants.

I figured https://github.com/GitCredentialManager/git-credential-manager is the obvious choice, will give that a whirl.

**Comment by bk2204** [comment]
Hey,

It likely is that the same root URL is being used here and Git is still using NTLM, while Git LFS is using Basic.  Unfortunately, there's no way to control the authentication type used by Git.

What you probably need to do is set `credential.http://mydomain:8080/.usehttppath` to true (replacing the URL portion with your URL), which will mean that the entire URL, including the path, will get used.  That will allow Git and Git LFS to store their credentials independently.  However, depending on how your server is configured, that may result in additional prompts: if it uses some sort of signed token or URL in the batch response, then it shouldn't, but otherwise, you may get prompted for each access.

**Comment by dennisl68-castra** [comment]
> I don't suppose MS would like to donate an Azure cloud node or something for this, if nothing else?! 
> 

MS Azure Services is free for open projects and MS Azure DevOps Server is free for up to 10 users if installing the Express version...

**Comment by jessehouwing** [comment]
I notified a number of folks inside the Azure DevOps team.

**Comment by jdx-john** [comment]
Well I set that up I think, but not I don't get asked for credentials at all for LFS commands - it just pauses a moment and fails every time.

```
> C:\gitlfstest>git config --list
> diff.astextplain.textconv=astextplain
> http.sslbackend=openssl
> http.sslcainfo=C:/Program Files/Git/mingw64/ssl/certs/ca-bundle.crt
> core.autocrlf=true
> core.fscache=true
> core.symlinks=false
> credential.helper=manager-core
> pull.rebase=false
> credential.https://dev.azure.com.usehttppath=true
> init.defaultbranch=master
> user.email=<REDACTED>
> user.name=<REDACTED>
> core.longpaths=true
> filter.lfs.process=git-lfs filter-process
> filter.lfs.required=true
> filter.lfs.clean=git-lfs clean -- %f
> filter.lfs.smudge=git-lfs smudge -- %f
> credential.httpusepath=true
> core.bare=false
> core.repositoryformatversion=0
> core.filemode=false
> core.symlinks=false
> core.ignorecase=true
> core.logallrefupdates=true
> remote.origin.url=http://<REDACTED>:8080/tfs/<REDACTED>/_git/gitlfstest
> remote.origin.fetch=+refs/heads/*:refs/remotes/origin/*
> branch.master.remote=origin
> branch.master.merge=refs/heads/master
> lfs.repositoryformatversion=0
> lfs.http://<REDACTED>8080/tfs/<REDACTED>/_git/gitlfstest.git/info/lfs.access=basic
> lfs.http://<REDACTED>:8080/tfs/<REDACTED>/_git/gitlfstest/info/lfs/objects/.access=basic
> credential.http://<REDACTED>:8080.helper=manager-core
> credential.http:/<REDACTED>:8080.usehttppath=true
> 
> C:\gitlfstest>git lfs locks
> Error while retrieving locks: Authorization error: http://<REDACTED>:8080/tfs/<REDACTED>/_git/gitlfstest.git/info/lfs/locks?refspec=refs%2Fheads%2Fmaster
> Check that you have proper access to the repository
> 
```

So this change did something but I do not know what! Perhaps I can/should purge all credentials though I'd have to find where they are stored.

**Comment by davehecker66** [comment]
I'm getting this same error. I have Visual Studio 2019 installed with Git-2.35.1.2-64-bit.exe WITH the "GIT LFS" option checked. In Git Bash I'm making a new clone of a repository: **git clone https://<remote-url> c:\test**

The clone succeeds, but the initial checkout fails with: batch response: Post "https://<remote-url>/info/lfs/objects/batch": **lookup <ip4-address>: dnsquery: DNS Name Does Not Exist.** (the variation is the process aborts so I see this error once on the first file).

At this point I can do **git fetch** and **git pull** without error. Doing **git lfs fetch** reports the "lookup <ip4-address>: dnsquery" error.

The clone is successful, but somewhere GIT LFS appears to doing a DNS lookup _on the ip4-address_ (which rightly fails; it is not a domain name).

NOTE: If I manually download the full files and put them where they belong, then **git lfs fetch** and **git lfs pull** don't complain. I am also able to modify the files and commit/push them without error, and others _who already have an older copy of the full file_ are able to pull the changed file without error. **It seems that the ONLY failure scenario is when the local file does not exist, and GIT LFS is trying to do the initial retrieval of the full file content.**

Thanks,
--Dave

**Comment by bk2204** [comment]
@davehecker66 The issue you're reporting is almost certainly a different issue.  If you were seeing the same issue, you'd be seeing an authentication error.  Could you please open a new issue, filling out the issue template, and including the output of attempting to run the command with `GIT_TRACE=1 GIT_TRANSFER_TRACE=1 GIT_CURL_VERBOSE=1`?

**Comment by davehecker66** [comment]
**I will open a separate issue as requested.** However, here's my reasoning for thinking it's the same underlying issue:

Although this issue is titled "Authentication problems" and provides lots of authentication-related details, I didn't see any error message mentioning an authentication issue. Maybe I missed it, but the first error I see being reported matches the one I'm seeing:
`batch response: Post "https://<remote-url>/info/lfs/objects/batch": lookup <ip4-address>: dnsquery: DNS Name Does Not Exist.`
That indicates a failure _before_ any request was actually executed (_before_ there was even a chance of an authentication error occurring).

When I first had a problem, I was cloning via Visual Studio 2019. My initial assumption was an authentication problem because after the "dnslookup of an IP address" error was shown in the console, I was endlessly prompted to re-enter my credentials. (It's like VS got "some error" returned, and blindly assumed my stored credentials _which worked for the clone_ were now somehow incorrect.)

So I stopped testing from Visual Studio and started directly using GIT BASH, which confirmed that **git fetch** and **git pull** were fine, but **git lfs fetch** and **git lfs pull** were aborting on the first LFS file with the "dnslookup of an IP address" error (which did _not_ invalidate my stored credentials).

Thanks,
--Dave

**Comment by ssrmm** [comment]
I spent some time to play around with this again and now found a solution which works on our DevOps Server:

1. Generate a new PAT in the Azure DevOps Web UI (Profile-Picture -> Security). Use the settings shown in the screenshot below and adjust organization and expiration date appropriately.
2. Open a Git Bash.
3. Run the command `pat=<your-pat>`. Replace `<your-pat>` with the PAT from DevOps.
4. Run the command `git config --global http."https://<server-url>/".extraHeader "Authorization: Basic $(echo -n :$pat | base64)"`. Replace `<server-url>` with the URL of your DevOps server (e.g. `https://devops.example.com/` or `https://devops.example.com:8081/`).
5. According to the documentation, Azure DevOps is supposed to send reminder mails for tokens that are about to expire. However, at least for me that didn't happen. In doubt set set yourself a reminder in your calendar app for when the token expires so you can know to renew it.

![image](https://user-images.githubusercontent.com/22149188/159941958-ca03e29d-d24a-4334-9401-5c5c51092d9e.png)

What I also tried but couldn't get to work is using the credential manager to store the PAT, When doing that, LFS started working, but "normal" Git stopped working. In the trace output it looked like Git was trying to do NTLM authentication with the PAT, which seems to not be supported.

**Comment by ssrmm** [comment]
> I'll let other folks try out on the cloud version of Azure DevOps and, assuming that works, we can close this.

@bk2204 As far as I can tell, the cloud version has never been affected by this problem. That was one of the things I tried when trying to narrow down the problem.

**Comment by davehecker66** [comment]
Given @ssrmm found a way to eliminate the reported error with an authentication-related change, my issue does seem different. I haven't opened the separate issue yet, but still planning to (I need to repeat my test with the requested settings).

**Comment by jdx-john** [comment]
> What I also tried but couldn't get to work is using the credential manager to store the PAT, When doing that, LFS started working, but "normal" Git stopped working. In the trace output it looked like Git was trying to do NTLM authentication with the PAT, which seems to not be supported.

@ssrmm would you go a bit deeper on that - are you saying it works but you must continually re-provide authentication? How does your workaround fit in to day-to-day development using git/lfs files - is it a pain or work smoothly?

**Comment by bk2204** [comment]
`http.extraHeader` for this purpose is insecure because it puts credentials in plaintext in the Git config.  We've basically told lots of people specifically not to do that.

I plan to rework some of the authentication code in Git to allow a credential helper to specify a particular authentication scheme, which should fix this problem by allowing the credential helper to force Basic in all situations.  I just haven't gotten there yet.

**Comment by ssrmm** [comment]
@jdx-john Yes that sounds like we both have the same behavior with approach 2. I never tried the workaround that was suggested, I think I just missed that reply entirely.

**Comment by ssrmm** [comment]
> `http.extraHeader` for this purpose is insecure because it puts credentials in plaintext in the Git config. We've basically told lots of people specifically not to do that.
Yeah, it is not ideal. In this case it is "just" a PAT that has only access to Git repos it is less bad. In our case all affected machines have disk encryption as well.

> I plan to rework some of the authentication code in Git to allow a credential helper to specify a particular authentication scheme, which should fix this problem by allowing the credential helper to force Basic in all situations. I just haven't gotten there yet.
That sounds like a good feature :+1:

**Comment by danielpullwitt** [comment]
We have the same behavior with our self hosted Azure DevOps instance using git lfs 3.0.2

The only way we found to get git LFS working reliably was to use Azure DevOps personal access tokens (PAT), we found a way to get this working without the security issues of adding the plain text token via `http.extraHeader` to git config.

- When using the credentials manager, we need to leave the user name empty and only add PAT as password; user name breaks authentication in various use cases
- Downgrade connection to http 1.1, http 2 causes errors (`git config --global http.version HTTP/1.1`).

**Comment by ssrmm** [comment]
For me at least PAT in credential manager doesn't work, that's approach two I described above. As far as I could tell, the username doesn't matter when using PAT, because it seems to be ignored.

**Comment by vtbassmatt** [comment]
The Azure DevOps team recommends moving from NTLM to Kerberos with this new [blog post](https://devblogs.microsoft.com/devops/reconfigure-azure-devops-server-to-use-kerberos-instead-of-ntlm/).

**Comment by bk2204** [comment]
Okay, since the Azure DevOps team now has official documentation about how to handle this, I'm closing this issue.  If you continue to have problems, please contact the Azure DevOps folks or your server administrator to address those issues further.

**Comment by Chefkoch81** [comment]
Unfortunately the Microsoft blogpost was deleted and for me, even with git-fls 3.1, I can only use "http.extraHeader".

In Azure DevOps server application settings our Authentication is set to "Negotiate (Kerberos)". That sounds correct to me.

My main question is, has anybody got it to work without setting "http.extraHeader"?

**Comment by ssrmm** [comment]
Wow, Microsoft never ceases to surprise! It looks like somebody was clever enough to save a [backup on the Wayback Machine](https://web.archive.org/web/20220505055116/https://devblogs.microsoft.com/devops/reconfigure-azure-devops-server-to-use-kerberos-instead-of-ntlm/).

Though I don't know if the method from the blog post works or not, since we haven't tried it yet. The fact that the post was deleted does not bode well.

**Comment by jdx-john** [comment]
We had tried and run into issues, thanks for reporting the post was missing I hadn't noticed.

**Comment by vtbassmatt** [comment]
I'm looking into the disappearing blog post with Microsoft.

**Comment by vtbassmatt** [comment]
> I'm looking into the disappearing blog post with Microsoft.

My contact at Microsoft let me know that issues were discovered with the post as-written for the latest versions of Azure DevOps Server. They've taken the post private until they can sort things out. I've asked for them to expedite getting it reposted. Sorry for the inconvenience.

**Comment by Chefkoch81** [comment]
> > I'm looking into the disappearing blog post with Microsoft.
> 
> My contact at Microsoft let me know that issues were discovered with the post as-written for the latest versions of Azure DevOps Server. They've taken the post private until they can sort things out. I've asked for them to expedite getting it reposted. Sorry for the inconvenience.

The post is here again, but I still cannot get it to work. Even worse there is now a security issue for git-bash 2.30.2 (which is the last one containing git-lfs 2.x), so I need to find another solution.

**Comment by Chefkoch81** [comment]
> The post is here again, but I still cannot get it to work. Even worse there is now a security issue for git-bash 2.30.2 (which is the last one containing git-lfs 2.x), so I need to find another solution.

Now I finally changed on of my production machines, which are part of the same domain, and there git-lfs works with git-lfs 3.2.
For the most time I tested in VMs in the past, which were not part of the domain and if I am correct, on such machines Kerberos cannot work.
So I still have the problem on how to make it work on those machines.

**Comment by janniksam** [comment]
> > The post is here again, but I still cannot get it to work. Even worse there is now a security issue for git-bash 2.30.2 (which is the last one containing git-lfs 2.x), so I need to find another solution.
> 
> Now I finally changed on of my production machines, which are part of the same domain, and there git-lfs works with git-lfs 3.2. For the most time I tested in VMs in the past, which were not part of the domain and if I am correct, on such machines Kerberos cannot work. So I still have the problem on how to make it work on those machines.

Our dev domains are in a dev domain, while our DevOps Server is hosted in the prod domain .

**Comment by bk2204** [comment]
If you have your realm in DNS, it's completely possible to use an alternate Kerberos realm at least on Unix, simply by invoking `kinit` with the absolute principal to get a TGT: `kinit bk2204@PROD.EXAMPLE.COM`.  Apparently Windows also allows you to do this with `klist get PRINCIPAL` as well, although I don't use Windows myself so can't verify.

**Comment by wefwefweqd23r32fdsfd123** [comment]
Just stumbled on this problem in 2025.   It seems Azure Devops and GIT LFS really don't play nicely anymore, and each team blame the other.  It's clear to me however, removal of NTLM, when everything else (GIT, Azure Devops) were still using it, was a really poor decision that has lead directory these problems.
