### ISSUE TITLE
error: cannot spawn .git/hooks/pre-push: No such file or directory error: waitpid for (NULL) failed: No child processes error: failed to push some refs to 'github.com:shiyouroc/MyPorject.git'

### ISSUE THREAD

**Issue by shiyouroc** [git-lfs/git-lfs#4885]
Hello everyone, my English is not good, the content is translated by the translator.
I want to upload a very large file and it pops up
error: cannot spawn .git/hooks/pre-push: No such file or directory
error: waitpid for (NULL) failed: No child processes
error: failed to push some refs to 'github.com:shiyouroc/MyPorject.git'
How should this be done?

**Comment by bk2204** [comment]
Hey,

Could you provide the output of `git lfs env` so we can see what system you're working on?  It sounds like this is an issue with Git in some way.

Also, are you running any sort of non-default firewall or antivirus (that is, if you're using Windows, using something other than Windows Firewall or Windows Defender)?  Those are common causes of problems and could be the issue here.

If you have trouble understanding, please tell me, and I'll try to use different words.  I can also help in Spanish or French if one of those is a language you speak.

**Comment by bk2204** [comment]
Hey,

Since we haven't heard back from you, I'm going to close this.  Please feel free to provide the requested information and we can reopen.
