### ISSUE TITLE
Access is denied when trying to git lfs push

### ISSUE THREAD

**Issue by csdjk** [git-lfs/git-lfs#4886]
$ git push
Uploading LFS objects:  57% (4/7), 93 MB | 881 KB/s, done.
LFS: Put "https://github-cloud.s3.amazonaws.com/alambic/media/386560498/76/00/76003c9e129468aee16bf2afad943960a950a7a539ad400902d1d8fec6db78deff?actor_id=335197487&key_id=0&repo_id=213653868": write tcp 192.168.xxx->52.216.xxx: wsasend: Access is denied.
LFS: Put "https://github-cloud.s3.amazonaws.com/alambic/media/386560498/36/ac/36acc325eaf7a59170236991f4f65f0692e77c037c8fb1969d9b906598d26c8466?actor_id=33519787&key_id=0&repo_id=213653868": write tcp 192.168.1.xxx->52.216.1.xxx: wsasend: Access is denied.
LFS: Put "https://github-cloud.s3.amazonaws.com/alambic/media/386560498/b0/d6/b0d6456f03d9445b2587da5c4485d16d740b3bc202ce0adaa47fa547ffaff4b818?actor_id=335197827&key_id=0&repo_id=21365123868": write tcp 192.168.1.xxx->52.216.143.xxx: wsasend: Access is denied.

**Comment by KalleOlaviNiemitalo** [comment]
It looks like the send operation is denied by something in your local computer. Do you have a third-party firewall installed?

**Comment by csdjk** [comment]
> It looks like the send operation is denied by something in your local computer. Do you have a third-party firewall installed?

I turned off the third party firewall after the push is the same error

**Comment by bk2204** [comment]
Hey,

This message means that your computer has denied the outgoing connection.  This is going to be caused by something on your computer that's preventing the connection from being made, which is likely a third-party antivirus, firewall, monitoring software, or some sort of proxy.

Often, disabling this software is not sufficient to prevent it from breaking Git or Git LFS.  You'll need to completely uninstall it and then reboot, and then things should work again.  The Git and Git LFS developers don't recommend using third-party antivirus or firewalls for this reason; instead, use Windows Defender and Windows Firewall.

Can you retry after uninstalling all of those third-party programs and rebooting?

**Comment by amar-laksh** [comment]
FIX: at least in my case, check which encryption you're using for your ssh keys, RSA works but not ED

**Comment by bk2204** [comment]
If your SSH keys are the cause of this, then you have a broken SSH proxy which is causing failures, and you should remove that software.

**Comment by bk2204** [comment]
Since we haven't heard back on this issue in about a month, and it's caused by a local issue on the system, I'm going to close this.
