### ISSUE TITLE
Critical Vulnerability (CVE-2022-23806)

### ISSUE THREAD

**Issue by gucci-ninja** [git-lfs/git-lfs#4888]
**Describe the issue**
Git-LFS is using a version of [Go (1.11)](https://github.com/git-lfs/git-lfs/blob/main/go.mod#L32) that currently has a critical vulnerability from the crypto/elliptic package. Here is the [CVE reference](https://nvd.nist.gov/vuln/detail/CVE-2022-23806)

**System environment**
Applicable for all environments.

**Output of `git lfs env`**
N/A as it's a security issue not with the product itself.

**Additional context**
Git LFS should upgrade to Go version to v1.17.7 or v1.16.4 to resolve the vulnerability.

**Comment by bk2204** [comment]
Hey,

This is not an actual vulnerability.  Git LFS by default builds binaries with the latest Go 1.17.  We allow people to use older versions of Go because various distros backport security fixes and there's no reason to needlessly lock out older versions.

In fact, the [documentation](https://go.dev/doc/modules/gomod-ref) clearly states that this directive means that the code was written assuming certain semantics, and controls the behavior of the compiler in the face of that directive.  It's not intended as a directive to force people to upgrade their code.

As a result, I'll be closing this issue, since it doesn't actually represent a security vulnerability.

**Comment by gucci-ninja** [comment]
Thanks for the clarification. We will build our own binaries as part of the documentation.
