### ISSUE TITLE
Using `git-lfs` to track large `.sql` (text) files on backups

### ISSUE THREAD

**Issue by haneef95** [git-lfs/git-lfs#4915]
**Describe the issue**
To check if git-lfs will keep a full copy of every version of the `.sql` file or just the differences on the `git-lfs` backend and on the local copy.

How will it appear within Github? Could I see the text differences on a line-by-line basis, just like other git commits?

**System environment**
Cent OS

**Additional context**
Any other relevant context about the problem here.

**Comment by KalleOlaviNiemitalo** [comment]
The `.git/lfs/objects/` directory in the local repository will store the versions of LFS files as uncompressed full copies, rather than deltas. I don't know whether GitHub stores them as deltas.

**Comment by bk2204** [comment]
Hey,

Git LFS doesn't store data in a compressed way.  It keeps a full history of the files, since in many cases, files stored in Git LFS (e.g., images) are already compressed and attempting to compress them again would simply expand them.

As to how GitHub works with LFS files, please ask GitHub Support.  This repository is only for the open source Git LFS client, and we don't track GitHub-specific questions or issues here.
