### ISSUE TITLE
GPG Error - Signatures couldn't be verified

### ISSUE THREAD

**Issue by RogueOverride** [git-lfs/git-lfs#4931]
**Describe the bug**
When installing the repository for Ubuntu 20.04 LTS (Focal), everything appears fine, but the moment we perform a `apt-get update` we get the following message:

```
An error was encountered while installing package(s): W: GPG error: https://packagecloud.io/github/git-lfs/ubuntu focal InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 6B05F25D762E3157
E: The repository 'https://packagecloud.io/github/git-lfs/ubuntu focal InRelease' is not signed.
```

This breaks all future installs on the system.

**To Reproduce**
1. `curl -s https://packagecloud.io/install/repositories/github/git-lfs/script.deb.sh | sudo bash`
2. `apt-get update`

**Expected behavior**
That the package cache will update without errors regarding signatures.

**System environment**
Environment: AWS
Instance Type: g5g.2xlarge
Operating System: Ubuntu 20.04 LTS
EC2 Image Name: "ARM64 NVIDIA Deep Learning" 

**Output of `git lfs env`**
N/A - Unable to install.

**Additional context**
N/A.

**Comment by bk2204** [comment]
Hey,

Are you using an arm64 image?  This message probably means that there's no arm64 package for Ubuntu focal, which is the case: we provide arm64 packages only for the latest Debian release.  GitHub Actions doesn't have native arm64 runners, so we only build for certain systems since the packages have to be built in emulation, which is extremely slow and expensive.

Things do appear to work for me on an x86-64 Ubuntu focal Docker container.

If you want the latest release, you can download the tarballs from the release assets page, which should provide relocatable binaries, even though they're not packaged.

As for the script itself, we don't control it; it's shipped by packagecloud.io and we don't have the ability to customize it.  You can provide them feedback on failing earlier in this case, though.

**Comment by RogueOverride** [comment]
Thanks for clarifying this, I'll look into that approach.

**Comment by bk2204** [comment]
Sounds good.  I'm going to close this, since I don't think there's anything for us to track here, but if something else comes up, please let us know.
