### ISSUE TITLE
Is there any good approach for merge non-lfs upstream?

### ISSUE THREAD

**Issue by demonguy** [git-lfs/git-lfs#5002]
We got an upstream which isn't lfs, however contains so many binary files.
So we decide to migrate our repo to lfs. But how can we merge upstream in the future? Is there known approach for doing it?

**Comment by bk2204** [comment]
Hey,

If you've used something like `git lfs migrate import` without the `--no-rewrite` flag, then you've rewritten history and the old and new repos will have completely diverged.  If you've used the `--no-rewrite` flag or otherwise not rewritten the entire history, then it's likely you can continue to merge upstream, but you could end up with binaries instead of LFS files.  I'm not aware of any way to avoid this.

**Comment by demonguy** [comment]
What i think so far, is to maintain a pure upstream clone repo, migrate it to lfs
and then, frequently fetch upstream, try to migrate the dealta and changes into lfs.
Then merge into our repo

But is there a good way to migrate dealta to lfs? Or i can only use `git add` `git commit` to do it one by one?

**Comment by bk2204** [comment]
In general, no, there is no good way to do this.  This is a problem whenever you have two divergent histories with similar files, whether or not LFS is used.

If you weren't using LFS, you could well use `git fast-import` and `git fast-export` to replay the commits, but I don't think that's going to work here.  Similarly, applying patches is probably not going to work for you here, either.
