### ISSUE TITLE
Git LFS 3.2 fails to build for linux/arm

### ISSUE THREAD

**Issue by JamesHutchisonCarta** [git-lfs/git-lfs#5026]
**Describe the bug**
See https://github.com/microsoft/vscode-dev-containers/issues/1473

**To Reproduce**
Attempt to install from scratch such as the git LFS feature used by dev containers

Error: `./git-lfs-debian.sh: line 163: ./install.sh: No such file or directory`

**Expected behavior**
Does not error

**System environment**
Linux / ARM64

**Output of `git lfs env`**
Unknown

**Additional context**
This is early, will updated as I get more info

**Comment by bk2204** [comment]
Hey,

Are you expecting that file to be in the current directory when extracted?  As mentioned in the changelog, we now ship our tarballs such that all files are in a top-level directory, since the old way of doing things is called a tarbomb and is generally undesirable.

We did specifically call this out as a change to be anticipated.

**Comment by JamesHutchisonCarta** [comment]
Hey thanks for replying! That sounds like the issue. I'll update the related issue in https://github.com/microsoft/vscode-dev-containers/issues/1473 as it sounds like the fix will need to be done on their end.

**Comment by JamesHutchisonCarta** [comment]
Since this is not a bug but a feature, I'm going to close this ticket.
