### ISSUE TITLE
Add info on how to start tracking files already in git

### ISSUE THREAD

**Issue by gerazov** [git-lfs/git-lfs#5034]
It's helpful to know how to start tracking files already in git using `git lfs`.

The tip in the `README` is only partial (as are several answers on Stack Overflow):
> Tip: if you have large files already in your repository's history, git lfs track will not track them retroactively. To migrate existing large files in your history to use Git LFS, use `git lfs migrate`. 

 I found the answer by @bk2204 [here](https://github.com/git-lfs/git-lfs/issues/874#issuecomment-762937377):

> If you want to track existing files, you need to either use `git lfs migrate import --no-rewrite` with an appropriate pattern or use `git add --renormalize .` after git lfs track (and then commit).

The `git add --renormalize .` made all the difference :+1: thanks! :pray:

**Comment by bk2204** [comment]
Hey,

Thanks for the issue.  It's possible we could add a little something to the README, but I'd rather move this to a FAQ entry, since the README is getting a little long and it will necessarily be incomplete.  We'd planned to move the documentation to AsciiDoc sometime before 3.3, and I think at that point we can include the FAQ in the repo and point users to that as part of this change.

**Comment by gerazov** [comment]
Yeah sure :+1:  

For the moment you could add the renormalize to the readme - it has the tip already there.

**Comment by kuzeko** [comment]
What is the user of the `--no-rewrite` ?
