### ISSUE TITLE
Can prompt multiple times for SSH credentials

### ISSUE THREAD

**Issue by kemin711** [git-lfs/git-lfs#5040]
**Describe the issue**
If forgot to load the ssh key, when git pull using the ssh protocol, then will ask the key for each file. 
Should be nice to only ask the key once.

**System environment**
Linux server and Linux client

**Output of `git lfs env`**

`git-lfs/3.2.0 (GitHub; linux amd64; go 1.18.2)
git version 2.36.1.299.gab336e8

Endpoint=https://pus2/dspkg.git/info/lfs (auth=none) # this is not set up
  SSH=git@pus2:dspkg
LocalWorkingDir=/home/keminz/dspkg
LocalGitDir=/prednet/home/keminz/dspkg/.git
LocalGitStorageDir=/home/keminz/dspkg/.git
LocalMediaDir=/home/keminz/dspkg/.git/lfs/objects
LocalReferenceDirs=
TempDir=/home/keminz/dspkg/.git/lfs/tmp
ConcurrentTransfers=8
TusTransfers=false
BasicTransfersOnly=false
SkipDownloadErrors=false
FetchRecentAlways=false
FetchRecentRefsDays=7
FetchRecentCommitsDays=0
FetchRecentRefsIncludeRemotes=true
PruneOffsetDays=3
PruneVerifyRemoteAlways=false
PruneRemoteName=origin
LfsStorageDir=/home/keminz/dspkg/.git/lfs
AccessDownload=none
AccessUpload=none
DownloadTransfers=basic,lfs-standalone-file,ssh
UploadTransfers=basic,lfs-standalone-file,ssh
GIT_EXEC_PATH=/usr/local/libexec/git-core
git config filter.lfs.process = "git-lfs filter-process"
git config filter.lfs.smudge = "git-lfs smudge -- %f"
git config filter.lfs.clean = "git-lfs clean -- %f"
`
**Additional context**
Currently the set up works perfectly as expected.

**Comment by bk2204** [comment]
Hey,

Git LFS doesn't actually request the SSH key for each file, but because it is multi-threaded, it can ask for it multiple times, once for each thread, so that it can make independent authentication requests.  That is, it should only request the key up to 8 times unless the authentication expires, since there are only 8 threads in the general case.

We could consider caching the authentication across threads, although that becomes a bit trickier and doesn't prevent the fact that the authentication might expire and need an additional request to get new tokens.
