### ISSUE TITLE
Cannot clone in long-named working directory on Windows

### ISSUE THREAD

**Issue by ash-r1** [git-lfs/git-lfs#5090]
**Describe the bug**

I am using the latest Git for Windows package.
I met a bug when I cloned my repo into the deeply nested directory.

At first, git said below with the long path like `C:\Users\ash\Documents\work\ash\work-dir\ASH(Dev)\steam\ep001\seq001\c001\work\light\lt-01-2022-08-17-13-27-21`

```
Could not canonicalize current working directory: The filename, directory name, or volume label syntax is incorrect.
fatal: the remote end hung up unexpectedly
```

By investigating around os_tools, I found the subprocess executing "cygpath -w" returns an incorrect result.
Here's the line: 
https://github.com/git-lfs/git-lfs/blob/7001116051a53b0b93ab1f1aafbb3b6516480a23/tools/os_tools.go#L31

I found two variations around this problem. (I guess the almost same reason causes these two.)

## case1. "C:\Users\ash\Documents\work\ash\work-dir\ASH(Dev)\steam\ep001\seq001\c001\work\light\lt-01-2022-08-17-13-27-21" 

By calling `cygpath -w` with this path by `os.Exec`, stdout puts like below:

```
7-21
/c/Users/ash/Documents/work/ash/work-dir/ASH(Dev)/steam/ep001/seq001/c001/work/light/lt-01-2022-08-17-13-27-21
```

As you see, it has two lines unexpectedly.

## case 2. "C:\Users\ash\Documents\work\ash\work-dir\ASH(Dev)\steam\ep001\seq001\c001\work\light\lt-01" 

With this case, `cygpath` fails and put below line into stderr.

```
Stderr: lt-01: can't convert empty path
```

**To Reproduce**

1. use Windows. 
2. make directory `/c/Users/ash/Documents/work/ash/work-dir/ASH(Dev)/steam/ep001/seq001/c001/work/light`.
3. cd to there.
4. `git clone repo-url lt-01-2022-08-17-13-27-21` (lfs enabled in local/remote)

**Expected behavior**

Not failing.

**System environment**

OS: Windows 11
Git & Git LFS: git-lfs-windows-amd64-v3.2.0-52-g1f8c5045 (running `/c/Program Files/Git/bin/bash.exe`)
arch: amd64

**Output of `git lfs env`**

```
git-lfs/3.2.0 (GitHub; windows amd64; go 1.18.5)
git version 2.37.2.windows.2

LocalWorkingDir=
LocalGitDir=
LocalGitStorageDir=
LocalMediaDir=lfs\objects
LocalReferenceDirs=
TempDir=lfs\tmp
ConcurrentTransfers=8
TusTransfers=false
BasicTransfersOnly=false
SkipDownloadErrors=false
FetchRecentAlways=false
FetchRecentRefsDays=7
FetchRecentCommitsDays=0
FetchRecentRefsIncludeRemotes=true
PruneOffsetDays=3
PruneVerifyRemoteAlways=false
PruneRemoteName=origin
LfsStorageDir=lfs
AccessDownload=none
AccessUpload=none
DownloadTransfers=basic,lfs-standalone-file,ssh
UploadTransfers=basic,lfs-standalone-file,ssh
GIT_EXEC_PATH=C:/Program Files/Git/mingw64/libexec/git-core
git config filter.lfs.process = "git-lfs filter-process"
git config filter.lfs.smudge = "git-lfs smudge -- %f"
git config filter.lfs.clean = "git-lfs clean -- %f"
```

**Additional context**

I'm not sure why git-lfs calls `cygpath -w`.
By replacing `tools.Getwd()` by `os.Getwd()` in this line, this bug has reslved.
https://github.com/git-lfs/git-lfs/blob/7001116051a53b0b93ab1f1aafbb3b6516480a23/commands/commands.go#L351
Of course, this change might occur other problems.
It might relate to MinGW bash / Golang core lib.

This build is skipping cygpath, it works: https://github.com/ash-r1/git-lfs/releases/tag/v3.2.0-57-gac68a634

**Comment by bk2204** [comment]
Hey,

Thanks for the report.  `cygpath -w` is required to handle both Cygwin, which Go doesn't support natively, as well as `file:///` URLs.  If `cygpath -w` is not returning a single value, that would be a bug in the MINGW or Cygwin runtime you're using.

I'm not able to reproduce this on my Windows 10 VM, even with the latest Git for Windows, although it's possible that you're seeing this problem because you're using `Documents`, which typically should not be used to store Git repositories because Windows imposes special, bizarre permissions on it that break other tools.  If you try moving your repositories out of the `Documents` folder and still see this, can you please report it to either Git for Windows, if that's where your `cygpath` comes from, or otherwise the purveyor of that utility?

**Comment by ash-r1** [comment]
@bk2204 Thank you for replying.

> `cygpath -w` is required to handle both Cygwin, which Go doesn't support natively, as well as `file:///` URLs.

Just curious, when Git LFS needs to use `file:///` path scheme for Cwd?
I tested with the latest Git / git-lfs on windows and found `C:¥`-style only.

> that would be a bug in the MINGW or Cygwin runtime

Tbh, I agree with you.
Although, the MinGW on my VM is bundled by Git for windows.
To improve the end-user experience of Git-LFS, we have to escalate this issue to MinGW/Cygwin maintainers or try to avoid this bug.

Btw, Who maintains Git for windows? Does anyone know?

> I'm not able to reproduce this on my Windows 10 VM

This problem depends on the path you use. Which exact path did you use?
Also, I guess cygwin terminal's internal width can cause it.

I don't think it's because of Documents dir. I tested on several other directories, including non-Documents dir.

For more information, I meet this bug when user-input has line-break on default Git bash width like: 

```sh
$ cygpath -w "C:¥Users¥ash¥Documents¥work¥ash¥work-dir¥ASH(Dev)¥steam¥ep001¥seq001¥c001¥work¥light¥lt-01-2022-08-17-13-2
7-21"
C:¥Users¥ash¥Documents¥work¥ash¥work-dir¥ASH(Dev)¥steam¥ep001¥seq001¥c001¥work¥light¥lt-01-2022-08-17-13-27-21
```

It can be a line-break control mistake between Cygwin/MINGW and golang os.Exec.

**Comment by bk2204** [comment]
Hey,

> Just curious, when Git LFS needs to use `file:///` path scheme for Cwd? I tested with the latest Git / git-lfs on windows and found `C:¥`-style only.

Git LFS rewrites all local paths into `file:///` URLs internally for remotes and this is required for cloning, fetching, and pushing local paths.  The same function is used in multiple different locations.  We use the same function there because on Cygwin, it's also required to canonicalize both sets of paths identically.

> > that would be a bug in the MINGW or Cygwin runtime
> 
> Tbh, I agree with you. Although, the MinGW on my VM is bundled by Git for windows. To improve the end-user experience of Git-LFS, we have to escalate this issue to MinGW/Cygwin maintainers or try to avoid this bug.
>
> Btw, Who maintains Git for windows? Does anyone know?

The Git for Windows project is maintained on GitHub: https://github.com/git-for-windows/git/.  You should open an issue there about this, since they'd be able to fix it.
 
> > I'm not able to reproduce this on my Windows 10 VM
> 
> This problem depends on the path you use. Which exact path did you use? Also, I guess cygwin terminal's internal width can cause it.

I used a completely identical path except that my home is `C:\Users\bk2204` instead of `C:\Users\ash`.  Note that there's no TTY in this case, so using the terminal's width is incorrect and would be a bug in cygpath.

> I don't think it's because of Documents dir. I tested on several other directories, including non-Documents dir.
> 
> For more information, I meet this bug when user-input has line-break on default Git bash width like:
> 
> ```shell
> $ cygpath -w "C:¥Users¥ash¥Documents¥work¥ash¥work-dir¥ASH(Dev)¥steam¥ep001¥seq001¥c001¥work¥light¥lt-01-2022-08-17-13-2
> 7-21"
> C:¥Users¥ash¥Documents¥work¥ash¥work-dir¥ASH(Dev)¥steam¥ep001¥seq001¥c001¥work¥light¥lt-01-2022-08-17-13-27-21
> ```

Note that it looks like you're using the Japanese Yen symbol and not the backslash here, which could definitely be the problem.  Note that Git LFS sets the locale to UTF-8, which should avoid this, but you should be sure you're using UTF-8 (`chcp 65001`) and not something like SHIFT-JIS.

> It can be a line-break control mistake between Cygwin/MINGW and golang os.Exec.

We strip all whitespace, so I'm pretty sure that's not the case.

**Comment by ash-r1** [comment]
@bk2204 

Thank you for your kindness. I'll investigate more based on your comment.
I'm posting the issue on the git-for-windows repo.

> Note that there's no TTY in this case, so using the terminal's width is incorrect and would be a bug in cygpath.

Thanks. That's true and depends on cygpath's implementation. Anyways it's a cygpath's bug.

> Note that it looks like you're using the Japanese Yen symbol

Ah, yes. It could depend on the OS language. I'll test on English VM before moving to git-for-windows repo.

I'll close this issue for now because this problem would be caused by `cygpath` bundled in git-for-windows.

I really appreciate your support. Thank you a lot.

**Comment by ash-r1** [comment]
#5106 would have fixed this issue 🎉
