### ISSUE TITLE
git clone --shared checkout without fetch

### ISSUE THREAD

**Issue by Thaodan** [git-lfs/git-lfs#5100]
**Describe the issue**
I tried to clone a local repo that already has all objects but lfs tells me to download them instead.

1. git clone --local  --shared /var/lib/gitea/data/gitea-repositories/archlinux-packages/repo-home-thaodan-bin.git home-thaodan
2. git lfs checkout:
>Skipped checkout for "x86_64/shpp-git-1.9.1.1.r20.g130d1ca-1-any.pkg.tar.xz", content not local. Use fetch to download.

**System environment**
```
[git@thaodan home-thaodan]$ cat /etc/os-release 
NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
BUILD_ID=rolling
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://archlinux.org/"
DOCUMENTATION_URL="https://wiki.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://bugs.archlinux.org/"
LOGO=archlinux-logo
```

**Output of `git lfs env`**
```
[git@thaodan home-thaodan]$ git lfs env
git-lfs/3.2.0 (GitHub; linux amd64; go 1.18.2)
git version 2.37.2

Endpoint=file:///var/lib/gitea/data/gitea-repositories/archlinux-packages/repo-home-thaodan-bin.git (auth=none)
LocalWorkingDir=/srv/http/repo.thaodan.de/archlinux/home-thaodan
LocalGitDir=/srv/http/repo.thaodan.de/archlinux/home-thaodan/.git
LocalGitStorageDir=/srv/http/repo.thaodan.de/archlinux/home-thaodan/.git
LocalMediaDir=/var/lib/gitea/data/lfs/objects
LocalReferenceDirs=/var/lib/gitea/data/gitea-repositories/archlinux-packages/repo-home-thaodan-bin.git/lfs/objects
TempDir=/var/lib/gitea/data/lfs/tmp
ConcurrentTransfers=8
TusTransfers=false
BasicTransfersOnly=false
SkipDownloadErrors=false
FetchRecentAlways=false
FetchRecentRefsDays=7
FetchRecentCommitsDays=0
FetchRecentRefsIncludeRemotes=true
PruneOffsetDays=3
PruneVerifyRemoteAlways=false
PruneRemoteName=origin
LfsStorageDir=/var/lib/gitea/data/lfs
AccessDownload=none
AccessUpload=none
DownloadTransfers=basic,lfs-standalone-file,ssh
UploadTransfers=basic,lfs-standalone-file,ssh
GIT_EXEC_PATH=/usr/lib/git-core
git config filter.lfs.process = "git-lfs filter-process"
git config filter.lfs.smudge = "git-lfs smudge -- %f"
git config filter.lfs.clean = "git-lfs clean -- %f"
```
**Additional context**
Any other relevant context about the problem here.

I'm using Gitea to push prebuild packages to the server, the package should be checkout either using git worktree or using local clones.
In any case git-lfs doesn't check the existing objects in the storage.

**Comment by bk2204** [comment]
Hey,

In order to clone a local repo and have `--shared` or any sort of alternates work, the LFS objects have to live in a location that's under the `lfs/objects` directory in the repository from which you're cloning, and that data has to be in the appropriate format used by Git LFS.

Are the Git LFS objects stored under `/var/lib/gitea/data/gitea-repositories/archlinux-packages/repo-home-thaodan-bin.git/lfs/objects`?  If so, can you show the full path to some object under that directory?  If not, then you'll need to specify an appropriate URL with `lfs.url` in the local `.git/config` after cloning and use `git lfs fetch`.

**Comment by Thaodan** [comment]
> Are the Git LFS objects stored under
> `/var/lib/gitea/data/gitea-repositories/archlinux-packages/repo-home-thaoda
> n-bin.git/lfs/objects`?  If so, can you show the full path to some object
> under that directory?  If not, then you'll need to specify an appropriate
> URL with `lfs.url` in the local `.git/config` after cloning and use `git
> lfs fetch`.

They are not they are the global object cache `/var/lib/gitea/data/lfs`.
Lfs.url won't work since the objects are present and the webserver isn't 
configured to do around trip with itself.

Even if so there would be just duplication.

**Comment by bk2204** [comment]
Hey,

I know you want to do a local clone in this case, but a local clone only works here if the LFS objects are in the same Git repository (under `lfs/objects`) as you're cloning from.  That's just how this operation happens to work for local clones, and isn't going to change.

Since in this case you aren't able to do a local clone and have it work, you'll need to use HTTPS or SSH to clone this repository and fetch objects, even if that leads to duplication.
