### ISSUE TITLE
Git LFS Problem in Pushing Larger Files 

### ISSUE THREAD

**Issue by park-jeounghan** [git-lfs/git-lfs#5135]
git lfs push error checked request.

![image](https://user-images.githubusercontent.com/48382217/194012746-538ceef0-481c-448f-881d-7d933b1657b2.png)

help me 
i can't git push , because git lfs http 502 error  show

file size = 800MB

$ git --version
git version 2.38.0.windows.1

AJG@LAPTOP-8TDH792M MINGW64 /x/tangun/LFS-test (master)
$ git lfs --version
git-lfs/3.2.0 (GitHub; windows amd64; go 1.18.2)

os : windows 10 x64

**Comment by park-jeounghan** [comment]
$ git --version
git version 2.38.0.windows.1

AJG@LAPTOP-8TDH792M MINGW64 /x/tangun/LFS-test (master)
$ git lfs --version
git-lfs/3.2.0 (GitHub; windows amd64; go 1.18.2)

**Comment by bk2204** [comment]
Hey,

An HTTP 502 error is a Bad Gateway.  Like all 500-series errors, this indicates that the server has had a problem and is not able to service the request.  There's nothing we can do on the client side and you'd need to talk to the administrator of that server to see if they can get things fixed so that doesn't happen anymore.

**Comment by park-jeounghan** [comment]
> 여기요,
> 
> HTTP 502 오류는 잘못된 게이트웨이입니다. 모든 500 시리즈 오류와 마찬가지로 이는 서버에 문제가 있어 요청을 처리할 수 없음을 나타냅니다. 클라이언트 측에서 우리가 할 수 있는 일은 아무것도 없으며 더 이상 그런 일이 발생하지 않도록 문제를 해결할 수 있는지 확인하려면 해당 서버의 관리자에게 문의해야 합니다.

>
I know what your answer means
But if PUSH is not possible on all PCs now
I think you're right, but
It is possible to PUSH on an external developer PC who has been using Git for a long time.
We are looking for other examples.
Thank you for your reply

good luck to you
