### ISSUE TITLE
Windows: Could not find Git; can not register Git LFS.

### ISSUE THREAD

**Issue by MicahZoltu** [git-lfs/git-lfs#5147]
**Describe the issue**
I have git on a Windows box.  When I try to install git lfs, it tells me "Could not find Git; can not register Git LFS."  I don't have `git` on my system/user path, but if I try running the installer from a command prompt (mingw64) which *does* have git on the PATH I get the same error.  My .gitconfig is also not in the default location.

I'm guessing that since git lfs demands elevation (why?), it is executing in a different context that doesn't inherit environment variables from my shell.

**System environment**
Windows 11, both cygwin and Windows directly.
(redacted/removed a few things from below)
```text
diff.astextplain.textconv=astextplain
http.sslbackend=schannel
core.autocrlf=input
core.fscache=true
core.symlinks=false
pull.ff=only
init.defaultbranch=master
core.sshcommand=ssh -F ***/ssh/config -i ***/ssh/micah_rsa
core.autocrlf=input
user.name=****
user.email=****
pull.rebase=false
fetch.prune=true
rebase.autostash=false
```

**Comment by bk2204** [comment]
Hey,

This message comes because we need Git to be on the PATH and in a system path if it's being installed system-wide to prevent security problems.  If you don't want to do that, then I'd use the Git LFS installed with Git for Windows.

I'm also going to ping @chrisd8088, who helped work on this change and might be able to offer alternate solutions.

**Comment by MicahZoltu** [comment]
There isn't a way to use the installer from the Git LFS website to do a local install, it is for global install only?

**Comment by chrisd8088** [comment]
Typically users tend to install Git LFS via the Git for Windows [project](https://gitforwindows.org/) because it packages Git LFS along with Git.

If you are using the standalone Git LFS packages for Windows, the Inno Setup installer does still need to be able to locate Git, and  it looks in all the locations found in the `PATH` [variable](https://github.com/git-lfs/git-lfs/blob/f4cd44bed7d12494bb3972bd67da8d324d964599/script/windows-installer/inno-setup-git-lfs-installer.iss#L173).  I'm not sure why it would not find your Git if it's available in `PATH`, but perhaps that has something to do with how MinGW manages environment variables.

At any rate, all the Inno Setup installer really does is validate some aspects of your setup and then [make sure](https://github.com/git-lfs/git-lfs/blob/f4cd44bed7d12494bb3972bd67da8d324d964599/script/windows-installer/inno-setup-git-lfs-installer.iss#L67-L70) that the location of the `git-lfs.exe` binary is in your user and system `PATH` variables and that the `GIT_LFS_PATH` variable is also defined in both the user and system context, and then [runs](https://github.com/git-lfs/git-lfs/blob/f4cd44bed7d12494bb3972bd67da8d324d964599/script/windows-installer/inno-setup-git-lfs-installer.iss#L221) `git-lfs.exe install`.

If you're managing a custom configuration and want to try those things yourself, that might be the easiest route.  Then you can also control whether you run `git-lfs.exe install` (which is the same as `git lfs install`, assuming Git can find the `git-lfs.exe` binary in `PATH`) in its default "global" mode or with the `--local`, `--worktree`, or `--system` flags.

The global mode is akin to the `git config` global mode, i.e., it wants to adjust your `$HOME/.gitconfig` file to include the normal `lfs` filter settings.  If you use the `--local` flag then the current Git repository's `.git/config` file is adjusted, and `--system` adjusts the `$(prefix)/etc/gitconfig` file, which is based on where Git was installed.  Finally, the `--system` flag also skips installing the Git LFS custom Git hooks; otherwise the `git lfs install` command will try to install them in `.git/hooks`, but only if you're in a Git repository at the time.

**Comment by MicahZoltu** [comment]
I was hoping to be able to be able to use this without adding `git` or `git-lfs` to the PATH using the instructions helpfully provided by @chrisd8088, but there doesn't appear to be a way to do this.  I was able to download `git-lfs.exe` from the releases page (not the installer) and then do `git-lfs.exe install`.  This appears to have correctly found and updated the `.gitconfig` used by `git` and I now have `filter.lfs.*` entries.  It just put `git-lfs` for the commands, but I modified it to include a full path to `git-lfs`.

Unfortunately, `git lfs` still says `git: 'lfs' is not a git command`, and if I try to run `C:\path\to\git-lfs.exe ls-files` it fails because `git-lfs` cannot find `git` (since `git` isn't on the path):
> Error: failed to find `git rev-parse --git-dir --show-toplevel`: executable file not found in %PATH%

I don't see any way to teach `git-lfs` where `git` is other than via PATH, and I am not sure how to make `git lfs` become a valid command.

For now, I have fallen back to using WSL to address my immediate issue of needing to fetch some files, but it would be nice if it was possible to get `git-lfs` working in a "pathless" environment (useful, for example, when one is working with multiple versions of `git` on the same host and wants to keep the system clean/isolated).

**Comment by berndschatz** [comment]
@MicahZoltu thx for the hint with the release page.

After i copied the binary in the /usr/bin folder of cygwin, 
it works:

```
$ cp Downloads/git-lfs-3.2.0/git-lfs.exe /usr/bin/.
$ git lfs ls-files
Not in a Git repository.
```

@chrisd8088  regarding ,,Typically users tend to install Git LFS via the Git for Windows [project](https://gitforwindows.org/) because it packages Git LFS along with Git.''. 

In general you need much more than git and git-lfs for a working developer environment.
To download every tool manually and to keep it up to date is IMHO wasting time.

**Comment by bk2204** [comment]
I don't think we're going to have Git LFS work in a way where Git is not in the PATH.  The PATH environment variable is the standard way to locate where programs are, and we need to invoke it properly which means we need to look at PATH.  As a result, I'm going to close this.

**Comment by TechQuery** [comment]
If someone has the same error with:

```powershell
winget update GitHub.GitLFS
```

this answer may save you: https://stackoverflow.com/a/78714176/8876677

It seems the `C:\Program Files\Git\cmd` `PATH` value set by Git for Windows has nothing help for Git LFS installer.
