### ISSUE TITLE
mac13.0  install git-lfs error

### ISSUE THREAD

**Issue by xiaohuihui000** [git-lfs/git-lfs#5151]
Warning: You are using macOS 13.
We do not provide support for this pre-release version.
You will encounter build failures with some formulae.
Please create pull requests instead of asking for help on Homebrew's GitHub,
Twitter or any other official channels. You are responsible for resolving
any issues you experience while you are running this
pre-release version.

Error: go: undefined method `on_intel' for #<Resource:0x00007f8e3083cf78>

can you help me?

**Comment by bk2204** [comment]
Hey,

I think this is a problem with the Homebrew configuration.  The `<#Resource...>` thing indicates a Ruby object address, and Homebrew is written in Ruby.  I'd see if somebody has fixed this on Homebrew or wait until Homebrew officially supports macOS Ventura, since I don't think there's anything we can do here to address this.
