### ISSUE TITLE
feature: bash completion script

### ISSUE THREAD

**Issue by peterdd** [git-lfs/git-lfs#5155]
I miss a bash complition similiar to what exists for git when typing 

`git-lfs[TAB][TAB]`

See also https://github.com/git/git/blob/master/contrib/completion/git-completion.bash

On Debian **bash-completion** package seems to not contain git or git-lfs

`dpkg-query -L bash-completion`

**Comment by bk2204** [comment]
Hey,

I think this would be a nice improvement.  We're already tracking this as #5104, since I think it's possible to try to implement one set of functionality for all shells, so I'm going to close this in favour of that one.

I know that Git does provide such functionality, but not in the bash-completion package.  It's likely that we can provide something similar that can be shipped alongside Git LFS for those who want to use it.
