### ISSUE TITLE
Jenkins security disable core.hookPath cause git lfs install failed

### ISSUE THREAD

**Issue by nhatkhai** [git-lfs/git-lfs#5171]
**Describe the issue**
https://github.com/jenkinsci/git-plugin/pull/1237 had add invalid value into `core.hookPath=NUL:` in windows. This cause `git lfs install` failed with follow message:

Is it possible for git lfs design to still work under this setting? Seem like Jenkins forks currently think this is the right approach for disable hook!

```
11:07:05  open C:\XYZ\NUL:\pre-push: The filename, directory name, or volume label syntax is incorrect.
11:07:05  To resolve this, either:
11:07:05    1: run `git lfs update --manual` for instructions on how to merge hooks.
11:07:05    2: run `git lfs update --force` to overwrite your hook.
```

**System environment**
git version 2.33.1.windows.1

**Comment by bk2204** [comment]
You should be able to run with `--skip-repo`.  If I set my `core.hooksPath` to `/dev/null` on Linux, I can reproduce the behaviour you're seeing.  However, if I use `--skip-repo`, then the `git lfs install` command works.

**Comment by nhatkhai** [comment]
But I need was install it with ‘—local’

**Comment by bk2204** [comment]
Despite what the documentation says, that will actually work.  `--skip-repo` basically means "skip installing hooks"; it has no effect on the modification of the Git configuration file.

If that works for you, let me know, and leave this issue open.  Then I can update the documentation and FAQ to cover this case so it will be easier to discover in the future.

**Comment by bk2204** [comment]
Yes, if you run `git lfs install --local`, then it won't affect `git clone`, because the repository doesn't exist yet.  You'd need to use `--global` or the default behaviour (which is `--global`) before cloning for the installation to have an effect.  `--skip-repo` won't affect that either way.

It is the case that, for example, `git push` will not push LFS objects if the hooks are not installed.  If you need that behaviour, then you need to have a conversation with the Jenkins folks about unbreaking the hook path.

**Comment by bk2204** [comment]
Okay, there's now some docs on this, including a FAQ entry, in #5177.  That should make this easier to explain and hopefully easier for folks to figure out what's up.

**Comment by harryssuperman** [comment]
@bk2204 , Thank u very much for the FAQ entry
