### ISSUE TITLE
Unable to clone repository in Windows 10 hosts with "Updating files" stuck at percentage

### ISSUE THREAD

**Issue by viertelb** [git-lfs/git-lfs#5178]
**Describe the bug**
I am not sure if this is the right place to put it since we are using Gitlab. That beeing said, I can clone a repository successfully from Ubuntu, but when I try to do it from Windows 10 the process gets stuck at "Updating files" at 94%. Waiting several hours does not lead to the process beeing finished. 

As far as I understand all pointer have been cloned and the process is stuck at converting pointers to files. 

**Also, I would be happy to know if it would be possible to clone just the pointers and download the files when I need them separately on a per-file-basis.**

**To Reproduce**
1. Open Git Bash in folder in Windows 10.
2. git lfs install
3. eval $(ssh-agent -s) shows the process running with PID
4. ssh-add <KEY>
5. git clone <REPO>

```
Cloning into 'REPO'...
remote: Enumerating objects: 6097, done.
remote: Counting objects: 100% (3507/3507), done.
remote: Compressing objects: 100% (2028/2028), done.
remote: Total 6097 (delta 1504), reused 3447 (delta 1473), pack-reused 2590
Receiving objects: 100% (6097/6097), 410.14 MiB | 12.12 MiB/s, done.
Resolving deltas: 100% (3234/3234), done.
Updating files:  94% (4701/5001)

```

**Expected behavior**
I expect the clone process to finish.

**System environment**
Windows 10 Enterprise, Build 19044
Connected via VPN to the network

**Output of `git config -l`**
```
diff.astextplain.textconv=astextplain
filter.lfs.clean=git-lfs clean -- %f
filter.lfs.smudge=git-lfs smudge -- %f
filter.lfs.process=git-lfs filter-process
filter.lfs.required=true
http.sslbackend=openssl
http.sslcainfo=C:/Program Files/Git/mingw64/ssl/certs/ca-bundle.crt
core.autocrlf=true
core.fscache=true
core.symlinks=false
credential.helper=manager
filter.lfs.clean=git-lfs clean -- %f
filter.lfs.smudge=git-lfs smudge -- %f
filter.lfs.process=git-lfs filter-process
filter.lfs.required=true
credential.helper=manager
gui.recentrepo=C:/Users/vierte_b/gitlab/test
http.postbuffer=100000000
``` 

**Output of `git lfs env`**
```
$ git lfs env
git-lfs/2.9.1 (GitHub; windows amd64; go 1.12.7; git 7b479cc8)
git version 2.24.1.windows.2

LocalWorkingDir=
LocalGitDir=
LocalGitStorageDir=
LocalMediaDir=lfs\objects
LocalReferenceDirs=
TempDir=lfs\tmp
ConcurrentTransfers=3
TusTransfers=false
BasicTransfersOnly=false
SkipDownloadErrors=false
FetchRecentAlways=false
FetchRecentRefsDays=7
FetchRecentCommitsDays=0
FetchRecentRefsIncludeRemotes=true
PruneOffsetDays=3
PruneVerifyRemoteAlways=false
PruneRemoteName=origin
LfsStorageDir=lfs
AccessDownload=none
AccessUpload=none
DownloadTransfers=basic,lfs-standalone-file
UploadTransfers=basic,lfs-standalone-file
GIT_EXEC_PATH=C:/Program Files/Git/mingw64/libexec/git-core
git config filter.lfs.process = "git-lfs filter-process"
git config filter.lfs.smudge = "git-lfs smudge -- %f"
git config filter.lfs.clean = "git-lfs clean -- %f"

```
**Additional context**
Cloning the same repo in Ubuntu works fine. The output is in German but it is clear that the process went beyond "Updating files" and now is working on the "filter" section, making (slow) progress).

The Ubuntu is a VM running on the Windows 10 hosts. Both, the host and the VM are connected via VPN to the network.

```
Klone nach 'REPO' …
remote: Enumerating objects: 6097, done.
remote: Counting objects: 100% (3507/3507), done.
remote: Compressing objects: 100% (2028/2028), done.
remote: Total 6097 (delta 1504), reused 3447 (delta 1473), pack-reused 2590
Empfange Objekte: 100% (6097/6097), 410.14 MiB | 2.26 MiB/s, fertig.
Löse Unterschiede auf: 100% (3234/3234), fertig.
Aktualisiere Dateien: 100% (5001/5001), fertig.
Filtere Inhalt:  61% (214/350), 443.48 MiB | 3.07 MiB/s
```

**Comment by bk2204** [comment]
Hey,

My guess as to what's happening here is that you have a non-default antivirus or firewall here that's breaking things.  We've seen problems in the past with things like Kaspersky, but in general we recommend against using anything but Windows Firewall or Windows Defender.  Other monitoring software can also cause this problem.  Git LFS is a Go binary and as such it behaves very differently from other software and can trigger bugs in software that intercepts system operations.  Can you confirm that you're either not using any such software, or can you reproduce the problem after completely uninstalling all of it and rebooting?

You may also try updating the version of Git in use, which should also update Git LFS.  2.9.1 is a little old and we've shipped a lot of new versions since then, and the versions of both Git and Git LFS you're using have security problems.

I'd also like to ask you to try the operation in a Windows Subsystem for Linux instance, preferably using an Ubuntu 22.10 (kinetic) instance on the Linux disk.  That will help us see if the problem is this particular repository on your system or if the problem is something interfering with Windows processes.

**Comment by viertelb** [comment]
Thanks for the fast reply. This is company hardware and I have little influence on the software installed, so I will probably not be able to test it without the security restrictions. 

Did I understand you correctly, that I should install the Windows subsystem inside my Linux Virtualbox guest?

Now that we are talking about it I remember having trouble cloning a small repo over VPN on a different Windows 10 host. Only when I disabled the VPN cloning was successfull. Just a sidenote that maybe the VPN with Windows might be the problem (although I use a different VPN here (Check Point) than on the other machine, where I used the Windows-built-in VPN solution).

**Comment by bk2204** [comment]
Hey,

I'd requested that you use the Windows Subsystem for Linux from within Windows to clone the repository and test.  Usually that is less prone to breakage from broken antiviruses and monitoring software.  If you can do that, then it will provide us helpful information to see if that's the cause.

You can certainly try turning the VPN off and see if that helps.  If you'd like to do more debugging, you can invoke the process with `GIT_TRACE=1 GIT_TRANSPORT_TRACE=1 GIT_CURL_VERBOSE=1` (by prepending that to the clone command) and then redirect standard error to a file.  That should also provide us with information about what might be going wrong.

Ultimately, if it does end up being the security software, then you'll need to discuss that with your employer.  Neither Git nor Git LFS recommend using non-default antivirus or security software for that purpose because it tends to break in lots of exciting ways which are out of our control to fix.  That's one of the reasons I requested completely removing it and rebooting since the operation seems to work under Ubuntu.

**Comment by viertelb** [comment]
I was able to clone it using a WSL, thank you very much for pointing me to that option.
