### ISSUE TITLE
Question: How to fetch git objects and LFS objects from different servers?

### ISSUE THREAD

**Issue by saraf-akshay** [git-lfs/git-lfs#5253]
**Description**
We've a heavy clone traffic. So I have an internal mirror server in my org to facilitate with cloning operations. This has been working well for non LFS repos. All my servers are configured with a .gitconfig file which is configured to use mirror URL insteadOf the GitHub URL. 
My .gitconfig file looks like:
```
[url "ssh://<internal mirror>/<repo name>"]
    insteadOf = https://github.com/<repo name>
```

We recently started using git lfs, for a few repos. So I am still learning.

**Problem Statement**: Is there a way to fetch git objects from internal mirror server and LFS objects from GitHub?
With my current insteadOf it's also changing the LFS URL, so the git clone fails. If I try to redirect LFS URL to GitHub, it still doesn't work.
```
[url "ssh://<internal mirror>/<repo name>"]
    insteadOf = https://github.com/<repo name>
[lfs]
	url = https://github.com/<repo name>/info/lfs
```

**System environment**
Using windows server 2016 data center edition
Git version: git version 2.26.2.windows.1
Git lfs version: git-lfs/2.10.0

**Comment by chrisd8088** [comment]
Hey, I'm sorry you're having trouble.  Other core team members may be able to shed additional light on this, but here's what I was able to check using a clone of a personal repo on GitHub.

First, if one simply has the kind of `insteadOf` alias you describe, like this:
```
[url "ssh://git@ssh.github.com/<user>/<repo>"]
        insteadOf = https://github.com/<user>/<repo>
```

then when Git invokes Git LFS, the latter will respect that and attempt to communicate with the SSH server.  For instance, running `GIT_TRACE=1 GIT_TRANSFER_TRACE=1 GIT_CURL_VERBOSE=1 git clone https://github.com/<user>/repo>` I get:
```
22:41:29.757470 trace git-lfs: attempting pure SSH protocol connection
...
22:41:29.766742 trace git-lfs: pure SSH protocol connection failed: Unable to negotiate version with remote side (unable to read capabilities): EOF
...
22:41:29.770486 trace git-lfs: run_command: ssh git@ssh.github.com git-lfs-authenticate /<user>/<repo> download
22:41:29.770622 trace git-lfs: exec: ssh 'git@ssh.github.com' 'git-lfs-authenticate /<user>/<repo> download'
...
22:41:31.047602 trace git-lfs: HTTP: POST https://lfs.github.com/<user>/<repo>/objects/batch
> POST /<user>/<repo>/objects/batch HTTP/1.1
> Host: lfs.github.com
```

What's happening here is that Git LFS applies the `insteadOf` alias and makes a connection to the SSH server to see if it support the "pure SSH" transport protocol.  Few, if any, Git LFS hosting services support this yet, and GitHub does not, so the client gives up on that and proceeds to run the `git-lfs-authenticate` command on the remote server via SSH.  That step is [documented](https://github.com/git-lfs/git-lfs/blob/02ac3de0e19fbfeea7f8ddb079cfe074367a48d3/docs/api/server-discovery.md#ssh) and the server replies with a small JSON response that includes an `href` field telling the Git LFS client where to perform its HTTP requests; in this case, the `https://lfs.github.com/<user>/<repo>/objects/batch` URL.  The client then proceeds to make its requests against that URL, and the clone succeeds with all Git LFS objects downloaded.

So, one answer to your problem might be to implement the `git-lfs-authenticate` command in your SSH server so that it sends back the [documented](https://github.com/git-lfs/git-lfs/blob/02ac3de0e19fbfeea7f8ddb079cfe074367a48d3/docs/api/server-discovery.md#ssh) JSON response.

---

That said, I also found that I could "defeat" the SSH `insteadOf` alias for Git LFS requests so long as I provided a longer alias, because both Git and Git LFS apply the alias with the longest matching prefix.

So using this in my `$HOME/.gitconfig` worked for me to force Git LFS to not use SSH at all, while Git still used SSH:
```
[url "ssh://git@ssh.github.com/<user>/<repo>"]
        insteadOf = https://github.com/<user>/<repo>
[url "https://github.com/<user>/<repo>.git/info/lfs"]
        insteadOf = https://github.com/<user>/<repo>.git/info/lfs
[lfs]
        url = https://github.com/<user>/<repo>.git/info/lfs
```

What happens here is that the `lfs.url` configuration causes the Git LFS client [use](https://github.com/git-lfs/git-lfs/blob/02ac3de0e19fbfeea7f8ddb079cfe074367a48d3/lfsapi/endpoint_finder.go#L88-L90) that URL in preference to [deriving](https://github.com/git-lfs/git-lfs/blob/02ac3de0e19fbfeea7f8ddb079cfe074367a48d3/lfsapi/endpoint_finder.go#L122) it from the URL supplied to `git clone`.  (You could also use `remote.origin.lfsurl`, I believe, to achieve the same thing.)

However, the aliases will still be [applied](https://github.com/git-lfs/git-lfs/blob/02ac3de0e19fbfeea7f8ddb079cfe074367a48d3/lfsapi/endpoint_finder.go#L173) when the "new endpoint" is [constructed](https://github.com/git-lfs/git-lfs/blob/02ac3de0e19fbfeea7f8ddb079cfe074367a48d3/lfsapi/endpoint_finder.go#L89) from the `lfs.url` value.  Since the alias with the longest-match prefix is [chosen](https://github.com/git-lfs/git-lfs/blob/02ac3de0e19fbfeea7f8ddb079cfe074367a48d3/lfsapi/endpoint_finder.go#L306-L308), though, we can take advantage of the fact that the `https://github.com/<user>/<repo>.git/info/lfs` `insteadOf` prefix is longer than the `https://github.com/<user>/<repo>` one, so we can avoid the SSH URL's alias being selected.

I don't know if that will work with your setup, but I hope it will help.

**Comment by saraf-akshay** [comment]
This works @chrisd8088 
Thanks a lot for your detailed response.

Do you have a suggestion on how this could work for more than 1 repo? I've a use case to scale it to few repos. I feel there could be only 1 `lfs.url` ? Or if there can be multiple I am unaware of the syntax.

Example:
```
## Repo 1
[url "ssh://git@ssh.github.com/<user1>/<repo1>"]
        insteadOf = https://github.com/<user1>/<repo1>
[url "https://github.com/<user1>/<repo1>.git/info/lfs"]
        insteadOf = https://github.com/<user1>/<repo1>.git/info/lfs

## Repo 2
[url "ssh://git@ssh.github.com/<user2>/<repo2>"]
        insteadOf = https://github.com/<user2>/<repo2>
[url "https://github.com/<user2>/<repo2>.git/info/lfs"]
        insteadOf = https://github.com/<user2>/<repo2>.git/info/lfs


[lfs]
        url = https://github.com/<user>/<repo>.git/info/lfs
```

How would `lfs.url` work for multiple repositories?
In the meantime, I'm following the document you shared to setup `git-lfs-authenticate`

**Comment by chrisd8088** [comment]
Yes, as far as I know this would only work for one repo at a time, given that `lfs.url` or `remote.<remote>.lfsurl` is generic.  I think you'd have to go with the fuller `git-lfs-authenticate` solution to support that use case, unfortunately.

**Comment by chrisd8088** [comment]
I should also add, though, that you could try putting the `lfs.url` or `remote.<remote>.lfsurl` directives into a `.lfsconfig` file in each repo, and committing the file to the repo, while leaving the `url.<url>.insteadOf` directives in your global `.gitconfig`.  That might work for your case.  I haven't tested it myself in this specific instance, but the idea of `.lfsconfig` is that the Git LFS client will read it in preference to the usual Git configuration files if it exists, and it lets you put a subset of `lfs.*` directives into it.

That way, the `lfs.url` directives would be set individually for each repo, in each repo.

You can see the full details in the `git-lfs-config(5)` [manual page](https://github.com/git-lfs/git-lfs/blob/02ac3de0e19fbfeea7f8ddb079cfe074367a48d3/docs/man/git-lfs-config.adoc).

**Comment by saraf-akshay** [comment]
Thanks a lot @chrisd8088 
All my questions were addressed. Closing this now.

**Comment by chrisd8088** [comment]
Great!  Good luck!
