### ISSUE TITLE
batch response: Git LFS is disabled for this repository.

### ISSUE THREAD

**Issue by yi-yunseok** [git-lfs/git-lfs#5262]
When I trying to use `lfs` features,

`batch response: Git LFS is disabled for this repository. `

I don't know why it is.

https://github.com/yi-yunseok/Yi-Yunseok.github.io

**Comment by bk2204** [comment]
Hey,

Anything that starts with "batch response" comes from the server side and we just report back what the server said.  In this case, the server said that Git LFS is disabled for this repository, but we don't know more.  You'd need to either look at the documentation for GitHub or contact GitHub's support team, since we only handle the open source Git LFS project in this repository.

**Comment by yi-yunseok** [comment]
Thanks for the answer :)
