### ISSUE TITLE
Issues with releases hosted in packagecloud

### ISSUE THREAD

**Issue by dharmendrasha** [git-lfs/git-lfs#5275]
Describe the issue
Attempting to do an apt-get update on a system configured with the git-lfs packagecloud source results in

`E: The repository 'https://packagecloud.io/github/git-lfs/ubuntu kinetic Release' does not have a Release file.`

It would appear that packagecloud are no longer providing the git-lfs packages as attempts to access any git-lfs packagecloud URL reports failure

System environment
Ubuntu 22.10

Additional context
This worked up until very recently.

**Comment by dharmendrasha** [comment]
similar issue : https://github.com/git-lfs/git-lfs/issues/4548

**Comment by chrisd8088** [comment]
Hey, I'm sorry you're having trouble.  I don't believe we have published any packages for Ubuntu Kinetic Kudu; our publication script's last [listed](https://github.com/git-lfs/git-lfs/blob/c66fd28d6c346ffe3be9f5d6bbab550a12b1fbc7/script/packagecloud.rb#L68) Ubuntu release is Jammy Jellyfish.

(As of commit e2465f84b50452ff746f4f389afe5f8052a5a658 in PR #5010, Packagecloud did not yet support Kinetic, and we haven't added it since.)

I've written up PR #5276 to update the set of distributions for which we'll upload packages to Packagecloud the next time we make a release.  However, I don't have a fixed date for when the next Git LFS release will be.  When the next release is complete, though, there should be a package uploaded for Ubuntu Kinetic Kudu.
