### ISSUE TITLE
Optimal way to pull LFS objects when not using Clone?

### ISSUE THREAD

**Issue by strich** [git-lfs/git-lfs#5279]
**Describe the issue**
I've got a CI script we use for our projects (30GB+) that needs to handle both clean new repos on a build agent and existing repo's that can do a pull. The script is currently like so:
```
git init // Only if there is no existing repo
git remote add origin $Remote // Only if there is no existing repo
git fetch origin develop --depth=1
git reset --hard FETCH_HEAD
git lfs pull origin

```
Unfortunately it seems `git reset` is currently causing lfs to download the binary files and in a very slow manner. Is it possible to disable lfs for these commands prior to `lfs pull` so we can efficiently get the repo up to date and only then get lfs to pull objects in hopefully an efficient manner?

**Comment by bk2204** [comment]
Normally, Git invokes Git LFS to smudge things on checkout, which is the normal way of working on things.  If you have a really old Git (I think older than 2.15), though, Git LFS gets invoked once per file instead of once for the entire process.  That can make things a lot slower than you'd like.

During the `git reset --hard`, you can indeed use `GIT_LFS_SKIP_SMUDGE=1` to make Git LFS do nothing in that case and then use `git lfs pull`.

If you're using a reasonably recent Git, then it should perform just fine in either case.  Can you share what version of Git and what OS you're working with?

**Comment by strich** [comment]
This was run on a machine that was built only a couple weeks ago and
installed with Windows 10 and Git for Windows, so it shouldn't be a
particularly old version of lfs. I can try the skip smudge option you
provided some time over the next week or so, thanks.
Are you sure it optimises downloads for reset? It didn't feel like it.

**Comment by nigels-com** [comment]
We've discovered that `git lfs clone` has some flags for including or excluding the LFS objects.
But, we're also being warned that `git lfs` is "deprecated", so hopefuly -I and -X will be showing up in `git clone` too?

**Comment by bk2204** [comment]
Since we haven't heard back on the version of Git or Git LFS here, I'm going to close this issue.  If you can provide the information requested, we can reopen.
