### ISSUE TITLE
Add git-lfs as a tool for VS Code on Flathub

### ISSUE THREAD

**Issue by ranisalt** [git-lfs/git-lfs#5285]
**Describe the issue**

Hello! Git-LFS it pretty much ubiquitous for developers, and some will use [the Flatpak'd version of Visual Studio Code](https://flathub.org/apps/details/com.visualstudio.code) for developing. However, git-lfs is not currently easily available inside Flatpak containers, and one would have to download and install from sources in order to use git-lfs inside it.

Developing inside Flatpak is useful, as it prevents malicious code from touching the host filesystem. It is also helpful to avoid polluting the host filesystem with dependencies, given that they are installed inside the sandbox and are not available out of it - similar to what Python's virtual environments do.

I want to submit a Flatpak'd package for git-lfs to Flathub, the major Flatpak package repository, so that it would be easy to install in this scenario - just running `flatpak install com.visualstudio.code.tool.git-lfs`. They require [app submissions to be either done by the developers](https://github.com/flathub/flathub/wiki/App-Submission#theres-an-app-that-id-like-to-see-on-flathub-but-im-not-the-developer), or be acquainted by them.

I prepared everything, as I am using it for my own installation, but I would like it published to the Flathub repository. If you allow me to do it, I would submit the script myself, and would become the owner/maintainer of the package in Flathub. If the maintainers of git-lfs would rather control and maintain it, feel free to [copy my branch](https://github.com/ranisalt/flathub/tree/com.visualstudio.code.tool.git-lfs) and [submit a pull request](https://github.com/flathub/flathub/wiki/App-Submission#how-to-submit-an-app).

Thanks for your time!

**Comment by bk2204** [comment]
Hey,

Sorry for not getting back to you sooner.  I think it's best to use Git LFS from the same source as one uses Git, wherever you get it from.

I don't think we want to be responsible for shipping a Flatpak or officially sanction others to do so at the moment, just like we don't want to be responsible for shipping snaps or other containers.  Because of the nature of containerized tooling, it's very difficult to make sure all the dependencies are kept up to date so the container environment , and Git LFS doesn't release often enough to ship secure containers of software.

We can consider this at some point in the future, but for now, I don't think we want to go forward with this approach.

**Comment by ranisalt** [comment]
Thanks for your response!

> I think it's best to use Git LFS from the same source as one uses Git, wherever you get it from.

Not sure if I follow you here, but `git` is bundled in the Visual Studio Code package from Flathub, so creating a package for it will come from the same source as `git` in this context. It is akin to installing both `git` and `git-lfs` from apt/dnf/pacman.

> we don't want to be responsible for shipping snaps or other containers

I'm proposing that it is made available inside the Visual Studio Code container, _not_ that it become shipped as a standalone tool; this is because host binaries are not available inside the sandbox, so to have `git-lfs` installed currently the user has to install the whole `golang` SDK, and then install with `go install github.com/git-lfs/git-lfs`, and it is not available outside the sandbox either.

> Because of the nature of containerized tooling, it's very difficult to make sure all the dependencies are kept up to date so the container environment , and Git LFS doesn't release often enough to ship secure containers of software.

The idea is to make the package need as little maintenance as possible. It is technically possible to build it from the main branch instead of using version tags, if you prefer. Or, every once in a while, rebuild it so that it picks up updated compatible versions of dependencies, without intervention. How does it look?

The git-lfs organization does not need to deal with that, Flathub allows unofficial packages. Visual Studio Code is an example itself, it's not packaged by Microsoft. If you are OK with that, nothing else is needed :)

**Comment by bk2204** [comment]
I don't think it's a problem if Git LFS is shipped inside the Visual Studio Code container along with Git.  Git LFS is open source and can be distributed by anyone under the terms of the license.  As long as you're honest that it's not an official package by the project, that's fine.

None of the core team, to my knowledge, uses VS Code, so we're not super knowledgeable when it comes to how that's distributed.  However, we know there are several other similar tools that distribute Git LFS, and that's cool.

As for the version, I think it's typically better to distribute released versions rather than the main branch.  Those see better testing and it's easier for users to read the changelog and discover notable changes that way.

**Comment by lu9dce** [comment]
sh in vcode
------
echo $PATH
/app/bin:/app/bin:/app/bin:/usr/bin:/home/eduardo/.var/app/com.visualstudio.code/data/node_modules/bin
-------------------

create dir 
/home/eduardo/.var/app/com.visualstudio.code/data/node_modules/bin
and copy git-lfs
------------

**Comment by bk2204** [comment]
Since I think this question has been answered, I'm closing this.
