### ISSUE TITLE
Limitations page in the wiki dissapears

### ISSUE THREAD

**Issue by usinelogicielle** [git-lfs/git-lfs#5302]
**Describe the bug**
The page https://github.com/git-lfs/git-lfs/wiki/Limitations doesn't exist anymore.
We can it in the README https://github.com/git-lfs/git-lfs/blob/main/README.md 
In the summary of wiki page : https://github.com/git-lfs/git-lfs/wiki 
The summary of the WIKI doesn't corresponding to the actual pages of the wiki.

**Expected behavior**
The page will be here. Or delete the link from the other document

**Comment by bk2204** [comment]
Thanks for the report.  It looks like someone deleted this page, so I've restored it.

**Comment by chrisd8088** [comment]
Thanks for restoring the page again, @maloewe-ona!  I hope we don't have to restrict the wiki editing privileges because we do see a slow but steady flow of contributions from folks like yourself, but we'll try to keep a closer eye on the pages in the wiki.  I've set up a notification using the wiki's RSS [feed](https://github.com/git-lfs/git-lfs/wiki.atom) and so I should be alerted when changes are made in the future, and anyone else is welcome to do the same.

Thanks again for the help!
