### ISSUE TITLE
Too many concurrent connections during download

### ISSUE THREAD

**Issue by MichaelFrommberger** [git-lfs/git-lfs#5303]
**Describe the bug**
It seems that git-lfs uses more concurrent downloads than configured in `lfs.concurrenttransfers`. 

In the attached wireshark statistics you can see that there are about 34 https connections to the artifactory server (139.23.11.233) which provides the git-lfs repository. `lfs.concurrenttransfers` was configured with 8.

![2023-03-04 00_13_07-Wireshark · Conversations · lfs_test cap](https://user-images.githubusercontent.com/17617977/222854627-08cbd69b-0793-47f0-9c82-c10897fc023b.png)

Furthermore when dumping the traffic to/from server there can be seen some sort of 'empty' connections which only perform the TLS handshake and afterwards close the connection from the client side. These connections seem to be additional connections to the number of connections configured in `lfs.concurrenttransfers`. Attached you can such an connection whitout payload.

![2023-03-04 00_15_30-lfs_test cap](https://user-images.githubusercontent.com/17617977/222855281-fe347f64-3257-4525-bb27-3a1314ddf4bb.png)

In general all data seem to be retrieved correctly during fetching. No error in the logs (even with `GIT_TRACE=1 GIT_TRANSFER_TRACE=1 GIT_CURL_VERBOSE=1`) can be seen. This issue only popped up during monitoring of the artifactory server. It has been recognized that there are many connections without retrieving any data, only doing the TLS handshake.

**To Reproduce**
1. Clone a repository using https protocol.
2. Sniff the communication between the lfs server and your client
3. Check the number of connections
4. Check if there are any connections with handshake only which have been closed by the lfs client ("Encrypted Alert" message). 

The issue can be seen here regardless of the size and the count of lfs tracked files (60 - 4000 files).

**Expected behavior**
Only as much as configured connections will be made by the lfs-client.

**System environment**
Gentoo Linux in WSL2 under Win10 21H2  / Ubuntu 22.04 in Docker Container

**Output of `git lfs env`**
git-lfs/3.2.0 (GitHub; linux amd64; go 1.20.1)
git version 2.39.2

Endpoint=https://139.23.11.233/artifactory/test-lfs (auth=none)
  SSH=139.23.11.233:/artifactory/test-lfs
LocalWorkingDir=/home/frommi/source/LFS_TEST
LocalGitDir=/home/frommi/source/LFS_TEST/.git
LocalGitStorageDir=/home/frommi/source/LFS_TEST/.git
LocalMediaDir=/home/frommi/source/LFS_TEST/.git/lfs/objects
LocalReferenceDirs=
TempDir=/home/frommi/source/LFS_TEST/.git/lfs/tmp
ConcurrentTransfers=8
TusTransfers=false
BasicTransfersOnly=false
SkipDownloadErrors=false
FetchRecentAlways=false
FetchRecentRefsDays=7
FetchRecentCommitsDays=0
FetchRecentRefsIncludeRemotes=true
PruneOffsetDays=3
PruneVerifyRemoteAlways=false
PruneRemoteName=origin
LfsStorageDir=/home/frommi/source/LFS_TEST/.git/lfs
AccessDownload=none
AccessUpload=none
DownloadTransfers=basic,lfs-standalone-file,ssh
UploadTransfers=basic,lfs-standalone-file,ssh
GIT_EXEC_PATH=/usr/libexec/git-core
git config filter.lfs.process = "git-lfs filter-process"
git config filter.lfs.smudge = "git-lfs smudge -- %f"
git config filter.lfs.clean = "git-lfs clean -- %f"

**Additional context**
The LFS server is an Artifactory server.

**Comment by bk2204** [comment]
Hey,

The `lfs.concurrenttransfers` flag is designed to limit the number of actual transferred objects at a time and doesn't affect things like batch requests, so it is possible that there are more connections in flight at a time.

My guess, though, that what's happening in your case is that there's some sort of proxy (which could be an antivirus or firewall on your Windows machine, a proxy, or a TLS MITM device) that's terminating the connections abruptly without allowing data to be sent.  We use Go's HTTP library, which should not open TLS connections unless there's a need for them, and my test clone against GitHub shows that there's no spurious connections being created.  It could also be that for whatever reason your Artifactory server is dropping connections, but I think that's substantially less likely, since the encrypted alert that's presumably causing the connection to hang up looks like it's coming from your machine.

**Comment by bk2204** [comment]
I think this answers the problem reported, and as such, I'm going to close it, but if you don't agree, let us know and we can reopen it.
