### ISSUE TITLE
repo size increase 5x after git lfs migrate

### ISSUE THREAD

**Issue by erickeller** [git-lfs/git-lfs#5305]
**Describe the issue**

a bare clone of the repository including +4000 binaries weight 4.1 GB. Once migrated with git lfs migrate the same repository suddenly wights + 20 GB. Could someone explain the rationale of this behavior?

```
du -sh foo.git.bare
4.1G	foo.git.bare
```

```
export BINARY_INCLUDES="*.7z,*.acd,*.bcc_obj,*.bin,*.bmp,*.bpl,*.chm,*.dat,*.db,*.dcp,*.dcr,*.DCR,*.dcu,*.~ddp,*.ddp,*.dfm,*.dll,*.dls,*.doc,*.docx,*.e32,*.eap,*.emf,*.exe,*.gdb,*.gif,*.hlp,*.ico,*.identcache,*.jpg,*.JPG,*.KIT,*.lrs,*.msg,*.obj,*.otares,*.pcr,*.pdf,*.pdn,*.png,*.res,*.RES,*.skn,*.swf,*.tdf,*.TDF,*.thmx,*.tmp,*.trc,*.tst,*.vsd,*.xls,*.xlsx,*.zip"

git lfs migrate import --everything --include="${BINARY_INCLUDES}"
git lfs fsck
git gc --aggressive
```

```
du -sh foo.git.bare
20G	foo.git.bare
```

**System environment**

Linux ubuntu 20.04

**Output of `git lfs env`**

```
git-lfs/3.3.0 (GitHub; linux amd64; go 1.19.3)
git version 2.25.1

Endpoint=https://bitbucket.example.com//foo.git/info/lfs (auth=none)
  SSH=git@bitbucket.example.com://foo.git
LocalWorkingDir=
LocalGitDir=/home/ubuntu/foo.git.bare-lfs
LocalGitStorageDir=/home/ubuntu/foo.git.bare-lfs
LocalMediaDir=/home/ubuntu/foo.git.bare-lfs/lfs/objects
LocalReferenceDirs=
TempDir=/home/ubuntu/foo.git.bare-lfs/lfs/tmp
ConcurrentTransfers=8
TusTransfers=false
BasicTransfersOnly=false
SkipDownloadErrors=false
FetchRecentAlways=false
FetchRecentRefsDays=7
FetchRecentCommitsDays=0
FetchRecentRefsIncludeRemotes=true
PruneOffsetDays=3
PruneVerifyRemoteAlways=false
PruneRemoteName=origin
LfsStorageDir=/home/ubuntu/foo.git.bare-lfs/lfs
AccessDownload=none
AccessUpload=none
DownloadTransfers=basic,lfs-standalone-file,ssh
UploadTransfers=basic,lfs-standalone-file,ssh
GIT_EXEC_PATH=/usr/lib/git-core
git config filter.lfs.process = "git-lfs filter-process"
git config filter.lfs.smudge = "git-lfs smudge -- %f"
git config filter.lfs.clean = "git-lfs clean -- %f"
```

**Additional context**

I would have expected that git lfs increase the overall size of the repository that much.

Anything I can do to debug this?

**Comment by bk2204** [comment]
Hey,

Yeah, let me explain how this works.  When you store data in Git, it's deltified and compressed.  Thus, if you have lots of highly redundant data, Git can store it very efficiently.  However, if you have things that are already compressed, like many images or compressed archives, they won't compress; instead, they'll actually expand.

Git LFS doesn't store data compressed or deltified, so if your data is highly compressible, it will be larger.  However, it makes up for this by not storing most of it locally.  Once it's pushed to the server, you can do `git lfs prune` (possibly with the `--force` option if you want), which will delete the large files from your copy and leave them only on the server, which usually ends up making the repository smaller locally because only the binaries you need to check out the current HEAD are downloaded.

Does that answer your question?

**Comment by erickeller** [comment]
Yes this makes sense thank you for the clarification. An additional question: does lfs store only one copy of the object at any point of time on the server referring to the unique hash of this binary object? Or would there be multiple copy of those depending on path / banches? E.g. one pointer to a file can be used several time referring to the same data without duplication ok the backend side?

**Comment by bk2204** [comment]
Git LFS will preserve the history of the object.  However, like Git, it identifies objects by their hash (in the case of Git LFS, a SHA-256 hash), so if the same file contents are used multiple times (via multiple paths or an unchanged file over multiple revisions, or both), then only one copy of those file contents will be stored and it will be referenced multiple times.  If the file contents change, Git LFS will store a new object.

**Comment by bk2204** [comment]
I think this answers the question, so I'm going to close this issue.  If you still have more questions, please let us know, and we can reopen.
