### ISSUE TITLE
"Encountered 1 file(s) that may not have been copied correctly on Windows" on Ubuntu 20.04.5 LTS

### ISSUE THREAD

**Issue by harrywang** [git-lfs/git-lfs#5310]
Ubuntu 20.04.5 LTS

Had this error when doing `git add .` with large files.

Only files > 4G.

I found https://github.com/git-lfs/git-lfs/issues/4744 but that's for Windows and I ran into this error on Linux.

Any help? Thanks!

**Comment by harrywang** [comment]
I forgot to do `git lfs install`, which solved the problem.

**Comment by harrywang** [comment]
for a file of 7.7G this error shows up again. then I could `git add .` and `git commit -am 'msg'` but when `git push`,

**Comment by bk2204** [comment]
Hey,

This message occurs to let you know that this file (and all files larger than 4 GiB) will be broken on Windows if you use an older version of Git.  If you're using Git 2.34 or newer, this message won't be printed, and you can disable it by setting `lfs.largefilewarning` to false if you don't want to see it or don't use Windows.

It doesn't indicate that anything is wrong unless you're using an older version of Git on Windows.

**Comment by myers** [comment]
```
git config --global lfs.largefilewarning false
```

**Comment by treya-lin** [comment]
> 

Thanks for the explanation. Good to know that we can ignore this warning on linux. I was worried every time I saw it. 

By the way I am working with git version 2.34.1 but this warning is still printed.

**Comment by bk2204** [comment]
If you're using Git 2.34 or newer, you also require Git LFS 3.1.0 in order to recognize that Git 2.34 or newer shouldn't print the message.  If you still see the issue after using Git LFS 3.1.0 or newer and Git 2.34 or newer, please open a new issue, filling out the issue template and including the output of `git config -l`.

**Comment by MonolithFoundation** [comment]
But got error when push ref main:: Error in git rev-list --stdin --objects --not --remotes=hf --: exit status 128 fatal: bad object 43edff100e5f01893461be9d3123cc2b5790ade9

**Comment by bk2204** [comment]
I believe this has been fixed in a newer version, but this is a completely separate issue.  If you've tried the latest version and can still reproduce the problem, please open a new issue, filling out the issue templates and including reproduction steps.  Please refrain from commenting on closed issues, as mentioned in the contributing documentation.
