### ISSUE TITLE
MIssing Bytes When Downloading Pointers

### ISSUE THREAD

**Issue by PhiKuz** [git-lfs/git-lfs#5318]
**Describe the issue**
I am trying to download the LFS pointers to memory using Unreal Engine so I can make POST request to the LFS API. Everything in the system works except for the fact that all text files I try to download from Git, pointers included, do not download completely. They continue downloading until they stop at an arbitrary point, cutting of the last parts of the documents.  Since the pointers are small I have been able to just add an arbitrary number to expected GetContentLength from the response, but this is not ideal.
To be clear, this does not appear to be an issue with files coming from LFS; this is an issue with files being pulled directly from Github. If there is a better place to post this please let me know!

**System environment**
Unreal Engine 5.1
Using VaRest for JSON calls
Using a modified Runtime File Downloader for downloading files/pointers

**Comment by bk2204** [comment]
You would do a shallow clone using the command-line Git, with something like `git clone --depth=1 https://github.com/git/git.git`.  Note that if you have the Git LFS binary installed, this will also automatically download the LFS objects, which would avoid you needing to make the requests yourself.

If you can't use the Git binary, you could use libgit2 to perform the clone, but it doesn't invoke Git LFS, so you'd need to handle that yourself, which it sounds like you're already doing.

If you scrape the GitHub raw file endpoints, you'll end up getting rate limited and served a 429 for all requests to github.com for the next 30 minutes, so that's definitely not a good approach to take.  However, discussion of that approach is generally off-topic for this issue tracker.

**Comment by bk2204** [comment]
I think I've answered this, so I'm going to close it, but if you still have questions, please let us know and we can reopen.
