### ISSUE TITLE
Youtube link is dead

### ISSUE THREAD

**Issue by KyrieLii** [git-lfs/git-lfs#5320]
**Describe the issue**

> https://github.com/git-lfs/git-lfs/blob/main/docs/README.md

This link is dead : https://www.youtube.com/watch?v=uLR1RNqJ1Mw

Anyone know the correct one ? 👀

**Comment by chrisd8088** [comment]
Thanks for the report!  From the Internet Archive I see this was a video on the "GitHub Training & Guides" channel, which appears to have been removed recently.  I'm trying to find out if anyone at GitHub has more details.

**Comment by chrisd8088** [comment]
GitHub's developer relations team reports that the channel has been decommissioned, and since the video was made many years ago, a master copy no longer exists.  Watching the Internet Archive [version](https://web.archive.org/web/20160120103000/https://www.youtube.com/watch?v=uLR1RNqJ1Mw), I see that while the command-line portions of the video are still accurate, the various screen captures are quite out of date.

I'll make a request to GitHub's team to see if they can produce a new video at some point, but until then, we'll just have to remove the link.  Thanks for reporting the problem!
