### ISSUE TITLE
Listing locked files under a specific path

### ISSUE THREAD

**Issue by lucadirocco** [git-lfs/git-lfs#5359]
**Describe the issue**
I have a gitlab repository with several thousands configurations files, arranged in a tree structure reflecting network topology, vendors and resource types.
When a reosurce is to be instantiated, I fetch one of the candidate configuration files from the suitable path in gitlab, and I use 
git lfs lock feature (via lfs apis) to lock the file in order to mark it as "in use".
When looking for a "not-in-use" configuration file, I need to check the locked files under a specific path (the api seems only to get all the locked files in the whole repository, which could produce a huge result in my case). 
Any way to list locked files under a specific directory only?

**System environment**
AlmaLinux release 8.7

**Output of `git lfs env`**
I don't use git lfs plugin, just apis.

**Comment by chrisd8088** [comment]
Hey, thanks for the question.  From the [documentation](https://github.com/git-lfs/git-lfs/blob/8e96b5d5d84095d1c0dd0c550d8fdf2c8c5c6456/docs/api/locking.md#list-locks) for the locking API, the lock listing request may provide a `path` parameter which the server should use to restrict the set of locks it returns, e.g.:
```
GET https://<lfs-server>/locks?path=<path to match>&...
```

However, when I test that with GitHub (not GitLab), it seems as though their server implementation only returns exact matches for the `path` argument, rather than using it for a prefix match, as is implied should be done by the API documentation.  GitLab's implementation may have the same limitation, or not -- you would have to experiment a bit to see, I think.

**Comment by lucadirocco** [comment]
Thank you for your reply, Chris. 

I'm using the `path` parameter indeed, but (with gitlab) the server only accepts an exact file path.
If I specify a directory path or a file path with wildcard, the result is empty

From my tests, it looks like there are only two options:
1) Testing if a specific file (i.e. with exact path) is locked
2) Listing all the locked files in the repository

I also noticed something weird about 2): although the api accepts a `refspec` parameter (e.g. `refspec=refs%2Fheads%2Fmain`), the result includes also locked files from other branches (even if those files do not exist in the specified branch)

I don't know if such behavior is faulty or specific to gitlab. 
I must admit I'm getting very confused.

**Comment by lucadirocco** [comment]
According to [API Doc](https://github.com/git-lfs/git-lfs/blob/8e96b5d5d84095d1c0dd0c550d8fdf2c8c5c6456/docs/api/locking.md#list-locks):  
refspec - Optional fully qualified server refspec from which to search for locks.

**Comment by lucadirocco** [comment]
I don't know how lock feature Is supposed to work.
This is how it works in mu tests with both Github and Gitlab:

/Git LFS locks are scoped at the repository level, not at branch level.

**Comment by bk2204** [comment]
An implementation is welcome to implement branch-scoped locks.  However, I'm not aware of any that do, since it makes things like pull requests very difficult, since a PR affects both the base branch and the branch containing the commits.

Implementations are also welcome to reject locks for files not in the history.  However, again, I'm not aware of any that do.

The documentation for the API doesn't specify that wildcards are allowed.  If you specified `*`, then that would match the literal path `*`, which is valid on Unix, but not on Windows.

Since I think that answers the question, I'm going to close this.
