### ISSUE TITLE
lfs unlock is not sending `refspec`

### ISSUE THREAD

**Issue by TimePrinciple** [git-lfs/git-lfs#5372]
**Describe the bug**
The subcommand `git lfs unlock <filename>` is not sending `refspec`, instead, it only sends `path` used to identify the lock. But without `refspec`, how does the server know which group of locks to search for? Is there any way to make this command sends `refspec` along with `path`?

**Expected behavior**
`git lfs unlock <filename>` sends `refspec` along with `path`.

![image](https://github.com/git-lfs/git-lfs/assets/52569592/a5409e12-7727-412e-959c-2038133c0d6a)

**Comment by chrisd8088** [comment]
Hey, I'm sorry you're having trouble.  You didn't fill in the issue template, so without the output of `git lfs env` I don't know what version of Git LFS you're using.

With any recent version, you should see the `refspec` sent by the client if you use `GIT_CURL_VERBOSE=1` to set that environment variable before a `git lfs unlock` command.  The Git LFS client has [supported](https://github.com/git-lfs/git-lfs/blob/1efc16b424ea1f88bfbcfe81a667bcfb2cdba3d5/docs/api/locking.md#delete-lock) a `ref` parameter since v2.4.0.

Here's an example from my v3.3.0 client:
```
$ git lfs lock 123.bin
Locked 123.bin

$ git lfs locks
123.bin	chrisd8088	ID:3093198

$ GIT_CURL_VERBOSE=1 git lfs unlock 123.bin 
...
> POST /chrisd8088/.../info/lfs/locks/3093198/unlock HTTP/1.1
...
{"force":false,"ref":{"name":"refs/heads/main"}}20:01:45.161935 trace git-lfs: HTTP: 200
...
< HTTP/2.0 200 OK
...
Unlocked 123.bin
```

In your case, your screenshot suggests you have a proxy in place of some kind which is perhaps interfering with your HTTP request, so you may want to investigate that.
