### ISSUE TITLE
Git LFS PUT 501 LFS: Not Implemented

### ISSUE THREAD

**Issue by huangmin-ms** [git-lfs/git-lfs#5373]
**Describe the issue**
Error when we were trying to do git push to a github repo.

```
18:25:46.628418 trace git-lfs: tq: sending batch of size 2
18:25:46.628418 trace git-lfs: api: batch 2 files
18:25:46.628418 trace git-lfs: HTTP: POST https://github.com/xxx
18:25:46.773962 trace git-lfs: http: decompressed gzipped response
18:25:46.777574 trace git-lfs: HTTP: 200
18:25:46.778116 trace git-lfs: tq: starting transfer adapter "basic"
18:25:46.778657 trace git-lfs: HTTP: PUT https://github-cloud.s3.amazonaws.com/alambic/media/180603904/91/d1/91d15a37b734545a23905a324e64ceaa8ccf6dd696f88cbd4853cb10ad212b8e
18:25:46.820766 trace git-lfs: HTTP: PUT https://github-cloud.s3.amazonaws.com/alambic/media/180603904/62/6d/626de29e471f2f5bcd7086a6ca8cba022855639d0c52f6f402267d19b4a6cb0d
18:25:46.870056 trace git-lfs: HTTP: 501
18:25:46.870710 trace git-lfs: tq: retrying object 626de29e471f2f5bcd7086a6ca8cba022855639d0c52f6f402267d19b4a6cb0d: LFS: Not Implemented: https://github-cloud.s3.amazonaws.com/alambic/media/180603904/62/6d/626de29e471f2f5bcd7086a6ca8cba022855639d0c52f6f402267d19b4a6cb0d?actor_id=20963210&key_id=0&repo_id=138970676
```

**System environment**
```
os
Microsoft Windows Server 2022
git version
git version 2.39.1.windows.1
git lfs version
git-lfs/3.3.0 (GitHub; windows amd64; go 1.19.3; git 77deabdf)
```

**Output of `Git.exe config --global --list`**
```
Git.exe config --global --list
2023-05-22T18:25:06.1633140Z filter.lfs.clean=git-lfs clean -- %f filter.lfs.smudge=git-lfs smudge -- %f filter.lfs.process=git-lfs filter-process filter.lfs.required=true credential.helper=store
2023-05-22T18:25:06.1649986Z filter.lfs.clean=git-lfs clean -- %f
2023-05-22T18:25:06.1650826Z filter.lfs.smudge=git-lfs smudge -- %f
2023-05-22T18:25:06.1651501Z filter.lfs.process=git-lfs filter-process
2023-05-22T18:25:06.1652026Z filter.lfs.required=true
2023-05-22T18:25:06.1652652Z credential.helper=store
```

**Comment by chrisd8088** [comment]
Hey, I'm sorry you're having trouble.  It looks like you are using GitHub for your Git LFS hosting, and having problems connecting to them, so you may need to contact their Support team, as this project is just for the open-source Git LFS client.

However, before you do that, can you try running with `GIT_TRACE=1 GIT_TRANSFER_TRACE=1 GIT_CURL_VERBOSE=1` and reporting the output?

I would also suggest taking a look at whether you have any proxy or non-default antivirus, firewall, or monitoring software is in use.  On Windows in particular, those can interfere with the operation of the Git LFS client, and we generally recommend only using the default Windows Defender.

**Comment by chrisd8088** [comment]
As we haven't heard anything more regarding this issue, and it appears to not be related to the Git LFS client, I'm going to close the issue.

**Comment by bk2204** [comment]
That configuration isn't correct, which is why this is happening.  You're sending two `Authorization` headers, which is not valid according to the RFC, and so the server is refusing to serve you.  This is why `http.extraHeader` shouldn't be used for authentication.

You should use a credential helper instead, and [the Git FAQ explains](https://git-scm.com/docs/gitfaq#http-credentials-environment) how to use a one-off credential helper from the command line.  That will provide the required credentials without causing authentication problems.

**Comment by huangmin-ms** [comment]
@bk2204 

I don't have `http.extraHeader` in my local git config and from the trace.log (which I attached in my Github support ticket)
I can see there's only one `Authorization` header was sent for lfs endpoint:
```
19:24:36.242497 trace git-lfs: HTTP: POST https://github.com/MicrosoftDocs/powershell-reference-assemblies.git/info/lfs/locks/verify
> POST /MicrosoftDocs/powershell-reference-assemblies.git/info/lfs/locks/verify HTTP/1.1
> Host: github.com
> Accept: application/vnd.git-lfs+json
> Authorization: Basic * * *
> Content-Length: 44
> Content-Type: application/vnd.git-lfs+json; charset=utf-8
> User-Agent: git-lfs/3.3.0 (GitHub; windows amd64; go 1.19.3; git 77deabdf)
```
There are two `Authorization` headers sent for AWS endpoint but I am not sure where the AWS4-HMAC-SHA256 header comes from.
```
19:24:37.463601 trace git-lfs: HTTP: PUT https://github-cloud.s3.amazonaws.com/alambic/media/180603904/e6/5b/e65b5df7a598***e62c518c51535b036f9465cd6f8b785084a4fe64246f0541dbf
> PUT /alambic/media/180603904/e6/5b/e65b5df7a598fe62c518c51535b0***5cd6f8b785084a4fe64246f0541dbf?actor_id=20963210&key_id=0&repo_id=138970676 HTTP/1.1
> Host: github-cloud.s3.amazonaws.com
> Authorization: AWS4-HMAC-SHA256 Credential=AKIAIM**,SignedHeaders=host;x-amz-content-sha256;x-amz-date,Signature=78504ffd94b1cb9783c***
> Authorization: Basic * * * * *
> Content-Length: 91091678
> Content-Type: text/plain; charset=utf-8
> User-Agent: git-lfs/3.3.0 (GitHub; windows amd64; go 1.19.3; git 77deabdf)
> X-Amz-Content-Sha256: e65b5df7a598fe62c518c51535b036f9465cd6f8b785084a4fe64246f0541dbf
> X-Amz-Date: 20230619T112437Z
```

**Comment by huangmin-ms** [comment]
> Perhaps the `AWS4-HMAC-SHA256` comes from `objects[*].actions.download.header.Authorization` in the batch API response as shown in https://github.com/git-lfs/git-lfs/blob/main/docs/api/basic-transfers.md.

Yes, thanks for pointing out, the AWS endpoint and auth header are both from the response of the batch API. So the question is why the basic auth is also added in AWS request? is it expected?

**Comment by huangmin-ms** [comment]
> Multiple `Authorization` header fields in the same request are disallowed by https://www.rfc-editor.org/rfc/rfc7230#section-3.2.2 ("A sender MUST NOT generate") and https://www.rfc-editor.org/rfc/rfc7235#section-4.2 (not comma-delimited, unlike `WWW-Authenticate`). Given this, I think it would make sense if the Git LFS client discarded all user-configured `Authorization` header fields when the batch API also specifies an `Authorization` header field.

I found a similar issue https://github.com/actions/checkout/issues/415, not sure if related.

**Comment by bk2204** [comment]
The Git LFS client doesn't override headers because Git doesn't override headers in this case.  Git will accept and specify multiple headers that are of the same type in `http.extraheader`, even if in general that's not allowed (because sometimes it is allowed, like with cookies).  There are also probably some systems which require that behaviour, and in general, we try to implement whatever Git does.  The only reason this doesn't come up with Git is that Git doesn't attempt to authenticate until it receives a 401, so it never acquires credentials from elsewhere if `http.extraheader` is set.

The solution here really is to use a credential manager, and Git LFS will not attempt to fill a credential in that case.  That's also much more secure.

It's my intention to send a series to the Git list relatively soon which will deprecate the use of `http.extraheader` for authentication in favour of more robust credential helper support and warn when `http.extraheader` is used for authentication.

**Comment by bk2204** [comment]
> Does Git even have the case where it gets headers from one server and sends them to another?

No, it doesn't have that case.  However, it does have the case where you can specify multiple headers even though it's not allowed and it sends them anyway, therefore so do we.

Note that the Git LFS protocol is not limited to sending `Authorization` headers; one could send other headers that _are_ allowed as duplicates and `http.extraheader` would need to be correctly honoured there, and we don't want a giant list of which headers are allowed to be that way and which aren't.

> Does "more robust credential helper support" mean that, if the HTTP `WWW-Authenticate` header field from the server lists `Basic` and `Bearer` as supported authentication schemes, then the credential helper would be able to choose which of those is used?

Yes, it does.  That's an explicit goal of my work.  I may even do a follow-up series to allow three-legged authentication such a NTLM or Kerberos to be pushed into the credential helper if it's not already handled automatically by my current series.

**Comment by huangmin-ms** [comment]
> does this mean that git lfs client is not support `-c http.extraheader="Authorizartion xxx` because whenever you set this extraheader, it will end up with two authorization headers just like my case.
> 
> I have gone through a few issues in this repo and found people was succeed using this extraheader in command line, so just curious, why sometimes it works and sometimes it doesn't.

does this mean that git lfs client is not support -c http.extraheader="Authorizartion xxx because whenever you set this extraheader, it will end up with two authorization headers just like my case.

I have gone through a few issues in this repo and found people was succeed using this extraheader in command line, so just curious, why sometimes it works and sometimes it doesn't.

**Comment by huangmin-ms** [comment]
> The Git LFS client doesn't override headers because Git doesn't override headers in this case. Git will accept and specify multiple headers that are of the same type in `http.extraheader`, even if in general that's not allowed (because sometimes it is allowed, like with cookies). There are also probably some systems which require that behaviour, and in general, we try to implement whatever Git does. The only reason this doesn't come up with Git is that Git doesn't attempt to authenticate until it receives a 401, so it never acquires credentials from elsewhere if `http.extraheader` is set.
> 
> The solution here really is to use a credential manager, and Git LFS will not attempt to fill a credential in that case. That's also much more secure.
> 
> It's my intention to send a series to the Git list relatively soon which will deprecate the use of `http.extraheader` for authentication in favour of more robust credential helper support and warn when `http.extraheader` is used for authentication.

does this mean that git lfs client is not support -c http.extraheader="Authorizartion xxx because whenever you set this extraheader, it will end up with two authorization headers just like my case.

I have gone through a few issues in this repo and found people was succeed using this extraheader in command line, so just curious, why sometimes it works and sometimes it doesn't.

**Comment by bk2204** [comment]
No, Git LFS does indeed support that.  However, if your LFS server (like GitHub's) adds additional Authorization headers, then it will result in non-conforming HTTP, and the server will probably reject it, as it did here.  However, some LFS servers (like the LFS test server) do use the client-provided authentication for objects, and in such a case it will work as expected.  It depends on the server implementation.

Using `http.extraHeader` says, "Always add this header, no matter what."  Since you told Git LFS to do that, it followed your directions, presuming you knew what you were doing.  It's an expert feature, both in Git and Git LFS.

However, that being said, it is not recommended (by us or by Git upstream) to use `http.extraheader` for authentication because it often results in unexpected behaviour and that's not a secure way to pass or store credentials.  You should use a credential helper instead, which will work correctly.  As I mentioned above, [the Git FAQ outlines how to pass credentials from the environment using an ad-hoc credential helper](https://git-scm.com/docs/gitfaq#http-credentials-environment), which provides all the functionality you've requested with Basic authentication with none of the problems you've seen here.

**Comment by bk2204** [comment]
If Git receives a successful credential, it will ask all the configured credential helpers to store it.  Obviously, the credential helper I've mentioned and you have listened above won't persist anything.  However, if you have other credential helpers installed, they could.  To avoid using any other credential helpers that may be configured, you can first set `credential.helper` to the empty string, which clears the list, and only then set the one above, so that it's the only one configured.

So on the command line, it would look like this: `git -c credential.helper= -c credential.helper='!f() { echo username=$accountName; echo password=$accessToken; };f' clone URL`.  The same thing can be done in a config file.

This is all documented in the `gitcredentials(7)` manual page.

**Comment by huangmin-ms** [comment]
> If Git receives a successful credential, it will ask all the configured credential helpers to store it. Obviously, the credential helper I've mentioned and you have listened above won't persist anything. However, if you have other credential helpers installed, they could. To avoid using any other credential helpers that may be configured, you can first set `credential.helper` to the empty string, which clears the list, and only then set the one above, so that it's the only one configured.
> 
> So on the command line, it would look like this: `git -c credential.helper= -c credential.helper='!f() { echo username=$accountName; echo password=$accessToken; };f' clone URL`. The same thing can be done in a config file.
> 
> This is all documented in the `gitcredentials(7)` manual page.

Thanks, before I config this credential helper, I did unset all other credential helpers. then I think it should be fine in terms of security.
For example:
```
git config --global --unset-all credential.helper
git config --system --unset-all credential.helper
```
