### ISSUE TITLE
clone github chromium repo to private repo got rejected because file size limit of 100 MB

### ISSUE THREAD

**Issue by 0x0a0d** [git-lfs/git-lfs#5374]
I'm planing to create a fork of chromium but I still wanna keep my forked up to date with chromium/chromium. So I'm trying to clone the chromium repo to a private repo on Github. The initial clone works fine, but when I try to push around 10,000 commits to my private git, I encounter the following error:

```
remote: error: See https://gh.io/lfs for more information.
remote: error: File chrome/tools/test/reference_build/chrome/chrome_dll.pdb is 101.65 MB; this exceeds GitHub's file size limit of 100.00 MB
remote: error: GH001: Large files detected. You may want to try Git Large File Storage - https://git-lfs.github.com.
```

I have tried:
- Using import repo on Github but failed
- `partial-push`: By only push ~1000 commits once
- `lfs`: try something like `git lfs install`, `git lfs track '*.pdb'`, `git lfs track 'chrome/tools/test/reference_build/chrome/chrome_dll.pdb'`

But the problem persists. I'm not sure what else I need to do to fix this issue when pushing such a large number of commits from the Chromium repo to my own private git.

Could someone please advise me on how to resolve this error? Any help would be greatly appreciated.

**Comment by chrisd8088** [comment]
Hey, I'm sorry you're having trouble.  It sounds like you want to use GitHub as your Git hosting service, so you may want to contact their Support team to ask for help, as this project is just for the open-source Git LFS client.

That said, one particular issue you are clearly running into is that because you're working with a pre-existing Git repository and history, you will need to rewrite it to use Git LFS.  The `git lfs track '*.pdb'` command only creates a `.gitattributes` entry for any new commits with files matching `*.pdb`.  Since you already have those files in your private copy of the repository, you'll need to run a command like `git lfs migrate import --include='*.pdb' --everything` to rewrite the entire history of the repository.

There's a FAQ [entry](https://github.com/git-lfs/git-lfs/blob/1efc16b424ea1f88bfbcfe81a667bcfb2cdba3d5/docs/man/git-lfs-faq.adoc) about this (see "I’m using Git LFS, but I still see GitHub’s large file error. How do I fix this?"), and the `git-lfs-migrate(1)` manual [page](https://github.com/git-lfs/git-lfs/blob/1efc16b424ea1f88bfbcfe81a667bcfb2cdba3d5/docs/man/git-lfs-migrate.adoc) has details on running that command.  With a repository the size of the Chromium one, I would anticipate it may take a long time, and you may also want to run `git lfs migrate info --everything` first to get a sense of what files exist in the whole Git history that are above GitHub's hosting limit.

Good luck!
