### ISSUE TITLE
Get "509: certificate signed by unknown authority" on valid certificate.

### ISSUE THREAD

**Issue by BobKerns** [git-lfs/git-lfs#5398]
**Describe the bug**
I have been getting the error "509: certificate signed by unknown authority" on a valid certificate (not self-signed).

After some sleuthing, including building from source, and then making `appendRootCAsForHostFromPlatform` always return `nil`, I determined it was related to adding certificates from the System keychain.

Removing all expired and self-signed certs from the keychain then resolved the issue. Fortunately, I don't think I need any of the removed certs, but that is not guaranteed to be the case.

A little further experimentation revealed that the killer cert was a self-signed cert with a CN matching the hostname of my new non-self-signed cert. This seems to be a requirement for it to fail.

Note that the self-signed cert was *trusted*, and it was in the System keychain precisely to make it be trusted. But it has the opposite effect on git-lfs, even though it should have no bearing on validating the actual cert.

**To Reproduce**

1. Choose a git-lfs server with a valid cert, configure to use it.
2. Create a CA
3. Create a self-signed server cert in that CA
4. Import it into the System keychain
5. [optional] mark the cert as trusted.
6. git lfs lock <path> now gives "X509: certificate signed by unknown authority".

**Expected behavior**
Certs in the System chain should not break otherwise good certs.

**System environment**
MacOS Ventura

**Output of `git lfs env`**
```
git-lfs/3.3.0 (GitHub; darwin amd64; go 1.19.4)
git version 2.41.0

Endpoint=https://kabocha.4kows.com/lfs/4kows/quicken (auth=basic)
LocalWorkingDir=/Users/rwk/p/quicken
LocalGitDir=/Users/rwk/p/quicken/.git
LocalGitStorageDir=/Users/rwk/p/quicken/.git
LocalMediaDir=/Users/rwk/p/quicken/.git/lfs/objects
LocalReferenceDirs=
TempDir=/Users/rwk/p/quicken/.git/lfs/tmp
ConcurrentTransfers=8
TusTransfers=false
BasicTransfersOnly=false
SkipDownloadErrors=false
FetchRecentAlways=false
FetchRecentRefsDays=7
FetchRecentCommitsDays=0
FetchRecentRefsIncludeRemotes=true
PruneOffsetDays=3
PruneVerifyRemoteAlways=false
PruneRemoteName=origin
LfsStorageDir=/Users/rwk/p/quicken/.git/lfs
AccessDownload=basic
AccessUpload=basic
DownloadTransfers=basic,lfs-standalone-file,ssh
UploadTransfers=basic,lfs-standalone-file,ssh
git config filter.lfs.process = "git-lfs filter-process"
git config filter.lfs.smudge = "git-lfs smudge -- %f"
git config filter.lfs.clean = "git-lfs clean -- %f"
```

**Additional context**

Similar results happen with `curl` using a Lets Encrypt-provided cert, if the supplied `fullchain.pem` file is used. This file includes an expired root cert (DST Root CA X3), that causes some software (openssl-based) to fail, despite the presence of a trusted root.

After resolving that issue, git-lfs still did not work.

The validity check should only depend on the existence of a chain of valid certs up to a trusted root. The existence of expired certs outside that path should not invalidate the cert.

The error message is true, but the logic behind it is backwards. A cert should fail because it is _not_ signed by a _known_ authority, and signatures by unknown authorities should be discarded, not cause a validation failure.

**Comment by chrisd8088** [comment]
Hey, I'm sorry you're having trouble.  From what I can see, this message doesn't come from Git LFS per se; it's output by the Go language's `crypto/x509` package, which Git LFS uses.

So far as I can tell, the message [comes](https://github.com/golang/go/blob/e45202f2154839f713b603fd6e5f8a8ad8d527e0/src/crypto/x509/verify.go#L141) from an error type which is only [generated](https://github.com/golang/go/blob/e45202f2154839f713b603fd6e5f8a8ad8d527e0/src/crypto/x509/verify.go#L942-L954) in one place, and specifically only if no valid chains are [found](https://github.com/golang/go/blob/e45202f2154839f713b603fd6e5f8a8ad8d527e0/src/crypto/x509/verify.go#L952-L953) at all.

From your description, I confess I don't quite see how that would end up being the case, but clearly there must have been no valid chains (self-signed or otherwise) in order to produce this error.

I'm going to close this issue, because I don't think there's anything we can do in the Git LFS project to make this better (or worse!)

If you'd like to pursue it further, I might suggest crafting a small Go language program which uses the `crypto/x509` package and demonstrates the problem, and then reporting it to the Go project team.

Thanks for the report, and good luck!
