### ISSUE TITLE
`package is in a very bad inconsistent state` when attempting to install on ARM architecture

### ISSUE THREAD

**Issue by BBBmau** [git-lfs/git-lfs#5434]
**Describe the bug**
Getting the following output when attempting to install through `sudo apt-get install git-lfs`
```
mau@mau-virtual-machine:/bin$ sudo apt-get install git-lfs
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
git-lfs is already the newest version (3.3.0).
0 upgraded, 0 newly installed, 0 to remove and 9 not upgraded.
1 not fully installed or removed.
Need to get 0 B/6,765 kB of archives.
After this operation, 0 B of additional disk space will be used.
Do you want to continue? [Y/n] y
dpkg: error processing package git-lfs (--configure):
 package is in a very bad inconsistent state; you should
 reinstall it before attempting configuration
Errors were encountered while processing:
 git-lfs
E: Sub-process /usr/bin/dpkg returned an error code (1)
```

**To Reproduce**
1. Follow Linux install instructions

**Expected behavior**
Should install successfully

**System environment**
perform this on VM Ware Fusion ARM architecture | Ubuntu 20.04

**Output of `git lfs env`**
n/a

**Additional context**
running this on Apple Silicon

**Comment by bk2204** [comment]
Hey,

I assume you're attempting to install on an arm64 machine, not an arm (32-bit machine).  If so, I don't believe we've ever shipped a package for Ubuntu 20.04 on arm64.  We build exactly one non-amd64 package, which is always an arm64 package for the latest Debian version, and we started doing that when Debian 11 was current.  That's because GitHub Actions doesn't offer any non-amd64 OSes and it's very expensive to cross-build, so there's only one package.

As a consequence, we would have uploaded this package for Debian 11 and Ubuntu 22.04 and later, but not Ubuntu 20.04.  Thus, I don't think this can ever work, and you are probably trying and failing to install an amd64 package, which is why you get that message.

As of Git LFS 3.4.0, which is planned for release on Wednesday, we'll only build for Debian 12 and newer, and there won't be any supported Ubuntu releases at all.  I'd recommend upgrading to the latest Debian version if it's important to you to have a Debian package, or you can download one of the pre-built binaries from the tarballs on the release page.
