### ISSUE TITLE
fatal: clean filter 'lfs' failed' 'exit status 128'

### ISSUE THREAD

**Issue by hgkjshegfskef** [git-lfs/git-lfs#5478]
**Describe the issue**
I have a repository cloned to NTFS drive where I store ebooks (in PDF and EPUB), together with Calibre database. I have been using git-lfs for a long time on this repo. Today I discovered that Calibre doesn't "see" the books anymore, but more interestingly, I am faced with an error when running `git status` and `git lfs status`:

```
❯ GIT_TRACE=1 git lfs status
16:07:23.757723 git.c:748               trace: exec: git-lfs status
16:07:23.757776 run-command.c:661       trace: run_command: git-lfs status
16:07:23.763250 trace git-lfs: exec: git 'version'
16:07:23.765208 trace git-lfs: exec: git '-c' 'filter.lfs.smudge=' '-c' 'filter.lfs.clean=' '-c' 'filter.lfs.process=' '-c' 'filter.lfs.required=false' 'rev-parse' '--git-dir' '--show-toplevel'
16:07:23.767526 trace git-lfs: exec: git 'config' '--includes' '--local' 'lfs.repositoryformatversion'
16:07:23.768738 trace git-lfs: exec: git '-c' 'filter.lfs.smudge=' '-c' 'filter.lfs.clean=' '-c' 'filter.lfs.process=' '-c' 'filter.lfs.required=false' 'rev-parse' 'HEAD' '--symbolic-full-name' 'HEAD'
16:07:23.770914 trace git-lfs: exec: git '-c' 'filter.lfs.smudge=' '-c' 'filter.lfs.clean=' '-c' 'filter.lfs.process=' '-c' 'filter.lfs.required=false' 'rev-parse' '--git-common-dir'
16:07:23.772494 trace git-lfs: exec: git 'config' '--includes' '-l'
16:07:23.773877 trace git-lfs: exec: git 'rev-parse' '--is-bare-repository'
16:07:23.775300 trace git-lfs: exec: git 'config' '--includes' '-l' '--blob' ':.lfsconfig'
16:07:23.777292 trace git-lfs: exec: git 'config' '--includes' '-l' '--blob' 'HEAD:.lfsconfig'
On branch master
16:07:23.779246 trace git-lfs: exec: git '-c' 'filter.lfs.smudge=' '-c' 'filter.lfs.clean=' '-c' 'filter.lfs.process=' '-c' 'filter.lfs.required=false' 'rev-parse' 'HEAD' '--symbolic-full-name' 'HEAD'
16:07:23.780730 trace git-lfs: exec: git 'config' '--includes' 'branch.master.remote'
16:07:23.781986 trace git-lfs: exec: git 'config' '--includes' 'branch.master.merge'
16:07:23.783194 trace git-lfs: exec: git '-c' 'filter.lfs.smudge=' '-c' 'filter.lfs.clean=' '-c' 'filter.lfs.process=' '-c' 'filter.lfs.required=false' 'rev-parse' 'refs/remotes/origin/master' '--symbolic-full-name' 'refs/remotes/origin/master'
Objects to be pushed to origin/master:

16:07:23.784672 trace git-lfs: run_command: git rev-list --objects --do-walk --stdin --
16:07:23.784679 trace git-lfs: exec: git '-c' 'filter.lfs.smudge=' '-c' 'filter.lfs.clean=' '-c' 'filter.lfs.process=' '-c' 'filter.lfs.required=false' 'rev-list' '--objects' '--do-walk' '--stdin' '--'
16:07:23.784901 trace git-lfs: exec: git '-c' 'filter.lfs.smudge=' '-c' 'filter.lfs.clean=' '-c' 'filter.lfs.process=' '-c' 'filter.lfs.required=false' 'cat-file' '--batch-check'
16:07:23.785159 trace git-lfs: exec: git '-c' 'filter.lfs.smudge=' '-c' 'filter.lfs.clean=' '-c' 'filter.lfs.process=' '-c' 'filter.lfs.required=false' 'rev-parse' '--git-common-dir'
16:07:23.786775 trace git-lfs: exec: git 'update-index' '-q' '--refresh'
Failed to run `git update-index`: error running /usr/libexec/git-core/git 'update-index' '-q' '--refresh': 'Files don't match:
/run/media/ave/Music/books/.git/lfs/objects/f2/60/f260c83a3c3497e4ac84b93b37a42871c4eede7229c8b4ea7bf77998b9d4c510
/run/media/ave/Music/books/.git/lfs/tmp/449202652
error: external filter 'git-lfs filter-process' failed
fatal: Randal E. Bryant/Computer Systems_ A Programmer's Perspective (374)/metadata.opf: clean filter 'lfs' failed' 'exit status 128'
```

The `.opf` file is an XML that is lfs-tracked:

```
❯ grep opf .gitattributes
*.opf filter=lfs diff=lfs merge=lfs -text
```

I don't understand what the error means and I am not sure how to proceed. Perhaps, some time ago I changed the metadata file, but that should lead to this kind of corruption.

**System environment**

OS: Fedora Linux 37

**Output of `git lfs env`**
```
❯ git lfs env
git-lfs/3.3.0 (GitHub; linux amd64; go 1.19.6)
git version 2.41.0

Endpoint=https://gitlab.com/username/books.git/info/lfs (auth=none)
  SSH=git@gitlab.com:username/books.git
LocalWorkingDir=/run/media/ave/Music/books
LocalGitDir=/run/media/ave/Music/books/.git
LocalGitStorageDir=/run/media/ave/Music/books/.git
LocalMediaDir=/run/media/ave/Music/books/.git/lfs/objects
LocalReferenceDirs=
TempDir=/run/media/ave/Music/books/.git/lfs/tmp
ConcurrentTransfers=8
TusTransfers=false
BasicTransfersOnly=false
SkipDownloadErrors=false
FetchRecentAlways=false
FetchRecentRefsDays=7
FetchRecentCommitsDays=0
FetchRecentRefsIncludeRemotes=true
PruneOffsetDays=3
PruneVerifyRemoteAlways=false
PruneRemoteName=origin
LfsStorageDir=/run/media/ave/Music/books/.git/lfs
AccessDownload=none
AccessUpload=none
DownloadTransfers=basic,lfs-standalone-file,ssh
UploadTransfers=basic,lfs-standalone-file,ssh
GIT_EXEC_PATH=/usr/libexec/git-core
git config filter.lfs.process = "git-lfs filter-process"
git config filter.lfs.smudge = "git-lfs smudge -- %f"
git config filter.lfs.clean = "git-lfs clean -- %f"
```

**Comment by bk2204** [comment]
Hey,

This error message means that the file in your working tree and the file with the same hash in the LFS storage are of different sizes.  Since a cryptographic hash is supposed to uniquely identify a file and, with a secure hash like SHA-256, finding any two different messages that produce the same hash should be functionally impossible, this usually indicates some sort of corruption.

Could you first try `git lfs fsck` to verify that your repository is in a good state and include the output here?  Can you also try `git hash-object -t blob "Randal E. Bryant/Computer Systems_ A Programmer's Perspective (374)/metadata.opf"` afterwards and see what that says, and if it fixes the problem for you?

**Comment by hgkjshegfskef** [comment]
Thanks for the reply. fsck said everything is fine, but hash-object gave the same error.

I guess I'll just give up on some changes and re-clone the repo.

**Comment by bk2204** [comment]
Hey,

I don't think you should need to give up on those changes.  Can you try moving `/run/media/ave/Music/books/.git/lfs/objects/f2/60/f260c83a3c3497e4ac84b93b37a42871c4eede7229c8b4ea7bf77998b9d4c510` to contain a `.bak` extension and then try `git status` again?  That should clean the file again, and if `git lfs fsck` says everything's okay, you should be good to go.  If it complains about that file, you can move it back by deleting the `.bak` extension.

Just to make sure, besides this being an NTFS drive, is there any sort of unusual configuration involved?  For example, is your repository using a cloud syncing service such as Dropbox or OneDrive, perhaps, or any sort of automated process running that might change files?  We know, for example, that cloud syncing services tend to break repositories, which is why I asked.

**Comment by hgkjshegfskef** [comment]
>  Can you try moving /run/media/ave/Music/books/.git/lfs/objects/f2/60/f260c83a3c3497e4ac84b93b37a42871c4eede7229c8b4ea7bf77998b9d4c510 to contain a .bak extension and then try git status again? That should clean the file again, and if git lfs fsck says everything's okay, you should be good to go.

Thanks a lot, that helped. I should finally dedicate some time to study git internals...

> Just to make sure, besides this being an NTFS drive, is there any sort of unusual configuration involved? For example, is your repository using a cloud syncing service such as Dropbox or OneDrive, perhaps, or any sort of automated process running that might change files?

No, just a gitlab repo. The HDD might be dying as well, though.
