### ISSUE TITLE
Can I use `git lfs ls-files` to list files on remote for a specific SHA without downloading any of the files?

### ISSUE THREAD

**Issue by redsun82** [git-lfs/git-lfs#5519]
**Describe the issue**
I'd like to know what files are available for download on a specific git checkout where no LFS files were downloaded yet.

**Additional context**
I've done some trials and as far as I could test:
* `git lfs ls-files` or the equivalent `git lfs ls-files HEAD` on a working copy were LFS files have not been fetched yet will show nothing
* `git lfs ls-files <remote>/<branch>` (for example `git lfs ls-files origin/main`) will list files on the remote, but only works for named references

I couldn't understand how to show a list of files from a remote related to a specific git commit. What I'm thinking of as a use case, is to skip downloading LFS files on CI (that takes quite long for our repo) but instruct our build system to fetch files lazily when they are listed as a dependency of what we want to build. That would be much easier and less boiler-platey if given such a checkout without LFS files we could know exactly what files are available without downloading them.

So if there is a way to achieve this with `ls-files` or by any other means, I'd be happy to hear it 🙂

**Comment by bk2204** [comment]
Hey,

The commands you've specified (using `git lfs ls-files`) don't actually list anything on the remote.  Instead, they look at the given Git commit and find all of the LFS pointer files referenced by the files in that commit.  The Git LFS protocol doesn't offer a way to list the files on a remote repository if you don't already know their sizes and object IDs, and it's specifically designed to operate independently from the contents of the repository (so people can use independent servers).

However, if you have a revision available locally, you can use a syntax like `git lfs ls-files -l 16f09066000e3328fb2d5c54beb55fc25c1af15c` to list the contents of that revision.  If the files are not checked out, they'll be listed with a `-` instead of a `*`, but that shouldn't be a problem.

Without the revision available locally, though, I'm afraid that there isn't a way to find out the information you want.
