### ISSUE TITLE
Syncing Lockstate

### ISSUE THREAD

**Issue by soma-web** [git-lfs/git-lfs#5540]
**Describe the issue**
If a file is forced unlocked from another person or unlocked from a differrent PC with the same credentials the file remains writable on the pc where it was originally locked.

Steps to reproduce:
1. Clone Repo with lockable git-lfs files 2 times into 2 different directories
2. lock a lockable file in repo 1 => file turns writable in repo 1
3. force unlock file in 2nd repository 
4. in first repository try git checkout or some other methods => file remains writable, no chance to sync the lockable state with git-lfs tools

**Comment by chrisd8088** [comment]
Hey, I'm sorry you're having trouble.  I think this issue was been discussed before in #3246, and in https://github.com/git-lfs/git-lfs/issues/3246#issuecomment-644356190 there's the suggestion to use `git checkout .` (note the dot character in the command).

That does reset the file permissions to make them read-only again in the example I developed from your description, starting with a new empty repository on GitHub:

```
$ git clone https://github.com/.../lock-test lock-test
$ cd lock-test
$ git lfs track --lockable '*.bin'
$ echo foo >foo.bin
$ git add foo.bin .gitattributes
$ git commit -m init
$ git push origin main
$ cd ..

$ git clone https://github.com/chrisd8088/git-lfs-lock lock-test-1
$ git clone https://github.com/chrisd8088/git-lfs-lock lock-test-2

$ ls -l lock-test-1/foo.bin 
-r--r--r-- ... lock-test-1/foo.bin
$ ls -l lock-test-2/foo.bin 
-r--r--r-- ... lock-test-2/foo.bin

$ cd lock-test-1
$ git lfs lock foo.bin
$ ls -l foo.bin 
-rw-r--r-- ... foo.bin

$ cd ../lock-test-2
$ git lfs locks
foo.bin ...
$ git lfs unlock foo.bin
Unlocked foo.bin
$ git lfs locks
$ ls -l foo.bin
-r--r--r-- ... foo.bin

$ cd ../lock-test-1
$ ls -l foo.bin
-rw-r--r-- ... foo.bin

$ git lfs locks --verify
$ ls -l foo.bin
-rw-r--r-- ... foo.bin

$ git checkout .
Updated 1 path from the index
$ ls -l foo.bin
-r--r--r-- ... foo.bin
```

In the first clone of the repository, where the lock was taken and the file was made writeable, after the file has been unlocked from the second clone, running `git lfs locks --verify` does not reset the file permissions on the file to be read-only.  This is a bit unfortunate, but the command would have to check all files because there's no longer any information available from the Git LFS server as to which locks no longer exist.

But, running `git checkout .` does reset the file to be read-only, because it checks all the files in the working tree.

I'm going to close this issue, therefore, but please let us know if that doesn't work for you.

**Comment by soma-web** [comment]
Thanks, for pointing me to --verify
