### ISSUE TITLE
E: The package libcudnn8 needs to be reinstalled, but I can't find an archive for it.

### ISSUE THREAD

**Issue by banbsyip** [git-lfs/git-lfs#5568]
when i run the sudo apt-get install git-lfs,there is someting wrong.
<img width="1136" alt="image" src="https://github.com/git-lfs/git-lfs/assets/18277076/d711f089-bc41-4ae6-9bb2-d7b6d759b943">
(gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.4) ) #110-UbuntuSMP Tue Jul 18 12:55:35 UTC 2017

**Comment by bk2204** [comment]
Hey,

This isn't a Git LFS issue.  The problem is that you have a package on your system, `libcudnn8` (which looks like part of an nVidia library) that is improperly installed.  On Debian and Ubuntu, the package manager won't allow you install new packages, such as `git-lfs`, when there's a broken package, so you'll need to fix the broken package first.  You can try `sudo apt-get install -f` and `dpkg -C`, which will print some diagnostics, and once `sudo apt-get install -f` completes successfully, you should be able to install Git LFS.

I'll also note that Ubuntu 16.04 isn't receiving regular security updates, so we aren't shipping up-to-date Git LFS packages for it anymore.  (We build the packages for Ubuntu on Debian, and the corresponding Debian version is now so old that it can't be installed any longer.)  You can still install older Git LFS packages for the moment, but we won't be shipping newer versions there.  The oldest Ubuntu for which we are shipping packages is 20.04 (focal).
