### ISSUE TITLE
Ability to configure client to ignore "that should have been pointers, but weren't"

### ISSUE THREAD

**Issue by axkibe** [git-lfs/git-lfs#5587]
**Describe the issue**

This is another take or view on the issue of binaries having gotten in the repository that shouldn't. I'm fully aware how one would fix it etc. but here is the issue.

For the average user (for whom LFS should be an opaque thing) it is super confusing, they pull and suddendly have files marked as changed albeit they did not touch them, combine this with a traditional edit conflict, they'll throw up their hands and tell me git is just unusable..

What I want: A global config option that make LFS ignore these cases for them if the files are binaries, and honestly a dicussion that IMO this generally should be a warning and needing a command to fix it, instead of autoconverting the files to pointers on pull..

In detail my setup:
* all people I admin I install and configure LFS for them, I also install a filter list by default of all common binary types.. so generally they really shouldn't ever notice that LFS is working under the hood.
* Sometimes an external person commits to a shared repository and despite my instructions sometimes they do not have LFS properly installed, if this means they dont see the binaries it would be their problem, but...
* their commit puts in the binaries into the sytem..
* the someone just pulls and gets super confused about "why are the files marked as changed"

**Comment by axkibe** [comment]
Just to clarify, if the binary is already in the repository history the damage is already done, might just leave it there (until someone migrat/fixes the whole history)

**Comment by axkibe** [comment]
I'll side-step  by adding following pre-receive hook on all repos.

```sh
#!/bin/dash
while read oldsha newsha refname; do
        output=$(/usr/bin/git-lfs fsck --pointers $newsha)
        if [ $? -ne 0 ]; then
                echo
                echo $output
                echo
                echo "sorry, you need to install git-lfs, please"
                echo "then run:"
                echo "   git lfs migrate import"
                echo "and try to push again, thank you"
                return 1
        fi
done
```

**Comment by bk2204** [comment]
Hey,

While I agree that it would be nice to have some way to ignore this, in general the problem here is Git.  If the binary in the history is a Git binary but it's marked for LFS, Git checks it out by passing it through Git LFS, which we pass through without changes.  When the files get their timestamps modified (for whatever reason), Git refreshes them, and when it cleans them, it invokes them through Git LFS, and they become pointers.  It's really Git that decides whether Git LFS should or should not be used, and Git LFS doesn't have a way to know whether, for example, `git reset --hard` is being used or whether the user is trying to fix the problem.

I'm open to ideas about how Git can handle this functionality better if you'd like to propose some, but note that in general Git doesn't accept functionality just for Git LFS, so we need a solution that is generally applicable and of general value.

**Comment by axkibe** [comment]
Okay I see, unfortunally I'm not deep into git internal, I though this was an user interface decission to be done this way.. which I would have questioned the wisdom of :)

Anyway, I found a workaround.
