### ISSUE TITLE
When I git clone a github library, it displays:

### ISSUE THREAD

**Issue by moHen-github** [git-lfs/git-lfs#5600]
Hello, I encountered some issues while using git lfs:
When I git clone a github library, it displays:
<img width="496" alt="微信图片_20231229003430" src="https://github.com/git-lfs/git-lfs/assets/142018482/52e8433e-c55c-4c30-9f3b-bfe1dc8943bf">
(The data directory in this library stores pointer files in the format of. csv)
The result of cloning is that none of the pointer files have been downloaded locally, and all other code files have been cloned.

Looking forward to your answer

**Comment by moHen-github** [comment]
And I haven't established a connection with the remote warehouse, it's just that I'm cloning someone else's library. So can I directly use the command: git fetch?

**Comment by chrisd8088** [comment]
Hey, I'm sorry you're having trouble.  You didn't provide the output of `git lfs env`, as our issue template requests, so it's difficult to guess what might be going on here.

However, the error message in your screenshot shows that the client is trying to contact the `https://gitclone.com/` server.  That's not a GitHub system, so you appear to have some kind of other service or proxy configured.  If you're trying to use GitHub, I would strongly suggest doing so directly, rather than through a proxy or other intermediary.

**Comment by moHen-github** [comment]
I'm sorry, maybe my expression was not very complete. If you need me to provide the output of git lfs env, the following is:
<img width="509" alt="image" src="https://github.com/git-lfs/git-lfs/assets/142018482/2f1fea82-4539-46a6-a657-5d1affeb5f02">
是的，gitclone应该是个代理，这是因为我在git clone遇到lfs对象时候，下载速度不到10KB，可能是我在中国的原因，所以使用了这个帮助加速。
期待您的再次回复。

**Comment by moHen-github** [comment]
I'm sorry, maybe my expression was not very complete. If you need me to provide the output of git lfs env, the following is:
<img width="473" alt="image" src="https://github.com/git-lfs/git-lfs/assets/142018482/4c98ece8-ee47-41c9-b4b1-96db36b0e8a2">

Yes, gitclone should be an agent because when I encountered an lfs object in git clone, the download speed was less than 10KB, which may be due to my location in China, so I used this help to speed up.

Looking forward to your reply again.

**Comment by chrisd8088** [comment]
OK, so you'd like to use the `gitclone.com` service; however, that's not one I'm familiar with, and I don't know if they support Git LFS.
You'd have to contact them to see if they provide that API.  And, note that GitHub itself will send your Git LFS object requests to AWS S3, so they might also have to proxy that.

If you can use GitHub directly, I think you'll have a better experience, but again, I don't know anything about `gitclone.com`.

But since this isn't an issue with the Git LFS client itself, I'm going to close this issue, as this project is just for the client.
