### ISSUE TITLE
Release v3.4.1 is missing in CHANGELOG.md

### ISSUE THREAD

**Issue by luzpaz** [git-lfs/git-lfs#5613]
**Describe the issue**

[v3.4.1](https://github.com/git-lfs/git-lfs/releases/tag/v3.4.1) is missing from [CHANGELOG.md](https://github.com/git-lfs/git-lfs/blob/main/CHANGELOG.md).

**Comment by chrisd8088** [comment]
Thanks for the question!  This is expected, because we don't put patch releases into the `main` branch's `CHANGELOG` until the next minor release, as [documented](https://github.com/git-lfs/git-lfs/blob/0fbd4fe41cf049846ce1347c81ebb231bca5ab76/docs/howto/release-git-lfs.md#building-a-release) in our how-to-release notes:

> If we are releasing a MAJOR or MINOR version and not a PATCH, and if the most recent non-PATCH release was followed by a series of one or more PATCH releases, include any changes listed in the CHANGELOG of that series' release branch in the new release's CHANGELOG.

The release is [noted](https://github.com/git-lfs/git-lfs/blob/release-3.4/CHANGELOG.md#341-13-dec-2023) in the `release-3.4` branch's version of `CHANGELOG.md`, and that (plus any subsequent 3.4.x patch releases) will be merged into the `main` version when 3.5.0 is released.

**Comment by luzpaz** [comment]
Understood. Makes it harder for downstream maintainers to track changes in an automated fashion though...afaict
