### ISSUE TITLE
Error: "stale NFS file handle" with lfs.storage

### ISSUE THREAD

**Issue by phoeniixhawk** [git-lfs/git-lfs#5676]
Hi,

I'm using lfs.storage mapped to an nfs share on Ubuntu 20.04.  I mount the nfs share like `sudo mount -t nfs4 -o nfsvers=4.1,rsize=1048576,wsize=1048576,hard,timeo=600,retrans=2,noresvport $NFS_SERVER:/ $NFS_MOUNT`.  This runs on 9 build machines that build the same repo, but different flavors of the code.

It works seamlessly, even running multiple commits that also launch 9 builds.  Once this share has been populated with the 8G of lfs data, everything is fine.  The problem I'm seeing is if the NFS share is empty, each of these builds will attempt to populate the lfs.storage directory for the first time, but some (1 or 2) of the builds fail with a stale NFS file handle.

```
git-lfs/3.4.1 (GitHub; linux amd64; go 1.21.1)
git version 2.43.2

$ git-lfs filter-process
Error downloading object: al/Utility.h (0947911): Smudge error: Error reading from media file: read /mnt/nfs/lfsstorage/objects/09/47/094791119587241f616d8f45d4176d6bf65f454dee6b66d261bb96e9e35f2e2b: stale NFS file handle: read /mnt/nfs/lfsstorage/objects/09/47/094791119587241f616d8f45d4176d6bf65f454dee6b66d261bb96e9e35f2e2b: stale NFS file handle

read /mnt/nfs/lfsstorage/objects/09/47/094791119587241f616d8f45d4176d6bf65f454dee6b66d261bb96e9e35f2e2b: stale NFS file handle
Error reading from media file: read /mnt/nfs/lfsstorage/objects/09/47/094791119587241f616d8f45d4176d6bf65f454dee6b66d261bb96e9e35f2e2b: stale NFS file handle
```

I believe this is an issue with the fact that the filesystem is not atomic, and two of the builds tried writing to the file at the same time, but I'm at a loss as to how to fix this.  Again, once all files are saved to the share, all builds, even 27 at a time, all run fine.

I also tried with the nfs option sync, but no luck.

Any ideas for options I'm missing or if it is even possible to let this run without errors?

**Comment by bk2204** [comment]
Hey,

In general, this error message comes from the operating system.  When a program, such as Git LFS, opens a file, it gets a file descriptor from the kernel.  The kernel on the client associates that file descriptor with a certain handle it gets from the NFS server to represent that file.  If the NFS server restarts or the connection gets dropped, then it's possible that the handle the client kernel has is not valid, and the client kernel returns this error.

I don't have a lot of general experience with NFS and so can't really speak to how to fix this, but since this is a generic operating system error message, you can search for “stale NFS file handle” or `ESTALE` and find potential solutions that might apply to your situation.

I agree this is likely related to renames, which we do require to be atomic.  Git LFS, like Git, does expect the file system to provide POSIX semantics (other than possible case insensitivity), so a successful call to `rename(2)` must reflect the change and preserve the old file descriptor, but it's my understanding that NFSv4 should be capable of providing those semantics in the general case (since it's allegedly POSIX compliant in at least some configurations), so at least in theory this should work.

If you can't get it working, you could try `sshfs`, which might work better, or try pre-populating the `lfs.storage` location before starting the build, as workarounds.

**Comment by phoeniixhawk** [comment]
Thanks BK for that great explanation and helping point me in a new direction.  I thought I'd take a chance and see if any lfs options could possibly help, but figured it is more likely something to do at the os level.  Hope this doesnt reopen issue.
