### ISSUE TITLE
how to accerlate git add when using git lfs

### ISSUE THREAD

**Issue by lucashaha** [git-lfs/git-lfs#5697]
i found git add jut write one file ,if i have 8 big files ,how can i write 8 files in lfs/objects or lfs/tmp at the same time 
![image](https://github.com/git-lfs/git-lfs/assets/99971678/92ecc491-d3ed-4d0f-a1bf-75c83e4f3292)

**Comment by bk2204** [comment]
Hey,

I'm not sure what your goal is.  `git add` will in fact write multiple files if you specify them on the command line, but I don't believe it's multithreaded.  If you want a multithreaded approach and you just need the files in the LFS storage (and not the Git index), you can pipe each file to `git lfs clean` and you can run several threads of that.  However, if you run `git add` on the file again, then it will be cleaned again, because without `git add` you haven't recorded the large files in the index.

If you tell us a bit more about what your goal is, we'd be able to better help you achieve it.

**Comment by lucashaha** [comment]
when I use git add，.git/lfs/ increase just one at one time,is it possible to add multiple file in .git/lfs/tmp and  .git/lfs/objects?
![image](https://github.com/git-lfs/git-lfs/assets/99971678/8ea9b099-1281-404a-bb43-00d42b2607e6)
![image](https://github.com/git-lfs/git-lfs/assets/99971678/4c8fc23e-a371-413f-bb4e-52165c436623)
![image](https://github.com/git-lfs/git-lfs/assets/99971678/f157b205-0177-46de-bb38-3621be6068ce)
![image](https://github.com/git-lfs/git-lfs/assets/99971678/216c85f0-6ae8-4524-b2d7-fa0ee49bbe05)
![image](https://github.com/git-lfs/git-lfs/assets/99971678/7cf31a24-87bc-466d-ac11-564bf7c1e5d2)

**Comment by bk2204** [comment]
As I mentioned above, it is possible to add them to the Git LFS storage by doing something like so (assuming the list of files is in the file `FILES` and you want to run 8 at a time):

```
$ cat FILES | xargs -P8 -L1 sh -c 'git lfs clean < "$0"'
```

However, that won't add them to the index, so if you want to actually commit those objects, you'll need to use `git add`, which isn't multithreaded.  You're welcome to request that parallel `git add` be implemented [on the Git mailing list](https://git-scm.com/community) or send a patch yourself.

It _is_ possible to combine `git lfs clean`, `git hash-object -t blob`, and then a single `git update-index` call to do it in parallel, but you'll need to do a decent amount of scripting to do that.
