### ISSUE TITLE
Git LFS efficiency in various usage scenarios

### ISSUE THREAD

**Issue by Kitiara** [git-lfs/git-lfs#5705]
Hello,

I'm curious about whether Git LFS efficiency is adversely affected in the following usage scenarios:

1. The impact of using a repository tracked with LFS for submodule purposes on the main repository. As the submodule size increases, the main repository's size will naturally grow, but what I'm particularly curious about here is the difference in efficiency between using an LFS repository for submodule purposes vs. creating a LFS directory.
2. Tracking small-sized binary files with LFS.
3. Tracking files, whether small or large in size, with LFS, whether they are binary or not (this could result from tracking an entire directory).

Thank you.

**Comment by bk2204** [comment]
As for 1, there's no difference in performance.  Git LFS will operate identically in either case.  The only benefit to using a submodule would be if you really didn't need the LFS objects in some case, so you could just avoid checking it out.  You could also just run with `GIT_LFS_SKIP_SMUDGE=1` as well, but it would be a little easier with the submodule.

For 2, there is a cost to uploading and downloading each file, with Git LFS because each file is a separate HTTPS request.  Git LFS uploads and downloads in parallel, which makes this less of an issue, but it's not free.  Similarly, there is a cost to smudge and clean files, but that is much smaller for small files.

Part of the situation is also how often those files are changed.  If they're changed very infrequently, then they'll be smudged, cleaned, uploaded, and downloaded very infrequently.  Git LFS does cache files locally, so if you have the files locally, then you won't need to upload or download, and they usually won't be checked out, either, so the cost is lower.  Similarly, files which are changed very frequently will be more expensive to deal with.

For 3, most of the answer is the same as 2.  Git LFS doesn't care about the contents of files; binary files are just as good or bad in every way as text files.  If you have more files, there will be a cost to hashing them when you do `git add` (or, if they're modified, when you do `git status`), which is dependent on size.  The cost to hashing is much lower with newer versions of Go on systems with SHA-NI instructions.

As a practical matter, we tend to recommend against tracking files in LFS that are likely to be usefully diffable or mergeable because Git LFS files are not by default diffable or mergeable.  Thus, for things like source code or text-based documentation (e.g., Markdown, AsciiDoc, DocBook), it may be beneficial to avoid tracking those files with Git LFS and instead split the files if they're very large, potentially using an include mechanism.  If you have giant files which are effectively blobs, just in text form, such as giant JSON blobs, then those may be a better choice for Git LFS.
