### ISSUE TITLE
Is `git lfs dedup` supported on btrfs on CentOS?

### ISSUE THREAD

**Issue by wangruohui** [git-lfs/git-lfs#5717]
**Describe the issue**

I am trying `git lfs debup` on a btrfs filesystem on CentOS. I think btrfs should support cow but it reports not support. I download the git lfs binary of version 3.5.1 from the release page and also tried the rpm package, but neither works. Is there other issue I missed?

**System environment**

```shell
$ uname -r 
3.10.0-693.el7.x86_64
$ cat /etc/redhat-release 
CentOS Linux release 7.4.1708 (Core) 
$ btrfs --version 
btrfs-progs v4.9.1
$ git --version 
git version 2.44.0
$ git lfs --version 
git-lfs/3.5.1 (GitHub; linux amd64; go 1.21.7; git e237bb3a)
$ df -T
Filesystem               Size  Used Avail Use% Mounted on
/dev/mapper/centos-data btrfs     166G  5.3G  159G   4% /data
$ cd /data/gpt2/
$ git lfs dedup
This system does not support de-duplication.
$ git config -l
user.name=****
user.email=****
credential.helper=cache
init.defaultbranch=main
filter.lfs.clean=git-lfs clean -- %f
filter.lfs.smudge=git-lfs smudge -- %f
filter.lfs.process=git-lfs filter-process
filter.lfs.required=true
core.repositoryformatversion=0
core.filemode=true
core.bare=false
core.logallrefupdates=true
remote.origin.url=https://huggingface.co/openai-community/gpt2
remote.origin.fetch=+refs/heads/*:refs/remotes/origin/*
branch.main.remote=origin
branch.main.merge=refs/heads/main
lfs.repositoryformatversion=0
```

**Output of `git lfs env`**
The output of running `git lfs env` as a code block.

```
$ git lfs env 
git-lfs/3.5.1 (GitHub; linux amd64; go 1.21.7; git e237bb3a)
git version 2.44.0

Endpoint=https://huggingface.co/openai-community/gpt2.git/info/lfs (auth=none)
LocalWorkingDir=/data/gpt2
LocalGitDir=/data/gpt2/.git
LocalGitStorageDir=/data/gpt2/.git
LocalMediaDir=/data/gpt2/.git/lfs/objects
LocalReferenceDirs=
TempDir=/data/gpt2/.git/lfs/tmp
ConcurrentTransfers=8
TusTransfers=false
BasicTransfersOnly=false
SkipDownloadErrors=false
FetchRecentAlways=false
FetchRecentRefsDays=7
FetchRecentCommitsDays=0
FetchRecentRefsIncludeRemotes=true
PruneOffsetDays=3
PruneVerifyRemoteAlways=false
PruneVerifyUnreachableAlways=false
PruneRemoteName=origin
LfsStorageDir=/data/gpt2/.git/lfs
AccessDownload=none
AccessUpload=none
DownloadTransfers=basic,lfs-standalone-file,ssh
UploadTransfers=basic,lfs-standalone-file,ssh
GIT_ASKPASS=****
GIT_EXEC_PATH=$HOME/.local/libexec/git-core
git config filter.lfs.process = "git-lfs filter-process"
git config filter.lfs.smudge = "git-lfs smudge -- %f"
git config filter.lfs.clean = "git-lfs clean -- %f"
```

**Additional context**
Any other relevant context about the problem here.

**Comment by Elhazinforever** [comment]
Contact WhatsApp

في جمعة، 19 أبريل، 2024 في 10:22 ص، كتب WRH ***@***.***>:

**Comment by bk2204** [comment]
Hey,

I don't have a CentOS 7 system to test and this is something I can't test in a container, but it does work for me on a test btrfs file system on Ubuntu 23.10.  My guess here is that your kernel is simply too old for this to work properly.  The manual page indicates that the ioctl operations we're using are first present in kernel 4.5, and before that they were private to btrfs.  There have been [others that have seen similar functionality fail to work](https://forums.centos.org/viewtopic.php?t=65217) on CentOS 7, so that's likely the cause.

While I can't guarantee it, if you upgrade to a newer version of your OS, you'll probably see things working.  Since CentOS 7 will soon be EOL, this seems like something you'd want to do anyway.

If you want to test, you can always use `git lfs dedup --test` to test whether the OS and file system you're working on support copy-on-write.
