### ISSUE TITLE
Unable to check out git lfs repo hosting large files in Nexus

### ISSUE THREAD

**Issue by thoefkens** [git-lfs/git-lfs#5798]
**Describe the issue**
We have a git repo configured to use lfs with Nexus as the storage.
When checking out the repo, some users get this error:

Error downloading object: Smudge error: Error downloading base/ tls: server sent certificate containing RSA key larger than 8192 bits

**System environment**
Occurs on both macOS and Windows. 

**Output of `git lfs env`**
```
git-lfs/3.5.1 (GitHub; darwin arm64; go 1.22.1)
git version 2.39.3 (Apple Git-146)

**Additional context**
The certificate of the Nexus server is a 4096-bit RSA certicate, which is added as a trusted certificate for git and the operating system.

**Comment by bk2204** [comment]
Hey,

Can you please use an up-to-date version of curl (such as the version in Homebrew) and run `curl -vX POST -d '{}' https://nexus2.muc.ct.accounts.intern/repository/gitlfs-hosted/info/lfs/objects/batch` and include the standard error as a code block or text file?  You'll probably get an error, and that's okay, but what I'm really interested in is the output like this (example from a server of mine):

```
* SSL connection using TLSv1.3 / TLS_AES_256_GCM_SHA384 / X25519 / RSASSA-PSS
* ALPN: server accepted h2
* Server certificate:
*  subject: CN=phthalo.io
*  start date: May  8 01:25:06 2024 GMT
*  expire date: Aug  6 01:25:05 2024 GMT
*  subjectAltName: host "phthalo.io" matched cert's "phthalo.io"
*  issuer: C=US; O=Let's Encrypt; CN=R3
*  SSL certificate verify ok.
*   Certificate level 0: Public key type RSA (3072/128 Bits/secBits), signed using sha256WithRSAEncryption
*   Certificate level 1: Public key type RSA (2048/112 Bits/secBits), signed using sha256WithRSAEncryption
*   Certificate level 2: Public key type RSA (4096/152 Bits/secBits), signed using sha256WithRSAEncryption
```

My guess is that there's a large certificate somewhere in the chain that's causing that.

**Comment by bk2204** [comment]
Well, if the end certificate is marked CA: false with a basic constraint, then it wouldn't be a valid self-signed certificate and Go (and OpenSSL) would look for a different trust path.  Since most certificates, even self-signed ones, are issued with that constraint, it's possible that's what's going on here.

**Comment by bk2204** [comment]
Yes, that seems like the problem.  This change was made in Go's TLS library to resolve https://github.com/golang/go/issues/61460, which is a DoS attack.  You can probably set `GODEBUG=tlsmaxrsasize=16384` in the environment to work around it, but any Go program you use, including Git LFS, will be subject to the DoS attack.

In general, if you need 192-bit security, then your RSA keys don't need to be larger than 7680 bits, or you can use an elliptic curve key of 384 bits, which will be much, much faster.  In fact, [NIST doesn't even recommend RSA keys that large](https://nvlpubs.nist.gov/nistpubs/SpecialPublications/NIST.SP.800-78-5.ipd.pdf) and instead recommends keys of 3072 bits or more (line 315), so typically a 4096-bit key should be totally sufficient even for a CA valid until 2039.

My recommendation would be to reissue the certificates with a smaller root key size, but if that's not possible, the environment variable should work.  We can't make any changes to Git LFS here because this is effectively a decision in a TLS library that we don't control (and, also, it happens to be one that I agree with in the general case).

**Comment by bk2204** [comment]
I mean, I think the existing error message ("tls: server sent certificate containing RSA key larger than 8192 bits") explains pretty clearly what the problem is: your certificate has a too-large key.  This is a situation where users are not following cryptographic best practices and advice from reputable organizations, and the advice would be to follow those recommendations.  This is literally the first time this issue has ever come up, so I don't think adding additional advice into the code is warranted.

As for the attack, I don't know the details of it, so I can't say anything about what the consequences might be.  It is in theory possible for a malicious server to send several large certificates (say, a 10-certificate long chain, each with 16384-bit keys) and cause several different trust root possibilities to be tried, so the expense could very well be substantial in attempting to verify the chain, including well beyond the legitimate chain.
