### ISSUE TITLE
Please do not use git-lfs, as its not optimum to use, it does not give warnings and deleted my entire directory of 1 gb dataset without any warning

### ISSUE THREAD

**Issue by RaghavMangla** [git-lfs/git-lfs#5802]
**Describe the issue**
A clear and concise description of why you wrote in today.

**System environment**
The version of your operating system, plus any relevant information about platform or configuration (e.g., container or CI usage, Cygwin, WSL, or non-Basic authentication).  If relevant, include the output of `git config -l` as a code block.

**Output of `git lfs env`**
The output of running `git lfs env` as a code block.

**Additional context**
Any other relevant context about the problem here.

**Comment by chrisd8088** [comment]
Hey, it sounds like you're having serious trouble, and I'm sorry for that.

If you fill out the issue template and provide the information requested (the output of `git lfs env` and `git config -l`, with any private data redacted) and of course a detailed description of what steps you performed and what happened, we might be able to provide some help.

You're also welcome to open a [discussion](https://github.com/git-lfs/git-lfs/discussions/) and provide more general feedback on what went wrong for you and your opinions about that.

However, if we don't hear from you in a few days, we'll close this issue, because as it stands it doesn't provide any information we can act on to help you or others in the future.
