### ISSUE TITLE
git lfs filee not showing after pushing

### ISSUE THREAD

**Issue by KoxyG** [git-lfs/git-lfs#5839]

**Comment by chrisd8088** [comment]
I'm sorry you're having trouble.

As I asked in https://github.com/git-lfs/git-lfs/discussions/5817#discussioncomment-10214476, please include the output of `git lfs env` when run inside your Git repository's working tree.  Please also state your operating system and version, and provide a description of the steps you took which led to the problem.  Otherwise, we can't help!

**Comment by chrisd8088** [comment]
Without further information, we can't help, so I'm going to close this.  If you need to, please re-open it and make sure to supply a full explanation of the problem and your environment.
