### ISSUE TITLE
git-lfs 3.5.1 has CVE-2024-24790 because it seems that it's using GO 1.21.7

### ISSUE THREAD

**Issue by daipok** [git-lfs/git-lfs#5851]
**Describe the issue**
We are just including git-lfs 3.5.1 as part of our jenkins agent (as a container) build, and using scanner it tells there's a CVE-2024-24790 issue with Go 1.21.7

**System environment**
Build docker image locally on an Ubuntu 22.04.4 LTS, and using jfrog 2.37.1

{
                  "component_id": "generic://sha256:aa7c4495760aac4c03b041ffeb970620bd24204303696afd8d662610ce027e7f/git-lfs",
                  "full_path": "usr/local/bin/git-lfs"
                },
                {
                  "component_id": "go://github.com/golang/go:1.21.7",
                  "full_path": "github.com/golang/go"
                }

**Output of `git lfs env`**
[jenkins@b5f5862a6c34 ~]$ git lfs env
git-lfs/3.5.1 (GitHub; linux amd64; go 1.21.7; git e237bb3a)
git version 2.43.5

LocalWorkingDir=
LocalGitDir=
LocalGitStorageDir=
LocalMediaDir=lfs/objects
LocalReferenceDirs=
TempDir=lfs/tmp
ConcurrentTransfers=8
TusTransfers=false
BasicTransfersOnly=false
SkipDownloadErrors=false
FetchRecentAlways=false
FetchRecentRefsDays=7
FetchRecentCommitsDays=0
FetchRecentRefsIncludeRemotes=true
PruneOffsetDays=3
PruneVerifyRemoteAlways=false
PruneVerifyUnreachableAlways=false
PruneRemoteName=origin
LfsStorageDir=lfs
AccessDownload=none
AccessUpload=none
DownloadTransfers=basic,lfs-standalone-file,ssh
UploadTransfers=basic,lfs-standalone-file,ssh
GIT_EXEC_PATH=/usr/libexec/git-core
git config filter.lfs.process = ""
git config filter.lfs.smudge = ""
git config filter.lfs.clean = ""

**Additional context**
Any other relevant context about the problem here.

**Comment by chrisd8088** [comment]
Hey, thanks for the report.  As it happens, so far as I'm aware this is not relevant to Git LFS (that is, it's a false positive) because the CVE in question pertains to the `net/netip` Go package (see https://pkg.go.dev/vuln/GO-2024-2887) and we don't use that package; instead, we still only use the older `net` package's `IP` structure and its functions.

Nevertheless, the next time we release a new version of Git LFS we'll use Go version 1.22 or the recently-released version 1.23.

**Comment by daipok** [comment]
> Hey, thanks for the report. As it happens, so far as I'm aware this is not relevant to Git LFS (that is, it's a false positive) because the CVE in question pertains to the `net/netip` Go package (see https://pkg.go.dev/vuln/GO-2024-2887) and we don't use that package; instead, we still only use the older `net` package's `IP` structure and its functions.
> 
> Nevertheless, the next time we release a new version of Git LFS we'll use Go version 1.22 or the recently-released version 1.23.

Is there a timeline of a new release that will be using Go 1.22/1.23?

**Comment by chrisd8088** [comment]
> Is there a timeline of a new release that will be using Go 1.22/1.23?

We don't have a fixed date at the moment, but I would like to have a new release complete by the end of November or in early December, if possible.

**Comment by itaysk** [comment]
Hello from team Trivy :) Just chiming in to say that Trivy now allows software maintainers (you) to publish vulnerability analysis about your software (packages, libraries, container images) so that vulnerability scanners will automatically suppress those irrelevant vulnerabilities for end users. You can read more here:
https://aquasecurity.github.io/trivy/latest/docs/supply-chain/vex/repo/#publishing-vex-documents
https://github.com/aquasecurity/vexhub
Feel free to reach me or the Trivy team if you have any issues/feedback.

**Comment by andreasgrob** [comment]
This seems to have been remediated in git-lfs 3.6.0.
