### ISSUE TITLE
files are not tracked by lfs after commit despite lfs status claiming they will be on commit

### ISSUE THREAD

**Issue by imbuedhope** [git-lfs/git-lfs#5904]
**Describe the bug**
When attempting to track all files that match the pattern for `**/foo` where `foo` is a directory `git-lfs status` lists files under the `foo` folder as part of lfs (after a `git add`) (i.e. it correctly matches for `**/foo/**`), however `git-lfs ls-files` does not list the files after a commit

**To Reproduce**

testing gitignore behavior with pattern (works as expected)
```
$ git init
Initialized empty Git repository in /tmp/lfs-bug/.git/
$ git lfs install
Updated git hooks.
Git LFS initialized.
$ echo "**/ignored" > .gitignore
$ mkdir -p 1/ignored
$ mkdir ignored
$ touch ignored/should-be-ignored
$ touch 1/ignored/should-also-be-ignored
$ git status
On branch master

No commits yet

Untracked files:
  (use "git add <file>..." to include in what will be committed)
	.gitignore

nothing added to commit but untracked files present (use "git add" to track)
```

testing git lfs behavior with the same pattern (fails)
```
$ git lfs track "**/lfs"
Tracking "**/lfs"
$ mkdir lfs
$ mkdir -p 1/lfs
$ touch lfs/should-be-in-lfs
$ touch 1/lfs/should-also-be-in-lfs
$ git add .
$ git lfs status

Objects to be committed:

	.gitattributes (Git: 6b1af79)
	.gitignore (Git: 0d22482)
	1/lfs/should-also-be-in-lfs (LFS: e3b0c44)
	lfs/should-be-in-lfs (LFS: e3b0c44)

Objects not staged for commit:


$ git lfs ls-files
$ git commit -m "test"
[master (root-commit) 3d8869c] test
 4 files changed, 3 insertions(+)
 create mode 100644 .gitattributes
 create mode 100644 .gitignore
 create mode 100644 1/lfs/should-also-be-in-lfs
 create mode 100644 lfs/should-be-in-lfs
$ git lfs ls-files
$ 
```

**Expected behavior**
when `git lfs track "**/foo"` is run it should result in matching with the "**/foo/**" pattern when the changes are committed like `git lfs status` suggests it will be

**System environment**
Ubuntu 22.04 LTS

**Output of `git lfs env`**
```
git-lfs/3.0.2 (GitHub; linux amd64; go 1.18.1)
git version 2.34.1

LocalWorkingDir=/tmp/lfs-bug
LocalGitDir=/tmp/lfs-bug/.git
LocalGitStorageDir=/tmp/lfs-bug/.git
LocalMediaDir=/tmp/lfs-bug/.git/lfs/objects
LocalReferenceDirs=
TempDir=/tmp/lfs-bug/.git/lfs/tmp
ConcurrentTransfers=8
TusTransfers=false
BasicTransfersOnly=false
SkipDownloadErrors=false
FetchRecentAlways=false
FetchRecentRefsDays=7
FetchRecentCommitsDays=0
FetchRecentRefsIncludeRemotes=true
PruneOffsetDays=3
PruneVerifyRemoteAlways=false
PruneRemoteName=origin
LfsStorageDir=/tmp/lfs-bug/.git/lfs
AccessDownload=none
AccessUpload=none
DownloadTransfers=basic,lfs-standalone-file,ssh
UploadTransfers=basic,lfs-standalone-file,ssh
GIT_EXEC_PATH=/usr/lib/git-core
git config filter.lfs.process = "git-lfs filter-process"
git config filter.lfs.smudge = "git-lfs smudge -- %f"
git config filter.lfs.clean = "git-lfs clean -- %f"
```

**Comment by chrisd8088** [comment]
Hey, thanks for the detailed report, and I'm sorry this is causing confusion.

I think that you may be reporting the same issue described in #5124 where zero-byte files staged in Git's index are reported as Git LFS objects by `git lfs status`.

There's also another slightly tricky issue at work here, which is that Git's rules for patterns in `.gitattributes` files are different from those of `.gitignore` files, in particular when it comes to how files are matched recursively within directories.  From the `.gitattributes` [documentation](https://git-scm.com/docs/gitattributes#_description):

> The rules by which the pattern matches paths are the same as in `.gitignore` files (see [gitignore[5]](https://git-scm.com/docs/gitignore)), with a few exceptions:
> - negative patterns are forbidden
> - patterns that match a directory do not recursively match paths inside that directory (so using the trailing-slash `path/` syntax is pointless in an attributes file; use `path/**` instead)

In other words, the pattern `**/lfs` will only match files named `lfs`, not everything in a directory named `lfs` found at any point in the directory hierarchy (except for zero-byte files, as noted above).  To match anything in a directory named `lfs`, you'd want to use `**/lfs/**`, I believe.

If we test that without using zero-byte files, I get:
```
$ git init test
$ cd test

$ git lfs track "**/lfs/**"
$ mkdir -p lfs nonlfs foo/lfs/bar foo/nonlfs/bar
$ echo baz >baz
$ for d in lfs nonlfs foo foo/lfs foo/nonlfs foo/lfs/bar foo/nonlfs/bar; do cp baz "$d/baz"; done
$ git add .

$ git lfs status

Objects to be committed:

	.gitattributes (Git: 2a47a42)
	baz (Git: bf07a7f)
	foo/baz (Git: bf07a7f)
	foo/lfs/bar/baz (LFS: bf07a7f)
	foo/lfs/baz (LFS: bf07a7f)
	foo/nonlfs/bar/baz (Git: bf07a7f)
	foo/nonlfs/baz (Git: bf07a7f)
	lfs/baz (LFS: bf07a7f)
	nonlfs/baz (Git: bf07a7f)

Objects not staged for commit:

$ git lfs status --json | jq .
{
  "files": {
    "foo/lfs/bar/baz": {
      "status": "A"
    },
    "foo/lfs/baz": {
      "status": "A"
    },
    "lfs/baz": {
      "status": "A"
    }
  }
}
```

(Note that for historical reasons, using the `--porcelain` option to `git lfs status` just returns all staged files of any type, so it's not very useful here.  See #3215 for some discussion of that issue.  But with the `--json` we only get files that are Git LFS objects.)

If I now add a zero-byte file anywhere, it will be listed as a (potential) Git LFS object, because zero-byte files are considered to be their own Git LFS pointers for various technical reasons.

```
$ touch nil lfs/nil nonlfs/nil
$ git add .
$ git lfs status --json | jq .
{
  "files": {
    "foo/lfs/bar/baz": {
      "status": "A"
    },
    "foo/lfs/baz": {
      "status": "A"
    },
    "lfs/baz": {
      "status": "A"
    },
    "lfs/nil": {
      "status": "A"
    },
    "nil": {
      "status": "A"
    },
    "nonlfs/nil": {
      "status": "A"
    }
  }
}
```

One suggestion from https://github.com/git-lfs/git-lfs/issues/5124#issuecomment-1256317209 was that we could enhance `git lfs status` to try to scan the `.gitattributes` files and determine whether any zero-byte files that were found also matched `filter=lfs` patterns or not.  That could work, and might be a behaviour which was toggled on or off with a new option.  However, no one has found time to work on an implementation, although if anyone wants to contribute a PR with one, we'd be very happy to take a look at it!

In the meantime, I'll probably close this issue in favour of #5124, unless there's another concern here beyond the zero-byte files and the specifics of recursively matching within directories using patterns in `.gitattributes` files.
