### ISSUE TITLE
git-lfs segfaults, and then deletes itself upon execution (Intel MacOS only)

### ISSUE THREAD

**Issue by milljm** [git-lfs/git-lfs#5907]
**Describe the bug**
This may be due to Conda-Forge (as that is where I am obtaining git-lfs). But I am posting here, and I will link a like-issue on git-lfs-feedstock.

conda-forge issue ref: https://github.com/conda-forge/git-lfs-feedstock/issues/51

**To Reproduce**
While on an Intel Mac, with Conda installed:
```bash
❯ conda create -n testing git-lfs
❯ conda activate testing
❯ git-lfs --version
zsh: killed     ./git-lfs --version
❯ which git-lfs
git-lfs not found
```

More information and steps are available on the issue I referenced.

**System environment**
```pre
❯ uname -a
Darwin cheesegrater1 23.5.0 Darwin Kernel Version 23.5.0: Wed May  1 20:09:52 PDT 2024; root:xnu-10063.121.3~5/RELEASE_X86_64 x86_64
```

**Output of `git lfs env`**
Not possible, as it segfaults with the current version. However, if I use the last previous version:
```bash
❯ conda search git-lfs
<trimmed>
git-lfs                        3.4.1      h694c41f_0  conda-forge         
git-lfs                        3.5.1      h694c41f_0  conda-forge  <----- this one works       
git-lfs                        3.5.1      hac5c5a4_1  conda-forge  
❯ conda create -n testing git-lfs=3.51=h694c41f_0
❯ conda activate testing
```

```pre
❯ git lfs env
git-lfs/3.5.1 (GitHub; darwin amd64; go 1.21.7; git e237bb3a)
git version 2.39.3 (Apple Git-146)

LocalWorkingDir=
LocalGitDir=
LocalGitStorageDir=
LocalMediaDir=lfs/objects
LocalReferenceDirs=
TempDir=lfs/tmp
ConcurrentTransfers=1
TusTransfers=false
BasicTransfersOnly=false
SkipDownloadErrors=false
FetchRecentAlways=false
FetchRecentRefsDays=7
FetchRecentCommitsDays=0
FetchRecentRefsIncludeRemotes=true
PruneOffsetDays=3
PruneVerifyRemoteAlways=false
PruneVerifyUnreachableAlways=false
PruneRemoteName=origin
LfsStorageDir=lfs
AccessDownload=none
AccessUpload=none
DownloadTransfers=basic,lfs-standalone-file,ssh
UploadTransfers=basic,lfs-standalone-file,ssh
GIT_EXEC_PATH=/Library/Developer/CommandLineTools/usr/libexec/git-core
git config filter.lfs.process = "git-lfs filter-process"
git config filter.lfs.smudge = "git-lfs smudge -- %f"
git config filter.lfs.clean = "git-lfs clean -- %f"
```
The output of running `git lfs env` as a code block.

**Additional context**

I am not sure if this is a Conda-Forge issue, or GIT-LFS issue.

**Comment by chrisd8088** [comment]
This sounds like an interesting problem!

I confess I'm unfamiliar with Conda Forge, but it sounds like it is perhaps now building Git LFS binaries itself instead of bundling the downloads we provide.  As of just a couple of days ago, commit conda-forge/git-lfs-feedstock@cebd41932f9d08cb8c97787b4de66ac8ce1da593 seems like it may have made that change.

Is it possible that it's building them only for ARM64 platforms (i.e., the Apple Silicon M-series of CPUs) and you're trying to run it on an Intel Mac?

Your `uname -a` output ends with `x86_64`, which implies you have an Intel CPU; otherwise it would say `arm64`.

I'd suggest talking to the Conda Forge team to see if they can provide a build for macOS on AMD64 (i.e., `x86_64`) platforms.  If not, we offer both from our release download [page](https://github.com/git-lfs/git-lfs/releases).  You'd want the "Darwin AMD64" one, I believe.

**Comment by milljm** [comment]
It looks like they might be cross-compiling for the Intel Mac platform maybe (using Apple Si).

I'll certainly build git-lfs on one of our native Intel Macs, and report back. At the very least, this will show which party is responsible. Cheers!

**Comment by milljm** [comment]
Having issues compiling using conda-forge's recipe. But I can confirm the release you have available is just fine. So I am going to close this.

Release I downloaded:
https://github.com/git-lfs/git-lfs/releases/download/v3.5.1/git-lfs-darwin-amd64-v3.5.1.zip
