### ISSUE TITLE
Windows uninstaller freeze!

### ISSUE THREAD

**Issue by ve3** [git-lfs/git-lfs#835]
1. Download Git lfs
2. double click to install. default path is my desktop.
3. don't run command that alert on install done.
4. there are 2 files git-lfs.exe and git-lfs-uninstaller.exe. now i seems to don't want it. i want to delete it.
5. right click on git-lfs-uninstaller.exe and run as admin because double click won't work.
6. everything on desktop freezed. can't right click. can't delete file. and can't find where is this file in task manager.

are these files safe?

**Comment by technoweenie** [comment]
That uninstaller is generated by [nsis](http://nsis.sourceforge.net/Main_Page). I want to look at using another windows installer toolkit for future versions though.

There's nothing weird in the [uninstall process](https://github.com/github/git-lfs/blob/b0318b25350b9abfe56af0afb01913a9b2ed56a4/script/nsis/installer.nsi#L61-L67). It just deletes `git-lfs.exe` from your system.

**Comment by ttaylorr** [comment]
Hi @ve3, can you confirm whether this is still happening? I am inclined to close this issue, since it is quite old and we haven't received any reports of similar behavior since.

I am going to close this issue for now, but please do not hesitate to leave a comment here if this issue persists for you, and I'd be happy to dive in further.
