### ISSUE TITLE
Add ref information to upload request

### ISSUE THREAD

**Issue by dluksza** [git-lfs/git-lfs#845]
Current upload request specification makes it hard to enforce branch based permissions in Gerrit. In order to enforce them Gerrit must first accept all incoming large files, then based on the pushed repository content either discard uploaded objects or keep them.

Such approach leads to waste of user's time, data transfer and server storage.

Adding destination ref information into upload request would solve this issue. Before sending back upload links Gerrit can check user access permissions to given ref, preventing or allowing large object upload.

Example upload request with ref information:

```
> POST https://git-lfs-server.com/objects/batch HTTP/1.1
> Accept: application/vnd.git-lfs+json
> Content-Type: application/vnd.git-lfs+json
> Authorization: Basic ... (if authentication is needed)
>
> {
>   "operation": "upload",
>   "ref": "refs/heads/master",
>   "objects": [
>     {
>       "oid": "1111111",
>       "size": 123
>     }
>   ]
> }
>
```

**Comment by technoweenie** [comment]
:+1: Seems legit. This is something that existing implementations can ignore.

**Comment by rubyist** [comment]
:+1: here too

**Comment by brabil** [comment]
Would be interested in such feature.

**Comment by technoweenie** [comment]
I just added this to my [Git LFS v1.2](https://github.com/github/git-lfs/issues/844) list. Now since it's a  simple addition that shouldn't affect things, it's likely it'll be in the next 1.1.x release. It really depends on how busy I am, and whether anyone else contributes the code instead :) Anyone that comments on this issue will get pinged on the pull request (unless you ask me not to).

**Comment by ttaylorr** [comment]
This was implemented by @technoweenie in https://github.com/git-lfs/git-lfs/issues/2712.
