### ISSUE TITLE
Commited binary file, can not rebase, checkout or hard reset

### ISSUE THREAD

**Issue by shuhrat** [git-lfs/git-lfs#884]
Hi all!
In our project there is a `git-lfs` tracked folder with binary files. 
One of my colleague who has no git-lfs on his system commited actual binary file to the `dev`.

Here is the story:
- He commited binary file
- `pre-push` hook did not allow him to push
- He installed `git-lfs`, so hook showed green light and he pushed changes to the remote

Annoying thing is that, anyone who rebased from remote now have a file on stage, file cannot be removed, tried commands:
- `git reset --hard @`
- `git checkout -- junk-file.png`

no success, file is still in working directory

![checkout](https://cloud.githubusercontent.com/assets/104213/11561997/181aa6ec-99dc-11e5-9b0c-2a11e28f41c6.png)
![reset](https://cloud.githubusercontent.com/assets/104213/11561998/181af386-99dc-11e5-80a9-fbbf20a668f4.png)

---

As a workaround
1. Reverted that badass commit
2. Removed `git-lfs` configurations from `.gitconfig`
3. Rebased
4. Turned back configurations to `.gitconfig`

**Comment by technoweenie** [comment]
Hey @shuhrat, I was just troubleshooting a case just like this, and gave the same workaround. You say your colleague doesn't have LFS installed, but the `pre-push` prevented his push initially. Was this Git LFS's hook, or a custom one your project uses? There's been some discussion in #867 and the [git lfs chat](https://gitter.im/github/git-lfs) about this issue.

I think what's happening is that Git LFS keeps updating the binary file to an LFS object. Running `git status` makes it check to see if files are updated. File patterns in `.gitattributes` will tell `git status` to run them through the Git LFS clean filter, causing it to change. This is why temporarily disabling Git LFS is a workaround.

**Comment by shuhrat** [comment]
We use [git-hooks-js](https://github.com/tarmolov/git-hooks-js)
I just made `web4/.githooks/pre-push/git-lfs` file with some modifications
```bash
#!/usr/bin/env bash
set -e

command -v git-lfs >/dev/null 2>&1 || {
    echo -e "\n\n\x1B[31mProject is configured for Git LFS but 'git-lfs' was not found on your path.\x1B[0m"
    echo -e "For more information see documentation\n"
    exit 1
}

git lfs pre-push "$@"
```

**Comment by technoweenie** [comment]
That is a really cool hack. With that, I'd feel comfortable doing more with hooks.

**Comment by shuhrat** [comment]
@technoweenie is there any recommendations for `{pre-commit,push}` hook to prevent such annoying events?

**Comment by technoweenie** [comment]
None that I've seen, but I'd love to see one for Git LFS.

**Comment by RagtagShawn** [comment]
Anybody know if this issue is going to actually get fixed or are workarounds the only solution?

This is basically a problem for any repo that has been around a while and started using LFS in the middle of the repos life time.  If any user goes back to an old revision they would get LFS trying to auto modify their files on the old revisions before they were being tracked by LFS.

Why does LFS modify files before a commit has been done?  The whole point is for remote storage for large files but if the file is not being committed then why make it an LFS file if it was not one already?

I am not an expert Git user so maybe there is something I don't understand, but I do know debugging these issues for remote team members who are Git newbs is a huge PIA.

**Comment by shuhrat** [comment]
We solved this issue with such pre-commit hook

```bash
#!/usr/bin/env bash

set -e

binary_files=""

changed_files=$(git diff --cached --name-only --diff-filter=ACM)

lfs_files=$(echo $changed_files | xargs git check-attr filter | grep 'filter: lfs$' | sed -e 's/: filter: lfs//')

for file in $lfs_files; do
    soft_sha=$(git hash-object -w $file)
    raw_sha=$(git hash-object -w --no-filters $file)

    if [ $soft_sha == $raw_sha ]; then
        binary_files="$file\n$binary_files"
    fi
done

if [[ -n "$binary_files" ]]; then
    echo "Achtung!"
    echo "----------"
    echo "You tried to commit binary files:"
    echo -e "\x1B[31m$binary_files\x1B[0m"
    echo "Revert your changes and commit those files with git-lfs!"
    echo "----------"
    exit 1
fi

exit 0
```

**Comment by ttaylorr** [comment]
> Anybody know if this issue is going to actually get fixed or are workarounds the only solution?

It is not possible to fix this entirely, since there is nothing that we can do to prevent issues like this if Git LFS is not installed properly. That said, there now exists a command `git lfs migrate import`, which allows for easy history-rewriting such that these erroneous commits can be rewritten correctly.
