### ISSUE TITLE
Git LFS doesn't work with npm install

### ISSUE THREAD

**Issue by brynn-mahsman** [git-lfs/git-lfs#899]
When I run `npm install --save git+ssh://git@github.com:bmahsman/bubblegum.git`, npm checks out the text files that git lfs puts in place of the actual assets. It appears npm isn't using my local user account's `~/.gitconfig`, i.e. the filters aren't being used and git-lfs is not being executed.

The issue could be with npm, but I wonder if `git lfs install` only sets up git lfs for the current user, while `npm install` is using some kind of global settings for all users. I detail the issue more in [this question](http://superuser.com/questions/999556/how-do-you-setup-npm-to-install-from-a-github-repository-that-uses-git-lfs), which no one has answered after a month. Any help is appreciated.

**Comment by bmahsman** [comment]
I made an issue on npm as well. https://github.com/npm/npm/issues/10857

**Comment by technoweenie** [comment]
Git LFS doesn't understand the `git+ssh` protocol. You can use `git@github.com:bmahsman/bubblegum.git` instead.

**Comment by bmahsman** [comment]
After poring over the output from `git` and `npm` with `export GIT_TRACE=1` and `npm config loglevel verbose`, I believe I have figured out how to get this to work, at least with GitLab (I have since moved from GitHub to GitLab, which also supports Git LFS).

Step 1. Inside of your repository, run the following command (replace `bubblegum`) and then commit the resulting `.gitconfig` and push:
```
$ git config -f .gitconfig lfs.url https://gitlab.com/brynn.mahsman/bubblegum.git/info/lfs
```

Step 2. In the directory in which you want to `npm install` your project, run for example:
```
$ npm install -S https://gitlab.com/brynn.mahsman/bubblegum.git
```

The `.gitconfig` you commit to the repository allows the git commands used by `npm install` know what `lfs.url` to use. I'm not sure if this solution only masks the fact that `npm install` can't figure out the `lfs.url` without you explicitly specifying it in `.gitconfig`. In other words, when I run the command `git clone https://gitlab.com/brynn.mahsman/bubblegum.git`, `git` somehow knows the `lfs.url` even if I don't have the `.gitconfig` in the repository. Would someone please enlighten me as to whether this is something `npm install` should be able to do without having to write this `.gitconfig`?

**Comment by technoweenie** [comment]
> note: For this to work with GitHub, it would appear that the lfs.url to use is: https://api.github.com/lfs/<user or organization>/<repository name>, e.g.

If your git host supports LFS properly, the LFS endpoint should always be your git remote with a "/info/lfs" suffix. You should only have to configure `lfs.url` if your LFS service is hosted separately from your Git service.

GitHub's lfs-authenticate command over SSH does return that "api.github.com" url, but `https://github.com/brynn.mahsman/bubblegum.git/info/lfs` works just fine too.

You can run `git lfs env` to see what url it will attempt to use.

```
$ git lfs env
git-lfs/1.1.0 (GitHub; darwin amd64; go 1.5.1; git fbbfd7d)
git version 2.5.4 (Apple Git-61)

Endpoint=https://github.com/github/git-lfs.git/info/lfs (auth=none)
Endpoint (dev)=http://github.dev/technoweenie/whatever.git/info/lfs (auth=none)
```

**Comment by bmahsman** [comment]
Do you have any idea why `npm install` does not have the proper `lfs.url` on its own without having to tell it explicitly with a `.gitconfig` in the repository?

I noticed that when you give `npm install` a repository it first makes a bare clone with `--mirror` in its cache directory, and then attempts to make a non-bare clone from that, which then is the basis for the files it installs to `node_modules/bubblegum/`.

Is there something about creating a bare mirror on the local filesystem that makes it lose the ability for your Git host to report the correct `lfs.url`?

**Comment by technoweenie** [comment]
Git LFS replaces pointers on checkout to the working directory. I don't think bare clones will do anything LFS related. If npm wants to support LFS, they'd have to download the actual objects manually. Git LFS doesn't really have any convenient commands for it, but they could be added if npm wanted to add support.

**Comment by bmahsman** [comment]
Thanks. In that case, I believe this is now entirely in npm's court. I'll make an issue in their project and see if they want to support it. The `.gitconfig` workaround should suffice for now.

**Comment by technoweenie** [comment]
> I noticed that when you give npm install a repository it first makes a bare clone with --mirror in its cache directory, and then attempts to make a non-bare clone from that, which then is the basis for the files it installs to node_modules/bubblegum/.

Ok, I think I get what's happening, and why you need the `.gitconfig`:

The first repo is a clone from a remote git host. But since it's a bare clone, LFS is not invoked at all. The second repo is a clone of the bare repo. Its `origin` remote is some local file path, and not a remote git host. That's why you need the `.gitconfig`.

Perhaps the client could detect this, and look at the config of the repo's local `origin` to get the original remote git host?

**Comment by feugy** [comment]
Hi there.

**Although this problem is on npm side, I post here a workaround for other users**

We got the same problem here, but workaround provided by zxcpoiu didn't work due to authentication (we're using a private repo).

After some research on [Git Enterprise Doc](https://help.github.com/enterprise/2.7/admin/guides/installation/git-large-file-storage-on-github-enterprise/), we found that providing a `.lfsconfig` file on the repo that has lfs items solved the issue:

```
[remote "origin"]
    lfsurl = ssh://git@github.com/user/repo.git
```

**Comment by pjho** [comment]
@feugy champion! Cheers for that. 

For anyone else on bitbucket I needed to drop the `ssh://` to get that working so:

```
[remote "origin"]
    lfsurl = git@bitbucket.org:org-name/repo-name.git

**Comment by bk2204** [comment]
From seeing this message, it sounds like you're trying to use a local Windows path to clone, which won't work.  If you're using the latest `master`, you can instead specify a file URL (not a local path), like this: `file:///c%3a/Some/Path/Component/Here`.  This feature isn't in 2.8.0, but it should be in 2.9.0 when that's released.

**Comment by bk2204** [comment]
Could you please open a new issue for this, then, including the information requested in the CONTRIBUTING file?  This sounds like a different issue than this one.
