### ISSUE TITLE
How to remove LFS completely in my repository?

### ISSUE THREAD

**Issue by hh123okbb** [git-lfs/git-lfs#910]
Download LFS tracked files always fail. The log shows "dial tcp: i/o timeout". Maybe the cloud service used by LFS is unsuitable for me (A Chinese guy).

I guess I wouldn't use LFS anymore. How could I remove LFS in my repository?

**Comment by Aorjoa** [comment]
Cloud you try `git lfs uninit`?

**Comment by jhessin** [comment]
Yes but how do I remove it for good?

**Comment by technoweenie** [comment]
Probably use `git filter-branch` to replace lfs pointers in your history with the actual data. There's no automated tool in LFS for this.

**Comment by alph486** [comment]
@technoweenie I feel like if I'm going to be ping'd via email to upgrade and purchase space if I tried the feature I should be able to easily delete things. If there's not, I feel there should definitely be a documented workaround to opt out of this otherwise paid feature. Maybe this is a feature request.

**Comment by lstagner** [comment]
I would also like to know how to do this.

I ran `git lfs uninstall`, deleted the large file and `.gitattributes` file it created, and commited the changes but it still shows that I am using some storage.

How can I make my repo (internals and all) look like I never install `git-lfs` (I don't care about changing history)

**Comment by Henry0422** [comment]
OMG, I already ran: `git lfs uninstall`

And it said: `C:\Users\hanr\GitHub\SGMPy [v0.1.1 = +7 ~1 -1 !]> git lfs uninstall
Global Git LFS configuration has been removed.
open C:\Users\hanr\GitHub\SGMPy\.git\hooks\pre-push: The system cannot find the
file specified.`

But I can still check the version.... `C:\Users\hanr\GitHub\SGMPy [v0.1.1 = +7 ~1 -1 !]> git lfs ver
git-lfs/1.2.0 (GitHub; windows amd64; go 1.6.1; git 9bd3b8e)`

I also would like to know how to make my repo look like I never install git-lfs.

Thanks.

**Comment by andyneff** [comment]
@alph486 The pay feature you are referring to is probably a specific server implementation, not a client detail (say like github.com's lfs server or bitbitbucket.org's lfs server, for example)

To answer the question, how to convert an local lfs repo into a non-lfs repo, I must first ask the question "What do you want to do about history?" Do you want all the previous versions to be converted, or only the most recent version?

FYI `git lfs uninstall` is not *really* going to directly help here.

### Convert tip only ###

If your only concern is the tip of the repo, you can probably remove the entries from `.gitattributes` and trigger the git index that every lfs file is different, and then add and commit those files. This is the same procedure in how you change the auto newlines in a git repo. I'll have to test this some, but [this](https://help.github.com/articles/dealing-with-line-endings/) might get you in the right direction. The only caviate is you don't want to reset the .gitattributes files first. So I might....

1. Modify .gitattribues and remove all the lfs settings
2. Save
3. `git add`
4. `git commit`
5. Then try the instructions in the link (I haven't tested this with lfs yet)

### Convert all of history ###

In issue #326, we found a number of (**WARNING** SLOW) `git filter-branch` techniques that will ADD LFS files by rewriting  history I imagine the same procedure used [here](https://github.com/github/git-lfs/issues/326#issuecomment-104881826) can be used, only instead of `git lfs track` use `git lfs untrack`, and maybe if you are feeling a bit pedantic change the echo to say "Unadding" instead of "Adding"
Again, I haven't tested this yet, but I think it might work.

**Comment by Henry0422** [comment]
@andyneff 
Thank you :smiley:

**Comment by dbinoj** [comment]
Is it safe to remove .git/lfs after running 'git lfs uninstall' and following steps 1 through 9 in https://help.github.com/articles/remove-sensitive-data/ on all locations which ever used LFS? I still have considerable amount of data in that folder and I want it gone.

**Comment by uyouthe** [comment]
@Aorjoa thank you! `git lfs uninit` worked well for me.

**Comment by nateGeorge** [comment]
Hmm, I removed the files, did `git lfs uninstall`, deleted .gitattributes, did `git lfs prune`, pushed to the master, but it's still showing up in my billing as above quota.  What gives?

**Comment by donal** [comment]
> but it's still showing up in my billing as above quota. What gives?

@nateGeorge Hey Nate, you ask a good question. If you need LFS files purged from your GitHub.com account to free up storage against your quota, please get in touch with [GitHub Support](https://github.com/contact) and we'll be happy to help you.

**Comment by nateGeorge** [comment]
Thanks donal, for anyone else viewing this, FYI:

If you want to purge specific files, you'll need to provide the Git LFS object ID values of each file. The object ID is a 64 character string which you can view by running the following command on the local clone of your repository:

git lfs ls-files --long

Or you can delete the entire repo.

Still, Amazon S3 is much cheaper ($1.3/month for 50GB vs $5/month for github, and that's after you exhaust the free tier, which is 5GB vs github's 1GB) and in my opinion easier to use.

**Comment by jcppkkk** [comment]
[How to remove LFS completely in my repository]
[Undo git lfs migrate]
[git lfs untrack history]

I messed up my project's LFS setting (with `git lfs migrate --everything`) and try to restore files from LFS pointer in all commit history.

The goal fits the issue title, so i post my solution here in case any one need it.

**BACKUP your repository before trying this script !**
```sh
git filter-branch -f --prune-empty --tree-filter '
if [ -f .gitattributes ]; then 
	git rm .gitattributes
fi
find * -type f | while read FILE; do 
if head -2 "$FILE" | grep -q "^oid sha256"; then
	ref=$(cat "$FILE")
	echo -n "$ref" | git lfs smudge > "$FILE"
	git add "$FILE"
fi
done' --tag-name-filter cat -- --all
```

**Comment by lockywolf** [comment]
@jcppkkk 
Thanks for sharing the script, but I kind of still have some traces of git-lfs remaining in my repo.

Namely, when I run 
    git lfs ls-files
, I still see a whole list of files.

Also, my 
    cat .git/config

still has lines:
    [lfs "<repo-path>"]
        locksverify=false

Any suggestions on how to remove these as well?

**Comment by gastonmorixe** [comment]
I just removed .git folder and started over

**Comment by rasmuseeg** [comment]
I suggest the following:

`$ git lfs uninstall`

Now remove the .gitattributes

And proceed with the following steps for [Dealing with line endings](https://help.github.com/articles/dealing-with-line-endings/#refreshing-a-repository-after-changing-line-endings) but skip step 6

**Comment by ttaylorr** [comment]
Just want to reiterate this comment (https://github.com/git-lfs/git-lfs/issues/3026#issuecomment-457795501), which explains that `git lfs uninstall && git rm .gitattributes` _does not_ remove historical revisions of Git LFS objects in your history.

**Comment by hangtwenty** [comment]
Regarding solutions - similar to the filter-branch way, you can use BFG. 

`java -jar "$BFG_PATH" --delete-files ".gitattributes"` etc ... you may also want to do it for the actual LFS-tracked files (or just use `--strip-blobs-bigger-than` feature for that, may do the trick)

https://rtyley.github.io/bfg-repo-cleaner/

**Comment by ttaylorr** [comment]
> Regarding solutions - similar to the filter-branch way, you can use BFG.

Git LFS has a built-in tool that offers a similar feature set that support is offered for here, which is `git lfs migrate export`.

**Comment by mrgloom** [comment]
For me on mac os only `sudo git lfs uninstall --system` helped.

**Comment by dimmduh** [comment]
Easy way - download source zip, drop .gitattributes and start new repo

**Comment by benblo** [comment]
Here's the solution I ended up using: mirror-clone from original repo with LFS, export everything, mirror-push to a new non-LFS repo:
```
#!/bin/bash

remote_with_lfs=your_original_url               # your original repo, with LFS
remote_without_lfs=your_rewritten_url           # your new repo, rewritten without LFS; expected to be empty (just init'd), otherwise you need to force-push and risk a mess
git clone --mirror $remote_with_lfs migrated    # use --mirror or --bare, otherwise you'll need to track all branches before running export
cd migrated
git lfs migrate export --include="*" --everything
git push $remote_without_lfs --mirror           # pushes all branches AND tags: https://stackoverflow.com/a/49343086/322119
```
This will reinject all the large files' versions across the whole history.
This is exactly what I wanted, so I'm happy (I was afraid it was only gonna push new files at the head, losing history), but be warned that it rewrites history (which is why I'm pushing to a new, different repo).

**Comment by caozuba** [comment]
I used `git lfs pull` to download original file then `git lfs uninstall,` after that I removed the `.gitattributes` file and commit again.

**Comment by VilleMiekkoja** [comment]
> Cloud you try `git lfs uninit`?

Error: unknown command "uninit" for "git-lfs"

**Comment by m-truong** [comment]
"git-lfs uninit" doesn't seem to work for me. I think "git-lfs uninstall" and "git-lfs prune" might work?

**Comment by bk2204** [comment]
If you want to turn your repository from a repo with LFS files into one that doesn't have any LFS files, you should use `git lfs migrate export`.  Please see the manual page for instructions and examples.  `git lfs uninstall` doesn't remove the old LFS files from history, and `git lfs prune` is completely unrelated.

**Comment by afrixs** [comment]
> I just removed .git folder and started over

Surprisingly, even this step didn't work for me (`git add .` was still adding certain files to LFS)... After searching for a long time I found a `[filter "lfs"]` entry in `/etc/gitconfig` that I had to remove. Don't know how the entry appeared there and I would wonder where are other global configurations (e.g. tracked extensions) located or how to disable them (if I wanted to use lfs sometime but with other extensions)...

**Comment by afrixs** [comment]
@andyneff thanks for your answer. I'd like to ask how to solve this situation properly:

I create a new repo so it contains no history (and therefore there is no need for `git lfs migrate export` if I understand it well). Then I run `git lfs uninstall` just to make sure LFS hooks are not present (the command just produces an error because there is no LFS in the project). Then I create an empty file and `git add` it. After doing that `git lfs status` shows that the file is marked as LFS, which is what I don't want. I need this particular repo to remain LFS-less after adding files of any type, extension or size. What should I do to achieve this?

Here is the use-case:
```
~$ mkdir nonlfs_repo && cd nonlfs_repo && git init
Initialized empty Git repository in /home/matej/nonlfs_repo/.git/

~/nonlfs_repo$ git lfs uninstall
WARNING: error running /usr/lib/git-core/git 'config' '--includes' '--global' '--remove-section' 'filter.lfs': 'fatal: no such section: filter.lfs' 'exit status 128'
open /home/matej/nonlfs_repo/.git/hooks/pre-push: no such file or directory
Hooks for this repository have been removed.
Global Git LFS configuration has been removed.

~/nonlfs_repo$ touch empty.txt
~/nonlfs_repo$ git add .
~/nonlfs_repo$ git lfs status

Objects to be committed:

        empty.txt (LFS: e3b0c44)        # I need this to be 'Git:' instead of 'LFS:'

Objects not staged for commit:
```

**Comment by andyneff** [comment]
I'm trying to reproduce your behavior, and I'm not getting `LFS` like you are. Unfortunately, I'm not that familiar with the `git lfs status`. I'm more familiar with the `git lfs ls-files` command. Running that on "staged uncommited" in my test will not show the `empty.txt` file. I will show you what I did in a clean docker container.

```
# I added the PTRACE capability so you can practice with strace if you want
docker run -it --rm --cap-add SYS_PTRACE ubuntu:20.04
apt-get update
apt-get install -y git-lfs
# Notice I don't uninstall git-lfs next, there's no need for that step, I'll explain why below
mkdir nonlfs_repo
cd nonlfs_repo
git init
touch empty.txt
git add empty.txt
git lfs status
git lfs ls-files
```

My lfs status shows:

```
root@d25d414edd08:/nonlfs# git lfs status

Git LFS objects to be committed:

        empty.txt (Git: e3b0c44)

Git LFS objects not staged for commit:
```

You'll see nothing from `git lfs ls-files`.

git lfs will not "lfs a file" unless you add it to the tracking wildcard pattern via the `git lfs track` command. And this is controlled by the `.gitattributes` file, which should be local to your repo. And since you just ran `git init` the .gitattributes file should be non-existent, (same as empty). **My only remaining guess** is that you have some global (See https://stackoverflow.com/a/28027656/4166604 . You'll see an `strace` suggestion to track it down if you can't find it) `.gitattributes` files somewhere on your system, and you need to track down what that means, and remove the offender. If this is the case, note that unless you have a special circumstances, this file should have never been used for setting the git lfs filters in the first place.

Git attribute lines look like the following:

```
root@f4538ed518bd:/nonlfs# cat .gitattributes
*.lfs filter=lfs diff=lfs merge=lfs -text
```

Continuing on, what an lfs track file should look like:

```
git lfs track "*.lfs"
ls > foo.lfs
git add foo.lfs
git lfs status
git ls-files
```

Status shows:

```
root@d25d414edd08:/nonlfs# git lfs status

Git LFS objects to be committed:

        empty.txt (Git: e3b0c44)
        foo.lfs (LFS: c3a9e7b)

Git LFS objects not staged for commit:
```

Only `git lfs ls-files` will show:

```
c3a9e7b42e * foo.lfs
```

Now if you want to triple check everything?

```
git commit -m "blah"
git log --patch
```

Now you will see the "empty.txt" file is just a normal file, but they "lfs file" is a pre smudged lfs pointer, and will look like this in the log:

```
version https://git-lfs.github.com/spec/v1
oid sha256:c3a9e7b42e37bfed929344c49b622d9ddac68d6af63786c39fd065d33ab5cace
size 18
```

You can also view this pre-smudged lfs pointer using the `git show` command too

```
git show empty.txt
git show foo.lfs
```

`empty.txt` will be the actual file (empty in the case), and the `foo.lfs` will be the lfs pointer.

I hope this helps clarify somethings.

**Comment by afrixs** [comment]
Thank you very much for your express and elaborate response! Didn't know about the `strace` tool, it looks very useful for problem solving. It turned out that although `git lfs status` marked the `empty.txt` file as LFS in my example above, `git lfs ls-files` didn't list it and no `.git/lfs` directory was created after committing, so this didn't cause problems. However the problem I had in my real git repo turned out to be very silly: there appeared to be a `.gitattributes` file with the lfs filters in a subfolder of the repo, not in the topmost directory so I haven't noticed it before now. (The file was probably created when I played with lfs in the past)

**Comment by midaslefkowitz** [comment]
I wrote a [script](https://gist.github.com/midaslefkowitz/79f491ed991c5c610cd555cb3e6df282) that completely removes lfs from a git repo.  WARNING - it rewrites your history.
