### ISSUE TITLE
fetchinclude

### ISSUE THREAD

**Issue by AndrewJDR** [git-lfs/git-lfs#912]
Should the following:

```
 git lfs pull -I '**/*.a'
```

Pull down all .a files, even if they're in deeply nested directories? It doesn't seem to actually do that in my project, even though git lfs pull --help says fetchinclude supports "wildcard matching as per gitignore".

Thanks.

**Comment by ajohnson23** [comment]
After further investigation, it's clear that fetchinclude uses Go's filepath.Match, which does not support the double asterisk notation that gitinclude supports. While I didn't look thoroughly, there's a good chance there are other differences between filepath.Match semantics and gitignore semantics, as well.

At minimum, I think the documentation for fetchinclude should be changed not to say "wildcard matching as per gitignore", since this is incorrect.

Ideally, the gitignore semantics would actually be supported by git-lfs's fetchinclude/fetchexclude, because filepath.Match is fairly limited in comparison.

As it stands, I'll have to implement some workaround with git lfs ls-files and shell scripting to get the power I need.

**Comment by ajohnson23** [comment]
This may be of interest (MIT license):
https://github.com/bmatcuk/doublestar

Perhaps this could be used to implement double star matching for fetchinclude/fetchexclude in git-lfs.

**Comment by technoweenie** [comment]
I'd be interested in a patch using `doublestar` or something like it :+1:

**Comment by qwertzguy** [comment]
Yes, please fix the help message first though! That seems rather urgent as I also got tricked into believing the help message :disappointed:

**Comment by gogodave** [comment]
I don't even see filepath.Match constructs working.   If you have a directory named abc which contains files stored in lfs and do `git lfs pull -I 'a*' `, lfs matches nothing. But doing `git lfs pull -I abc` will match.

**Comment by ttaylorr** [comment]
Hi, I think that this issue is obsolete, since package `filepathfilter` has gone through not one, but _two_ major refactors since the time that this issue was last updated.

The pattern should now work in the format that you have given above, either with `**/*.jpg` or `*.jpg` (to match any file ending in `.jpg` anywhere in the file tree).

In the past I stated that this may change in the future, and the first one would work in the future while the second one would eventually be phased out. I've learned more about the wildmatch semantics (from Git's `wildmatch.c`), and I'm no longer convinced that this needs to be the case.

In another patch, we treat `*.jpg` by implicitly spelling it as `**/*.jpg`, because there is no directory separator in the original pattern. This may become the standard in the future, but I'd like to gather more opinions from the broader Git LFS community to see what to do before any final decision is made.

In any case, we have a while to decide, since the earliest we could make this change would be in v3.0.0.

In the meantime, I am going to close this issue for now, since it is fixed. If you have any problems with it in the future, please do let me know and I would be more than happy to take a look in a new issue. Thanks!
