### ISSUE TITLE
Workflow when reverting LFS tracked files

### ISSUE THREAD

**Issue by Klipi** [git-lfs/git-lfs#957]
I ran into trouble with a build server that doesn't yet support Git LFS. This basically meant that I needed to get LFS to untrack files that were already commited and pushed to LFS. The workflow to do so seems to require manually moving the original files back to the repository. This seems odd when the reverse (Git to Git LFS) is basically `git rm --cached <file>` -> `git add <file>` -> `git commit` as long as the tracking is set up correctly. Is the reverting flow a known issue and planned to be improved?

Related Issue: #641 
[Related StackOverflow question](http://stackoverflow.com/questions/35011366/move-git-lfs-tracked-files-under-regular-git/35064134#35064134)

**Comment by mrdomino** [comment]
I'd love to know about this as well. I initially used overly aggressive patterns for lfs in my repository, which led to lots of small vendored binary assets that don't change frequently getting sucked in. Because the smudge-based lfs workflow scales so poorly in number-of-files, it's now really hard to clone the repo without manual LFS involvement.

I'd like to fix this by just restricting the sets of files tracked, but there's no obvious way to move a subset of previously LFS-tracked files out of LFS.

**Comment by technoweenie** [comment]
We could add a command for that. But yes, that's the proper way to re-add a file. Works if you're going from git => lfs or lfs => git, as long as the .gitattributes is correct.

@mrdomino The current master has a `git lfs clone` command that improves the performance dramatically by wrapping `git clone` and adding hacks to get around some internal git limitations.

**Comment by tstephens619** [comment]
I made the same mistake of including several small graphics formats into my git lfs tracking list.  I was able to move this files back into git by doing the following

# Create a list of all of the files currently being tracked by git-lfs, filter out *.gz and *.rpm (I want to still track those extensions with git-lfs)
git lfs ls-files | grep -vE "\.gz|\.rpm$" | cut -d ' ' -f 3 > ~/temp/lfs-files.txt

# Stop tracking the small graphics files
git lfs untrack "*.tts"
git lfs untrack "*.bfx"
git lfs untrack "*.ttf"
git lfs untrack "*.xcf"
git lfs untrack "*.pkm"
git lfs untrack "*.png"

# Temporarily uninit git-lfs
git lfs uninit

# Use the file list to touch each file
cat ~/temp/lfs-files.txt | xargs touch

# git status will now show each file as modified

# Add the changes to git index (I did this via git gui)

# commit the changes and then re-init git-lfs
git commit
git lfs init

**Comment by devedse** [comment]
Is there  any way to do this on Windows? Since there is no 'touch' command?

**Comment by technoweenie** [comment]
All `touch` does is creates an empty file if it doesn't exist. Is there no equivalent for that? You could try running this in a Git Bash env on Windows, instead of Powershell or the cmd shell.

**Comment by devedse** [comment]
I managed to work around this issue by executing the following command:

git rm --cached -r .
git add .

**Comment by bootstraponline** [comment]
A built in command for reverting individual files, or list of files, would be awesome.

**Comment by ttaylorr** [comment]
One way to do this would be:

```bash
for file in $FILES_TO_REVERT; do
  git lfs untrack "$file";
  git rm --cached "$file";
  git add --force "$file";
done

git commit -m "..."
```

My preference would be not to add a command to Git LFS to the above effect, since it is possible in a number of different way with the porcelain commands provided by Git and Git LFS. If a number of people feel strongly about this and would prefer to have a command builtin to Git LFS to the above effect, I would be happy to resume discussion about this.

**Comment by krassik** [comment]
If I perform the same steps as @tstephens619 (for *.png files only)  but before and after the steps  

git lfs ls-files | grep png   

greps the same set of files, what is this indicative of? 
Does this mean, untracking did not work for me ?

**Comment by iperov** [comment]
git lfs is useless piece of shit. Don't use it.

**Comment by ggrrll** [comment]
mind that `git lfs uninit` is not supported any longer 

on git-lfs/3.4.0 (GitHub; linux amd64; go 1.20.6)
