### ISSUE TITLE
"Problem accessing" files with unicode characters in their names

### ISSUE THREAD

**Issue by Scratch-net** [git-lfs/git-lfs#987]
We have some files with unicode characters like 

> PB SCN 16 Odhrán.wav

and when cloning such a repository on windows git-lfs fails to access them
Here's the log. <skipped> reffers to some unnecessary path part

```
git-lfs/1.1.1 (GitHub; windows amd64; go 1.5.3; git 69d1419)
git version 2.7.0.windows.1

$ git-lfs.exe pull
....
Problem accessing "<skipped>_odhr\303\243\302\242n.wav"
...

GetFileAttributesEx "<skipped>_tom\303\243\302\242s.wav": The filename, directory name, or volume label syntax is incorrect.
goroutine 66 [running]:
github.com/github/git-lfs/lfs.Stack(0x0, 0x0, 0x0)
    C:/Users/techn/go/src/github.com/github/git-lfs/lfs/errors.go:557 +0x87
github.com/github/git-lfs/commands.logPanicToWriter(0x2b941c0, 0xc08244a048, 0x2b94528, 0xc082977920)
    C:/Users/techn/go/src/github.com/github/git-lfs/commands/commands.go:184 +0xf86
github.com/github/git-lfs/commands.logPanic(0x2b94528, 0xc082977920, 0x0, 0x0)
    C:/Users/techn/go/src/github.com/github/git-lfs/commands/commands.go:148 +0x428
github.com/github/git-lfs/commands.handlePanic(0x2b94528, 0xc082977920, 0x0, 0x0)
    C:/Users/techn/go/src/github.com/github/git-lfs/commands/commands.go:123 +0x55
github.com/github/git-lfs/commands.LoggedError(0x2b94528, 0xc082977920, 0x958120, 0x14, 0xc082ac3ea8, 0x1, 0x1)
    C:/Users/techn/go/src/github.com/github/git-lfs/commands/commands.go:73 +0x89
github.com/github/git-lfs/commands.checkoutWithChan(0xc082312cc0)
    C:/Users/techn/go/src/github.com/github/git-lfs/commands/command_checkout.go:183 +0x304
github.com/github/git-lfs/commands.checkoutFromFetchChan.func1(0xc082312cc0, 0xc082004560)
    C:/Users/techn/go/src/github.com/github/git-lfs/commands/command_checkout.go:78 +0x28
created by github.com/github/git-lfs/commands.checkoutFromFetchChan
    C:/Users/techn/go/src/github.com/github/git-lfs/commands/command_checkout.go:80 +0x440
```

**Comment by technoweenie** [comment]
Thanks for the report!

**Comment by technoweenie** [comment]
I replicated this on my Windows VM, but couldn't on my Mac laptop. But, I had another issue on my Mac, but only when using `git lfs pull`:

```
$ git status
## master...origin/master
?? "\"PB SCN 16 Odhr\\303\\241n.wav\""
```

So even if it worked, it's likely that it would've written the wrong file.

Here's what I _think_ is going on. If you have Git LFS configured with the default smudge filters, everything works. This is because git is passing the correctly-formatted filename to `git lfs smudge`.

However, if you enable `git lfs install --skip-smudge`, you have to run `git lfs pull` to download the LFS objects. It gets it's filenames through `git ls-tree` in [`lsTreeBlobs()`](https://github.com/github/git-lfs/blob/a2781ff9cd5c38d0662218412910cbd14d296ed7/lfs/scanner.go#L577). Here's what the command output looks like:

```
$ git ls-tree master -rl
100644 blob d899f6551a51cf19763c5955c7a06a2726f018e9      42	.gitattributes
100644 blob 4d343e022e11a8618db494dc3c501e80c7e18197     126	"PB SCN 16 Odhr\303\241n.wav"
```

Our Go code is parsing that to the literal filename of `"PB SCN 16 Odhr\303\241n.wav"`. Git LFS on the mac happily accepts this, downloads the file, and writes `"PB SCN 16 Odhr\303\241n.wav"`, instead of replacing `PB SCN 16 Odhrán.wav`.

```bash
$ ls -al
total 24
-rw-r--r--   1 rick  staff    4 Feb 19 10:41 "PB SCN 16 Odhr\303\241n.wav"
drwxr-xr-x   6 rick  staff  204 Feb 19 10:41 .
drwxr-xr-x  23 rick  staff  782 Feb 19 10:41 ..
drwxr-xr-x  14 rick  staff  476 Feb 19 10:42 .git
-rw-r--r--   1 rick  staff   42 Feb 19 10:41 .gitattributes
-rw-r--r--   1 rick  staff  126 Feb 19 10:41 PB SCN 16 Odhrán.wav
```

In this output, the original pointer is intact, using 126 bytes. The "large content" is literally just `wav\n`, which you can see in the bad file.

Based on all this, I'm going to look into the following fixes:

* Raise if `lsTreeBlobs()` returns a filename that doesn't exist in the working directory. Assuming a clean checkout, this should never happen. We don't want the lfs checkout process to create new files.
* Change `lsTreeBlobs()` so it uses the `-z` option. This produces more raw output with the real filename. It appears all on one line because lines are separated by a null byte.

```bash
$ git ls-tree master -rlz
100644 blob d899f6551a51cf19763c5955c7a06a2726f018e9      42	.gitattributes100644 blob 4d343e022e11a8618db494dc3c501e80c7e18197     126	PB SCN 16 Odhrán.wav
```

Notice the lack of quotes or unicode escape codes.

**Comment by technoweenie** [comment]
Fixed in #1016. Let me know if you still have problems with the current master branch, or the next Git LFS release (v1.1.2).

**Comment by andyli** [comment]
I've a similar issue, with another error message, using GitLab as remote repo. Using **Windows command prompt**:
```
>git clone https://gitlab.com/andyli/MR-Chatbot.git
Cloning into 'MR-Chatbot'...
remote: Counting objects: 4008, done.
remote: Compressing objects: 100% (1792/1792), done.
remote: Total 4008 (delta 2267), reused 3950 (delta 2216)
Receiving objects: 100% (4008/4008), 452.70 MiB | 5.81 MiB/s, done.

Resolving deltas: 100% (2267/2267), done.
Downloading Assets/Model_22E/Textures/Aluminium texture.png (1.89 MB)
"git-lfs smudge -- 'Assets/Model_22E/Textures/å±å¹å¿«ç§ 2016-10-18 ä¸å2.47.25.png'": git-lfs smudge -- 'Assets/Model_22E/Textures/å±å¹å¿«ç§ 2016-10-18 ä¸å2.47.25.png': No such file or directory
error: external filter git-lfs smudge -- %f failed -1
error: external filter git-lfs smudge -- %f failed
fatal: Assets/Model_22E/Textures/屏幕快照 2016-10-18 下午2.47.25.png: smudge filter lfs failed
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry the checkout with 'git checkout -f HEAD'
```

My git and git lfs versions:
```
git-lfs/1.4.4 (GitHub; windows amd64; go 1.7.3; git cbf91a9)
git version 2.10.1.windows.1
```

**Comment by technoweenie** [comment]
@andyli Can you create a sample repo with that same filename so we can test it? The png contents can be something different of course.

**Comment by andyli** [comment]
I've set the project as public, so I think you can directly do `git clone https://gitlab.com/andyli/MR-Chatbot.git`.

**Comment by PascalRean** [comment]
@andyli I have the same issue with accentued filenames. I use git lfs 1.4.4 with git 2.10.1.

Did you resolved this issue ?

Pascal.

**Comment by PascalRean** [comment]
I've just test with git 2.11.0. It's working !!!!

**Comment by ttaylorr** [comment]
Please feel free to create a new issue if the problem arrises again 👍
